### ISSUE TITLE
Waiting for watcher times out and fails BWC in 7.16 suite

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#81110]
The waiting for 3 watcher nodes in a partially upgraded cluster has caused numerous failures. 

Multiple upgrade tests have failed (seemingly) due to timing out for watcher to be available. 

For all the failures, a commonality is:

Many logging entries on the old node like:
```
java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.NamedDiff][index_template]
	at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:112) ~[elasticsearch-7.4.2.jar:7.4.2]
```
and
```
» [2021-11-29T15:28:50,675][WARN ][o.e.c.c.PublicationTransportHandler] [v7.6.1-2] unexpected error while deserializing an incoming cluster state
»  java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.NamedDiff][component_template]
```

Followed by many entries such as:
```
[2021-11-29T15:25:28,834][DEBUG][o.e.x.w.WatcherService   ] [v7.4.2-2] missing watcher index templates, not starting watcher service
```

This has failed upgrading from <7.6

**Build scans:**
https://gradle-enterprise.elastic.co/s/ut4mgi4xhjgiy/tests/:x-pack:qa:rolling-upgrade:v7.4.2%23twoThirdsUpgradedTest/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT/test%20%7Bp0=mixed_cluster%2F90_ml_data_frame_analytics_crud%2FStart%20and%20stop%20old%20outlier_detection%20job%7D

[7.4.2]: https://gradle-enterprise.elastic.co/s/ijen7stimdkx2
[7.0.1]: https://gradle-enterprise.elastic.co/s/tupfxl7ltc6t6
[7.3.0]: https://gradle-enterprise.elastic.co/s/yvfjs3lvxk4x2
[7.6.1]: https://gradle-enterprise.elastic.co/s/ijen7stimdkx2

**Reproduction line:**
`./gradlew ':x-pack:qa:rolling-upgrade:v7.4.2#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/90_ml_data_frame_analytics_crud/Start and stop old outlier_detection job}" -Dtests.seed=F85312FD66A3AAFE -Dtests.bwc=true -Dtests.locale=el-CY -Dtests.timezone=CTT -Druntime.java=8`

**Applicable branches:**
7.16

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dmixed_cluster/90_ml_data_frame_analytics_crud/Start%20and%20stop%20old%20outlier_detection%20job%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure in test setup: Failed to initialize at least 3 watcher nodes

  at __randomizedtesting.SeedInfo.seed([F85312FD66A3AAFE:70072D27C85FC706]:0)
  at org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.waitForWatcher(UpgradeClusterClientYamlTestSuiteIT.java:74)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:972)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

  Caused by: java.lang.AssertionError: 
  Expected: "started"
       but: was "stopped"

    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.junit.Assert.assertThat(Assert.java:923)
    at org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.lambda$waitForWatcher$0(UpgradeClusterClientYamlTestSuiteIT.java:70)
    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1123)
    at org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.waitForWatcher(UpgradeClusterClientYamlTestSuiteIT.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:972)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
    at java.lang.Thread.run(Thread.java:748)

```

**Comment by benwtrent** [comment]
Possibly related:

https://github.com/elastic/elasticsearch/issues/66837

**Comment by droberts195** [comment]
```
[2021-11-29T15:25:28,834][DEBUG][o.e.x.w.WatcherService   ] [v7.4.2-2] missing watcher index templates, not starting watcher service
```

also relates to this discussion: https://github.com/elastic/elasticsearch/pull/80937#discussion_r755032834

Although as that thread concluded there's no production problem with index creation with respect to removing the legacy index templates as soon as the master node is on 7.16 it is tripping up the test condition that's waiting for all watcher nodes to be ready.

However, this looks more urgent from the point-of-view of ensuring the 7.16 release is sound:

```
» [2021-11-29T15:28:50,675][WARN ][o.e.c.c.PublicationTransportHandler] [v7.6.1-2] unexpected error while deserializing an incoming cluster state
»  java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.NamedDiff][component_template]
```

If this is a new problem in 7.16 then surely it's a blocker for 7.16 release?  Does it mean the older nodes in the mixed version cluster cannot receive the latest cluster state because there's something that's unconditionally sending them component templates that they don't understand?  Or has this been a problem for a long time and nobody has noticed?  (It seems like it was only noticed by chance in this issue, as it's not the root cause of the test failures.)

**Comment by martijnvg** [comment]
I'm confused how errors like this can occur with component templates (and composable index templates):

```
[2021-11-30T23:28:26,300][WARN ][o.e.c.c.PublicationTransportHandler] [v7.4.0-2] unexpected error while deserializing an incoming cluster state |  
-- | --
  | »  java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.NamedDiff][component_template] |  
  | »  	at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:112) ~[elasticsearch-7.4.0.jar:7.4.0] |  
  | »  	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45) ~[elasticsearch-7.4.0.jar:7.4.0] |  
  | »  	at org.elasticsearch.cluster.NamedDiffableValueSerializer.readDiff(NamedDiffableValueSerializer.java:56) ~[elasticsearch-7.4.0.jar:7.4.0] |  
  | »  	at org.elasticsearch.cluster.NamedDiffableValueSerializer.readDiff(NamedDiffableValueSerializer.java:30) ~[elasticsearch-7.4.0.jar:7.4.0] |  
  | »  	at org.elasticsearch.cluster.DiffableUtils$MapDiff.<init>(DiffableUtils.java:406) ~[elasticsearch-7.4.0.jar:7.4.0] |  
  | »  	at org.elasticsearch.cluster.DiffableUtils$ImmutableOpenMapDiff.<init>(DiffableUtils.java:234) ~[elasticsearch-7.4.0.jar:7.4.0] |  
  | »  	at org.elasticsearch.cluster.DiffableUtils.readImmutableOpenMapDiff(DiffableUtils.java:127) ~[elasticsearch-7.4.0.jar:7.4.0] |  
  | »  	at org.elasticsearch.cluster.metadata.MetaData$MetaDataDiff.<init>(MetaData.java:873) ~[elasticsearch-7.4.0.jar:7.4.0] |  
  | »  	at org.elasticsearch.cluster.metadata.MetaData.readDiffFrom(MetaData.java:812) ~[elasticsearch-7.4.0.jar:7.4.0] |  
  | »  	at org.elasticsearch.cluster.ClusterState$ClusterStateDiff.<init>(ClusterState.java:883) ~[elasticsearch-7.4.0.jar:7.4.0] |  
  | »  	at org.elasticsearch.cluster.ClusterState.readDiffFrom(ClusterState.java:793) ~[elasticsearch-7.4.0.jar:7.4.0]
```

because [minimum support version is set to V_7_7_0](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/metadata/ComponentTemplateMetadata.java#L88). So a 7.4.0 node should never receive component template in the incoming cluster state?

**Comment by DaveCTurner** [comment]
> If this is a new problem in 7.16 then surely it's a blocker for 7.16 release?

I can reproduce this serialisation bug in 7.9.0 but not 7.8.0. It appears that it's (usually) not fatal, the cluster forms anyway. I believe this might be because it's only the diff mechanism which ignores `getMinimalSupportedVersion`, and subsequent cluster state updates will attempt a diff, fail due to an incompatible base version, and fall back to sending a full cluster state which is serialised correctly.

**Comment by DaveCTurner** [comment]
I opened https://github.com/elastic/elasticsearch/issues/81262 describing the issue with cluster state serialization, although there's still a number of open questions that I haven't had time to answer. It's unclear to me whether this is the cause of these test failures or not.

**Comment by DaveCTurner** [comment]
I also opened #81116 and #81230 to add assertions that will expose bugs of this nature sooner.

**Comment by droberts195** [comment]
> It's unclear to me whether this is the cause of these test failures or not.

They're not.  The cause of the test failures is that _sometimes_ in the 2/3rds upgraded cluster the newly upgraded master node deletes the legacy watcher index templates and then the single old node in the cluster treats that as meaning watcher isn't "ready".

So either we need to wait for _all_ the nodes to be on the latest version before deleting legacy watcher templates (which relates to the thread starting at https://github.com/elastic/elasticsearch/pull/80937#discussion_r755032834), or else the test framework needs modifying to only expect watcher nodes that are on the new version to be "ready".

It's only _sometimes_ because it happens when the master node is second to get upgraded out of the 3 nodes and the newly elected master is the previously upgraded node rather than the still-to-be-upgraded old node.

**Comment by droberts195** [comment]
Now we have both 7.16 and 7.17 branches this problem is causing 20+ build failures per day that cannot easily be muted because the problem is in a `@Before` method that applies to all X-Pack rolling upgrade tests.

Please can somebody adjust the definition of Watcher being "ready" in a mixed version cluster where the legacy Watcher index templates have been deleted.

**Comment by martijnvg** [comment]
I will mute all watcher test in xpack rolling upgrade qa module and comment out the `waitForWatcher()` before method.
This is a drastic measurement, but I don't see a short term solution here and the full bwc tests can't successfully  complete.

**Comment by jakelandis** [comment]
These rolling upgrade tests are failing because as of https://github.com/elastic/elasticsearch/pull/80937 (7.16.0) we remove some legacy templates that are no longer in use. However, older code (at least 7.8.0) r[equires those templates](https://github.com/elastic/elasticsearch/blob/7.8/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/WatcherIndexTemplateRegistry.java#L108) to [pass validation](https://github.com/elastic/elasticsearch/blob/7.8/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherLifeCycleService.java#L162) on shard allocation changes else it will stop watcher.  So what is happening here is once a node is upgraded to 7.16+ it is deleting the index template which in turn stops watcher. I will log an bug. 

The validation logic was changed a few times since 7.8.0 and [currently](https://github.com/elastic/elasticsearch/blob/7.16/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/WatcherIndexTemplateRegistry.java#L130) only looks for any watcher-history template which still exists so no issues here outside of a mixed cluster with a new version that removes these templates and old version that requires these templates.

I think the fix here is to simply revert the deletion of those templates and re-enable these tests here.   

(also note - there are some links on this issue to restart tests, but probably best to just focus this issue on the rolling upgrade tests and then re-evaulate the restart test failures)

**Comment by gmarouli** [comment]
Since this is related to versions < 7.16 it doesn't seem relevant anymore. The test on main currently is not muted and there haven't been any failures reported recently.
