### ISSUE TITLE
IllegalArgumentException: missing required setting [azure.client.xxxxx.key] for setting [azure.client.xxxxx.proxy.host]

### ISSUE THREAD

**Issue by dharada** [elastic/elasticsearch#81286]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14.2 (7.x)

**Plugins installed**: ["repository-azure"]

**JVM version** (`java -version`):  openjdk 16.0.2

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 20.04

**Description of the problem including expected versus actual behavior**:

"IllegalArgumentException: missing required setting [azure.client.xxxxx.key] for setting [azure.client.xxxxx.proxy.host]" happens as we cannot boot ES when the following condition.

**Steps to reproduce**:

To use [sas_token](https://www.elastic.co/guide/en/elasticsearch/plugins/7.14/repository-azure-client-settings.html#repository-azure-client-settings) to access Azure storage (**not to use [key](https://www.elastic.co/guide/en/elasticsearch/plugins/7.14/repository-azure-client-settings.html#repository-azure-client-settings)**)

 1. bin/elasticsearch-keystore add azure.client.secondary.account
 2. bin/elasticsearch-keystore add azure.client.secondary.sas_token
 3. (elasticsearch.yml) to use proxy.*
```
azure.client.secondary.proxy.host: xxx.xxx.xx.xxx
azure.client.secondary.proxy.type: http
azure.client.secondary.proxy.port: xxxx
```

but we get the following error as saying missing required setting `[azure.client.secondary.key]`.   I think it should be OK to use _sas_token_ instead of _key_ to use Azure repository with proxy.* settings.

![key-manual](https://user-images.githubusercontent.com/1519063/144550698-d159416a-198c-4903-90cb-ebca4310fd7f.png)

**Provide logs (if relevant)**:

```
[2021-12-03T10:46:22,445][ERROR][o.e.b.Bootstrap          ] [node-7142-9] Exception
java.lang.IllegalArgumentException: missing required setting [azure.client.secondary.key] for setting [azure.client.secondary.proxy.host]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:549) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:478) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:449) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:420) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.node.Node.<init>(Node.java:445) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.node.Node.<init>(Node.java:281) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:219) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:219) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:399) [elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) [elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116) [elasticsearch-cli-7.14.2.jar:7.14.2]
	at org.elasticsearch.cli.Command.main(Command.java:79) [elasticsearch-cli-7.14.2.jar:7.14.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) [elasticsearch-7.14.2.jar:7.14.2]
	Suppressed: java.lang.IllegalArgumentException: missing required setting [azure.client.secondary.key] for setting [azure.client.secondary.proxy.port]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:549) ~[elasticsearch-7.14.2.jar:7.14.2]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:478) ~[elasticsearch-7.14.2.jar:7.14.2]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:449) ~[elasticsearch-7.14.2.jar:7.14.2]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:420) ~[elasticsearch-7.14.2.jar:7.14.2]
		at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138) ~[elasticsearch-7.14.2.jar:7.14.2]
```

**Comment by PPACI** [comment]
I got a similar issue with the timeout settings
```
java.lang.IllegalArgumentException: missing required setting [azure.client.default.key] for setting [azure.client.default.timeout]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:578)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:507)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:477)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:447)
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:137)
	at org.elasticsearch.node.Node.<init>(Node.java:502)
	at org.elasticsearch.node.Node.<init>(Node.java:309)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.Command.main(Command.java:77)
```

* Using account key instead of sas_token works
* Removing `azure.client.default.timeout: 10s` from my `elasticsearch.yml` works as well
