### ISSUE TITLE
[CI] FileWatcherTests testSimpleFileOperations failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#81305]
It seems this test stated failing on Dec 1st

**Build scan:**
https://gradle-enterprise.elastic.co/s/d7426kw4dcfxg/tests/:server:test/org.elasticsearch.watcher.FileWatcherTests/testSimpleFileOperations

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.watcher.FileWatcherTests.testSimpleFileOperations" -Dtests.seed=B6EC439B4D4CE3D6 -Dtests.locale=sv -Dtests.timezone=Etc/GMT-13 -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.watcher.FileWatcherTests&tests.test=testSimpleFileOperations

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: iterable containing ["onFileChanged: test.txt"]
     but: no item was "onFileChanged: test.txt"

  at __randomizedtesting.SeedInfo.seed([B6EC439B4D4CE3D6:59621166A963CE02]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.watcher.FileWatcherTests.testSimpleFileOperations(FileWatcherTests.java:111)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by jakelandis** [comment]
It seems only be failing on Mac with Java 17 

Here are a few of the repo lines

```
./gradlew ':server:test' --tests "org.elasticsearch.watcher.FileWatcherTests.testSimpleDirectoryOperationsWithContentChecking" -Dtests.seed=6DE787CD475D316B -Dtests.locale=sq -Dtests.timezone=Africa/Kinshasa -Druntime.java=17

 ./gradlew ':server:test' --tests "org.elasticsearch.watcher.FileWatcherTests.testSimpleFileOperations" -Dtests.seed=B6EC439B4D4CE3D6 -Dtests.locale=sv -Dtests.timezone=Etc/GMT-13 -Druntime.java=17

 ./gradlew ':server:test' --tests "org.elasticsearch.watcher.FileWatcherTests.testSimpleFileOperations" -Dtests.seed=A668DF84F164BD3A -Dtests.locale=vi-VN -Dtests.timezone=Australia/Broken_Hill -Druntime.java=17

./gradlew ':server:test' --tests "org.elasticsearch.watcher.FileWatcherTests.testSimpleFileOperations" -Dtests.seed=860C36A18D5B27B4 -Dtests.locale=hi-IN -Dtests.timezone=America/Chicago -Druntime.java=17
```

**Comment by dimitris-athanasiou** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/c5fwhkbcsu2ta/tests/:server:test/org.elasticsearch.watcher.FileWatcherTests/testSimpleFileOperations?top-execution=1

**Comment by droberts195** [comment]
Still failing on macOS with Java 17: https://gradle-enterprise.elastic.co/s/u5yiuehfhwel4/tests/:server:test/org.elasticsearch.watcher.FileWatcherTests/testSimpleFileOperations

**Comment by javanna** [comment]
Another one: https://gradle-enterprise.elastic.co/s/z4o34g7bqgodk/console-log?task=:server:test

**Comment by cbuescher** [comment]
Another one today on master, also a Darwin build: https://gradle-enterprise.elastic.co/s/azbqkmlx7arda
Is there any information we need to gather at this point from more failures or can I try doing a platform-specific mute here for now? @probakowski

**Comment by davidkyle** [comment]
Another Darwin/master combo failure 

https://gradle-enterprise.elastic.co/s/fj3vvouwtcb2c/tests/:server:test/org.elasticsearch.watcher.FileWatcherTests/testSimpleFileOperations?top-execution=1

Also `FileWatcherTests::testSimpleDirectoryOperationsWithContentChecking` failed with a similar error

```
java.lang.AssertionError: 
-- | --
  | Expected: iterable with items ["onFileChanged: test-dir/test2.txt"] in any order |  
  | but: no item matches: "onFileChanged: test-dir/test2.txt" in []
```

https://gradle-enterprise.elastic.co/s/fj3vvouwtcb2c/tests/:server:test/org.elasticsearch.watcher.FileWatcherTests/testSimpleDirectoryOperationsWithContentChecking?top-execution=1
