### ISSUE TITLE
Cannot enroll to nodes with publish addresses

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#81313]
In this scenario the initial node is started behind some IP translation, and the second, to-enroll, node has to use the initial node's published address to contact it.
Enrolling fails because the second node doesn't trust the certificate from the initial's node enroll endpoint. That certificate doesn't contain the published address in the SAN field.

In the following example the initial node runs inside a docker container, and the second node attempts to enroll from the host:
```
docker run -it -p 192.168.1.137:19300:9300 -p 192.168.1.137:19200:9200 -e "http.publish_host=192.168.1.137" -e "http.publish_port=19300" -e "transport.publish_host=192.168.1.137" -e "transport.publish_port=19200" -e "ES_JAVA_OPTS=-Xms2g -Xmx2g" elasticsearch:test
```
The generated node-enrollment token indeed contains the published address:
```
{"ver":"8.1.0","adr":["192.168.1.137:19300"], ...}
```
But enrolling the second node, from the docker host, fails with:
```
./bin/elasticsearch -v --enrollment-token eyJ2ZXIiOiI4LjEuMCIsImFkciI6WyIxOTIuMTY4LjEuMTM3OjE5MzAwIl0sImZnciI6ImRjYjMyMzkyZGU0Mzg3NGQyN2VhYThmZWM1ZDJmMmZhZjkxZDcwNTE1ZmIxZGRhNzlmNjFiZDhlMjE2YzY1ZjciLCJrZXkiOiJ4YktHZ0gwQm9jS1d0b2xRVmlQYzo0TW4zRm5FRlN1NmtjLWhKNF9XdEZRIn0=
warning: ignoring JAVA_HOME=/Users/albert/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home; using bundled JDK
warning: ignoring JAVA_HOME=/Users/albert/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home; using bundled JDK
warning: ignoring JAVA_HOME=/Users/albert/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home; using bundled JDK
Exception in thread "main" javax.net.ssl.SSLHandshakeException
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:200)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
        at org.elasticsearch.xpack.core.common.socket.SocketAccess.lambda$doPrivileged$0(SocketAccess.java:42)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.elasticsearch.xpack.core.common.socket.SocketAccess.doPrivileged(SocketAccess.java:41)
        at org.elasticsearch.xpack.core.security.CommandLineHttpClient.execute(CommandLineHttpClient.java:178)
        at org.elasticsearch.xpack.core.security.CommandLineHttpClient.execute(CommandLineHttpClient.java:135)
        at org.elasticsearch.xpack.security.cli.AutoConfigureNode.execute(AutoConfigureNode.java:289)
        at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
        at org.elasticsearch.cli.Command.main(Command.java:77)
        at org.elasticsearch.xpack.security.cli.AutoConfigureNode.main(AutoConfigureNode.java:144)
Caused by: java.security.cert.CertificateException
        at org.elasticsearch.xpack.core.security.CommandLineHttpClient$1.checkServerTrusted(CommandLineHttpClient.java:358)
        at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
        ... 24 more
```
From
```
openssl s_client -connect 192.168.1.137:19300 -showcerts 2> /dev/null | openssl x509 -text
```
I can see the published address is not in the SAN
```
 X509v3 Subject Alternative Name:
      DNS:localhost, IP Address:172.17.0.2, IP Address:127.0.0.1, DNS:3f73bd091c2d
```

@jkakavas I worked on the code that introduced this bug. Let me know if you want me to raise a fix.

**Comment by jkakavas** [comment]
> @jkakavas I worked on the code that introduced this bug. Let me know if you want me to raise a fix.

If you have the spare cycles to, that'd be great @albertzaharovits . Given the time and place where we calculate the SANs, I think we can only handle this case when the publish host is explicitly set by the user in either the config or an env var.
