### ISSUE TITLE
Prevent users from running elasticsearch-service-tokens as root

### ISSUE THREAD

**Issue by marius-dr** [elastic/elasticsearch#81378]
With the change to service tokens showing up as a warning in the upgrade assistant, this tool will get a lot more attention soon. 
Currently you are able to run it as root, which will make your Elasticsearch node not start with an access denied exception, since the service token file gets created with the wrong permissions.
There is no way to prevent the admins from running it with a different user than the one that ES will be run(since we don't know what they will run ES with), but we can prevent them from running as root since ES cannot start as root anyways. 
```
2021-12-02T19:27:19,226][INFO ][o.e.x.s.a.Realms         ] [localhost.localdomain] license mode is [trial], currently licensed security realms are [reserved/reserved,file/default_file,native/default_native]
[2021-12-02T19:27:19,236][INFO ][o.e.x.s.a.s.FileRolesStore] [localhost.localdomain] parsed [0] roles from file [/etc/elasticsearch/roles.yml]
[2021-12-02T19:27:19,559][ERROR][o.e.b.Bootstrap          ] [localhost.localdomain] Exception
java.lang.IllegalStateException: security initialization failed
        at org.elasticsearch.xpack.security.Security.createComponents(Security.java:571) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$18(Node.java:733) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at org.elasticsearch.node.Node.<init>(Node.java:747) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) [elasticsearch-cli-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.cli.Command.main(Command.java:77) [elasticsearch-cli-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
Caused by: java.lang.IllegalStateException: Failed to load service_tokens file [/etc/elasticsearch/service_tokens]
        at org.elasticsearch.xpack.security.authc.service.FileServiceAccountTokenStore.<init>(FileServiceAccountTokenStore.java:73) ~[?:?]
        at org.elasticsearch.xpack.security.Security.createComponents(Security.java:746) ~[?:?]
        at org.elasticsearch.xpack.security.Security.createComponents(Security.java:560) ~[?:?]
        ... 20 more
Caused by: java.nio.file.AccessDeniedException: /etc/elasticsearch/service_tokens
```

**Comment by ywangd** [comment]
We discussed this issue during team meeting and agreed that we should print warnings if the new file is created with different owner, mode and/or permissions than the `elasticsearch.yml` file. 

Currently the CLI tools do not prevent running as root. Many of them are actually safe to run as root because updating existing files, e.g. `users`, does not change the file owner and permission. This problem only happens when a new file must be created which is the case for the `elasticsearch-service-tokens` command and also a few other commands like `elasticsearch-syskeygen`, `elasticsearch-certutil`. We feel preventing running as root entirely is a breaking change that we don't like. Therefore we consider issuing warnings to be the right level of mitigation.
