### ISSUE TITLE
[CI] CCRIndexLifecycleIT testILMUnfollowFailsToRemoveRetentionLeases failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#81420]
**Build scan:**
https://gradle-enterprise.elastic.co/s/uzsijdzawn6y4/tests/:x-pack:plugin:ilm:qa:multi-cluster:follow-cluster/org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT/testILMUnfollowFailsToRemoveRetentionLeases

**Reproduction line:**
`./gradlew ':x-pack:plugin:ilm:qa:multi-cluster:follow-cluster' --tests "org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.testILMUnfollowFailsToRemoveRetentionLeases" -Dtests.seed=6CD3B71115DA6A51 -Dtests.locale=bg -Dtests.timezone=Asia/Baghdad -Druntime.java=8`

**Applicable branches:**
7.15

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT&tests.test=testILMUnfollowFailsToRemoveRetentionLeases

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://127.0.0.1:55582], URI [/follower/_ccr/follow?wait_for_active_shards=1], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [leader]","index_uuid":"_na_","index":"leader"}],"type":"index_not_found_exception","reason":"no such index [leader]","index_uuid":"_na_","index":"leader"},"status":404}

  at __randomizedtesting.SeedInfo.seed([6CD3B71115DA6A51:678FDF4194894279]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:110)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:82)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:78)
  at org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.testILMUnfollowFailsToRemoveRetentionLeases(CCRIndexLifecycleIT.java:506)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by gmarouli** [comment]
Since there haven't been any recent failures, I will close this issue.
