### ISSUE TITLE
[CI] TransformSurvivesUpgradeIT testTransformRollingUpgrade failing after version bump in 7.16 branch

### ISSUE THREAD

**Issue by breskeby** [elastic/elasticsearch#81576]
After bumping version in 7.16 branch the test in :x-pack:qa:rolling-upgrade:v7.16.0#oldClusterTest started failing.

**Build scan:**
https://gradle-enterprise.elastic.co/s/oe2jolamdpxum/tests/:x-pack:qa:rolling-upgrade:v7.16.0%23oldClusterTest/org.elasticsearch.upgrades.TransformSurvivesUpgradeIT/testTransformRollingUpgrade

**Reproduction line:**
`./gradlew ':x-pack:qa:rolling-upgrade:v7.16.0#oldClusterTest' -Dtests.class="org.elasticsearch.upgrades.TransformSurvivesUpgradeIT" -Dtests.method="testTransformRollingUpgrade" -Dtests.seed=4C2B72AC461F57B8 -Dtests.bwc=true -Dtests.locale=es-ES -Dtests.timezone=America/Porto_Acre -Druntime.java=8`

**Applicable branches:**
7.16

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.TransformSurvivesUpgradeIT&tests.test=testTransformRollingUpgrade

**Failure excerpt:**
```
java.lang.AssertionError: Transform index templates not found. The templates that exist are: [.deprecation-indexing-template, .ml-anomalies-, .ml-notifications-000002, .ml-state, .ml-stats, .monitoring-alerts-7, .monitoring-beats, .monitoring-es, .monitoring-kibana, .monitoring-logstash, .slm-history, .watch-history-13, 1, gen-tokens-old-cluster-template, ilm-history, invalid-tokens-old-cluster-template, logs, metrics, refresh-tokens-old-cluster-template, synthetics]

  at __randomizedtesting.SeedInfo.seed([4C2B72AC461F57B8:E3564715ED59847C]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.upgrades.TransformSurvivesUpgradeIT.lambda$waitForTemplates$3(TransformSurvivesUpgradeIT.java:103)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1123)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1096)
  at org.elasticsearch.upgrades.TransformSurvivesUpgradeIT.waitForTemplates(TransformSurvivesUpgradeIT.java:86)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:972)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by droberts195** [comment]
Fixed by #81571
