### ISSUE TITLE
PipelineConfigurationTests.testGetVersion failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#81804]
**Build scan**: https://gradle-enterprise.elastic.co/s/attcj4okt4yx2

**Repro line**: `gradlew ':server:test' --tests "org.elasticsearch.ingest.PipelineConfigurationTests.testGetVersion" -Dtests.seed=7CCCA4766532F76E -Dtests.locale=hi-IN -Dtests.timezone=Etc/GMT-13 -Druntime.java=17`

**Reproduces locally?**: Yes

**Applicable branches**: master

**Failure excerpt**:

```
org.elasticsearch.ingest.PipelineConfigurationTests > testGetVersion FAILED
    org.elasticsearch.ElasticsearchParseException: Failed to parse content to map
        at __randomizedtesting.SeedInfo.seed([7CCCA4766532F76E:83202F8B575990AC]:0)
        at app//org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:273)
        at app//org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:173)
        at app//org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:136)
        at app//org.elasticsearch.ingest.PipelineConfiguration.getConfigAsMap(PipelineConfiguration.java:87)
        at app//org.elasticsearch.ingest.PipelineConfiguration.getVersion(PipelineConfiguration.java:101)
        at app//org.elasticsearch.ingest.PipelineConfigurationTests.testGetVersion(PipelineConfigurationTests.java:109)

        Caused by:
        com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte 0xa5
         at [Source: (byte[])"{"version": ११६०६०३१४, "description": "blah", "_meta" : {"foo": "bar"}}
        "; line: 1, column: 15]
            at app//com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
            at app//com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
            at app//com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidInitial(UTF8StreamJsonParser.java:3570)
            at app//com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeCharForError(UTF8StreamJsonParser.java:3313)
            at app//com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3545)
            at app//com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2652)
            at app//com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:812)
            at app//org.elasticsearch.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:45)
            at app//org.elasticsearch.xcontent.support.AbstractXContentParser.findNonEmptyMapStart(AbstractXContentParser.java:348)
            at app//org.elasticsearch.xcontent.support.AbstractXContentParser.readMapSafe(AbstractXContentParser.java:315)
            at app//org.elasticsearch.xcontent.support.AbstractXContentParser.mapOrdered(AbstractXContentParser.java:270)
            at app//org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:271)
            ... 5 more
```

**Comment by danhermann** [comment]
This was resolved by the addition of `Locale.ROOT` to the string formatting call in https://github.com/elastic/elasticsearch/pull/81603

**Comment by droberts195** [comment]
This is also failing in 8.0 - see https://gradle-enterprise.elastic.co/s/3ppmzx2wdltlw/tests/:server:test/org.elasticsearch.ingest.PipelineConfigurationTests/testGetVersion

Please backport the fix to that branch

**Comment by jakelandis** [comment]
It looks like #81603 has been back ported: https://github.com/elastic/elasticsearch/pull/81603#issuecomment-1000489039 and the test passes locally for me. closing.
