### ISSUE TITLE
peer recovery stuck at TRANSLOG stage

### ISSUE THREAD

**Issue by LiuDui** [elastic/elasticsearch#81927]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14.2

**Plugins installed**:  [ ]

**JVM version** (`java -version`): 
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):  centos 7.x

**Description of the problem including expected versus actual behavior**:
Replica stuck at peer recovery several times when rolling restart. It can recovery if I move the shard to other node. 
```
GET _cat/recovery?active_only
log_perform-1 8  8.8m peer translog 11.70.213.168 1637811693000010032 11.70.213.179 1637811693000010232 n/a n/a 0 0 0.0% 0 0 0 0.0% 0 35000 35000 100.0%
log_perform-1 9  8.8m peer translog 11.70.213.168 1637811693000010032 11.70.213.179 1637811693000010232 n/a n/a 0 0 0.0% 0 0 0 0.0% 0 10000 10000 100.0%
log_perform-1 15 8.8m peer translog 11.70.213.143 1637811693000010132 11.70.213.179 1637811693000010232 n/a n/a 0 0 0.0% 0 0 0 0.0% 0 35000 35000 100.0%
log_perform-1 21 8.8m peer translog 11.70.213.143 1637811693000010132 11.70.213.179 1637811693000010232 n/a n/a 0 0 0.0% 0 0 0 0.0% 0 15000 15000 100.0%
```

**Steps to reproduce**: 
Problems cropped up occasionally several times. But I can't reproduce steadily.  Here's how I use:
1. Set up three nodes cluster.
2. create index which has settings as follow:
```
"settings": {
                "number_of_shards" :   30,
                "number_of_replicas" : 1,
                "index.translog.sync_interval": "5s",
                "index.translog.durability": "async",
                "index.routing.allocation.total_shards_per_node":"21"
        },
```
 3. bulk docs
 4. perform rolling restart.

**Provide logs (if relevant)**:
 The thread dump of master node:
```

"elasticsearch[1637811693000010032][generic][T#1]" #38 daemon prio=5 os_prio=0 tid=0x00007f70f480a800 nid=0xb471 in Object.wait() [0x00007f70e09fa000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Unknown Source)
        at org.elasticsearch.index.seqno.ReplicationTracker.waitForLocalCheckpointToAdvance(ReplicationTracker.java:1466)
        - locked <0x000000055a172360> (a org.elasticsearch.index.seqno.ReplicationTracker)
        at org.elasticsearch.index.seqno.ReplicationTracker.markAllocationIdAsInSync(ReplicationTracker.java:1184)
        - locked <0x000000055a172360> (a org.elasticsearch.index.seqno.ReplicationTracker)
        at org.elasticsearch.index.shard.IndexShard.markAllocationIdAsInSync(IndexShard.java:2462)
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$finalizeRecovery$33(RecoverySourceHandler.java:800)
        at org.elasticsearch.indices.recovery.RecoverySourceHandler$$Lambda$6550/871582995.run(Unknown Source)
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$runUnderPrimaryPermit$19(RecoverySourceHandler.java:372)
        at org.elasticsearch.indices.recovery.RecoverySourceHandler$$Lambda$6527/2130626299.run(Unknown Source)
        at org.elasticsearch.common.util.CancellableThreads.execute(CancellableThreads.java:82)
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.runUnderPrimaryPermit(RecoverySourceHandler.java:350)
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.finalizeRecovery(RecoverySourceHandler.java:800)
...
```

 I added some extra logs and saw some information in target node (The added log is a bit messy and hopefully describes the information):
![image](https://user-images.githubusercontent.com/26088415/146774826-a254d5f7-db96-4ada-bb9c-490139f5e562.png)

**Comment by LiuDui** [comment]
When replica shard send startRecovery request to primary, it takes a snapshot of the local index as`Store. MetadataSnapshot`, which is not guaranteed to be based on safeCommit. 
When opening InternEngine, the `trimUnsafeCommits(engineConfig)` operation is performed to delete the commit whose age is older than safeCommit.

Is there any mechanism to ensure that index files contained in the `Store. MetadataSnapshot`  will not be deleted after the `trimUnsafeCommits(engineConfig)` is executed when Phase1 can be skipped?

**Comment by LiuDui** [comment]
@dnhatn hi~Would you please have a look here? Appreciate much.

> 1. When opening InternEngine, the `trimUnsafeCommits(engineConfig)` operation is performed to delete the commit whose age is newer than safeCommit.
> 2. When replica shard send startRecovery request to primary, it takes a snapshot of the local index as`Store. MetadataSnapshot`, which is not guaranteed to be based on safeCommit. If `safeCommit.get().localCheckpoint == globalCheckpoint`, engine will not be opened before the request is sent, resulting `Store. MetadataSnapshot` containing unsafe commits which will be used to calculate whether phase1 needs to be skipped.
> 3. If phase1 is skipped, when Engine is opened on replica and perform `trimUnsafeCommits(engineConfig)`, some file will be delete.
> 
> Is there any mechanism to ensure that index files contained in the `Store. MetadataSnapshot` will not be deleted after the `trimUnsafeCommits(engineConfig)` is executed when Phase1 can be skipped?
