### ISSUE TITLE
[CI] EnrollmentProcessTests test20DockerAutoFormCluster failing

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#81999]
Recent failures all seem to be on `centos:8`, in case that's relevant.

**Build scan:**
https://gradle-enterprise.elastic.co/s/4pufysfkxptsa/tests/:qa:os:destructiveDistroTest.default-docker/org.elasticsearch.packaging.test.EnrollmentProcessTests/test20DockerAutoFormCluster

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.EnrollmentProcessTests&tests.test=test20DockerAutoFormCluster

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c docker exec --tty 30c11c84a6a5a102a9ff93c74104e517729bfd10500153eec57de16c426cf305 "/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token" -s node]
   result: exitCode = [69] stdout = [WARNING: Owner of file [/usr/share/elasticsearch/config/users] used to be [root], but now is [elasticsearch]
WARNING: Owner of file [/usr/share/elasticsearch/config/users_roles] used to be [root], but now is [elasticsearch]

ERROR: Failed to determine the health of the cluster.] stderr = []

  at __randomizedtesting.SeedInfo.seed([4BA666E236538CA1:BA9CF85FAB75DDE6]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.util.docker.DockerShell.run(DockerShell.java:49)
  at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:194)
  at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:174)
  at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:170)
  at org.elasticsearch.packaging.test.EnrollmentProcessTests.test20DockerAutoFormCluster(EnrollmentProcessTests.java:99)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by ywangd** [comment]
[Another one](https://gradle-enterprise.elastic.co/s/52fmbrt5thiea/tests/:qa:os:destructiveDistroTest.default-docker/org.elasticsearch.packaging.test.EnrollmentProcessTests/test20DockerAutoFormCluster?top-execution=1) on my PR CI today

**Comment by cbuescher** [comment]
This looks similar but is on from today on master. Repoening, maybe @pugnascotia can take a look if this looks similar and if so, why the above mentioned fix doesn't apply? 
https://gradle-enterprise.elastic.co/s/ddtq2eeailnjc

**Comment by jkakavas** [comment]
This means that we get an exception in https://github.com/elastic/elasticsearch/blob/537f371f348207e7c59d28162b61c3720e931d0c/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/tool/BaseRunAsSuperuserCommand.java#L213 . This probably means that we're asking the node for its health too quickly after it has started ( since it only happens occasionally ), and I'd bet we throw here: https://github.com/elastic/elasticsearch/blob/fc5a820da9d9b8ad4c885c6d90ce72363632088a/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/CommandLineHttpClient.java#L150

@pugnascotia any idea on a good waiting strategy here? We're executing a CLI tool against that node in docker and that CLI tool internally tries to determine the node health. Do we have "do this until you get something back for x retries but disregard Exceptions thrown" that I'm missing ?

**Comment by pugnascotia** [comment]
@jkakavas I'm confused about why it fails - when we run the container, we use `waitForElasticsearch()` to check that it's up. Feels like either the wait command isn't robust enough, maybe? Can we add more logging to help diagnose what's going on?

**Comment by jkakavas** [comment]
Yes, part of it is that when security is enabled we end up calling `waitForXpack()` which is just establishes a socket connection. We can do better now by capturing the auto-generated credentials from the stdout on startup in the cases where we want to test auto-configuration or by using the `ELASTIC_PASSWORD` env

**Comment by ywangd** [comment]
Happened today on 8.0: https://gradle-enterprise.elastic.co/s/yotpc5psqtwzi/tests/:qa:os:destructiveDistroTest.default-dockerUbi/org.elasticsearch.packaging.test.EnrollmentProcessTests/test20DockerAutoFormCluster?top-execution=1

**Comment by pugnascotia** [comment]
We're seeing failures in the archive test case too, and I think that part of the problem is the `expect` script that we use to run Elasticsearch. It has an `expect "Elasticsearch keystore password:"` line in the script, which will time out if the output isn't matched. ES is left running in the background regardless, but on a slow system it could cause Expect to bail before all the ES output is printed.
