### ISSUE TITLE
:libs:elasticsearch-geo:test fails due to SecurityManager

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#82035]
**Build scan**:
https://gradle-enterprise.elastic.co/s/mrhwevhayoeku/tests/overview?outcome=failed
**Repro line**:
?? ./gradlew :libs:elasticsearch-geo:test
**Reproduces locally?**:
no
**Applicable branches**:
8.0
**Failure history**:

failing since 21Dec
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Warsaw&tests.container=org.elasticsearch.geometry.RectangleTests&tests.sortField=FAILED&tests.test=classMethod&tests.unstableOnly=true
**Failure excerpt**:
```
java.lang.RuntimeException: unable to install test security manager
at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:180)
at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:241)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:488)
at java.lang.Class.forName(Class.java:467)
at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:631)
Caused by: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
at java.lang.System.setSecurityManager(System.java:416)
at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:164)
at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:241)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:488)
at java.lang.Class.forName(Class.java:467)
at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:631)
```

could be related to openjdk18 as all of the failurs in gradle enterprise history are saying that they run with that jdk?

**Comment by pgomulka** [comment]
it looks like we should run with `java.security.manager=allow` in that jdk
https://github.com/openjdk/jdk18/blob/dfb15c3e343974eb138ca1a8db3364cd2bac70a4/src/java.base/share/classes/java/lang/System.java#L2222

https://github.com/openjdk/jdk18/blob/dfb15c3e343974eb138ca1a8db3364cd2bac70a4/src/java.base/share/classes/java/lang/System.java#L395

**Comment by mark-vieira** [comment]
I think this is just a matter of backporting https://github.com/elastic/elasticsearch/pull/80957. @ChrisHegarty I think we'll need to backport https://github.com/elastic/elasticsearch/pull/80957 to the 8.0 and 7.17 branches if we want to support running on Java 18 there, yes?

**Comment by ChrisHegarty** [comment]
Yeap. Backports in progress.

**Comment by mark-vieira** [comment]
ping @ChrisHegarty just a friendly reminder on this one

**Comment by ChrisHegarty** [comment]
Thanks for the reminder. Backport to 8.0 went fine, but the 7.17 port is encountering test issues, which are proving difficult to diagnose.

**Comment by pgomulka** [comment]
since https://github.com/elastic/elasticsearch/pull/82053 is already merged I think we can close this one
