### ISSUE TITLE
YAML test failure "cat.shards/10_basic/Test cat shards output"

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#82151]
**Build scan**:  https://gradle-enterprise.elastic.co/s/cvatdzy4g77wu

**Repro line**:  `./gradlew ':rest-api-spec:yamlRestTest' --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT" -Dtests.method="test {yaml=cat.shards/10_basic/Test cat shards output}" -Dtests.seed=1751BA43AF68208E -Dtests.locale=ar-IQ -Dtests.timezone=Asia/Chita -Druntime.java=17` 

**Reproduces locally?**: no

**Applicable branches**: master

**Failure history**: https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Chicago&tests.container=org.elasticsearch.test.rest.ClientYamlTestSuiteIT&tests.sortField=FAILED&tests.test=test%20%7Byaml%3Dcat.shards/10_basic/Test%20cat%20shards%20output%7D&tests.unstableOnly=true

**Failure excerpt**:  
```
Exception
java.lang.AssertionError: Failure at [cat.shards/10_basic:95]: field [$body] was expected to match the provided regex but didn't	
Expected: ^$	
     but: was ".tasks 0 p STARTED   127.0.0.1 yamlRestTest-0\n"	
	at __randomizedtesting.SeedInfo.seed([1751BA43AF68208E:9F05859901944D76]:0)	
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:489)	
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)	
		•••
Caused by: java.lang.AssertionError: field [$body] was expected to match the provided regex but didn't	
Expected: ^$	
     but: was ".tasks 0 p STARTED   127.0.0.1 yamlRestTest-0\n"	
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
		•••
	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:64)	
	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)	
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:478)	
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)	
		•••
Output View rawDownload raw
[2021-12-31T01:00:42,291][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=cat.shards/10_basic/Test cat shards output] before test	
[2021-12-31T01:00:42,317][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] Stash dump on test failure [{	
  "stash" : {	
    "body" : ".tasks 0 p STARTED   127.0.0.1 yamlRestTest-0	
"	
  }	
}]
```

**Comment by joegallo** [comment]
Looks very similar to https://gradle-enterprise.elastic.co/s/hyt7g3srhqefa/tests/:rest-api-spec:yamlRestTest/org.elasticsearch.test.rest.ClientYamlTestSuiteIT/test%20%7Byaml=cat.indices%2F20_hidden%2FTest%20cat%20indices%20output%20for%20dot-hidden%20index%20and%20dot-prefixed%20pattern%7D?top-execution=1

**Comment by masseyke** [comment]
This looks like it has the same cause as e https://github.com/elastic/elasticsearch/issues/84765#issuecomment-1076873120.
