### ISSUE TITLE
[CI] RoleDescriptorTests testSerialization failing

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#82216]
**Build scan:**
https://gradle-enterprise.elastic.co/s/rszuztj2zglxw/tests/:x-pack:plugin:security:test/org.elasticsearch.xpack.security.authz.RoleDescriptorTests/testSerialization

**Reproduction line:**
`./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authz.RoleDescriptorTests.testSerialization" -Dtests.seed=D84C48900B786F5A -Dtests.locale=es-CL -Dtests.timezone=Canada/Atlantic -Druntime.java=8`

**Applicable branches:**
7.16

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.authz.RoleDescriptorTests&tests.test=testSerialization

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <Role[name=fWPnNBrlZHmsQXJKqNWqaQGKyykyTKWThZjpbEPW, cluster=[read_ccr], global=[], indicesPrivileges=[IndicesPrivileges[indices=[ZFeu,Rudm,xnkc,HjcM,xvWO], allowRestrictedIndices=[true], privileges=[read,manage,create_index,monitor], , query={ "match_all": {} }],], applicationPrivileges=[ApplicationResourcePrivileges[application=AoGoqwyuIx, privileges=[fOJdz,AAMDk], resources=[gXWHCjlT,XACQdsSw]],ApplicationResourcePrivileges[application=zSeLCgHFsFtH, privileges=[MpcRtekS], resources=[uMsUISiW,zJuOBTBz,tBdWczGw]],], runAs=[TSBUGKQB,NrnAIDen], metadata=[{PtJDXWag=107338494}]]>
     but: was <Role[name=fWPnNBrlZHmsQXJKqNWqaQGKyykyTKWThZjpbEPW, cluster=[read_ccr], global=[], indicesPrivileges=[IndicesPrivileges[indices=[ZFeu,Rudm,xnkc,HjcM,xvWO], allowRestrictedIndices=[false], privileges=[read,manage,create_index,monitor], , query={ "match_all": {} }],], applicationPrivileges=[ApplicationResourcePrivileges[application=AoGoqwyuIx, privileges=[fOJdz,AAMDk], resources=[gXWHCjlT,XACQdsSw]],ApplicationResourcePrivileges[application=zSeLCgHFsFtH, privileges=[MpcRtekS], resources=[uMsUISiW,zJuOBTBz,tBdWczGw]],], runAs=[TSBUGKQB,NrnAIDen], metadata=[{PtJDXWag=107338494}]]>

  at __randomizedtesting.SeedInfo.seed([D84C48900B786F5A:8C9429D82C2A52C6]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.security.authz.RoleDescriptorTests.testSerialization(RoleDescriptorTests.java:246)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by tvernum** [comment]
Interestingly, this only seems to reproduce on `7.16` and not `7.17`
It's almost certainly a result of #82180, but I wonder why it's only happening on that branch

**Comment by nik9000** [comment]
I got a 7.17 failure:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authz.RoleDescriptorTests.testSerialization" -Dtests.seed=662EC1EF0EC74506 -Dtests.locale=bg -Dtests.timezone=Asia/Jerusalem -Druntime.java=8
```

**Comment by jdconrad** [comment]
Also 7.17

https://gradle-enterprise.elastic.co/s/eyofpt4v3zz7c

**Comment by jkakavas** [comment]
This was resolved in https://github.com/elastic/elasticsearch/pull/82242
