### ISSUE TITLE
Let users know why they are seeing debug logs in 8.0.0 after upgrading from 6.8.20->7.17.0->8.0.0

### ISSUE THREAD

**Issue by bhavyarm** [elastic/elasticsearch#82263]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.0.0

**OS version** (`uname -a` if on a Unix-like system): darwin

**Description of the problem including expected versus actual behavior**: If user upgrades from 6.8.20->7.17.0->8.0.0 ES with both data and config folder - ES displays a bunch of debug logs which are not shown because of https://github.com/elastic/elasticsearch/pull/51459 starting 7.7.0 

This is how logs look. Can we please tell the user - this is because of the 6.8.20 config file?
```
2022-01-04T12:53:59,339][DEBUG][o.e.a.s.m.TransportMasterNodeAction] [Bhavyas-MacBook-Pro.local] unexpected exception during publication
org.elasticsearch.ResourceNotFoundException: component template matching [metrics-system.cpu@custom] not found
	at org.elasticsearch.action.admin.indices.template.get.TransportGetComponentTemplateAction.masterOperation(TransportGetComponentTemplateAction.java:86) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.admin.indices.template.get.TransportGetComponentTemplateAction.masterOperation(TransportGetComponentTemplateAction.java:30) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.executeMasterOperation(TransportMasterNodeAction.java:121) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:215) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:220) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:215) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:152) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:52) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:79) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:53) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:77) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.security.action.filt
```

**Comment by bhavyarm** [comment]
cc @DaveCTurner Thanks!
