### ISSUE TITLE
Indexing attachment via ingest attachment plugin shutdowns elasticsearch entirely

### ISSUE THREAD

**Issue by ivansorokinf** [elastic/elasticsearch#82354]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.2

**Plugins installed**: [ingest-attachment]

**JVM version** (`java -version`): bundled

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**: Indexing attachment via ingest attachment plugin shutdowns elasticsearch. Expected behaviour: returns error for broken or unparsable file.

**Steps to reproduce**:

 1. setup elasticsearch and ingest-attachment plugin
 2. try to index provided file from archive using ingest-attachment plugin
 3. elasticsearch is down

**Provide logs (if relevant)**:
```
fatal error in thread [elasticsearch[pc_name][write][T#2]], exiting
java.lang.StackOverflowError
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:207)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
        at org.apache.poi.hwpf.model.StyleSheet.createPap(StyleSheet.java:220)
```

It seems that this bug is on Apache POI side but it also heavily affects elasticsearch users so I decided to submit issue here as well.

[file.zip](https://github.com/elastic/elasticsearch/files/7838249/file.zip)

**Comment by akhilma-kore** [comment]
@ivansorokinf @elasticmachine Is this fixed I am facing the same error. Any help will be much appreciated.
