### ISSUE TITLE
[CI] Failure waiting to lock Gradle cache

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#82411]
**Build scan**: https://gradle-enterprise.elastic.co/s/pz364cg4yaixy

**Applicable branches**: 8.0

**Failure excerpt**:

```
  | [7.16.3] FAILURE: Build failed with an exception. |  
  | [7.16.3] |  
  | [7.16.3] * What went wrong: |  
  | [7.16.3] Execution failed for task ':distribution:archives:buildLinuxAarch64'. |  
  | [7.16.3] > A build operation failed. |  
  | [7.16.3]       Timeout waiting to lock Artifact transforms cache (/var/lib/jenkins/.gradle/caches/transforms-3). It is currently in use by another Gradle instance. |  
  | [7.16.3]   Owner PID: 3535 |  
  | [7.16.3]   Our PID: 244086 |  
  | [7.16.3]   Owner Operation: |  
  | [7.16.3]   Our operation: |  
  | [7.16.3]   Lock file: /var/lib/jenkins/.gradle/caches/transforms-3/transforms-3.lock |  
  | [7.16.3]    > Timeout waiting to lock Artifact transforms cache (/var/lib/jenkins/.gradle/caches/transforms-3). It is currently in use by another Gradle instance. |  
  | [7.16.3]      Owner PID: 3535 |  
  | [7.16.3]      Our PID: 244086 |  
  | [7.16.3]      Owner Operation: |  
  | [7.16.3]      Our operation: |  
  | [7.16.3]      Lock file: /var/lib/jenkins/.gradle/caches/transforms-3/transforms-3.lock |  
  | [7.16.3] |  
  | [7.16.3] * Try: |  
  | [7.16.3] > Run with --info or --debug option to get more log output. |  
  | [7.16.3] > Run with --scan to get full insights. |  
  | [7.16.3] |  
  | [7.16.3] * Exception is: |  
  | [7.16.3] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':distribution:archives:buildLinuxAarch64'. |  
  | [7.16.3] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38) |  
  | [7.16.3] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77) |  
  | [7.16.3] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55) |  
  | [7.16.3] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52) |  
  | [7.16.3] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204) |  
  | [7.16.3] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199) |  
  | [7.16.3] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66) |  
  | [7.16.3] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59) |  
  | [7.16.3] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157) |  
  | [7.16.3] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59) |  
  | [7.16.3] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53) |  
  | [7.16.3] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73) |  
  | [7.16.3] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52) |  
  | [7.16.3] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74) |  
  | [7.16.3] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402) |  
  | [7.16.3] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389) |  
  | [7.16.3] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382) |  
  | [7.16.3] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368) |  
  | [7.16.3] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127) |  
  | [7.16.3] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191) |  
  | [7.16.3] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182) |  
  | [7.16.3] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124) |  
  | [7.16.3] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64) |  
  | [7.16.3] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48) |  
  | [7.16.3] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) |  
  | [7.16.3] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) |  
  | [7.16.3] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61) |  
  | [7.16.3] 	at java.base/java.lang.Thread.run(Thread.java:831) |  
  | [7.16.3] Caused by: org.gradle.internal.operations.MultipleBuildOperationFailures: A build operation failed. |  
  | [7.16.3]     Timeout waiting to lock Artifact transforms cache (/var/lib/jenkins/.gradle/caches/transforms-3). It is currently in use by another Gradle instance. |  
  | [7.16.3] Owner PID: 3535 |  
  | [7.16.3] Our PID: 244086 |  
  | [7.16.3] Owner Operation: |  
  | [7.16.3] Our operation: |  
  | [7.16.3] Lock file: /var/lib/jenkins/.gradle/caches/transforms-3/transforms-3.lock
```

**Comment by breskeby** [comment]
likely related to us having inner and outer gradle builds. We probably need to use different gradle user homes for those.

**Comment by Luegg** [comment]
Another occurrence of the same issue: https://gradle-enterprise.elastic.co/s/7zszi2lwjmcns/console-log?task=:distribution:bwc:maintenance:buildBwcLinuxAarch64Tar#L649

**Comment by cbuescher** [comment]
I just saw one of these too: https://gradle-enterprise.elastic.co/s/ocrt77ddmhthk/console-log?anchor=4121

**Comment by slobodanadamovic** [comment]
Another one occurred today: https://gradle-enterprise.elastic.co/s/nkiv25f7fpchm/console-log?anchor=11503

**Comment by williamrandolph** [comment]
I got one today: https://gradle-enterprise.elastic.co/s/ou5jrffvbilbe/console-log?anchor=10595

**Comment by cbuescher** [comment]
One on `main` today: https://gradle-enterprise.elastic.co/s/l7klgcfwpmglo

**Comment by n1v0lg** [comment]
On `8.6` https://gradle-enterprise.elastic.co/s/rm4cmpyeuwjau

**Comment by craigtaverner** [comment]
Got this failure again today, this time on `8.6`: https://gradle-enterprise.elastic.co/s/af4msyfmlmtv6

```
  [8.5.4] FAILURE: Build failed with an exception. |  
-- | --
  | [8.5.4] |  
  | [8.5.4] * What went wrong: |  
  | [8.5.4] Execution failed for task ':libs:elasticsearch-x-content:generateProviderManifest'. |  
  | [8.5.4] > Error while evaluating property 'jars' of task ':libs:elasticsearch-x-content:generateProviderManifest' |  
  | [8.5.4]    > A build operation failed. |  
  | [8.5.4]          Timeout waiting to lock Artifact transforms cache (/var/lib/jenkins/.gradle/caches/transforms-3). It is currently in use by another Gradle instance. |  
  | [8.5.4]      Owner PID: 5970 |  
  | [8.5.4]      Our PID: 230147 |  
  | [8.5.4]      Owner Operation: |  
  | [8.5.4]      Our operation: |  
  | [8.5.4]      Lock file: /var/lib/jenkins/.gradle/caches/transforms-3/transforms-3.lock |  
  | [8.5.4]       > Timeout waiting to lock Artifact transforms cache (/var/lib/jenkins/.gradle/caches/transforms-3). It is currently in use by another Gradle instance. |  
  | [8.5.4]         Owner PID: 5970 |  
  | [8.5.4]         Our PID: 230147 |  
  | [8.5.4]         Owner Operation: |  
  | [8.5.4]         Our operation: |  
  | [8.5.4]         Lock file: /var/lib/jenkins/.gradle/caches/transforms-3/transforms-3.lock
```

**Comment by mark-vieira** [comment]
@breskeby I think we just need to backport your fix is all.
