### ISSUE TITLE
Persistent Settings Takes Effect After RecoverStateUpdateTask's Reroute

### ISSUE THREAD

**Issue by GrandFisher** [elastic/elasticsearch#82456]
RecoverStateUpdateTask execute Reroute before persistent settings takes effect, this may cause the logic about `AllocationService#reroute`  execute in an unexpected way.
`    class RecoverStateUpdateTask extends ClusterStateUpdateTask {

        @Override
        public ClusterState execute(final ClusterState currentState) {
            if (currentState.blocks().hasGlobalBlock(STATE_NOT_RECOVERED_BLOCK) == false) {
                logger.debug("cluster is already recovered");
                return currentState;
            }

            final ClusterState newState = Function.<ClusterState>identity()
                .andThen(ClusterStateUpdaters::updateRoutingTable)
                .andThen(ClusterStateUpdaters::removeStateNotRecoveredBlock)
                .apply(currentState);

            return allocationService.reroute(newState, "state recovered");
        }
       ....
`
The place where the persistent settings is applied in master is after clusterstate publish .

**Comment by GrandFisher** [comment]
We want to  move `allocationService.reroute(newState, "state recovered")` to callback method  `RecoverStateUpdateTask#clusterStateProcessed`,and in it we can  submit a `ClusterStateUpdateTask` that execute `allocationService.reroute(currentState, "state recovered")`

**Comment by DaveCTurner** [comment]
I'm not sure I understand the impact of this: the task in question doesn't change any cluster settings so the latest persistent settings should all be applied already. Could you share some more details of which settings this affects and what the unexpected behaviour is? Maybe open a PR with a test that shows the problem?

**Comment by DaveCTurner** [comment]
I'm closing this due to the lack of response, but we're happy to reopen it if we receive more details about how this is a problem.

**Comment by GrandFisher** [comment]
Sorry, I missed this reply. I'm trying [#81081](https://github.com/elastic/elasticsearch/pull/81081/files). I setted up `cluster.routing.allocation.batch_fetch_shard.enable` is true  in persistent settings, and full restart the whole cluster. And I found that the logic of single fetch was executed  which should execute batch fetch logic.
I Jstack the process,  and found that the RecoverStateUpdateTask executed first after full restart, and at the time ,the persistent settings was not updating by master.



>

**Comment by GrandFisher** [comment]
Below is the Jstack process result.
`"elasticsearch[master_0_1][masterService#updateTask][T#1]" #581 daemon prio=5 os_prio=0 cpu=405778.91ms elapsed=440.88s tid=0x00007fc33c22a800 nid=0x972 runnable  [0x00007fc29e3a2000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.IOUtil.write1(java.base@11.0.2/Native Method)
	at sun.nio.ch.EPollSelectorImpl.wakeup(java.base@11.0.2/EPollSelectorImpl.java:254)
	- locked <0x00000001cbbeba90> (a java.lang.Object)
	at io.netty.channel.nio.NioEventLoop.wakeup(NioEventLoop.java:763)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:907)
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1011)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:800)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:298)
	at org.elasticsearch.transport.netty4.Netty4TcpChannel.sendMessage(Netty4TcpChannel.java:146)
	at org.elasticsearch.transport.OutboundHandler.internalSend(OutboundHandler.java:131)
	at org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:124)
	at org.elasticsearch.transport.OutboundHandler.sendRequest(OutboundHandler.java:88)
	at org.elasticsearch.transport.TcpTransport$NodeChannels.sendRequest(TcpTransport.java:245)
	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:702)
	at org.elasticsearch.transport.TransportService$$Lambda$2708/0x0000000800affc40.sendRequest(Unknown Source)
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:616)
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:598)
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.start(TransportNodesAction.java:182)
	at org.elasticsearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:82)
	at org.elasticsearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:51)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:153)
	at com.bytedance.aggregation.groupby.GroupbyOptimizeActionFilter.apply(GroupbyOptimizeActionFilter.java:73)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:151)
	at com.bytedance.aggregation.groupby.RewriteToGroupByActionFilter.apply(RewriteToGroupByActionFilter.java:44)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:151)
	at com.bytedance.aggregation.fetch.FetchActionFilter.apply(FetchActionFilter.java:69)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:151)
	at org.elasticsearch.plugin.elasticfence.handler.impl.AbstractAuthenticationHandler.auth(AbstractAuthenticationHandler.java:411)
	at org.elasticsearch.plugin.elasticfence.SecurityActionFilter.apply(SecurityActionFilter.java:79)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:151)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:129)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64)
	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.list(TransportNodesListGatewayStartedShards.java:96)
	at org.elasticsearch.gateway.GatewayAllocator$InternalPrimaryShardAllocator.listStartedShards(GatewayAllocator.java:302)
	at org.elasticsearch.gateway.GatewayAllocator$InternalPrimaryShardAllocator$$Lambda$2865/0x0000000800c21840.list(Unknown Source)
	at org.elasticsearch.gateway.AsyncShardFetch.asyncFetch(AsyncShardFetch.java:312)
	at org.elasticsearch.gateway.AsyncShardFetch.fetchData(AsyncShardFetch.java:142)
	- locked <0x00000005f8f0a190> (a org.elasticsearch.gateway.GatewayAllocator$InternalAsyncFetch)
	at org.elasticsearch.gateway.GatewayAllocator$InternalPrimaryShardAllocator.fetchData(GatewayAllocator.java:280)
	at org.elasticsearch.gateway.PrimaryShardAllocator.makeAllocationDecision(PrimaryShardAllocator.java:86)
	at org.elasticsearch.gateway.BaseGatewayShardAllocator.allocateUnassigned(BaseGatewayShardAllocator.java:80)
	at org.elasticsearch.gateway.GatewayAllocator.innerAllocatedUnassigned(GatewayAllocator.java:151)
	at org.elasticsearch.gateway.GatewayAllocator.allocateUnassigned(GatewayAllocator.java:140)
	at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:448)
	at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:416)
	at org.elasticsearch.gateway.GatewayService$RecoverStateUpdateTask.execute(GatewayService.java:256)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219)
	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:167)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:205)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:669)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)`

**Comment by DaveCTurner** [comment]
Ok I see. The reason we don't see the persistent settings in this first reroute is that they're not applied while the `STATE_NOT_RECOVERED_BLOCK` is in place, because of this check for `disableStatePersistence()`:

https://github.com/elastic/elasticsearch/blob/12ad399c488f0cc60e19b5e1b29c6d569cb4351a/server/src/main/java/org/elasticsearch/cluster/service/ClusterApplierService.java#L494-L500

In the specific case of `cluster.routing.allocation.batch_fetch_shard.enable` I think this setting should not be dynamic anyway (and possibly even not a setting) but more generally I see how this could be problem.

**Comment by GrandFisher** [comment]
Thank you so much, I temporarily solved this problem by add the settings to `elasticsearch.yml`, but I think this way contains potential risks, there is always the possibility that someone forgets to add a setting similar to `cluster.routing.allocation.batch_fetch_shard.enable` to the `elasticsearch.yml` file.
