### ISSUE TITLE
Nicer error for incorrect arguments for scripting fields API

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#82581]
`field('myfield').get(<index>, <default>)` is a standard field API method looked up via duck-typing.  If a script puts the argumetns in the wrong order, eg `field('mykeyword').get('default-keyword', 2)`, the error is
```
"caused_by" : {
  "type" : "wrong_method_type_exception",
  "reason" : "cannot convert MethodHandle(AbstractKeywordDocValuesField,int,String)String to (Object,String,int)Object",
  "stack_trace" : "java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(AbstractKeywordDocValuesField,int,String)String to (Object,String,int)
at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:884)
at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:869)
at org.elasticsearch.painless.DefBootstrap$PIC.fallback(DefBootstrap.java:231)
at org.elasticsearch.painless.PainlessScript$Script.execute(field('flattened.list2').get('dne', 1):25)
at org.elasticsearch.search.fetch.subphase.ScriptFieldsPhase$1.process(ScriptFieldsPhase.java:47)
at org.elasticsearch.search.fetch.FetchPhase.buildSearchHits(FetchPhase.java:168)
at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:90)
```

We could make that more user-friendly.

Refs: #78920

**Comment by jdconrad** [comment]
Closing this as it is unlikely to be prioritized.
