### ISSUE TITLE
[CI] BasicDistributedJobsIT testFailOverBasics_withDataFeeder failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#82591]
This has failed a couple of times now but didn't reproduce locally for me.

**Build scan:**
https://gradle-enterprise.elastic.co/s/dd4r3j7yidfcy/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT/testFailOverBasics_withDataFeeder

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT.testFailOverBasics_withDataFeeder" -Dtests.seed=B25306F25F5A8CDB -Dtests.locale=uk -Dtests.timezone=Europe/Sofia -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT&tests.test=testFailOverBasics_withDataFeeder

**Failure excerpt:**
```
java.util.concurrent.ExecutionException: org.elasticsearch.transport.RemoteTransportException: [node_t1][127.0.0.1:37403][cluster:admin/xpack/ml/datafeeds/delete]

  at __randomizedtesting.SeedInfo.seed([B25306F25F5A8CDB:5DE65A09985D9256]:0)
  at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:257)
  at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:244)
  at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:75)
  at org.elasticsearch.xpack.ml.support.BaseMlIntegTestCase.deleteAllDatafeeds(BaseMlIntegTestCase.java:379)
  at org.elasticsearch.xpack.ml.support.BaseMlIntegTestCase.cleanup(BaseMlIntegTestCase.java:264)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: org.elasticsearch.transport.RemoteTransportException: [node_t1][127.0.0.1:37403][cluster:admin/xpack/ml/datafeeds/delete]


    Caused by: org.elasticsearch.ElasticsearchStatusException: Cannot delete datafeed [data_feed_id] while its status is started

      at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.conflictStatusException(ExceptionsHelper.java:77)
      at org.elasticsearch.xpack.ml.datafeed.DatafeedManager.deleteDatafeed(DatafeedManager.java:229)
      at org.elasticsearch.xpack.ml.action.TransportDeleteDatafeedAction.masterOperation(TransportDeleteDatafeedAction.java:77)
      at org.elasticsearch.xpack.ml.action.TransportDeleteDatafeedAction.masterOperation(TransportDeleteDatafeedAction.java:35)
      at org.elasticsearch.action.support.master.TransportMasterNodeAction.executeMasterOperation(TransportMasterNodeAction.java:121)
      at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:215)
      at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
      at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:220)
      at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:215)
      at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:152)
      at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:52)
      at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:79)
      at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:53)
      at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:77)
      at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:54)
      at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:71)
      at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:67)
      at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:67)
      at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:276)
      at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:115)
      at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:94)
      at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:773)
      at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:149)
      at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:121)
      at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:86)
      at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:354)
      at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:222)
      at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:35)
      at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
      at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:143)
      at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:415)
      at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:241)
      at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:168)
      at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:125)
      at java.lang.Thread.run(Thread.java:833)

```

**Comment by ywelsch** [comment]
Another one: https://gradle-enterprise.elastic.co/s/gtydgco7fn42k/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT/testFailOverBasics_withDataFeeder

**Comment by davidkyle** [comment]
One more on 8.0

https://gradle-enterprise.elastic.co/s/aapsm7tmw65cc/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT/testFailOverBasics_withDataFeeder

**Comment by davidkyle** [comment]
I suspect this is a consequence of moving the GET Datafeed stats action off master in #82271 and has resulted in an inconsistent view of the datafeed state. 

Muting in #83317

**Comment by thecoop** [comment]
Happened again on 7.17: https://gradle-enterprise.elastic.co/s/y37ifjzcebahk/tests/task/:x-pack:plugin:ml:internalClusterTest/details/org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT/testFailOverBasics

**Comment by droberts195** [comment]
> I suspect this is a consequence of moving the GET Datafeed stats action off master in https://github.com/elastic/elasticsearch/pull/82271 and has resulted in an inconsistent view of the datafeed state.

The reason this happens is because when the master node publishes a new cluster state it won't report that new state itself until all the other nodes confirm they've received that state. However, the _non_-master nodes will report what's in that new state as soon as they receive it.

At the very end of `testFailOverBasics_withDataFeeder` we wait for the datafeed stats to report that the datafeed is started. Then the test ends and cleanup starts. The first thing that cleanup does is to stop all the started datafeeds. What happens in this failure is that the stats request and the stop request go to different non-master nodes. The stats request goes to a node that has received the very latest cluster state. The stop request goes to a node that hasn't. So the node that's being told to stop all datafeeds cannot see the cluster state that says the datafeed is started. That node then thinks the datafeed doesn't need stopping, so doesn't stop it. Later on, the delete request happens after the cluster state has propagated, and refuses to delete the started datafeed.

The obvious fix is to revert #82271 and make get datafeed stats a master node action again. However, that also has downsides, as it will pile more work back onto the master node. Get datafeed stats is called every minute as part of X-Pack usage. It's also called when the jobs list in the UI is refreshed, which could be every 30 seconds. So potentially we have 3 calls per minute to get datafeed stats and it's not ideal if all the processing has to be done on the master node.

Overloading the master node with stats calls has caused more problems in the past than these intermittent inconsistent views of the cluster state. Waiting for a datafeed to be started and then immediately stopping it is quite a weird thing to do, which is probably why we've never had a customer complaint about this despite seeing it cause problems in tests.
