### ISSUE TITLE
"Test cat indices output for dot-hidden index and dot-prefixed pattern" fails on master

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#82660]
**Build scan**:

https://gradle-enterprise.elastic.co/s/cme7huijunvdg

**Repro line**:

```
REPRODUCE WITH: ./gradlew ':rest-api-spec:yamlRestTest' --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT" \
  -Dtests.method="test {yaml=cat.indices/20_hidden/Test cat indices output for dot-hidden index and dot-prefixed pattern}" \
  -Dtests.seed=A19AD8C02AD3D7B4 \
  -Dtests.locale=pl-PL \
  -Dtests.timezone=Asia/Singapore \
  -Druntime.java=17

REPRODUCE WITH: ./gradlew ':rest-api-spec:yamlRestTest' --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT" \
  -Dtests.method="test {yaml=cat.indices/20_hidden/Test cat indices output for dot-hidden index and dot-prefixed pattern}" \
  -Dtests.seed=A19AD8C02AD3D7B4 \
  -Dtests.locale=pl-PL \
  -Dtests.timezone=Asia/Singapore \
  -Druntime.java=17
```

**Reproduces locally?**:
No

**Applicable branches**:

`master`

**Failure history**:

This is the first failure of this test since July 2021

**Failure excerpt**:

```
11:39:28         Caused by:
11:39:28         java.lang.AssertionError: field [$body] was expected to match the provided regex but didn't
11:39:28         Expected: ^(green  \s+
11:39:28            open   \s+
11:39:28            \.index1 \s+
11:39:28            ([a-zA-Z0-9=/_+]|[\\\-]){22} \s+
11:39:28            1      \s+
11:39:28            0      \s+
11:39:28            0      \s+
11:39:28            0      \s+
11:39:28            (\d+|\d+[.]\d+)(kb|b) \s+
11:39:28            (\d+|\d+[.]\d+)(kb|b) \s*
11:39:28          )
11:39:28          $
11:39:28              but: was "green open .index1 qxYUkTocRnqz27Ix1xgxVQ 1 0 0 0 225b 225b\ngreen open .tasks  HRmCS8fTRVqa0m1RBS486g 1 0 0 0 225b 225b\n"
11:39:28             at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
11:39:28             at org.junit.Assert.assertThat(Assert.java:956)
11:39:28             at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:64)
11:39:28             at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
11:39:28             at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:478)
11:39:28             ... 38 more
```

**Comment by martijnvg** [comment]
I ran into a failure for `cat.indices/20_hidden/Test cat indices output with a hidden index with a hidden alias` test:
https://gradle-enterprise.elastic.co/s/63fli54x3diom#tests

It looks similar:

```
java.lang.AssertionError: Failure at [cat.indices/20_hidden:167]: field [$body] was expected to match the provided regex but didn't	
	Expected: ^(green  \s+	
	   open   \s+	
	   index1 \s+	
	   ([a-zA-Z0-9=/_+]|[\\\-]){22} \s+	
	   1      \s+	
	   0      \s+	
	   0      \s+	
	   0      \s+	
	   (\d+|\d+[.]\d+)(kb|b) \s+	
	   (\d+|\d+[.]\d+)(kb|b) \s*	
	 )	
	 $	
	     but: was "green open index1 CZSfJ8gMRqmt8p0LKt81lg 1 0 0 0 225b 225b\ngreen open .tasks PZs5J745Qr-IPYpCrDFiYg 1 0 0 0 225b 225b\n"	
```

@probakowski Should this test failure be triaged as part of this issue?
