### ISSUE TITLE
Reduce Translog stats to do syscall when monitoring cluster and indices

### ISSUE THREAD

**Issue by luyuncheng** [elastic/elasticsearch#82720]
When i do benchmark many indices concurrent index with environment elasticsearch7.10.2, a monitor do request node stats, i see thousands of system call per seconds: `stat("/data00/xxx/translog-x.tlog")` using strace command. 

i checked some hot_thread shows:

```
"elasticsearch[9200-XXXX][management][T#3]" #153 daemon prio=5 os_prio=0 cpu=355816.24ms elapsed=130925.66s tid=0x00007f58c8100d40 nid=0x3791e3 runnable  [0x00007f5b80ac4000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.fs.UnixNativeDispatcher.stat0(java.base@15.0.1/Native Method)
        at sun.nio.fs.UnixNativeDispatcher.stat(java.base@15.0.1/UnixNativeDispatcher.java:277)
        at sun.nio.fs.UnixFileAttributes.get(java.base@15.0.1/UnixFileAttributes.java:70)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(java.base@15.0.1/UnixFileAttributeViews.java:52)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(java.base@15.0.1/UnixFileSystemProvider.java:148)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(java.base@15.0.1/LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(java.base@15.0.1/Files.java:1843)
        at java.nio.file.Files.getLastModifiedTime(java.base@15.0.1/Files.java:2394)
        at org.elasticsearch.index.translog.BaseTranslogReader.getLastModifiedTime(BaseTranslogReader.java:147)
        at org.elasticsearch.index.translog.Translog.findEarliestLastModifiedAge(Translog.java:434)
        at org.elasticsearch.index.translog.Translog.earliestLastModifiedAge(Translog.java:422)
        at org.elasticsearch.index.translog.Translog.stats(Translog.java:851)
        at org.elasticsearch.index.engine.InternalEngine.getTranslogStats(InternalEngine.java:592)
        at org.elasticsearch.index.shard.IndexShard.translogStats(IndexShard.java:1088)
        at org.elasticsearch.action.admin.indices.stats.CommonStats.<init>(CommonStats.java:213)
        at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.shardOperation(TransportIndicesStatsAction.java:105)
        at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.shardOperation(TransportIndicesStatsAction.java:48)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.onShardOperation(TransportBroadcastByNodeAction.java:434)
```

When using network file system, `stat` syscall is a heavy job, this syscall would do many getAttribute to remote server when it refresh dentry, so it is prefer to reduce the syscall getAttribute.

i reviewed the code `Translog.java` and `TranslogReader.java`, actually `TranslogReader` is an immutable translog file reader. it seems we can read lastModifiedTime once instead of every time.

**Comment by original-brownbear** [comment]
relates #77466

**Comment by luyuncheng** [comment]
> relates #77466

@original-brownbear hi, there is a lot of work in #77466 about stats api, but i am not sure is there any work about reduce translog stats.  i do a pr about reduce translog stats: #82721 

I do some monitor about UnixFileAttributes callings, the most calling and time-consuming is `Files.readAttributes`, so when access into immutable file.

**Comment by original-brownbear** [comment]
Hi @luyuncheng 

right that issue doesn't go into detail on the stat's API slowness cause. You're spot on here with the fact that translog stats are a large chunk of the stats API slowness in large clusters, I'm seeing the same in our benchmarks.

> I do some monitor about UnixFileAttributes callings, the most calling and time-consuming is Files.readAttributes, so when access into immutable file.

++

> i do a pr about reduce translog stats: #82721

Thanks, I'll take a look!
