### ISSUE TITLE
[CI] FeatureMigrationIT testMigrateInternalManagedSystemIndex failing

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#82787]
Possibly related to https://github.com/elastic/elasticsearch/issues/79620 and https://github.com/elastic/elasticsearch/issues/79894

**Build scan:**
https://gradle-enterprise.elastic.co/s/dtctggai2a3fu/tests/:modules:reindex:internalClusterTest/org.elasticsearch.migration.FeatureMigrationIT/testMigrateInternalManagedSystemIndex

**Reproduction line:**
`./gradlew ':modules:reindex:internalClusterTest' --tests "org.elasticsearch.migration.FeatureMigrationIT.testMigrateInternalManagedSystemIndex" -Dtests.seed=3F108B636FD24EDA -Dtests.locale=zh-SG -Dtests.timezone=America/Cayman -Druntime.java=16`

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.migration.FeatureMigrationIT&tests.test=testMigrateInternalManagedSystemIndex

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([3F108B636FD24EDA:60B2E4FA292639C8]:0)
  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertNotNull(Assert.java:712)
  at org.junit.Assert.assertNotNull(Assert.java:722)
  at org.elasticsearch.migration.FeatureMigrationIT.assertIndexHasCorrectProperties(FeatureMigrationIT.java:295)
  at org.elasticsearch.migration.FeatureMigrationIT.testMigrateInternalManagedSystemIndex(FeatureMigrationIT.java:221)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:831)

```

**Comment by cbuescher** [comment]
Another one today, also 7.17:  https://gradle-enterprise.elastic.co/s/3eoivyw2thhyc
Didn't reproduce for me locally.

**Comment by henningandersen** [comment]
Another one today: https://gradle-enterprise.elastic.co/s/lm43bklilhabu

No luck reproducing with repro line.

**Comment by jtibshirani** [comment]
Another one, also on 7.17: https://gradle-enterprise.elastic.co/s/lm43bklilhabu

I muted the test (only on the 7.17 branch since that's where we've seen failures).

**Comment by grcevski** [comment]
I think I see the problem. The issue with this test is that a shard migration might happen after we have upgraded the index, perhaps because we delete indices after we upgrade them, and the test fails to find index stats of an index in a shard that's being checked.

The failure always happens when our test infrastructure adds the option to check shards, i.e. `IndexSettings.INDEX_CHECK_ON_STARTUP`. The interesting sequence is the following:

```
[2022-02-01T11:22:50,638][WARN ][o.e.i.s.IndexShard       ] [node_s2] [.int-unman-old-reindexed-for-8][0] performing expensive diagnostic checks during shard startup ...
[2022-02-01T11:22:50,716][INFO ][o.e.c.r.a.AllocationService] [node_s1] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.int-unman-old-reindexed-for-8][0]]]). |  
[2022-02-01T11:22:50,880][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s1] [.int-unman-old/klla4AsxQDiyRVH47dFvEg] deleting index |  
[2022-02-01T11:22:50,992][INFO ][o.e.u.SystemIndexMigrator] [node_s1] finished migrating old index [.int-unman-old] from feature [A-test-feature] to new index [.int-unman-old-reindexed-for-8] |  
[2022-02-01T11:22:51,030][WARN ][o.e.i.s.IndexShard       ] [node_s0] [.int-unman-old-reindexed-for-8][0] performing expensive diagnostic checks during shard startup ...
[2022-02-01T11:22:51,045][INFO ][o.e.u.SystemIndexMigrator] [node_s1] finished migrating feature indices 
```

Whenever the test fails we see double `performing expensive diagnostic checks` on the `.int-unman-old-reindexed-for-8` index, and always on a different node than what the index originally migrated on. In our case the shard started on node_s1, but then it seems it got moved to node_s0. The test proceeds to check index stats on `.int-unman-old-reindexed-for-8`, but I think the new shard on node_s0 for `.int-unman-old-reindexed-for-8` isn't GREEN yet and the stats call fails to provide data.

I believe all we need to do in the test is add ensureGreen() after we finish all migrations and before we check any index stats.
