### ISSUE TITLE
combined_fields + dfs_query_then_fetch causes error

### ISSUE THREAD

**Issue by cyradin** [elastic/elasticsearch#82817]
**Elasticsearch version** (`bin/elasticsearch --version`): docker image elasticsearch:7.13.4, also tried on 7.15.0

**Plugins installed**: [analysis-icu, analysis-phonetic]

**JVM version** (`java -version`):  ???

**OS version** (`uname -a` if on a Unix-like system): official docker image

**Description of the problem including expected versus actual behavior**:
Using combined_fields query with dfs_query_then_fetch causes "docCount must not exceed maxDoc" error if the request goes to multiple shards.

**Steps to reproduce**:
Example:
```
PUT /my-index
{
  "settings": {
    "index": {
      "number_of_shards": 2 
    }
  }
}

POST /my-index/_doc
{
  "name": "item 1",
  "description": "description 1"
}
POST /my-index/_doc
{
  "name": "item 2",
  "description": "description 2"
}

POST /my-index/_search?search_type=dfs_query_then_fetch
{
  "query": {
    "combined_fields": {
      "fields": [
        "name", "description"
      ],
      "query": "item"
    }
  }
}
```

**Provide logs (if relevant)**:
Response:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "docCount must not exceed maxDoc, docCount: 2, maxDoc: 1"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "dfs_query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "my-index",
        "node" : "iieOmNBaRkaOGjyQCQw6Bg",
        "reason" : {
          "type" : "illegal_argument_exception",
          "reason" : "docCount must not exceed maxDoc, docCount: 2, maxDoc: 1"
        }
      }
    ],
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "docCount must not exceed maxDoc, docCount: 2, maxDoc: 1",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "docCount must not exceed maxDoc, docCount: 2, maxDoc: 1"
      }
    }
  },
  "status" : 400
}
```

**Comment by ywelsch** [comment]
The full stack trace is the following:

```
org.elasticsearch.transport.RemoteTransportException: [yamlRestTest-0][127.0.0.1:52644][indices:data/read/search[phase/query/id]]
  1> Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
  1>    at org.elasticsearch.search.query.QueryPhase.executeInternal(QueryPhase.java:197)
  1>    at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:80)
  1>    at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$5(SearchService.java:713)
  1>    at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunna  1> ble.java:47)
  1>    at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  1>    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  1>    at java.base/java.lang.Thread.run(Thread.java:833)
  1> Caused by: java.lang.IllegalArgumentException: docCount must not exceed maxDoc, docCount: 3, maxDoc: 1
  1>    at org.apache.lucene.search.CollectionStatistics.<init>(CollectionStatistics.java:81)
  1>    at org.apache.lucene.sandbox.search.CombinedFieldQuery$CombinedFieldWeight.mergeCollectionStatistics(CombinedFieldQuery.java:368)
  1>    at org.apache.lucene.sandbox.search.CombinedFieldQuery$CombinedFieldWeight.<init>(CombinedFieldQuery.java:343)
  1>    at org.apache.lucene.sandbox.search.CombinedFieldQuery.createWeight(CombinedFieldQuery.java:287)
  1>    at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:894)
  1>    at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:161)
  1>    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:555)
  1>    at org.elasticsearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:224)
  1>    at org.elasticsearch.search.query.QueryPhase.executeInternal(QueryPhase.java:179)
  1>    ... 11 more
  1> }
  1>    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:730)
  1>    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:417)
  1>    at org.elasticsearch.action.search.DfsQueryPhase.lambda$run$0(DfsQueryPhase.java:66)
  1>    at org.elasticsearch.action.search.CountedCollector.countDown(CountedCollector.java:40)
  1>    at org.elasticsearch.action.search.CountedCollector.onFailure(CountedCollector.java:59)
  1>    at org.elasticsearch.action.search.DfsQueryPhase$1.onFailure(DfsQueryPhase.java:100)
  1>    at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:48)
  1>    at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:642)
  1>    at org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1613)
  1>    at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1350)
  1>    at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1472)
  1>    at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1447)
  1>    at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:50)
  1>    at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:47)
  1>    at org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:1125)
  1>    at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:77)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
  1>    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  1>    at java.base/java.lang.Thread.run(Thread.java:833)
```

This looks to be a bug in Lucene's `CombinedFieldQuery` which does not take into account that collectionStatistics might be overridden:

https://github.com/apache/lucene/blob/07ee3ba83a4c9f3abc24bf9d3fbb3c3102c4a102/lucene/sandbox/src/java/org/apache/lucene/sandbox/search/CombinedFieldQuery.java#L353-L366

**Comment by ywelsch** [comment]
This was a Lucene bug (see https://github.com/apache/lucene/pull/910), which has now been fixed. It will be released in one one of the upcoming Elasticsearch releases once we update to the upcoming Lucene 9.3.0 release.
