### ISSUE TITLE
[CI] PutPrivilegesResponseTests testSerialization failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#82831]
Started failing today, possibly related to https://github.com/elastic/elasticsearch/pull/82670

**Build scan:**
https://gradle-enterprise.elastic.co/s/cekmpdm3ktkiu/tests/:x-pack:plugin:core:test/org.elasticsearch.xpack.core.security.action.privilege.PutPrivilegesResponseTests/testSerialization

**Reproduction line:**
`./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.security.action.privilege.PutPrivilegesResponseTests.testSerialization" -Dtests.seed=496E6D8B556D0669 -Dtests.locale=ja-JP -Dtests.timezone=Asia/Yekaterinburg -Druntime.java=17`

**Applicable branches:**
master, 8.0

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.core.security.action.privilege.PutPrivilegesResponseTests&tests.test=testSerialization

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: "{\"created\":{\"gQePHz\":[\"GEatNb\",\"DIgmgL\",\"poUSEU\",\"knnGKv\"],\"Xozvz\":[\"QjIaCc\",\"ToYrtJ\",\"ClviQM\"],\"Boq\":[\"cthnpZ\"]}}"
     but: was "{\"created\":{\"gQePHz\":[\"GEatNb\",\"DIgmgL\",\"poUSEU\",\"knnGKv\"],\"Boq\":[\"cthnpZ\"],\"Xozvz\":[\"QjIaCc\",\"ToYrtJ\",\"ClviQM\"]}}"

  at __randomizedtesting.SeedInfo.seed([496E6D8B556D0669:1DB60CC3723F3BF5]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.core.security.action.privilege.PutPrivilegesResponseTests.testSerialization(PutPrivilegesResponseTests.java:37)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by mark-vieira** [comment]
@arteam this might be related to https://github.com/elastic/elasticsearch/pull/82670. Looks like it's just a matter of response order not matching the exact order in the request. Perhaps we should just change the assertions to be order-insensitive here.

**Comment by mark-vieira** [comment]
I've gone ahead and muted this in `master` since it's failed a number of times and reliably reproduces.

**Comment by mark-vieira** [comment]
Muted in `8.0` as well since there were failures there as well.

**Comment by ChrisHegarty** [comment]
The changes in  #82670 expose a pre-existing issue in the test - it inadvertently relies on iteration order of Map, which is a test bug.

Iteration order of Map depends on may factors including, but not limited to, size, capacity, resize, or in the case of Map::of a per-JVM instance salt. For example:

```
jshell> Map<String,Integer> map1 = new HashMap<>(5)
map1 ==> {}

jshell> map1.put("Bob", 1); map1.put("Alise", 1); map1.put("Fred", 1)
$2 ==> null
$3 ==> null
$4 ==> null

jshell> map1.toString()
$5 ==> "{Fred=1, Bob=1, Alise=1}"

jshell> Map<String,Integer> map2 = new HashMap<>()
map2 ==> {}

jshell> map2.put("Bob", 1); map2.put("Alise", 1); map2.put("Fred", 1)
$7 ==> null
$8 ==> null
$9 ==> null

jshell> map2.toString()
$10 ==> "{Bob=1, Alise=1, Fred=1}"
```

**Comment by arteam** [comment]
I've seen this test failing, I've fixed a similar error in https://github.com/elastic/elasticsearch/commit/bc91cd031696195140abbf56fa96545962566caf. Let me fix it.
