### ISSUE TITLE
[CI] Failures in :qa:ccs-rolling-upgrade-remote-cluster:v7.17.0#twoThirdUpgraded Cluster Setup

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#82872]
Seeing this happen constantly in CCS BwC tests:

**Build scan**:

https://gradle-enterprise.elastic.co/s/rwr7uhwap36zq/console-log?anchor=3508

**Repro line**:

non, cluster setup fails.

**Reproduces locally?**:

Haven't tried yet

**Applicable branches**:

master

**Failure history**:

**Failure excerpt**:

```
=== Log output of node `node{:qa:ccs-rolling-upgrade-remote-cluster:v7.17.0-remote-1}` ===

»    ↓ errors and warnings from /dev/shm/elastic+elasticsearch+master+intake+multijob+bwc/qa/ccs-rolling-upgrade-remote-cluster/build/testclusters/v7.17.0-remote-1/logs/v7.17.0-remote.log ↓
» [2022-01-20T14:59:03,377][WARN ][o.e.d.FileBasedSeedHostsProvider] [v7.17.0-remote-1] expected, but did not find, a dynamic hosts list at [/dev/shm/elastic+elasticsearch+master+intake+multijob+bwc/qa/ccs-rolling-upgrade-remote-cluster/build/testclusters/v7.17.0-remote-1/config/unicast_hosts.txt]
»   ↑ repeated 11 times ↑
» [2022-01-20T14:59:03,374][WARN ][o.e.c.c.ClusterFormationFailureHelper] [v7.17.0-remote-1] master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [v7.17.0-remote-0, v7.17.0-remote-1, v7.17.0-remote-2] to bootstrap a cluster: have discovered [{v7.17.0-remote-1}{eAmxs5caSoycdfmlZe-LbQ}{Gy54APi1S_yt0fizPEtYmQ}{127.0.0.1}{127.0.0.1:32963}{cdfhilmrstw}]; discovery will continue using [] from hosts providers and [{v7.17.0-remote-1}{eAmxs5caSoycdfmlZe-LbQ}{Gy54APi1S_yt0fizPEtYmQ}{127.0.0.1}{127.0.0.1:32963}{cdfhilmrstw}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
» [2022-01-20T14:59:26,644][WARN ][stderr                   ] [v7.17.0-remote-1] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
» [2022-01-20T14:59:26,647][WARN ][stderr                   ] [v7.17.0-remote-1] SLF4J: Defaulting to no-operation (NOP) logger implementation
» [2022-01-20T14:59:26,647][WARN ][stderr                   ] [v7.17.0-remote-1] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
» [2022-01-20T14:59:35,769][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.17.0-remote-1] fatal error in thread [main], exiting
»  java.lang.AssertionError: {current_term=2, last_accepted_version=67, node_id=eAmxs5caSoycdfmlZe-LbQ, node_version=7170099, oldest_index_version=7170099}
»  	at org.elasticsearch.gateway.PersistedClusterStateService.loadOnDiskState(PersistedClusterStateService.java:499) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.gateway.PersistedClusterStateService.loadBestOnDiskState(PersistedClusterStateService.java:395) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.gateway.PersistedClusterStateService.loadBestOnDiskState(PersistedClusterStateService.java:348) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:102) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.node.Node.start(Node.java:1133) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:272) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:367) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
```

https://gradle-enterprise.elastic.co/s/rwr7uhwap36zq/console-log?anchor=3508)](https://gradle-enterprise.elastic.co/s/rwr7uhwap36zq/console-log/raw

**Comment by original-brownbear** [comment]
Fixed now, BwC merge order issue only.
