### ISSUE TITLE
[CI] ClientYamlTestSuiteIT test {yaml=indices.get_alias/10_basic/Get aliases via /_all/_alias/} failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#83256]
Tried various combinations of things to see if I could get it to reproduce but no luck.

**Build scan:**
https://gradle-enterprise.elastic.co/s/gilio54m2qpfg/tests/:rest-api-spec:yamlRestTest/org.elasticsearch.test.rest.ClientYamlTestSuiteIT/test%20%7Byaml=indices.get_alias%2F10_basic%2FGet%20aliases%20via%20%2F_all%2F_alias%2F%7D

**Reproduction line:**
`./gradlew ':rest-api-spec:yamlRestTest' --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT" -Dtests.method="test {yaml=indices.get_alias/10_basic/Get aliases via /_all/_alias/}" -Dtests.seed=A6876E6644ACEAF -Dtests.locale=ro -Dtests.timezone=CST6CDT -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.test.rest.ClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dindices.get_alias/10_basic/Get%20aliases%20via%20/_all/_alias/%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [indices.get_alias/10_basic:86]: got unexpected warning header [
	299 Elasticsearch-8.1.0-SNAPSHOT-6dba3344a49153459bbc8f6e632868723e8486c6 "this request accesses system indices: [.tasks], but in a future major version, direct access to system indices will be prevented by default"
]

  at __randomizedtesting.SeedInfo.seed([A6876E6644ACEAF:823C493CCAB6A357]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:489)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)
  at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.AssertionError: got unexpected warning header [
  	299 Elasticsearch-8.1.0-SNAPSHOT-6dba3344a49153459bbc8f6e632868723e8486c6 "this request accesses system indices: [.tasks], but in a future major version, direct access to system indices will be prevented by default"
  ]

    at org.junit.Assert.fail(Assert.java:88)
    at org.elasticsearch.test.rest.yaml.section.DoSection.checkWarningHeaders(DoSection.java:487)
    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:370)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:478)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)
    at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(null:-1)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by tlrx** [comment]
Another test `Get all aliases via /_alias` in the same test suite failed today on master:
https://gradle-enterprise.elastic.co/s/tzbtlsotpzive/

I'll mute on master and 8.1.0.

**Comment by joegallo** [comment]
```
  1> [2022-02-04T12:52:49,602][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=search.aggregation/200_top_hits_metric/top_hits aggregation with nested documents and disabled _source] before test
  1> [2022-02-04T12:52:50,207][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=search.aggregation/200_top_hits_metric/top_hits aggregation with nested documents and disabled _source] after test
  1> [2022-02-04T12:52:50,309][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=indices.forcemerge/10_basic/Force merge with wait_for_completion parameter] before test
  1> [2022-02-04T12:52:50,594][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] There are still tasks running after this test that might break subsequent tests [indices:admin/auto_create, indices:admin/forcemerge, indices:data/write/index].
  1> [2022-02-04T12:52:50,594][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=indices.forcemerge/10_basic/Force merge with wait_for_completion parameter] after test
  1> [2022-02-04T12:52:50,699][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=indices.get_alias/10_basic/Get all aliases via /_alias] before test
  2> Úno 04, 2022 12:52:51 ODP. org.elasticsearch.client.RestClient logResponse
  2> WARNING: request [GET http://[::1]:51206/_alias?error_trace=true] returned 1 warnings: [299 Elasticsearch-8.2.0-SNAPSHOT-a2949f5305e42dcf8a82b9e6c13067b0a4a9c1a4 "this request accesses system indices: [.tasks], but in a future major version, direct access to system indices will be prevented by default"]
  1> [2022-02-04T12:52:51,197][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "test_index_2" : {
```

```
  1> [2022-01-28T04:37:17,855][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=cat.aliases/10_basic/Alias against closed index] after test
  1> [2022-01-28T04:37:17,999][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=nodes.stats/60_transport_stats/Transport stats] before test
  1> [2022-01-28T04:37:18,021][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=nodes.stats/60_transport_stats/Transport stats] after test
  1> [2022-01-28T04:37:18,163][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=indices.forcemerge/10_basic/Force merge with wait_for_completion parameter] before test
  1> [2022-01-28T04:37:18,346][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] There are still tasks running after this test that might break subsequent tests [indices:admin/auto_create, indices:admin/forcemerge, indices:data/write/index, internal:cluster/shard/started].
  1> [2022-01-28T04:37:18,346][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=indices.forcemerge/10_basic/Force merge with wait_for_completion parameter] after test
  1> [2022-01-28T04:37:18,501][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] [yaml=indices.get_alias/10_basic/Get aliases via /_all/_alias/] before test
  2> Ian 28, 2022 4:37:18 AM org.elasticsearch.client.RestClient logResponse
  2> WARNING: request [GET http://127.0.0.1:41309/_all/_alias?error_trace=true] returned 1 warnings: [299 Elasticsearch-8.1.0-SNAPSHOT-6dba3344a49153459bbc8f6e632868723e8486c6 "this request accesses system indices: [.tasks], but in a future major version, direct access to system indices will be prevented by default"]
  1> [2022-01-28T04:37:18,880][INFO ][o.e.t.r.ClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
```
