### ISSUE TITLE
[CI] TransportDesiredNodesActionsIT testDeleteDesiredNodesTasksAreBatchedCorrectly failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#83386]
**Build scan:**
https://gradle-enterprise.elastic.co/s/3sdeo4fn4dpio/tests/:server:internalClusterTest/org.elasticsearch.action.admin.cluster.desirednodes.TransportDesiredNodesActionsIT/testDeleteDesiredNodesTasksAreBatchedCorrectly

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.cluster.desirednodes.TransportDesiredNodesActionsIT.testDeleteDesiredNodesTasksAreBatchedCorrectly" -Dtests.seed=EFDF9BFF1D476AA8 -Dtests.locale=ro-RO -Dtests.timezone=US/Indiana-Starke -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.admin.cluster.desirednodes.TransportDesiredNodesActionsIT&tests.test=testDeleteDesiredNodesTasksAreBatchedCorrectly

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([EFDF9BFF1D476AA8]:0)

```

**Comment by mark-vieira** [comment]
These are now failing in 8.1 after the backported fix with a slightly different error:

```
java.lang.AssertionError: no longer master
	at __randomizedtesting.SeedInfo.seed([77EBECBE24AA2307]:0)
	at org.elasticsearch.action.admin.cluster.desirednodes.TransportDesiredNodesActionsIT$1.onFailure(TransportDesiredNodesActionsIT.java:387)
	at org.elasticsearch.cluster.ClusterStateTaskListener.onNoLongerMaster(ClusterStateTaskListener.java:31)
	at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.onNoLongerMaster(MasterService.java:619)
	at org.elasticsearch.cluster.service.MasterService$TaskInputs.lambda$onNoLongerMaster$0(MasterService.java:893)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.elasticsearch.cluster.service.MasterService$TaskInputs.onNoLongerMaster(MasterService.java:893)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:232)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:162)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:152)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:208)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:717)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:260)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.tags=8.1&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.action.admin.cluster.desirednodes.TransportDesiredNodesActionsIT&tests.sortField=FAILED&tests.test=testDeleteDesiredNodesTasksAreBatchedCorrectly&tests.unstableOnly=true

**Comment by mark-vieira** [comment]
Nevermind, looks like there was a follow up to fix this issue that's still working its way through CI.
