### ISSUE TITLE
AsyncSearchActionIT#testUpdateStoreKeepAlive can fail with assertion

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#83422]
### CI Link

https://gradle-enterprise.elastic.co/s/hlbba7jpfiwm6

### Repro line
```
./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testUpdateStoreKeepAlive" -Dtests.seed=BBF09564E57352EC -Dtests.locale=es-CO -Dtests.timezone=Pacific/Marquesas -Druntime.java=17
```
### Does it reproduce?

No

### Applicable branches

master

### Failure excerpt
It looks like the +10 days update isn't reflected in the response:
```
java.lang.AssertionError: 
    Expected: a value greater than <1638199886894L>
         but: <1638199886894L> was equal to <1638199886894L>
        at __randomizedtesting.SeedInfo.seed([BBF09564E57352EC:824D51180820ED87]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.search.AsyncSearchActionIT.testUpdateStoreKeepAlive(AsyncSearchActionIT.java:392)
```

**Comment by jtibshirani** [comment]
We've also seen another assertion error in the same test: https://gradle-enterprise.elastic.co/s/6odmjpmerlk7a. It looks like a different issue, where the async search task is never cleaned up:

```
org.elasticsearch.xpack.search.AsyncSearchActionIT > testUpdateStoreKeepAlive FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([B760AFB0B7495F74:8EDD6BCC5A1AE01F]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.junit.Assert.assertFalse(Assert.java:74)
        at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase.lambda$ensureTaskRemoval$0(AsyncSearchIntegTestCase.java:198)
```

**Comment by jtibshirani** [comment]
Looking over the failure history and details, these seem extremely rare. I'll close this issue since we don't have immediate plans to dig into them. Please reopen this if the same failures pop up again.
