### ISSUE TITLE
[CI] EnrollmentProcessTests test10ArchiveAutoFormCluster failing

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#83543]
**Build scan:**
https://gradle-enterprise.elastic.co/s/qvcxwxjjrkmng/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.EnrollmentProcessTests/test10ArchiveAutoFormCluster

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.EnrollmentProcessTests&tests.test=test10ArchiveAutoFormCluster

**Failure excerpt:**
```
java.lang.AssertionError: Startup command should succeed. Stderr: [exitCode = [1] stdout = [spawn -ignore HUP sudo -E -u elasticsearch /tmp/elasticsearch-node1/bin/elasticsearch -p /tmp/elasticsearch-node1/elasticsearch.pid -v
[2022-02-04T17:13:03,993][INFO ][o.e.n.Node               ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] version[8.2.0-SNAPSHOT], pid[19359], build[default/tar/fc4a9d444f0f5c9a9a3af5768a441ff802c93368/2022-02-04T16:53:37.389548783Z], OS[Linux/4.18.0-348.12.2.el8_5.x86_64/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.2/17.0.2+8]
[2022-02-04T17:13:03,999][INFO ][o.e.n.Node               ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] JVM home [/tmp/elasticsearch-node1/jdk], using bundled JDK [true]
[2022-02-04T17:13:04,000][INFO ][o.e.n.Node               ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-12891945020659820706, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms1g, -Xmx1g, -XX:MaxDirectMemorySize=536870912, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/tmp/elasticsearch-node1, -Des.path.conf=/tmp/elasticsearch-node1/config, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=true]
[2022-02-04T17:13:04,001][WARN ][o.e.n.Node               ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] version [8.2.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
[2022-02-04T17:13:05,825][WARN ][stderr                   ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[2022-02-04T17:13:05,827][WARN ][stderr                   ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] SLF4J: Defaulting to no-operation (NOP) logger implementation
[2022-02-04T17:13:05,827][WARN ][stderr                   ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2022-02-04T17:13:07,048][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [aggs-matrix-stats]
[2022-02-04T17:13:07,049][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [analysis-common]
[2022-02-04T17:13:07,049][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [constant-keyword]
[2022-02-04T17:13:07,050][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [data-streams]
[2022-02-04T17:13:07,050][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [frozen-indices]
[2022-02-04T17:13:07,051][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [ingest-common]
[2022-02-04T17:13:07,051][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [ingest-geoip]
[2022-02-04T17:13:07,051][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [ingest-user-agent]
[2022-02-04T17:13:07,051][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [kibana]
[2022-02-04T17:13:07,052][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [lang-expression]
[2022-02-04T17:13:07,052][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [lang-mustache]
[2022-02-04T17:13:07,052][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [lang-painless]
[2022-02-04T17:13:07,053][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [legacy-geo]
[2022-02-04T17:13:07,053][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [mapper-extras]
[2022-02-04T17:13:07,053][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [mapper-version]
[2022-02-04T17:13:07,054][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [old-lucene-versions]
[2022-02-04T17:13:07,054][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [parent-join]
[2022-02-04T17:13:07,054][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [percolator]
[2022-02-04T17:13:07,055][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [rank-eval]
[2022-02-04T17:13:07,055][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [reindex]
[2022-02-04T17:13:07,056][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [repositories-metering-api]
[2022-02-04T17:13:07,056][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [repository-azure]
[2022-02-04T17:13:07,056][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [repository-encrypted]
[2022-02-04T17:13:07,057][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [repository-gcs]
[2022-02-04T17:13:07,057][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [repository-s3]
[2022-02-04T17:13:07,058][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [repository-url]
[2022-02-04T17:13:07,058][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [runtime-fields-common]
[2022-02-04T17:13:07,058][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [search-business-rules]
[2022-02-04T17:13:07,059][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [searchable-snapshots]
[2022-02-04T17:13:07,059][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [snapshot-based-recoveries]
[2022-02-04T17:13:07,060][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [snapshot-repo-test-kit]
[2022-02-04T17:13:07,060][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [spatial]
[2022-02-04T17:13:07,060][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [test-delayed-aggs]
[2022-02-04T17:13:07,061][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [test-die-with-dignity]
[2022-02-04T17:13:07,061][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [test-error-query]
[2022-02-04T17:13:07,061][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [transform]
[2022-02-04T17:13:07,062][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [transport-netty4]
[2022-02-04T17:13:07,062][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [unsigned-long]
[2022-02-04T17:13:07,062][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [vector-tile]
[2022-02-04T17:13:07,063][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [vectors]
[2022-02-04T17:13:07,063][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [wildcard]
[2022-02-04T17:13:07,063][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-aggregate-metric]
[2022-02-04T17:13:07,063][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-analytics]
[2022-02-04T17:13:07,063][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-async]
[2022-02-04T17:13:07,064][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-async-search]
[2022-02-04T17:13:07,064][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-autoscaling]
[2022-02-04T17:13:07,064][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-ccr]
[2022-02-04T17:13:07,064][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-core]
[2022-02-04T17:13:07,064][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-deprecation]
[2022-02-04T17:13:07,065][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-enrich]
[2022-02-04T17:13:07,065][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-eql]
[2022-02-04T17:13:07,065][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-fleet]
[2022-02-04T17:13:07,065][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-graph]
[2022-02-04T17:13:07,066][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-identity-provider]
[2022-02-04T17:13:07,066][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-ilm]
[2022-02-04T17:13:07,066][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-logstash]
[2022-02-04T17:13:07,067][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-ml]
[2022-02-04T17:13:07,067][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-monitoring]
[2022-02-04T17:13:07,068][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-ql]
[2022-02-04T17:13:07,068][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-rollup]
[2022-02-04T17:13:07,068][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-security]
[2022-02-04T17:13:07,068][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-shutdown]
[2022-02-04T17:13:07,069][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-sql]
[2022-02-04T17:13:07,069][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-stack]
[2022-02-04T17:13:07,069][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-text-structure]
[2022-02-04T17:13:07,069][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-voting-only-node]
[2022-02-04T17:13:07,069][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] loaded module [x-pack-watcher]
[2022-02-04T17:13:07,070][INFO ][o.e.p.PluginsService     ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] no plugins loaded
[2022-02-04T17:13:07,115][INFO ][o.e.e.NodeEnvironment    ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] using [1] data paths, mounts [[/ (/dev/sda2)]], net usable_space [305gb], net total_space [349.7gb], types [xfs]
[2022-02-04T17:13:07,116][INFO ][o.e.e.NodeEnvironment    ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] heap size [1gb], compressed ordinary object pointers [true]
[2022-02-04T17:13:07,144][INFO ][o.e.n.Node               ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] node name [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834], node ID [KCqm0unNRP2q8eIQ9vPtaw], cluster name [elasticsearch], roles [data_frozen, ml, data_hot, transform, data_content, data_warm, master, remote_cluster_client, data, data_cold, ingest]
[2022-02-04T17:13:12,468][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] [controller/19691] [Main.cc@123] controller (64 bit): Version 8.2.0-SNAPSHOT (Build e78d581a0cdbc3) Copyright (c) 2022 Elasticsearch BV
[2022-02-04T17:13:12,690][INFO ][o.e.x.s.Security         ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] Security is enabled
[2022-02-04T17:13:13,057][INFO ][o.e.x.s.a.Realms         ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] license mode is [trial], currently licensed security realms are [reserved/reserved,file/default_file,native/default_native]
[2022-02-04T17:13:13,068][INFO ][o.e.x.s.a.s.FileRolesStore] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] parsed [0] roles from file [/tmp/elasticsearch-node1/config/roles.yml]
[2022-02-04T17:13:13,805][INFO ][o.e.x.s.InitialNodeSecurityAutoConfiguration] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] Auto-configuration will not generate a password for the elastic built-in superuser, as we cannot  determine if there is a terminal attached to the elasticsearch process. You can use the `bin/elasticsearch-reset-password` tool to set the password for the elastic user.
[2022-02-04T17:13:14,916][INFO ][o.e.t.n.NettyAllocator   ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=1mb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=4mb, heap_size=1gb}]
[2022-02-04T17:13:14,953][INFO ][o.e.i.r.RecoverySettings ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] using rate limit [40mb] with [default=40mb, read=0b, write=0b, max=0b]
[2022-02-04T17:13:14,997][INFO ][o.e.d.DiscoveryModule    ] [elasticsearch-ci-immutable-rocky-linux-8-p-1643993485372011834] using discovery type [multi-node] and seed hosts providers [settings]

Timed out waiting for startup to succeed] stderr = []]
Expected: <0>
     but: was <1>

  at __randomizedtesting.SeedInfo.seed([A92A8315B8A1C61D:FCDB5E7E546C2170]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.packaging.test.PackagingTestCase.awaitElasticsearchStartup(PackagingTestCase.java:356)
  at org.elasticsearch.packaging.test.PackagingTestCase.awaitElasticsearchStartupWithResult(PackagingTestCase.java:370)
  at org.elasticsearch.packaging.test.EnrollmentProcessTests.test10ArchiveAutoFormCluster(EnrollmentProcessTests.java:47)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by arteam** [comment]
I guess it somewhat similar to #81999?

**Comment by pugnascotia** [comment]
This test hasn't failed for a couple of weeks, so hopefully my last fix has worked 🤞
