### ISSUE TITLE
SQL: Upgrade  JLine/Jansi

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#83575]
### Description

The current version of JLine used by the SQL CLI has an old JAnsi dependency - when used in an environment with new hardware (such as Apple M1/Silicon) the terminal detection is unlikely to work (see https://github.com/elastic/elasticsearch/pull/83566).
Upgrading JAnsi to 2.4 (and by transition JLine as well) should fix this problem.

**Comment by luigidellaquila** [comment]
SQL CLI is currently using `jline-terminal-jna`, so we are not affected from the problem described.

**Comment by luigidellaquila** [comment]
On Mac M1 architectures, SQL CLI fails indeed, with the following:

```
Exception in thread "main" com.sun.jna.LastErrorException: [14] Bad address
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:415)
	at com.sun.jna.Function.invoke(Function.java:361)
	at com.sun.jna.Library$Handler.invoke(Library.java:265)
	at jdk.proxy1/jdk.proxy1.$Proxy0.ioctl(Unknown Source)
	at org.jline.terminal.impl.jna.osx.OsXNativePty.getSize(OsXNativePty.java:82)
	at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:60)
	at org.jline.terminal.Terminal.getBufferSize(Terminal.java:216)
	at org.jline.reader.impl.LineReaderImpl.doDisplay(LineReaderImpl.java:741)
	at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:298)
	at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:115)
	at org.elasticsearch.xpack.sql.cli.JLineTerminal.<init>(JLineTerminal.java:44)
```

An upgrade should solve the problem
