### ISSUE TITLE
.tasks index in 7.17 fails upgrade

### ISSUE THREAD

**Issue by ngbrown** [elastic/elasticsearch#83768]
### Elasticsearch Version

7.17.0

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

Windows 2019

### Problem Description

Upgrading indexes in 7.17.0 fails on the system index `.tasks` with an error "mapper_parsing_exception", and a reason "Root mapping definition has unsupported parameters".

I would expect required system indexes such as `.tasks` to upgrade without issue.

This seems like a blocker to upgrading to 8.x.

<details><summary>Screenshot</summary>
<p>

![Screenshot - 2022-02-10_01-12-00](https://user-images.githubusercontent.com/228987/153365250-12ab90cc-734b-4558-9310-20a815aa2795.png)

</p>
</details>

### Steps to Reproduce

This elasticsearch instance has been upgraded through several major and minor versions starting at 6.0.0. It was most recently upgraded from 7.9.0 to 7.17.0.  The migration assistant in Kibana 7.17.0 was then ran and the "Migrate indices" was clicked.

The query `GET /_migration/deprecations` has the results:

```json
{
  "cluster_settings" : [ ],
  "node_settings" : [ ],
  "index_settings" : {
    ".tasks" : [
      {
        "level" : "critical",
        "message" : "Index created before 7.0",
        "url" : "https://ela.st/es-deprecation-7-reindex",
        "details" : "This index was created with version 6.0.0 and is not compatible with 8.0. Reindex or remove the index before upgrading.",
        "resolve_during_rolling_upgrade" : false
      }
    ]
  },
  "ml_settings" : [ ],
  "ccr_auto_followed_system_indices" : [ ]
}
```

### Logs (if relevant)

```
[2022-02-10T01:45:51,040][INFO ][o.e.u.SystemIndexMigrator] [HDWPTENG01] preparing to migrate old index [.tasks] from feature [tasks] to new index [.tasks-reindexed-for-8]
[2022-02-10T01:45:51,129][INFO ][o.e.u.SystemIndexMigrator] [HDWPTENG01] migrating index [.tasks] from feature [tasks] to new index [.tasks-reindexed-for-8]
[2022-02-10T01:45:51,138][INFO ][o.e.c.m.MetadataCreateIndexService] [HDWPTENG01] failed on parsing mappings on index creation [.tasks-reindexed-for-8]
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [task : {_meta={version=7.17.0}, dynamic=strict, properties={task={properties={node={type=keyword}, headers={type=object, enabled=false}, parent_task_id={type=keyword}, running_time_in_nanos={type=long}, action={type=keyword}, description={type=text}, start_time_in_millis={type=long}, id={type=long}, type={type=keyword}, cancellable={type=boolean}, status={type=object, enabled=false}}}, response={type=object, enabled=false}, completed={type=boolean}, error={type=object, enabled=false}}}]
	at org.elasticsearch.index.mapper.MapperService.parseMappings(MapperService.java:505) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MapperService.mergeAndApplyMappings(MapperService.java:419) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:402) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1303) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$3(MetadataCreateIndexService.java:453) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:673) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:451) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:567) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:413) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:420) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:319) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:51) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:836) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:403) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:243) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.access$100(MasterService.java:63) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:146) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:202) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:262) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:225) [elasticsearch-7.17.0.jar:7.17.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [task : {_meta={version=7.17.0}, dynamic=strict, properties={task={properties={node={type=keyword}, headers={type=object, enabled=false}, parent_task_id={type=keyword}, running_time_in_nanos={type=long}, action={type=keyword}, description={type=text}, start_time_in_millis={type=long}, id={type=long}, type={type=keyword}, cancellable={type=boolean}, status={type=object, enabled=false}}}, response={type=object, enabled=false}, completed={type=boolean}, error={type=object, enabled=false}}}]
	at org.elasticsearch.index.mapper.MappingParser.checkNoRemainingFields(MappingParser.java:72) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:145) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MapperService.parseMappings(MapperService.java:503) ~[elasticsearch-7.17.0.jar:7.17.0]
	... 24 more
[2022-02-10T01:45:51,143][WARN ][o.e.p.AllocatedPersistentTask] [HDWPTENG01] task [upgrade-system-indices] failed with an exception
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [task : {_meta={version=7.17.0}, dynamic=strict, properties={task={properties={node={type=keyword}, headers={type=object, enabled=false}, parent_task_id={type=keyword}, running_time_in_nanos={type=long}, action={type=keyword}, description={type=text}, start_time_in_millis={type=long}, id={type=long}, type={type=keyword}, cancellable={type=boolean}, status={type=object, enabled=false}}}, response={type=object, enabled=false}, completed={type=boolean}, error={type=object, enabled=false}}}]
	at org.elasticsearch.index.mapper.MapperService.parseMappings(MapperService.java:505) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MapperService.mergeAndApplyMappings(MapperService.java:419) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:402) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1303) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$3(MetadataCreateIndexService.java:453) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:673) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:451) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:567) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:413) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:420) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:319) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:51) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:836) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:403) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:243) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.access$100(MasterService.java:63) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:146) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:202) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:262) [elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:225) [elasticsearch-7.17.0.jar:7.17.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [task : {_meta={version=7.17.0}, dynamic=strict, properties={task={properties={node={type=keyword}, headers={type=object, enabled=false}, parent_task_id={type=keyword}, running_time_in_nanos={type=long}, action={type=keyword}, description={type=text}, start_time_in_millis={type=long}, id={type=long}, type={type=keyword}, cancellable={type=boolean}, status={type=object, enabled=false}}}, response={type=object, enabled=false}, completed={type=boolean}, error={type=object, enabled=false}}}]
	at org.elasticsearch.index.mapper.MappingParser.checkNoRemainingFields(MappingParser.java:72) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:145) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MapperService.parseMappings(MapperService.java:503) ~[elasticsearch-7.17.0.jar:7.17.0]
	... 24 more
[2022-02-10T01:45:51,144][WARN ][o.e.p.PersistentTasksClusterService] [HDWPTENG01] persistent task upgrade-system-indices failed
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [task : {_meta={version=7.17.0}, dynamic=strict, properties={task={properties={node={type=keyword}, headers={type=object, enabled=false}, parent_task_id={type=keyword}, running_time_in_nanos={type=long}, action={type=keyword}, description={type=text}, start_time_in_millis={type=long}, id={type=long}, type={type=keyword}, cancellable={type=boolean}, status={type=object, enabled=false}}}, response={type=object, enabled=false}, completed={type=boolean}, error={type=object, enabled=false}}}]
	at org.elasticsearch.index.mapper.MapperService.parseMappings(MapperService.java:505) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MapperService.mergeAndApplyMappings(MapperService.java:419) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:402) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1303) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$3(MetadataCreateIndexService.java:453) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:673) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:451) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:567) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:413) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:420) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:319) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:51) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:836) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:403) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:243) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService.access$100(MasterService.java:63) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:146) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:202) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:262) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:225) ~[elasticsearch-7.17.0.jar:7.17.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [task : {_meta={version=7.17.0}, dynamic=strict, properties={task={properties={node={type=keyword}, headers={type=object, enabled=false}, parent_task_id={type=keyword}, running_time_in_nanos={type=long}, action={type=keyword}, description={type=text}, start_time_in_millis={type=long}, id={type=long}, type={type=keyword}, cancellable={type=boolean}, status={type=object, enabled=false}}}, response={type=object, enabled=false}, completed={type=boolean}, error={type=object, enabled=false}}}]
	at org.elasticsearch.index.mapper.MappingParser.checkNoRemainingFields(MappingParser.java:72) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:145) ~[elasticsearch-7.17.0.jar:7.17.0]
	at org.elasticsearch.index.mapper.MapperService.parseMappings(MapperService.java:503) ~[elasticsearch-7.17.0.jar:7.17.0]
	... 24 more
[2022-02-10T01:45:51,220][WARN ][o.e.p.AllocatedPersistentTask] [HDWPTENG01] attempt to complete task [upgrade-system-indices[c]] with id [upgrade-system-indices] in the [COMPLETED] state
```

**Comment by ngbrown** [comment]
This `.tasks` index also caused issues when migrating from 6.x to 7.x also, as noted in https://github.com/elastic/kibana/issues/29454. A UI was added to delete the system `.tasks` index in https://github.com/elastic/kibana/pull/29774, but it was specifically not going to be ported to Kibana 7.x because "they should have a better solution for dealing with the tasks index by then".

**Comment by redNixon** [comment]
Can confirm that this is occurring on my cluster and that I've aso this situation has that been the root caused some other non-trivial issues that started post upgrade.  My .tasks
```json
{
  ".tasks": {
    "aliases": {},
    "mappings": {
      "dynamic": "strict",
      "_meta": {
        "version": 3
      },
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "error": {
          "type": "object",
          "enabled": false
        },
        "response": {
          "type": "object",
          "enabled": false
        },
        "task": {
          "properties": {
            "action": {
              "type": "keyword"
            },
            "cancellable": {
              "type": "boolean"
            },
            "description": {
              "type": "text"
            },
            "headers": {
              "type": "object",
              "enabled": false
            },
            "id": {
              "type": "long"
            },
            "node": {
              "type": "keyword"
            },
            "parent_id": {
              "type": "keyword"
            },
            "parent_task_id": {
              "type": "keyword"
            },
            "running_time_in_nanos": {
              "type": "long"
            },
            "start_time_in_millis": {
              "type": "long"
            },
            "status": {
              "type": "object",
              "enabled": false
            },
            "type": {
              "type": "keyword"
            }
          }
        }
      }
    },
    "settings": {
      "index": {
        "number_of_shards": "1",
        "auto_expand_replicas": "0-1",
        "provided_name": ".tasks",
        "creation_date": "1554833681037",
        "priority": "2147483647",
        "number_of_replicas": "1",
        "uuid": "KI6tHjCIRxKKEuxaLFSnCw",
        "version": {
          "created": "6060299",
          "upgraded": "7110299"
        }
      }
    }
  }
}
`
```

**Comment by liza-mae** [comment]
This appears to be a duplicate of an issue we are currently investigating: https://github.com/elastic/elasticsearch/issues/83779
