### ISSUE TITLE
[CI] FullClusterRestartIT testSearchTimeSeriesMode failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#83822]
**Build scan:**
https://gradle-enterprise.elastic.co/s/ljtyfyyt5g2rc/tests/:qa:full-cluster-restart:v8.0.0%23oldClusterTest/org.elasticsearch.upgrades.FullClusterRestartIT/testSearchTimeSeriesMode

**Reproduction line:**
`./gradlew ':qa:full-cluster-restart:v8.0.0#oldClusterTest' -Dtests.class="org.elasticsearch.upgrades.FullClusterRestartIT" -Dtests.method="testSearchTimeSeriesMode" -Dtests.seed=5D7C6139DC209842 -Dtests.bwc=true -Dtests.locale=no-NO -Dtests.timezone=Europe/Riga -Druntime.java=17`

**Applicable branches:**
8.0

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.FullClusterRestartIT&tests.test=testSearchTimeSeriesMode

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://127.0.0.1:41499], URI [/testsearchtimeseriesmode], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"unknown setting [index.routing_path] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"}],"type":"illegal_argument_exception","reason":"unknown setting [index.routing_path] please check that any required plugins are installed, or check the breaking changes documentation for removed settings","suppressed":[{"type":"illegal_argument_exception","reason":"unknown setting [index.mode] did you mean [index.codec]?"}]},"status":400}

  at __randomizedtesting.SeedInfo.seed([5D7C6139DC209842:240C684B8CCEB1C7]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:346)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:312)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:287)
  at org.elasticsearch.upgrades.FullClusterRestartIT.createTimeSeriesModeIndex(FullClusterRestartIT.java:326)
  at org.elasticsearch.upgrades.FullClusterRestartIT.testSearchTimeSeriesMode(FullClusterRestartIT.java:231)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by mark-vieira** [comment]
FYI, when opening any pull requests for fixes for this, ensure you add the `test-full-bwc` label to your PR. By default we only run BWC tests against snapshot (in development) versions. You'll need that label to ensure we run tests against release versions as well, which is what we're running into here.

**Comment by mark-vieira** [comment]
The alternative here is to come up with a more sophisticated way to handle feature flags in test clusters. Something like telling the cluster "feature flag x is required for all non-snapshot versions x -> y" and then we apply it if applicable on node startup. If feature flags are going to become increasingly common this seems like something we might need since right now manually dealling with them in conditionals in build scripts is a nightmare.

I've also seen a bunch of other tests failing after the release of 8.0.0 and I can't determine if these are similarly related to missing feature flags or something else. Any  thoughts on https://gradle-enterprise.elastic.co/s/xwfobj3slkwmk?

**Comment by nik9000** [comment]
> I've also seen a bunch of other tests failing after the release of 8.0.0 and I can't determine if these are similarly related to missing feature flags or something else. Any thoughts on https://gradle-enterprise.elastic.co/s/xwfobj3slkwmk?

I had a look at that - I recognized one of them as a wire protocol fix that @salvatore-campagna just made. Do you have it on your branch? The other I don't know about. But getting that far *is* progress.

**Comment by mark-vieira** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/83876 which should resolve these specific failures once backported to 8.0.

**Comment by mark-vieira** [comment]
> I had a look at that - I recognized one of them as a wire protocol fix that @salvatore-campagna just made. Do you have it on your branch? The other I don't know about. But getting that far _is_ progress.

Yeah, even on an up to date 8.0 branch and the feature flag stuff sorted out the mixed cluster tests are still blowing up: https://gradle-enterprise.elastic.co/s/rrc5ceg7syh2k

**Comment by nik9000** [comment]
@salvatore-campagna, could you check this out on Monday?

**Comment by salvatore-campagna** [comment]
O what I see is the following.

The stack trace error message says: `java.lang.NullPointerException: Cannot invoke \"java.lang.Double.doubleValue()\" because \"originalFrom\" is null`

This mean the `InternalRange.java` version used is the one of revision `edffb36c2c5b142be0b7aaadc4d4f6e4be804433`
corresponding to commit `[8.0] Fix bucket keys format for range aggregations on float field (#81801) (#82434)`:

```java
public InternalRange(StreamInput in) throws IOException {
        super(in);
        format = in.readNamedWriteable(DocValueFormat.class);
        keyed = in.readBoolean();
        int size = in.readVInt();
        List<B> ranges = new ArrayList<>(size);
        for (int i = 0; i < size; i++) {
            String key = in.readString();
            double from = in.readDouble();
            Double originalFrom = in.getVersion().onOrAfter(Version.V_7_17_0) ? in.readOptionalDouble() : Double.valueOf(from);
            double to = in.readDouble();
            Double originalTo = in.getVersion().onOrAfter(Version.V_7_17_0) ? in.readOptionalDouble() : Double.valueOf(to);
            long docCount = in.readVLong();
            ranges.add(
                getFactory().createBucket(
                    key,
                    from,
                    originalFrom,
                    to,
                    originalTo,
                    docCount,
                    InternalAggregations.readFrom(in),
                    keyed,
                    format
                )
            );
        }
        this.ranges = ranges;
    }
```

When calling `createBucket` we unbox the `Double` (originalFrom) to a double. That is where the NPE comes from. Anyway, `InternalRange.java` went through 3 other changes with the last one being `fb6e1fb127e3c2bb1683402e9ab083115a56b08d` which should have fixed the issue with possible null values (see the check on null `originalFrom` which results in using `Double.NEGATIVE_INFINITY`.

So, for some reason here, it looks like we are running an older version. My understanding is that this is actually what the test is checking. Am I wrong?

**Comment by salvatore-campagna** [comment]
For test `java.lang.IllegalStateException: unexpected byte [0x30]`, something similar happens...we need to have #83821 which anyway didn't land in `8.0.0`.

**Comment by salvatore-campagna** [comment]
FYI. I am working on https://github.com/elastic/elasticsearch/pull/83509 which, ideally, should fix BWC issues with `8.0.0` for tests failing because of:
* `java.lang.NullPointerException: Cannot invoke \"java.lang.Double.doubleValue()\" because \"originalFrom\" is null`
* `java.lang.IllegalStateException: unexpected byte [0x30]`

**Comment by salvatore-campagna** [comment]
After doing the backport for 8.0 of the fix I still see bwc tests failing for the index settings.

@nik9000 @mark-vieira I can try to have a look at it tomorrow.

**Comment by mark-vieira** [comment]
I believe I'll have to merge and backport https://github.com/elastic/elasticsearch/pull/83876 to get rid of those errors.

**Comment by salvatore-campagna** [comment]
Ok so I will wait for it and do an update branch. Thanks.
