### ISSUE TITLE
SystemIndexManager doesn't cope with missing metadata

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#83890]
### Elasticsearch Version

8.0.0, but probably affects all versions after system indices were introduced

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

The following was observed in the logs of a cluster after upgrading to v8.0.0:

```
[instance-0000000049] failed to notify ClusterStateListener
java.lang.IllegalStateException: Cannot read version string in index .watches
	at org.elasticsearch.indices.SystemIndexManager.readMappingVersion(SystemIndexManager.java:281) ~[elasticsearch-8.0.0.jar:8.0.0]
	at org.elasticsearch.indices.SystemIndexManager.checkIndexMappingUpToDate(SystemIndexManager.java:268) ~[elasticsearch-8.0.0.jar:8.0.0]
```

`SystemIndexManager` expects to find the index's version in a particular, standard place, and in this case it didn’t.
However, I think there’s a gap here, because from looking back at the index templates we used to ship for .watches (for v6 and v7) they didn't set the version in what is now the expected place. We ought to have logic to handle moving from the old world to the new world, and that seems to be missing. I’m not sure that logic would be any different from the data simply being missing.

I’m confused though about why we haven’t hit this before now. It's also surprising because I don’t believe there’s anything special in v8.0.0 here - the problem ought to have surfaced in earlier versions

In terms of what we need to do, I think if `SystemIndexManager` can't find the version metadata, it could assume that the index comes from an earlier version and needs an upgrade. However, `SystemIndexManager` doesn't handle upgrades since they're specific to the plugin / service / whatever that owns the index. So in this case, we need some logic in the Watcher area to affect an upgrade, or at the very least a metadata update, to stop `SystemIndexManager` from complaining.

### Steps to Reproduce

Not sure. Presumably creating an old enough cluster with Watcher running, and upgrading to 8.0.0 would do it.

**Comment by pugnascotia** [comment]
Actually, I wonder if the fix here is a bit simpler that I first thought - there is logic in `SystemIndexManager` where we presume that we need a mapping update if `_meta.version` is null, so I think we can also assume this if `_meta` itself is null.
