### ISSUE TITLE
[CI] SearchWithMinCompatibleSearchNodeIT testMinVersionAsNewVersion failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#83903]
Multiple tests in `SearchWithMinCompatibleSearchNodeIT` have been failing since the release of 8.0.0. This must be some kind of issue with version compatibility logic related to a new major version release. Not sure who the proper area is so feel free to reassign.

**Build scan:**
https://gradle-enterprise.elastic.co/s/p6c3uyqra7ots/tests/:qa:mixed-cluster:v8.0.0%23mixedClusterTest/org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT/testMinVersionAsNewVersion

**Reproduction line:**
`./gradlew ':qa:mixed-cluster:v8.0.0#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT" -Dtests.method="testMinVersionAsNewVersion" -Dtests.seed=13514DF4F8B5132C -Dtests.bwc=true -Dtests.locale=es-CR -Dtests.timezone=US/East-Indiana -Druntime.java=17`

**Applicable branches:**
master, 8.1

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT&tests.test=testMinVersionAsNewVersion

**Failure excerpt:**
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

  at __randomizedtesting.SeedInfo.seed([13514DF4F8B5132C:7CC6377F9A70328C]:0)
  at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
  at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
  at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
  at java.util.Objects.checkIndex(Objects.java:359)
  at java.util.ArrayList.get(ArrayList.java:427)
  at org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT.prepareTestData(SearchWithMinCompatibleSearchNodeIT.java:54)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by cbuescher** [comment]
Local reproduction didn't immediately work for me, but looking at the failure, the problem already happens at test setup where the array that should hold nodes of the current version is empty. The node metadata list is retrieved earlier on by a rest client from the test cluster via the "_nodes" API, so that API response is most likely already missing to report the new version nodes. I wonder if all the tests in the mixed cluster tests use the same cluster setup and the node e.g. died for some reason in a previous test. There are some failing rest tests in this CI run, e.g. the first is https://gradle-enterprise.elastic.co/s/duryqccfqji7s/tests/:qa:mixed-cluster:v8.0.0%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=search.aggregation%2F41_date_range%2FDate%20Range%20Missing%7D?top-execution=1 with an "illegal_state_exception" that might have killed a node. Need to do some more digging on that though.

**Comment by cbuescher** [comment]
I think the failure in `SearchWithMinCompatibleSearchNodeIT testMinVersionAsNewVersion` is only a result of the earlier rest test failure mentioned above, which should be fixed by https://github.com/elastic/elasticsearch/pull/83509 and backports, so I'm closing this.

**Comment by cbuescher** [comment]
I looked at [the logs](https://gradle-enterprise.elastic.co/s/z5m2afgdwunvg/console-log/raw) and currently believe the missing nodes at startup of `SearchWithMinCompatibleSearchNodeIT` are the follow up of some other cluster error. I found cases the uncaught `DocumentMapper` excections mentioned in https://github.com/elastic/elasticsearch/issues/86887 in here too and now wonder if the issues are linked.

**Comment by cbuescher** [comment]
Closing as this seem to be follow-up failures to previous failures in mixed cluster tests. If someone wants to reopen it please also check if there are any other tests failing in conjunction, we might want to separate this integration test from other yaml test suites in that case.
