### ISSUE TITLE
Entire FollowIndexSecurityIT suite sometimes fails

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#84156]
There have been several build failures in the past few days where the whole `FollowIndexSecurityIT` suite fails with connection errors:

```
java.net.ConnectException: Connection refused
        at __randomizedtesting.SeedInfo.seed([D5A8084EC9E25925:E6A6A837ACA01A02]:0)
        at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:918)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:299)
```

Some interesting errors in logs:
```
[2022-02-14T23:30:20,568][WARN ][o.e.t.TcpTransport       ] [follow-cluster-0] exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:41444, remoteAddress=127.0.0.1/127.0.0.1:38375, profile=default}], closing connection
»  org.elasticsearch.ElasticsearchSecurityException: action [indices:admin/seq_no/renew_retention_lease] is unauthorized for user [test_ccr] with roles [ccruser], this action is granted by the index privileges [manage,all]
»  	at org.elasticsearch.xpack.core.security.support.Exceptions.authorizationError(Exceptions.java:36) ~[?:?]
»  	at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:919) ~[?:?]
»  	at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.handleFailure(AuthorizationService.java:978) ~[?:?]
»  	at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:963) ~[?:?]
```

Examples:
* https://gradle-enterprise.elastic.co/s/tqlnn3z6a5i7m
* https://gradle-enterprise.elastic.co/s/eaj7lxro2bv4o
* https://gradle-enterprise.elastic.co/s/hmhadf6fezkli

**Comment by ywangd** [comment]
This seems to be the same issue as #84006. I raised it as a bug (#61308) a while back. I felt it was a documentation issue and never had time to dig into it.

**Comment by DaveCTurner** [comment]
Tim, Yang and I discussed this earlier and concluded that we should give the user in the test the privileges to renew retention leases. I've muted the test suite and opened a PR to clarify that this isn't running in system context in #84409.
