### ISSUE TITLE
bulk index response from 8.0.0 not compatible although headers are set

### ISSUE THREAD

**Issue by sothawo** [elastic/elasticsearch#84173]
### Elasticsearch Version

Elasticsearch 8.0.0 running from docker image

### Java Version

_bundled_

### OS Version

Elasticsearch docker

### Problem Description

When sending a bulk index request to Elasticsearch 8.0.0 with the compatibility headers set for a client version 7, the bulk response is missing the `_type` property in the index answer. This causes the client failing to parse the response.

```
Unable to parse response body for Response{requestLine=POST /_bulk?timeout=1m HTTP/1.1, host=http://localhost:9200, response=HTTP/1.1 200 OK}] with root cause

java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:208) ~[na:na]
	at org.elasticsearch.action.DocWriteResponse.<init>(DocWriteResponse.java:116) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:43) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:28) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.index.IndexResponse$Builder.build(IndexResponse.java:96) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.index.IndexResponse$Builder.build(IndexResponse.java:93) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.bulk.BulkItemResponse.fromXContent(BulkItemResponse.java:148) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.bulk.BulkResponse.fromXContent(BulkResponse.java:177) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2011) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$8(RestHighLevelClient.java:1673) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1749) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1702) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1672) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:577) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
```

### Steps to Reproduce

send a bulk index request with the `RestHighLevelClient` 7.15.2 to the cluster

```
POST http://localhost:9200/_bulk?timeout=1m HTTP/1.1
Accept: application/vnd.elasticsearch+json;compatible-with=7
Content-Type: application/vnd.elasticsearch+json;compatible-with=7
Authorization: Basic *****
Content-Length: 121
Host: localhost:9200
Proxy-Connection: Keep-Alive
User-Agent: elasticsearch-java/7.15.2-SNAPSHOT (Java/17.0.2)
X-Elastic-Client-Meta: es=7.15.2-SNAPSHOT,jv=17,t=7.15.2-SNAPSHOT,hc=4.1.5
```
```
{"index":{"_index":"entities","_id":"1"}}
{"id":"1","text":"text-1"}
```
This will return
```
HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-type: application/vnd.elasticsearch+json;compatible-with=7
content-length: 202
```
```
{"took":13,"errors":false,"items":[{"index":{"_index":"entities","_id":"1","_version":5,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":40,"_primary_term":3,"status":200}}]}
```
When sending the same request to Elasticsearch 7.17.0 the following body is returned>
```
{"took":456,"errors":false,"items":[{"index":{"_index":"entities","_type":"_doc","_id":"1","_version":2,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":10,"_primary_term":2,"status":200}}]}
```

Here the `_type` field is returned which is missing in the response from 8.0.0 .

Btw, when not using bulk, but a normal index for a single document, then the `_type` is returned, it 's misisng in the bulk response.

**Comment by nik9000** [comment]
Attached CRUD and REST to this because I'm not sure which folks own this.

**Comment by p-kimberley** [comment]
I can confirm this issue persists with the recently released `7.17.1` Java High-Level REST Client, against a `8.0.0` Elasticsearch cluster. I'm getting the same error message as the OP.

**Comment by pjmeisch-cc** [comment]
This is not a client issue, but a not compatible response from the server

**Comment by idrissneumann** [comment]
Is it safe to upgrade `elasticsearch-rest-high-level-client` to the 8.0.0-alpha2 version (which is older than the 7.17.1 we're already using right now) ? Because we're experiencing the same kind of issues (not on bulk requests though):

```
{"instant":{"epochSecond":1648543298,"nanoOfSecond":702000000},"thread":"Thread-3057","level":"ERROR","loggerName":"tn.prodit.network.se.exception.TechnicalException","message":"java.io.IOException: Unable to parse response body for Response{requestLine=PUT /internal-offer/_doc/1500_null?timeout=1m HTTP/1.1, host=https://elasticsearch.comwork.io:443, response=HTTP/1.1 200 OK}","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","contextMap":{},"threadId":3085,"threadPriority":5}
Caused by: java.io.IOException: Unable to parse response body for Response{requestLine=PUT /internal-offer/_doc/1500_null?timeout=1m HTTP/1.1, host=https://elasticsearch.comwork.io:443, response=HTTP/1.1 200 OK}
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2190)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105)
	at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:1241)
	at tn.prodit.network.se.utils.singleton.impl.RestHighLevelClientImpl.index(RestHighLevelClientImpl.java:30)
	at tn.prodit.network.se.route.AbstractIndexationDeltaRoute.indexationNewData(AbstractIndexationDeltaRoute.java:169)
	... 3 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.elasticsearch.action.DocWriteResponse.<init>(DocWriteResponse.java:116)
	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:43)
	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:28)
	at org.elasticsearch.action.index.IndexResponse$Builder.build(IndexResponse.java:96)
	at org.elasticsearch.action.index.IndexResponse.fromXContent(IndexResponse.java:78)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484)
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$8(RestHighLevelClient.java:2105)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2188)
```

And it appears since the upgrade of our elastic cluster to the 8.0.0 version.

Thanks in advance.

**Comment by idrissneumann** [comment]
Thanks @swallez we enabled the `apiCompatibilityMode` and all our issues goes away.

However, we'll add the migration to this client in our roadmap: https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html (`co.elastic.clients:elasticsearch-java:8.1.1`).

**Comment by anmol8118** [comment]
Hi @sothawo , 
I tried setting compatible headers in my existing rest high-level client, but unfortunately, I'm still getting the following error:

"java.lang.IllegalStateException: Unsupported Content-Type: application/vnd.elasticsearch+json;compatible-with=7"

Can you please help me here?

Elastic Search cluster: 8.5.3v
HLRC: 7.6.2v

**Comment by swallez** [comment]
@anmol8118 you should use the latest HLRC (version 7.17.x) and enable compatibility mode as described above.

**Comment by aspexi** [comment]
@swallez hi there, I'm struggling with this issue with 7.17.14, ES version 8.8.1, compatibility mode enabled, additional headers added:

```
customHeaders.put(HttpHeaders.ACCEPT, "application/vnd.elasticsearch+json;compatible-with=7");
customHeaders.put(HttpHeaders.CONTENT_TYPE, "application/vnd.elasticsearch+json;compatible-with=7");
```

Network traffic anlyse confirms presence of those in requests and responses, the _type field is present while still hitting:

```
java.io.IOException: Unable to parse response body for Response{requestLine=POST /_bulk?timeout=1m HTTP/1.1, host=http://localhost:9200, response=HTTP/1.1 200 OK}
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at org.elasticsearch.action.DocWriteResponse.<init>(DocWriteResponse.java:116)
```

What else to check here? Only _bulk requests are affected.

**Comment by Pedrocaz** [comment]
> @swallez hi there, I'm struggling with this issue with 7.17.14, ES version 8.8.1, compatibility mode enabled, additional headers added:
> 
> ```
> customHeaders.put(HttpHeaders.ACCEPT, "application/vnd.elasticsearch+json;compatible-with=7");
> customHeaders.put(HttpHeaders.CONTENT_TYPE, "application/vnd.elasticsearch+json;compatible-with=7");
> ```
> 
> Network traffic anlyse confirms presence of those in requests and responses, the _type field is present while still hitting:
> 
> ```
> java.io.IOException: Unable to parse response body for Response{requestLine=POST /_bulk?timeout=1m HTTP/1.1, host=http://localhost:9200, response=HTTP/1.1 200 OK}
> Caused by: java.lang.NullPointerException
> 	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
> 	at org.elasticsearch.action.DocWriteResponse.<init>(DocWriteResponse.java:116)
> ```
> 
> What else to check here? Only _bulk requests are affected.

I'm having the same problem, any news on this issue?

**Comment by awakelee** [comment]
any news here?

**Comment by guyuwei-love** [comment]
@sothawo Hi, Which version should I introduce to solve this problem?
<dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>???</version>
        </dependency>

**Comment by ShruthiKNataraj** [comment]
Hi, I am facing same issue. Did we find the solution?
