### ISSUE TITLE
[CI] PasswordToolsTests test40GeneratePasswordsBootstrapAlreadySet failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#84226]
This seems to be windows specific, a process that is expected seems to be missing.

**Build scan:**
https://gradle-enterprise.elastic.co/s/3u52yxwnisswc/tests/:qa:os:destructiveDistroTest.default-windows-archive/org.elasticsearch.packaging.test.PasswordToolsTests/test40GeneratePasswordsBootstrapAlreadySet

**Reproduction line:**
`null`

**Applicable branches:**
8.0

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.PasswordToolsTests&tests.test=test40GeneratePasswordsBootstrapAlreadySet

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [powershell.exe -Command Get-Process -Id 9004 | Stop-Process -Force; Wait-Process -Id 9004]
   result: exitCode = [1] stdout = [] stderr = [Wait-Process : Cannot find a process with the process identifier 9004.
At line:1 char:45
+ Get-Process -Id 9004 | Stop-Process -Force; Wait-Process -Id 9004
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (9004:Int32) [Wait-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenId,Microsoft.PowerShell.Commands.WaitProcessCommand]

  at __randomizedtesting.SeedInfo.seed([461F33367744C666:6F486D9B28AC2270]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.util.Archives.lambda$stopElasticsearch$10(Archives.java:424)
  at org.elasticsearch.packaging.util.Platforms.onWindows(Platforms.java:57)
  at org.elasticsearch.packaging.util.Archives.stopElasticsearch(Archives.java:423)
  at org.elasticsearch.packaging.test.PackagingTestCase.stopElasticsearch(PackagingTestCase.java:337)
  at org.elasticsearch.packaging.test.PackagingTestCase.assertWhileRunning(PackagingTestCase.java:290)
  at org.elasticsearch.packaging.test.PasswordToolsTests.test40GeneratePasswordsBootstrapAlreadySet(PasswordToolsTests.java:115)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by cbuescher** [comment]
From the logs:
```
powershell.exe, -Command, Get-Process -Id 9004 | Stop-Process -Force; Wait-Process -Id 9004] exitCode = [1] stdout = [] stderr = [Wait-Process : Cannot find a process with the process identifier 9004.
At line:1 char:45
+ Get-Process -Id 9004 | Stop-Process -Force; Wait-Process -Id 9004
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (9004:Int32) [Wait-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenId,Microsoft.PowerShell.Commands.WaitProcessCommand]
```
and
```
[2022-02-22T07:03:38,326][INFO ][o.e.p.u.Shell            ] [TEST-PasswordToolsTests.test40GeneratePasswordsBootstrapAlreadySet-seed#[461F33367744C666]-workerest_thread_info] Ran: [powershell.exe, -Command, $processInfo = New-Object System.Diagnostics.ProcessStartInfo; $processInfo.FileName = 'C:\tmp\elasticsearch\bin\elasticsearch.bat'; $processInfo.Arguments = '-v -p C:\tmp\elasticsearch\elasticsearch.pid'; $processInfo.RedirectStandardOutput = $true; $processInfo.RedirectStandardError = $true; $processInfo.RedirectStandardInput = $true; $processInfo.UseShellExecute = $false; $process = New-Object System.Diagnostics.Process; $process.StartInfo = $processInfo; $outScript = { $EventArgs.Data | Out-File -Encoding UTF8 -Append 'C:\tmp\elasticsearch\logs\output.out' }; $errScript = { $EventArgs.Data | Out-File -Encoding UTF8 -Append 'C:\tmp\elasticsearch\logs\output.err' }; $stdOutEvent = Register-ObjectEvent -InputObject $process -Action $outScript -EventName 'OutputDataReceived'; $stdErrEvent = Register-ObjectEvent -InputObject $process -Action $errScript -EventName 'ErrorDataReceived'; $process.Start() | Out-Null; $process.BeginOutputReadLine(); $process.BeginErrorReadLine(); $process.StandardInput.WriteLine('null'); Wait-Process -Timeout 25 -Id $process.Id; $process.Id;] exitCode = [0] stdout = [3400] stderr = [Wait-Process : This command stopped operation because process "cmd (3400)" is not stopped in the specified time-out.
At line:1 char:1031
+ ... t.WriteLine('null'); Wait-Process -Timeout 25 -Id $process.Id; $proce ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (System.Diagnostics.Process (cmd):Process) [Wait-Process], TimeoutException
    + FullyQualifiedErrorId : ProcessNotTerminated,Microsoft.PowerShell.Commands.WaitProcessCommand]
[2022-02-22T07:03:38,327][INFO ][o.e.p.u.Shell            ] [TEST-PasswordToolsTests.test40GeneratePasswordsBootstrapAlreadySet-seed#[461F33367744C666]-workerest_thread_info] Cleanup of output files failed
java.io.UncheckedIOException: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+8.0+multijob+packaging-tests-windows\os\windows-2022\qa\os\build\testrun\destructiveDistroTest.default-windows-archive\temp\org.elasticsearch.packaging.util.Shell6237293417882706357.out: The process cannot access the file because it is being used by another process
	at org.elasticsearch.packaging.util.FileUtils.deleteIfExists(FileUtils.java:342) ~[test/:?]
	at org.elasticsearch.packaging.util.Shell.runScriptIgnoreExitCode(Shell.java:194) ~[test/:?]
	at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:141) ~[test/:?]
	at org.elasticsearch.packaging.util.Shell.run(Shell.java:73) ~[test/:?]
	at org.elasticsearch.packaging.util.Archives.runElasticsearchStartCommand(Archives.java:344) ~[test/:?]
	at org.elasticsearch.packaging.test.PackagingTestCase.runElasticsearchStartCommand(PackagingTestCase.java:316) ~[test/:?]
	at org.elasticsearch.packaging.test.PackagingTestCase.assertWhileRunning(PackagingTestCase.java:265) ~[test/:?]
	at org.elasticsearch.packaging.test.PasswordToolsTests.test40GeneratePasswordsBootstrapAlreadySet(PasswordToolsTests.java:115) ~[test/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) ~[randomizedtesting-runner-2.7.7.jar:?]
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946) ~[randomizedtesting-runner-2.7.7.jar:?]
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982) ~[randomizedtesting-runner-2.7.7.jar:?]
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) ~[randomizedtesting-runner-2.7.7.jar:?]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55) ~[junit-4.12.jar:4.12]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55) ~[junit-4.12.jar:4.12]
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) ~[randomizedtesting-runner-2.7.7.jar:?]
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) ~[randomizedtesting-runner-2.7.7.jar:?]
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831) ~[randomizedtesting-runner-2.7.7.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+8.0+multijob+packaging-tests-windows\os\windows-2022\qa\os\build\testrun\destructiveDistroTest.default-windows-archive\temp\org.elasticsearch.packaging.util.Shell6237293417882706357.out: The process cannot access the file because it is being used by another process
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275) ~[?:?]
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105) ~[?:?]
	at java.nio.file.Files.delete(Files.java:1152) ~[?:?]
	at org.elasticsearch.packaging.util.FileUtils.deleteIfExists(FileUtils.java:340) ~[test/:?]
	... 21 more
```

**Comment by mark-vieira** [comment]
I think the root cause here is the initial attempt to start ES for this test timed out.

```
stderr = [Wait-Process : This command stopped operation because process "cmd (3400)" is not stopped in the specified time-out.
```

Let's keep an eye on this and bump the timeout if necessary.
