### ISSUE TITLE
failure in org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=vectors/60_knn_and_binary_dv_fields_api/empty dense vector throws for vector accesses}

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#84232]
### CI Link

https://gradle-enterprise.elastic.co/s/uly2b5kj6erfa

### Repro line

  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=vectors/60_knn_and_binary_dv_fields_api/empty dense vector throws for vector accesses}" -Dtests.seed=DF0CDE4908AC363 -Dtests.locale=ar-YE -Dtests.timezone=America/North_Dakota/Center -Druntime.java=17

### Does it reproduce?

Yes

### Applicable branches

master

### Failure excerpt

```
  2> java.lang.AssertionError: Failure at [vectors/60_knn_and_binary_dv_fields_api:203]: expected [400] status code but api [search] returned [200 OK] [{"took":163,"timed_out":false,"_shards":{"total":2,"successful":1,"skipped":0,"failed":1,"failures":[{"shard":1,"index":"test-index","node":"RwRAYt1VTDW6Oupq9TjsJw","reason":{"type":"script_exception","reason":"runtime error","script_stack":["org.elasticsearch.xpack.vectors.query.DenseVector$1.getVector(DenseVector.java:209)","field(params.field).get().vector[2]\n","                         ^---- HERE"],"script":"field(params.field).get().vector[2] ...","lang":"painless","position":{"offset":25,"start":0,"end":36},"caused_by":{"type":"illegal_argument_exception","reason":"Dense vector value missing for a field, use isEmpty() to check for a missing vector value"}}}]},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}]
        at __randomizedtesting.SeedInfo.seed([DF0CDE4908AC363:85A4F23E3E76AE9B]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:493)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
        at java.base/java.lang.Thread.run(Thread.java:833)

        Caused by:
        java.lang.AssertionError: expected [400] status code but api [search] returned [200 OK] [{"took":163,"timed_out":false,"_shards":{"total":2,"successful":1,"skipped":0,"failed":1,"failures":[{"shard":1,"index":"test-index","node":"RwRAYt1VTDW6Oupq9TjsJw","reason":{"type":"script_exception","reason":"runtime error","script_stack":["org.elasticsearch.xpack.vectors.query.DenseVector$1.getVector(DenseVector.java:209)","field(params.field).get().vector[2]\n","                         ^---- HERE"],"script":"field(params.field).get().vector[2] ...","lang":"painless","position":{"offset":25,"start":0,"end":36},"caused_by":{"type":"illegal_argument_exception","reason":"Dense vector value missing for a field, use isEmpty() to check for a missing vector value"}}}]},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}]
            at org.junit.Assert.fail(Assert.java:88)
            at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:365)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:482)
            ... 39 more```

**Comment by stu-elastic** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/84575, last master failure was on [March 2nd](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Chicago&tests.container=org.elasticsearch.xpack.test.rest.XPackRestIT&tests.sortField=FAILED&tests.test=test%20%7Bp0%3Dvectors/60_knn_and_binary_dv_fields_api/empty%20dense%20vector%20throws%20for%20vector%20accesses%7D&tests.unstableOnly=true).
