### ISSUE TITLE
[CI] DatafeedCcsIT testDatafeedWithCcsRemoteHealthy failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#84290]
**Build scan:**
https://gradle-enterprise.elastic.co/s/j2ejoyp6jzmis/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.DatafeedCcsIT/testDatafeedWithCcsRemoteHealthy

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.DatafeedCcsIT.testDatafeedWithCcsRemoteHealthy" -Dtests.seed=2B74FA46CB2D4E50 -Dtests.locale=zh-SG -Dtests.timezone=Etc/GMT-12 -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.DatafeedCcsIT&tests.test=testDatafeedWithCcsRemoteHealthy

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is <closed>
     but: was <opened>

  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ml.integration.DatafeedCcsIT.lambda$testDatafeedWithCcsRemoteHealthy$0(DatafeedCcsIT.java:114)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1068)
  at org.elasticsearch.xpack.ml.integration.DatafeedCcsIT.testDatafeedWithCcsRemoteHealthy(DatafeedCcsIT.java:112)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by droberts195** [comment]
This looks like the test just ran incredibly slowly.  CI runs 8 or 16 test suites in parallel, and this is a pretty complicated test that fires up two multi-node clusters, so there was probably heavy resource contention while it was running in CI that isn't seen when running the ML internal cluster test suite on its own.  I'll increase the timeout for the datafeed to finish.

**Comment by pgomulka** [comment]
another one https://gradle-enterprise.elastic.co/s/zd3cejw5tr6ce/tests/overview?outcome=failed

**Comment by tvernum** [comment]
Failed again, sorry.
https://gradle-enterprise.elastic.co/s/pscx3ar5pwzfa/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.DatafeedCcsIT/testDatafeedWithCcsRemoteHealthy?top-execution=1

**Comment by droberts195** [comment]
I've added some test logging in https://github.com/elastic/elasticsearch/pull/84331 to help understand what's happening.

**Comment by gmarouli** [comment]
One more failure: https://gradle-enterprise.elastic.co/s/dvfkcwwsokypm/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.DatafeedCcsIT/testDatafeedWithCcsRemoteHealthy

**Comment by droberts195** [comment]
The test logging helped.  The problem is that the test is just running incredibly slowly when so many other test suites are running in parallel:

<img width="1318" alt="Screenshot 2022-03-04 at 09 58 29" src="https://user-images.githubusercontent.com/7405510/156742015-22a4a1ef-b0b3-454b-9b81-2b3d8271767f.png">

This multi-cluster test is spinning up local and remote clusters each with 3 nodes, and then that's running in parallel with many other heavyweight test suites, so it's not surprising the CI workers sometimes struggle with the load if the other test suites also happen to run a test that involves multiple nodes at the same time.

So the solution is just to increase the time allowed even further.
