### ISSUE TITLE
Support asynchronously delete indices

### ISSUE THREAD

**Issue by tianchen92** [elastic/elasticsearch#84385]
### Description

version: 7.10
Currently indices deletion is proceed in a synchronous manner, this is fine in most cases. 
However, if the deletion is slow due to big data and poor hardware(cold data node), it would block other cluster state changes  (indices creation, recovery etc).
We have met the problem when we fully restart a cluster(with SSD and HDD nodes) with some indices deletion at the same time, the HDD nodes had high IOPS and the recovery process is extremely slow. We printed the jstack traces and files deleting related are as follows. HDD nodes have poor performance compared with SSD, and this will block other cluster state changes. 

>"elasticsearch[1634006546000014732][clusterApplierService#updateTask][T#1]" #46 daemon prio=5 os_prio=0 cpu=11851.52ms elapsed=412.36s allocated=1895M defined_classes=1011 tid=0x00007ff1ef7aa500 nid=0x19ac runnable  [0x00007ff1c4bfc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.UnixNativeDispatcher.unlink0(java.base@11.0.9.1-ga/Native Method)
	at sun.nio.fs.UnixNativeDispatcher.unlink(java.base@11.0.9.1-ga/UnixNativeDispatcher.java:156)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(java.base@11.0.9.1-ga/UnixFileSystemProvider.java:236)
	at sun.nio.fs.AbstractFileSystemProvider.delete(java.base@11.0.9.1-ga/AbstractFileSystemProvider.java:105)
	at java.nio.file.Files.delete(java.base@11.0.9.1-ga/Files.java:1141)
	at org.elasticsearch.core.internal.io.IOUtils$1.visitFile(IOUtils.java:243)
	at org.elasticsearch.core.internal.io.IOUtils$1.visitFile(IOUtils.java:222)
	at java.nio.file.Files.walkFileTree(java.base@11.0.9.1-ga/Files.java:2724)
	at java.nio.file.Files.walkFileTree(java.base@11.0.9.1-ga/Files.java:2796)
	at org.elasticsearch.core.internal.io.IOUtils.rm(IOUtils.java:222)
	at org.elasticsearch.core.internal.io.IOUtils.rm(IOUtils.java:202)
	at org.elasticsearch.env.NodeEnvironment.deleteIndexDirectoryUnderLock(NodeEnvironment.java:642)
	at org.elasticsearch.env.NodeEnvironment.deleteIndexDirectorySafe(NodeEnvironment.java:626)
	at org.elasticsearch.indices.IndicesService.deleteIndexStoreIfDeletionAllowed(IndicesService.java:1114)
	at org.elasticsearch.indices.IndicesService.deleteIndexStore(IndicesService.java:1101)
	at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:1007)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:304)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:238)
	- locked <0x0000001002c15b18> (a org.elasticsearch.indices.cluster.IndicesClusterStateService)
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:510)
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:500)
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:471)
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418)
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:68)
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:162)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.9.1-ga/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.9.1-ga/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.9.1-ga/Thread.java:834)

Perhaps we could add a settings to support delete index files in another thread, only changing the indices memory structure and return quickly while the time-consuming deleting process executing in the background. The default settings value make sure it wont't break current behavior, and one could turn on this flag when deleting big indices in nodes with poor performance.

I think it not too much work and i would like to take this issue if we decide to do so, thanks!

**Comment by DaveCTurner** [comment]
This is broadly related to #74149 in the sense that the fix I envision for #74149 would make index deletion happen asynchronously. There's a more general point that the `IndicesClusterStateService` does a bunch of other IO on the cluster applier thread, it's not just deleting indices, and we really should move all this work into the background.

> I think it not too much work

I think it's a pretty big task but maybe you see some shortcut that I don't.

> Perhaps we could add a settings

IMO it should not be optional. Even optional behaviour must still work correctly, but in this case if it works correctly then I think we should always use it.

**Comment by tianchen92** [comment]
@DaveCTurner Thanks for your reply.
>I think it's a pretty big task but maybe you see some shortcut that I don't.

`IndicesClusterStateService#deleteIndices` will invoke `IndicesService#removeIndex` or `IndicesService#deleteUnassignedIndex` or `IndicesService#verifyIndexIsDeleted` according to different case, and finally call `IndicesService#deleteIndexStoreIfDeletionAllowed` which does the actual files deletion. I think we could simply skip `deleteIndexStoreIfDeletionAllowed` and add it to `pendingDeletes` (we now already have mechanism to process pendingDeletes), and at the end of IndicesClusterStateService#deleteIndices`, use a single thread(i.e. generic) to delete pendingDeletes in turn.

>IMO it should not be optional. Even optional behaviour must still work correctly, but in this case if it works correctly then I think we should always use it.

Agreed, I proposed  to add settings because i am afraid that async delete is not normal case. Since we all think this work should be done in background, it's absolutely ok not to add settings.

**Comment by tianchen92** [comment]
ping @DaveCTurner

**Comment by DaveCTurner** [comment]
What more do you need from me here @tianchen92?

**Comment by tianchen92** [comment]
> What more do you need from me here @tianchen92?

Do you think the solution I mentioned above is reasonable? and if so i would start the work. thanks :)

**Comment by DaveCTurner** [comment]
Sorry, there's not enough info here for me to say whether it's going to work or not. It's definitely something we'd like to fix, but it's not a high priority for us right now. If you have an idea for a fix then please open a PR so we can see some more details.

**Comment by tianchen92** [comment]
I have opened a draft PR to help understand the idea. @DaveCTurner 
https://github.com/elastic/elasticsearch/pull/85015

**Comment by tlrx** [comment]
We discussed this in a small group today and we agreed that indices deletions has various issues today that are worth to be addressed together. Those issues and a proposed solution are well captured in #74149, so we're going to close this issue and the linked pull request.
