### ISSUE TITLE
[CI] GroupMappingIT testGroupMapping failing

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#84586]
**Build scan:**
https://gradle-enterprise.elastic.co/s/fmiiv5kmsm2uu/tests/:x-pack:qa:third-party:active-directory:test/org.elasticsearch.xpack.security.authc.ldap.GroupMappingIT/testGroupMapping

**Reproduction line:**
`./gradlew ':x-pack:qa:third-party:active-directory:test' --tests "org.elasticsearch.xpack.security.authc.ldap.GroupMappingIT.testGroupMapping" -Dtests.seed=D51FD3E394A6008D -Dtests.locale=es-GT -Dtests.timezone=Europe/Sarajevo -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.authc.ldap.GroupMappingIT&tests.test=testGroupMapping

**Failure excerpt:**
```
org.elasticsearch.ElasticsearchSecurityException: unable to authenticate user [odin] for action [indices:data/write/index]

  at __randomizedtesting.SeedInfo.seed([D51FD3E394A6008D:9718CF59E5601BBC]:0)
  at org.elasticsearch.xpack.core.security.support.Exceptions.authenticationError(Exceptions.java:20)
  at org.elasticsearch.xpack.core.security.authc.DefaultAuthenticationFailureHandler.createAuthenticationError(DefaultAuthenticationFailureHandler.java:186)
  at org.elasticsearch.xpack.core.security.authc.DefaultAuthenticationFailureHandler.failedAuthentication(DefaultAuthenticationFailureHandler.java:106)
  at org.elasticsearch.xpack.security.authc.AuthenticationService$AuditableTransportRequest.authenticationFailed(AuthenticationService.java:332)
  at org.elasticsearch.xpack.security.authc.RealmsAuthenticator.consumeNullUser(RealmsAuthenticator.java:269)
  at org.elasticsearch.xpack.security.authc.RealmsAuthenticator.lambda$consumeToken$3(RealmsAuthenticator.java:212)
  at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:136)
  at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31)
  at org.elasticsearch.xpack.core.common.IteratingActionListener.onResponse(IteratingActionListener.java:132)
  at org.elasticsearch.xpack.security.authc.RealmsAuthenticator.lambda$consumeToken$0(RealmsAuthenticator.java:190)
  at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:136)
  at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.lambda$authenticateWithCache$3(CachingUsernamePasswordRealm.java:221)
  at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:136)
  at org.elasticsearch.xpack.security.authc.ldap.LdapRealm$LdapSessionActionListener.onFailure(LdapRealm.java:308)
  at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:38)
  at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactory.lambda$getSessionWithoutPool$2(ActiveDirectorySessionFactory.java:163)
  at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:144)
  at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:77)
  at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils$2.onFailure(LdapUtils.java:204)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
  at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils.maybeForkAndRun(LdapUtils.java:102)
  at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils.maybeForkThenBind(LdapUtils.java:212)
  at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactory$ADAuthenticator.authenticate(ActiveDirectorySessionFactory.java:320)
  at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactory.getSessionWithoutPool(ActiveDirectorySessionFactory.java:161)
  at org.elasticsearch.xpack.security.authc.ldap.PoolingSessionFactory.session(PoolingSessionFactory.java:110)
  at org.elasticsearch.xpack.security.authc.ldap.LdapRealm.lambda$doAuthenticate$1(LdapRealm.java:147)
  at org.elasticsearch.xpack.security.authc.ldap.LdapRealm$CancellableLdapRunnable.doRun(LdapRealm.java:343)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:776)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by tvernum** [comment]
> [2022-03-02T20:38:19,939][WARN ][o.e.x.s.a.RealmsAuthenticator] [node_s2] Authentication to realm external failed - authenticate failed (Caused by LDAPException(resultCode=85 (timeout), errorMessage='A client-side timeout was encountered while waiting 5000ms for a response to simple bind request with message ID 1 for user 'odin@ad.test.elasticsearch.com' from server localhost:49182.', ldapSDKVersion=6.0.3, revision=405ee52a554f9867e81d4598a5b2f97beabeb29a))
