### ISSUE TITLE
XPack REST tests can exceed disk watermark

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#84583]
Some CI failures have popped up in the xpack REST tests because the node exceeds the low disk watermark. Some examples:
* https://gradle-enterprise.elastic.co/s/wwp2kj4lciuui
* https://gradle-enterprise.elastic.co/s/eopbgip2r6xo6
* https://gradle-enterprise.elastic.co/s/dnz2plf5ie7k6

The tests that report failures are `deprecation/10_basic` and `data_streams/10_data_stream_resolvability`, but it's not clear that they're actually causing the issue. 

Failure excerpt:
```
   1> [2022-03-01T05:49:30,059][INFO ][o.e.x.t.r.XPackRestIT    ] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "cluster_settings" : [ ],
  1>       "node_settings" : [
  1>         {
  1>           "level" : "critical",
  1>           "message" : "Disk usage exceeds low watermark",
  1>           "url" : "https://ela.st/es-deprecation-7-disk-watermark-exceeded",
  1>           "details" : "Disk usage exceeds low watermark, which will prevent reindexing indices during upgrade. Get disk usage on all nodes below the value specified in cluster.routing.allocation.disk.watermark.low (nodes impacted: [yamlRestTest-0])",
  1>           "resolve_during_rolling_upgrade" : false
  1>         }
  1>       ],
  1>       "index_settings" : { },
  1>       "ml_settings" : [ ]
  1>     }
  1>   }
  1> }]
  1> [2022-03-01T05:49:30,218][INFO ][o.e.x.t.r.XPackRestIT    ] [test] [p0=data_streams/10_data_stream_resolvability/Verify data stream resolvability in migrations API] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=data_streams/10_data_stream_resolvability/Verify data stream resolvability in migrations API}" -Dtests.seed=BACCA71A0230AC25 -Dtests.locale=es-AR -Dtests.timezone=Pacific/Galapagos -Druntime.java=17
  2> java.lang.AssertionError: Failure at [data_streams/10_data_stream_resolvability:347]: field [node_settings] doesn't have length [0]
    Expected: <0>
         but: was <1>
        at __randomizedtesting.SeedInfo.seed([BACCA71A0230AC25:329898C0ACCCC1DD]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:493)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)
```

**Comment by jtibshirani** [comment]
I tagged the data management team since the test failures relate to data streams, but it is not clear that they are really the cause -- please feel free to redirect the issue.

**Comment by dimitris-athanasiou** [comment]
Another occurrence: https://gradle-enterprise.elastic.co/s/jjli6wup3uh7g

**Comment by mark-vieira** [comment]
These all seem specific to our Mac workers. Given I've removed testing on Mac in c2e488cd3f0e7becf29a36da49ef44cb8b923b0b I think we can close this issue.
