### ISSUE TITLE
[CI] Failure in search.aggregations/200_top_hits/explain

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#84590]
### CI Link

https://gradle-enterprise.elastic.co/s/3stpdnruqbul4

### Repro line

./gradlew ':qa:mixed-cluster:v7.1.1#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/200_top_hits/explain}" -Dtests.seed=E69913F3CCC37076 -Dtests.bwc=true

### Does it reproduce?

No

### Applicable branches

7.17

### Failure excerpt

```
        Caused by:
        java.lang.AssertionError: 
        Expected: "weight(text:the in 0) [PerFieldSimilarity], result of:"
             but: was "weight(text:the in 2) [PerFieldSimilarity], result of:"
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.junit.Assert.assertThat(Assert.java:956)
            at org.junit.Assert.assertThat(Assert.java:923)
            at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:99)
            at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:471)
            ... 37 more
```

**Comment by nik9000** [comment]
> Expected: "weight(text:the in 0) [PerFieldSimilarity], result of:"
>              but: was "weight(text:the in 2) [PerFieldSimilarity], result of:"

I think these get enumerated identifiers and I just need to use `\d` instead of `0` or `2` here.
