### ISSUE TITLE
[CI] Failure in RandomSamplerIT#testRandomSamplerHistogram

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#84595]
### CI Link

https://gradle-enterprise.elastic.co/s/l7kmxsv3tsale

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.aggregations.bucket.RandomSamplerIT.testRandomSamplerHistogram" -Dtests.seed=AED6446652EDAB2B -Dtests.locale=cs -Dtests.timezone=Africa/Bangui -Druntime.java=17

### Does it reproduce?

No

### Applicable branches

master

### Failure excerpt

```
org.elasticsearch.search.aggregations.bucket.RandomSamplerIT > testRandomSamplerHistogram FAILED
    java.lang.AssertionError: 
    Expected: a value less than <127.55000000000001>
         but: <145.07999999999993> was greater than <127.55000000000001>
        at __randomizedtesting.SeedInfo.seed([AED6446652EDAB2B:B3962E383F3EDAC]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.search.aggregations.bucket.RandomSamplerIT.testRandomSamplerHistogram(RandomSamplerIT.java:157)
```

**Comment by jtibshirani** [comment]
CC @benwtrent as I think you just added this test!

**Comment by benwtrent** [comment]
Feel free to mute! It may be flaky. I ran it 100s of times locally but Jenkins has a way.
