### ISSUE TITLE
ML fails full cluster restart from very old clusters on Arch Linux

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#84844]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+full-bwc/88/BWC_VERSION=7.1.1,nodes=general-purpose/

### Repro line

./gradlew :x-pack:qa:full-cluster-restart:v7.5.1#bwcTest

### Does it reproduce?

Yes

### Applicable branches

master, + more?

### Failure excerpt

```
org.elasticsearch.xpack.restart.MlHiddenIndicesFullClusterRestartIT > testMlIndicesBecomeHidden FAILED
    org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:42875], URI [/_ml/anomaly_detectors/ml-hidden-indices-old-cluster-job/_open], status line [HTTP/1.1 500 Internal Server Error]
    {"error":{"root_cause":[{"type":"exception","reason":"Unexpected job state [failed] while waiting for job to be opened"}],"type":"exception","reason":"Unexpected job state [failed] while waiting for job to be opened"},"status":500}
        at __randomizedtesting.SeedInfo.seed([5FE9AE310F42DEEA:4336424EF3ED7B18]:0)
        at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:312)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:287)
        at app//org.elasticsearch.xpack.restart.MlHiddenIndicesFullClusterRestartIT.openAnomalyDetectorJob(MlHiddenIndicesFullClusterRestartIT.java:187)
        at app//org.elasticsearch.xpack.restart.MlHiddenIndicesFullClusterRestartIT.testMlIndicesBecomeHidden(MlHiddenIndicesFullClusterRestartIT.java:73)

```

**Comment by benwtrent** [comment]
Here are the test logs [full-cluster-restart.zip](https://github.com/elastic/elasticsearch/files/8218240/full-cluster-restart.zip)

**Comment by nik9000** [comment]
The logs I linked are wrong - that is another failure. Ignore that. And the file Ben uploaded. It's from the logs I linked that are wrong.

I can reproduce this every time. But Ben can't. It'll have to wait, I think.

**Comment by nik9000** [comment]
I think this is a problem on my end:
```
[2022-03-09T17:59:22,149][WARN ][o.e.x.m.p.l.CppLogMessageHandler] [v7.5.1-1] [controller/556050] [CDetachedProcessSpawner.cc@193] Child process with PID 556346 has exited with exit code 1
```

**Comment by droberts195** [comment]
There is certainly an error at the moment that's causing many full cluster restart tests on master and 8.1 to fail.

I looked at one of them on 7.5.1 to see if ML was responsible and I don't think it is: https://gradle-enterprise.elastic.co/s/wgrygn5op5kas

The error that caused a node to die in that is:

```
[2022-03-10T00:21:28,079][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.5.1-1] fatal error in thread [elasticsearch[v7.5.1-1][clusterApplierService#updateTask][T#1]], exiting
java.lang.AssertionError: null
        at org.elasticsearch.index.IndexService.updateMetadata(IndexService.java:787) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateIndices(IndicesClusterStateService.java:535) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:228) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:544) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:530) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:503) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:717) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:260) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

The code that's failing there is this:

```
            final long currentSettingsVersion = currentIndexMetadata.getSettingsVersion();
            final long newSettingsVersion = newIndexMetadata.getSettingsVersion();
            if (currentSettingsVersion == newSettingsVersion) {
                assert updateIndexSettings == false;
```

It makes me wonder if a side effect of https://github.com/elastic/elasticsearch/pull/84780 is that we don't change the settings version when we make system indices hidden but this bit of code thinks we should?  The reason I mention that PR is that it's in the relatively short list of changes that were in the first periodic full BWC run that started failing and it seems most closely related.  /cc @williamrandolph and @grcevski on that part.

> I think this is a problem on my end:

You run Arch Linux locally right @nik9000?  In that case the problems you see locally could be completely different to what is seen in CI.  Arch Linux isn't supported but since it uses the very latest version of every Linux package it's a good canary in the mine for problems that will happen on supported platforms in a year or two so it's worth trying to find out what happened.

>```
> [2022-03-09T17:59:22,149][WARN ][o.e.x.m.p.l.CppLogMessageHandler] [v7.5.1-1] [controller/556050] [CDetachedProcessSpawner.cc@193] Child process with PID 556346 has exited with exit code 1
>```

The first thing to do is find out which process had PID 556346.  If you grep in the logs you might find out.  For example, if you find `[autodetect/556346]` anywhere in your logs then that means it was `autodetect`.  It could also be `pytorch_inference`, `normalizer` or `data_frame_analyzer`.  Then the next thing is to just try running that program with `--help`, for example, `$ES_HOME/platform/linux-x86_64/bin/autodetect --help` or `$ES_HOME/platform/linux-x86_64/bin/pytorch_inference --help`.  If there's some fundamental problem running the program due to changes in OS libraries then that should reveal it.

**Comment by nik9000** [comment]
> You run Arch Linux locally right @nik9000? In that case the problems you see locally could be completely different to what is seen in CI. Arch Linux isn't supported but since it uses the very latest version of every Linux package it's a good canary in the mine for problems that will happen on supported platforms in a year or two so it's worth trying to find out what happened.

Thanks so much! I'm on arch. I was for a while having problems with some missing `libcrypt` thing. I think I brought in the right dependencies for that. I'll grep around.

Sorry for implicating you guys in what was almost certainly my bug.

**Comment by nik9000** [comment]
I was getting failures running any *old* ml tasks without this package: https://archlinux.org/packages/core/x86_64/libxcrypt-compat/ . Modern versions of ml don't need it. But I'm still getting error like:

```
$ grep 595653 /home/nik9000/Code/Elastic/elasticsearch/x-pack/qa/full-cluster-restart/build/testclusters/v7.5.1-*/logs/v7.5.1.log 
/home/nik9000/Code/Elastic/elasticsearch/x-pack/qa/full-cluster-restart/build/testclusters/v7.5.1-1/logs/v7.5.1.log:[2022-03-10T11:11:08,432][WARN ][o.e.x.m.p.l.CppLogMessageHandler] [v7.5.1-1] [controller/595355] [CDetachedProcessSpawner.cc@193] Child process with PID 595653 has exited with exit code 1
```

That made me think it's `controller` but I dunno. I run it alone and with `--help` and didn't see any crashes. I ran all of these without any parameters and with `--help`:
```
$ ls /home/nik9000/.gradle/caches/transforms-3/aba06f3ed37f2e60edb683737b6aeaa8/transformed/elasticsearch-7.5.1-linux-x86_64.tar.gz/elasticsearch-7.5.1/modules/x-pack-ml/platform/linux-x86_64/bin/
autoconfig  autodetect  categorize  controller  data_frame_analyzer  normalize
```

and none of them crashed

**Comment by droberts195** [comment]
Thanks for uploading the logs.

This line is interesting:

```
Caused by: java.io.FileNotFoundException: Cannot open /home/nik9000/Code/Elastic/elasticsearch/x-pack/qa/full-cluster-restart/build/testclusters/v7.5.1-1/tmp/autodetect_ml-hidden-indices-old-cluster-job_input_595262 (No such file or directory)
```

The order we connect the named pipes is:

1. Logging
2. Input
3. Output
4. Restore
5. Persist

The fact it's failed on the input pipe suggests the logging pipe was connected successfully.  This is also interesting because we install seccomp filtering in between opening the logging pipe and creating the input pipe.

It almost certainly means that a C library call in glibc is implemented using a different kernel syscall in the latest version of Arch Linux to what it was using before, and that syscall is not on our permitted list in 7.5.1.  But if this problem doesn't occur when running the full cluster restart tests against a more recent version of Elasticsearch then that implies we added the necessary calls at some point.  Looking back through the ml-cpp PRs suggests it's https://github.com/elastic/ml-cpp/pull/1828 which went into 7.12.1.  This basically means ML won't work on recent Arch Linux until 7.12.1.  It's not a problem for end users as Arch Linux isn't a supported platform.  I guess it means if you want to run the full cluster restart tests against a version older than 7.12.1 you need to use an alternative machine that's got an older Linux distribution on it.

**Comment by nik9000** [comment]
> It's not a problem for end users as Arch Linux isn't a supported platform. I guess it means if you want to run the full cluster restart tests against a version older than 7.12.1 you need to use an alternative machine that's got an older Linux distribution on it.

Fair enough!
