### ISSUE TITLE
Elasticsearch 8.1 test framework does not work with external plugins

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#84879]
### Elasticsearch Version

8.1.0

### Java Version

_bundled_

### OS Version

osx

### Problem Description

Using the test framework with 8.1.0 does not work with external plugins. Updating and trying to run the tests results in

### Steps to Reproduce

```
./gradlew clean check
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava
Note: /Users/alr/devel/spinscale/elasticsearch-ingest-langdetect/src/main/java/com/cybozu/labs/langdetect/SecureDetectorFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not find org.elasticsearch.plugin:transport-netty4:8.1.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/transport-netty4/8.1.0/transport-netty4-8.1.0.pom
       - https://s3.amazonaws.com/download.elasticsearch.org/lucenesnapshots/cc2a31f2be8/org/elasticsearch/plugin/transport-netty4/8.1.0/transport-netty4-8.1.0.pom
     Required by:
         project : > org.elasticsearch.test:framework:8.1.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
5 actionable tasks: 5 executed
```

When trying to exclude netty4 dependency via 

```
configurations {
  testImplementation {
    exclude(group: 'org.elasticsearch.plugin', module: 'transport-netty4')
  }
}
```

The following error occurs:

```
> Task :test FAILED

org.elasticsearch.plugin.ingest.langdetect.LangDetectProcessorTests > classMethod FAILED
    java.lang.RuntimeException at BootstrapForTesting.java:185
        Caused by: java.lang.IllegalArgumentException at PolicyUtil.java:288
Exception in thread "Thread-3" Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.test.ESTestCase
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=20, name=Thread-3, state=RUNNABLE, group=TGRP-LangDetectProcessorTests]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
                at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
                at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
                at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1893)
                at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
                at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)
java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.test.ESTestCase
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=21, name=Thread-4, state=RUNNABLE, group=TGRP-LangDetectProcessorTests]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
                at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
                at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
                at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1893)
                at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
                at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)
```

However, digging into the error in the logs yields:

```
java.lang.RuntimeException: unable to install test security manager
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:185)
	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:242)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:631)
Caused by: java.lang.IllegalArgumentException: Unknown codebases [codebase.netty-common, codebase.netty-transport] in policy file [jar:file:/Users/alr/.gradle/caches/modules-2/files-2.1/org.elasticsearch/elasticsearch/8.1.0/323f1615a79e3e1921c8031f20a84b5bf38d5e03/elasticsearch-8.1.0.jar!/org/elasticsearch/bootstrap/test-framework.policy]
Available codebases: [LIST OF JARS HERE]
	at org.elasticsearch.bootstrap.PolicyUtil.readPolicy(PolicyUtil.java:288)
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:145)
	... 4 more
```

So this seems, that transport netty4 module is still referenced somewhere, and cannot be excluded?

**Comment by mark-vieira** [comment]
We are aware of this issue and it should get resolved by https://github.com/elastic/infra/pull/35152
