### ISSUE TITLE
collector [cluster_stats] failed to collect data when source-only index shards are present at cluster node

### ISSUE THREAD

**Issue by SPodjasek** [elastic/elasticsearch#84902]
### Elasticsearch Version

7.17.1

### Installed Plugins

repository-gcs

### Java Version

_bundled_

### OS Version

_docker_image_

### Problem Description

I've recently restored some source-only snapshots to my cluster and suddenly lost any from most of my nodes.
Looking at `GET _cat/nodes`, I only see data from 1 of 5 nodes. Similarly, only a single node is visible when looking at 'Stack monitoring' in Kibana.

After investigating, I've found the following error in master logs: `collector [cluster_stats] failed to collect data` (you can find the full logline below). Furthermore, looking at `GET _cluster/stats`, you can see the following failures on every node containing shards from the recovered index:
```json
{
  "_nodes": {
    "total": 5,
    "successful": 1,
    "failed": 4,
    "failures": [
      // Only first failure is shown
      {
        "type": "failed_node_exception",
        "reason": "Failed node [<<removed>>]",
        "node_id": "<<removed>>",
        "caused_by": {
          "type": "unsupported_operation_exception",
          "reason": "unsupported_operation_exception: _source only indices can't be searched or filtered"
        }
      }
    ]
  }
}
```

I'm currently re-indexing those source-only indexes, but it seems that until this process finishes and I'll remove source-only indexes, my cluster stats won't be visible - IMHO, this should not work that way.

### Steps to Reproduce

Recover snapshot from source-only repository - after that, any node containing shards for restored index will fail to supply stats.

### Logs (if relevant)

```json
{
  "type": "server",
  "timestamp": "2022-03-11T10:03:27,751Z",
  "level": "ERROR",
  "component": "o.e.x.m.c.c.ClusterStatsCollector",
  "cluster.name": "<<removed>>",
  "node.name": "<<removed>>",
  "message": "collector [cluster_stats] failed to collect data",
  "cluster.uuid": "<<removed>>",
  "node.id": "<<removed>>",
  "stacktrace": [
    "java.lang.NullPointerException: null",
    "at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]",
    "at org.elasticsearch.xpack.monitoring.collector.cluster.ClusterStatsMonitoringDoc.<init>(ClusterStatsMonitoringDoc.java:81) ~[x-pack-monitoring-7.17.1.jar:7.17.1]",
    "at org.elasticsearch.xpack.monitoring.collector.cluster.ClusterStatsCollector.doCollect(ClusterStatsCollector.java:115) ~[x-pack-monitoring-7.17.1.jar:7.17.1]",
    "at org.elasticsearch.xpack.monitoring.collector.Collector.collect(Collector.java:95) [x-pack-monitoring-7.17.1.jar:7.17.1]",
    "at org.elasticsearch.xpack.monitoring.MonitoringService$MonitoringExecution$1.doRun(MonitoringService.java:269) [x-pack-monitoring-7.17.1.jar:7.17.1]",
    "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.1.jar:7.17.1]",
    "at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]",
    "at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]",
    "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) [elasticsearch-7.17.1.jar:7.17.1]",
    "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]",
    "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]",
    "at java.lang.Thread.run(Thread.java:833) [?:?]"
  ]
}
```

**Comment by SPodjasek** [comment]
I can now confirm that after removing source-only indexes everything is back to normal.

**Comment by OlivierCavadenti** [comment]
In ClusterStatsMonitoringDoc the status cannot be null, but it come from ClusterStatsResponse where we can see the status can be set to null.
In the second constructor of ClusterStatsResponse, status come from no failed nodes : 

```java
ClusterHealthStatus status = null;
    for (ClusterStatsNodeResponse response : nodes) {
        // only the master node populates the status
        if (response.clusterStatus() != null) {
            status = response.clusterStatus();
            break;
        }
    }
    this.status = status
```

So we also can see that SeqIdGeneratingFilterReader throw the "_source only indices can't be searched or filtered" error during restoring snapshot (like we can see in SourceOnlySnapshotIT.java => testSnapshotAndRestore) and cause nodes to fail (then causes status to be null in ClusterHealthStatus).

I will be happy to fix it, but status need to be nullable in ClusterStatsMonitoringDoc also (tests say no at this time...) or we can retreive it by another way ?

**Comment by SPodjasek** [comment]
As a side note I would like to add that this problem also affects Elastic Cloud management interface. Disk usage is not reported properly for any node containing source-only index.

![screenshot-20220419_173139](https://user-images.githubusercontent.com/3293161/165480468-1fd1f2ce-69a5-49f9-b3fc-db92564bea64.png)

**Comment by jaebongim** [comment]
Hi @elastic/es-data-management  is this issue resolved?

**Comment by jaebongim** [comment]
Hi, @OlivierCavadenti  is this resolved?
