### ISSUE TITLE
[CI Failure] IndicesRequestTests.testIndicesStats failure

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#8497]
http://build-us-1.elasticsearch.org/job/es_core_14_window-2012/304/

```
java.lang.AssertionError: org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction$IndexShardStatsRequest
Expected: ["test1", "test0", "test0"]
     got: []

	at __randomizedtesting.SeedInfo.seed([C97289D5AE27CFBB:D82FFC40EC13878D]:0)
	at org.junit.Assert.assertThat(Assert.java:780)
	at org.elasticsearch.action.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:816)
	at org.elasticsearch.action.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:801)
	at org.elasticsearch.action.IndicesRequestTests.testIndicesStats(IndicesRequestTests.java:485)
```

**Comment by javanna** [comment]
I can't repro this anymore, I think we can close for now and reopen if it fails again, given that it didn't happen for a long while it probably got fixed meanwhile.
