### ISSUE TITLE
Execution failed for task ':plugins:repository-azure:qa:microsoft-azure-storage:integTestRunner'. AzureStorageRepositoryClientYamlTestSuiteIT

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#85311]
### CI Link

https://gradle-enterprise.elastic.co/s/fvfzzozxrp5wi/console-log?task=:plugins:repository-azure:qa:microsoft-azure-storage:integTestRunner

### Repro line

./gradlew ':plugins:repository-azure:qa:microsoft-azure-storage:integTestRunner' -Dtests.seed=F828B3BAED164440 -Dtests.class=org.elasticsearch.repositories.azure.AzureStorageRepositoryClientYamlTestSuiteIT -Dtests.method="test {yaml=repository_azure/10_repository/Get a non existing snapshot}" -Dtests.security.manager=true -Dtests.locale=ca-ES -Dtests.timezone=America/Marigot -Dcompiler.java=11 -Druntime.java=8

### Does it reproduce?

Didn't try

### Applicable branches

6.8

### Failure history

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20There%20were%20test%20failures:%201%20suite%2C%20*%20tests%2C%20*%20%5Bseed:%20*&search.relativeStartTime=P7D&search.timeZoneId=Europe/Zurich

### Failure excerpt

```


1> [2022-03-24T05:16:10,922][INFO ][o.e.r.a.AzureStorageRepositoryClientYamlTestSuiteIT] [test] Stash dump on test failure [{ |  
-- | --
  | 1>   "stash" : { |  
  | 1>     "body" : { |  
  | 1>       "error" : { |  
  | 1>         "root_cause" : [ |  
  | 1>           { |  
  | 1>             "type" : "repository_verification_exception", |  
  | 1>             "reason" : "[repository] path [6.8_integration_tests] is not accessible on master node", |  
  | 1>             "stack_trace" : "RepositoryVerificationException[[repository] path [6.8_integration_tests] is not accessible on master node]; nested: IOException[Can not write blob master.dat]; nested: StorageException[The specified account is disabled.]; |  
  | 1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:634) |  
  | 1> 	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:230) |  
  | 1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:708) |  
  | 1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) |  
  | 1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) |  
  | 1> 	at java.lang.Thread.run(Thread.java:748) |  
  | 1> Caused by: java.io.IOException: Can not write blob master.dat |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:94) |  
  | 1> 	at org.elasticsearch.common.blobstore.BlobContainer.writeBlobAtomic(BlobContainer.java:102) |  
  | 1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:629) |  
  | 1> 	... 5 more |  
  | 1> Caused by: com.microsoft.azure.storage.StorageException: The specified account is disabled. |  
  | 1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87) |  
  | 1> 	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:313) |  
  | 1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185) |  
  | 1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:938) |  
  | 1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:768) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:247) |  
  | 1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:69) |  
  | 1> 	at java.security.AccessController.doPrivileged(Native Method) |  
  | 1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:68) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:246) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:114) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:92) |  
  | 1> 	... 7 more |  
  | 1> " |  
  | 1>           } |  
  | 1>         ], |  
  | 1>         "type" : "repository_verification_exception", |  
  | 1>         "reason" : "[repository] path [6.8_integration_tests] is not accessible on master node", |  
  | 1>         "caused_by" : { |  
  | 1>           "type" : "i_o_exception", |  
  | 1>           "reason" : "Can not write blob master.dat", |  
  | 1>           "caused_by" : { |  
  | 1>             "type" : "storage_exception", |  
  | 1>             "reason" : "The specified account is disabled.", |  
  | 1>             "stack_trace" : "com.microsoft.azure.storage.StorageException: The specified account is disabled. |  
  | 1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87) |  
  | 1> 	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:313) |  
  | 1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185) |  
  | 1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:938) |  
  | 1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:768) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:247) |  
  | 1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:69) |  
  | 1> 	at java.security.AccessController.doPrivileged(Native Method) |  
  | 1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:68) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:246) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:114) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:92) |  
  | 1> 	at org.elasticsearch.common.blobstore.BlobContainer.writeBlobAtomic(BlobContainer.java:102) |  
  | 1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:629) |  
  | 1> 	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:230) |  
  | 1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:708) |  
  | 1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) |  
  | 1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) |  
  | 1> 	at java.lang.Thread.run(Thread.java:748) |  
  | 1> " |  
  | 1>           }, |  
  | 1>           "stack_trace" : "java.io.IOException: Can not write blob master.dat |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:94) |  
  | 1> 	at org.elasticsearch.common.blobstore.BlobContainer.writeBlobAtomic(BlobContainer.java:102) |  
  | 1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:629) |  
  | 1> 	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:230) |  
  | 1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:708) |  
  | 1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) |  
  | 1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) |  
  | 1> 	at java.lang.Thread.run(Thread.java:748) |  
  | 1> Caused by: com.microsoft.azure.storage.StorageException: The specified account is disabled. |  
  | 1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87) |  
  | 1> 	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:313) |  
  | 1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185) |  
  | 1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:938) |  
  | 1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:768) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:247) |  
  | 1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:69) |  
  | 1> 	at java.security.AccessController.doPrivileged(Native Method) |  
  | 1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:68) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:246) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:114) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:92) |  
  | 1> 	... 7 more |  
  | 1> " |  
  | 1>         }, |  
  | 1>         "stack_trace" : "RepositoryVerificationException[[repository] path [6.8_integration_tests] is not accessible on master node]; nested: IOException[Can not write blob master.dat]; nested: StorageException[The specified account is disabled.]; |  
  | 1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:634) |  
  | 1> 	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:230) |  
  | 1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:708) |  
  | 1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) |  
  | 1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) |  
  | 1> 	at java.lang.Thread.run(Thread.java:748) |  
  | 1> Caused by: java.io.IOException: Can not write blob master.dat |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:94) |  
  | 1> 	at org.elasticsearch.common.blobstore.BlobContainer.writeBlobAtomic(BlobContainer.java:102) |  
  | 1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:629) |  
  | 1> 	... 5 more |  
  | 1> Caused by: com.microsoft.azure.storage.StorageException: The specified account is disabled. |  
  | 1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87) |  
  | 1> 	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:313) |  
  | 1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185) |  
  | 1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:938) |  
  | 1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:768) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:247) |  
  | 1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:69) |  
  | 1> 	at java.security.AccessController.doPrivileged(Native Method) |  
  | 1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:68) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:246) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:114) |  
  | 1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:92) |  
  | 1> 	... 7 more |  
  | 1> " |  
  | 1>       }, |  
  | 1>       "status" : 500 |  
  | 1>     } |  
  | 1>   } |  
  | 1> }]


```

**Comment by arteam** [comment]
It's probably related to #84231

**Comment by fcofdez** [comment]
It should be fixed now, as I missed some credentials that needed to be refreshed.

**Comment by mark-vieira** [comment]
@fcofdez The Azure tests are failing again, is this related or should we open a new issue?

https://gradle-enterprise.elastic.co/s/vdkmiujxqcgwq
