### ISSUE TITLE
`script-src` CSP error happinging on `security/investigate/timelines/template`

### ISSUE THREAD

**Issue by bacloud22** [elastic/elasticsearch#85363]
### Elasticsearch Version

8.1

### Java Version

_bundled_

### OS Version

Windows server 2019 

### Problem Description

Some resources are not being loaded causing the whole page to crash with error (in logs)

### Steps to Reproduce

Chrome HAR file

https://file.io/sGILG1DJraEt

### Logs (if relevant)

Error on Firefox:

> Error: n is undefined
> c@http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.4.js:3:7167
> 831/i/y<@http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.4.js:3:7599
> useMemo@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:65039
> useMemo@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:431:5229
> i@http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.4.js:3:7554
> b@http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.6.js:3:365491
> 1432/Nt/o<@http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.9.js:3:28473
> Nt@http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.9.js:3:29035
> 1432/Lt/<@http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.9.js:3:30212
> Lt@http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.9.js:3:30353
> 1432/Xi<@http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.9.js:3:65590
> ga@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:59761
> rs@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:68106
> ts@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:67925
> Ns@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:111177
> Pu@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:97334
> Lu@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:97146
> wu@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:94325
> Ji/<@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:46038
> __kbnSharedDeps_npm__</t.unstable_runWithPriority@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:455:3462
> Xi@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:45747
> Ji@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:45985
> Qi@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:45918
> vu@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:91140
> Da@http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:63420
> h/u</<@http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.plugin.js:2:173012

Error on Chrome

Error

> Error: Cannot read properties of undefined (reading 'includes')
>     at c (http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.4.js:3:7169)
>     at http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.4.js:3:7599
>     at Object.useMemo (http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:447:65039)
>     at useMemo (http://localhost:5601/50609/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:431:5229)
>     at i (http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.4.js:3:7554)
>     at b (http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.6.js:3:365491)
>     at http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.9.js:3:28473
>     at Nt (http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.9.js:3:29035)
>     at http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.9.js:3:30210
>     at Lt (http://localhost:5601/50609/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.9.js:3:30353)

**Comment by bacloud22** [comment]
![image](https://user-images.githubusercontent.com/10267332/160239957-1dfbb75c-cb2f-4621-8a7f-6de8189b2a18.png)
![image](https://user-images.githubusercontent.com/10267332/160239973-88174575-8389-4386-82ae-c0eccc456da3.png)

**Comment by bacloud22** [comment]
I'm sorry this is an issue with Kibana I believe. I will port it in Kibana's repository.
