### ISSUE TITLE
[CI] FrozenExistenceDeciderIT testZeroToOne failing

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#85369]
**Build scan:**
https://gradle-enterprise.elastic.co/s/dlc3aqpl7zz7u/tests/:x-pack:plugin:autoscaling:internalClusterTest/org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT/testZeroToOne

**Reproduction line:**
`./gradlew ':x-pack:plugin:autoscaling:internalClusterTest' --tests "org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT.testZeroToOne" -Dtests.seed=DA251326124317EE -Dtests.locale=ms -Dtests.timezone=BST -Druntime.java=17`

**Applicable branches:**
8.1

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT&tests.test=testZeroToOne

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=118, name=Thread-5, state=RUNNABLE, group=TGRP-FrozenExistenceDeciderIT]

  at __randomizedtesting.SeedInfo.seed([DA251326124317EE:AB71BDC714A849CD]:0)

  Caused by: java.lang.AssertionError: policy step registry cache failed sanity check

    at __randomizedtesting.SeedInfo.seed([DA251326124317EE]:0)
    at org.elasticsearch.xpack.ilm.PolicyStepsRegistry.getStep(PolicyStepsRegistry.java:377)
    at org.elasticsearch.xpack.ilm.IndexLifecycleRunner.getCurrentStep(IndexLifecycleRunner.java:108)
    at org.elasticsearch.xpack.ilm.IndexLifecycleRunner.runPeriodicStep(IndexLifecycleRunner.java:173)
    at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:420)
    at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggered(IndexLifecycleService.java:351)
    at org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:186)
    at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:220)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by joegallo** [comment]
My fault entirely -- this one should be fixed by https://github.com/elastic/elasticsearch/pull/85346.
