### ISSUE TITLE
The Security Manager is deprecated exception (ES wont start)

### ISSUE THREAD

**Issue by mischabraam** [elastic/elasticsearch#85665]
### Elasticsearch Version

latest: elasticsearch: stable 7.10.2 (bottled)

### Java Version

openjdk: stable 18 (bottled) [keg-only]

### OS Version

Darwin Ricks-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

### Problem Description

Clean install of elasticsearch with `brew install elasticsearch` doesn't work with openjdk@18 (latest). An exception is thrown when elasticsearch tries to start about the Security Manager.

### Steps to Reproduce

brew install elasticsearch

### Logs (if relevant)

Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:416)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)

**Comment by tvernum** [comment]
Hi @mischabraam 

Our list of supported platforms is here: 
- https://www.elastic.co/support/matrix#matrix_jvm

Note that we do not currently advertise support for JDK18.

**Comment by ChrisHegarty** [comment]
What version of Elasticsearch is being used here?  We've been testing and running ES 7.x and 8.x on Java 18 successfully for months now in our CI.

**Comment by druvisc** [comment]
I'm having the same error on a macOS M1 for `elasticsearch@6.8` with JDK 11.

**Comment by ChrisHegarty** [comment]
ES versions 7.17.x, and 8.x will, at least, start with Java 18. See https://github.com/elastic/elasticsearch/pull/80957

**Comment by mischabraam** [comment]
```
brew info elasticsearch
```
Gives the following
```
elasticsearch: stable 7.10.2 (bottled)
Distributed search & analytics engine
https://www.elastic.co/products/elasticsearch
Deprecated because it is switching to an incompatible license. Check out `opensearch` instead!
/usr/local/Cellar/elasticsearch/7.10.2 (156 files, 113.5MB) *
  Poured from bottle on 2022-04-04 at 11:10:28
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/elasticsearch.rb
License: Apache-2.0
==> Dependencies
Build: gradle@6 ✘
Required: openjdk :heavy_check_mark:
==> Caveats
Data:    /usr/local/var/lib/elasticsearch/
Logs:    /usr/local/var/log/elasticsearch/elasticsearch_<account>.log
Plugins: /usr/local/var/elasticsearch/plugins/
Config:  /usr/local/etc/elasticsearch/
To start elasticsearch now and restart at login:
  brew services start elasticsearch
```

```
brew info openjdk
```
Gives the following
```
openjdk: stable 18 (bottled) [keg-only]
Development kit for the Java programming language
https://openjdk.java.net/
/usr/local/Cellar/openjdk/18 (641 files, 307.6MB)
  Poured from bottle on 2022-04-04 at 11:10:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openjdk.rb
License: GPL-2.0-only with Classpath-exception-2.0
==> Dependencies
Build: autoconf :heavy_check_mark:
```

**Comment by mischabraam** [comment]
I couldn't get it working by downgrading using `brew install openjdk@17` (maybe I did something wrong here)

**Comment by rjernst** [comment]
> I couldn't get it working by downgrading

Can you confirm which version of JDK was used when starting Elasticsearch? The first couple lines of the Elasticsearch log should show this

**Comment by PNixx** [comment]
```
brew uninstall --ignore-dependencies openjdk && brew install openjdk@17
```
It work for me.

**Comment by mirrayeesahmad** [comment]
I uninstalled openjdk@18 and installed openjdk@17
brew uninstall --ignore-dependencies openjdk@18
brew install openjdk@17

However when installing elasticsearch@6 openjdk was getting upgraded so i ignored openjdk dependency
using `brew install --ignore-dependencies elasticsearch@6`

it is working for me now.

**Comment by iampankajkumar** [comment]
I am getting the same error with JDK 8.

ES version - 7.0.0 
Please suggest some solution.

Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:416)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82

**Comment by DaveCTurner** [comment]
I believe this issue only affects versions of ES that are now past [EOL](https://www.elastic.co/support/eol) so no further action is needed here. I am therefore closing it.

**Comment by svanschalkwyk** [comment]
I'm building against 8.2.0 and getting this: 
```
java.lang.RuntimeException: unable to install test security manager
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:185)
	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:241)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:631)
Caused by: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at org.elasticsearch.bootstrap.Security.setSecurityManager(Security.java:102)
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:169)
	... 5 more```

**Comment by svanschalkwyk** [comment]
Also occurs when building plugins from ES github: 
No changes to any build files. 
```
Caused by: java.lang.RuntimeException: unable to install test security manager
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:207)
	... 42 more
Caused by: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at org.elasticsearch.bootstrap.Security.setSecurityManager(Security.java:109)
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:189)
	... 42 more
```

**Comment by DaveCTurner** [comment]
@svanschalkwyk thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question.
