### ISSUE TITLE
Support IMDSv2 for EC2 Discovery for ES 7.17.x

### ISSUE THREAD

**Issue by mifune-cedrowo** [elastic/elasticsearch#85733]
### Elasticsearch Version

7.17.2

### Installed Plugins

ec2-discovery

### Java Version

_bundled_

### OS Version

Centos7

### Problem Description

EC2 discovery plugin is not working correctly in latest ES7.17.2 version:
Changes merged to master to address this issue for ES8
https://github.com/elastic/elasticsearch/pull/84410

Can the same changes be cherrypicked to ES 7.17.x?

### Steps to Reproduce

Try to bootstrap ES cluster 7.17.2 on AWS cloud with IMSDv2 enforced.

### Logs (if relevant)

Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: http://169.254.169.254/latest/meta-data/local-ipv4
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at org.elasticsearch.discovery.ec2.SocketAccess.doPrivilegedIOException(SocketAccess.java:37) ~[?:?]
	at org.elasticsearch.discovery.ec2.Ec2NameResolver.resolve(Ec2NameResolver.java:89) ~[?:?]
	at org.elasticsearch.discovery.ec2.Ec2NameResolver.resolveIfPossible(Ec2NameResolver.java:115) ~[?:?]
	at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:230) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:218) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.common.network.NetworkService.resolvePublishHostAddresses(NetworkService.java:170) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.transport.TcpTransport.createBoundTransportAddress(TcpTransport.java:482) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:414) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:140) ~[?:?]
	at org.elasticsearch.xpack.core.security.transport.netty4.SecurityNetty4Transport.doStart(SecurityNetty4Transport.java:96) ~[?:?]
	at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4ServerTransport.doStart(SecurityNetty4ServerTransport.java:59) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:318) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.node.Node.start(Node.java:1180) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:335) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:443) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.17.2.jar:7.17.2]
	... 6 more

[2022-04-07T02:05:49,007][INFO ][o.e.n.Node               ] [master-Vancouver] version[7.17.2], pid[8453], build[default/rpm/de7261de50d90919ae53b0eff9413fd7e5307301/2022-03-28T15:12:21.446567561Z], OS[Linux/3.10.0-1160.59.1.el7.x86_64/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.2/17.0.2+8]
[2022-04-07T02:06:01,837][INFO ][o.e.p.PluginsService     ] [master-Vancouver] loaded module [mapper-version]

**Comment by DaveCTurner** [comment]
Unfortunately the 7.x branch is now in maintenance mode and only open to bugfixes, but adding direct support for IMDSv2-only environments is really a feature enhancement and not a bugfix. You can achieve the same effect using the [file-based seed hosts provider](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-hosts-providers.html#file-based-hosts-provider) with some external mechanism to query the AWS APIs and create the file.
