### ISSUE TITLE
[CI] TransportAnalyzeIndexDiskUsageActionTests testManyShards failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#85760]
Seen on a more recent master too: https://gradle-enterprise.elastic.co/s/lqvmj6wwmusge

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests.testManyShards" -Dtests.seed=E8308741DC10FB50 -Dtests.locale=da-DK -Dtests.timezone=Asia/Dili -Druntime.java=17

org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests > testManyShards FAILED
    java.lang.NullPointerException: Cannot invoke "org.elasticsearch.action.admin.indices.diskusage.IndexDiskUsageStats.getIndexSizeInBytes()" because the return value of "java.util.Map.get(Object)" is null
        at __randomizedtesting.SeedInfo.seed([E8308741DC10FB50:1650F3483C5EEB50]:0)
        at org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests.testManyShards(TransportAnalyzeIndexDiskUsageActionTests.java:259)


Suite: Test class org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests
  1> [2022-04-08T19:57:45,738][INFO ][o.e.a.a.i.d.TransportAnalyzeIndexDiskUsageActionTests] [testManyShards] before test
  1> [2022-04-08T19:57:51,310][INFO ][o.e.a.a.i.d.TransportAnalyzeIndexDiskUsageActionTests] [testManyShards] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests.testManyShards" -Dtests.seed=E8308741DC10FB50 -Dtests.locale=da-DK -Dtests.timezone=Asia/Dili -Druntime.java=17
  2> java.lang.NullPointerException: Cannot invoke "org.elasticsearch.action.admin.indices.diskusage.IndexDiskUsageStats.getIndexSizeInBytes()" because the return value of "java.util.Map.get(Object)" is null
        at __randomizedtesting.SeedInfo.seed([E8308741DC10FB50:1650F3483C5EEB50]:0)
        at org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests.testManyShards(TransportAnalyzeIndexDiskUsageActionTests.java:259)
  2> NOTE: leaving temporary files on disk at: /Users/davidturner/src/elasticsearch-master/server/build/testrun/test/temp/org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests_E8308741DC10FB50-001
  2> NOTE: test params are: codec=Asserting(Lucene91): {}, docValues:{}, maxPointsInLeafNode=464, maxMBSortInHeap=5.399408316367019, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=da-DK, timezone=Asia/Dili
  2> NOTE: Mac OS X 10.15.7 x86_64/Eclipse Adoptium 17.0.2 (64-bit)/cpus=16,threads=1,free=296792064,total=536870912
  2> NOTE: All tests run in this JVM: [TransportAnalyzeIndexDiskUsageActionTests]
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/pld526vr6sjcc/tests/:server:test/org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests/testManyShards

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests.testManyShards" -Dtests.seed=BE079260AA971166 -Dtests.locale=ro-RO -Dtests.timezone=Pacific/Palau -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests&tests.test=testManyShards

**Failure excerpt:**
```
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.action.admin.indices.diskusage.IndexDiskUsageStats.getIndexSizeInBytes()" because the return value of "java.util.Map.get(Object)" is null

  at __randomizedtesting.SeedInfo.seed([BE079260AA971166:4067E6694AD90166]:0)
  at org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests.testManyShards(TransportAnalyzeIndexDiskUsageActionTests.java:259)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by tlrx** [comment]
Also occurs on 7.17 today (https://gradle-enterprise.elastic.co/s/jfhyyan5dwiba) and on other branches too in the past 15 days.

I'll mute on 8.2, 8.1 and 7.17

**Comment by grcevski** [comment]
Failed on 8.3 https://gradle-enterprise.elastic.co/s/jpo4rsbpkwqc2/tests/:server:test/org.elasticsearch.action.admin.indices.diskusage.TransportAnalyzeIndexDiskUsageActionTests/testRandomLimitConcurrentRequests?top-execution=1
