### ISSUE TITLE
Discovery GCE test fails on FIPS

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#85803]
### CI Link

https://gradle-enterprise.elastic.co/s/mcboq4te6p7o6

### Repro line

./gradlew :plugins:discovery-gce:qa:gce:check -Dtests.fips.enabled=true

### Does it reproduce?

Yes

### Applicable branches

master

### Failure excerpt

This seems to have started failing since #85132

```
[2022-04-12T17:07:29,829][WARN ][o.e.c.g.GceInstancesServiceImpl] [yamlRestTest-1] unable to resolve default zone from metadata server for GCE discovery service
  java.security.KeyStoreException: Uninitialized keystore
       at java.security.KeyStore.size(KeyStore.java:1296) ~[?:?]
       at org.bouncycastle.jsse.provider.ProvTrustManagerFactorySpi.getTrustAnchors(ProvTrustManagerFactorySpi.java:227) ~[bctls-fips-1.0.9.jar:1.0.9]
       at org.bouncycastle.jsse.provider.ProvTrustManagerFactorySpi.engineInit(ProvTrustManagerFactorySpi.java:163) ~[bctls-fips-1.0.9.jar:1.0.9]
       at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:282) ~[?:?]
       at com.google.api.client.util.SslUtils.initSslContext(SslUtils.java:107) ~[google-http-client-1.41.1.jar:1.41.1]
```

**Comment by arteam** [comment]
I guess it's reminiscent to #75028. The Google Java SDK changed the trust store format to p12 from JSK due some Android issues: https://github.com/googleapis/google-api-java-client/commit/83f37023ea50a643a76eb6e5230072e5c829a205
