### ISSUE TITLE
[CI] SimpleNestedIT testDeleteNestedDocsWithAlias failing

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#85862]
**Build scan:**
https://gradle-enterprise.elastic.co/s/phuedkzpsdg6e/tests/:server:internalClusterTest/org.elasticsearch.search.nested.SimpleNestedIT/testDeleteNestedDocsWithAlias

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.nested.SimpleNestedIT.testDeleteNestedDocsWithAlias" -Dtests.seed=1FE570B0ACE8DBC9 -Dtests.locale=uk-UA -Dtests.timezone=Australia/LHI -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.nested.SimpleNestedIT&tests.test=testDeleteNestedDocsWithAlias

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=3137, name=elasticsearch[node_s1][masterService#updateTask][T#1], state=RUNNABLE, group=TGRP-SimpleNestedIT]

  at __randomizedtesting.SeedInfo.seed([1FE570B0ACE8DBC9:7C25917CE5C6CCFE]:0)

  Caused by: java.lang.AssertionError: (No message provided)

    at __randomizedtesting.SeedInfo.seed([1FE570B0ACE8DBC9]:0)
    at org.elasticsearch.cluster.routing.allocation.IndexMetadataUpdater.applyChanges(IndexMetadataUpdater.java:134)
    at org.elasticsearch.cluster.routing.allocation.RoutingAllocation.updateMetadataWithRoutingChanges(RoutingAllocation.java:274)
    at org.elasticsearch.cluster.routing.allocation.AllocationService.buildResultAndLogHealthChange(AllocationService.java:150)
    at org.elasticsearch.cluster.routing.allocation.AllocationService.applyStartedShards(AllocationService.java:143)
    at org.elasticsearch.cluster.action.shard.ShardStateAction$ShardStartedClusterStateTaskExecutor.execute(ShardStateAction.java:734)
    at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:901)
    at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:871)
    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:253)
    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:153)
    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:114)
    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:170)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:714)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:260)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by romseygeek** [comment]
The assertion has to do with index metadata, which I think is probably for @elastic/es-data-management to look at rather than the search team.

**Comment by joegallo** [comment]
#86159 removed this (unstable) assertion, so there's nothing to do here.
