### ISSUE TITLE
[CI] SearchableSnapshotActionIT testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#85887]
This happened on my docs PR. It is not reproducible but the error message seems rather legit.

**Build scan:**
https://gradle-enterprise.elastic.co/s/pgbg4oxgq4nk4/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT/testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped

**Reproduction line:**
`./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped" -Dtests.seed=5A2654283877A3C8 -Dtests.locale=ar-DZ -Dtests.timezone=Africa/Ndjamena -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT&tests.test=testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is "cold"
     but: was "hot"

  at __randomizedtesting.SeedInfo.seed([5A2654283877A3C8:731A97359BBAD1F6]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.lambda$testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped$11(SearchableSnapshotActionIT.java:342)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1061)
  at org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped(SearchableSnapshotActionIT.java:340)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by joegallo** [comment]
```
» [2022-04-13T18:33:04,914][WARN ][o.e.l.LicenseService     ] [javaRestTest-0] License [will expire] on [Wednesday, April 27, 2022].
»  # If you have a new license, please update it. Otherwise, please reach out to
»  # your support contact.
»  #
»  # Commercial plugins operate with reduced functionality on license expiration:
»  # - security
»  #  - Cluster health, cluster stats and indices stats operations are blocked
»  #  - All data operations (read and write) continue to work
»  # - watcher
»  #  - PUT / GET watch APIs are disabled, DELETE watch API continues to work
»  #  - Watches execute and write to the history
»  #  - The actions of the watches don't execute
»  # - monitoring
»  #  - The agent will stop collecting cluster and indices metrics
»  # - graph
»  #  - Graph explore APIs are disabled
»  # - ml
»  #  - Machine learning APIs are disabled
»  # - logstash
»  #  - Logstash will continue to poll centrally-managed pipelines
»  # - beats
»  #  - Beats will continue to poll centrally-managed configuration
»  # - deprecation
»  #  - Deprecation APIs are disabled
»  # - upgrade
»  #  - Upgrade API is disabled
»  # - sql
»  #  - SQL support is disabled
»  # - rollup
»  #  - Creating and Starting rollup jobs will no longer be allowed.
»  #  - Stopping/Deleting existing jobs, RollupCaps API and RollupSearch continue to function.
»  # - transform
»  #  - Creating, starting, updating transforms will no longer be allowed.
»  #  - Stopping/Deleting existing transforms continue to function.
»  # - analytics
»  #  - Aggregations provided by Analytics plugin are no longer usable.
»  # - ccr
»  #  - Creating new follower indices will be blocked
»  #  - Configuring auto-follow patterns will be blocked
»  #  - Auto-follow patterns will no longer discover new leader indices
»  #  - The CCR monitoring endpoint will be blocked
»  #  - Existing follower indices will continue to replicate data
»   ↑ repeated 6 times ↑
» [2022-04-13T18:33:00,520][ERROR][o.e.x.c.i.SearchableSnapshotAction] [javaRestTest-0] [searchable_snapshot] action is not available in the current license
»   ↑ repeated 4 times ↑
» [2022-04-13T18:35:10,490][WARN ][o.e.x.i.ExecuteStepsUpdateTask] [javaRestTest-0] policy [policy-asJAe] for index [index-ugdghdxgjc-000001] failed on cluster state step [{"phase":"hot","action":"rollover","name":"update-rollover-lifecycle-date"}]. Moving to ERROR step
»   ↑ repeated 9 times ↑
» [2022-04-13T18:33:00,107][TRACE][o.e.x.i.h.ILMHistoryStore] [javaRestTest-0] queueing ILM history item for indexing [ilm-history-5]: [{"index":".ds-logs-vewnxkyxbb-2022.04.13-000001","policy":"policy-nhxdr","@timestamp":1649874780107,"index_age":132,"success":false,"state":{"phase":"cold","failed_step":"branch-check-prerequisites","phase_definition":"{\"policy\":\"policy-nhxdr\",\"phase_definition\":{\"min_age\":\"0ms\",\"actions\":{\"searchable_snapshot\":{\"snapshot_repository\":\"yLecN\",\"force_merge_index\":true}}},\"version\":1,\"modified_date_in_millis\":1649874779816}","action_time":"1649874780091","is_auto_retryable_error":"true","phase_time":"1649874780053","step_info":"{\"type\":\"security_exception\",\"reason\":\"current license is non-compliant for [searchable-snapshots]\",\"license.expired.feature\":\"searchable-snapshots\"}","action":"searchable_snapshot","step":"ERROR","creation_date":"1649874779975","step_time":"1649874780092"},"error_details":"{\"type\":\"security_exception\",\"reason\":\"current license is non-compliant for [searchable-snapshots]\",\"license.expired.feature\":\"searchable-snapshots\",\"stack_trace\":\"org.elasticsearch.ElasticsearchSecurityException: current license is non-compliant for [searchable-snapshots]\\n\\tat org.elasticsearch.license.LicenseUtils.newComplianceException(LicenseUtils.java:27)\\n\\tat org.elasticsearch.xpack.core.ilm.SearchableSnapshotAction.lambda$toSteps$1(SearchableSnapshotAction.java:136)\\n\\tat org.elasticsearch.xpack.core.ilm.BranchingStep.performAction(BranchingStep.java:66)\\n\\tat org.elasticsearch.xpack.ilm.ExecuteStepsUpdateTask.doExecute(ExecuteStepsUpdateTask.java:112)\\n\\tat org.elasticsearch.xpack.ilm.IndexLifecycleClusterStateUpdateTask.execute(IndexLifecycleClusterStateUpdateTask.java:46)\\n\\tat org.elasticsearch.xpack.ilm.IndexLifecycleRunner.lambda$static$0(IndexLifecycleRunner.java:65)\\n\\tat org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:901)\\n\\tat org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:871)\\n\\tat org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:253)\\n\\tat org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:153)\\n\\tat org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:114)\\n\\tat org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:170)\\n\\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:714)\\n\\tat org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:260)\\n\\tat org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)\\n\\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\\n\\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\\n\\tat java.base/java.lang.Thread.run(Thread.java:833)\\n\"}"}]
» [2022-04-13T18:33:00,122][ERROR][o.e.c.s.MasterService    ] [javaRestTest-0] exception thrown by listener while notifying of new cluster state:
```

I did a little bit of investigation here, and it looks to me like it's really a license failure moreso than specifically a `SearchableSnapshotAction` failure -- for whatever reason the license in place while the test is running appears to think it's not compatible with the `searchable_snapshot` action, so the current ILM step ends up being an ERROR step rather than the expected flow.

I'm not sure what to do with that information, so I'm leaving this ticket as is for now, but I figured I'd paste the things I found. 🤷

**Comment by gmarouli** [comment]
Since there haven't been any recent failures, I will close this issue.
