### ISSUE TITLE
InternalCategorizationAggregationTests.testReduceRandom fails

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#85910]
### CI Link

https://gradle-enterprise.elastic.co/s/egvpjvrcicct4/console-log?task=:x-pack:plugin:ml:test

### Repro line

./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.aggs.categorization2.InternalCategorizationAggregationTests.testReduceRandom" -Dtests.seed=6D522EC986882EDC -Dtests.locale=fr -Dtests.timezone=Asia/Manila -Druntime.java=17

### Does it reproduce?

Yes

### Applicable branches

master

### Failure excerpt

```
org.elasticsearch.xpack.ml.aggs.categorization2.InternalCategorizationAggregationTests > testReduceRandom FAILED
    java.lang.IllegalArgumentException: threshold must be between 0.01 and 0.99: got 1.0
        at __randomizedtesting.SeedInfo.seed([6D522EC986882EDC:AD6F82D8A0D5B78A]:0)
        at org.elasticsearch.xpack.ml.aggs.categorization2.TokenListCategorizer.<init>(TokenListCategorizer.java:82)
        at org.elasticsearch.xpack.ml.aggs.categorization2.InternalCategorizationAggregation.reduce(InternalCategorizationAggregation.java:270)
        at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:439)
```

**Comment by benwtrent** [comment]
closing as duplicate: https://github.com/elastic/elasticsearch/issues/85903
