### ISSUE TITLE
[CI] MapperExtrasClientYamlTestSuiteIT test {yaml=match_only_text/10_basic/Wildcard highlighting} failing

### ISSUE THREAD

**Issue by lockewritesdocs** [elastic/elasticsearch#85939]
### CI Link

https://gradle-enterprise.elastic.co/s/k63tpbpe4emde/tests/:modules:mapper-extras:yamlRestTestV7CompatTest/org.elasticsearch.index.mapper.MapperExtrasClientYamlTestSuiteIT/test%20%7Byaml=match_only_text%2F10_basic%2FWildcard%20highlighting%7D?top-execution=1

### Repro line

./gradlew ':modules:mapper-extras:yamlRestTestV7CompatTest' --tests "org.elasticsearch.index.mapper.MapperExtrasClientYamlTestSuiteIT.test {yaml=match_only_text/10_basic/Wildcard highlighting}" -Dtests.seed=FE62C4A989FE4F8B -Dtests.locale=el-CY -Dtests.timezone=SystemV/AST4ADT -Druntime.java=17	

### Does it reproduce?

Didn't try

### Applicable branches

8.0

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/New_York&tests.container=org.elasticsearch.index.mapper.MapperExtrasClientYamlTestSuiteIT&tests.sortField=FAILED&tests.test=test%20%7Byaml%3Dmatch_only_text/10_basic/Wildcard%20highlighting%7D&tests.unstableOnly=true

### Failure excerpt

```
java.lang.AssertionError: Failure at [match_only_text/10_basic:318]: field [hits.hits.0.highlight.foo.0] is null
at __randomizedtesting.SeedInfo.seed([FE62C4A989FE4F8B:7636FB7327022273]:0)	
at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:489)	
at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)	
at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)	
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at java.lang.reflect.Method.invoke(Method.java:568)	
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)	
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)	
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)	
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)	
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)	
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)	
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)	
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)	
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)	
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)	
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)	
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)	
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)	
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)	
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)	
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)	
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)	
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)	
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)	
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)	
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)	
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)	
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)	
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)	
at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)	
at java.lang.Thread.run(Thread.java:833)

**Comment by lockewritesdocs** [comment]
Relates to #85604.

Same failure is happening in the `8.0` branch in the backport PR #85936. Here's a link to the [failure history](https://gradle-enterprise.elastic.co/s/k72qv2hoqnltm/tests/:modules:mapper-extras:yamlRestTestV7CompatTest/org.elasticsearch.index.mapper.MapperExtrasClientYamlTestSuiteIT/test%20%7Byaml=match_only_text%2F10_basic%2FWildcard%20highlighting%7D?expanded-stacktrace=WyIwIl0) for that PR.

**Comment by ywelsch** [comment]
8.0 is an inactive branch and typically not getting any backports of any kind of fixes. Docs changes are perhaps the exception for this, but the PRs making changes to the docs should perhaps not be running the above tests anyway. Something for the https://github.com/orgs/elastic/teams/es-delivery folks to ponder about?

**Comment by lockewritesdocs** [comment]
@ywelsch, so I cannot backport any changes to 8.0? I'm unable to choose which tests run on a PR.

**Comment by ywelsch** [comment]
I thought that PRs marked with `docs` would only run a subset of the tests (only what's relevant to the docs build), but things might have changed. In any case we are not actively building and testing inactive branches (only when we backport docs which have a different backport policy than the software/rest of the stuff in the repository), which looks to be an issue with our development process. @jpountz as you have recently written a note about backports etc., do you have some thoughts here?

**Comment by ywelsch** [comment]
@lockewritesdocs I backported the fix to 8.0 (see d6c30071da1) to unblock you, but this is something you might run into more frequently until we get clarification on our development processes.

**Comment by lockewritesdocs** [comment]
Thanks @ywelsch! Very much appreciated. Regarding the tests that run, @mark-vieira might have some insight about PRs with the `>docs` label.

**Comment by jpountz** [comment]
@ywelsch I had the same expectations as you have, though I thought that the decision regarding which tests to run depended on the touched folders rather than on labels. Hopefully @mark-vieira can help figure out why the magic didn't work well on that PR. Docs are a bit special since they are not part of releases and we like to be able to keep updating them after releases, so I'm inclined to view this as an automation issue (only docs tests should have run on that other backport PR) rather than a process issue.

**Comment by lockewritesdocs** [comment]
@jpountz, thank you for confirming expectations on backports. @mark-vieira, I removed the `backport` label and applied the `docs` label, but the same combination of tests are running. The same pipeline test is failing on two, unrelated docs PRs for `8.0` (see [this failure](https://gradle-enterprise.elastic.co/s/knrzkz2wlobsy/tests/:modules:ingest-common:yamlRestTestV7CompatTest/org.elasticsearch.ingest.common.IngestCommonClientYamlTestSuiteIT/test%20%7Byaml=ingest%2F90_simulate%2FTest%20simulate%20with%20provided%20pipeline%20that%20does%20not%20exist%7D?top-execution=1), and I don't know how to suppress that test. Any ideas on how to proceed without pushing a fix for that test?

**Comment by mark-vieira** [comment]
> Any ideas on how to proceed without pushing a fix for that test?

Yeah, I don't think Jenkins actually updates unless there's an actual push to the branch. I think in this scenario we can just ignore this error if we're certain it's not related to the PR, which I believe we are.
