### ISSUE TITLE
[CI] CCRIT.testAutoFollowing

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#85951]
### CI Link

https://gradle-enterprise.elastic.co/s/xqkefsonks3ni/tests/:client:rest-high-level:asyncIntegTest/org.elasticsearch.client.CCRIT/testAutoFollowing?top-execution=1

### Repro line

./gradlew ':client:rest-high-level:asyncIntegTest' --tests "org.elasticsearch.client.CCRIT.testAutoFollowing" -Dtests.seed=BD8CF40508D1FA6A -Dtests.locale=en-US -Dtests.timezone=Pacific/Saipan -Druntime.java=17

### Does it reproduce?

Yes

### Applicable branches

master

### Failure excerpt

```
org.elasticsearch.client.CCRIT > testAutoFollowing FAILED
    java.lang.AssertionError: 
    Expected: not null
         but: was null
        at __randomizedtesting.SeedInfo.seed([BD8CF40508D1FA6A:1262D2050C785147]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.client.CCRIT.lambda$testAutoFollowing$3(CCRIT.java:293)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1069)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1042)
        at org.elasticsearch.client.CCRIT.testAutoFollowing(CCRIT.java:289)
```

The test fails locally too but with a different error:

```
org.elasticsearch.client.CCRIT > testAutoFollowing FAILED
    org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=status_exception, reason=can not fetch remote cluster state as the license state of the remote cluster [local_cluster] could not be determined]
        at __randomizedtesting.SeedInfo.seed([BD8CF40508D1FA6A:1262D2050C785147]:0)
        at app//org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:178)
        at app//org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484)
        at app//org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2461)
        at app//org.elasticsearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:2373)
        at app//org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:672)
        at app//org.elasticsearch.client.RestClient$1.completed(RestClient.java:408)
        at app//org.elasticsearch.client.RestClient$1.completed(RestClient.java:392)
        at app//org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
        at app//org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
        at app//org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
        at app//org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
        at app//org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
        at app//org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at app//org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at app//org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at app//org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at app//org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at app//org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at app//org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at app//org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at app//org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        at java.base@18/java.lang.Thread.run(Thread.java:833)

        Caused by:
        org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=resource_not_found_exception, reason=license info is missing for cluster [local_cluster]]
            at app//org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:490)
            at app//org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:401)
            at app//org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:431)
            at app//org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:597)
            at app//org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:170)
            ... 21 more
```

**Comment by tbrooks8** [comment]
Closing as this test has been removed on recent branches.
