### ISSUE TITLE
Node stackoverflow crash during parsing regular expression.

### ISSUE THREAD

**Issue by howardhuanghua** [elastic/elasticsearch#85982]
### Elasticsearch Version

7.10.1

### Java Version

JDK11

### OS Version

CentOS

### Problem Description

In ES 7.10.1/Lucene 8.7.0, we still hit this regular expression parsing issue, which caused node stackoverflow crash.
Relate issues: 
https://github.com/elastic/elasticsearch/issues/28344
https://github.com/elastic/elasticsearch/issues/37637

I have attached the crashed ES node log: [node.log](https://github.com/elastic/elasticsearch/files/8510772/node.log)
```
at java.lang.String.codePointAt(String.java:727) ~[?:?]
	at org.apache.lucene.util.automaton.RegExp.match(RegExp.java:1106) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseComplExp(RegExp.java:1179) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseRepeatExp(RegExp.java:1149) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1142) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 12:43:52]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 21978bbe0307e2df17293e0502701bbe4a59c0be - root - 2021-11-03 `12:43:52]
```
The cluster node has 128GB physical memory and 32GB node heap size.
Related node jvm settings:
`-Xss1m -Xms32736m -Xmx32736m`

We have already set `index.max_regex_length` to 500 for every indices, we still could see 1000+ lines of `parseConcatExp` recursion call. So probably some other bugs caused dead-loop in parseConcatExp function. 

### Steps to Reproduce

It's hard to reproduce it. There is no complicated regex search request.

**Comment by nik9000** [comment]
#84624 should close this one. I believe in versions as old as 7.10 there's a chance for this to happen if you send the `fields` API with lots of fields. I believe I merged a fix for that a while back as well as protection on that regex ctor. But #82923 properly protects all regex ctors. It's much better.

**Comment by benwtrent** [comment]
recursive overflow via regex parsing is now protected against, closing.
