### ISSUE TITLE
node 异常掉线 disconnecting from relevant node java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by huangpeng0817** [elastic/elasticsearch#86030]
elasticsearch version:7.15.1
jdk:jdk17
网络监控无异常，集群整体状态正常，突然出现节点掉线问题。偶尔是多服务器上多个节点掉，无规律
master上日志：
```
[2022-04-19T11:58:00,923][DEBUG][o.e.m.f.FsHealthService  ] [masternode-3] health check succeeded
[2022-04-19T11:58:03,529][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:58:13,529][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:58:23,529][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:58:33,529][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:58:43,530][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:58:53,530][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:59:03,530][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:59:13,531][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:59:23,531][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:59:33,531][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:59:43,532][DEBUG][o.a.h.i.c.PoolingHttpClientConnectionManager] [masternode-3] Closing expired connections
[2022-04-19T11:59:51,776][DEBUG][o.e.t.TcpTransport       ] [masternode-3] close connection exception caught on transport layer [Netty4TcpChannel{localAddress=/10.100.8.22:8300, remoteAddress=/10.100.8.64:33348, profile=default}], disconnecting from relevant node
java.net.SocketException: Connection reset
        at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at org.elasticsearch.transport.CopyBytesSocketChannel.readFromSocketChannel(CopyBytesSocketChannel.java:130) ~[transport-netty4-client-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:115) ~[transport-netty4-client-7.15.1.jar:7.15.1]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.66.Final.jar:4.1.66.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-04-19T11:59:51,776][DEBUG][o.e.t.TcpTransport       ] [masternode-3] close connection exception caught on transport layer [Netty4TcpChannel{localAddress=/10.100.8.22:60422, remoteAddress=10.100.8.64/10.100.8.64:8305, profile=default}], disconnecting from relevant node
java.net.SocketException: Connection reset
        at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at org.elasticsearch.transport.CopyBytesSocketChannel.readFromSocketChannel(CopyBytesSocketChannel.java:130) ~[transport-netty4-client-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:115) ~[transport-netty4-client-7.15.1.jar:7.15.1]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.66.Final.jar:4.1.66.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-04-19T11:59:51,776][DEBUG][o.e.t.TcpTransport       ] [masternode-3] close connection exception caught on transport layer [Netty4TcpChannel{localAddress=/10.100.8.22:8300, remoteAddress=/10.100.8.64:33392, profile=default}], disconnecting from relevant node
java.net.SocketException: Connection reset
        at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at org.elasticsearch.transport.CopyBytesSocketChannel.readFromSocketChannel(CopyBytesSocketChannel.java:130) ~[transport-netty4-client-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:115) ~[transport-netty4-client-7.15.1.jar:7.15.1]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.66.Final.jar:4.1.66.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.66.Final.jar:4.1.66.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```
data上日志：
```
[2022-04-19T11:14:16,945][INFO ][o.e.m.j.JvmGcMonitorService] [datanode-258] [gc][4287656] overhead, spent [269ms] collecting in the last [1s]
[2022-04-19T11:30:43,410][INFO ][o.e.m.j.JvmGcMonitorService] [datanode-258] [gc][4288641] overhead, spent [609ms] collecting in the last [1.3s]
[2022-04-19T11:59:59,721][INFO ][o.e.c.c.Coordinator      ] [datanode-258] master node [{masternode-3}{SlCs64CHSzm-ZRgkARM59A}{-yMTQQQDToSA7HvXHKWGYQ}{10.100.8.22}{10.100.8.22:8300}{m}{xpack.installed=true, transform.node=false}] failed, restarting discovery
org.elasticsearch.ElasticsearchException: node [{masternode-3}{SlCs64CHSzm-ZRgkARM59A}{-yMTQQQDToSA7HvXHKWGYQ}{10.100.8.22}{10.100.8.22:8300}{m}{xpack.installed=true, transform.node=false}] failed [3] consecutive checks
        at org.elasticsearch.cluster.coordination.LeaderChecker$CheckScheduler$1.handleException(LeaderChecker.java:275) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1289) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1289) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:313) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:228) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:311) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:303) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:124) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:82) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:712) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:132) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:104) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:63) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[?:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [masternode-3][10.100.8.22:8300][internal:coordination/fault_detection/leader_check]
Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: rejecting leader check since [{datanode-258}{V1TPeipNRkSi4IurDFO-tg}{xof_8iHTSgWFvJaAUwsG2A}{10.100.8.64}{10.100.8.64:8301}{dr}{xpack.installed=true, transform.node=false}] has been removed from the cluster
        at org.elasticsearch.cluster.coordination.LeaderChecker.handleLeaderCheck(LeaderChecker.java:181) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.cluster.coordination.LeaderChecker.lambda$new$0(LeaderChecker.java:102) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:259) ~[?:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:330) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:61) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:201) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:100) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:82) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:712) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:132) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:104) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69) ~[elasticsearch-7.15.1.jar:7.15.1]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:63) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[?:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[2022-04-19T11:59:59,796][INFO ][o.e.c.s.ClusterApplierService] [datanode-258] master node changed {previous [{masternode-3}{SlCs64CHSzm-ZRgkARM59A}{-yMTQQQDToSA7HvXHKWGYQ}{10.100.8.22}{10.100.8.22:8300}{m}], current []}, term: 2, version: 18894, reason: becoming candidate: onLeaderFailure
[2022-04-19T12:00:00,042][INFO ][o.e.c.s.ClusterApplierService] [datanode-258] master node changed {previous [], current [{masternode-3}{SlCs64CHSzm-ZRgkARM59A}{-yMTQQQDToSA7HvXHKWGYQ}{10.100.8.22}{10.100.8.22:8300}{m}]}, removed {{datanode-262}{-sDfCf7ZSa2rYF3tqwSSSQ}{8tGlEnr3TYaJD3oRHZfdjQ}{10.100.8.64}{10.100.8.64:8305}{dr}}, term: 2, version: 18906, reason: ApplyCommitRequest{term=2, version=18906, sourceNode={masternode-3}{SlCs64CHSzm-ZRgkARM59A}{-yMTQQQDToSA7HvXHKWGYQ}{10.100.8.22}{10.100.8.22:8300}{m}{xpack.installed=true, transform.node=false}}
[2022-04-19T12:00:03,320][INFO ][o.e.c.s.ClusterApplierService] [datanode-258] added {{datanode-262}{-sDfCf7ZSa2rYF3tqwSSSQ}{8tGlEnr3TYaJD3oRHZfdjQ}{10.100.8.64}{10.100.8.64:8305}{dr}}, term: 2, version: 18907, reason: ApplyCommitRequest{term=2, version=18907, sourceNode={masternode-3}{SlCs64CHSzm-ZRgkARM59A}{-yMTQQQDToSA7HvXHKWGYQ}{10.100.8.22}{10.100.8.22:8300}{m}{xpack.installed=true, transform.node=false}}
```

**Comment by DaveCTurner** [comment]
> 网络监控无异常，集群整体状态正常，突然出现节点掉线问题。偶尔是多服务器上多个节点掉，无规律

I hope Google Translate has translated this accurately:

> There is no abnormality in network monitoring, the overall status of the cluster is normal, and the node disconnection problem suddenly occurs. Occasionally, multiple nodes on multiple servers are dropped, irregularly

I think this means your network monitoring is not sensitive enough. `Connection reset` is a definite indication that something else (not Elasticsearch) is terminating these network connections abruptly. Elasticsearch itself does not close these connections. Since this is not something we can address in Elasticsearch I am closing this issue and redirecting you to  the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) where there's an active community that should be able to help. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
