### ISSUE TITLE
[CI] EnrichAdvancedSecurityIT testBasicFlowLong failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#86061]
**Build scan:**
https://gradle-enterprise.elastic.co/s/uzta7vt7jueno/tests/:x-pack:plugin:enrich:qa:rest-with-advanced-security:javaRestTest/org.elasticsearch.xpack.enrich.EnrichAdvancedSecurityIT/testBasicFlowLong

**Reproduction line:**
`./gradlew ':x-pack:plugin:enrich:qa:rest-with-advanced-security:javaRestTest' --tests "org.elasticsearch.xpack.enrich.EnrichAdvancedSecurityIT.testBasicFlowLong" -Dtests.seed=8E23D36573B910BC -Dtests.locale=en-SG -Dtests.timezone=America/Menominee -Druntime.java=16`

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.enrich.EnrichAdvancedSecurityIT&tests.test=testBasicFlowLong

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a value equal to or greater than <1>
     but: <0> was less than <1>

  at __randomizedtesting.SeedInfo.seed([8E23D36573B910BC:C85067CA23BC2A64]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.test.enrich.CommonEnrichRestTestCase.verifyEnrichMonitoring(CommonEnrichRestTestCase.java:310)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1141)
  at org.elasticsearch.test.enrich.CommonEnrichRestTestCase.testBasicFlowLong(CommonEnrichRestTestCase.java:162)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:831)

```

**Comment by masseyke** [comment]
This one doesn't look like just an overburdened test machine because the failure happens on line 310, after we've asserted that we got results back. So there's a hit, but `_source.enrich_coordinator_stats.remote_requests_total` is missing or 0. It looks like it gets incremented here: https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/action/EnrichCoordinatorProxyAction.java#L164 and read here: https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/action/EnrichCoordinatorProxyAction.java#L143. The read and write are done by separate threads. And the docs for LongAdder::sum (which is what longValue calls) say `The returned value is NOT an atomic snapshot; invocation in the absence of concurrent updates returns an accurate result, but concurrent updates that occur while the sum is being calculated might not be incorporated.` (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/LongAdder.html#sum--). Maybe that's the problem here? It seems pretty unlikely that that would happen, but I don't see anything else that could explain this.

**Comment by masseyke** [comment]
I'm not familiar with this code, but I did a little experimenting, and there is nothing preventing that reading code from running at the same time as the writing code. So it does seem like that could be it. I'm guessing @martijnvg is more familiar with this.

**Comment by martijnvg** [comment]
@masseyke Thanks for looking into this. 

> I'm not familiar with this code, but I did a little experimenting, and there is nothing preventing that reading code from running at the same time as the writing code. So it does seem like that could be it. 

I don't fully understand this failure yet.

But yes, there is nothing that guarantees that invocations to `remoteRequestsTotal#longValue()` and `executedSearchesTotal#longValue()` occur while the corresponding `add(...)` / `incumbent()` methods are invoked.
But the next time the monitor runs the updates to these `LongAdder` that occurred while reading should be visible and therefor be reported by monitoring? By default monitoring runs every 10s and the tests wait up to 3 minutes until a monitor doc with a `remote_requests_total` and `executed_searches_total` have been found that is equal or higher than 1.

**Comment by martijnvg** [comment]
Maybe we should try to figure out if this is a monitoring issue or an issue with the enrich stats. We can try to do this by also executing the enrich stats api in the `verifyEnrichMonitoring()` method and just log the response. If the the stats report the expected results then we should take a better look at monitoring and otherwise we should further investigate the enrich stats.

Also it looks like in CI this test failure only occurs in the 7.17 branch. When you were investigating this failure locally were running this test from 7.17 branch or other branches?

**Comment by masseyke** [comment]
I was running from 7.17.

**Comment by benwtrent** [comment]
Another failure on 7.17: https://gradle-enterprise.elastic.co/s/p2iihswlrwzok

**Comment by davidkyle** [comment]
There are a number of tests failing in this suite I've muted the entire suite in #88427 

Possibly related to #88091

**Comment by joegallo** [comment]
I spent some time looking at this one tonight. What do you think about this idea, @masseyke?

```diff
diff --git a/x-pack/plugin/enrich/qa/common/src/main/java/org/elasticsearch/test/enrich/CommonEnrichRestTestCase.java b/x-pack/plugin/enrich/qa/common/src/main/java/org/elasticsearch/test/enrich/CommonEnrichRestTestCase.java
index 906fde417e3..2ebcd900356 100644
--- a/x-pack/plugin/enrich/qa/common/src/main/java/org/elasticsearch/test/enrich/CommonEnrichRestTestCase.java
+++ b/x-pack/plugin/enrich/qa/common/src/main/java/org/elasticsearch/test/enrich/CommonEnrichRestTestCase.java
@@ -278,7 +280,7 @@ public abstract class CommonEnrichRestTestCase extends ESRestTestCase {

     private static void verifyEnrichMonitoring() throws IOException {
         Request request = new Request("GET", "/.monitoring-*/_search");
-        request.setJsonEntity("{\"query\": {\"term\": {\"type\": \"enrich_coordinator_stats\"}}}");
+        request.setJsonEntity("{\"query\": {\"term\": {\"type\": \"enrich_coordinator_stats\"}},\"sort\": [{\"_doc\": \"desc\"}]}");
         Map<String, ?> response;
         try {
```

The default size is 10, and we're iterating the returned hits (not all the docs in the index, just the returned hits). So if some hiccup happens such that we get 10 docs with the totals at 0, then will the current code ever see any docs beyond that? Sorting by _doc desc gives the documents in reverse index order, so we'd get the newest documents first (I think?).

That said, though, while the above is a nice theory, I haven't been able to reproduce the failure locally (I have accounted for https://github.com/elastic/elasticsearch/pull/88427, and I am running on 7.17), so there's no proof I'm right about this. Likewise I don't see what would be special about 7.17 that would only make this issue occur there.

**Comment by masseyke** [comment]
I'm wondering if this is just another bug due to the weirdness of our deprecation logger returning its payload on the response of whatever request comes in next. So something is returned with hits but there's no `_source.enrich_coordinator_stats.remote_requests_total`.  The logs have this suspicious bit (notice the deprecation message in the middle of the test):
```
  1> [2022-04-21T01:43:44,821][INFO ][o.e.x.e.EnrichAdvancedSecurityIT] [testBasicFlowLong] before test
  1> [2022-04-21T01:43:44,953][INFO ][o.e.x.e.EnrichAdvancedSecurityIT] [testBasicFlowLong] initializing REST clients against [http://[::1]:40717, http://127.0.0.1:39325]
  1> [2022-04-21T01:46:49,716][WARN ][o.e.c.RestClient         ] [testBasicFlowLong] request [DELETE http://[::1]:40717/*,-.ds-ilm-history-*?expand_wildcards=open%2Cclosed%2Chidden] returned 1 warnings: [299 Elasticsearch-7.17.4-SNAPSHOT-88516a1914c957ccc369cb38eaaaf2b3783876ab "this request accesses system indices: [.triggered_watches, .watches], but in a future major version, direct access to system indices will be prevented by default"]
  1> [2022-04-21T01:46:49,964][INFO ][o.e.x.e.EnrichAdvancedSecurityIT] [testBasicFlowLong] after test
```
I can't remember exactly how the deprecation logger works though because it's been a few months since I dealt with it.

**Comment by masseyke** [comment]
Oh here's the ticket I was looking for: #85506. Doesn't it look like another side effect of that one? I've been able to get that same deprecation warning by running this test alone (which seems like a problem on its own). But I haven't been able to get the test to fail.

**Comment by masseyke** [comment]
The only things in `.watches` are the system watches, so I think that's fine. Here's how we're getting the deprecation warning (and this is on 7.17 so I'm not sure we haven't already fixed this)
```
        at org.elasticsearch.common.logging.DeprecationLogger.logDeprecation(DeprecationLogger.java:115) ~[elasticsearch-7.17.6-SNAPSHOT.jar:7.17.6-SNAPSHOT]
        at org.elasticsearch.common.logging.DeprecationLogger.warn(DeprecationLogger.java:111) ~[elasticsearch-7.17.6-SNAPSHOT.jar:7.17.6-SNAPSHOT]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.checkSystemIndexAccess(IndexNameExpressionResolver.java:430) ~[elasticsearch-7.17.6-SNAPSHOT.jar:7.17.6-SNAPSHOT]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:396) ~[elasticsearch-7.17.6-SNAPSHOT.jar:7.17.6-SNAPSHOT]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:270) ~[elasticsearch-7.17.6-SNAPSHOT.jar:7.17.6-SNAPSHOT]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:92) ~[elasticsearch-7.17.6-SNAPSHOT.jar:7.17.6-SNAPSHOT]
        at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:76) ~[elasticsearch-7.17.6-SNAPSHOT.jar:7.17.6-SNAPSHOT]
        at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:37) ~[elasticsearch-7.17.6-SNAPSHOT.jar:7.17.6-SNAPSHOT]
```

**Comment by masseyke** [comment]
If my guess is right (and I'm not completely convinced that it is), I think this one might be fixed by #73734

**Comment by jakelandis** [comment]
Another occurrence on a PR build: https://gradle-enterprise.elastic.co/s/cjlcxgjrfnkv2/tests/:x-pack:plugin:enrich:qa:rest-with-advanced-security:javaRestTest/org.elasticsearch.xpack.enrich.EnrichAdvancedSecurityIT/testBasicFlowIp?expanded-stacktrace=WyIwIl0&top-execution=1

REPRODUCE WITH: ./gradlew ':x-pack:plugin:enrich:qa:rest-with-advanced-security:javaRestTest' --tests "org.elasticsearch.xpack.enrich.EnrichAdvancedSecurityIT.testBasicFlowIp" -Dtests.seed=162A27EB96A3DDD1 -Dtests.locale=th-TH -Dtests.timezone=Asia/Almaty -Druntime.java=20

**Comment by joegallo** [comment]
https://gradle-enterprise.elastic.co/s/j5fbu72vt26v4

**Comment by DaveCTurner** [comment]
I muted this in 7bd40f101e7b1c82ebfdb5c1a6b1e4bdf40f4ab6
