### ISSUE TITLE
SQL: naming grouping subquery and filtering outside of it leads to unresolved extractor

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#86099]
### Description

The following query works fine:
`select author, s from (select author, sum(page_count) s from test_lib group by author) where s is not null`. 
However, naming the subquery:
`select author, s from (select author, sum(page_count) s from test_lib group by author) x where s is not null`
triggers an exception:
```
org.elasticsearch.xpack.sql.SqlIllegalArgumentException: Cannot resolve field extractor index for column [x.author{f}#5348]
        at org.elasticsearch.xpack.sql.querydsl.container.QueryContainer.columnMask(QueryContainer.java:238) ~[?:?]
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseAggActionListener.<init>(Querier.java:530) ~[?:?]
        at org.elasticsearch.xpack.sql.execution.search.Querier$CompositeActionListener.<init>(Querier.java:448) ~[?:?]
        at org.elasticsearch.xpack.sql.execution.search.Querier.query(Querier.java:142) ~[?:?]
        at org.elasticsearch.xpack.sql.plan.physical.EsQueryExec.execute(EsQueryExec.java:60) ~[?:?]
        at org.elasticsearch.xpack.sql.plan.physical.LeafExec.execute(LeafExec.java:31) ~[?:?]
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$sql$5(SqlSession.java:189) ~[?:?]
        at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:162) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:185) [x-pack-sql-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:162) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
        ...
```
Filtering (the grouping) inside the named subquery will work too.

**Comment by bpintea** [comment]
Likely a dup of #71394.

**Comment by gurudykim** [comment]
Hi, this is the answer to your issue.

"SELECT n, s FROM (SELECT authorn, SUM(page_count) AS s FROM test_lib GROUP BY author) x WHERE s IS NOT NULL"

I don't know if you want this answer, but I hope it helps
