### ISSUE TITLE
assertBusy() sometimes not reporting suppressed exceptions

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#86190]
In [this build](https://gradle-enterprise.elastic.co/s/zw5jghw3by7r2/tests/:server:internalClusterTest/org.elasticsearch.index.seqno.GlobalCheckpointSyncIT/testPersistGlobalCheckpoint?expanded-stacktrace=WyIwIl0&top-execution=1) we see an assertion error from within `assertBusy()`, but there are no suppressed exceptions. The Jenkins log agrees:

```
⋮
  1> [2022-04-25T11:29:13,746][INFO ][o.e.i.s.GlobalCheckpointSyncIT] [testPersistGlobalCheckpoint] [GlobalCheckpointSyncIT#testPersistGlobalCheckpoint]: cleaning up after test
  1> [2022-04-25T11:29:13,761][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s2] [test/mcAfDtBUSSWx4p9pFOMXdg] deleting index
  1> [2022-04-25T11:29:13,831][INFO ][o.e.c.m.MetadataIndexTemplateService] [node_s2] removing template [random_index_template]
  1> [2022-04-25T11:29:13,863][INFO ][o.e.i.s.GlobalCheckpointSyncIT] [testPersistGlobalCheckpoint] [GlobalCheckpointSyncIT#testPersistGlobalCheckpoint]: cleaned up after test
  1> [2022-04-25T11:29:13,864][INFO ][o.e.i.s.GlobalCheckpointSyncIT] [testPersistGlobalCheckpoint] after test
  2> REPRODUCE WITH: gradlew ':server:internalClusterTest' --tests "org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.testPersistGlobalCheckpoint" -Dtests.seed=7557CE3BCB407DEA -Dtests.locale=cs -Dtests.timezone=Europe/Mariehamn -Druntime.java=18
  2> java.lang.AssertionError: 
    Expected: <2L>
         but: was <-1L>
        at __randomizedtesting.SeedInfo.seed([7557CE3BCB407DEA:1B5972A012B5C62C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:239)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1061)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1034)
        at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.testPersistGlobalCheckpoint(GlobalCheckpointSyncIT.java:232)
  1> [2022-04-25T11:29:13,912][INFO ][o.e.i.s.GlobalCheckpointSyncIT] [testPersistLocalCheckpoint] before test
⋮
```

I don't understand how this can happen. Is `assertBusy()` not running the action repeatedly for some reason? Are the suppressed exceptions being removed from the output somehow? It can be important to see them sometimes.

**Comment by mark-vieira** [comment]
It does seem as though the build scan hides the supressed exceptions. You can get them in the raw JUnit XML though. In this instance it looks like this:

```
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
	Suppressed: java.lang.AssertionError: 
Expected: &lt;2L&gt;
     but: was &lt;-1L&gt;
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:237)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1049)
		... 38 more
```

In this case, not super helpful but the information is still technically available if we need it. Looking at the [build scan data model](https://docs.gradle.com/enterprise/event-model-javadoc/com/gradle/scan/eventmodel/gradle/exception/Exception_3_0.html) it doesn't look like suppressed exceptions are even captured (only causes) so I don't think getting them in build scans is possible. We can certainly request this though.

**Comment by pugnascotia** [comment]
In general, it may be useful for build scans to capture suppressed exceptions. In this particular case, however, maybe we can adjust the thrown exception to confirm that `assertBusy` did indeed try for the full time / number of iterations. e.g. something like:

    throw new AssertionError("Code block did not execute successfully after {timeout} / {iterations}", e)

**Comment by DaveCTurner** [comment]
Yes I'm not too worried about this particular case: as Mark says, the suppressed ones are not exactly helpful. I was just surprised I couldn't see them, and doubly surprised that they weren't there in the Jenkins logs either. I think this will trip someone up at some point, since we do capture useful info in suppressed exceptions in various places.

**Comment by mark-vieira** [comment]
Yeah, I think the reason being that suppressed exceptions are generally a special case and most reporting tooling is going to print the causual chain, not suppressed exceptions. As Rory mentions, we could augment our own reporting here to catch these and print the suppressed exceptions if applicable but yeah, anything that's just going to effectively print the stacktrace is going to omit these.

Given that this data _is_ accessible (you have to dig a little) and in 99% of cases the suppressed exceptions aren't helpful I'm inclined to do nothing here unless we think we're commonly missing useful diagnostic information.

**Comment by DaveCTurner** [comment]
Ok, I'll close this for now and come back with some more meaningful omissions if I encounter them.
