### ISSUE TITLE
NullPointerException with empty string filter & Java Driver

### ISSUE THREAD

**Issue by fabienrousseau** [elastic/elasticsearch#8629]
I currently have a NullPointerException when using the Java Driver (1.4.0).
It is displayed client side, but it happens on the server side.

```
2014-11-24 11:42:34,347 [elasticsearch[Zeus][transport_client_worker][T#8]{New I/O worker #8}] DEBUG type - [Zeus] [myindex][3], node[0tdeHG7LSMKLKyqn7g0ifw], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@69a9f314] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [Ancient One][inet[/192.168.200.103:9300]][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.SearchParseException: [myindex][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"term":{"source":""}}}}}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:681) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:537) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:776) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:767) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.run(MessageChannelHandler.java:275) ~[elasticsearch-1.4.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_25]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_25]
Caused by: java.lang.NullPointerException: null
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:70) ~[na:1.7.0_25]
	at java.nio.CharBuffer.wrap(CharBuffer.java:369) ~[na:1.7.0_25]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.utf8Bytes(JsonXContentParser.java:91) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.objectBytes(JsonXContentParser.java:116) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.index.query.TermFilterParser.parse(TermFilterParser.java:97) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:315) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:296) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.index.query.FilteredQueryParser.parse(FilteredQueryParser.java:74) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:252) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33) ~[elasticsearch-1.4.0.jar:na]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:665) ~[elasticsearch-1.4.0.jar:na]
	... 9 common frames omitted
```
Note that the query is successfully parsed the first time it is executed and no error is thrown, but always fail after...
I was not able to reproduce it using curl + shell.

Below is an extract of the code to help reproduce this behaviour:

       org.elasticsearch.node.Node node = NodeBuilder.nodeBuilder().client(true).node();
       Client client = node.client();

       FilterBuilder emptyFilter = FilterBuilders.termFilter("source", "");

       SearchResponse response1 = client.prepareSearch("myindex").setTypes("mytype").setQuery(QueryBuilders.filteredQuery(null, emptyFilter)).execute().actionGet();
       logger.info("First attempt");

       SearchResponse response2 = client.prepareSearch("myindex").setTypes("mytype").setQuery(QueryBuilders.filteredQuery(null, emptyFilter)).execute().actionGet();
       logger.info("Done");

**Comment by iampivot** [comment]
I also see this, with es 1.4.2 client & server. My query and exceptions is as follows;

org.elasticsearch.search.SearchParseException: [karriere][4]: from[0],size[36]: Parse Failure [Failed to parse source [{"from":0,"size":36,"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":{"filters":[{"term":{"regions":""}}]}}}},"sort":[{"adType":{"order":"asc","missing":"_last"}},{"updated":{"order":"desc","missing":"_first"}}],"facets":{"adType":{"terms":{"field":"adType","size":200,"all_terms":true},"facet_filter":{"and":{"filters":[{"term":{"regions":""}}]}},"global":true},"regions":{"terms":{"field":"regions","size":200,"all_terms":true},"facet_filter":{"and":{"filters":[]}},"global":true},"industry":{"terms":{"field":"industry","size":200,"all_terms":true},"facet_filter":{"and":{"filters":[{"term":{"regions":""}}]}},"global":true},"postPlace":{"terms":{"field":"postPlace","size":200,"all_terms":true},"facet_filter":{"and":{"filters":[{"term":{"regions":""}}]}},"global":true},"stateProvince":{"terms":{"field":"stateProvince","size":200,"all_terms":true},"facet_filter":{"and":{"filters":[{"term":{"regions":""}}]}},"global":true},"educationalQualification":{"terms":{"field":"educationalQualification","size":200,"all_terms":true},"facet_filter":{"and":{"filters":[{"term":{"regions":""}}]}},"global":true},"workTime":{"terms":{"field":"workTime","size":200,"all_terms":true},"facet_filter":{"and":{"filters":[{"term":{"regions":""}}]}},"global":true},"numemployed":{"statistical":{"field":"numemployed"}}}}]]

I have just upgraded from 0.20.6 (we had to stay on this version for some time due to hard lucene dependencies elsewhere), where the query was working ok. Is there anything I can do to help diagnose this issue?

**Comment by nicktindall** [comment]
This still occurs in 1.4.3

**Comment by masaruh** [comment]
I think I know what's happening here. It's due to the way Jackson parses input. Long story short, Jackson's ```CBORParser``` (which is used to parse query) has cache and if it finds cached value, it returns null as a result of ```getTextCharacters```, which is called from ```JsonXContentParser.utf8Bytes``` in the stack trace, while it's parsing empty input (If it doesn't, it returns empty array)

First query doesn't get NPE since nothing is cached.

I submitted a PR (https://github.com/FasterXML/jackson-core/pull/183) to make it return empty array instead of null.
(It looks a fix for something different but it fixes this case too, where ```_currentSegment``` is null)

**Comment by javanna** [comment]
Seems related to #6172 if not exactly the same.
