### ISSUE TITLE
Partially propagated keystore settings leading to an inconsistent behaviour  

### ISSUE THREAD

**Issue by mieciu** [elastic/elasticsearch#86340]
### Elasticsearch Version

Version: 7.17.3, Build: default/docker/5ad023604c8d7416c9eb6c0eadb62b14e766caff/2022-04-19T08:11:19.070913226Z, JVM: 18

### Installed Plugins

repository-gcs,repository-s3

### Java Version

_bundled_

### OS Version

Docker container, `Linux 9243db224f20 5.4.0-1032-gcp #34~18.04.1-Ubuntu SMP Thu Dec 10 09:14:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Problem Description

Supposed that we have a 3-node cluster which has a snapshot repository configured. If we delete the client credentials from a one node's keystore (`./bin/elasticsearch-keystore remove gcs.client.CLIENT_NAME.credentials_file`) we will end up in a situation where creation of another snapshot repository which uses this client becomes inconsistent - it might end up creating the repository successfully as well as throw `500` and report an `Unknown client name [elastic-internal-2fb10d]. Existing client configs: default` error

Cluster nodes:
```
10.41.31.169 21  57 2 0.35 0.57 0.66 himrst - instance-0000000001
10.41.0.34   29 100 0 1.49 1.82 2.08 mv     - tiebreaker-0000000002
10.41.0.211  11  58 1 1.84 2.05 2.07 himrst * instance-0000000000
```
in my case `instance-0000000001` had its keystore emptied. 

### Steps to Reproduce

Using ESS:
* Create a 3 node cluster in (any) GCP region 
* Delete `gcs.client.elastic-internal-<cluster_id>.credentials_file` keystore item from one node and restart it.
* Try creating a snapshot repository which uses `elastic-internal-<cluster_id>` client

You'll notice that cluster behaves inconsistently. It'll sometimes create the repository (`{"acknowledged": true}`) but it might end up throwing a `500` as well:

```
{
  "error": {
    "root_cause": [
      {
        "type": "repository_verification_exception",
        "reason": "[found-snapshots-duplicate] [[evt5iq7lT52unCCeGfnZGA, 'RemoteTransportException[[instance-0000000001][172.17.0.10:19570][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[found-snapshots-duplicate] store location [org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore@3b7848c0] is not accessible on the node [{instance-0000000001}{evt5iq7lT52unCCeGfnZGA}{w10Y-ICLT_6fuSOl0gTRwA}{10.41.31.169}{10.41.31.169:19570}{himrst}{logical_availability_zone=zone-1, server_name=instance-0000000001.2fb10dd64aa04bf1a156059df1999420, availability_zone=us-central1-c, xpack.installed=true, data=hot, instance_configuration=gcp.es.datahot.n2.68x10x45, transform.node=true, region=unknown-region}]]; nested: IllegalArgumentException[Unknown client name [elastic-internal-2fb10d]. Existing client configs: default];']]"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[found-snapshots-duplicate] [[evt5iq7lT52unCCeGfnZGA, 'RemoteTransportException[[instance-0000000001][172.17.0.10:19570][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[found-snapshots-duplicate] store location [org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore@3b7848c0] is not accessible on the node [{instance-0000000001}{evt5iq7lT52unCCeGfnZGA}{w10Y-ICLT_6fuSOl0gTRwA}{10.41.31.169}{10.41.31.169:19570}{himrst}{logical_availability_zone=zone-1, server_name=instance-0000000001.2fb10dd64aa04bf1a156059df1999420, availability_zone=us-central1-c, xpack.installed=true, data=hot, instance_configuration=gcp.es.datahot.n2.68x10x45, transform.node=true, region=unknown-region}]]; nested: IllegalArgumentException[Unknown client name [elastic-internal-2fb10d]. Existing client configs: default];']]"
  },
  "status": 500
}
```

### Logs (if relevant)

Instance log which had the keystore emptied:
<details>

```
[2022-05-02T09:40:20,335][WARN ][org.elasticsearch.repositories.VerifyNodeRepositoryAction] [instance-0000000001] [found-snapshots-duplicate] failed to verify repository
org.elasticsearch.repositories.RepositoryVerificationException: [found-snapshots-duplicate] store location [org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore@3b7848c0] is not accessible on the node [{instance-0000000001}{evt5iq7lT52unCCeGfnZGA}{w10Y-ICLT_6fuSOl0gTRwA}{10.41.31.169}{10.41.31.169:19570}{himrst}{logical_availability_zone=zone-1, server_name=instance-0000000001.2fb10dd64aa04bf1a156059df1999420, availability_zone=us-central1-c, xpack.installed=true, data=hot, instance_configuration=gcp.es.datahot.n2.68x10x45, transform.node=true, region=unknown-region}]
Caused by: java.lang.IllegalArgumentException: Unknown client name [elastic-internal-2fb10d]. Existing client configs: default
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageService.client(GoogleCloudStorageService.java:104) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.client(GoogleCloudStorageBlobStore.java:121) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.lambda$writeBlobMultipart$8(GoogleCloudStorageBlobStore.java:474) ~[?:?]
	at org.elasticsearch.repositories.gcs.SocketAccess.lambda$doPrivilegedVoidIOException$0(SocketAccess.java:43) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedVoidIOException(SocketAccess.java:42) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlobMultipart(GoogleCloudStorageBlobStore.java:474) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlob(GoogleCloudStorageBlobStore.java:260) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlob(GoogleCloudStorageBlobContainer.java:78) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.verify(BlobStoreRepository.java:3219) ~[elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.repositories.VerifyNodeRepositoryAction.doVerify(VerifyNodeRepositoryAction.java:130) ~[elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.repositories.VerifyNodeRepositoryAction.access$400(VerifyNodeRepositoryAction.java:37) ~[elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.repositories.VerifyNodeRepositoryAction$VerifyNodeRepositoryRequestHandler.messageReceived(VerifyNodeRepositoryAction.java:162) [elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.repositories.VerifyNodeRepositoryAction$VerifyNodeRepositoryRequestHandler.messageReceived(VerifyNodeRepositoryAction.java:157) [elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:341) [x-pack-security-7.17.3.jar:7.17.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:404) [x-pack-security-7.17.3.jar:7.17.3]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:394) [x-pack-security-7.17.3.jar:7.17.3]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeSystemUser(AuthorizationService.java:620) [x-pack-security-7.17.3.jar:7.17.3]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:250) [x-pack-security-7.17.3.jar:7.17.3]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$1(ServerTransportFilter.java:136) [x-pack-security-7.17.3.jar:7.17.3]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:136) [elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.action.ActionListener$MappedActionListener.onResponse(ActionListener.java:101) [elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticateAsync(AuthenticatorChain.java:102) [x-pack-security-7.17.3.jar:7.17.3]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:199) [x-pack-security-7.17.3.jar:7.17.3]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:128) [x-pack-security-7.17.3.jar:7.17.3]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:415) [x-pack-security-7.17.3.jar:7.17.3]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:67) [elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:260) [elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.3.jar:7.17.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.3.jar:7.17.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
</details>

On instance which had the keystore propagated correctly:
```
[2022-05-02T09:40:20,257][INFO ][org.elasticsearch.repositories.RepositoriesService] [instance-0000000000] put repository [found-snapshots-duplicate]
```

**FYI** @original-brownbear since we've chatted about it

**Comment by DaveCTurner** [comment]
@mieciu this isn't enough logs to diagnose what you're reporting. Could you share full logs from all the nodes and a timeline of the create-repository attempts, including an indication of which ones failed and which ones worked?

**Comment by original-brownbear** [comment]
No feedback closing for now, I can't see where we'd have a bug here with the information provided.
