### ISSUE TITLE
[CI] CertGenCliTests test40RunWithCert failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#86516]
**Build scan:**
https://gradle-enterprise.elastic.co/s/3hwd5tnuvxmlu/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.CertGenCliTests/test40RunWithCert

**Reproduction line:**
`null`

**Applicable branches:**
8.2

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.CertGenCliTests&tests.test=test40RunWithCert

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c sudo -E -u elasticsearch "/tmp/elasticsearch/bin/elasticsearch-reset-password" --auto --batch --silent --username elastic]
   result: exitCode = [75] stdout = [] stderr = [ERROR: Failed to reset password for the [elastic] user]

  at __randomizedtesting.SeedInfo.seed([1E2A95D22AAEDA0B:8645989032EFE3FF]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:204)
  at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:184)
  at org.elasticsearch.packaging.test.CertGenCliTests.setElasticPassword(CertGenCliTests.java:136)
  at org.elasticsearch.packaging.test.CertGenCliTests.lambda$test40RunWithCert$5(CertGenCliTests.java:129)
  at org.elasticsearch.packaging.test.PackagingTestCase.assertWhileRunning(PackagingTestCase.java:285)
  at org.elasticsearch.packaging.test.CertGenCliTests.test40RunWithCert(CertGenCliTests.java:128)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by slobodanadamovic** [comment]
This test failed only once in 90 days. I'm not sure why, but the `exitCode = [75]` suggests that it's a [temporary error](https://github.com/elastic/elasticsearch/blob/d1ba276587dd033120240a74a6a83f1f372fbd4a/libs/cli/src/main/java/org/elasticsearch/cli/ExitCodes.java#L27) and user should retry. 

![image](https://user-images.githubusercontent.com/4357326/177702043-49fa75b3-55f0-433b-b380-41dcad08641d.png)

These are last two lines of elasticsearch log that I can see in the [console log](https://gradle-enterprise.elastic.co/s/3hwd5tnuvxmlu/console-log/raw). GCP logs have been deleted and make it harder to analyze.
```
[2022-05-06T11:52:13,757][INFO ][o.e.x.s.s.SecurityIndexManager] [mynode] security index does not exist, creating [.security-7] with alias [.security]
[2022-05-06T11:52:13,815][INFO ][o.e.c.m.MetadataCreateIndexService] [mynode] [.security-7] creating index, cause [api], templates [], shards [1]/[0]
```

`elasticsearch-reset-password` is invoked 36 seconds after last visible log and failed. I don't have explanation why it failed, but since it only happened once I will close this issue and look into it closer if it occurs again.

```
[2022-05-06T11:51:53,522][INFO ][o.e.p.u.ServerUtils      ] [TEST-CertGenCliTests.test40RunWithCert-seed#[1E2A95D22AAEDA0B]-workerest_thread_info] Waiting for elasticsearch WITH Security enabled
[2022-05-06T11:52:09,527][WARN ][o.e.p.u.Shell            ] [TEST-CertGenCliTests.test40RunWithCert-seed#[1E2A95D22AAEDA0B]-workerest_thread_info] Running command with env: {ES_STARTUP_SLEEP_TIME=25}
[2022-05-06T11:52:48,726][INFO ][o.e.p.u.Shell            ] [TEST-CertGenCliTests.test40RunWithCert-seed#[1E2A95D22AAEDA0B]-workerest_thread_info] Ran: [bash, -c, sudo -E -u elasticsearch "/tmp/elasticsearch/bin/elasticsearch-reset-password" --auto --batch --silent --username elastic] exitCode = [75] stdout = [] stderr = [ERROR: Failed to reset password for the [elastic] user]
```

I suspect this was
