### ISSUE TITLE
org.elasticsearch.client.RequestOptionsTests / org.elasticsearch.client.RequestOptionsTests › classMethod

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#86595]
### CI Link

https://gradle-enterprise.elastic.co/s/ex3xoz5uob4ey/tests/:client:rest:test/org.elasticsearch.client.RestClientBuilderTests/classMethod?top-execution=1
https://gradle-enterprise.elastic.co/s/ex3xoz5uob4ey/tests/:client:rest:test/org.elasticsearch.client.RequestOptionsTests/classMethod?top-execution=1

### Repro line

Test does not report any.

### Does it reproduce?

No

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P14D&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.client.RequestOptionsTests&tests.test=classMethod
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P14D&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.client.RequestOptionsTests&tests.test=classMethod

It looks like this has started on Thursday May 5th

### Failure excerpt

```
com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at org.elasticsearch.client.RequestOptionsTests:
  1) Thread[id=24, name=Libgraal MBean Registration, state=TIMED_WAITING, group=main]
          at java.base@17.0.3/java.lang.Thread.sleep(Native Method)
          at platform/jdk.internal.vm.compiler.management/org.graalvm.compiler.hotspot.management.Factory.run(Factory.java:111)
```

**Comment by idegtiarenko** [comment]
Looks like a duplicate of: https://github.com/elastic/elasticsearch/issues/86567 ?

**Comment by idegtiarenko** [comment]
Duplicate
