### ISSUE TITLE
[CI] SnapshotLifecycleRestIT testStartStopStatus failing

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#86722]
**Build scan:**
https://gradle-enterprise.elastic.co/s/tgkionw5b7sgs/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT/testStartStopStatus

**Reproduction line:**
`./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT.testStartStopStatus" -Dtests.seed=38FAF47065B936C1 -Dtests.locale=zh-TW -Dtests.timezone=Australia/Sydney -Druntime.java=17`

**Applicable branches:**
8.2

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT&tests.test=testStartStopStatus

**Failure excerpt:**
```
java.lang.AssertionError: expected snapshot to exist but it does not: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.ds-.slm-history-5-2022.05.12-000001]","index_uuid":"_na_","resource.type":"index_or_alias","resource.id":".ds-.slm-history-5-2022.05.12-000001","index":".ds-.slm-history-5-2022.05.12-000001"}],"type":"index_not_found_exception","reason":"no such index [.ds-.slm-history-5-2022.05.12-000001]","index_uuid":"_na_","resource.type":"index_or_alias","resource.id":".ds-.slm-history-5-2022.05.12-000001","index":".ds-.slm-history-5-2022.05.12-000001"},"status":404}

  at __randomizedtesting.SeedInfo.seed([38FAF47065B936C1:28DFED8B06B10647]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT.lambda$testStartStopStatus$9(SnapshotLifecycleRestIT.java:339)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1065)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1038)
  at org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT.testStartStopStatus(SnapshotLifecycleRestIT.java:325)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by joegallo** [comment]
```
[2022-05-12T09:59:59,284][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] before test
[2022-05-12T09:59:59,715][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> waiting for SLM to stop
[2022-05-12T09:59:59,719][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> waiting for SLM to stop
[2022-05-12T09:59:59,724][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> waiting for SLM to stop
[2022-05-12T09:59:59,731][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> waiting for SLM to stop
[2022-05-12T09:59:59,742][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> waiting for SLM to stop
[2022-05-12T09:59:59,778][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T09:59:59,782][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T09:59:59,788][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T09:59:59,797][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T09:59:59,810][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T09:59:59,832][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T09:59:59,870][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T09:59:59,939][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T10:00:00,073][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T10:00:00,339][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T10:00:00,859][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T10:00:01,900][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T10:00:03,961][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
[2022-05-12T10:00:09,881][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testStartStopStatus] --> checking for snapshot creation...
```

I'm 97.5% sure the long and short of it is that this test run hit the timing lottery and the right bits of the test run started before midnight UTC, but the wrong bits of the test run executed after midnight UTC. The upshot being that the code is looking for an `.ds-.slm-history-5-2022.05.12-000001` index, but no such index exists in this case because it was actually created the previous day (a few seconds ago) so it's actually `.ds-.slm-history-5-2022.05.11-000001`.

**Comment by joegallo** [comment]
```
diff --git a/x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java b/x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java
index 1eec1143542..b2723029d40 100644
--- a/x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java
+++ b/x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java
@@ -716,7 +716,7 @@ public class SnapshotLifecycleRestIT extends ESRestTestCase {
     }

     private void assertHistoryIndexWaitingForRollover() throws IOException {
-        Step.StepKey stepKey = getStepKeyForIndex(client(), DataStream.getDefaultBackingIndexName(SLM_HISTORY_DATA_STREAM, 1));
+        Step.StepKey stepKey = getStepKeyForIndex(client(), ".ds-.slm-history-5-2022.05.24-000001");
         assertEquals("hot", stepKey.getPhase());
         assertEquals(RolloverAction.NAME, stepKey.getAction());
         assertEquals(WaitForRolloverReadyStep.NAME, stepKey.getName());
```

Making this change (i.e. hardcoding the index to what it would be **tomorrow**) results in a failure with the same stack trace as the original report, so let's go ahead and call that 100% sure that the test hit the timing lottery.
