### ISSUE TITLE
[CI] JarHellTests testNonJDKModuleURLs failing

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#86833]
Failed several times in the past few days https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Zurich&tests.container=org.elasticsearch.jdk.JarHellTests&tests.test=testNonJDKModuleURLs

**Build scan:**
https://gradle-enterprise.elastic.co/s/clidwoim6twwu/tests/:libs:elasticsearch-core:test/org.elasticsearch.jdk.JarHellTests/testNonJDKModuleURLs

**Reproduction line:**
`./gradlew ':libs:elasticsearch-core:test' --tests "org.elasticsearch.jdk.JarHellTests.testNonJDKModuleURLs" -Dtests.seed=E2BD591F7FEB9A87 -Dtests.locale=nl-BE -Dtests.timezone=America/Miquelon -Druntime.java=19`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.jdk.JarHellTests&tests.test=testNonJDKModuleURLs

**Failure excerpt:**
```
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessUserInformation")

  at __randomizedtesting.SeedInfo.seed([E2BD591F7FEB9A87:78B958BEFB5760A9]:0)
  at java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
  at java.security.AccessController.checkPermission(AccessController.java:1068)
  at java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
  at sun.nio.fs.UnixFileAttributeViews$Posix.checkReadExtended(UnixFileAttributeViews.java:186)
  at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:253)
  at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:168)
  at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
  at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
  at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.readAttributes(FilterFileSystemProvider.java:176)
  at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.readAttributes(FilterFileSystemProvider.java:176)
  at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.readAttributes(FilterFileSystemProvider.java:176)
  at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.readAttributes(FilterFileSystemProvider.java:176)
  at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.readAttributes(FilterFileSystemProvider.java:176)
  at java.nio.file.Files.readAttributes(Files.java:1851)
  at java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:114)
  at java.nio.file.Files.copy(Files.java:1308)
  at jdk.internal.module.ModulePath.readModule(ModulePath.java:336)
  at jdk.internal.module.ModulePath.scan(ModulePath.java:237)
  at jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:190)
  at jdk.internal.module.ModulePath.find(ModulePath.java:154)
  at java.lang.module.Resolver.findWithAfterFinder(Resolver.java:849)
  at java.lang.module.Resolver.resolve(Resolver.java:127)
  at java.lang.module.Configuration.resolve(Configuration.java:421)
  at java.lang.module.Configuration.resolve(Configuration.java:255)
  at org.elasticsearch.jdk.JarHellTests.testNonJDKModuleURLs(JarHellTests.java:126)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:828)

```

**Comment by ChrisHegarty** [comment]
First observation, this test only fails with JDK 19-ea. Investigating...

**Comment by ChrisHegarty** [comment]
Likely a JDK bug, see https://bugs.openjdk.java.net/browse/JDK-8267820?focusedCommentId=14496520&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14496520

**Comment by ChrisHegarty** [comment]
JDK bug filed: https://bugs.openjdk.java.net/browse/JDK-8287097

**Comment by hendrikmuhs** [comment]
comeback:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+periodic+java-matrix/ES_RUNTIME_JAVA=openjdk19,GRADLE_TASK=checkPart1,nodes=general-purpose/182/consoleFull

the log does not contain information about the jdk used, so I can't say, whether the jdk version is still too old or the fix does not work.

**Comment by valeriy42** [comment]
Another failure here https://gradle-enterprise.elastic.co/s/pt7gebztzmrl2 . JDK 19 again.

**Comment by grcevski** [comment]
We don't seem to print the JDK version when we get test failures, so I guess there's no way to find out if we had picked up the JDK 19 with the fix for this issue?

**Comment by rjernst** [comment]
@grcevski You can find the jdk version on the "infrastructure" page of the build scan, see `MATRIX_ES_RUNTIME_JAVA`
https://gradle-enterprise.elastic.co/s/pt7gebztzmrl2#infrastructure

**Comment by grcevski** [comment]
Hm, it only says openjdk19, I still can't find the full version in there. The build scan infrastructure says runtime was Oracle OpenJDK Runtime Environment 17.0.2+8-86, but I think that's for the build process.

**Comment by rjernst** [comment]
Oops, sorry, I see what you mean now. The info you want is printed at the beginning of the [console output](https://gradle-enterprise.elastic.co/s/pt7gebztzmrl2/console-log#L34):

```
Runtime JDK Version   : 19-ea (Oracle, 19-ea+16-1057)
```

**Comment by grcevski** [comment]
Thanks, I guess we still haven't picked up the build, it should be in `b26` and if I read the version info correctly it is 16 we are using. @ChrisHegarty is this correct? Maybe we should mute the test for a bit longer until we get the new build?

**Comment by ChrisHegarty** [comment]
Good find. We need to have the 19-EA build updated. It's way out of date.

**Comment by ChrisHegarty** [comment]
The JDK 19 EA build has been updated. This test is no longer failing - as expected. Closing this issue.
