### ISSUE TITLE
Closing and (re-)opening the same shard back-to-back can lead to shard allocation failure

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#86850]
Closing and then quickly (re-)opening the same shard can lead to failures when the shard lock is still held by an action during shard close. Specifically, during ILM's force merging an index with a different codec that involves a close operation this is somewhat likely to come up and result in exceptions like the below:

```
[xxxx] failing shard [FailedShard[routingEntry=[xxxx][2], node[xxxx], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[INITIALIZING], a[id=3cBZzl-1RMGr15jbqe3vMQ], unassigned_info[[reason=INDEX_CLOSED], at[2022-05-16T10:36:31.465Z], delayed=false, allocation_status[fetching_shard_data]], message=failed to create shard,
failure=java.io.IOException: failed to obtain in-memory shard lock, markAsStale=true]] java.io.IOException: failed to obtain in-memory shard lock at org.elasticsearch.index.IndexService.createShard(IndexService.java:513)
~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:828)
 ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:175)
 ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:600)
  ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:577)
   ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:232)
    ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:544)
    ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:530)
    ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:503)
    ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428)
    ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)
    ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:717)
     [elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:260) 
     [elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
     [elasticsearch-8.1.3.jar:8.1.3] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) 
     [?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] at java.lang.Thread.run(Thread.java:833) [?:?]
       Caused by: org.elasticsearch.env.ShardLockObtainFailedException: [.xxx[2]: obtaining shard lock for [starting shard] timed out after [5000ms], lock already held for [closing shard] with age [5693ms] 
       at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:967) 
          ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:867)
          ~[elasticsearch-8.1.3.jar:8.1.3] at org.elasticsearch.index.IndexService.createShard(IndexService.java:416) ~[elasticsearch-8.1.3.jar:8.1.3] ... 16 more
```

**Comment by halfa** [comment]
One of the remediation is to first force-merge at 2 segments and then force-merge at 1 with BEST_COMPRESSION. Reducing shard size also helps, but even at 20GB we were still seeing errors.
