### ISSUE TITLE
[CI] ActiveDirectoryGroupsResolverTests testResolveSubTree failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#86958]
**Build scan:**
https://gradle-enterprise.elastic.co/s/lbk5ynxsss7ym/tests/:x-pack:qa:third-party:active-directory:test/org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryGroupsResolverTests/testResolveSubTree

**Reproduction line:**
`./gradlew ':x-pack:qa:third-party:active-directory:test' --tests "org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryGroupsResolverTests.testResolveSubTree" -Dtests.seed=B75C7A14E63A1ABB -Dtests.locale=is-IS -Dtests.timezone=Australia/Adelaide -Druntime.java=18`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryGroupsResolverTests&tests.test=testResolveSubTree

**Failure excerpt:**
```
com.unboundid.ldap.sdk.LDAPException: A client-side timeout was encountered while waiting 5005ms for a response to simple bind request with message ID 1 for user 'cn=Bruce Banner,CN=Users,DC=ad,DC=test,DC=elasticsearch,DC=com' from server localhost:49182.

  at __randomizedtesting.SeedInfo.seed([B75C7A14E63A1ABB:3CE0D99C8300612D]:0)
  at com.unboundid.ldap.sdk.SimpleBindRequest.handleResponse(SimpleBindRequest.java:738)
  at com.unboundid.ldap.sdk.SimpleBindRequest.process(SimpleBindRequest.java:619)
  at com.unboundid.ldap.sdk.LDAPConnection.processBindOperation(LDAPConnection.java:4560)
  at com.unboundid.ldap.sdk.LDAPConnection.bind(LDAPConnection.java:2393)
  at com.unboundid.ldap.sdk.LDAPConnection.<init>(LDAPConnection.java:700)
  at org.elasticsearch.xpack.security.authc.ldap.LdapTestUtils.lambda$openConnection$0(LdapTestUtils.java:60)
  at java.security.AccessController.doPrivileged(AccessController.java:569)
  at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils.privilegedConnect(LdapUtils.java:76)
  at org.elasticsearch.xpack.security.authc.ldap.LdapTestUtils.openConnection(LdapTestUtils.java:55)
  at org.elasticsearch.xpack.security.authc.ldap.GroupsResolverTestCase.setUpLdapConnection(GroupsResolverTestCase.java:58)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by slobodanadamovic** [comment]
This integration test seems to have reached a default response timeout - which is 5s.

In the past 20 days it happened once:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/4357326/169542945-1c76a3cb-be38-49a7-b38b-c03d5cae9e7e.png">

@elastic/es-security (Team:Security) What would be a rule of thumb I should follow in such cases? 
Would it make sense to increase the response timeout to 10 seconds for this test? 
Or should we ignore this failure for now, since it's temporary and does not happen often (in the past 2.5 months it only timed out 4 times out of ~5k executions)?

**Comment by ywangd** [comment]
The test failed at setup time 

```
  at org.elasticsearch.xpack.security.authc.ldap.LdapTestUtils.openConnection(LdapTestUtils.java:55)
  at org.elasticsearch.xpack.security.authc.ldap.GroupsResolverTestCase.setUpLdapConnection(GroupsResolverTestCase.java:58)
```

Do we know how frequently this failure happens for all test methods from the subclasses of `GroupsResolverTestCase`?

**Comment by slobodanadamovic** [comment]
In the [past 30 days](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P30D&search.timeZoneId=Europe/Zurich&tests.container=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryGroupsResolverTests) there were in total 8 failures for all test methods of `ActiveDirectoryGroupsResolverTests`. The failures are all caused by the timeout when opening LDAP connection.

![image](https://user-images.githubusercontent.com/4357326/170241243-a66db29f-1f72-4da3-a344-77689873bb0b.png)

**Comment by ywangd** [comment]
@slobodanadamovic Thanks for the detailed analysis. 

`SearchGroupsResolverTests` uses a different fixture (`":x-pack:test:idp-fixture", "openldap"`), which explains why it never failed.

The other two test classes both use the smb-fixture and had similar failures on response timeout. Also other test methods in the same test class can still run succesfully when one of them fails. Using the failure in original post as an example, `testResolveSubTree` failed but all other test methods passed. It is worth noting that `testResolveBaseLevel` took `4.187` seconds which is close to the timeout. So I agree that increasing timeout to 10 seconds (roughly 5 + 4.187) is worth trying. If it fails again, we might want to look at how readiness check of the fixture can be improved or switch to a different fixture entirely.

**Comment by slobodanadamovic** [comment]
@ywangd I missed the fact that `SearchGroupsResolverTests` is using different fixture. Thanks for checking it as well.
I will follow up with PR which increases the timeout for all AD tests that use the smb fixture.

**Comment by slobodanadamovic** [comment]
Not sure why this issue has been reopened, when it [did not fail in the past 14 days](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P14D&search.timeZoneId=Europe/Zurich&tests.container=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryGroupsResolverTests).
