### ISSUE TITLE
DatabaseNodeService can create a race condition at node startup

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#86999]
The `DatabaseNodeService` is responsible for synchronizing and updating geoIP data on ingest nodes that is used by the GeoIP processor to perform lookups on incoming data.

This race condition is somewhat low risk. The impacts are that the update process of geoIP data can fail and will need to be retried after the next cluster state update. If the update process fails, a small window exists on the starting node where incoming geoIP data will be marked with the `DatabaseUnavailableProcessor` and need to be reprocessed. Example log of the issue is as follows:

```
[2022-05-17T21:36:32,599][ERROR][o.e.i.g.DatabaseNodeService] [elasticsearch2] failed to retrieve database [GeoLite2-City.mmdb]
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:177) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedRaiseException(ClusterBlocks.java:163) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:913) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.search.TransportSearchAction.executeLocalSearch(TransportSearchAction.java:747) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.search.TransportSearchAction.lambda$executeRequest$6(TransportSearchAction.java:390) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:136) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:112) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:77) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:478) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:277) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:103) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:79) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:53) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:77) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:54) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:170) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:105) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.client.internal.node.NodeClient.doExecute(NodeClient.java:83) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:380) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.client.internal.FilterClient.doExecute(FilterClient.java:57) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.client.internal.OriginSettingClient.doExecute(OriginSettingClient.java:43) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:380) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:366) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.client.internal.support.AbstractClient.search(AbstractClient.java:510) ~[elasticsearch-8.1.3.jar:8.1.3]
	at org.elasticsearch.ingest.geoip.DatabaseNodeService.lambda$retrieveDatabase$13(DatabaseNodeService.java:395) [ingest-geoip-8.1.3.jar:8.1.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:717) [elasticsearch-8.1.3.jar:8.1.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
```

The root cause of this race condition is that `DatabaseNodeService` receives updates to the cluster state by registering itself with the `IngestService#addIngestClusterStateListener`. The `IngestService` is a `ClusterStateApplier` so the cluster state received during updates **has not yet been published** to the `ClusterService` as the current cluster state. When a node is starting, the `IngestService` will see that this state is the first one that lacks the "cluster state not recovered" block on it and will start the geoIP database update process. The update process forks to another thread which eventually calls the search action to pull the database contents locally out of the system index that holds them.

If the forked update process gets to the search operation before the cluster state can be fully committed by the previous thread, AND if the client that submits the search operation deems it appropriate to execute the search against a locally available shard, the search operation will read the current cluster state (which still has the not "recovered block" on it) and throw a `ClusterBlockException`. This causes the download process to fail on the forked thread. The next cluster state update that arrives will restart the process, which should not encounter this race condition again since the preconditions for execution (no cluster blocks) should be stable at that point.

**Comment by jbaiera** [comment]
I spoke with @martijnvg and we figure that a decent solution here is to have `DatabaseNodeService` key its update task off of a standalone `ClusterStateListener` instead of being part of the `IngestService`'s applier method. This allows it to operate on a cluster state that is consistent throughout the system. Additionally, the `DatabaseNodeService` attempts to update pipelines in the ingest service. Because those pipelines are set up in the cluster state applier thread, it's possible (though highly unlikely in practice) that the update method has additional race conditions with creating those pipelines in the first place. Launching the `DatabaseNodeService` update methods as part of a `ClusterStateListener` mitigates that further.

The downside here is that there still exists a window of time where the local geoIP data is missing from a new node, which will mark documents as not having data available to do lookups, but that window exists today still as part of regular node start up and further so in the case that the update method fails with the race condition.

**Comment by jamshid** [comment]
Anyone know if this bug is new in v8 or is it possibly in v7.17?
