### ISSUE TITLE
Should restored indices be automatically be replicated by auto follow patterns?

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#87055]
Auto following automatically triggers index follow of indices in a remote cluster that match with configured patterns. 
When auto following finds indices in the remote cluster that need to be auto followed then it delegates the put follow api.
If the index following is triggered then it records the index uuid of these indices, so auto following doesn't auto 
follow these indices again.

If an index that has been auto followed and is deleted in the leader cluster and then restored and the original replicated index still exists in follower cluster then it can cause an error in the follower cluster:

```
[2022-05-11T16:54:32,137][WARN ][o.e.x.c.a.AutoFollowCoordinator] [xyz] failure occurred while auto following index [[xyz]] for auto follow pattern [xyz]
org.elasticsearch.snapshots.SnapshotRestoreException: [xyz:_latest_/_latest_] cannot restore index [xyz] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name
	at org.elasticsearch.snapshots.RestoreService$RestoreSnapshotStateTask.validateExistingClosedIndex(RestoreService.java:1454) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.snapshots.RestoreService$RestoreSnapshotStateTask.execute(RestoreService.java:1244) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:51) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:836) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:403) ~[elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:243) [elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.cluster.service.MasterService.access$100(MasterService.java:63) [elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170) [elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:146) [elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:202) [elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) [elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:262) [elasticsearch-7.17.2.jar:7.17.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:225) [elasticsearch-7.17.2.jar:7.17.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

The index in the leader cluster has a different index uuid and therefor the the auto follower attempts to follow it using the put follow api. The auto follower thinks that the index is new, but in fact it isn't. It is just an old index being restored.

I'm not sure what is the desired behaviour is here. Maybe the auto following feature should also take the index name into account when auto following indices? Maybe just double check if an index with same name already exists in the follower cluster and if so skip auto following that index. The put follow index api can always be used manually to follow this restored index if that is required.

**Comment by henningandersen** [comment]
We discussed this in the es-distributed team and decided that this is a case where human intervention is necessary. We cannot rebootstrap the follower against the new leader index, since that may make the follower go back in time. We also cannot ignore this completely, since the follower will then be missing any new data that appeared.

This could be reported to users either through the existing autofollower stats, a new autofollower api for this or the new health api. An action to indicate the users choice will be necessary (e.g., to register as already followed).
