### ISSUE TITLE
failed to flush after setting shard to inactive  org.elasticsearch.index.engine.FlushFailedEngineException

### ISSUE THREAD

**Issue by balibaba12** [elastic/elasticsearch#8719]
can you help me?

This is the error which I got:

[2014-12-01 11:20:14,831][INFO ][node                     ] [Human Torch] started 
[2014-12-01 11:51:12,002][WARN ][index.engine.internal    ] [Human Torch] [bifs_index-2014-07-18][0] failed to flush after setting shard to inactive 
org.elasticsearch.index.engine.FlushFailedEngineException: [bifs_index-2014-07-18][0] Flush failed 
        at org.elasticsearch.index.engine.internal.InternalEngine.flush(InternalEngine.java:804) 
        at org.elasticsearch.index.engine.internal.InternalEngine.updateIndexingBufferSize(InternalEngine.java:223) 
        at org.elasticsearch.indices.memory.IndexingMemoryController$ShardsIndicesStatusChecker.run(IndexingMemoryController.java:201) 
        at org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run(ThreadPool.java:437) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441) 
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317) 
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:181) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:205) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) 
        at java.lang.Thread.run(Thread.java:619) 
Caused by: java.io.IOException: Map failed 
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:758) 
        at org.apache.lucene.store.MMapDirectory.map(MMapDirectory.java:283) 
        at org.apache.lucene.store.MMapDirectory$MMapIndexInput.<init>(MMapDirectory.java:228) 
        at org.apache.lucene.store.MMapDirectory.openInput(MMapDirectory.java:195) 
        at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:80) 
        at org.elasticsearch.index.store.Store$StoreDirectory.openInput(Store.java:473) 
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.<init>(CompressingStoredFieldsReader.java:130) 
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsReader(CompressingStoredFieldsFormat.java:113) 
        at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:129) 
        at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:96) 
        at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:141) 
        at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:235) 
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:101) 
        at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:382) 
        at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:111) 
        at org.apache.lucene.search.SearcherManager.<init>(SearcherManager.java:89) 
        at org.elasticsearch.index.engine.internal.InternalEngine.buildSearchManager(InternalEngine.java:1471) 
        at org.elasticsearch.index.engine.internal.InternalEngine.flush(InternalEngine.java:788) 
        ... 12 more 
Caused by: java.lang.OutOfMemoryError: Map failed 
        at sun.nio.ch.FileChannelImpl.map0(Native Method) 
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:755) 
        ... 29 more 
[2014-12-01 11:51:12,819][WARN ][index.engine.internal    ] [Human Torch] [bifs_index-2014-07-18][1] failed to flush after setting shard to inactive 
org.elasticsearch.index.engine.FlushFailedEngineException: [bifs_index-2014-07-18][1] Flush failed 
        at org.elasticsearch.index.engine.internal.InternalEngine.flush(InternalEngine.java:804) 
        at org.elasticsearch.index.engine.internal.InternalEngine.updateIndexingBufferSize(InternalEngine.java:223) 
        at org.elasticsearch.indices.memory.IndexingMemoryController$ShardsIndicesStatusChecker.run(IndexingMemoryController.java:201) 
        at org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run(ThreadPool.java:437) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441) 
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317) 
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:181) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:205) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) 
        at java.lang.Thread.run(Thread.java:619) 
Caused by: java.io.IOException: Map failed 
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:758) 
        at org.apache.lucene.store.MMapDirectory.map(MMapDirectory.java:283) 
        at org.apache.lucene.store.MMapDirectory$MMapIndexInput.<init>(MMapDirectory.java:228) 
        at org.apache.lucene.store.MMapDirectory.openInput(MMapDirectory.java:195) 
        at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:80) 
        at org.elasticsearch.index.store.Store$StoreDirectory.openInput(Store.java:473) 
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.<init>(CompressingStoredFieldsReader.java:130) 
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsReader(CompressingStoredFieldsFormat.java:113) 
        at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:129) 
        at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:96) 
        at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:141) 
        at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:235) 
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:101) 
        at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:382) 
        at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:111) 
        at org.apache.lucene.search.SearcherManager.<init>(SearcherManager.java:89) 
        at org.elasticsearch.index.engine.internal.InternalEngine.buildSearchManager(InternalEngine.java:1471) 
        at org.elasticsearch.index.engine.internal.InternalEngine.flush(InternalEngine.java:788) 
        ... 12 more 
Caused by: java.lang.OutOfMemoryError: Map failed 
        at sun.nio.ch.FileChannelImpl.map0(Native Method) 
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:755) 
        ... 29 mor

**Comment by clintongormley** [comment]
Lots has changed in the last year, so I'll close this issue.
