### ISSUE TITLE
[CI] DecryptionPacketsInputStreamTests testSuccessEncryptAndDecryptTypicalPacketLength failing

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#87308]
### CI Link

https://gradle-enterprise.elastic.co/s/afglqa56dts6e

### Repro line

./gradlew ':x-pack:plugin:repository-encrypted:test' --tests "org.elasticsearch.repositories.encrypted.DecryptionPacketsInputStreamTests.testSuccessEncryptAndDecryptTypicalPacketLength" \   -Dtests.seed=544B090874C4983A \   -Dtests.locale=da-DK \   -Dtests.timezone=Iran \   -Druntime.java=17 \   -Dtests.fips.enabled=true

### Does it reproduce?

No

### Applicable branches

8.3

### Failure history

Based on build emails, may be the first time it failed recently?

### Failure excerpt

```
org.elasticsearch.repositories.encrypted.DecryptionPacketsInputStreamTests > testSuccessEncryptAndDecryptTypicalPacketLength FAILED |  
-- | --
  | java.io.IOException: Exception during packet decryption |  
  | at __randomizedtesting.SeedInfo.seed([544B090874C4983A:63F608DDE1AA8B8]:0) |  
  | at org.elasticsearch.repositories.encrypted.DecryptionPacketsInputStream.decrypt(DecryptionPacketsInputStream.java:164) |  
  | at org.elasticsearch.repositories.encrypted.DecryptionPacketsInputStream.nextComponent(DecryptionPacketsInputStream.java:107) |  
  | at org.elasticsearch.repositories.encrypted.ChainingInputStream.nextIn(ChainingInputStream.java:416) |  
  | at org.elasticsearch.repositories.encrypted.ChainingInputStream.read(ChainingInputStream.java:220) |  
  | at java.base/java.io.InputStream.readNBytes(InputStream.java:409) |  
  | at java.base/java.io.InputStream.readAllBytes(InputStream.java:346) |  
  | at org.elasticsearch.repositories.encrypted.DecryptionPacketsInputStreamTests.testEncryptAndDecryptSuccess(DecryptionPacketsInputStreamTests.java:165) |  
  | at org.elasticsearch.repositories.encrypted.DecryptionPacketsInputStreamTests.testSuccessEncryptAndDecryptTypicalPacketLength(DecryptionPacketsInputStreamTests.java:55) |  
  |   |  
  | Caused by: |  
  | javax.crypto.AEADBadTagException: Error finalising cipher data: mac check in GCM failed |  
  | at java.base/jdk.internal.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source) |  
  | at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) |  
  | at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) |  
  | at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) |  
  | at org.bouncycastle.jcajce.provider.ClassUtil.throwBadTagException(Unknown Source) |  
  | at org.bouncycastle.jcajce.provider.BaseCipher.engineDoFinal(Unknown Source) |  
  | at org.bouncycastle.jcajce.provider.BaseCipher.engineDoFinal(Unknown Source) |  
  | at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2337) |  
  | at org.elasticsearch.repositories.encrypted.DecryptionPacketsInputStream.decrypt(DecryptionPacketsInputStream.java:162) |  
  | ... 7 more
```

**Comment by original-brownbear** [comment]
@albertzaharovits could you take a look here? This is beyond my encryption skills :)
