### ISSUE TITLE
[CI] RestClientMultipleHostsIntegTests testNonRetryableException failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#87314]
**Build scan:**
https://gradle-enterprise.elastic.co/s/s6afak4ddj7pq/tests/:client:rest:test/org.elasticsearch.client.RestClientMultipleHostsIntegTests/testNonRetryableException

**Reproduction line:**
`null`

**Applicable branches:**
master, 8.3 and 7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.client.RestClientMultipleHostsIntegTests&tests.test=testNonRetryableException

**Failure excerpt:**
```
java.lang.AssertionError: expected:<2> but was:<3>

  at __randomizedtesting.SeedInfo.seed([760E01B07BB0737:1E21C6ABA4668226]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:645)
  at org.junit.Assert.assertEquals(Assert.java:631)
  at org.elasticsearch.client.RestClientMultipleHostsIntegTests.testNonRetryableException(RestClientMultipleHostsIntegTests.java:351)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by martijnvg** [comment]
Two more instances:
* https://gradle-enterprise.elastic.co/s/xw66zjwvumyvu
* https://gradle-enterprise.elastic.co/s/rm6qtzntmjpec

I also muted this test in the 8.3 branch.

**Comment by cbuescher** [comment]
I just found this test still muted and am assigning a medium-risk label for now to make it visible.
