### ISSUE TITLE
[CI] ReloadingDatabasesWhilePerformingGeoLookupsIT test failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#87453]
**Build scan:**
https://gradle-enterprise.elastic.co/s/7oyy2l4mpqghu/tests/:modules:ingest-geoip:internalClusterTest/org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT/test

**Reproduction line:**
`./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT.test" -Dtests.seed=BE466E926F86A692 -Dtests.locale=en-IE -Dtests.timezone=Africa/El_Aaiun -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT&tests.test=test

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: null
     but: was <java.io.IOException: access denied: /dev/shm/elastic+elasticsearch+main+intake+multijob+part1/modules/ingest-geoip/build/testrun/internalClusterTest/temp/org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT_BE466E926F86A692-001/tempDir-003/GeoLite2-City-Test.mmdb>

  at __randomizedtesting.SeedInfo.seed([BE466E926F86A692:36125148C17ACB6A]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT.test(ReloadingDatabasesWhilePerformingGeoLookupsIT.java:177)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by martijnvg** [comment]
This is the actual failure:

```
[2022-06-07T10:50:09,535][ERROR][o.e.i.g.ReloadingDatabasesWhilePerformingGeoLookupsIT] [[Thread-22]] error in update databases thread after run [1] |  
-- | --
  | java.io.IOException: access denied: /dev/shm/elastic+elasticsearch+main+intake+multijob+part1/modules/ingest-geoip/build/testrun/internalClusterTest/temp/org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT_BE466E926F86A692-001/tempDir-003/GeoLite2-City-Test.mmdb |  
  | at org.apache.lucene.tests.mockfile.WindowsFS.checkDeleteAccess(WindowsFS.java:116) ~[lucene-test-framework-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13] |  
  | at org.apache.lucene.tests.mockfile.WindowsFS.deleteIfExists(WindowsFS.java:165) ~[lucene-test-framework-9.2.0.jar:9.2.0 ba8c3a806ada3d7b3c34d408e449a92376a8481b - romseygeek - 2022-05-19 15:10:13] |  
  | at java.nio.file.Files.deleteIfExists(Files.java:1191) ~[?:?] |  
  | at java.nio.file.Files.copy(Files.java:3148) ~[?:?] |  
  | at org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT.lambda$test$2(ReloadingDatabasesWhilePerformingGeoLookupsIT.java:146) [internalClusterTest/:?] |  
  | at java.lang.Thread.run(Thread.java:833) [?:?]
```

This happens while performing: `Files.copy(source, geoIpTmpDir.resolve("GeoLite2-City-Test.mmdb"), StandardCopyOption.REPLACE_EXISTING);`

The `GeoLite2-City-Test.mmdb` in geoip tmp dir is being used while being replaced with another file. 
This is what happens in the wild too when a new database is being downloaded from geoip index.
(only then `Files.move(...)` is used, but `WindowsFS` also checks for open files and would also fail)

I think this test should use a `SuppressFileSystems` annotation.
