### ISSUE TITLE
[CI] MlDistributedFailureIT testFullClusterRestart failing

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#87593]
**Build scan:**
https://gradle-enterprise.elastic.co/s/myalsc2z2ojgc/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testFullClusterRestart

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testFullClusterRestart" -Dtests.seed=71D6AD0C1F2BC9E6 -Dtests.locale=sk -Dtests.timezone=America/Regina -Druntime.java=19`

**Applicable branches:**
8.3

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT&tests.test=testFullClusterRestart

**Failure excerpt:**
```
java.lang.AssertionError: Expected 2 tasks, but got [[{"id":"job-full-cluster-restart-job","task":{"xpack/ml/job":{"params":{"job_id":"full-cluster-restart-job","timeout":"1800000ms","job":{"job_id":"full-cluster-restart-job","job_type":"anomaly_detector","job_version":"8.3.0","create_time":1655069657507,"analysis_config":{"bucket_span":"1h","detectors":[{"detector_description":"count","function":"count","detector_index":0}],"influencers":[],"model_prune_window":"30d"},"analysis_limits":{"model_memory_limit":"1024mb","categorization_examples_limit":4},"data_description":{"time_field":"time","time_format":"yyyy-MM-dd HH:mm:ss"},"model_snapshot_retention_days":10,"daily_model_snapshot_retention_after_days":1,"results_index_name":"shared","allow_lazy_open":false}},"state":{"state":"failed","allocation_id":6,"reason":"failed to search for associated datafeed"}}},"allocation_id":6,"assignment":{"executor_node":"yilJY3LvROa__htYGYf5Ww","explanation":""},"allocation_id_on_last_status_update":6}]] expected:<2> but was:<1>

  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:645)
  at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$run$25(MlDistributedFailureIT.java:731)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1098)
  at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.run(MlDistributedFailureIT.java:727)
  at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testFullClusterRestart(MlDistributedFailureIT.java:158)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:828)

```

**Comment by davidkyle** [comment]
The missing task is the datefeed which is reported in the job's failed state:

```
"state":{"state":"failed","allocation_id":6,"reason":"failed to search for associated datafeed"}
```

Then in the logs we have:

```
[2022-06-12T15:34:22,395][ERROR][o.e.x.m.j.t.OpenJobPersistentTasksExecutor] [node_t1] [full-cluster-restart-job] failed to search for associated datafeed
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.node.DiscoveryNode.getVersion()" because the return value of "org.elasticsearch.cluster.node.DiscoveryNodes.getMasterNode()" is null
	at org.elasticsearch.xpack.ml.job.task.OpenJobPersistentTasksExecutor.isMasterNodeVersionOnOrAfter(OpenJobPersistentTasksExecutor.java:393) ~[main/:?]
	at org.elasticsearch.xpack.ml.job.task.OpenJobPersistentTasksExecutor.lambda$runJob$14(OpenJobPersistentTasksExecutor.java:306) ~[main/:?]
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:162) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.xpack.ml.job.task.OpenJobPersistentTasksExecutor.lambda$getRunningDatafeed$25(OpenJobPersistentTasksExecutor.java:407) [main/:?]
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:162) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.xpack.ml.datafeed.persistence.DatafeedConfigProvider.lambda$findDatafeedIdsForJobIds$1(DatafeedConfigProvider.java:212) [main/:?]
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:162) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.client.internal.node.NodeClient$ActionResponseTaskListener.onResponse(NodeClient.java:175) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:171) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:165) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$RunAfterActionListener.onResponse(ActionListener.java:367) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:723) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchLookupFieldsPhase.run(FetchLookupFieldsPhase.java:75) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:470) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:464) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.ExpandSearchPhase.onPhaseDone(ExpandSearchPhase.java:151) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:105) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:470) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:464) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:269) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:106) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:115) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:90) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:768) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:828) [?:?]
```

**Comment by droberts195** [comment]
We should take this as an opportunity to make all our code robust when there temporarily isn't a master node.  We don't want anything to go into the failed state just because it happened to do something during the second or two when a new master was being elected.  Instead we should just try again next time there's a cluster state update.

These are all the places in the ML plugin where we get the current master node:

```
bash-3.2$ find src/main -name '*.java' | xargs grep getMasterNode
src/main/java/org/elasticsearch/xpack/ml/action/TransportCloseJobAction.java:            if (nodes.getMasterNode() == null) {
src/main/java/org/elasticsearch/xpack/ml/action/TransportCloseJobAction.java:                    nodes.getMasterNode(),
src/main/java/org/elasticsearch/xpack/ml/action/TransportStopDatafeedAction.java:            if (nodes.getMasterNode() == null) {
src/main/java/org/elasticsearch/xpack/ml/action/TransportStopDatafeedAction.java:                    nodes.getMasterNode(),
src/main/java/org/elasticsearch/xpack/ml/action/TransportStopDataFrameAnalyticsAction.java:            redirectToMasterNode(nodes.getMasterNode(), request, listener);
src/main/java/org/elasticsearch/xpack/ml/action/TransportExplainDataFrameAnalyticsAction.java:                if (node.getId().equals(nodes.getMasterNodeId())) {
src/main/java/org/elasticsearch/xpack/ml/action/TransportStopTrainedModelDeploymentAction.java:            redirectToMasterNode(nodes.getMasterNode(), request, listener);
src/main/java/org/elasticsearch/xpack/ml/job/task/OpenJobPersistentTasksExecutor.java:        return clusterState.nodes().getMasterNode().getVersion().onOrAfter(version);
src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentService.java:        DiscoveryNode masterNode = currentState.nodes().getMasterNode();
```

It's clear from the `grep` output that some of those already account for no master node, but all of them should be checked to make sure they behave sensibly in the absence of a master node.  For anything running internally within the cluster the response should be to try again once a master node is available and not fail.

**Comment by pxsalehi** [comment]
There is also this failure: https://gradle-enterprise.elastic.co/s/7qfqe7pn5ulgq which I think is related.

**Comment by davidkyle** [comment]
Closing this issue as the source of the NPE (`org.elasticsearch.cluster.node.DiscoveryNodes.getMasterNode() is null`) has been replaced by a check on the Transport version. 

> It's clear from the grep output that some of those already account for no master node, but all of them should be checked to make sure they behave sensibly in the absence of a master node. 

✅ All uses of `DiscoveryNodes::getMasterNode` have a null check.
