### ISSUE TITLE
[CI] DebMetadataTests test05CheckLintian failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#87632]
This is an upgraded version of Lintian on Ubuntu 22.04 taking offence at the Intel MKL libraries not being linked against libc:

```
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx2.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx512.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx512_mic.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_core.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_def.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_gnu_thread.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_intel_lp64.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_mc3.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx2.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx512.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx512_mic.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_cmpt.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_def.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_mc3.so	
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/tkvxgodtbhuzm/tests/:qa:os:destructiveDistroTest.default-deb/org.elasticsearch.packaging.test.DebMetadataTests/test05CheckLintian

**Reproduction line:**
`null`

**Applicable branches:**
master, 8.3

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DebMetadataTests&tests.test=test05CheckLintian

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c lintian --fail-on warning /var/lib/jenkins/workspace/elastic+elasticsearch+main+multijob+packaging-tests-unix/os/ubuntu-22.04-packaging/distribution/packages/deb/build/distributions/elasticsearch-8.4.0-SNAPSHOT-amd64.deb]
   result: exitCode = [2] stdout = [E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx2.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx512.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx512_mic.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_core.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_def.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_gnu_thread.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_intel_lp64.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_mc3.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx2.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx512.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx512_mic.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_cmpt.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_def.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_mc3.so
E: elasticsearch: malformed-override Unknown tag systemd-service-file-outside-lib in line 28
W: elasticsearch: mismatched-override unknown-field elasticsearch-*.deb License
W: elasticsearch: unknown-field License
N: 354 hints overridden (190 errors, 121 warnings, 43 info); 5 unused overrides] stderr = [running with root privileges is not recommended!]

  at __randomizedtesting.SeedInfo.seed([755215F255DF0D76:B5AC891EEFAB68CD]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.test.DebMetadataTests.test05CheckLintian(DebMetadataTests.java:38)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by droberts195** [comment]
What Lintian is saying is not correct - MKL _is_ linked against libc, for example:

```
[dave@marple lib]$ ldd libmkl_core.so
        linux-vdso.so.1 =>  (0x00007ffd9bbb9000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4dd9fab000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4dd9d8e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4dd99cd000) <-- HERE
        /lib64/ld-linux-x86-64.so.2 (0x00007f4dde7fd000)
[dave@marple lib]$ ldd libmkl_avx2.so
        linux-vdso.so.1 =>  (0x00007ffe50be0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0a085e7000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f0a08225000) <-- HERE
        /lib64/ld-linux-x86-64.so.2 (0x00007f0a0b788000)
```

The ldd output looks the same as it does for our libraries, for example:

```
[dave@marple lib]$ ldd libMlCore.so
        linux-vdso.so.1 =>  (0x00007ffcf0d99000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f85a3183000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f85a2f7e000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f85a2d76000)
        libboost_log-gcc10-mt-x64-1_77.so.1.77.0 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libboost_log-gcc10-mt-x64-1_77.so.1.77.0 (0x00007f85a2cce000)
        libxml2.so.2 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libxml2.so.2 (0x00007f85a2b20000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f85a290a000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f85a2608000)
        libboost_log_setup-gcc10-mt-x64-1_77.so.1.77.0 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libboost_log_setup-gcc10-mt-x64-1_77.so.1.77.0 (0x00007f85a2519000)
        libboost_iostreams-gcc10-mt-x64-1_77.so.1.77.0 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libboost_iostreams-gcc10-mt-x64-1_77.so.1.77.0 (0x00007f85a2504000)
        libboost_thread-gcc10-mt-x64-1_77.so.1.77.0 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libboost_thread-gcc10-mt-x64-1_77.so.1.77.0 (0x00007f85a24e7000)
        libboost_filesystem-gcc10-mt-x64-1_77.so.1.77.0 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libboost_filesystem-gcc10-mt-x64-1_77.so.1.77.0 (0x00007f85a24c3000)
        libstdc++.so.6 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libstdc++.so.6 (0x00007f85a2237000)
        libgcc_s.so.1 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libgcc_s.so.1 (0x00007f85a221b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f85a1e5a000) <-- HERE
        /lib64/ld-linux-x86-64.so.2 (0x00007f85a3606000)
        libboost_chrono-gcc10-mt-x64-1_77.so.1.77.0 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libboost_chrono-gcc10-mt-x64-1_77.so.1.77.0 (0x00007f85a1e4e000)
        libboost_atomic-gcc10-mt-x64-1_77.so.1.77.0 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libboost_atomic-gcc10-mt-x64-1_77.so.1.77.0 (0x00007f85a1e44000)
        libboost_regex-gcc10-mt-x64-1_77.so.1.77.0 => /home/dave/ml-cpp/build/distribution/platform/linux-x86_64/lib/./libboost_regex-gcc10-mt-x64-1_77.so.1.77.0 (0x00007f85a1deb000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f85a1bda000)
```

Presumably there's some low level difference in the way libc is linked that's causing the problem.

**Comment by droberts195** [comment]
It's possible to fix this as follows:

```
[dave@marple lib]$ patchelf --add-needed libc.so.6 libmkl_core.so
[dave@marple lib]$ readelf -a libmkl_core.so | grep 'Shared library'
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
```

However, to then redistribute the fixed version would be a breach of the [MKL license](https://github.com/elastic/ml-cpp/blob/769008947c1f9be6e182d9cc5e011e43faf17a5b/3rd_party/licenses/MKL-LICENSE.txt#L5):

> You may use and redistribute the software (the "Software"), **without modification**...

**Comment by droberts195** [comment]
Yes, agreed.  I've opened #87706 to try to do this.  Tomorrow I'll get an Ubuntu 22.04 machine to try it on so that I can make sure I've got the syntax right.
