### ISSUE TITLE
[CI] Leftover health-node task in docs test suite causes suite timeout

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#87784]
**Build scan:**
https://gradle-enterprise.elastic.co/s/7t6tvecxnp4ka/tests/:docs:yamlRestTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Ftransform%2Fapis%2Fget-transform-stats%2Fline_275%7D

**Reproduction line:**
`./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/transform/apis/get-transform-stats/line_275}" -Dtests.seed=12EFD88F87A1877A -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=en -Dtests.timezone=America/Blanc-Sablon -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dreference/transform/apis/get-transform-stats/line_275%7D

**Failure excerpt:**
```
org.junit.AssumptionViolatedException: [reference/transform/apis/get-transform-stats/line_275] skipped, reason: [todo] unsupported features [default_shards, stash_in_key, stash_in_path, stash_path_replace, warnings, always_skip]

  at com.carrotsearch.randomizedtesting.RandomizedTest.assumeTrue(RandomizedTest.java:744)
  at com.carrotsearch.randomizedtesting.RandomizedTest.assumeFalse(RandomizedTest.java:752)
  at org.apache.lucene.tests.util.LuceneTestCase.assumeFalse(LuceneTestCase.java:898)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:433)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by droberts195** [comment]
This isn't a transform test failure.

65 tests in the suite have taken over 30 seconds to run because a health API task is never cleaned up between tests and the test framework waits up to 30 seconds for tasks to stop:

```
java.lang.AssertionError: 1 active tasks found: |  
-- | --
  | health-node[c]                 GI71M8r-TSqrOpbFcP-Uzw:22889 cluster:12                   persistent 1655448411364 06:46:51 3.2m        127.0.0.1 node-0 id=health-node |  
  | expected:<0> but was:<1>
```

Then the test suite times out as a result.

**Comment by droberts195** [comment]
I guess either the health tasks need to be cleaned up between docs tests, or else the wait for pending tasks to complete needs to ignore health tasks if they're supposed to be running throughout the docs tests.

**Comment by droberts195** [comment]
@gmarouli I think this is a side effect of #86131, which was merged yesterday.

If the health-node task is supposed to run forever during REST tests and not be stopped and restarted between each test then you probably want to change the default task filter in https://github.com/elastic/elasticsearch/blob/43b69b6f704da5b0a41f1785635f2c894bd9d2e5/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java#L449-L451

But then also check if anything needs modifying that already specifies a custom task filter to https://github.com/elastic/elasticsearch/blob/43b69b6f704da5b0a41f1785635f2c894bd9d2e5/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java#L462

**Comment by gmarouli** [comment]
@droberts195 thank you for the analysis and the pointers. I will fix it.
