### ISSUE TITLE
[CI] ConfigurationTests test10Install failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#88093]
**Build scan:**
https://gradle-enterprise.elastic.co/s/3e4pcadoblml4/tests/:qa:os:destructiveDistroTest.default-windows-archive/org.elasticsearch.packaging.test.ConfigurationTests/test10Install

**Reproduction line:**
`null`

**Applicable branches:**
8.3

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.ConfigurationTests&tests.test=test10Install

**Failure excerpt:**
```
java.lang.RuntimeException: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch-8.3.0-SNAPSHOT -> C:\tmp\elasticsearch

  at __randomizedtesting.SeedInfo.seed([F16BD16EC2CDC407:1D31DD969E5D7B5D]:0)
  at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:136)
  at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:100)
  at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:55)
  at org.elasticsearch.packaging.test.PackagingTestCase.install(PackagingTestCase.java:240)
  at org.elasticsearch.packaging.test.ConfigurationTests.test10Install(ConfigurationTests.java:34)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch-8.3.0-SNAPSHOT -> C:\tmp\elasticsearch

    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
    at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
    at java.nio.file.Files.move(Files.java:1432)
    at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:134)
    at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:100)
    at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:55)
    at org.elasticsearch.packaging.test.PackagingTestCase.install(PackagingTestCase.java:240)
    at org.elasticsearch.packaging.test.ConfigurationTests.test10Install(ConfigurationTests.java:34)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:577)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by mark-vieira** [comment]
This looks like a transient failure to me. We've only seen one instance of this in the past 30 days. Closing for now.
