### ISSUE TITLE
[CI] InternalAutoDateHistogramTests testSerializationPre830 failing

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#88137]
When I run the test locally with no seed and -Dtests.iters=100 I get 7 failures, so less than 10% of the time, but still quite high. I think someone merged something very recently that happened to fail first after my PR. Anyone working on code affecting the DateHistogram?

**Build scan:**
https://gradle-enterprise.elastic.co/s/t2765oinlidb2/tests/:server:test/org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests/testSerializationPre830

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testSerializationPre830" -Dtests.seed=8803810CBB78AC0B -Dtests.locale=ro -Dtests.timezone=Etc/GMT-5 -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests&tests.test=testSerializationPre830

**Failure excerpt:**
```
java.lang.AssertionError: expected:<1> but was:<5448336502868150856>

  at __randomizedtesting.SeedInfo.seed([8803810CBB78AC0B:536A9C0AC6C9A12]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:645)
  at org.junit.Assert.assertEquals(Assert.java:631)
  at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testSerializationPre830(InternalAutoDateHistogramTests.java:474)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by craigtaverner** [comment]
The assertion number is so far off I wonder if this is an integer overflow error?
```
expected:<1> but was:<5448336502868150856>
```

Or perhaps a deserialization error:

```
        InternalAutoDateHistogram deserialized = copyInstance(instance, version);
        assertEquals(1, deserialized.getBucketInnerInterval());
```

**Comment by benwtrent** [comment]
@craigtaverner I think this has to do with the test assuming the serialization version it is serializing from is from before 8.3. 

That is no longer the case, periodically it could be serializing from 8.3->8.4

Check this block of code out:

https://github.com/elastic/elasticsearch/blob/00b3721108d749dcaf88ee187a61e66b21006060/server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogram.java#L226..L230

The "Current" version agg is initialized with a completely random interval. The test is assuming that the stream input is from pre 8.3 and consequently the interval gets set to 1. 

Well, that is no longer the case due to version bump.

**Comment by joegallo** [comment]
++, I ran a quick bisect because I ran into this also, and the commit that comes up as 'bad' is 99b4425d78b79cd56b3cb70a58d411bc066d0cd0 (the 8.3.1 version bump itself).

**Comment by javanna** [comment]
That's definitely the problem, and the right fix. Test bug, my bad :)

**Comment by joegallo** [comment]
No worries! Happy to help.

**Comment by salvatore-campagna** [comment]
The issue has been fixed and re-opened by exalate, probably due to some issue while synching with Jira.
