### ISSUE TITLE
RemoveProcessorTests.testRemoveFields reproducible failure

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#88182]
### CI Link

local

### Repro line

```
./gradlew ':modules:ingest-common:test'
  --tests "org.elasticsearch.ingest.common.RemoveProcessorTests.testRemoveFields"
  -Dtests.seed=36B04332FE19F8F0 -Dtests.locale=zh-Hans-SG
  -Dtests.timezone=America/North_Dakota/New_Salem -Druntime.java=18
```

### Does it reproduce?

Yes

### Applicable branches

master at least

### Failure excerpt

```
REPRODUCE WITH: ./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.RemoveProcessorTests.testRemoveFields" -Dtests.seed=36B04332FE19F8F0 -Dtests.locale=zh-Hans-SG -Dtests.timezone=America/North_Dakota/New_Salem -Druntime.java=18

org.elasticsearch.ingest.common.RemoveProcessorTests > testRemoveFields FAILED
    java.lang.IllegalArgumentException: _version cannot be null
        at __randomizedtesting.SeedInfo.seed([36B04332FE19F8F0:B111437B07740782]:0)
        at org.elasticsearch.ingest.IngestSourceAndMetadata.versionValidator(IngestSourceAndMetadata.java:543)
        at org.elasticsearch.ingest.IngestSourceAndMetadata.remove(IngestSourceAndMetadata.java:300)
        at org.elasticsearch.ingest.IngestDocument.removeField(IngestDocument.java:324)
        at org.elasticsearch.ingest.IngestDocument.removeField(IngestDocument.java:301)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.elasticsearch.ingest.common.RemoveProcessor.fieldsToRemoveProcessor(RemoveProcessor.java:64)
        at org.elasticsearch.ingest.common.RemoveProcessor.execute(RemoveProcessor.java:54)
        at org.elasticsearch.ingest.common.RemoveProcessorTests.testRemoveFields(RemoveProcessorTests.java:39)


Suite: Test class org.elasticsearch.ingest.common.RemoveProcessorTests
  1> [2022-06-29T09:34:07,872][INFO ][o.e.i.c.RemoveProcessorTests] [testRemoveFields] before test
  1> [2022-06-29T09:34:07,933][INFO ][o.e.i.c.RemoveProcessorTests] [testRemoveFields] after test
  2> REPRODUCE WITH: ./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.RemoveProcessorTests.testRemoveFields" -Dtests.seed=36B04332FE19F8F0 -Dtests.locale=zh-Hans-SG -Dtests.timezone=America/North_Dakota/New_Salem -Druntime.java=18
  2> java.lang.IllegalArgumentException: _version cannot be null
        at __randomizedtesting.SeedInfo.seed([36B04332FE19F8F0:B111437B07740782]:0)
        at org.elasticsearch.ingest.IngestSourceAndMetadata.versionValidator(IngestSourceAndMetadata.java:543)
        at org.elasticsearch.ingest.IngestSourceAndMetadata.remove(IngestSourceAndMetadata.java:300)
        at org.elasticsearch.ingest.IngestDocument.removeField(IngestDocument.java:324)
        at org.elasticsearch.ingest.IngestDocument.removeField(IngestDocument.java:301)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.elasticsearch.ingest.common.RemoveProcessor.fieldsToRemoveProcessor(RemoveProcessor.java:64)
        at org.elasticsearch.ingest.common.RemoveProcessor.execute(RemoveProcessor.java:54)
        at org.elasticsearch.ingest.common.RemoveProcessorTests.testRemoveFields(RemoveProcessorTests.java:39)
  2> NOTE: leaving temporary files on disk at: /home/nik9000/Code/Elastic/elasticsearch/modules/ingest-common/build/testrun/test/temp/org.elasticsearch.ingest.common.RemoveProcessorTests_36B04332FE19F8F0-002
  2> NOTE: test params are: codec=Asserting(Lucene92): {}, docValues:{}, maxPointsInLeafNode=562, maxMBSortInHeap=6.759347191787296, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=zh-Hans-SG, timezone=America/North_Dakota/New_Salem
  2> NOTE: Linux 5.18.7-arch1-1 amd64/N/A 18.0.1.1 (64-bit)/cpus=16,threads=1,free=453204944,total=536870912
  2> NOTE: All tests run in this JVM: [RemoveProcessorTests]
WARNING: A terminally deprecated method in java.lang.System has been called
```

**Comment by dakrone** [comment]
This was already fixed by #88183
