### ISSUE TITLE
[CI] DebMetadataTests test05CheckLintian failing

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#88252]
**Build scan:**
https://gradle-enterprise.elastic.co/s/qhcumlpvkjrag/tests/:qa:os:destructiveDistroTest.default-deb/org.elasticsearch.packaging.test.DebMetadataTests/test05CheckLintian

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DebMetadataTests&tests.test=test05CheckLintian

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c lintian --fail-on-warnings /var/lib/jenkins/workspace/elastic+elasticsearch+main+multijob+packaging-tests-unix/os/debian-10-packaging/distribution/packages/deb/build/distributions/elasticsearch-8.4.0-SNAPSHOT-amd64.deb]
   result: exitCode = [1] stdout = [W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/autodetect
W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/categorize
W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller
W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/data_frame_analyzer
W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/normalize
W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/pytorch_inference
N: 354 tags overridden (191 errors, 121 warnings, 42 info); 5 unused overrides] stderr = [warning: the authors of lintian do not recommend running it with root privileges!
warning: --fail-on-warnings is deprecated]

  at __randomizedtesting.SeedInfo.seed([BB3B9D8B6B37758A:7BC50167D1431031]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.test.DebMetadataTests.test05CheckLintian(DebMetadataTests.java:44)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by droberts195** [comment]
Fixed by https://github.com/elastic/ml-cpp/pull/2346
