### ISSUE TITLE
[CI] PluginsServiceTests classMethod failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#88275]
**Build scan:**
https://gradle-enterprise.elastic.co/s/jfq4w6bzdfc44/tests/:server:test/org.elasticsearch.plugins.PluginsServiceTests/classMethod

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.plugins.PluginsServiceTests&tests.test=classMethod

**Failure excerpt:**
```
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\jenkins\workspace\platform-support\211\server\build\testrun\test\temp\org.elasticsearch.plugins.PluginsServiceTests_D6E9C143DF9FF0A4-001\testLoadServiceProviders-002\custom_plugin_string.jar: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\platform-support\211\server\build\testrun\test\temp\org.elasticsearch.plugins.PluginsServiceTests_D6E9C143DF9FF0A4-001\testLoadServiceProviders-002\custom_plugin_string.jar: The process cannot access the file because it is being used by another process
   C:\Users\jenkins\workspace\platform-support\211\server\build\testrun\test\temp\org.elasticsearch.plugins.PluginsServiceTests_D6E9C143DF9FF0A4-001\testLoadServiceProviders-002: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\211\server\build\testrun\test\temp\org.elasticsearch.plugins.PluginsServiceTests_D6E9C143DF9FF0A4-001\testLoadServiceProviders-002
   C:\Users\jenkins\workspace\platform-support\211\server\build\testrun\test\temp\org.elasticsearch.plugins.PluginsServiceTests_D6E9C143DF9FF0A4-001\testLoadServiceProviders-001\custom_plugin_integer.jar: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\platform-support\211\server\build\testrun\test\temp\org.elasticsearch.plugins.PluginsServiceTests_D6E9C143DF9FF0A4-001\testLoadServiceProviders-001\custom_plugin_integer.jar: The process cannot access the file because it is being used by another process
   C:\Users\jenkins\workspace\platform-support\211\server\build\testrun\test\temp\org.elasticsearch.plugins.PluginsServiceTests_D6E9C143DF9FF0A4-001\testLoadServiceProviders-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\211\server\build\testrun\test\temp\org.elasticsearch.plugins.PluginsServiceTests_D6E9C143DF9FF0A4-001\testLoadServiceProviders-001
   C:\Users\jenkins\workspace\platform-support\211\server\build\testrun\test\temp\org.elasticsearch.plugins.PluginsServiceTests_D6E9C143DF9FF0A4-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\211\server\build\testrun\test\temp\org.elasticsearch.plugins.PluginsServiceTests_D6E9C143DF9FF0A4-001

  at __randomizedtesting.SeedInfo.seed([D6E9C143DF9FF0A4]:0)
  at org.apache.lucene.util.IOUtils.rm(IOUtils.java:341)
  at org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:209)
  at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by idegtiarenko** [comment]
Looks like this only happens on windows

**Comment by csoulios** [comment]
There were several failures today on windows environments:

https://gradle-enterprise.elastic.co/s/2femtkz4mtjl4
https://gradle-enterprise.elastic.co/s/w42xmnc5ztn7g
https://gradle-enterprise.elastic.co/s/uk4layv32tbcs

**Comment by breskeby** [comment]
@ChrisHegarty Unfortunately this started to show up again today: https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.plugins.PluginsServiceTests

**Comment by Luegg** [comment]
another instance: https://gradle-enterprise.elastic.co/s/ccdehemdth72e/tests/:server:test/org.elasticsearch.plugins.PluginsServiceTests/classMethod?top-execution=1

**Comment by Luegg** [comment]
Looks like the error started to show up once more: https://gradle-enterprise.elastic.co/s/ei6iqekw225sa/console-log?task=:server:test

**Comment by iverase** [comment]
More failures: https://gradle-enterprise.elastic.co/s/tsmqsxnunnvq4

As far as I can see only windows

**Comment by breskeby** [comment]
I've raised a PR with a potential fix

**Comment by craigtaverner** [comment]
This failed several times again this morning. For example: https://gradle-enterprise.elastic.co/s/rk6mdmqybrebg/tests/:server:test/org.elasticsearch.plugins.PluginsServiceTests/classMethod?top-execution=1

**Comment by breskeby** [comment]
@craigtaverner I've merged the fix
