### ISSUE TITLE
[CI] ClientYamlTestSuiteIT test {yaml=cluster.desired_nodes/10_basic/Test using the same version with different definition is forbidden} failing

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#88804]
**Build scan:**
https://gradle-enterprise.elastic.co/s/haccxit3bswga/tests/:rest-api-spec:yamlRestTest/org.elasticsearch.test.rest.ClientYamlTestSuiteIT/test%20%7Byaml=cluster.desired_nodes%2F10_basic%2FTest%20using%20the%20same%20version%20with%20different%20definition%20is%20forbidden%7D

**Reproduction line:**
`./gradlew ':rest-api-spec:yamlRestTest' --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT" -Dtests.method="test {yaml=cluster.desired_nodes/10_basic/Test using the same version with different definition is forbidden}" -Dtests.seed=D2FDC3CB48E9BD82 -Dtests.locale=ar-AE -Dtests.timezone=Asia/Ust-Nera -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.test.rest.ClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dcluster.desired_nodes/10_basic/Test%20using%20the%20same%20version%20with%20different%20definition%20is%20forbidden%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [cluster.desired_nodes/10_basic:301]: expected [2xx] status code but api [_internal.update_desired_nodes] returned [400 Bad Request] [---
error:
  root_cause:
  - type: "illegal_argument_exception"
    reason: "Desired nodes with history [test] and version [1] already exists with\
      \ a different definition"
    stack_trace: "org.elasticsearch.ElasticsearchException$1: Desired nodes with history\
      \ [test] and version [1] already exists with a different definition\n\tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:638)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:566)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.build(RestResponse.java:143)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:102)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:81)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:55)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.client.internal.node.NodeClient$SafelyWrappedActionListener.onFailure(NodeClient.java:170)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:201)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$2(TransportMasterNodeAction.java:275)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.ActionListener$DelegatingActionListener.onFailure(ActionListener.java:218)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.desirednodes.TransportUpdateDesiredNodesAction$UpdateDesiredNodesTask.onFailure(TransportUpdateDesiredNodesAction.java:161)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$Batcher$UpdateTask.onFailure(MasterService.java:193)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:266)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:165)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:710)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)\n\
      \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\
      \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\
      \tat java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: java.lang.IllegalArgumentException:\
      \ Desired nodes with history [test] and version [1] already exists with a different\
      \ definition\n\tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.desirednodes.TransportUpdateDesiredNodesAction.updateDesiredNodes(TransportUpdateDesiredNodesAction.java:134)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.desirednodes.TransportUpdateDesiredNodesAction$UpdateDesiredNodesExecutor.execute(TransportUpdateDesiredNodesAction.java:196)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:959)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:929)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:261)\n\
      \t... 9 more\n"
  type: "illegal_argument_exception"
  reason: "Desired nodes with history [test] and version [1] already exists with a\
    \ different definition"
  stack_trace: "java.lang.IllegalArgumentException: Desired nodes with history [test]\
    \ and version [1] already exists with a different definition\n\tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.desirednodes.TransportUpdateDesiredNodesAction.updateDesiredNodes(TransportUpdateDesiredNodesAction.java:134)\n\
    \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.desirednodes.TransportUpdateDesiredNodesAction$UpdateDesiredNodesExecutor.execute(TransportUpdateDesiredNodesAction.java:196)\n\
    \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:959)\n\
    \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:929)\n\
    \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:261)\n\
    \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:165)\n\
    \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)\n\
    \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)\n\
    \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:710)\n\
    \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)\n\
    \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)\n\
    \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\
    \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\
    \tat java.base/java.lang.Thread.run(Thread.java:833)\n"
status: 400
]

  at __randomizedtesting.SeedInfo.seed([D2FDC3CB48E9BD82:5AA9FC11E615D07A]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:510)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:479)
  at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.AssertionError: expected [2xx] status code but api [_internal.update_desired_nodes] returned [400 Bad Request] [---
  error:
    root_cause:
    - type: "illegal_argument_exception"
      reason: "Desired nodes with history [test] and version [1] already exists with\
        \ a different definition"
      stack_trace: "org.elasticsearch.ElasticsearchException$1: Desired nodes with history\
        \ [test] and version [1] already exists with a different definition\n\tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:638)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:566)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.build(RestResponse.java:143)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:102)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:81)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:55)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.client.internal.node.NodeClient$SafelyWrappedActionListener.onFailure(NodeClient.java:170)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:201)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$2(TransportMasterNodeAction.java:275)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.ActionListener$DelegatingActionListener.onFailure(ActionListener.java:218)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.desirednodes.TransportUpdateDesiredNodesAction$UpdateDesiredNodesTask.onFailure(TransportUpdateDesiredNodesAction.java:161)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$Batcher$UpdateTask.onFailure(MasterService.java:193)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:266)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:165)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:710)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)\n\
        \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\
        \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\
        \tat java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: java.lang.IllegalArgumentException:\
        \ Desired nodes with history [test] and version [1] already exists with a different\
        \ definition\n\tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.desirednodes.TransportUpdateDesiredNodesAction.updateDesiredNodes(TransportUpdateDesiredNodesAction.java:134)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.desirednodes.TransportUpdateDesiredNodesAction$UpdateDesiredNodesExecutor.execute(TransportUpdateDesiredNodesAction.java:196)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:959)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:929)\n\
        \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:261)\n\
        \t... 9 more\n"
    type: "illegal_argument_exception"
    reason: "Desired nodes with history [test] and version [1] already exists with a\
      \ different definition"
    stack_trace: "java.lang.IllegalArgumentException: Desired nodes with history [test]\
      \ and version [1] already exists with a different definition\n\tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.desirednodes.TransportUpdateDesiredNodesAction.updateDesiredNodes(TransportUpdateDesiredNodesAction.java:134)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.desirednodes.TransportUpdateDesiredNodesAction$UpdateDesiredNodesExecutor.execute(TransportUpdateDesiredNodesAction.java:196)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:959)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:929)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:261)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:165)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:710)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)\n\
      \tat org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)\n\
      \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\
      \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\
      \tat java.base/java.lang.Thread.run(Thread.java:833)\n"
  status: 400
  ]

    at org.junit.Assert.fail(Assert.java:88)
    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:373)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:499)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:479)
    at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(null:-1)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by fcofdez** [comment]
@arteam would you mind taking a look? this seems to be related with the latest changes
