### ISSUE TITLE
[CI] CheckstylePrecommitPluginFuncTest can configure checkstyle tasks failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#88840]
**Build scan:**
https://gradle-enterprise.elastic.co/s/bk6aimwbbjs42/tests/:integTest/org.elasticsearch.gradle.internal.precommit.CheckstylePrecommitPluginFuncTest/can%20configure%20checkstyle%20tasks

**Reproduction line:**
`null`

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.internal.precommit.CheckstylePrecommitPluginFuncTest&tests.test=can%20configure%20checkstyle%20tasks

**Failure excerpt:**
```
java.lang.IllegalStateException: An error occurred executing build with args '-Dorg.gradle.vfs.watch=false precommit -Dtest.external=true' in directory 'C:\Users\jenkins\AppData\Local\Temp\junit3855567245455936041'

  at org.gradle.testkit.runner.internal.ToolingApiGradleExecutor.run(ToolingApiGradleExecutor.java:162)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:324)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:262)
  at org.elasticsearch.gradle.internal.test.InternalAwareGradleRunner.build(InternalAwareGradleRunner.java:145)
  at org.elasticsearch.gradle.internal.test.NormalizeOutputGradleRunner.build(NormalizeOutputGradleRunner.java:145)
  at org.elasticsearch.gradle.internal.precommit.CheckstylePrecommitPluginFuncTest.can configure checkstyle tasks(CheckstylePrecommitPluginFuncTest.groovy:41)

  Caused by: org.gradle.tooling.GradleConnectionException: Could not execute build using connection to Gradle installation 'C:\Users\jenkins\.gradle\wrapper\dists\gradle-7.5-all\6qsw290k5lz422uaf8jf6m7co\gradle-7.5'.

    at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
    at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
    at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
    at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:69)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
    at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
    at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:83)
    at org.gradle.testkit.runner.internal.ToolingApiGradleExecutor.run(ToolingApiGradleExecutor.java:138)
    at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:324)
    at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:262)
    at org.elasticsearch.gradle.internal.test.InternalAwareGradleRunner.build(InternalAwareGradleRunner.java:145)
    at org.elasticsearch.gradle.internal.test.NormalizeOutputGradleRunner.build(NormalizeOutputGradleRunner.java:145)
    at org.elasticsearch.gradle.internal.precommit.CheckstylePrecommitPluginFuncTest.can configure checkstyle tasks(CheckstylePrecommitPluginFuncTest.groovy:41)

    Caused by: org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:49567'.

      at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:140)
      at org.gradle.internal.remote.internal.inet.SocketConnection$1.close(SocketConnection.java:149)
      at org.gradle.internal.concurrent.CompositeStoppable$2.stop(CompositeStoppable.java:90)
      at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
      at org.gradle.internal.remote.internal.inet.SocketConnection.stop(SocketConnection.java:151)
      at org.gradle.launcher.daemon.client.DaemonClientConnection.stop(DaemonClientConnection.java:92)
      at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:159)
      at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:99)
      at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:44)
      at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:30)
      at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:60)
      at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:37)
      at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:222)
      at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:148)
      at org.gradle.tooling.internal.provider.DefaultConnection.getModel(DefaultConnection.java:202)
      at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:54)
      at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:38)
      at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:64)
      at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:49)
      at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:97)
      at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:89)
      at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:143)
      at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
      at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
      at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
      at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:67)
      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.lang.Thread.run(Thread.java:833)

      Caused by: java.io.IOException: Connection reset by peer

        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
        at sun.nio.ch.IOUtil.write(IOUtil.java:76)
        at sun.nio.ch.IOUtil.write(IOUtil.java:53)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:279)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:267)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:261)
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:138)
        at org.gradle.internal.remote.internal.inet.SocketConnection$1.close(SocketConnection.java:149)
        at org.gradle.internal.concurrent.CompositeStoppable$2.stop(CompositeStoppable.java:90)
        at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
        at org.gradle.internal.remote.internal.inet.SocketConnection.stop(SocketConnection.java:151)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.stop(DaemonClientConnection.java:92)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:159)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:99)
        at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:30)
        at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:222)
        at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:148)
        at org.gradle.tooling.internal.provider.DefaultConnection.getModel(DefaultConnection.java:202)
        at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:54)
        at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:38)
        at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:64)
        at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:49)
        at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:97)
        at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:89)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:143)
        at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
        at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:67)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)

```

**Comment by mark-vieira** [comment]
This looks to be just a transient error with the tooling api losing connection with a test daemon. Closing this as it's unlikely to reliably reproduce.
