### ISSUE TITLE
[CI] ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT testReloadSecureSettingsWithIncorrectPassword failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#88887]
**Build scan:**
https://gradle-enterprise.elastic.co/s/mkaycqqry57g4/tests/:x-pack:qa:password-protected-keystore:javaRestTest/org.elasticsearch.password_protected_keystore.ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT/testReloadSecureSettingsWithIncorrectPassword

**Reproduction line:**
`./gradlew ':x-pack:qa:password-protected-keystore:javaRestTest' --tests "org.elasticsearch.password_protected_keystore.ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.testReloadSecureSettingsWithIncorrectPassword" -Dtests.seed=79AF6F6ADD1FA62B -Dtests.locale=sq -Dtests.timezone=America/Guayaquil -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.password_protected_keystore.ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT&tests.test=testReloadSecureSettingsWithIncorrectPassword

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <2>
     but: was <1>

  at __randomizedtesting.SeedInfo.seed([79AF6F6ADD1FA62B:6B379B08CE5EB30]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.password_protected_keystore.ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.testReloadSecureSettingsWithIncorrectPassword(ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.java:56)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by ywangd** [comment]
This is a genuine bug. It is a racing condition as indicated by the following error stacktrace:
```
java.lang.IllegalStateException: SecureString has already been closed
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.settings.SecureString.ensureNotClosed(SecureString.java:136)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.settings.SecureString.getChars(SecureString.java:129)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.node.reload.NodesReloadSecureSettingsRequest.writeTo(NodesReloadSecureSettingsRequest.java:89)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.node.reload.TransportNodesReloadSecureSettingsAction$NodeRequest.writeTo(TransportNodesReloadSecureSettingsAction.java:168)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.transport.OutboundMessage.serialize(OutboundMessage.java:70)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:169)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.transport.OutboundHandler.sendRequest(OutboundHandler.java:110)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.transport.TcpTransport$NodeChannels.sendRequest(TcpTransport.java:309)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:889)
»  	at org.elasticsearch.security@8.5.0-SNAPSHOT/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor.sendWithUser(SecurityServerTransportInterceptor.java:156)
»  	at org.elasticsearch.security@8.5.0-SNAPSHOT/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$1.sendRequest(SecurityServerTransportInterceptor.java:134)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:778)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:724)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.start(TransportNodesAction.java:243)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:122)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.node.reload.TransportNodesReloadSecureSettingsAction.doExecute(TransportNodesReloadSecureSettingsAction.java:104)
```

I raised #88922.
