### ISSUE TITLE
[CI] TokenBackwardsCompatibilityIT testAccessTokensWorkInUpgradedCluster failing

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#88988]
**Build scan:**
https://gradle-enterprise.elastic.co/s/dzenscywk4x2e/tests/:x-pack:qa:rolling-upgrade:v7.17.6%23upgradedClusterTest/org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT/testAccessTokensWorkInUpgradedCluster

**Reproduction line:**
`./gradlew ':x-pack:qa:rolling-upgrade:v7.17.6#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT" -Dtests.method="testAccessTokensWorkInUpgradedCluster" -Dtests.seed=906EAC9C77F95F7C -Dtests.bwc=true -Dtests.locale=uk -Dtests.timezone=Antarctica/Casey -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT&tests.test=testAccessTokensWorkInUpgradedCluster

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:45709], URI [/_security/_authenticate], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"security_exception","reason":"token expired","header":{"WWW-Authenticate":"Bearer realm=\"security\", error=\"invalid_token\", error_description=\"The access token expired\""}}],"type":"security_exception","reason":"token expired","header":{"WWW-Authenticate":"Bearer realm=\"security\", error=\"invalid_token\", error_description=\"The access token expired\""}},"status":401}

  at __randomizedtesting.SeedInfo.seed([906EAC9C77F95F7C:33472577B7EE502C]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.assertAccessTokenWorks(TokenBackwardsCompatibilityIT.java:266)
  at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testAccessTokensWorkInUpgradedCluster(TokenBackwardsCompatibilityIT.java:218)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by n1v0lg** [comment]
This seems closely related:

https://github.com/elastic/elasticsearch/issues/77350

As mentioned in this [comment](https://github.com/elastic/elasticsearch/issues/77350#issuecomment-1090253158) when I try to reproduce locally I get a failure, but not the same as in CI. The CI failure is due to an expired token, whereas locally the issue a missing index:

... `no such index [token_backwards_compatibility_it]` ...

**Comment by slobodanadamovic** [comment]
@n1v0lg I've looked at this issue on Friday during my test triage and wasn't able to reproduce it either.

The only thing I see which could potentially explain why it sometimes fails is the fact that this token was used after timeout has been reached. The timeout is configured to 1 hour: https://github.com/elastic/elasticsearch/blob/241f1bc2be274093879b8fb66dec1ccb13614ac1/x-pack/qa/rolling-upgrade/build.gradle#L57

Token used in "upgraded" cluster is created during testing of "old" cluster. Test using token in upgraded cluster is called after ~1 hour and 3 minutes since old cluster test was executed. See `Started after`:

### Old cluster:

![image](https://user-images.githubusercontent.com/4357326/182354348-d72856d0-bd21-46c6-91b0-15551ddc7287.png)


### Upgraded cluster:
![image](https://user-images.githubusercontent.com/4357326/182354412-497de8f5-ea76-4da3-b4c6-25a86ee5006c.png)

I'm not sure how we can solve this easily since [the maximum timeout is 1 hour](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#token-service-settings).

**Comment by n1v0lg** [comment]
@slobodanadamovic nice, thanks for the context and investigation! 

I overlooked that this particular test failure was already mentioned in the linked issue. In the interest of keeping things in one place, I'll close this issue as duplicate of https://github.com/elastic/elasticsearch/issues/77350 and comment further there.

**Comment by idegtiarenko** [comment]
It looks like this is still happening: https://gradle-enterprise.elastic.co/s/zs7bwpfsh2tzw/tests/:x-pack:qa:rolling-upgrade:v8.3.4%23upgradedClusterTest/org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT/testAccessTokensWorkInUpgradedCluster?top-execution=1

**Comment by n1v0lg** [comment]
That build started at 10:01:44 AM CEST which is before I merged the PR, so the fix wasn't active yet. I'll keep an eye on the channel though in case post-fix failures come up.
