### ISSUE TITLE
[CI] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#89057]
### CI Link

https://gradle-enterprise.elastic.co/s/shxeer3uu36ie/failure?expanded-stacktrace=WyIwIl0

The above link is for a FIPS build. But the failure does not seem to related to FIPS because it also failed on non-fips build
https://gradle-enterprise.elastic.co/s/rueive3ch5kzo/failure#1

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

7.17

### Failure history

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Deprecated%20Gradle%20features%20were%20used%20in%20this%20build%2C%20making%20it%20incompatible%20with%20Gradle%208.0&search.timeZoneId=Australia/Melbourne

### Failure excerpt

```
org.gradle.api.GradleException: Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0	
at org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler.featureUsed(LoggingDeprecatedFeatureHandler.java:79)	
at org.gradle.internal.deprecation.DeprecationLogger.nagUserWith(DeprecationLogger.java:264)	
at org.gradle.internal.deprecation.DeprecationLogger.nagUserWith(DeprecationLogger.java:236)	
at org.gradle.internal.deprecation.DeprecationMessageBuilder$WithDocumentation.nagUser(DeprecationMessageBuilder.java:155)	
at org.gradle.api.internal.tasks.execution.TaskExecution.nagUserAboutUnreadableInputsOrOutputs(TaskExecution.java:381)	
at org.gradle.api.internal.tasks.execution.TaskExecution.handleUnreadableInputs(TaskExecution.java:351)	
at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$captureExecutionState$1(CaptureStateBeforeE
```

**Comment by breskeby** [comment]
This seems to surface a temporal issue with the ci machine disk reading. I'll keep an eye on this

**Comment by breskeby** [comment]
The error message is actually quite misleading I have to admin

**Comment by droberts195** [comment]
The same error message occurred today for an 8.4 build in https://gradle-enterprise.elastic.co/s/nexvghcidxnxc

It _wasn't_ on a FIPS build this time.

**Comment by ywangd** [comment]
Another one on 8.5 https://gradle-enterprise.elastic.co/s/gm5meipimjcvs
