### ISSUE TITLE
version_conflict_engine_exception，version conflict, required seqNo [69120140], primary term [1]. current document has seqNo [103022466]

### ISSUE THREAD

**Issue by wangshouqi111** [elastic/elasticsearch#89329]
### Elasticsearch Version

7.1.1

### Java Version

jdk1.8

### OS Version

linux

### Problem Description

Why report this error？
I didn't set if_seq_no  when  update，Why is  if_seq_no smaller than current seq_no

### Steps to Reproduce

client:
`public void index(List<PromoSkuInfoEsEntry> promoSkuInfoEsEntries) throws IOException {
        BulkRequest request = new BulkRequest();
        List<List<PromoSkuInfoEsEntry>> lists = Lists.partition(promoSkuInfoEsEntries, 5000);
        for (List<PromoSkuInfoEsEntry> list : lists) {
            for (PromoSkuInfoEsEntry promoSkuInfoEsEntry : list) {
                String jsonValue = objectMapper.writeValueAsString(promoSkuInfoEsEntry);
                String id = PromoGenerateIdUtil.getPromoSkuESId(promoSkuInfoEsEntry);
                UpdateRequest updateRequest = new UpdateRequest(xxx, id).routing(promoSkuInfoEsEntry.getSkuId());
                updateRequest.doc(jsonValue, XContentType.JSON);
                updateRequest.docAsUpsert(true);
                request.add(updateRequest);
            }
            BulkResponse bulk = newPromoRestHighLevelClient.bulk(request, RequestOptions.DEFAULT);
            checkBulkResponse(bulk);
        }
    }`
client version:
`<dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>7.1.1</version>
        </dependency>
`

### Logs (if relevant)

`com.xxx.promo.search.domain.exception.IndexRetryException: [xxx/FGQKKLajQsOjBa61XF4hfw][[xxx][5]] ElasticsearchException[Elasticsearch exception [type=version_conflict_engine_exception, reason=[1_1449437083_12352061_2020616363]: version conflict, required seqNo [69120140], primary term [1]. current document has seqNo [103022466] and primary term [1]]]
at com.xxx.promo.search.db.es.PromoSkuOperateEs.checkBulkResponse(PromoSkuOperateEs.java:149)
at com.xxx.promo.search.db.es.PromoSkuOperateEs.index(PromoSkuOperateEs.java:100)
at com.xxx.promo.search.task.handler.SinglePromoSkuIndexTaskHandler.prcessTask(SinglePromoSkuIndexTaskHandler.java:131)
at com.xxx.promo.search.task.handler.SinglePromoSkuIndexTaskHandler.handleAndThrowException(SinglePromoSkuIndexTaskHandler.java:85)
at com.xxx.promo.search.task.handler.SinglePromoSkuIndexTaskHandler.handle(SinglePromoSkuIndexTaskHandler.java:68)
at com.xxx.promo.search.task.schedule.SinglePromoSkuWriteEsTaskSchedule.lambda$null$1(SinglePromoSkuWriteEsTaskSchedule.java:99)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)`

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by wangshouqi111** [comment]
https://discuss.elastic.co/t/version-conflict-engine-exception-help-me/312065  help me

**Comment by wangshouqi111** [comment]
why required seqNo [69120140] small
