### ISSUE TITLE
[CI] CloseFollowerIndexIT testCloseAndReopenFollowerIndex failing

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#89379]
**Build scan:**
https://gradle-enterprise.elastic.co/s/d2wdbckj5muam/tests/:x-pack:plugin:ccr:internalClusterTestNoSecurityManager/org.elasticsearch.xpack.ccr.CloseFollowerIndexIT/testCloseAndReopenFollowerIndex

**Reproduction line:**
`./gradlew ':x-pack:plugin:ccr:internalClusterTestNoSecurityManager' --tests "org.elasticsearch.xpack.ccr.CloseFollowerIndexIT.testCloseAndReopenFollowerIndex" -Dtests.seed=DCD4FCC3B74E80D6 -Dtests.locale=fi-FI -Dtests.timezone=Asia/Kuwait -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ccr.CloseFollowerIndexIT&tests.test=testCloseAndReopenFollowerIndex

**Failure excerpt:**
```
java.lang.IllegalStateException: unable to launch a new watch service

  at __randomizedtesting.SeedInfo.seed([DCD4FCC3B74E80D6:968605C00D663417]:0)
  at org.elasticsearch.reservedstate.service.FileSettingsService.startWatcher(FileSettingsService.java:201)
  at org.elasticsearch.reservedstate.service.FileSettingsService.setWatching(FileSettingsService.java:142)
  at org.elasticsearch.reservedstate.service.FileSettingsService.startIfMaster(FileSettingsService.java:136)
  at org.elasticsearch.reservedstate.service.FileSettingsService.doStart(FileSettingsService.java:111)
  at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:43)
  at org.elasticsearch.node.Node.start(Node.java:1370)
  at org.elasticsearch.test.InternalTestCluster$NodeAndClient.startNode(InternalTestCluster.java:982)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:820)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.io.IOException: User limit of inotify watches reached

    at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)
    at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:266)
    at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:364)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by grcevski** [comment]
I'm going to close this one as a duplicate of https://github.com/elastic/elasticsearch/issues/89231.
