### ISSUE TITLE
[CI] MachineLearninIT failures

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#89421]
### CI Link

https://gradle-enterprise.elastic.co/s/n2dk7tyhwaefg

### Repro line

./gradlew ':client:rest-high-level:integTestRunner' -Dtests.seed=4CC56AD847E61970 -Dtests.class=org.elasticsearch.client.MachineLearningIT -Dtests.method="testGetDatafeedStats" -Dtests.security.manager=true -Dtests.locale=sk-SK -Dtests.timezone=Asia/Ust-Nera -Dcompiler.java=11 -Druntime.java=8

### Does it reproduce?

Didn't try

### Applicable branches

6.8

### Failure excerpt

```
Suite: org.elasticsearch.client.MachineLearningIT
  1> [2022-08-17T17:18:33,052][INFO ][o.e.c.MachineLearningIT  ] [testGetDatafeedStats] before test
  1> [2022-08-17T17:18:33,054][INFO ][o.e.c.MachineLearningIT  ] [testGetDatafeedStats] initializing REST clients against [http://[::1]:46561]
  1> [2022-08-17T17:18:33,152][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 1153]] request [PUT http://[::1]:46561/datafeed_stats_data_1?master_timeout=30s&include_type_name=false&timeout=30s] returned 1 warnings: [299 Elasticsearch-6.8.24-SNAPSHOT-f0683e1 "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template"]
  1> [2022-08-17T17:18:43,757][WARN ][o.e.c.MachineLearningIT  ] [testGetDatafeedStats] failed to close all jobs. Forcing closed
  1> org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=status_exception, reason=cannot close job [ml-get-datafeed-stats-test-id-1] because it failed, use force close]
  1> 	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-6.8.24-SNAPSHOT.jar:6.8.24-SNAPSHOT]
  1> 	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2061) ~[elasticsearch-rest-high-level-client-6.8.24-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2031) ~[elasticsearch-rest-high-level-client-6.8.24-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1778) ~[elasticsearch-rest-high-level-client-6.8.24-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1735) ~[elasticsearch-rest-high-level-client-6.8.24-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1697) ~[elasticsearch-rest-high-level-client-6.8.24-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.client.MachineLearningClient.closeJob(MachineLearningClient.java:373) ~[elasticsearch-rest-high-level-client-6.8.24-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.client.MlTestStateCleaner.closeAllJobs(MlTestStateCleaner.java:90) [test/:?]
  1> 	at org.elasticsearch.client.MlTestStateCleaner.deleteAllJobs(MlTestStateCleaner.java:79) [test/:?]
  1> 	at org.elasticsearch.client.MlTestStateCleaner.clearMlMetadata(MlTestStateCleaner.java:50) [test/:?]
  1> 	at org.elasticsearch.client.MachineLearningIT.cleanUp(MachineLearningIT.java:150) [test/:?]
```

Digging through the long series of failures and stacktraces, I found

```
[2022-08-17T07:18:43,747][WARN ][o.e.p.PersistentTasksNodeService] [node-0] task job-ml-get-datafeed-stats-test-id-1 failed with an exception
org.elasticsearch.ElasticsearchException: Failed to launch autodetect for job ml-get-datafeed-stats-test-id-1
	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:42) ~[?:?]
	at org.elasticsearch.xpack.ml.job.process.autodetect.NativeAutodetectProcessFactory.createNativeProcess(NativeAutodetectProcessFactory.java:122) ~[?:?]
	at org.elasticsearch.xpack.ml.job.process.autodetect.NativeAutodetectProcessFactory.createAutodetectProcess(NativeAutodetectProcessFactory.java:72) ~[?:?]
	at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager.create(AutodetectProcessManager.java:565) ~[?:?]
	at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager.createProcessAndSetRunning(AutodetectProcessManager.java:519) ~[?:?]
	at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager.access$600(AutodetectProcessManager.java:101) ~[?:?]
	at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager$3.doRun(AutodetectProcessManager.java:464) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:778) ~[elasticsearch-6.8.24-SNAPSHOT.jar:6.8.24-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.24-SNAPSHOT.jar:6.8.24-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: java.io.FileNotFoundException: Cannot open /tmp/elasticsearch-6479512883450609939/autodetect_ml-get-datafeed-stats-test-id-1_input_143018 (No such file or directory)
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeOutputStreamUnix(NamedPipeHelper.java:249) ~[?:?]
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeOutputStream(NamedPipeHelper.java:174) ~[?:?]
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeOutputStream(NamedPipeHelper.java:160) ~[?:?]
	at org.elasticsearch.xpack.ml.process.ProcessPipes.connectStreams(ProcessPipes.java:137) ~[?:?]
	at org.elasticsearch.xpack.ml.job.process.autodetect.NativeAutodetectProcessFactory.createNativeProcess(NativeAutodetectProcessFactory.java:118) ~[?:?]
	... 10 more
```

And searching GH for something similar, I found https://github.com/elastic/elasticsearch/issues/87462 but this doesn't seem to be a upgrade test...

**Comment by droberts195** [comment]
Closing as this has only been seen on 6.8 and that's no longer supported.
