### ISSUE TITLE
[CI] KerberosAuthenticationIT.testGetOauth2TokenInExchangeForKerberosTickets

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#89426]
### CI Link

https://gradle-enterprise.elastic.co/s/zc64gxmhdr6ky

### Repro line

gradlew ':x-pack:qa:kerberos-tests:javaRestTest' --tests "org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.testGetOauth2TokenInExchangeForKerberosTickets" -Dtests.seed=5CCEB5F4CA40BFFC -Dtests.locale=sq -Dtests.timezone=Europe/Athens -Druntime.java=8

### Does it reproduce?

No

### Applicable branches

7.17

### Failure excerpt

```
org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT > testGetOauth2TokenInExchangeForKerberosTickets FAILED
    java.security.PrivilegedActionException: java.security.PrivilegedActionException: GSSException: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7) - LOOKING_UP_SERVER))
        at __randomizedtesting.SeedInfo.seed([5CCEB5F4CA40BFFC:8DD2E6C406F32E1E]:0)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.doAsWrapper(SpnegoHttpClientConfigCallbackHandler.java:424)
        at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.getBase64EncodedTokenForSpnegoHeader(SpnegoHttpClientConfigCallbackHandler.java:373)
        at org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.testGetOauth2TokenInExchangeForKerberosTickets(KerberosAuthenticationIT.java:143)

        Caused by:
        java.security.PrivilegedActionException: GSSException: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7) - LOOKING_UP_SERVER))
            at java.security.AccessController.doPrivileged(Native Method)
            at javax.security.auth.Subject.doAs(Subject.java:422)
            at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.lambda$doAsWrapper$8(SpnegoHttpClientConfigCallbackHandler.java:424)
            ... 4 more

            Caused by:
            GSSException: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7) - LOOKING_UP_SERVER))
                at sun.security.jgss.spnego.SpNegoContext.initSecContext(SpNegoContext.java:454)
                at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:248)
                at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
                at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.lambda$getBase64EncodedTokenForSpnegoHeader$6(SpnegoHttpClientConfigCallbackHandler.java:375)
                ... 7 more

                Caused by:
                GSSException: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7) - LOOKING_UP_SERVER)
                    at sun.security.jgss.krb5.Krb5Context.initSecContext(Krb5Context.java:772)
                    at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:248)
                    at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
                    at sun.security.jgss.spnego.SpNegoContext.GSS_initSecContext(SpNegoContext.java:882)
                    at sun.security.jgss.spnego.SpNegoContext.initSecContext(SpNegoContext.java:317)
                    ... 10 more

                    Caused by:
                    KrbException: Server not found in Kerberos database (7) - LOOKING_UP_SERVER
                        at sun.security.krb5.KrbTgsRep.<init>(KrbTgsRep.java:73)
                        at sun.security.krb5.KrbTgsReq.getReply(KrbTgsReq.java:225)
                        at sun.security.krb5.KrbTgsReq.sendAndGetCreds(KrbTgsReq.java:236)
                        at sun.security.krb5.internal.CredentialsUtil.serviceCredsSingle(CredentialsUtil.java:482)
                        at sun.security.krb5.internal.CredentialsUtil.serviceCreds(CredentialsUtil.java:340)
                        at sun.security.krb5.internal.CredentialsUtil.serviceCreds(CredentialsUtil.java:314)
                        at sun.security.krb5.internal.CredentialsUtil.acquireServiceCreds(CredentialsUtil.java:169)
                        at sun.security.krb5.Credentials.acquireServiceCreds(Credentials.java:490)
                        at sun.security.jgss.krb5.Krb5Context.initSecContext(Krb5Context.java:695)
                        ... 14 more

                        Caused by:
                        KrbException: Identifier doesn't match expected value (906)
                            at sun.security.krb5.internal.KDCRep.init(KDCRep.java:140)
                            at sun.security.krb5.internal.TGSRep.init(TGSRep.java:65)
                            at sun.security.krb5.internal.TGSRep.<init>(TGSRep.java:60)
                            at sun.security.krb5.KrbTgsRep.<init>(KrbTgsRep.java:55)
                            ... 22 more
```

**Comment by slobodanadamovic** [comment]
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/89324
