### ISSUE TITLE
[CI] ClusterStateRestCancellationIT testClusterStateRestCancellation failing

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#89500]
**Build scan:**
https://gradle-enterprise.elastic.co/s/swrn2vccdizu6/tests/:qa:smoke-test-http:javaRestTest/org.elasticsearch.http.ClusterStateRestCancellationIT/testClusterStateRestCancellation

**Reproduction line:**
`./gradlew ':qa:smoke-test-http:javaRestTest' --tests "org.elasticsearch.http.ClusterStateRestCancellationIT.testClusterStateRestCancellation" -Dtests.seed=2034D67B43AAFEF0 -Dtests.locale=ca -Dtests.timezone=Europe/Madrid -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.http.ClusterStateRestCancellationIT&tests.test=testClusterStateRestCancellation

**Failure excerpt:**
```
java.lang.IllegalStateException: unable to launch a new watch service

  at __randomizedtesting.SeedInfo.seed([2034D67B43AAFEF0:A2A0FB19FD8E07BE]:0)
  at org.elasticsearch.reservedstate.service.FileSettingsService.startWatcher(FileSettingsService.java:271)
  at org.elasticsearch.reservedstate.service.FileSettingsService.startIfMaster(FileSettingsService.java:142)
  at org.elasticsearch.reservedstate.service.FileSettingsService.doStart(FileSettingsService.java:116)
  at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:43)
  at org.elasticsearch.node.Node.start(Node.java:1372)
  at org.elasticsearch.test.InternalTestCluster$NodeAndClient.startNode(InternalTestCluster.java:982)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:820)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.io.IOException: User limit of inotify watches reached

    at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)
    at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:266)
    at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:364)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by dimitris-athanasiou** [comment]
Not sure if this is a code issue or something with the CI worker setup.

**Comment by idegtiarenko** [comment]
This looks like another case of https://github.com/elastic/elasticsearch/issues/89231

**Comment by slobodanadamovic** [comment]
Happened again for `NetworkDisruptionIT` -> 
https://gradle-enterprise.elastic.co/s/s3tqzw2477a46/tests/:test:framework:integTest/org.elasticsearch.test.disruption.NetworkDisruptionIT/testClearDisruptionSchemeWhenNodeIsDown?expanded-stacktrace=WyIwLTEiXQ&top-execution=1

**Comment by thecoop** [comment]
Just merged a fix for another race condition in this class, #90302. If this happens again we can reopen & take another look.

**Comment by n1v0lg** [comment]
@thecoop It looks like the fix may not have worked. Seeing another failure on 8.5 (post backport) here:

https://gradle-enterprise.elastic.co/s/ufiseeo4zvusu

**Comment by thecoop** [comment]
What's the inotify limit set for these processes in tests? Could this actually be valid?

**Comment by grcevski** [comment]
I'm going to try to reproduce this on Ubuntu 20 since it failed there too. One thing that's interesting is that as part of the test suite we run older version of ES (BWC, rolling upgrade tests) - 8.4.x, where the bugs related to cleaning up the keys haven't been all fixed. So older builds which had issues with keys clean-up can potentially exhaust the inode watches.

**Comment by grcevski** [comment]
OK, so I think I see the culprit but it's not ES code, it's the gradle test executor and compiler accumulating inotify watches. I guess they simply keep on adding new things to watch for? Here's what I did to investigate:

1. I ran ./gradlew check on a Linux machine and while it's running I was monitoring what's happening with the watches.
2. I ran a simple command (`ls -l /proc/*/fd/* | grep inotify | wc -l`) to see how many ifd instances are taken while the tests are running and I see around 20 total, it goes up and down, depending on what tests run simultaneously. So this isn't an issue, since the default max ifd is 128.
3. So the next issue might be the total number of watches (going over the default 65535). For that I searched around and I found this handy script: https://raw.githubusercontent.com/fatso83/dotfiles/master/utils/scripts/inotify-consumers. I ran this tool few times while ./gradlew check is running and I see something like this:

```
   INOTIFY   INSTANCES
   WATCHES      PER   
    COUNT     PROCESS   PID USER         COMMAND
------------------------------------------------------------
   16152         1        3520 nino        /usr/lib/jvm/java-17-openjdk-amd64/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xss2m --add-exports jdk.compiler/com.sun.tools.javac.
    4773         1       12666 nino        /usr/lib/jvm/java-17-openjdk-amd64/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xss2m --add-exports jdk.compiler/com.sun.tools.javac.
     602         1        3005 nino        /usr/libexec/tracker-miner-fs-3
      38         4        2879 nino        /lib/systemd/systemd --user
       4         1        2917 nino        /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
       2         2        2888 nino        /usr/bin/pulseaudio --daemonize=no --log-target=journal
       1         1       57785 nino        /home/nino/.gradle/caches/transforms-3/86dd8c883bd800392a52851bda49d9c2/transformed/linux-18.0.2.1-x64.tar.gz/bin/java -Des.script
       1         1       57698 nino        /home/nino/.gradle/caches/transforms-3/86dd8c883bd800392a52851bda49d9c2/transformed/linux-18.0.2.1-x64.tar.gz/bin/java -Des.script
       1         1        3041 nino        /usr/libexec/gvfs-afc-volume-monitor
       1         1        3031 nino        /usr/libexec/goa-identity-service
       1         1        3024 nino        /usr/libexec/goa-daemon
       1         1        3015 nino        /usr/libexec/gvfs-udisks2-volume-monitor
       1         1        2887 nino        /usr/bin/pipewire-media-session
       1         1      151816 nino        /home/nino/.gradle/caches/transforms-3/86dd8c883bd800392a52851bda49d9c2/transformed/linux-18.0.2.1-x64.tar.gz/bin/java -Des.networ
       1         1      142882 nino        /home/nino/.gradle/caches/transforms-3/86dd8c883bd800392a52851bda49d9c2/transformed/linux-18.0.2.1-x64.tar.gz/bin/java -Des.networ

   21580  WATCHES TOTAL COUNT

INotify instances per user (e.g. limits specified by fs.inotify.max_user_instances): 

INSTANCES    USER
-----------  ------------------
19           nino

```

Looking closer at PID 3520 I see `worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 334'`, while PID 12666 is `org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.5.1`

I found this issue https://github.com/gradle/gradle/issues/3174, there's no indication that it's solved, so it simply means we have to cope with this for the time being... somehow.

To fix this on ES side, which I think we should do anyway, is to probably re-try couple of times to grab a watch key upon failing to do so. This might not fix the issue, but it's probably good practice, since watches will eventually free up on a system with many active watches and it makes our service more resilient.

Since we actively use inotify now in Elasticsearch, we should maybe look into increasing the limit for the tests, given our gradle build keeps on taking more and more. At the time I'm typing this, the tests at around 57% complete and compiler daemon has overtaken the test launcher in number of watches, putting my total to 37299 which is more than half way to 65535.

**Comment by mark-vieira** [comment]
I've disabled [Gradle file system watching](https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:daemon_watch_fs) in CI. It's primarily meant to accelerate incremental builds, so it doesn't really provide any benefit in CI. That hopefully provide some buffer. If we continue to hit these we can always bump the inotify limit on our workers.

**Comment by mark-vieira** [comment]
> OK, so I think I see the culprit but it's not ES code, it's the gradle test executor and compiler accumulating inotify watches. 

FWIW the Gradle test executor would be ES test code. The daemon process is responsible for the file watching I described in the previous coment.

**Comment by grcevski** [comment]
Thanks Mark!
