### ISSUE TITLE
[CI] FullClusterRestartIT testGeoIpSystemFeaturesMigration failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#89530]
**Build scan:**
https://gradle-enterprise.elastic.co/s/bchbcrnuy2yvc/tests/:modules:ingest-geoip:qa:full-cluster-restart:v7.17.6%23upgradedClusterTest/org.elasticsearch.ingest.geoip.FullClusterRestartIT/testGeoIpSystemFeaturesMigration

**Reproduction line:**
`./gradlew ':modules:ingest-geoip:qa:full-cluster-restart:v7.17.6#upgradedClusterTest' -Dtests.class="org.elasticsearch.ingest.geoip.FullClusterRestartIT" -Dtests.method="testGeoIpSystemFeaturesMigration" -Dtests.seed=F2BE87465C2AD850 -Dtests.bwc=true -Dtests.locale=tr -Dtests.timezone=Etc/GMT-10 -Druntime.java=17`

**Applicable branches:**
main, 8.4

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.ingest.geoip.FullClusterRestartIT&tests.test=testGeoIpSystemFeaturesMigration

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: iterable containing [".geoip_databases-reindexed-for-8", "my-index-00001"]
     but: item 0: was ".geoip_databases"

  at __randomizedtesting.SeedInfo.seed([F2BE87465C2AD850:63DF2F633B118995]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.ingest.geoip.FullClusterRestartIT.testCatIndices(FullClusterRestartIT.java:109)
  at org.elasticsearch.ingest.geoip.FullClusterRestartIT.lambda$testGeoIpSystemFeaturesMigration$3(FullClusterRestartIT.java:57)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1104)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1077)
  at org.elasticsearch.ingest.geoip.FullClusterRestartIT.testGeoIpSystemFeaturesMigration(FullClusterRestartIT.java:57)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by ChrisHegarty** [comment]
Another failure sighting: https://gradle-enterprise.elastic.co/s/jkqfj3jmr7ssa/tests/:modules:ingest-geoip:qa:full-cluster-restart:v7.17.7%23upgradedClusterTest/org.elasticsearch.ingest.geoip.FullClusterRestartIT/testGeoIpSystemFeaturesMigration

**Comment by davidkyle** [comment]
One more https://gradle-enterprise.elastic.co/s/c5wpbt2d64hmm

**Comment by masseyke** [comment]
This one might be related to #92888 (although since we don't have debug logging enabled for the test I can't say for sure).

**Comment by gmarouli** [comment]
Thanks @masseyke , I will check if I can enable logging and reproduce it locally.

**Comment by gmarouli** [comment]
I cannot reproduce it or find the failure history to see if it is still failing. I am going to close this and if it pops up again we can reopen it with newer data.
