### ISSUE TITLE
[CI] XPackRestIT test {p0=ml/upgrade_job_snapshot/Test existing but corrupt snapshot} failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#89564]
This looks to be reproducibly failing on our single processor node test job, and given the nature of the error message this very well be a legitimate deadlock scenario.

**Build scan:**
https://gradle-enterprise.elastic.co/s/g5rztp2kv5rq6/tests/:x-pack:plugin:yamlRestTest/org.elasticsearch.xpack.test.rest.XPackRestIT/test%20%7Bp0=ml%2Fupgrade_job_snapshot%2FTest%20existing%20but%20corrupt%20snapshot%7D

**Reproduction line:**
`./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/upgrade_job_snapshot/Test existing but corrupt snapshot}" -Dtests.seed=BCFE2A9A03956ACA -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH -Dtests.timezone=US/Indiana-Starke -Druntime.java=17 -Dtests.configure_test_clusters_with_one_processor=true`

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.test.rest.XPackRestIT&tests.test=test%20%7Bp0%3Dml/upgrade_job_snapshot/Test%20existing%20but%20corrupt%20snapshot%7D

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:37401], URI [/_features/_reset], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"timeout_exception","reason":"Timed out waiting for completion of [Task{id=4348, type='persistent', action='xpack/ml/job/snapshot/upgrade[c]', description='job-snapshot-upgrade-upgrade-model-snapshot-1234567890', parentTask=cluster:10, startTime=1661288471981, startTimeNanos=2146045551685}]"}],"type":"failed_node_exception","reason":"Failed node [r9fh43zvSCuFWI9e5ehabQ]","node_id":"r9fh43zvSCuFWI9e5ehabQ","caused_by":{"type":"timeout_exception","reason":"Timed out waiting for completion of [Task{id=4348, type='persistent', action='xpack/ml/job/snapshot/upgrade[c]', description='job-snapshot-upgrade-upgrade-model-snapshot-1234567890', parentTask=cluster:10, startTime=1661288471981, startTimeNanos=2146045551685}]"}},"status":500}

  at __randomizedtesting.SeedInfo.seed([BCFE2A9A03956ACA:34AA1540AD690732]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.resetFeatures(MlRestTestStateCleaner.java:35)
  at org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.clearMlState(AbstractXPackRestTest.java:131)
  at org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.cleanup(AbstractXPackRestTest.java:115)
  at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by mark-vieira** [comment]
@fcofdez Looks like we found our first instance of an error with this testing. Keep in mind this issue might exist in other branches, but we're only running these tests on `main` for now. Should we backport this elsewhere?

**Comment by fcofdez** [comment]
> @fcofdez Looks like we found our first instance of an error with this testing. Keep in mind this issue might exist in other branches, but we're only running these tests on main for now. Should we backport this elsewhere?

Thanks for the head up @mark-vieira. It won't be necessary to backport this elsewhere, as the intention is to start testing 1 processor configurations from 8.5 onwards.

**Comment by csoulios** [comment]
Failed again today: https://gradle-enterprise.elastic.co/s/i6wmuix7kepjm/

`./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/upgrade_job_snapshot/Test existing but corrupt snapshot}" -Dtests.seed=205CBFA10A615B6A -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=sl-SI -Dtests.timezone=CNT -Druntime.java=17`

**Comment by tlrx** [comment]
Failed again today: https://gradle-enterprise.elastic.co/s/yw7pchqk27loi

And earlier in https://gradle-enterprise.elastic.co/s/vatnmkc4wtk7i

Both on the single-processor-node test job.

**Comment by droberts195** [comment]
I think this is happening because the test framework waits for task completion which uses the `management` thread pool:

```
"elasticsearch[yamlRestTest-0][management][T#1]" #43 daemon prio=5 os_prio=31 cpu=53.50ms elapsed=25.32s tid=0x00007fbe9e3c1200 nid=84739 waiting on condition  [0x000070000597d000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@18.0.2.1/Native Method)
        at org.elasticsearch.tasks.TaskManager.waitForTaskCompletion(org.elasticsearch.server@8.5.0-SNAPSHOT/TaskManager.java:543)
        at org.elasticsearch.action.admin.cluster.node.tasks.list.TransportListTasksAction.lambda$processTasks$0(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportListTasksAction.java:78)
        at org.elasticsearch.action.admin.cluster.node.tasks.list.TransportListTasksAction$$Lambda$8023/0x0000000801d8b330.accept(org.elasticsearch.server@8.5.0-SNAPSHOT/Unknown Source)
        at java.util.function.Consumer.lambda$andThen$0(java.base@18.0.2.1/Consumer.java:65)
        at java.util.function.Consumer$$Lambda$6918/0x0000000801affa78.accept(java.base@18.0.2.1/Unknown Source)
        at org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportTasksAction.java:174)
        at org.elasticsearch.action.admin.cluster.node.tasks.list.TransportListTasksAction.processTasks(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportListTasksAction.java:81)
        at org.elasticsearch.action.admin.cluster.node.tasks.list.TransportListTasksAction.processTasks(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportListTasksAction.java:29)
        at org.elasticsearch.action.support.tasks.TransportTasksAction.nodeOperation(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportTasksAction.java:95)
        at org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportTasksAction.java:331)
        at org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportTasksAction.java:327)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(org.elasticsearch.security@8.5.0-SNAPSHOT/SecurityServerTransportInterceptor.java:254)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(org.elasticsearch.server@8.5.0-SNAPSHOT/AbstractRunnable.java:26)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(org.elasticsearch.security@8.5.0-SNAPSHOT/SecurityServerTransportInterceptor.java:316)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(org.elasticsearch.security@8.5.0-SNAPSHOT/SecurityServerTransportInterceptor.java:306)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$5(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:398)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$$Lambda$6315/0x0000000801bb8af8.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:962)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:926)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ContextPreservingActionListener.java:31)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$6(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:412)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$$Lambda$6326/0x0000000801bb9e18.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
        at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:162)
        at org.elasticsearch.xpack.security.authz.RBACEngine.authorizeClusterAction(org.elasticsearch.security@8.5.0-SNAPSHOT/RBACEngine.java:172)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:402)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:378)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$2(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:263)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$$Lambda$6282/0x0000000801bab700.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
        at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:162)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ContextPreservingActionListener.java:31)
        at org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$0(org.elasticsearch.security@8.5.0-SNAPSHOT/RBACEngine.java:140)
        at org.elasticsearch.xpack.security.authz.RBACEngine$$Lambda$6292/0x0000000801bb2cb0.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
        at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:162)
        at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRoles$1(org.elasticsearch.security@8.5.0-SNAPSHOT/CompositeRolesStore.java:185)
        at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore$$Lambda$6303/0x0000000801bb1860.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
        at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:162)
        at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRole(org.elasticsearch.security@8.5.0-SNAPSHOT/CompositeRolesStore.java:193)
        at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(org.elasticsearch.security@8.5.0-SNAPSHOT/CompositeRolesStore.java:175)
        at org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(org.elasticsearch.security@8.5.0-SNAPSHOT/RBACEngine.java:137)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:265)
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(org.elasticsearch.security@8.5.0-SNAPSHOT/ServerTransportFilter.java:112)
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$$Lambda$5971/0x0000000801b0e2a0.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
        at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:162)
        at org.elasticsearch.action.ActionListener$MappedActionListener.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:127)
        at org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticateAsync(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthenticatorChain.java:93)
        at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthenticationService.java:199)
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(org.elasticsearch.security@8.5.0-SNAPSHOT/ServerTransportFilter.java:104)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(org.elasticsearch.security@8.5.0-SNAPSHOT/SecurityServerTransportInterceptor.java:327)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(org.elasticsearch.server@8.5.0-SNAPSHOT/RequestHandlerRegistry.java:71)
        at org.elasticsearch.transport.TransportService$6.doRun(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportService.java:971)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(org.elasticsearch.server@8.5.0-SNAPSHOT/ThreadContext.java:892)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(org.elasticsearch.server@8.5.0-SNAPSHOT/AbstractRunnable.java:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@18.0.2.1/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@18.0.2.1/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@18.0.2.1/Thread.java:833)
```

So presumably there's an ML task that's being waited for that needs performs a sub-action that also runs in the `management` thread pool.

To me it seems dodgy that this code uses `sleep`: https://github.com/elastic/elasticsearch/blob/5f14c79320473605764840fd715ebbb31ec7491e/server/src/main/java/org/elasticsearch/tasks/TaskManager.java#L537-L549

@nik9000 `git blame` says you originally wrote that.  Is there any reason it couldn't be rewritten to schedule checks of the task state periodically instead of blocking a thread by sleeping?  Or do @dnhatn or @DaveCTurner have any insights on this since you've done work on the task manager by the look of it?

**Comment by DaveCTurner** [comment]
Yikes that's definitely a bug, although we did this sort of thing a lot back in 2016 when the code was first written. Ideally we wouldn't poll at all, tasks are only unregistered in one place so we should just be able to subscribe to an event triggered from there.

**Comment by pgomulka** [comment]
there is another failure. https://gradle-enterprise.elastic.co/s/dd75dcu3gmwmc/tests/:x-pack:plugin:yamlRestTest/org.elasticsearch.xpack.test.rest.XPackRestIT/test%20%7Bp0=ml%2Fupgrade_job_snapshot%2FTest%20existing%20but%20corrupt%20snapshot%7D?top-execution=1

this test is keep on failing ([13 times this week](https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Warsaw&tests.container=org.elasticsearch.xpack.test.rest.XPackRestIT&tests.test=test%20%7Bp0%3Dml/upgrade_job_snapshot/Test%20existing%20but%20corrupt%20snapshot%7D))  
Do you mind if I mute it?

**Comment by droberts195** [comment]
Sure, you can mute it if you like.  But it's only failing as part of the single processor tests, so shouldn't be affecting anyone's PR builds.

**Comment by droberts195** [comment]
Reopening - not fixed, just muted

**Comment by DaveCTurner** [comment]
_id._
