### ISSUE TITLE
ingest-attachment plug in error

### ISSUE THREAD

**Issue by AccountGc** [elastic/elasticsearch#89607]
### Elasticsearch Version

Version: 7.12.1, Build: default/tar/3186837139b9c6b6d23c3200870651f10d3343b7/2021-04-20T20:56:39.040728659Z, JVM: 1.8.0_291

### Installed Plugins

ik,ingest-attachment

### Java Version

java version "1.8.0_291"

### OS Version

Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 351 out of bounds for length 351
        at org.apache.poi.hwpf.sprm.SprmOperation.initSize(SprmOperation.java:177)
        at org.apache.poi.hwpf.sprm.SprmOperation.<init>(SprmOperation.java:75)
        at org.apache.poi.hwpf.sprm.SprmIterator.next(SprmIterator.java:47)
        at org.apache.poi.hwpf.sprm.ParagraphSprmUncompressor.uncompressPAP(ParagraphSprmUncompressor.java:62)
        at org.apache.poi.hwpf.usermodel.Paragraph.newParagraph(Paragraph.java:111)
        at org.apache.poi.hwpf.usermodel.Range.getParagraph(Range.java:777)
        at org.apache.tika.parser.microsoft.WordExtractor.handleHeaderFooter(WordExtractor.java:253)
        at org.apache.tika.parser.microsoft.WordExtractor.parse(WordExtractor.java:210)
        at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:218)
        at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:175)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)

### Steps to Reproduce

use ingest-attachment extract attachment content，plug in error

### Logs (if relevant)

none

**Comment by AccountGc** [comment]
use `sudo bin/elasticsearch-plugin install` install this plugin

**Comment by DJRickyB** [comment]
Hello, as mentioned in #89569 please visit https://discuss.elastic.co for your issue
