### ISSUE TITLE
7.17 mixed build can trip assertion error

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#89620]
### CI Link

https://gradle-enterprise.elastic.co/s/fwwoidncqrlek/console-log?anchor=-1

### Repro line

none

### Does it reproduce?

Didn't try

### Applicable branches

7.17

### Failure excerpt

```
» [2022-08-25T12:13:48,214][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.1.1-3] fatal error in thread [elasticsearch[v7.1.1-3][clusterApplierService#updateTask][T#1]], exiting
»  java.lang.AssertionError: {_doc=org.elasticsearch.index.mapper.DocumentMapper@12af1c3b}
»  	at org.elasticsearch.index.mapper.MapperService.assertMappingVersion(MapperService.java:264) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.index.mapper.MapperService.updateMapping(MapperService.java:218) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.index.IndexService.updateMapping(IndexService.java:551) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateIndices(IndicesClusterStateService.java:533) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:266) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:478) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:476) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:459) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:413) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:164) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.1.1.jar:7.1.1]
»  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
»  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
»  	at java.lang.Thread.run(Thread.java:835) [?:?]
```

Looks like it trips the assertion error in 7.1.1.

**Comment by dnhatn** [comment]
I am closing this issue as it hasn't failed again for several months.
