### ISSUE TITLE
[CI] SearchableSnapshotsIntegTests testCreateAndRestoreSearchableSnapshot failing

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#89687]
Test 4 times in the past 4 weeks (with different error messages though).

**Build scan:**
https://gradle-enterprise.elastic.co/s/knau5tfnrksy6/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests/testCreateAndRestoreSearchableSnapshot

**Reproduction line:**
`./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot" -Dtests.seed=2BC063F8B6C3C9E0 -Dtests.locale=hu -Dtests.timezone=Pacific/Funafuti -Druntime.java=17`

**Applicable branches:**
main, 7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests&tests.test=testCreateAndRestoreSearchableSnapshot

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=63, name=elasticsearch[node_s0][masterService#updateTask][T#1], state=RUNNABLE, group=TGRP-SearchableSnapshotsIntegTests]

  at __randomizedtesting.SeedInfo.seed([2BC063F8B6C3C9E0:A1A3148325549853]:0)

  Caused by: java.lang.AssertionError: Batched task executors must marshal response headers to the appropriate task context (e.g. using TaskContext#captureResponseHeaders) or suppress them (e.g. using BatchExecutionContext#dropHeadersContext) and must not leak them to the master service, but executor [org.elasticsearch.action.admin.indices.create.AutoCreateAction$TransportAction$$Lambda$2502/0x00000008013849f8@17e71a3f] leaked the following headers: {Warning=[299 Elasticsearch-8.5.0-SNAPSHOT-06226397fb95c1e72693008ebf929a7066e22c64 "[index.data_path] setting was deprecated in Elasticsearch and will be removed in a future release."]}

    at __randomizedtesting.SeedInfo.seed([2BC063F8B6C3C9E0]:0)
    at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1084)
    at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1017)
    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:278)
    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170)
    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)
    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:825)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by idegtiarenko** [comment]
It looks like there are 2 distinct failures there. The second one is:

```
java.lang.AssertionError: 	
Expected: not <true>	
     but: was <true>	
at __randomizedtesting.SeedInfo.seed([4042672BFA22464F:CA21105069B517FC]:0)	
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
at org.junit.Assert.assertThat(Assert.java:956)	
at org.junit.Assert.assertThat(Assert.java:923)	
at org.elasticsearch.xpack.searchablesnapshots.BaseSearchableSnapshotsIntegTestCase.assertShardFolders(BaseSearchableSnapshotsIntegTestCase.java:249)	
at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.lambda$testCreateAndRestoreSearchableSnapshot$2(SearchableSnapshotsIntegTests.java:259)	
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1141)	
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1114)
```

**Comment by idegtiarenko** [comment]
The other failure should be fixed by this change: https://github.com/elastic/elasticsearch/pull/89418
