### ISSUE TITLE
Update Settings API with _all target should not attempt to override settings on system indices

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#89692]
### Elasticsearch Version

8.3.2, 8.5-SNAPSHOT

### Java Version

_bundled_

### OS Version

Darwin chegar-MBP.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### Problem Description

When following the instructions to [delay allocation when a node leaves](https://www.elastic.co/guide/en/elasticsearch/reference/current/delayed-allocation.html#delayed-allocation), on a node that has been upgraded from 7.17.6 to 8.3.2 (or later), the settings update fails with:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "Cannot override settings on system indices: [.transform-internal-*] -> [index.unassigned.node_left.delayed_timeout]"
      }
    ],
    "type": "illegal_state_exception",
    "reason": "Cannot override settings on system indices: [.transform-internal-*] -> [index.unassigned.node_left.delayed_timeout]"
  },
  "status": 500
}
```

### Steps to Reproduce

1) Create a cluster 7.17.6.
2) Add the Kibana sample data.
3) Create a transform using the sample data.
4) Upgrade to 8.3.2 (or 8.5-SNAPSHOT)
5) Run the update index settings API with the superuser role and observe the error.

```
PUT /_all/_settings
{
  "settings": {
    "index.unassigned.node_left.delayed_timeout": "15m"
  }
}
```

### Logs (if relevant)

The logs show:
```
[2022-08-29T13:57:30,231][WARN ][o.e.a.a.i.s.p.TransportUpdateSettingsAction] [chegar-MBP.local] Cannot override settings on system indices: [.transform-internal-*] -> [index.unassigned.node_left.delayed_timeout]
[2022-08-29T13:57:30,247][WARN ][r.suppressed             ] [chegar-MBP.local] path: /_all/_settings, params: {index=_all}java.lang.IllegalStateException: Cannot override settings on system indices: [.transform-internal-*] -> [index.unassigned.node_left.delayed_timeout]
  at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.masterOperation(TransportUpdateSettingsAction.java:110)
  at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.masterOperation(TransportUpdateSettingsAction.java:44)
  at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.support.master.TransportMasterNodeAction.executeMasterOperation(TransportMasterNodeAction.java:128)
  at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:279)
  at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
```

**Comment by thecoop** [comment]
Are there any situations where `_all` *should* change settings on system indices?

**Comment by ChrisHegarty** [comment]
@gwbrown @williamrandolph 

> Are there any situations where `_all` _should_ change settings on system indices?

**Comment by thecoop** [comment]
I've been unable to reproduce this on 8.3.2 or latest 8.5.0, the settings command completes successfully with the data & transforms in place.

**Comment by grcevski** [comment]
@thecoop, perhaps the missing step is getting 7.17 going first, upgrading to 8.3 and then trying?

**Comment by thecoop** [comment]
I added some sample data from kibana to a running 7.17.6, added a random transform, then copied the data directory into a 8.5 snapshot directory, started it up, then ran the update index command

**Comment by gwbrown** [comment]
> Are there any situations where _all should change settings on system indices?

If you explicitly set `expand_wildcards=open,hidden` (or `all`). I don't expect this to be used a lot, but I could see it being useful for things like e.g. clearing write blocks.

**Comment by stefnestor** [comment]
This bug still surfaces 8.6.x. Is there any potential resolution ETA?


E.g. trying
```
PUT _all/_settings?expand_wildcards=open
{"settings": {"index.unassigned.node_left.delayed_timeout": "5m"} }
```
errors
```
{
  "error": {
    "reason": "Cannot override settings on system indices: [.transform-internal-*] -> [index.unassigned.node_left.delayed_timeout]",
    "root_cause": [
      {
        "reason": "Cannot override settings on system indices: [.transform-internal-*] -> [index.unassigned.node_left.delayed_timeout]",
        "type": "illegal_state_exception"
      }
    ],
    "type": "illegal_state_exception"
  },
  "status": 500
}
```
