### ISSUE TITLE
[CI] RandomSamplerIT testRandomSampler failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#89721]
This test was refactored this morning and has failed numerous times since

**Build scan:**
https://gradle-enterprise.elastic.co/s/amq7grg2caulq/tests/:server:internalClusterTest/org.elasticsearch.search.aggregations.bucket.RandomSamplerIT/testRandomSampler

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.aggregations.bucket.RandomSamplerIT.testRandomSampler" -Dtests.seed=784AB7689F1908AE -Dtests.locale=sr -Dtests.timezone=Antarctica/Vostok -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Yes - it's a seed-specific failure, so only reproduces with certain seeds

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.bucket.RandomSamplerIT&tests.test=testRandomSampler

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a value less than <59.45754788081997>
     but: <90.0> was greater than <59.45754788081997>

  at __randomizedtesting.SeedInfo.seed([784AB7689F1908AE:A033A2A38DF679FA]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.search.aggregations.bucket.RandomSamplerIT.testRandomSampler(RandomSamplerIT.java:115)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by dimitris-athanasiou** [comment]
cc @tveasey

**Comment by droberts195** [comment]
Here are some seeds that cause failures:

1. `784AB7689F1908AE` (the one in this issue description)
2. `CBE25367FBE36232`
3. `4015587C62744DB8`

**Comment by droberts195** [comment]
Since this seems like it's going to fail an annoyingly high proportion of the time I have opened #89722 to mute it.

**Comment by tveasey** [comment]
This might be because runs of sampler agg are not really independent in this test. I'll investigate tomorrow.

**Comment by tveasey** [comment]
> This might be because runs of sampler agg are not really independent in this test. I'll investigate tomorrow.

It is exactly this problem. `RandomSamplerAggregationBuilder` is used outside the loop over runs, but this fixes the seed so all 25 runs produce exactly the same result.

**Comment by davidkyle** [comment]
Reopening with another failure, this time on the 8.4 branch.

@tveasey the fix PR linked above (#89752) does not appear to have been back ported to 8.4 should it have been?


https://gradle-enterprise.elastic.co/s/wq4l5va6ufpmw

**Comment by benwtrent** [comment]
@davidkyle yeah, it should be backported. Its just a test update and we don't want failures to hurt development throughput.

**Comment by benwtrent** [comment]
@davidkyle @tveasey backport to 8.4: https://github.com/elastic/elasticsearch/pull/90606
