### ISSUE TITLE
[CI] ProfileDomainIntegTests testConcurrentActivateUpdates failing

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#89776]
**Build scan:**
https://gradle-enterprise.elastic.co/s/turc6aa5aqtig/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.profile.ProfileDomainIntegTests/testConcurrentActivateUpdates

**Reproduction line:**
`./gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.xpack.security.profile.ProfileDomainIntegTests.testConcurrentActivateUpdates" -Dtests.seed=2CB1A2766759F141 -Dtests.locale=pl -Dtests.timezone=Europe/Dublin -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.profile.ProfileDomainIntegTests&tests.test=testConcurrentActivateUpdates

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <Profile[uid=u_ZStoPhTrsYcQDKq6Oi45MDetmYMt2-fGNkdwO9LxDb4_0, enabled=true, lastSynchronized=1662038493111, user=ProfileUser[username=wiNPJHcQKR, roles=[foo], realmName=Jdts, domainName=null, email=null, fullName=null], labels={}, applicationData={}, versionControl=VersionControl[primaryTerm=1, seqNo=2]]>
     but: was <Profile[uid=u_ZStoPhTrsYcQDKq6Oi45MDetmYMt2-fGNkdwO9LxDb4_0, enabled=true, lastSynchronized=1662038493110, user=ProfileUser[username=wiNPJHcQKR, roles=[foo], realmName=Jdts, domainName=null, email=null, fullName=null], labels={}, applicationData={}, versionControl=VersionControl[primaryTerm=1, seqNo=3]]>

  at __randomizedtesting.SeedInfo.seed([2CB1A2766759F141:5D5C9D00FF0D3F43]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.security.profile.ProfileDomainIntegTests.testConcurrentActivateUpdates(ProfileDomainIntegTests.java:403)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by pgomulka** [comment]
another one https://gradle-enterprise.elastic.co/s/zij45oltqwuze/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.profile.ProfileDomainIntegTests/testConcurrentActivateUpdates?top-execution=1

**Comment by pxsalehi** [comment]
Failed again here https://gradle-enterprise.elastic.co/s/bh2levph7qbza/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.profile.ProfileDomainIntegTests/testConcurrentActivateUpdates?top-execution=1

**Comment by original-brownbear** [comment]
Reopening this, failed again for me in https://gradle-enterprise.elastic.co/s/sxrc3sybxx5si/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.profile.ProfileDomainIntegTests/testConcurrentActivateUpdates which included the fix from https://github.com/elastic/elasticsearch/pull/89793

**Comment by ywangd** [comment]
Errr hello again, dirty read. Thanks for reporting this. I'll deal with it.

**Comment by n1v0lg** [comment]
Just a heads up: [failing](https://gradle-enterprise.elastic.co/s/oriabca3e4o4o) on 8.5 as well so we should backport the fix once it's in place.

**Comment by gmarouli** [comment]
More failures on the 28th & 29th of September on main.

**Comment by ywangd** [comment]
Thanks all for reporting. I raised #90561

**Comment by davidkyle** [comment]
Another failure https://gradle-enterprise.elastic.co/s/gzutcqscjhqwk/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.profile.ProfileDomainIntegTests/testConcurrentActivateUpdates?top-execution=1

I won't mute as there is an open fix PR
