### ISSUE TITLE
[CI] org.elasticsearch.cluster.coordination.CoordinatorTests.testDoesNotElectNonMasterNode

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#89860]
### CI Link

https://gradle-enterprise.elastic.co/s/oxt3hlrxod3eg/tests/:server:test/org.elasticsearch.cluster.coordination.CoordinatorTests/testDoesNotElectNonMasterNode

### Repro line

`./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.CoordinatorTests.testDoesNotElectNonMasterNode" -Dtests.seed=B69C524FEA171AB8 -Dtests.locale=ko -Dtests.timezone=Europe/Guernsey -Druntime.java=17`

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.cluster.coordination.CoordinatorTests&tests.test=testDoesNotElectNonMasterNode#

### Failure excerpt

```
java.lang.AssertionError
        at org.elasticsearch.cluster.coordination.Coordinator.invariant(Coordinator.java:1096)
        at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.runFor(AbstractCoordinatorTestCase.java:765)
        at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:561)
        at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:544)
        at org.elasticsearch.cluster.coordination.CoordinatorTests.testDoesNotElectNonMasterNode(CoordinatorTests.java:161)
```

**Comment by DaveCTurner** [comment]
Suspect this is the same as https://github.com/elastic/elasticsearch/issues/89543 and appears that it could affect any of the `CoordinatorTests`. For instance:

```
./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.CoordinatorTests.testClusterUUIDLogging" -Dtests.seed=D96DF2234CA7E9DC:48A740BAECB0CD0C -Dtests.locale=el-CY -Dtests.timezone=Asia/Macao -Druntime.java=18
```
