### ISSUE TITLE
[CI-Failure] FullRollingRestartTests testFullRollingRestart

### ISSUE THREAD

**Issue by c-a-m** [elastic/elasticsearch#8996]
http://build-us-00.elasticsearch.org/job/es_core_13_window-2008/685/testReport/junit/org.elasticsearch.recovery/FullRollingRestartTests/testFullRollingRestart/

Error Message:  Count is 1748 but 2000 was expected.  Total shards: 8 Successful shards: 8 & 0 shard failures:

Stacktrace: 
java.lang.AssertionError: Count is 1748 but 2000 was expected.  Total shards: 8 Successful shards: 8 & 0 shard failures:
	at __randomizedtesting.SeedInfo.seed([C0A0FD2DD3226AE9:C1E7F37486768583]:0)
	at org.junit.Assert.fail(Assert.java:93)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:170)
	at org.elasticsearch.recovery.FullRollingRestartTests.testFullRollingRestart(FullRollingRestartTests.java:106)

**Comment by clintongormley** [comment]
Old test failure - closing
