### ISSUE TITLE
[CI] ClassificationHousePricingIT testFeatureImportanceValues failing

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#90019]
Failed as part of an intake build. First time this test has failed in 28 days. Attempted reproduction locally but it did not reproduce.

**Build scan:**
https://gradle-enterprise.elastic.co/s/bzko5uhtrlpoc/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT/testFeatureImportanceValues

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT.testFeatureImportanceValues" -Dtests.seed=4C2F17A6AD337FCA -Dtests.locale=ro-RO -Dtests.timezone=Europe/Oslo -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT&tests.test=testFeatureImportanceValues

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a collection with size a value greater than <0>
     but: collection size <0> was equal to <0>

  at __randomizedtesting.SeedInfo.seed([4C2F17A6AD337FCA:B1FE716ACAA4269F]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT.testFeatureImportanceValues(ClassificationHousePricingIT.java:1573)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by droberts195** [comment]
The test failed again yesterday in https://gradle-enterprise.elastic.co/s/r5lnrchv5sx36, so any extra debug information added after the last failure should now be available.

**Comment by droberts195** [comment]
Another failure in https://gradle-enterprise.elastic.co/s/lxvo2b6oykbr4

**Comment by kingherc** [comment]
Another one at https://gradle-enterprise.elastic.co/s/ywcwqr4s2m66u/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT/testFeatureImportanceValues?top-execution=1 .

I understand you enabled more logging, so I do not mute this now. But please consider muting until it's fixed.

**Comment by luigidellaquila** [comment]
New failure for this test 
https://gradle-enterprise.elastic.co/s/l6oekwgikjffk/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT/testFeatureImportanceValues?expanded-stacktrace=WyIwIl0&top-execution=1
but the error message seems different:

```
java.lang.AssertionError: 	
Expected: is <true>	
     but: was <false>	
at __randomizedtesting.SeedInfo.seed([92FA6D8BE974BF6C:6F2B0B478EE3E639]:0)	
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
at org.junit.Assert.assertThat(Assert.java:956)	
at org.junit.Assert.assertThat(Assert.java:923)	
at org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT.testFeatureImportanceValues(ClassificationHousePricingIT.java:1590)	

```

**Comment by cbuescher** [comment]
Another new one on 8.10: https://gradle-enterprise.elastic.co/s/hchcnuxiyrmgm

**Comment by cbuescher** [comment]
Another one today: https://gradle-enterprise.elastic.co/s/uwwlkdiu6izvg/tests/task/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/details/org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT/testFeatureImportanceValues?top-execution=1

**Comment by cbuescher** [comment]
Actually, scratch that, the above failure has some weird painless script errors in the logs, I'll open a new issue.
