### ISSUE TITLE
[CI] DownsampleActionSingleNodeTests » testCannotRollupWhileOtherRollupInProgress

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#90197]
### CI Link

https://gradle-enterprise.elastic.co/s/mg5vx5m3brp52/tests/:x-pack:plugin:rollup:test/org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests/testCannotRollupWhileOtherRollupInProgress?top-execution=1

### Repro line

`./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests.testCannotRollupWhileOtherRollupInProgress" -Dtests.seed=E143B4CB0FFC3300 -Dtests.locale=sr-ME -Dtests.timezone=Africa/Lagos -Druntime.java=17`

### Does it reproduce?

No

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests&tests.test=testCannotRollupWhileOtherRollupInProgress#

### Failure excerpt

```
java.lang.AssertionError: Rollup failed: index [rollup-fvmjtwravjpqjw/2cvJnGy2QgignPI2bsI2-Q] already exists	
	at __randomizedtesting.SeedInfo.seed([E143B4CB0FFC3300]:0)	
	at org.junit.Assert.fail(Assert.java:88)	
	at org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests$1.onFailure(DownsampleActionSingleNodeTests.java:523)	
	at org.elasticsearch.client.internal.node.NodeClient$SafelyWrappedActionListener.onFailure(NodeClient.java:170)	
	at org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:216)	
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$2(TransportMasterNodeAction.java:231)	
	at org.elasticsearch.action.ActionListener$DelegatingActionListener.onFailure(ActionListener.java:218)	
	at org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:170)	
	at org.elasticsearch.xpack.downsample.TransportRollupAction$RollupClusterStateUpdateTask.onFailure(TransportRollupAction.java:723)	
	at org.elasticsearch.cluster.service.MasterService$Batcher$UpdateTask.onFailure(MasterService.java:199)	
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:283)	
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170)	
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)	
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:825)	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)	
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)	
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)	
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by weizijun** [comment]
hi, @csoulios this PR fixed the failed test: https://github.com/elastic/elasticsearch/pull/90209

**Comment by pxsalehi** [comment]
I have muted it also on the 8.5 branch as well.
