### ISSUE TITLE
[CI] DiskHealthIndicatorServiceTests testNoBlockedIndicesAndRedAllRoleNodes failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#90305]
**Build scan:**
https://gradle-enterprise.elastic.co/s/ckfejrxsufgne/tests/:server:test/org.elasticsearch.health.node.DiskHealthIndicatorServiceTests/testNoBlockedIndicesAndRedAllRoleNodes

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.health.node.DiskHealthIndicatorServiceTests.testNoBlockedIndicesAndRedAllRoleNodes" -Dtests.seed=3CFAB87D5232A052 -Dtests.locale=tr -Dtests.timezone=Iran -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.health.node.DiskHealthIndicatorServiceTests&tests.test=testNoBlockedIndicesAndRedAllRoleNodes

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <3>
     but: was <2>

  at __randomizedtesting.SeedInfo.seed([3CFAB87D5232A052:1430093BFADB7355]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.health.node.DiskHealthIndicatorServiceTests.testNoBlockedIndicesAndRedAllRoleNodes(DiskHealthIndicatorServiceTests.java:150)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by masseyke** [comment]
I just ran into this one in a PR build. I thought I'd submit a PR for this one, but it's not as straightforward as I'd assumed so I'll leave it for @gmarouli and @andreidan. The problem is that we're putting indices on random nodes, and sometimes there are no indices on any of the RED nodes. Even though the node is RED and has a data role, we're not returning an ingest-related impact because there is no impacted index on the node. So I don't know if the correct thing is to change the test or to change the code -- Is the expected behavior that there is no ingest impact since there is no index on the node? Or is the expected behavior that there is an ingest impact since any second now a shard could get moved to this node?
(Side note -- it only reproduces some of the time with a given random seed. I  think at least some of the non-repeatable randomness is coming from UUID generation in the DiscoveryNodes)

**Comment by andreidan** [comment]
I think if a data node is passed a watermark (high or flood) ingest can be reported as affected (irrespective of indices blocks). I think this will simplify reasoning about the impacts and the code.

**Comment by dimitris-athanasiou** [comment]
Another failure today in [gradle link](https://gradle-enterprise.elastic.co/s/dldpouo6urv3o/tests/:server:test/org.elasticsearch.health.node.DiskHealthIndicatorServiceTests/testNoBlockedIndicesAndRedAllRoleNodes?top-execution=1)

I'll mute the test.

**Comment by hendrikmuhs** [comment]
Another repro line:
```
./gradlew ':server:test' --tests "org.elasticsearch.health.node.DiskHealthIndicatorServiceTests.testNoBlockedIndicesAndRedAllRoleNodes" -Dtests.seed=402F777205017E67 -Dtests.locale=sr-RS -Dtests.timezone=America/Cuiaba -Druntime.java=17
```

**Comment by gmarouli** [comment]
So the changes that need to happen:
- Change the messages in the symptom and diagnosis since there are no indices affected. I think the troubleshooting guide could stay the same and we can address this issue there.
- Reporting no impact is correct since there is no impact.

What do you think?

**Comment by dakrone** [comment]
A node that's out of disk space cannot write other information (such as `geoip` DB, file-based settings, writing cluster state), so even though it doesn't have data, it would still be impacted if it were entirely out of space.

**Comment by gmarouli** [comment]
Ah, very good points. It's clear now. I created: https://github.com/elastic/elasticsearch/issues/90442 let me know what you think.
