### ISSUE TITLE
[CI] DiskThresholdDeciderUnitTests testCannotAllocateDueToLackOfDiskResourcesWithMaxHeadroom failing

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#90374]
**Build scan:**
https://gradle-enterprise.elastic.co/s/3ujw5f3vlemai/tests/:server:test/org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderUnitTests/testCannotAllocateDueToLackOfDiskResourcesWithMaxHeadroom

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderUnitTests.testCannotAllocateDueToLackOfDiskResourcesWithMaxHeadroom" -Dtests.seed=C8BF48DCAE737843 -Dtests.locale=sr-BA -Dtests.timezone=America/Rainy_River -Druntime.java=17`

**Applicable branches:**
8.5

**Reproduces locally?:**
yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderUnitTests&tests.test=testCannotAllocateDueToLackOfDiskResourcesWithMaxHeadroom

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a string containing "allocating the shard to this node will bring the node above the high watermark cluster setting [cluster.routing.allocation.disk.watermark.high.max_headroom=150gb] and cause it to have less than the minimum required [150gb] of free space (free: [8.7tb], used: [10.3%], estimated shard size: [9.7tb])"
     but: was "allocating the shard to this node will bring the node above the high watermark cluster setting [cluster.routing.allocation.disk.watermark.high.max_headroom=150gb] and cause it to have less than the minimum required [150gb] of free space (free: [8.7tb], used: [10.2%], estimated shard size: [9.7tb])"

  at __randomizedtesting.SeedInfo.seed([C8BF48DCAE737843:BB42A250299E1C47]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderUnitTests.doTestCannotAllocateDueToLackOfDiskResources(DiskThresholdDeciderUnitTests.java:228)
  at org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderUnitTests.testCannotAllocateDueToLackOfDiskResourcesWithMaxHeadroom(DiskThresholdDeciderUnitTests.java:261)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by idegtiarenko** [comment]
We calculate the actual and expected % differently:

* expected: [100.0 * (totalBytes - freeBytes) / totalBytes](https://github.com/elastic/elasticsearch/blob/7dc8806dda46cb5eb5f140eda988b6e32cee446f/server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDeciderUnitTests.java#L226) that results in `10.3`
* actual [100.0 - (100.0 * getFreeBytes() / getTotalBytes())[https://github.com/elastic/elasticsearch/blob/862a86c0081553dd40af269c58a8f2195a6912c2/server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDecider.java#L609-L618] that results in `10.299999999999997`

The results are then formatted using `Strings.format1Decimals` that returns `10.2%` for the later value.

**Comment by kingherc** [comment]
@idegtiarenko , this relates to a recent PR I made. There is some java trouble with double operations sometimes. It usually can be fixed by moving around some parts in the double operation.
