### ISSUE TITLE
[CI] TokenAuthIntegTests testClientCredentialsGrant failing

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#90444]
This might be a Windows-specific issue. Possibly related to build and delivery but tagging as a security team issue since the test is owned by us.

**Build scan:**
https://gradle-enterprise.elastic.co/s/cjdsy35tk3hho/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.authc.TokenAuthIntegTests/testClientCredentialsGrant

**Reproduction line:**
`gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.testClientCredentialsGrant" -Dtests.seed=9A84EA1252225D9C -Dtests.locale=en-IN -Dtests.timezone=WET -Druntime.java=18`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.authc.TokenAuthIntegTests&tests.test=testClientCredentialsGrant

**Failure excerpt:**
```
java.io.UncheckedIOException: could not write file [C:\Users\jenkins\workspace\platform-support\381\x-pack\plugin\security\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.security.authc.TokenAuthIntegTests_9A84EA1252225D9C-001\tempDir-003\SUITE-0\config\operator_users.yml]

  at __randomizedtesting.SeedInfo.seed([9A84EA1252225D9C:CB0C625839D75037]:0)
  at org.elasticsearch.xpack.security.test.SecurityTestUtils.writeFile(SecurityTestUtils.java:58)
  at org.elasticsearch.xpack.security.test.SecurityTestUtils.writeFile(SecurityTestUtils.java:67)
  at org.elasticsearch.test.SecuritySettingsSource.nodeSettings(SecuritySettingsSource.java:152)
  at org.elasticsearch.test.SecurityIntegTestCase.nodeSettings(SecurityIntegTestCase.java:212)
  at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.nodeSettings(TokenAuthIntegTests.java:79)
  at org.elasticsearch.test.ESIntegTestCase$1.nodeSettings(ESIntegTestCase.java:2018)
  at org.elasticsearch.test.InternalTestCluster.getSettings(InternalTestCluster.java:468)
  at org.elasticsearch.test.InternalTestCluster.getNodeSettings(InternalTestCluster.java:707)
  at org.elasticsearch.test.InternalTestCluster.reset(InternalTestCluster.java:1159)
  at org.elasticsearch.test.InternalTestCluster.beforeTest(InternalTestCluster.java:1085)
  at org.elasticsearch.test.ESIntegTestCase.lambda$beforeInternal$0(ESIntegTestCase.java:362)
  at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
  at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
  at org.elasticsearch.test.ESIntegTestCase.beforeInternal(ESIntegTestCase.java:371)
  at org.elasticsearch.test.ESIntegTestCase.setupTestCluster(ESIntegTestCase.java:2221)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\381\x-pack\plugin\security\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.security.authc.TokenAuthIntegTests_9A84EA1252225D9C-001\tempDir-003\SUITE-0\config\operator_users.yml4546994645870407188tmp -> C:\Users\jenkins\workspace\platform-support\381\x-pack\plugin\security\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.security.authc.TokenAuthIntegTests_9A84EA1252225D9C-001\tempDir-003\SUITE-0\config\operator_users.yml

    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
    at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
    at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:144)
    at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:144)
    at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:144)
    at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:144)
    at java.nio.file.Files.move(Files.java:1432)
    at org.elasticsearch.xpack.security.test.SecurityTestUtils.writeFile(SecurityTestUtils.java:53)
    at org.elasticsearch.xpack.security.test.SecurityTestUtils.writeFile(SecurityTestUtils.java:67)
    at org.elasticsearch.test.SecuritySettingsSource.nodeSettings(SecuritySettingsSource.java:152)
    at org.elasticsearch.test.SecurityIntegTestCase.nodeSettings(SecurityIntegTestCase.java:212)
    at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.nodeSettings(TokenAuthIntegTests.java:79)
    at org.elasticsearch.test.ESIntegTestCase$1.nodeSettings(ESIntegTestCase.java:2018)
    at org.elasticsearch.test.InternalTestCluster.getSettings(InternalTestCluster.java:468)
    at org.elasticsearch.test.InternalTestCluster.getNodeSettings(InternalTestCluster.java:707)
    at org.elasticsearch.test.InternalTestCluster.reset(InternalTestCluster.java:1159)
    at org.elasticsearch.test.InternalTestCluster.beforeTest(InternalTestCluster.java:1085)
    at org.elasticsearch.test.ESIntegTestCase.lambda$beforeInternal$0(ESIntegTestCase.java:362)
    at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
    at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
    at org.elasticsearch.test.ESIntegTestCase.beforeInternal(ESIntegTestCase.java:371)
    at org.elasticsearch.test.ESIntegTestCase.setupTestCluster(ESIntegTestCase.java:2221)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:577)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by n1v0lg** [comment]
I haven't gotten far yet but this is a very rare failure. In the past year, we've had fix of this kind (that is containing "could not write file" exceptions) and all were windows.

**Comment by DiannaHohensee** [comment]
It looks like the changes from https://github.com/elastic/elasticsearch/pull/100919, adding debug logging, got [hit here](https://github.com/elastic/elasticsearch/blob/17bc83f481ddcfc032f6743a7a64c64000d55740/x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authc/TokenAuthIntegTests.java#L636) in a new failure. Perhaps there's new information in the failure, @albertzaharovits.

[Here's the build scan failure](https://gradle-enterprise.elastic.co/s/qpeeivz357wfo/tests/task/:x-pack:plugin:security:internalClusterTest/details/org.elasticsearch.xpack.security.authc.TokenAuthIntegTests/testRefreshingMultipleTimesWithinWindowSucceeds?top-execution=1)
```
Jan 31, 2024 8:56:52 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException	
WARNING: Uncaught exception in thread: Thread[#709,Thread-30,5,TGRP-TokenAuthIntegTests]	
java.lang.AssertionError: unexpected	
	at __randomizedtesting.SeedInfo.seed([67D39B1CEA034557]:0)	
	at org.elasticsearch.test.ESTestCase.fail(ESTestCase.java:2127)	
	at org.elasticsearch.test.ESTestCase.fail(ESTestCase.java:2131)	
	at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.lambda$testRefreshingMultipleTimesWithinWindowSucceeds$15(TokenAuthIntegTests.java:636)	
	at java.base/java.lang.Thread.run(Thread.java:1583)	
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:25367/], URI [/_security/_authenticate], status line [HTTP/1.1 401 Unauthorized]	
{"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"oauth2 token: invalid token","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"oauth2 token: invalid token","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}	
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)	
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)	
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)	
	at org.elasticsearch.test.TestSecurityClient.execute(TestSecurityClient.java:492)	
	at org.elasticsearch.test.TestSecurityClient.authenticate(TestSecurityClient.java:79)	
	at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.lambda$testRefreshingMultipleTimesWithinWindowSucceeds$15(TokenAuthIntegTests.java:634)	
	... 1 more	
Jan 31, 2024 8:56:52 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException	
WARNING: Uncaught exception in thread: Thread[#692,Thread-13,5,TGRP-TokenAuthIntegTests]	
java.lang.AssertionError: unexpected	
	at __randomizedtesting.SeedInfo.seed([67D39B1CEA034557]:0)	
	at org.elasticsearch.test.ESTestCase.fail(ESTestCase.java:2127)	
	at org.elasticsearch.test.ESTestCase.fail(ESTestCase.java:2131)	
	at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.lambda$testRefreshingMultipleTimesWithinWindowSucceeds$15(TokenAuthIntegTests.java:636)	
	at java.base/java.lang.Thread.run(Thread.java:1583)	
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:25368/], URI [/_security/_authenticate], status line [HTTP/1.1 401 Unauthorized]	
{"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"oauth2 token: invalid token","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"oauth2 token: invalid token","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}	
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)	
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)	
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)	
	at org.elasticsearch.test.TestSecurityClient.execute(TestSecurityClient.java:492)	
	at org.elasticsearch.test.TestSecurityClient.authenticate(TestSecurityClient.java:79)	
	at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.lambda$testRefreshingMultipleTimesWithinWindowSucceeds$15(TokenAuthIntegTests.java:634)	
	... 1 more	
Jan 31, 2024 8:56:52 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException	
WARNING: Uncaught exception in thread: Thread[#695,Thread-16,5,TGRP-TokenAuthIntegTests]	
java.lang.AssertionError: unexpected	
	at __randomizedtesting.SeedInfo.seed([67D39B1CEA034557]:0)	
	at org.elasticsearch.test.ESTestCase.fail(ESTestCase.java:2127)	
	at org.elasticsearch.test.ESTestCase.fail(ESTestCase.java:2131)	
	at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.lambda$testRefreshingMultipleTimesWithinWindowSucceeds$15(TokenAuthIntegTests.java:636)	
	at java.base/java.lang.Thread.run(Thread.java:1583)	
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:25366/], URI [/_security/_authenticate], status line [HTTP/1.1 401 Unauthorized]	
{"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"oauth2 token: invalid token","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"oauth2 token: invalid token","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}	
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)	
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)	
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)	
	at org.elasticsearch.test.TestSecurityClient.execute(TestSecurityClient.java:492)	
	at org.elasticsearch.test.TestSecurityClient.authenticate(TestSecurityClient.java:79)	
	at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.lambda$testRefreshingMultipleTimesWithinWindowSucceeds$15(TokenAuthIntegTests.java:634)	
	... 1 more
```
