### ISSUE TITLE
[CI] `:qa:os:destructiveDistroTest.default-dockerIronBank-aarch64` fails because no project is defined

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#90449]
### CI Link

https://gradle-enterprise.elastic.co/s/2v46mjlivwtls

### Repro line

None

### Does it reproduce?

No

### Applicable branches

7.17

### Failure excerpt

Looks very much related to this [commit](https://github.com/elastic/elasticsearch/commit/a6f5e18ad7940f89ffd2eb5cee850d432eceac98)

```
Caused by: org.gradle.api.GradleException: no project [:distribution:docker:ironbank-docker-aarch64-export], project names: [root project 'elasticsearch', project ':benchmarks', project ':client', project ':distribution', project ':docs', project ':libs', project ':modules', project ':plugins', project ':qa', project ':rest-api-spec', project ':server', project ':test', project ':x-pack', project ':client:benchmark', project ':client:client-benchmark-noop-api-plugin', project ':client:rest', project ':client:rest-high-level', project ':client:sniffer', project ':client:test', project ':client:transport', project ':distribution:archives', project ':distribution:bwc', project ':distribution:docker', project ':distribution:packages', project ':distribution:tools', project ':libs:elasticsearch-cli', project ':libs:elasticsearch-core', project ':libs:elasticsearch-dissect', project ':libs:elasticsearch-geo', project ':libs:elasticsearch-grok', project ':libs:elasticsearch-log4j', project ':libs:elasticsearch-lz4', project ':libs:elasticsearch-nio', project ':libs:elasticsearch-plugin-classloader', project ':libs:elasticsearch-secure-sm', project ':libs:elasticsearch-ssl-config', project ':libs:elasticsearch-x-content', project ':modules:aggs-matrix-stats', project ':modules:analysis-common', project ':modules:ingest-common', project ':modules:ingest-geoip', project ':modules:ingest-user-agent', project ':modules:kibana', project ':modules:lang-expression', project ':modules:lang-mustache', project ':modules:lang-painless', project ':modules:legacy-geo', project ':modules:mapper-extras', project ':modules:parent-join', project ':modules:percolator', project ':modules:rank-eval', project ':modules:reindex', project ':modules:repository-url', project ':modules:runtime-fields-common', project ':modules:systemd', project ':modules:transport-netty4', project ':plugins:analysis-icu', project ':plugins:analysis-kuromoji', project ':plugins:analysis-nori', project ':plugins:analysis-phonetic', project ':plugins:analysis-smartcn', project ':plugins:analysis-stempel', project ':plugins:analysis-ukrainian', project ':plugins:discovery-azure-classic', project ':plugins:discovery-ec2', project ':plugins:discovery-gce', project ':plugins:ingest-attachment', project ':plugins:mapper-annotated-text', project ':plugins:mapper-murmur3', project ':plugins:mapper-size', project ':plugins:repository-azure', project ':plugins:repository-gcs', project ':plugins:repository-hdfs', project ':plugins:repository-s3', project ':plugins:store-smb', project ':plugins:transport-nio', project ':qa:ccs-old-version-remote-cluster', project ':qa:ccs-rolling-upgrade-remote-cluster', project ':qa:ccs-unavailable-clusters', project ':qa:evil-tests', project ':qa:full-cluster-restart', project ':qa:logging-config', project ':qa:mixed-cluster', project ':qa:multi-cluster-search', project ':qa:no-bootstrap-tests', project ':qa:os', project ':qa:remote-clusters', project ':qa:repository-multi-version', project ':qa:rolling-upgrade', project ':qa:smoke-test-client', project ':qa:smoke-test-http', project ':qa:smoke-test-ingest-disabled', project ':qa:smoke-test-ingest-with-all-dependencies', project ':qa:smoke-test-multinode', project ':qa:smoke-test-plugins', project ':qa:snapshot-based-recoveries', project ':qa:system-indices', project ':qa:translog-policy', project ':qa:unconfigured-node-name', project ':qa:verify-version-constants', project ':qa:wildfly', project ':server:cli', project ':test:external-modules', project ':test:fixtures', project ':test:framework', project ':test:logger-usage', project ':x-pack:docs', project ':x-pack:license-tools', project ':x-pack:plugin', project ':x-pack:qa', project ':x-pack:rest-resources-zip', project ':x-pack:snapshot-tool', project ':x-pack:test', project ':x-pack:transport-client', project ':distribution:archives:darwin-aarch64-tar', project ':distribution:archives:darwin-tar', project ':distribution:archives:integ-test-zip', project ':distribution:archives:linux-aarch64-tar', project ':distribution:archives:linux-tar', project ':distribution:archives:no-jdk-darwin-aarch64-tar', project ':distribution:archives:no-jdk-darwin-tar', project ':distribution:archives:no-jdk-linux-tar', project ':distribution:archives:no-jdk-windows-zip', project ':distribution:archives:windows-zip', project ':distribution:bwc:bugfix', project ':distribution:bwc:maintenance', project ':distribution:bwc:minor', project ':distribution:bwc:staged', project ':distribution:docker:docker-aarch64-export', project ':distribution:docker:docker-export', project ':distribution:docker:ironbank-docker-export', project ':distribution:docker:ubi-docker-aarch64-export', project ':distribution:docker:ubi-docker-export', project ':distribution:packages:aarch64-deb', project ':distribution:packages:aarch64-rpm', project ':distribution:packages:deb', project ':distribution:packages:no-jdk-deb', project ':distribution:packages:no-jdk-rpm', project ':distribution:pa…	
	at org.elasticsearch.gradle.util.GradleUtils.projectDependency(GradleUtils.java:188)	
	at org.elasticsearch.gradle.internal.InternalDistributionDownloadPlugin.lambda$registerInternalDistributionResolutions$1(InternalDistributionDownloadPlugin.java:72)	
	at org.elasticsearch.gradle.internal.InternalDistributionDownloadPlugin$ProjectBasedDistributionDependency.getDefaultNotation(InternalDistributionDownloadPlugin.java:177)	
	at org.elasticsearch.gradle.DistributionDownloadPlugin.finalizeDistributionDependencies(DistributionDownloadPlugin.java:119)	
	at org.elasticsearch.gradle.DistributionDownloadPlugin.lambda$setupDistributionContainer$2(DistributionDownloadPlugin.java:90)	
	at org.elasticsearch.gradle.ElasticsearchDistribution.maybeFreeze(ElasticsearchDistribution.java:164)	
	at org.elasticsearch.gradle.ElasticsearchDistribution.getArchiveDependencies(ElasticsearchDistribution.java:260)	
	at org.elasticsearch.gradle.internal.test.DistroTestPlugin.lambda$apply$0(DistroTestPlugin.java:124)
```

**Comment by n1v0lg** [comment]
@mark-vieira it looks you removed the project that's missing here in a recent [commit](https://github.com/elastic/elasticsearch/commit/a6f5e18ad7940f89ffd2eb5cee850d432eceac98) to 7.17

I'm assuming there that some parts of the build setup are still relying on the presence of this project

**Comment by mark-vieira** [comment]
Resolved by https://github.com/elastic/elasticsearch/pull/90478
