### ISSUE TITLE
[CI] KeywordScriptFieldTypeTests testTermsQuery failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#90497]
**Build scan:**
https://gradle-enterprise.elastic.co/s/6uktyn6tgu53k/tests/:server:test/org.elasticsearch.index.mapper.KeywordScriptFieldTypeTests/testTermsQuery

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.index.mapper.KeywordScriptFieldTypeTests.testTermsQuery" -Dtests.seed=903C0AF3965A5EE4 -Dtests.locale=zh-CN -Dtests.timezone=Asia/Choibalsan -Druntime.java=17`

**Applicable branches:**
main, 8.5

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.mapper.KeywordScriptFieldTypeTests&tests.test=testTermsQuery

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <2>
     but: was <3>

  at __randomizedtesting.SeedInfo.seed([903C0AF3965A5EE4:51369FA13356E08B]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.index.mapper.KeywordScriptFieldTypeTests.testTermsQuery(KeywordScriptFieldTypeTests.java:327)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by cbuescher** [comment]
This reproduces, although I get a slightly different assertion error in terms of expected vs. actual number. This suprises me since the seed seems to be the same, curious why reproduction doesn't lead to the same error here:
```
org.elasticsearch.index.mapper.KeywordScriptFieldTypeTests > testTermsQuery FAILED
    java.lang.AssertionError:
    Expected: <2>
         but: was <1>
        at __randomizedtesting.SeedInfo.seed([903C0AF3965A5EE4:51369FA13356E08B]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.mapper.KeywordScriptFieldTypeTests.testTermsQuery(KeywordScriptFieldTypeTests.java:327)
```

**Comment by cbuescher** [comment]
While trying to bisect this and going back in history I ocassionally also get another type of error with this seed which might need a closer look. Just putting it here for reference:
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.mapper.KeywordScriptFieldTypeTests.testTermsQuery" -Dtests.seed=903C0AF3965A5EE4 -Dtests.locale=zh-CN -Dtests.timezone=Asia/Choibalsan -Druntime.java=17

org.elasticsearch.index.mapper.KeywordScriptFieldTypeTests > testTermsQuery FAILED
    java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.elasticsearch.ElasticsearchParseException: failed to parse / load source
        at __randomizedtesting.SeedInfo.seed([903C0AF3965A5EE4:51369FA13356E08B]:0)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:681)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:639)
        at org.apache.lucene.search.IndexSearcher.count(IndexSearcher.java:421)
        at org.elasticsearch.index.mapper.KeywordScriptFieldTypeTests.testTermsQuery(KeywordScriptFieldTypeTests.java:309)

        Caused by:
        java.util.concurrent.ExecutionException: org.elasticsearch.ElasticsearchParseException: failed to parse / load source
            at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
            at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
            at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:677)
            ... 3 more

            Caused by:
            org.elasticsearch.ElasticsearchParseException: failed to parse / load source
                at app//org.elasticsearch.search.lookup.SourceLookup.source(SourceLookup.java:87)
                at app//org.elasticsearch.search.lookup.SourceLookup.get(SourceLookup.java:217)
                at app//org.elasticsearch.index.mapper.KeywordScriptFieldTypeTests$3.execute(KeywordScriptFieldTypeTests.java:392)

                Caused by:
                java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
                    at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
                    at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
                    at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
                    at java.base/java.util.Objects.checkIndex(Objects.java:359)
                    at org.apache.lucene.index.CodecReader.checkBounds(CodecReader.java:103)
                    at org.apache.lucene.index.CodecReader.document(CodecReader.java:88)
                    at org.elasticsearch.search.lookup.SourceLookup.source(SourceLookup.java:76)
                    ... 2 more
```

**Comment by cbuescher** [comment]
Test starts failing with c2dc6e6ef4b8505f3437d36f0a1b1185b72bcf64 which introduced a new Lucene 9.3 snapshot. Need to start digging whats different since then, but the test history doesn't show many failures and this change was back in June so this must be a subtle edge case that we are lucky to catch with this seed.

**Comment by cbuescher** [comment]
In the error case the tests IndexSearcher is using threads (useThreads == true). This seems to be set ow in 50% of cases wheras the flag before the change to Lucene 9.3 was only set rarely. I will try to get closer to why the thread execution might lead to the above mentioned errors.

**Comment by romseygeek** [comment]
Running a script that loads from source is absolutely not thread-safe, as the SourceLookup is shared between LeafReaderContexts, so that will be the problem here.

**Comment by javanna** [comment]
Interesting, this sounds like a change I made! https://github.com/apache/lucene/pull/959 I did not consider it could impact Elasticsearch tests as ES doesn't support concurrent searches, but I can see how some of our tests may be affected. It should be a matter of disabling concurrency for those tests that don't support it?

**Comment by cbuescher** [comment]
> it could impact Elasticsearch tests as ES doesn't support concurrent searches, but I can see how some of our tests may be affected. It should be a matter of disabling concurrency for those tests that don't support it?

I was wondering the same, but then again the test here is really simple and I wonder why it doesn't work concurrently? Maybe the combination of randomized settings? I'm happy just disabling concurrency here but what if we decide to use it at some point and are missing potential bugs lurking?

**Comment by cbuescher** [comment]
There are three failures that I see here more or less with the same frequency. 
* the `ElasticsearchParseException: failed to parse / load source`
* count of 1 instead of the expected two documents
* count of 3 instead of the expeted two docs

Linking the test here for convenience since its simple enough that I think it should "just work":
https://github.com/elastic/elasticsearch/blob/a0652116780ab6304918ee1734317a31c8271915/server/src/test/java/org/elasticsearch/index/mapper/KeywordScriptFieldTypeTests.java#L319

**Comment by romseygeek** [comment]
It doesn't work concurrently because the script accesses Source, and SourceLookup isn't thread-safe.  So if you enable concurrency and the searcher tries to run the script at the same time from two different threads, then you get races and incorrect results.  If we ever enable concurrency in ES searches then we'll need to address that, but it's always worked this way.

**Comment by cbuescher** [comment]
So what I hear here so far is that we'd need to change the way `IndexSearcher searcher = newSearcher(reader);` works since that is randomizing using threads or not under the hood. If I only change that for this one test we'll probably run into similar cases in other tests that use scripts? To me that sounds like at least all tests extending `AbstractScriptFieldTypeTestCase` should use a special method that doesn't randomize using threads or not? Maybe even more places?

**Comment by romseygeek** [comment]
If you use `IndexSearcher searcher = newSearcher(reader, true, true, false)` then you will get equivalent behaviour with threads disabled.

From a quick look it seems that we call `newSearcher()` in a lot of the script field type tests, but most of the time we're dealing with an index that has only one or two docs in it so we're less likely to hit the race.  Overriding `newSearcher` on the abstract base class sounds like a good plan here.  I think we can keep it local to just the script field type tests as most other queries will not have this problem.

**Comment by cbuescher** [comment]
> From a quick look it seems that we call `newSearcher()` in a lot of the script field type tests, but most of the time we're dealing with an index that has only one or two docs in it so we're less likely to hit the race. Overriding `newSearcher` on the abstract base class sounds like a good plan here. I think we can keep it local to just the script field type tests as most other queries will not have this problem.

Less likely yes, but I think we should either test everything with or without the thread option, otherwise we run into this kind of problem again. Overriding `newSearcher` unfortunately is not possible because its static in `LuceneTestCase` so I guess introducing another helper in `AbstractScriptFieldTypeTestCase` and some search/replace operation is need. Will do that and be back with a PR soon.

**Comment by javanna** [comment]
Thanks for fixing @cbuescher !
