### ISSUE TITLE
 [CI] :x-pack:qa:rolling-upgrade tests failing

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#90516]
### CI Link

https://gradle-enterprise.elastic.co/s/kja5p5zfbbroq

### Repro line

 ./gradlew ':x-pack:qa:rolling-upgrade:v8.5.0#bwcTest'

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

The root cause is a EOF exception reading a stream input

```
Caused by: java.io.EOFException
	at org.elasticsearch.common.bytes.BytesReferenceStreamInput.moveToNextSlice(BytesReferenceStreamInput.java:195) ~[elasticsearch-8.6.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.bytes.BytesReferenceStreamInput.maybeNextSlice(BytesReferenceStreamInput.java:184) ~[elasticsearch-8.6.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.bytes.BytesReferenceStreamInput.readByte(BytesReferenceStreamInput.java:44) ~[elasticsearch-8.6.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.io.stream.StreamInput.readVIntSlow(StreamInput.java:211) ~[elasticsearch-8.6.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.io.stream.StreamInput.readVInt(StreamInput.java:207) ~[elasticsearch-8.6.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.bytes.BytesReferenceStreamInput.readVInt(BytesReferenceStreamInput.java:113) ~[elasticsearch-8.6.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.io.stream.FilterStreamInput.readVInt(FilterStreamInput.java:60) ~[elasticsearch-8.6.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.unit.ByteSizeUnit.readFrom(ByteSizeUnit.java:307) ~[elasticsearch-8.6.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:70) ~[elasticsearch-8.6.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:992) ~[elasticsearch-8.6.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.core.ml.inference.assignment.AssignmentStats.<init>(AssignmentStats.java:462) ~[?:?]
```

Probably caused by #90464

**Comment by davidkyle** [comment]
Raised #90514 to revert the change
