### ISSUE TITLE
[CI] DataTierAllocationDeciderIT testTemplateOverriddenIfEnforced failing

### ISSUE THREAD

**Issue by gmarouli** [elastic/elasticsearch#90546]
I tried to reproduce it with `-Dtests.iters=100` but it didn't fail locally.

**Build scan:**
https://gradle-enterprise.elastic.co/s/rexceoai6rlvu/tests/:x-pack:plugin:core:internalClusterTest/org.elasticsearch.xpack.cluster.routing.allocation.DataTierAllocationDeciderIT/testTemplateOverriddenIfEnforced

**Reproduction line:**
`./gradlew ':x-pack:plugin:core:internalClusterTest' --tests "org.elasticsearch.xpack.cluster.routing.allocation.DataTierAllocationDeciderIT.testTemplateOverriddenIfEnforced" -Dtests.seed=6FEF32E0BB95C224 -Dtests.locale=id -Dtests.timezone=Asia/Gaza -Druntime.java=8`

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.cluster.routing.allocation.DataTierAllocationDeciderIT&tests.test=testTemplateOverriddenIfEnforced

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=312, name=elasticsearch[node_t0][generic][T#4], state=RUNNABLE, group=TGRP-DataTierAllocationDeciderIT]

  at __randomizedtesting.SeedInfo.seed([6FEF32E0BB95C224:4C15B3C013F62E9C]:0)

  Caused by: java.lang.AssertionError: java.lang.IllegalStateException: environment is not locked

    at __randomizedtesting.SeedInfo.seed([6FEF32E0BB95C224]:0)
    at org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:53)
    at org.elasticsearch.index.store.Store.decRef(Store.java:407)
    at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:479)
    at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90)
    at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436)
    at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:88)
    at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:2361)
    at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)

    Caused by: java.lang.IllegalStateException: environment is not locked

      at org.elasticsearch.env.NodeEnvironment.assertEnvIsLocked(NodeEnvironment.java:1108)
      at org.elasticsearch.env.NodeEnvironment.availableShardPaths(NodeEnvironment.java:933)
      at org.elasticsearch.env.NodeEnvironment.deleteShardDirectoryUnderLock(NodeEnvironment.java:571)
      at org.elasticsearch.indices.IndicesService.deleteShardStore(IndicesService.java:1049)
      at org.elasticsearch.index.IndexService.onShardClose(IndexService.java:590)
      at org.elasticsearch.index.IndexService.access$100(IndexService.java:102)
      at org.elasticsearch.index.IndexService$StoreCloseListener.accept(IndexService.java:705)
      at org.elasticsearch.index.IndexService$StoreCloseListener.accept(IndexService.java:692)
      at org.elasticsearch.index.store.Store.closeInternal(Store.java:439)
      at org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:98)
      at org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:51)
      at org.elasticsearch.index.store.Store.decRef(Store.java:407)
      at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:479)
      at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90)
      at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436)
      at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:88)
      at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:2361)
      at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
      at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777)
      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:750)

      Caused by: java.nio.channels.AsynchronousCloseException: (No message provided)

        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
        at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:315)
        at org.apache.lucene.mockfile.FilterFileChannel.size(FilterFileChannel.java:85)
        at org.apache.lucene.mockfile.FilterFileChannel.size(FilterFileChannel.java:85)
        at org.apache.lucene.mockfile.FilterFileChannel.size(FilterFileChannel.java:85)
        at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:182)
        at org.elasticsearch.env.NodeEnvironment.assertEnvIsLocked(NodeEnvironment.java:1105)
        at org.elasticsearch.env.NodeEnvironment.availableShardPaths(NodeEnvironment.java:933)
        at org.elasticsearch.env.NodeEnvironment.deleteShardDirectoryUnderLock(NodeEnvironment.java:571)
        at org.elasticsearch.indices.IndicesService.deleteShardStore(IndicesService.java:1049)
        at org.elasticsearch.index.IndexService.onShardClose(IndexService.java:590)
        at org.elasticsearch.index.IndexService.access$100(IndexService.java:102)
        at org.elasticsearch.index.IndexService$StoreCloseListener.accept(IndexService.java:705)
        at org.elasticsearch.index.IndexService$StoreCloseListener.accept(IndexService.java:692)
        at org.elasticsearch.index.store.Store.closeInternal(Store.java:439)
        at org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:98)
        at org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:51)
        at org.elasticsearch.index.store.Store.decRef(Store.java:407)
        at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:479)
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90)
        at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436)
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:88)
        at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:2361)
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

```

**Comment by idegtiarenko** [comment]
This has not reproduced locally nor happened on CI during last 90 days. I am going to close it, however feel free to reopen if you see this reproduces
