### ISSUE TITLE
[CI] SecurityPluginTests testThatPluginIsLoaded failing

### ISSUE THREAD

**Issue by gmarouli** [elastic/elasticsearch#90564]
**Build scan:**
https://gradle-enterprise.elastic.co/s/zniqikjuh5qcc/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.SecurityPluginTests/testThatPluginIsLoaded

**Reproduction line:**
`gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.xpack.security.SecurityPluginTests.testThatPluginIsLoaded" -Dtests.seed=AE1E6F6D3D7BA176 -Dtests.locale=und -Dtests.timezone=NST -Druntime.java=18`

**Applicable branches:**
8.4

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.SecurityPluginTests&tests.test=testThatPluginIsLoaded

**Failure excerpt:**
```
java.io.UncheckedIOException: could not write file [C:\Users\jenkins\workspace\platform-support\129\x-pack\plugin\security\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.security.SecurityPluginTests_AE1E6F6D3D7BA176-001\tempDir-003\SUITE-0\config\users]

  at __randomizedtesting.SeedInfo.seed([AE1E6F6D3D7BA176:4772FAD0849F1FFE]:0)
  at org.elasticsearch.xpack.security.test.SecurityTestUtils.writeFile(SecurityTestUtils.java:57)
  at org.elasticsearch.xpack.security.test.SecurityTestUtils.writeFile(SecurityTestUtils.java:66)
  at org.elasticsearch.test.SecuritySettingsSource.nodeSettings(SecuritySettingsSource.java:150)
  at org.elasticsearch.test.SecurityIntegTestCase.nodeSettings(SecurityIntegTestCase.java:212)
  at org.elasticsearch.xpack.security.SecurityPluginTests.nodeSettings(SecurityPluginTests.java:74)
  at org.elasticsearch.test.ESIntegTestCase$1.nodeSettings(ESIntegTestCase.java:2016)
  at org.elasticsearch.test.InternalTestCluster.getSettings(InternalTestCluster.java:468)
  at org.elasticsearch.test.InternalTestCluster.getNodeSettings(InternalTestCluster.java:707)
  at org.elasticsearch.test.InternalTestCluster.reset(InternalTestCluster.java:1148)
  at org.elasticsearch.test.InternalTestCluster.beforeTest(InternalTestCluster.java:1085)
  at org.elasticsearch.test.ESIntegTestCase.lambda$beforeInternal$0(ESIntegTestCase.java:362)
  at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
  at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
  at org.elasticsearch.test.ESIntegTestCase.beforeInternal(ESIntegTestCase.java:371)
  at org.elasticsearch.test.ESIntegTestCase.setupTestCluster(ESIntegTestCase.java:2219)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\129\x-pack\plugin\security\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.security.SecurityPluginTests_AE1E6F6D3D7BA176-001\tempDir-003\SUITE-0\config\users5166538917252910012tmp -> C:\Users\jenkins\workspace\platform-support\129\x-pack\plugin\security\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.security.SecurityPluginTests_AE1E6F6D3D7BA176-001\tempDir-003\SUITE-0\config\users

    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
    at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
    at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:144)
    at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:144)
    at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:144)
    at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:144)
    at java.nio.file.Files.move(Files.java:1432)
    at org.elasticsearch.xpack.security.test.SecurityTestUtils.writeFile(SecurityTestUtils.java:52)
    at org.elasticsearch.xpack.security.test.SecurityTestUtils.writeFile(SecurityTestUtils.java:66)
    at org.elasticsearch.test.SecuritySettingsSource.nodeSettings(SecuritySettingsSource.java:150)
    at org.elasticsearch.test.SecurityIntegTestCase.nodeSettings(SecurityIntegTestCase.java:212)
    at org.elasticsearch.xpack.security.SecurityPluginTests.nodeSettings(SecurityPluginTests.java:74)
    at org.elasticsearch.test.ESIntegTestCase$1.nodeSettings(ESIntegTestCase.java:2016)
    at org.elasticsearch.test.InternalTestCluster.getSettings(InternalTestCluster.java:468)
    at org.elasticsearch.test.InternalTestCluster.getNodeSettings(InternalTestCluster.java:707)
    at org.elasticsearch.test.InternalTestCluster.reset(InternalTestCluster.java:1148)
    at org.elasticsearch.test.InternalTestCluster.beforeTest(InternalTestCluster.java:1085)
    at org.elasticsearch.test.ESIntegTestCase.lambda$beforeInternal$0(ESIntegTestCase.java:362)
    at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
    at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
    at org.elasticsearch.test.ESIntegTestCase.beforeInternal(ESIntegTestCase.java:371)
    at org.elasticsearch.test.ESIntegTestCase.setupTestCluster(ESIntegTestCase.java:2219)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:577)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by gwbrown** [comment]
The stack trace here is identical to that in https://github.com/elastic/elasticsearch/issues/90564; I'm going to close this issue in favor of that one.
