### ISSUE TITLE
[CI] Various rollup tests failing with resource leak error

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#90661]
Several tests in this suite started failing in the last 15h with the same error message.

**Build scan:**
https://gradle-enterprise.elastic.co/s/l7ngbkdsqrnce/tests/:x-pack:plugin:rollup:test/org.elasticsearch.xpack.rollup.RollupResponseTranslationTests/testDateHistoWithGap

**Reproduction line:**
`./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.rollup.RollupResponseTranslationTests.testDateHistoWithGap" -Dtests.seed=947CD74CBDFDC7F9 -Dtests.jvm.argline="--enable-preview" -Dtests.locale=id -Dtests.timezone=America/Fort_Wayne -Druntime.java=19`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.rollup.RollupResponseTranslationTests&tests.test=testDateHistoWithGap

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
Created at:
	org.elasticsearch.common.util.MockPageCacheRecycler.wrap(MockPageCacheRecycler.java:32)
	org.elasticsearch.common.util.MockPageCacheRecycler.bytePage(MockPageCacheRecycler.java:72)
	org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:525)
	org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:537)
	org.elasticsearch.search.aggregations.metrics.HyperLogLogPlusPlus$HyperLogLog.<init>(HyperLogLogPlusPlus.java:211)
	org.elasticsearch.search.aggregations.metrics.HyperLogLogPlusPlus.<init>(HyperLogLogPlusPlus.java:75)
	org.elasticsearch.search.aggregations.metrics.CardinalityAggregator.<init>(CardinalityAggregator.java:75)
	org.elasticsearch.search.aggregations.metrics.CardinalityAggregatorFactory.lambda$registerAggregators$0(CardinalityAggregatorFactory.java:174)
	org.elasticsearch.search.aggregations.metrics.CardinalityAggregatorFactory.doCreateInternal(CardinalityAggregatorFactory.java:203)
	org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:41)
	org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:81)
	org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:256)
	org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:241)
	org.elasticsearch.xpack.rollup.RollupResponseTranslationTests.doQuery(RollupResponseTranslationTests.java:1316)
	org.elasticsearch.xpack.rollup.RollupResponseTranslationTests.doQueries(RollupResponseTranslationTests.java:1295)
	org.elasticsearch.xpack.rollup.RollupResponseTranslationTests.testUnsupportedMetric(RollupResponseTranslationTests.java:1022)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	java.base/java.lang.reflect.Method.invoke(Method.java:578)
	com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
	org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
	com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
	com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
	com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
	com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
	com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
	java.base/java.lang.Thread.run(Thread.java:1589), LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
Created at:
	org.elasticsearch.common.util.MockPageCacheRecycler.wrap(MockPageCacheRecycler.java:32)
	org.elasticsearch.common.util.MockPageCacheRecycler.bytePage(MockPageCacheRecycler.java:72)
	org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:525)
	org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:537)
	org.elasticsearch.search.aggregations.metrics.HyperLogLogPlusPlus$HyperLogLog.<init>(HyperLogLogPlusPlus.java:211)
	org.elasticsearch.search.aggregations.metrics.HyperLogLogPlusPlus.<init>(HyperLogLogPlusPlus.java:75)
	org.elasticsearch.search.aggregations.metrics.CardinalityAggregator.<init>(CardinalityAggregator.java:75)
	org.elasticsearch.search.aggregations.metrics.CardinalityAggregatorFactory.lambda$registerAggregators$0(CardinalityAggregatorFactory.java:174)
	org.elasticsearch.search.aggregations.metrics.CardinalityAggregatorFactory.doCreateInternal(CardinalityAggregatorFactory.java:203)
	org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:41)
	org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:81)
	org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:256)
	org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:241)
	org.elasticsearch.xpack.rollup.RollupResponseTranslationTests.doQuery(RollupResponseTranslationTests.java:1316)
	org.elasticsearch.xpack.rollup.RollupResponseTranslationTests.doQueries(RollupResponseTranslationTests.java:1296)
	org.elasticsearch.xpack.rollup.RollupResponseTranslationTests.testUnsupportedMetric(RollupResponseTranslationTests.java:1022)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	java.base/java.lang.reflect.Method.invoke(Method.java:578)
	com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
	org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
	com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
	com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
	com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
	com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
	com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
	java.base/java.lang.Thread.run(Thread.java:1589)]>

  at __randomizedtesting.SeedInfo.seed([947CD74CBDFDC7F9:F67CE4F88611045C]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:674)
  at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:465)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by cbuescher** [comment]
Similar looking failures in same test class on main branch:
https://gradle-enterprise.elastic.co/s/htv2h2twreimk
https://gradle-enterprise.elastic.co/s/lvsqwbam27tle

Then these are other tests where the error also looks related:

RollupIndexTests.testValidateMatchingField
https://gradle-enterprise.elastic.co/s/zlzgamvguxlk4

SearchActionTests.testSuggest
https://gradle-enterprise.elastic.co/s/y2mbmz62pm2i2

SearchActionTests.testRollupOnly
https://gradle-enterprise.elastic.co/s/odiv6h6lpm7la

RollupIndexTests.testValidateFieldMatchingNotAggregatable
https://gradle-enterprise.elastic.co/s/kvdamhyvz3mso

They all seem to involve the CardinalityAggregator and memory leak errors so I'm adding them here. 
Could not reproduce any of these locally but then again cleaning up the resource seems thread related.
I found this issue in the history that seems to touch on this problem:

https://github.com/elastic/elasticsearch/pull/90540

Maybe @not-napoleon or @nik9000 can verify this is related?

**Comment by joegallo** [comment]
RollupResponseTranslationTests.testStringTermsNullValue
https://gradle-enterprise.elastic.co/s/lvsqwbam27tle/tests/:x-pack:plugin:rollup:test/org.elasticsearch.xpack.rollup.RollupResponseTranslationTests/testStringTermsNullValue?top-execution=1

**Comment by craigtaverner** [comment]
Several new failures today:

* https://gradle-enterprise.elastic.co/s/gk33koqelwgcu/tests/:x-pack:plugin:rollup:test/org.elasticsearch.xpack.rollup.action.job.RollupIndexTests/testValidateMatchingField?top-execution=1
* https://gradle-enterprise.elastic.co/s/gidfdlc2cgfdg/tests/:x-pack:plugin:rollup:test/org.elasticsearch.xpack.rollup.action.job.RollupIndexTests/testValidateMatchingField?top-execution=1
* https://gradle-enterprise.elastic.co/s/6ha4lx65x6wvc/tests/:x-pack:plugin:rollup:test/org.elasticsearch.xpack.rollup.action.SearchActionTests/testSuggest?top-execution=1

I will mute at least two tests here:
* `RollupIndexTests.testValidateMatchingField`
* `SearchActionTests.testSuggest`

**Comment by craigtaverner** [comment]
I muted four more tests, this time in RollupResponseTranslationTests, in https://github.com/elastic/elasticsearch/pull/90829
I did this because this issue was originally reported for those tests.

**Comment by pgomulka** [comment]
an observation - when testing on windows this failures are happening almost every time (every time on my PR)
using test-windows label might ba good way to reproduce

**Comment by craigtaverner** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/mkwjbvpvk4ewa/tests/:x-pack:plugin:rollup:test/org.elasticsearch.xpack.rollup.RollupResponseTranslationTests/testNonMatchingPartition?top-execution=1

**Comment by pgomulka** [comment]
another one https://gradle-enterprise.elastic.co/s/gvayvipr74hsc/tests/:x-pack:plugin:rollup:test/org.elasticsearch.xpack.rollup.job.RollupIndexerStateTests/testStateChangeMidTrigger?top-execution=1

**Comment by romseygeek** [comment]
Another bunch of failures on `RollupIndexerStateTests`:
* `testBulkFailure` https://gradle-enterprise.elastic.co/s/v76qz42glfmum
* `testAbortIndexing` https://gradle-enterprise.elastic.co/s/advklf564cf2y
* `testFailureWhileStopping` https://gradle-enterprise.elastic.co/s/advklf564cf2y

And one in `SearchActionTests#testSeparateAll` https://gradle-enterprise.elastic.co/s/omwnrrylxbgkk

I don't think muting individual tests is helping here as it seems to be a larger issue with a resource leak somewhere in rollups.
