### ISSUE TITLE
[CI] :qa:full-cluster-restart:v8.4.3#upgradedClusterTest failure on restart

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#90686]
### CI Link

https://gradle-enterprise.elastic.co/s/bgas62xzkoiry

### Repro line

none / ./gradlew ":qa:full-cluster-restart:v8.4.3#upgradedClusterTest"

### Does it reproduce?

No

### Applicable branches

8.5

### Failure history

Didn't find previous errors yet

### Failure excerpt

https://gradle-enterprise.elastic.co/s/bgas62xzkoiry/console-log/raw?task=:qa:full-cluster-restart:v8.4.3%23upgradedClusterTest

```
:qa:full-cluster-restart:v8.4.3#upgradedClusterTest FAILED

=== Log output of node `node{:qa:full-cluster-restart:v8.4.3-0}` ===

»    ↓ errors and warnings from /var/lib/jenkins/workspace/elastic+elasticsearch+8.5+multijob+platform-support-unix/os/ubuntu-22.04&&immutable/qa/full-cluster-restart/build/testclusters/v8.4.3-0/logs/es.out ↓
» [2022-10-05T00:59:59,242][WARN ][o.e.d.FileBasedSeedHostsProvider] [v8.4.3-0] expected, but did not find, a dynamic hosts list at [/var/lib/jenkins/workspace/elastic+elasticsearch+8.5+multijob+platform-support-unix/os/ubuntu-22.04&&immutable/qa/full-cluster-restart/build/testclusters/v8.4.3-0/config/unicast_hosts.txt]
»   ↑ repeated 3 times ↑
» [2022-10-05T00:59:59,232][WARN ][o.e.c.c.ClusterBootstrapService] [v8.4.3-0] this node is locked into cluster UUID [W6ZjXbPpTMa7fo_f47cwew] but [cluster.initial_master_nodes] is set to [v8.4.3-0, v8.4.3-1]; remove this setting to avoid possible data loss caused by subsequent cluster bootstrap attempts
»   ↓ last 40 non error or warning messages from /var/lib/jenkins/workspace/elastic+elasticsearch+8.5+multijob+platform-support-unix/os/ubuntu-22.04&&immutable/qa/full-cluster-restart/build/testclusters/v8.4.3-0/logs/es.out ↓
» [2022-10-05T00:59:58,624][INFO ][o.e.t.TransportService   ] [v8.4.3-0] publish_address {127.0.0.1:44013}, bound_addresses {[::1]:38727}, {127.0.0.1:44013}
» [2022-10-05T00:59:59,254][INFO ][o.e.h.AbstractHttpServerTransport] [v8.4.3-0] publish_address {127.0.0.1:43029}, bound_addresses {[::1]:39401}, {127.0.0.1:43029}
» [2022-10-05T00:59:59,259][INFO ][o.e.n.Node               ] [v8.4.3-0] started {v8.4.3-0}{ShVFuqm8Q_qZy_x37uREYA}{_Pln3-mDTMeQQDY6gsHTBw}{v8.4.3-0}{127.0.0.1}{127.0.0.1:44013}{cdfhilmrstw}{ml.allocated_processors_double=32.0, ml.allocated_processors=32, upgraded=true, ml.machine_memory=101250101248, testattr=test, xpack.installed=true, ml.max_jvm_size=536870912}
» [2022-10-05T00:59:59,394][INFO ][o.e.c.r.a.AllocationService] [v8.4.3-0] updating number_of_replicas to [0] for indices [.tasks]
» [2022-10-05T00:59:59,399][INFO ][o.e.c.s.MasterService    ] [v8.4.3-0] elected-as-master ([1] nodes joined)[_FINISH_ELECTION_, {v8.4.3-0}{ShVFuqm8Q_qZy_x37uREYA}{_Pln3-mDTMeQQDY6gsHTBw}{v8.4.3-0}{127.0.0.1}{127.0.0.1:44013}{cdfhilmrstw} completing election], term: 3, version: 184, delta: master node changed {previous [], current [{v8.4.3-0}{ShVFuqm8Q_qZy_x37uREYA}{_Pln3-mDTMeQQDY6gsHTBw}{v8.4.3-0}{127.0.0.1}{127.0.0.1:44013}{cdfhilmrstw}]}
» [2022-10-05T00:59:59,482][INFO ][o.e.c.s.ClusterApplierService] [v8.4.3-0] master node changed {previous [], current [{v8.4.3-0}{ShVFuqm8Q_qZy_x37uREYA}{_Pln3-mDTMeQQDY6gsHTBw}{v8.4.3-0}{127.0.0.1}{127.0.0.1:44013}{cdfhilmrstw}]}, term: 3, version: 184, reason: Publication{term=3, version=184}
» [2022-10-05T00:59:59,556][INFO ][o.e.r.s.FileSettingsService] [v8.4.3-0] starting file settings watcher ...
» [2022-10-05T00:59:59,562][INFO ][o.e.r.s.FileSettingsService] [v8.4.3-0] file settings service up and running [tid=90]
» [2022-10-05T00:59:59,663][INFO ][o.e.x.c.t.IndexTemplateRegistry] [v8.4.3-0] upgrading composable template [.monitoring-es-mb] for [monitoring] from version [8000102] to version [8000103]
» [2022-10-05T00:59:59,664][INFO ][o.e.x.c.t.IndexTemplateRegistry] [v8.4.3-0] upgrading composable template [.monitoring-ent-search-mb] for [monitoring] from version [8000102] to version [8000103]
» [2022-10-05T00:59:59,665][INFO ][o.e.x.c.t.IndexTemplateRegistry] [v8.4.3-0] upgrading composable template [.monitoring-logstash-mb] for [monitoring] from version [8000102] to version [8000103]
» [2022-10-05T00:59:59,665][INFO ][o.e.x.c.t.IndexTemplateRegistry] [v8.4.3-0] upgrading composable template [.monitoring-kibana-mb] for [monitoring] from version [8000102] to version [8000103]
» [2022-10-05T00:59:59,666][INFO ][o.e.x.c.t.IndexTemplateRegistry] [v8.4.3-0] upgrading composable template [.monitoring-beats-mb] for [monitoring] from version [8000102] to version [8000103]
» [2022-10-05T00:59:59,667][INFO ][o.e.x.c.t.IndexTemplateRegistry] [v8.4.3-0] upgrading composable template [.ml-notifications-000002] for [ml] from version [8040399] to version [8050099]
» [2022-10-05T00:59:59,667][INFO ][o.e.x.c.t.IndexTemplateRegistry] [v8.4.3-0] upgrading composable template [.ml-anomalies-] for [ml] from version [8040399] to version [8050099]
» [2022-10-05T00:59:59,667][INFO ][o.e.x.c.t.IndexTemplateRegistry] [v8.4.3-0] upgrading composable template [.ml-state] for [ml] from version [8040399] to version [8050099]
» [2022-10-05T00:59:59,668][INFO ][o.e.x.c.t.IndexTemplateRegistry] [v8.4.3-0] upgrading composable template [.ml-stats] for [ml] from version [8040399] to version [8050099]
» [2022-10-05T00:59:59,732][INFO ][o.e.l.LicenseService     ] [v8.4.3-0] license [cb795875-7ca8-48b9-9cc1-0fd6075dd615] mode [basic] - valid
» [2022-10-05T00:59:59,738][INFO ][o.e.g.GatewayService     ] [v8.4.3-0] recovered [26] indices into cluster_state
» [2022-10-05T00:59:59,838][INFO ][o.e.c.m.MetadataIndexTemplateService] [v8.4.3-0] updating index template [.monitoring-ent-search-mb] for index patterns [.monitoring-ent-search-8-*]
» [2022-10-05T00:59:59,979][INFO ][o.e.c.m.MetadataIndexTemplateService] [v8.4.3-0] updating index template [.monitoring-es-mb] for index patterns [.monitoring-es-8-*]
» [2022-10-05T01:00:00,016][INFO ][o.e.c.m.MetadataIndexTemplateService] [v8.4.3-0] updating index template [.monitoring-kibana-mb] for index patterns [.monitoring-kibana-8-*]
» [2022-10-05T01:00:00,042][INFO ][o.e.c.m.MetadataIndexTemplateService] [v8.4.3-0] updating index template [.monitoring-logstash-mb] for index patterns [.monitoring-logstash-8-*]
» [2022-10-05T01:00:00,090][INFO ][o.e.c.m.MetadataIndexTemplateService] [v8.4.3-0] updating index template [.monitoring-beats-mb] for index patterns [.monitoring-beats-8-*]
» [2022-10-05T01:00:00,102][INFO ][o.e.c.m.MetadataIndexTemplateService] [v8.4.3-0] updating index template [.ml-notifications-000002] for index patterns [.ml-notifications-000002]
» [2022-10-05T01:00:00,134][INFO ][o.e.c.m.MetadataIndexTemplateService] [v8.4.3-0] updating index template [.ml-anomalies-] for index patterns [.ml-anomalies-*]
» [2022-10-05T01:00:00,143][INFO ][o.e.c.m.MetadataIndexTemplateService] [v8.4.3-0] updating index template [.ml-state] for index patterns [.ml-state*]
» [2022-10-05T01:00:00,154][INFO ][o.e.c.m.MetadataIndexTemplateService] [v8.4.3-0] updating index template [.ml-stats] for index patterns [.ml-stats-*]
» [2022-10-05T01:00:00,483][INFO ][o.e.h.n.s.HealthNodeTaskExecutor] [v8.4.3-0] Node [{v8.4.3-0}{ShVFuqm8Q_qZy_x37uREYA}] is selected as the current health node.
» [2022-10-05T01:00:00,527][INFO ][o.e.i.SystemIndexManager ] [v8.4.3-0] Index [.tasks] (alias [null]) mappings are not up-to-date and will be updated
» [2022-10-05T01:00:00,560][INFO ][o.e.c.m.MetadataMappingService] [v8.4.3-0] [.tasks/_LKzC2aLSgq3Kf7SiTZ3cg] update_mapping [_doc]
» [2022-10-05T01:00:00.791553857Z] [BUILD] Stopping node
» [2022-10-05T01:00:00,818][INFO ][o.e.n.Node               ] [v8.4.3-0] stopping ...
» [2022-10-05T01:00:00,819][INFO ][o.e.r.s.FileSettingsService] [v8.4.3-0] shutting down watcher thread
» [2022-10-05T01:00:00,820][INFO ][o.e.r.s.FileSettingsService] [v8.4.3-0] watcher service stopped
» [2022-10-05T01:00:00,823][INFO ][o.e.x.w.WatcherService   ] [v8.4.3-0] stopping watch service, reason [shutdown initiated]
» [2022-10-05T01:00:00,823][INFO ][o.e.x.w.WatcherLifeCycleService] [v8.4.3-0] watcher has stopped and shutdown

=== Log output of node `node{:qa:full-cluster-restart:v8.4.3-1}` ===

»    ↓ errors and warnings from /var/lib/jenkins/workspace/elastic+elasticsearch+8.5+multijob+platform-support-unix/os/ubuntu-22.04&&immutable/qa/full-cluster-restart/build/testclusters/v8.4.3-1/logs/es.out ↓
» [2022-10-05T00:57:08,943][WARN ][o.e.d.FileBasedSeedHostsProvider] [v8.4.3-1] expected, but did not find, a dynamic hosts list at [/var/lib/jenkins/workspace/elastic+elasticsearch+8.5+multijob+platform-support-unix/os/ubuntu-22.04&&immutable/qa/full-cluster-restart/build/testclusters/v8.4.3-1/config/unicast_hosts.txt]
» [2022-10-05T00:57:09,909][WARN ][o.e.c.s.MasterService    ] [v8.4.3-1] failing [elected-as-master ([2] nodes joined)[_FINISH_ELECTION_, {v8.4.3-0}{ShVFuqm8Q_qZy_x37uREYA}{Y7BGAPFrQA6BM09HjphLYA}{v8.4.3-0}{127.0.0.1}{127.0.0.1:43131}{cdfhilmrstw} completing election, {v8.4.3-1}{_3-J5xE8Sv6UjeR77qFRlw}{oI3k8w2BRG6NQ8inKbe32Q}{v8.4.3-1}{127.0.0.1}{127.0.0.1:41047}{cdfhilmrstw} completing election]]: failed to commit cluster state version [1] org.elasticsearch.cluster.coordination.FailedToCommitClusterStateException: node is no longer master for term 1 while handling publication
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.coordination.Coordinator.publish(Coordinator.java:1411)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:443)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:333)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:165)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:710)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
»  	at java.base/java.lang.Thread.run(Thread.java:833)
»  
» [2022-10-05T00:59:40,266][WARN ][o.e.c.NodeConnectionsService] [v8.4.3-1] failed to connect to {v8.4.3-0}{ShVFuqm8Q_qZy_x37uREYA}{Y7BGAPFrQA6BM09HjphLYA}{v8.4.3-0}{127.0.0.1}{127.0.0.1:43131}{cdfhilmrstw}{testattr=test, ml.machine_memory=101250101248, ml.max_jvm_size=536870912, xpack.installed=true, ml.allocated_processors=32} (tried [1] times) org.elasticsearch.transport.ConnectTransportException: [v8.4.3-0][127.0.0.1:43131] connect_exception
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:1100)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.action.ActionListener.lambda$toBiConsumer$0(ActionListener.java:305)
»  	at org.elasticsearch.base@8.4.3-SNAPSHOT/org.elasticsearch.core.CompletableContext.lambda$addListener$0(CompletableContext.java:33)
»  	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
»  	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
»  	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
»  	at org.elasticsearch.base@8.4.3-SNAPSHOT/org.elasticsearch.core.CompletableContext.addListener(CompletableContext.java:36)
»  	at org.elasticsearch.transport.netty4@8.4.3-SNAPSHOT/org.elasticsearch.transport.netty4.Netty4TcpChannel.addConnectListener(Netty4TcpChannel.java:141)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.transport.TcpTransport.initiateConnection(TcpTransport.java:396)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:358)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.transport.ClusterConnectionManager.internalOpenConnection(ClusterConnectionManager.java:361)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.transport.ClusterConnectionManager.connectToNodeOrRetry(ClusterConnectionManager.java:212)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.transport.ClusterConnectionManager.connectToNode(ClusterConnectionManager.java:111)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:455)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:439)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.NodeConnectionsService$ConnectionTarget.lambda$connect$0(NodeConnectionsService.java:248)
»  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.NodeConnectionsService.connectToNodes(NodeConnectionsService.java:128)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.connectToNodesAsync(ClusterApplierService.java:520)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.connectToNodesAndWait(ClusterApplierService.java:510)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:484)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:710)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)
»  	at org.elasticsearch.server@8.4.3-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
»  	at java.base/java.lang.Thread.run(Thread.java:833)
»  Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 127.0.0.1/127.0.0.1:43131
»  Caused by: java.net.ConnectException: Connection refused
»  	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
»  	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
»  	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
»  	at io.netty.transport@4.1.77.Final/io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
»  	at io.netty.transport@4.1.77.Final/io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
»  	at io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
»  	at io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623)
»  	at io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586)
»  	at io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
»  	at io.netty.common@4.1.77.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
»  	at io.netty.common@4.1.77.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
»  	at java.base/java.lang.Thread.run(Thread.java:833)
»  
» [2022-10-05T01:00:00,002][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v8.4.3-1] fatal error in thread [elasticsearch[v8.4.3-1][generic][T#3]], exiting java.lang.AssertionError: initial cluster state not set yet
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:181)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:141)
»  	at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporter.onCleanUpIndices(LocalExporter.java:598)
»  	at org.elasticsearch.xpack.monitoring.cleaner.CleanerService$IndicesCleaner.doRunInLifecycle(CleanerService.java:164)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractLifecycleRunnable.doRun(AbstractLifecycleRunnable.java:56)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:892)
»  	at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
»  	at java.base/java.lang.Thread.run(Thread.java:833)
»  
»  
»  ERROR: Elasticsearch exited unexpectedly
»   ↓ last 40 non error or warning messages from /var/lib/jenkins/workspace/elastic+elasticsearch+8.5+multijob+platform-support-unix/os/ubuntu-22.04&&immutable/qa/full-cluster-restart/build/testclusters/v8.4.3-1/logs/es.out ↓
» [2022-10-05T00:59:51,011][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-async-search]
» [2022-10-05T00:59:51,012][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-autoscaling]
» [2022-10-05T00:59:51,012][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-ccr]
» [2022-10-05T00:59:51,014][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-core]
» [2022-10-05T00:59:51,014][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-deprecation]
» [2022-10-05T00:59:51,014][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-enrich]
» [2022-10-05T00:59:51,014][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-eql]
» [2022-10-05T00:59:51,014][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-fleet]
» [2022-10-05T00:59:51,014][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-graph]
» [2022-10-05T00:59:51,015][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-identity-provider]
» [2022-10-05T00:59:51,016][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-ilm]
» [2022-10-05T00:59:51,016][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-logstash]
» [2022-10-05T00:59:51,017][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-ml]
» [2022-10-05T00:59:51,017][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-monitoring]
» [2022-10-05T00:59:51,018][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-ql]
» [2022-10-05T00:59:51,018][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-rollup]
» [2022-10-05T00:59:51,018][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-security]
» [2022-10-05T00:59:51,018][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-shutdown]
» [2022-10-05T00:59:51,019][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-sql]
» [2022-10-05T00:59:51,020][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-stack]
» [2022-10-05T00:59:51,021][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-text-structure]
» [2022-10-05T00:59:51,021][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-voting-only-node]
» [2022-10-05T00:59:51,021][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] loaded module [x-pack-watcher]
» [2022-10-05T00:59:51,022][INFO ][o.e.p.PluginsService     ] [v8.4.3-1] no plugins loaded
» [2022-10-05T00:59:54,239][INFO ][o.e.e.NodeEnvironment    ] [v8.4.3-1] using [1] data paths, mounts [[/ (/dev/root)]], net usable_space [249.1gb], net total_space [339gb], types [ext4]
» [2022-10-05T00:59:54,240][INFO ][o.e.e.NodeEnvironment    ] [v8.4.3-1] heap size [512mb], compressed ordinary object pointers [true]
» [2022-10-05T00:59:54,389][INFO ][o.e.n.Node               ] [v8.4.3-1] node name [v8.4.3-1], node ID [_3-J5xE8Sv6UjeR77qFRlw], cluster name [v8.4.3], roles [data_frozen, ml, data_hot, transform, data_content, data_warm, master, remote_cluster_client, data, data_cold, ingest]
» [2022-10-05T00:59:57,525][INFO ][o.e.x.s.Security         ] [v8.4.3-1] Security is disabled
» [2022-10-05T00:59:57,609][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [v8.4.3-1] [controller/440607] [Main.cc@123] controller (64 bit): Version 8.5.0-SNAPSHOT (Build 3922fab346e761) Copyright (c) 2022 Elasticsearch BV
» [2022-10-05T00:59:58,220][INFO ][o.e.t.n.NettyAllocator   ] [v8.4.3-1] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=1mb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=4mb, heap_size=512mb}]
» [2022-10-05T00:59:58,250][INFO ][o.e.i.r.RecoverySettings ] [v8.4.3-1] using rate limit [40mb] with [default=40mb, read=0b, write=0b, max=0b]
» [2022-10-05T00:59:58,297][INFO ][o.e.d.DiscoveryModule    ] [v8.4.3-1] using discovery type [multi-node] and seed hosts providers [settings, file]
» [2022-10-05T00:59:59,477][INFO ][o.e.n.Node               ] [v8.4.3-1] initialized
» [2022-10-05T00:59:59,478][INFO ][o.e.n.Node               ] [v8.4.3-1] starting ...
» [2022-10-05T00:59:59,508][INFO ][o.e.x.s.c.f.PersistentCache] [v8.4.3-1] persistent cache index loaded
» [2022-10-05T00:59:59,510][INFO ][o.e.x.d.l.DeprecationIndexingComponent] [v8.4.3-1] deprecation component started
» [2022-10-05T00:59:59,674][INFO ][o.e.t.TransportService   ] [v8.4.3-1] publish_address {127.0.0.1:33205}, bound_addresses {[::1]:34595}, {127.0.0.1:33205}
» [2022-10-05T01:00:01.130472976Z] [BUILD] Stopping node

```

**Comment by cbuescher** [comment]
I'm not sure what to make out of the logs other than that there seems to be a connection problem at startup.
This error particularly made me label this as a "distbuted" topic first, but please correct this if I'm wrong or missing the obvious: 
`org.elasticsearch.cluster.coordination.FailedToCommitClusterStateException: node is no longer master for term 1 while handling publication`

**Comment by arteam** [comment]
I couldn't reproduce this error locally and there no errors in CI on the 8.5 branch (which is also now outdated). I assume this was a an isolated failure due to connection issues.
