### ISSUE TITLE
[CI] SnaphotsAndFileSettingsIT testRestoreWithPersistedFileSettings failing

### ISSUE THREAD

**Issue by joegallo** [elastic/elasticsearch#90692]
**Build scan:**
https://gradle-enterprise.elastic.co/s/bngqipzvd33he/tests/:server:internalClusterTest/org.elasticsearch.reservedstate.service.SnaphotsAndFileSettingsIT/testRestoreWithPersistedFileSettings

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.reservedstate.service.SnaphotsAndFileSettingsIT.testRestoreWithPersistedFileSettings" -Dtests.seed=9110D7569E3D7948 -Dtests.jvm.argline="--enable-preview" -Dtests.locale=cs-CZ -Dtests.timezone=Asia/Muscat -Druntime.java=19`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.reservedstate.service.SnaphotsAndFileSettingsIT&tests.test=testRestoreWithPersistedFileSettings

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertTrue(Assert.java:52)
  at org.elasticsearch.reservedstate.service.SnaphotsAndFileSettingsIT.assertClusterStateSaveOK(SnaphotsAndFileSettingsIT.java:113)
  at org.elasticsearch.reservedstate.service.SnaphotsAndFileSettingsIT.testRestoreWithPersistedFileSettings(SnaphotsAndFileSettingsIT.java:318)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by joegallo** [comment]
Looks pretty similar to #90113, but that was closed by https://github.com/elastic/elasticsearch/pull/90117.

Test history is especially interesting here (https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=America/New_York&tests.container=org.elasticsearch.reservedstate.service.SnaphotsAndFileSettingsIT&tests.test=testRestoreWithPersistedFileSettings) there's three failures that look the same and one that looks different, but they all have a line like this in the logs:

```
[2022-09-29T11:14:40,458][WARN ][o.e.r.s.ReservedStateUpdateTask] [[elasticsearch[file-settings-watcher]]] Not updating reserved cluster state for namespace [file_settings], because version [2] is less or equal to the current metadata version [2] |  
-- | --
  | سبت 29, 2022 11:14:40 ص com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException |  
  | WARNING: Uncaught exception in thread: Thread[elasticsearch[file-settings-watcher],5,TGRP-SnaphotsAndFileSettingsIT] |  
  | java.lang.AssertionError |  
  | at __randomizedtesting.SeedInfo.seed([897B64625F82F06C]:0) |  
  | at org.apache.lucene.tests.mockfile.WindowsFS.onClose(WindowsFS.java:79) |  
  | at org.apache.lucene.tests.mockfile.HandleTrackingFS$1.close(HandleTrackingFS.java:103) |  
  | at java.base/java.io.BufferedInputStream.close(BufferedInputStream.java:481) |  
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeInput(UTF8StreamJsonParser.java:291) |  
  | at com.fasterxml.jackson.core.base.ParserBase.close(ParserBase.java:374) |  
  | at org.elasticsearch.core.IOUtils.close(IOUtils.java:71) |  
  | at org.elasticsearch.core.IOUtils.closeWhileHandlingException(IOUtils.java:169) |  
  | at org.elasticsearch.xcontent.provider.json.JsonXContentParser.close(JsonXContentParser.java:267) |  
  | at org.elasticsearch.reservedstate.service.FileSettingsService.processFileSettings(FileSettingsService.java:426) |  
  | at org.elasticsearch.reservedstate.service.FileSettingsService.lambda$startWatcher$3(FileSettingsService.java:328) |  
  | at java.base/java.lang.Thread.run(Thread.java:833)
```

Also in some cases another test fails, too, although I didn't get a notification for that. Examples: 
- https://gradle-enterprise.elastic.co/s/wyi32k7og5s5g/tests/overview?outcome=failed 
- https://gradle-enterprise.elastic.co/s/5plxopim2uz7g/tests/overview?outcome=failed

**Comment by grcevski** [comment]
Ah this is good, I used to have a test bug here that hid the actual exception, so I was fixing issues blind. It looks like we don't wait properly somewhere for the most up to date version of the cluster state.

**Comment by albertzaharovits** [comment]
I'm sorry to report that the bug might not have been slained:
https://gradle-enterprise.elastic.co/s/pr6kcxs2batve
My check shows that the merge commit for this bug-fix is an ancestor of the commit from the CI run:
`https://gradle-enterprise.elastic.co/s/pr6kcxs2batve`

Reopening... 😢
