### ISSUE TITLE
[CI] LoggedExecFuncTest failure

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#90718]
it happened in my pr twice - not related to this test
https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Warsaw&tests.container=org.elasticsearch.gradle.LoggedExecFuncTest&tests.test=failed%20tasks%20output%20logged%20to%20console%20when%20spooling%20true

**Build scan:**
https://gradle-enterprise.elastic.co/s/4vvzu6gt5rzac/tests/:integTest/org.elasticsearch.gradle.LoggedExecFuncTest/failed%20tasks%20output%20logged%20to%20console%20when%20spooling%20true

**Reproduction line:**
it is build tools so no reproduce line. but the test can be run with:
:build-tools:integTest

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.LoggedExecFuncTest&tests.test=failed%20tasks%20output%20logged%20to%20console%20when%20spooling%20true

**Failure excerpt:**
```
org.spockframework.runtime.ConditionNotSatisfiedError: Condition not satisfied:

normalized(givenOutput).contains(normalized(expected))
|          |            |        |          |
|          |            false    |          > Task :loggedExec FAILED
|          |                     |          Output for ls:
|          |                     > Task :loggedExec FAILED
|          |                     Output for ls:
|          Configuration cache is an incubating feature.
|          Calculating task graph as no configuration cache is available for tasks: loggedExec
|           
|          > Task :loggedExec FAILED
|          Could not read error output of command 'ls'.
|          java.io.IOException: Stream Closed
|          	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
|          	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
|          	at org.elasticsearch.gradle.LazyFileOutputStream.write(LazyFileOutputStream.java:51)
|          	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:67)
|          	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
|          	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
|          	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
|          	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
|          	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
|          	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
|          	at java.base/java.lang.Thread.run(Thread.java:833)
|          Output for ls:
|          ls: cannot access wtf
|           
|          FAILURE: Build failed with an exception.
|           
|          * What went wrong:
|          Execution failed for task ':loggedExec'.
|          > Process 'ls [wtf]' finished with non-zero exit value 2
|           
|          * Try:
|          > Run with --stacktrace option to get the stack trace.
|          > Run with --info or --debug option to get more log output.
|          > Run with --scan to get full insights.
|           
|          * Get more help at https://help.gradle.org
|           
|          BUILD FAILED in 3s
|          1 actionable task: 1 executed
|          Configuration cache entry stored.
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: loggedExec
 
> Task :loggedExec FAILED
Could not read error output of command 'ls'.
java.io.IOException: Stream Closed
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
	at org.elasticsearch.gradle.LazyFileOutputStream.write(LazyFileOutputStream.java:51)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:67)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Output for ls:
ls: cannot access wtf
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':loggedExec'.
> Process 'ls [wtf]' finished with non-zero exit value 2
 
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
 
* Get more help at https://help.gradle.org
 
BUILD FAILED in 3s
1 actionable task: 1 executed
Configuration cache entry stored.

  at org.elasticsearch.gradle.fixtures.AbstractGradleFuncTest.assertOutputContains(AbstractGradleFuncTest.groovy:96)
  at org.elasticsearch.gradle.LoggedExecFuncTest.failed tasks output logged to console when spooling #spooling(LoggedExecFuncTest.groovy:67)

```

**Comment by mark-vieira** [comment]
This hasn't happened since so let's just keep an eye on it for now.
