### ISSUE TITLE
[CI] SizeMappingIT testGetWithFields failing

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#90881]
**Build scan:**
https://gradle-enterprise.elastic.co/s/efva2osgphkle/tests/:plugins:mapper-size:internalClusterTest/org.elasticsearch.index.mapper.size.SizeMappingIT/testGetWithFields

**Reproduction line:**
`./gradlew ':plugins:mapper-size:internalClusterTest' --tests "org.elasticsearch.index.mapper.size.SizeMappingIT.testGetWithFields" -Dtests.seed=FA954CBDA791C93D -Dtests.locale=en-GB -Dtests.timezone=Canada/Saskatchewan -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.mapper.size.SizeMappingIT&tests.test=testGetWithFields

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([FA954CBDA791C93D]:0)

```

**Comment by jtibshirani** [comment]
Here's the important part of the stack trace:
```
WARNING: Uncaught exception in thread: Thread[elasticsearch[node_s4][search][T#1],5,TGRP-SizeMappingIT]
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([FA954CBDA791C93D]:0)
	at org.apache.lucene.tests.index.AssertingLeafReader$AssertingNumericDocValues.advanceExact(AssertingLeafReader.java:664)
	at org.apache.lucene.index.SingletonSortedNumericDocValues.advanceExact(SingletonSortedNumericDocValues.java:62)
	at org.elasticsearch.index.fielddata.plain.LeafLongFieldData$1.advanceExact(LeafLongFieldData.java:53)
	at org.elasticsearch.index.mapper.DocValueFetcher.fetchValues(DocValueFetcher.java:43)
	at org.elasticsearch.index.mapper.ValueFetcher.fetchDocumentField(ValueFetcher.java:57)
	at org.elasticsearch.search.fetch.subphase.FieldFetcher.fetch(FieldFetcher.java:171)
```

I poked around and found that this started failing consistently after #90762, but passes before. CC @romseygeek
