### ISSUE TITLE
[CI] InternalTestClusterIT testOperationsDuringRestart failing

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#90919]
This could be a transient error or maybe we have a leak and create too many watches?

**Build scan:**
https://gradle-enterprise.elastic.co/s/year4ovkhfudu/tests/:test:framework:integTest/org.elasticsearch.test.test.InternalTestClusterIT/testOperationsDuringRestart

**Reproduction line:**
`./gradlew ':test:framework:integTest' --tests "org.elasticsearch.test.test.InternalTestClusterIT.testOperationsDuringRestart" -Dtests.seed=3D1D47F12F43EB1B -Dtests.locale=es-NI -Dtests.timezone=America/Tegucigalpa -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.test.test.InternalTestClusterIT&tests.test=testOperationsDuringRestart

**Failure excerpt:**
```
java.lang.IllegalStateException: unable to launch a new watch service

  at __randomizedtesting.SeedInfo.seed([3D1D47F12F43EB1B:7443105028BF84F0]:0)
  at org.elasticsearch.reservedstate.service.FileSettingsService.startWatcher(FileSettingsService.java:277)
  at org.elasticsearch.reservedstate.service.FileSettingsService.startIfMaster(FileSettingsService.java:157)
  at org.elasticsearch.reservedstate.service.FileSettingsService.doStart(FileSettingsService.java:130)
  at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:43)
  at org.elasticsearch.node.Node.start(Node.java:1384)
  at org.elasticsearch.test.InternalTestCluster$NodeAndClient.startNode(InternalTestCluster.java:982)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:850)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.io.IOException: User limit of inotify watches reached

    at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)
    at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:266)
    at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:364)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by thecoop** [comment]
Looks like #89500 again

**Comment by thecoop** [comment]
@mark-vieira has disabled gradle watching for nested BwC builds, we'll need to see if it happens again...
