### ISSUE TITLE
[CI] RoundingTests testHugeTimeFewAttempts failing

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#91040]
**Build scan:**
https://gradle-enterprise.elastic.co/s/l7mi5zj66i5qa/tests/:server:test/org.elasticsearch.common.RoundingTests/testHugeTimeFewAttempts

**Reproduction line:**
`gradlew ':server:test' --tests "org.elasticsearch.common.RoundingTests.testHugeTimeFewAttempts" -Dtests.seed=DADD78254C30E9CA -Dtests.locale=is-IS -Dtests.timezone=Africa/Bamako -Druntime.java=19`

**Applicable branches:**
main, 8.5, 8.4, 7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.common.RoundingTests&tests.test=testHugeTimeFewAttempts

**Failure excerpt:**
```
junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown

  at __randomizedtesting.SeedInfo.seed([DADD78254C30E9CA:E3D09D6ABB5F56AB]:0)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2854)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2840)
  at org.elasticsearch.common.RoundingTests.testHugeTimeFewAttempts(RoundingTests.java:1024)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by davidkyle** [comment]
This is failing _fairly_ frequently on Windows but there is the occasional Linux failure also. Here's one https://gradle-enterprise.elastic.co/s/hjfonnvbxpzbg/tests/:server:test/org.elasticsearch.common.RoundingTests/testHugeTimeFewAttempts?top-execution=1

**Comment by ywangd** [comment]
Failed a bunch of times on Windows for 8.4

* https://gradle-enterprise.elastic.co/s/ei2o42pzhfvnu/tests/:server:test/org.elasticsearch.common.RoundingTests/testHugeTimeFewAttempts?top-execution=1
* https://gradle-enterprise.elastic.co/s/xhtmpxvqisbxm/tests/:server:test/org.elasticsearch.common.RoundingTests/testHugeTimeFewAttempts?top-execution=1
* https://gradle-enterprise.elastic.co/s/dq7v6txs7vyys/tests/:server:test/org.elasticsearch.common.RoundingTests/testHugeTimeFewAttempts

Should we backport the mute to 8.4? It's strange that it hasn't failed for 8.5?

**Comment by mark-vieira** [comment]
>  It's strange that it hasn't failed for 8.5?

It has, but interestingly only on the Java 19 jobs.

https://gradle-enterprise.elastic.co/scans/tests?search.tags=8.5&search.timeZoneId=Europe/Paris&tests.container=org.elasticsearch.common.RoundingTests&tests.test=testHugeTimeFewAttempts#

**Comment by thecoop** [comment]
This is possibly because the tz database has changed

The [2022b changelog](http://mm.icann.org/pipermail/tz-announce/2022-August/000071.html), on 11th August, includes
> Iran no longer observes DST after 2022.

The timezone tested is `Asia/Tehran`, so it could be that the specific timezone version used by the running jdk affects whether this test passes or fails. This may also be why it is more likely to change on jdk19, which is likely to use more up-to-date tzdata

**Comment by gmarouli** [comment]
We see failures also in other branches:
- `7.17`: https://gradle-enterprise.elastic.co/s/huhz5en2dkjdc/tests/:server:test/org.elasticsearch.common.RoundingTests/testHugeTimeFewAttempts
- `8.5`: https://gradle-enterprise.elastic.co/s/bbohmwuugcy2i/tests/:server:test/org.elasticsearch.common.RoundingTests/testHugeTimeFewAttempts
