### ISSUE TITLE
[CI] EqlSearchResponseTests testEqualsAndHashcode failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#91245]
**Build scan:**
https://gradle-enterprise.elastic.co/s/lg7kfskqvxyb6/tests/:x-pack:plugin:eql:test/org.elasticsearch.xpack.eql.action.EqlSearchResponseTests/testEqualsAndHashcode

**Reproduction line:**
`./gradlew ':x-pack:plugin:eql:test' --tests "org.elasticsearch.xpack.eql.action.EqlSearchResponseTests.testEqualsAndHashcode" -Dtests.seed=4B4A565053DC7610 -Dtests.locale=ca -Dtests.timezone=Europe/San_Marino -Druntime.java=18`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.eql.action.EqlSearchResponseTests&tests.test=testEqualsAndHashcode

**Failure excerpt:**
```
java.lang.IllegalArgumentException: duplicate key: xsXLL

  at __randomizedtesting.SeedInfo.seed([4B4A565053DC7610:3A452E9D9C3B3F3F]:0)
  at java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1189)
  at java.util.Map.of(Map.java:1395)
  at org.elasticsearch.xpack.eql.action.EqlSearchResponseTests.lambda$randomDocumentField$2(EqlSearchResponseTests.java:139)
  at org.elasticsearch.test.ESTestCase.randomList(ESTestCase.java:989)
  at org.elasticsearch.xpack.eql.action.EqlSearchResponseTests.randomDocumentField(EqlSearchResponseTests.java:136)
  at org.elasticsearch.xpack.eql.action.EqlSearchResponseTests.randomEvents(EqlSearchResponseTests.java:107)
  at org.elasticsearch.xpack.eql.action.EqlSearchResponseTests.createRandomSequencesResponse(EqlSearchResponseTests.java:203)
  at org.elasticsearch.xpack.eql.action.EqlSearchResponseTests.createRandomInstance(EqlSearchResponseTests.java:238)
  at org.elasticsearch.xpack.eql.action.EqlSearchResponseTests.randomEqlSearchResponse(EqlSearchResponseTests.java:170)
  at org.elasticsearch.xpack.eql.action.EqlSearchResponseTests.createTestInstance(EqlSearchResponseTests.java:157)
  at org.elasticsearch.xpack.eql.action.EqlSearchResponseTests.createTestInstance(EqlSearchResponseTests.java:38)
  at org.elasticsearch.test.AbstractWireTestCase.testEqualsAndHashcode(AbstractWireTestCase.java:58)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by luigidellaquila** [comment]
I can confirm, it's deterministic with that seed
