### ISSUE TITLE
The :distribution:bwc:maintenance:buildBwcZip task failed

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#91378]
### CI Link

https://gradle-enterprise.elastic.co/s/4c2b5gqkgrhr6/console-log?task=:distribution:bwc:maintenance:buildBwcZip

### Repro line

Has appeared in several test failures recently

### Does it reproduce?

Yes

### Applicable branches

7.17

### Failure history

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Process%20*/*%2C%20-Dbuild.snapshot%3Dtrue%2C%20-Dscan.tag.NESTED%2C%20*--parallel%2C%20*%20--build-cache%5D%27%20finished%20with%20non-zero%20exit%20value%201&search.timeZoneId=Europe/Athens

### Failure excerpt

```




:distribution:bwc:maintenance:buildBwcZip FAILED |  
  | Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 |  
  | Starting a Gradle Daemon (subsequent builds will be faster) |  
  | [6.8.24] > Task :buildSrc:compileMinimumRuntimeJava NO-SOURCE |  
  | [6.8.24] |  
  | [6.8.24] > Task :buildSrc:compileMinimumRuntimeGroovy |  
  | [6.8.24] Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 |  
  | [6.8.24] warning: [options] bootstrap class path not set in conjunction with -source 8 |  
  | [6.8.24] 1 warning |  
  | [6.8.24] |  
  | [6.8.24] > Task :buildSrc:processMinimumRuntimeResources NO-SOURCE |  
  | [6.8.24] > Task :buildSrc:minimumRuntimeClasses |  
  | [6.8.24] > Task :buildSrc:compileJava FAILED |  
  | [6.8.24] |  
  | [6.8.24] FAILURE: Build failed with an exception. |  
  | [6.8.24] |  
  | [6.8.24] * What went wrong: |  
  | [6.8.24] Execution failed for task ':buildSrc:compileJava'. |  
  | [6.8.24] > Could not resolve all files for configuration ':buildSrc:compileClasspath'. |  
  | [6.8.24]    > Could not find com.avast.gradle:gradle-docker-compose-plugin:0.8.12. |  
  | [6.8.24]      Searched in the following locations: |  
  | [6.8.24]        - https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.pom |  
  | [6.8.24]        - https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.jar |  
  | [6.8.24]        - https://plugins.gradle.org/m2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.pom |  
  | [6.8.24]        - https://plugins.gradle.org/m2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.jar |  
  | [6.8.24]      Required by: |  
  | [6.8.24]          project :buildSrc |  
  | [6.8.24]    > Could not find org.gradle:gradle-logging:4.3. |  
  | [6.8.24]      Searched in the following locations: |  
  | [6.8.24]        - https://repo.maven.apache.org/maven2/org/gradle/gradle-logging/4.3/gradle-logging-4.3.pom |  
  | [6.8.24]        - https://repo.maven.apache.org/maven2/org/gradle/gradle-logging/4.3/gradle-logging-4.3.jar |  
  | [6.8.24]        - https://plugins.gradle.org/m2/org/gradle/gradle-logging/4.3/gradle-logging-4.3.pom |  
  | [6.8.24]        - https://plugins.gradle.org/m2/org/gradle/gradle-logging/4.3/gradle-logging-4.3.jar |  
  | [6.8.24]      Required by: |  
  | [6.8.24]          project :buildSrc |  
  | [6.8.24] |  
  | [6.8.24] * Try: |  
  | [6.8.24] Run with --info or --debug option to get more log output. Run with --scan to get full insights. |  
  | [6.8.24] |  
  | [6.8.24] * Exception is: |  
  | [6.8.24] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildSrc:compileJava'. |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49) |  
  | [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416) |  
  | [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406) |  
  | [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165) |  
  | [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250) |  
  | [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158) |  
  | [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102) |  
  | [6.8.24] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49) |  
  | [6.8.24] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43) |  
  | [6.8.24] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355) |  
  | [6.8.24] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343) |  
  | [6.8.24] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336) |  
  | [6.8.24] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322) |  
  | [6.8.24] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134) |  
  | [6.8.24] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129) |  
  | [6.8.24] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202) |  
  | [6.8.24] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193) |  
  | [6.8.24] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129) |  
  | [6.8.24] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) |  
  | [6.8.24] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) |  
  | [6.8.24] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) |  
  | [6.8.24] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) |  
  | [6.8.24] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) |  
  | [6.8.24] 	at java.base/java.lang.Thread.run(Thread.java:834) |  
  | [6.8.24] Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':buildSrc:compileClasspath'. |  
  | [6.8.24] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1195) |  
  | [6.8.24] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2100(DefaultConfiguration.java:138) |  
  | [6.8.24] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1170) |  
  | [6.8.24] 	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:72) |  
  | [6.8.24] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.iterator(DefaultConfiguration.java:467) |  
  | [6.8.24] 	at org.gradle.internal.snapshot.impl.DefaultFileSystemSnapshotter$FileCollectionLeafVisitorImpl.visitCollection(DefaultFileSystemSnapshotter.java:240) |  
  | [6.8.24] 	at org.gradle.api.internal.file.AbstractFileCollection.visitLeafCollections(AbstractFileCollection.java:233) |  
  | [6.8.24] 	at org.gradle.api.internal.file.CompositeFileCollection.visitLeafCollections(CompositeFileCollection.java:205) |  
  | [6.8.24] 	at org.gradle.internal.snapshot.impl.DefaultFileSystemSnapshotter.snapshot(DefaultFileSystemSnapshotter.java:126) |  
  | [6.8.24] 	at org.gradle.internal.fingerprint.impl.AbstractFileCollectionFingerprinter.fingerprint(AbstractFileCollectionFingerprinter.java:48) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.DefaultTaskFingerprinter.fingerprintTaskFiles(DefaultTaskFingerprinter.java:46) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.createExecutionState(ResolveBeforeExecutionStateTaskExecuter.java:93) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:73) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:62) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56) |  
  | [6.8.24] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36) |  
  | [6.8.24] 	... 27 more |  
  | [6.8.24] Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.avast.gradle:gradle-docker-compose-plugin:0.8.12. |  
  | [6.8.24] Searched in the following locations: |  
  | [6.8.24]   - https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.pom |  
  | [6.8.24]   - https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.jar |  
  | [6.8.24]   - https://plugins.gradle.org/m2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.pom |  
  | [6.8.24]   - https://plugins.gradle.org/m2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.jar |  
  | [6.8.24] Required by: |  
  | [6.8.24]     project :buildSrc |  
  | [6.8.24] |  
  | [6.8.24] |  
  | [6.8.24] * Get more help at https://help.gradle.org |  
  | [6.8.24] |  
  | [6.8.24] BUILD FAILED in 22s |  
  | Output for /var/lib/jenkins/workspace/elastic+elasticsearch+7.17+multijob+platform-support-unix/os/debian-9&&immutable/distribution/bwc/maintenance/build/bwc/checkout-6.8/gradlew:

<br class="Apple-interchange-newline">:distribution:bwc:maintenance:buildBwcZip FAILED	
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8	
Starting a Gradle Daemon (subsequent builds will be faster)	
 [6.8.24] > Task :buildSrc:compileMinimumRuntimeJava NO-SOURCE	
 [6.8.24] 	
 [6.8.24] > Task :buildSrc:compileMinimumRuntimeGroovy	
 [6.8.24] Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8	
 [6.8.24] warning: [options] bootstrap class path not set in conjunction with -source 8	
 [6.8.24] 1 warning	
 [6.8.24] 	
 [6.8.24] > Task :buildSrc:processMinimumRuntimeResources NO-SOURCE	
 [6.8.24] > Task :buildSrc:minimumRuntimeClasses	
 [6.8.24] > Task :buildSrc:compileJava FAILED	
 [6.8.24] 	
 [6.8.24] FAILURE: Build failed with an exception.	
 [6.8.24] 	
 [6.8.24] * What went wrong:	
 [6.8.24] Execution failed for task ':buildSrc:compileJava'.	
 [6.8.24] > Could not resolve all files for configuration ':buildSrc:compileClasspath'.	
 [6.8.24]    > Could not find com.avast.gradle:gradle-docker-compose-plugin:0.8.12.	
 [6.8.24]      Searched in the following locations:	
 [6.8.24]        - https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.pom	
 [6.8.24]        - https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.jar	
 [6.8.24]        - https://plugins.gradle.org/m2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.pom	
 [6.8.24]        - https://plugins.gradle.org/m2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.jar	
 [6.8.24]      Required by:	
 [6.8.24]          project :buildSrc	
 [6.8.24]    > Could not find org.gradle:gradle-logging:4.3.	
 [6.8.24]      Searched in the following locations:	
 [6.8.24]        - https://repo.maven.apache.org/maven2/org/gradle/gradle-logging/4.3/gradle-logging-4.3.pom	
 [6.8.24]        - https://repo.maven.apache.org/maven2/org/gradle/gradle-logging/4.3/gradle-logging-4.3.jar	
 [6.8.24]        - https://plugins.gradle.org/m2/org/gradle/gradle-logging/4.3/gradle-logging-4.3.pom	
 [6.8.24]        - https://plugins.gradle.org/m2/org/gradle/gradle-logging/4.3/gradle-logging-4.3.jar	
 [6.8.24]      Required by:	
 [6.8.24]          project :buildSrc	
 [6.8.24] 	
 [6.8.24] * Try:	
 [6.8.24] Run with --info or --debug option to get more log output. Run with --scan to get full insights.	
 [6.8.24] 	
 [6.8.24] * Exception is:	
 [6.8.24] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildSrc:compileJava'.	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)	
 [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)	
 [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)	
 [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)	
 [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)	
 [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)	
 [6.8.24] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)	
 [6.8.24] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)	
 [6.8.24] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)	
 [6.8.24] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)	
 [6.8.24] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)	
 [6.8.24] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)	
 [6.8.24] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)	
 [6.8.24] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)	
 [6.8.24] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)	
 [6.8.24] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)	
 [6.8.24] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)	
 [6.8.24] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)	
 [6.8.24] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)	
 [6.8.24] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)	
 [6.8.24] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)	
 [6.8.24] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)	
 [6.8.24] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)	
 [6.8.24] 	at java.base/java.lang.Thread.run(Thread.java:834)	
 [6.8.24] Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':buildSrc:compileClasspath'.	
 [6.8.24] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1195)	
 [6.8.24] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2100(DefaultConfiguration.java:138)	
 [6.8.24] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1170)	
 [6.8.24] 	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:72)	
 [6.8.24] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.iterator(DefaultConfiguration.java:467)	
 [6.8.24] 	at org.gradle.internal.snapshot.impl.DefaultFileSystemSnapshotter$FileCollectionLeafVisitorImpl.visitCollection(DefaultFileSystemSnapshotter.java:240)	
 [6.8.24] 	at org.gradle.api.internal.file.AbstractFileCollection.visitLeafCollections(AbstractFileCollection.java:233)	
 [6.8.24] 	at org.gradle.api.internal.file.CompositeFileCollection.visitLeafCollections(CompositeFileCollection.java:205)	
 [6.8.24] 	at org.gradle.internal.snapshot.impl.DefaultFileSystemSnapshotter.snapshot(DefaultFileSystemSnapshotter.java:126)	
 [6.8.24] 	at org.gradle.internal.fingerprint.impl.AbstractFileCollectionFingerprinter.fingerprint(AbstractFileCollectionFingerprinter.java:48)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.DefaultTaskFingerprinter.fingerprintTaskFiles(DefaultTaskFingerprinter.java:46)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.createExecutionState(ResolveBeforeExecutionStateTaskExecuter.java:93)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:73)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:62)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)	
 [6.8.24] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)	
 [6.8.24] 	... 27 more	
 [6.8.24] Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.avast.gradle:gradle-docker-compose-plugin:0.8.12.	
 [6.8.24] Searched in the following locations:	
 [6.8.24]   - https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.pom	
 [6.8.24]   - https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.jar	
 [6.8.24]   - https://plugins.gradle.org/m2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.pom	
 [6.8.24]   - https://plugins.gradle.org/m2/com/avast/gradle/gradle-docker-compose-plugin/0.8.12/gradle-docker-compose-plugin-0.8.12.jar	
 [6.8.24] Required by:	
 [6.8.24]     project :buildSrc	
 [6.8.24] 	
 [6.8.24] 	
 [6.8.24] * Get more help at https://help.gradle.org/	
 [6.8.24] 	
 [6.8.24] BUILD FAILED in 22s	
Output for /var/lib/jenkins/workspace/elastic+elasticsearch+7.17+multijob+platform-support-unix/os/debian-9&&immutable/distribution/bwc/maintenance/build/bwc/checkout-6.8/gradlew:
```

**Comment by breskeby** [comment]
Added a workaround to the 6.8 branch https://github.com/elastic/elasticsearch/commit/3a01bc9fc11057150c68082432e2e0f8ea70511d

**Comment by kingherc** [comment]
@breskeby can you also do it for 7.17 branch? I see it a lot there as well.

**Comment by breskeby** [comment]
interesting I see other plugins resolved properly. I'll do that for `main` and `7.x` just to be safe

**Comment by pxsalehi** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/duuzjs7ofgjdc

**Comment by craigtaverner** [comment]
Today at https://gradle-enterprise.elastic.co/s/zwbufwel32l56

**Comment by mark-vieira** [comment]
Looks like this has been resolved.

**Comment by piergm** [comment]
Today it happened 4 more times. I'm reopening the issue.
https://gradle-enterprise.elastic.co/s/hj4jukp7c3b7c
https://gradle-enterprise.elastic.co/s/agt5rdxqkfsm4
https://gradle-enterprise.elastic.co/s/xmye3oms65g3e
https://gradle-enterprise.elastic.co/s/akr3zpcqhu2l2
