### ISSUE TITLE
[CI] SnapshotBasedRecoveryIT testSnapshotBasedRecovery failing

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#91383]
```
:qa:rolling-upgrade:v7.17.8#upgradedClusterTest FAILED	
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8	
REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.17.8#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=99DD5020A91464DB -Dtests.bwc=true -Dtests.locale=uk -Dtests.timezone=America/Curacao -Druntime.java=17	
org.elasticsearch.upgrades.SnapshotBasedRecoveryIT > testSnapshotBasedRecovery FAILED	
    org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:41245], URI [/snapshot_based_recovery/_settings], status line [HTTP/1.1 200 OK]	
    Warnings: [[index.indexing.slowlog.level] setting was deprecated in the previous Elasticsearch release and is removed in this release.]	
    {"acknowledged":true}	
        at __randomizedtesting.SeedInfo.seed([99DD5020A91464DB:703258D83588DF92]:0)	
        at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:343)	
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)	
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)	
        at app//org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1609)	
        at app//org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1603)	
        at app//org.elasticsearch.upgrades.SnapshotBasedRecoveryIT.testSnapshotBasedRecovery(SnapshotBasedRecoveryIT.java:103)	
Suite: Test class org.elasticsearch.upgrades.SnapshotBasedRecoveryIT	
  1> [2022-11-07T17:37:03,189][INFO ][o.e.u.SnapshotBasedRecoveryIT] [testSnapshotBasedRecovery] before test	
  1> [2022-11-07T17:37:03,193][INFO ][o.e.u.SnapshotBasedRecoveryIT] [testSnapshotBasedRecovery] initializing REST clients against [http://[::1]:36499, http://127.0.0.1:38953, http://[::1]:37855, http://127.0.0.1:43011, http://[::1]:45727, http://127.0.0.1:41245]	
  2> лист. 07, 2022 5:37:03 PM org.elasticsearch.client.RestClient logResponse	
  2> WARNING: request [PUT http://127.0.0.1:41245/snapshot_based_recovery/_settings] returned 1 warnings: [299 Elasticsearch-8.6.0-SNAPSHOT-a94347e002da18c9d567dde2b1bbec6b3ba133b0 "[index.indexing.slowlog.level] setting was deprecated in the previous Elasticsearch release and is removed in this release."]	
  1> [2022-11-07T17:37:03,387][INFO ][o.e.u.SnapshotBasedRecoveryIT] [testSnapshotBasedRecovery] There are still tasks running after this test that might break subsequent tests [health-node[c]].	
  1> [2022-11-07T17:37:03,388][INFO ][o.e.u.SnapshotBasedRecoveryIT] [testSnapshotBasedRecovery] after test	
  2> REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.17.8#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=99DD5020A91464DB -Dtests.bwc=true -Dtests.locale=uk -Dtests.timezone=America/Curacao -Druntime.java=17	
  2> org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:41245], URI [/snapshot_based_recovery/_settings], status line [HTTP/1.1 200 OK]	
    Warnings: [[index.indexing.slowlog.level] setting was deprecated in the previous Elasticsearch release and is removed in this release.]	
    {"acknowledged":true}	
        at __randomizedtesting.SeedInfo.seed([99DD5020A91464DB:703258D83588DF92]:0)	
        at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:343)	
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)	
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)	
        at app//org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1609)	
        at app//org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1603)	
        at app//org.elasticsearch.upgrades.SnapshotBasedRecoveryIT.testSnapshotBasedRecovery(SnapshotBasedRecoveryIT.java:103)	
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+main+multijob+platform-support-unix/os/debian-10&&immutable/qa/rolling-upgrade/build/testrun/v7.17.8#upgradedClusterTest/temp/org.elasticsearch.upgrades.SnapshotBasedRecoveryIT_99DD5020A91464DB-001	
  2> NOTE: test params are: codec=Asserting(Lucene94): {}, docValues:{}, maxPointsInLeafNode=1084, maxMBSortInHeap=7.319935879968938, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=uk, timezone=America/Curacao	
  2> NOTE: Linux 4.19.0-22-cloud-amd64 amd64/Oracle Corporation 17.0.2 (64-bit)/cpus=32,threads=1,free=361787920,total=536870912	
  2> NOTE: All tests run in this JVM: [DesiredNodesUpgradeIT, FeatureUpgradeIT, FieldCapsIT, IndexingIT, RecoveryIT, SnapshotBasedRecoveryIT]	
WARNING: A terminally deprecated method in java.lang.System has been called	
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/var/lib/jenkins/.gradle/wrapper/dists/gradle-7.5.1-all/1ehga6e77gqps5uk2kc5kf1vc/gradle-7.5.1/lib/plugins/gradle-testing-base-7.5.1.jar)	
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker	
WARNING: System::setSecurityManager will be removed in a future release	
Tests with failures:	
 - org.elasticsearch.upgrades.SnapshotBasedRecoveryIT.testSnapshotBasedRecovery
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/o3ol7dvdybvbu/tests/:qa:rolling-upgrade:v7.17.8%23upgradedClusterTest/org.elasticsearch.upgrades.SnapshotBasedRecoveryIT/testSnapshotBasedRecovery

**Reproduction line:**
`./gradlew ':qa:rolling-upgrade:v7.17.8#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=99DD5020A91464DB -Dtests.bwc=true -Dtests.locale=uk -Dtests.timezone=America/Curacao -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.SnapshotBasedRecoveryIT&tests.test=testSnapshotBasedRecovery

**Failure excerpt:**
```
org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:41245], URI [/snapshot_based_recovery/_settings], status line [HTTP/1.1 200 OK]
Warnings: [[index.indexing.slowlog.level] setting was deprecated in the previous Elasticsearch release and is removed in this release.]
{"acknowledged":true}

  at __randomizedtesting.SeedInfo.seed([99DD5020A91464DB:703258D83588DF92]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:343)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1609)
  at org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1603)
  at org.elasticsearch.upgrades.SnapshotBasedRecoveryIT.testSnapshotBasedRecovery(SnapshotBasedRecoveryIT.java:103)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by kingherc** [comment]
More failures. One [here](https://gradle-enterprise.elastic.co/s/zqpah2kn34v7s/console-log?task=:qa:rolling-upgrade:v7.17.5%23upgradedClusterTest):

```
:qa:rolling-upgrade:v7.17.5#upgradedClusterTest FAILED
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8

REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.17.5#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=BE3E19BF6CF46EE8 -Dtests.bwc=true -Dtests.locale=es-BO -Dtests.timezone=Pacific/Fiji -Druntime.java=17

org.elasticsearch.upgrades.SnapshotBasedRecoveryIT > testSnapshotBasedRecovery FAILED
    org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:44745], URI [/snapshot_based_recovery/_settings], status line [HTTP/1.1 200 OK]
    Warnings: [[index.indexing.slowlog.level] setting was deprecated in the previous Elasticsearch release and is removed in this release.]
    {"acknowledged":true}
        at __randomizedtesting.SeedInfo.seed([BE3E19BF6CF46EE8:57D11147F068D5A1]:0)
        at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:343)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
        at app//org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1609)
        at app//org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1603)
        at app//org.elasticsearch.upgrades.SnapshotBasedRecoveryIT.testSnapshotBasedRecovery(SnapshotBasedRecoveryIT.java:103)
```

And another one [here](https://gradle-enterprise.elastic.co/s/2wpbohtkyhdp2/console-log?task=:qa:rolling-upgrade:v7.17.8%23upgradedClusterTest):

```


 
--
  | REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.17.8#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=29D88A535EE9A489 -Dtests.bwc=true -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP -Dtests.timezone=America/Indiana/Petersburg -Druntime.java=17 |  
  |   |  
  | org.elasticsearch.upgrades.SnapshotBasedRecoveryIT > testSnapshotBasedRecovery FAILED |  
  | org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:34525], URI [/snapshot_based_recovery/_settings], status line [HTTP/1.1 200 OK] |  
  | Warnings: [[index.indexing.slowlog.level] setting was deprecated in the previous Elasticsearch release and is removed in this release.] |  
  | {"acknowledged":true} |  
  | at __randomizedtesting.SeedInfo.seed([29D88A535EE9A489:C03782ABC2751FC0]:0) |  
  | at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:343) |  
  | at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:313) |  
  | at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) |  
  | at app//org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1609) |  
  | at app//org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1603) |  
  | at app//org.elasticsearch.upgrades.SnapshotBasedRecoveryIT.testSnapshotBasedRecovery(SnapshotBasedRecoveryIT.java:103)

REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.17.8#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=29D88A535EE9A489 -Dtests.bwc=true -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP -Dtests.timezone=America/Indiana/Petersburg -Druntime.java=17	
org.elasticsearch.upgrades.SnapshotBasedRecoveryIT > testSnapshotBasedRecovery FAILED	
    org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:34525/], URI [/snapshot_based_recovery/_settings], status line [HTTP/1.1 200 OK]	
    Warnings: [[index.indexing.slowlog.level] setting was deprecated in the previous Elasticsearch release and is removed in this release.]	
    {"acknowledged":true}	
        at __randomizedtesting.SeedInfo.seed([29D88A535EE9A489:C03782ABC2751FC0]:0)	
        at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:343)	
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)	
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)	
        at app//org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1609)	
        at app//org.elasticsearch.test.rest.ESRestTestCase.updateIndexSettings(ESRestTestCase.java:1603)	
        at app//org.elasticsearch.upgrades.SnapshotBasedRecoveryIT.testSnapshotBasedRecovery(SnapshotBasedRecoveryIT.java:103)
```

**Comment by dimitris-athanasiou** [comment]
Another one [here](https://gradle-enterprise.elastic.co/s/la5gyszsad35o/tests/:qa:rolling-upgrade:v7.17.2%23upgradedClusterTest/org.elasticsearch.upgrades.SnapshotBasedRecoveryIT/testSnapshotBasedRecovery?top-execution=1)

**Comment by luigidellaquila** [comment]
Again [here](https://gradle-enterprise.elastic.co/s/cp43amgcdio2q/tests/:qa:rolling-upgrade:v8.6.0%23oneThirdUpgradedTest/org.elasticsearch.upgrades.SnapshotBasedRecoveryIT/testSnapshotBasedRecovery?top-execution=1)

**Comment by idegtiarenko** [comment]
This is an interesting one.

According to allocation explain added by Francisco the shard replica could be allocated:
``` 
// replica could be allocated here
      "node_id": "_eQKV6ukQSmqPaxYG26XxQ",
      "node_decision": "yes",

// excluded by test
      "node_id": "V7W-GKoBR0q9366uYpriAg",
      "node_decision": "no",
        {
          "decider": "filter",
          "decision": "NO",
          "explanation": "node matches index setting [index.routing.allocation.exclude.] filters [_id:\"V7W-GKoBR0q9366uYpriAg\"]"
        },

// primary is on this node
      "node_id": "7-iN4c0STsOfebKPTpRZNA",
      "node_decision": "no",
        {
          "decider": "same_shard",
          "decision": "NO",
          "explanation": "a copy of this shard is already allocated to this node [[snapshot_based_recovery][0], node[7-iN4c0STsOfebKPTpRZNA], [P], s[STARTED], a[id=v4h-FIixRBW1JZq1ad4jPQ], failed_attempts[0]]"
        },
```

According to the node logs we have:

```
[2022-11-22T09:51:09,628][INFO ][o.e.c.m.MetadataUpdateSettingsService] [v8.6.0-1] updating number_of_replicas to [1] for indices [snapshot_based_recovery]
[2022-11-22T09:51:09,634][DEBUG][o.e.c.r.a.a.DesiredBalanceShardsAllocator] [v8.6.0-1] Executing allocate for [72]
[2022-11-22T09:51:09,634][DEBUG][o.e.c.r.a.a.DesiredBalanceShardsAllocator] [v8.6.0-1] Starting desired balance computation for [72]
[2022-11-22T09:51:09,635][TRACE][o.e.c.r.a.a.DesiredBalanceShardsAllocator] [v8.6.0-1] Reconciling desired balance: DesiredBalance[lastConvergedIndex=71, assignments={...}]
[2022-11-22T09:51:09,637][TRACE][o.e.c.r.a.a.DesiredBalanceShardsAllocator] [v8.6.0-1] Desired balance updated: DesiredBalance[lastConvergedIndex=72, assignments={...}]. Diff: 
[snapshot_based_recovery][0]: ShardAssignment[nodeIds=[V7W-GKoBR0q9366uYpriAg], total=1, unassigned=0, ignored=0] --> ShardAssignment[nodeIds=[V7W-GKoBR0q9366uYpriAg], total=2, unassigned=1, ignored=1]
^^^ balance is computed with a replica that could not be allocated
```

**Comment by DaveCTurner** [comment]
https://gradle-enterprise.elastic.co/s/upxeqpfm7aeei looks like another one

**Comment by albertzaharovits** [comment]
Here are 2 more like this:
```
REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v8.6.0#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=99677DD23946907D -Dtests.bwc=true -Dtests.locale=ar-JO -Dtests.timezone=Etc/GMT -Druntime.java=17

org.elasticsearch.upgrades.SnapshotBasedRecoveryIT > testSnapshotBasedRecovery FAILED
    java.lang.AssertionError: timed out waiting for green state for index [snapshot_based_recovery] cluster state [{
```
https://gradle-enterprise.elastic.co/s/zhh2paid6jwbw
https://gradle-enterprise.elastic.co/s/6ba7vu2dtfs4c

and 2 more like this:
```
./gradlew ':qa:rolling-upgrade:v7.17.8#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=C2D24F9EBD9CC902 -Dtests.bwc=true -Dtests.locale=en-GB -Dtests.timezone=SystemV/CST6CDT -Druntime.java=17
```
https://gradle-enterprise.elastic.co/s/yg6nok2vzzynw
https://gradle-enterprise.elastic.co/s/djpo7ccaygfji

I'm going to raise a mute test PR and leave it up to you @idegtiarenko .

**Comment by slobodanadamovic** [comment]
This test failed recently on [8.5](https://gradle-enterprise.elastic.co/s/q44r7te3vzjda/tests/:qa:rolling-upgrade:v7.17.8%23twoThirdsUpgradedTest/org.elasticsearch.upgrades.SnapshotBasedRecoveryIT/testSnapshotBasedRecovery) and [8.6](https://gradle-enterprise.elastic.co/s/rb76j65b7pb56/tests/:qa:rolling-upgrade:v7.17.8%23twoThirdsUpgradedTest/org.elasticsearch.upgrades.SnapshotBasedRecoveryIT/testSnapshotBasedRecovery?top-execution=1) branches. I backported the test [mute](https://github.com/elastic/elasticsearch/issues/91383#:~:text=Mute%20SnapshotBasedRecoveryIT%20testSnapshotBasedRecovery%20%2391847) to these branches as well.

**Comment by joegallo** [comment]
Another one like the one that `@DaveCTurner` reported https://gradle-enterprise.elastic.co/s/vae2nxo2dfekg/tests/:qa:rolling-upgrade:v7.17.8%23twoThirdsUpgradedTest/org.elasticsearch.upgrades.RecoveryIT/testRecoveryWithConcurrentIndexing?top-execution=1.

**Comment by ywangd** [comment]
Another one For RecoveryIT https://gradle-enterprise.elastic.co/s/w7r7bhxmrd3og/tests/:qa:rolling-upgrade:v7.17.9%23twoThirdsUpgradedTest/org.elasticsearch.upgrades.RecoveryIT/testRecoveryWithConcurrentIndexing?expanded-stacktrace=WyIwIl0&top-execution=1
