### ISSUE TITLE
DataTierAllocationDeciderIT timeout exceeded

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#91393]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.5+multijob+platform-support-windows/GRADLE_TASK=checkPart2,os=windows-2012-r2/94/consoleFull

### Repro line

REPRODUCE WITH: gradlew ':x-pack:plugin:core:internalClusterTest' --tests "org.elasticsearch.xpack.cluster.routing.allocation.DataTierAllocationDeciderIT.testDesiredNodesAreTakenIntoAccountInAutoExpandReplicas" -Dtests.seed=7876FABCDE9E28A4 -Dtests.locale=hi -Dtests.timezone=US/Mountain -Druntime.java=19

### Does it reproduce?

Didn't try

### Applicable branches

8.5

### Failure excerpt

Too long.

```
02:52:16 REPRODUCE WITH: gradlew ':x-pack:plugin:core:internalClusterTest' --tests "org.elasticsearch.xpack.cluster.routing.allocation.DataTierAllocationDeciderIT.testDesiredNodesAreTakenIntoAccountInAutoExpandReplicas" -Dtests.seed=7876FABCDE9E28A4 -Dtests.locale=hi -Dtests.timezone=US/Mountain -Druntime.java=19
02:52:16 
02:52:16 org.elasticsearch.xpack.cluster.routing.allocation.DataTierAllocationDeciderIT > classMethod FAILED
02:52:16     java.lang.Exception: Suite timeout exceeded (>= 2400000 msec).
02:52:16         at __randomizedtesting.SeedInfo.seed([7876FABCDE9E28A4]:0)
```

**Comment by fcofdez** [comment]
It looks like an assertion related to allocation is tripping in one of the latest [failures](https://gradle-enterprise.elastic.co/s/6aumw7ezssi3a):
```
        Caused by:
        java.lang.AssertionError: double-initializing [.enrich-my-policy0-1668773917218][0], node[null], [R], recovery_source[peer recovery], s[UNASSIGNED], unassigned_info[[reason=REPLICA_ADDED], at[2022-11-18T12:18:37.688Z], delayed=false, allocation_status[no_attempt]], failed_attempts[0] to 1EA5L71cRPuG8NKYyUfBQA and [.enrich-my-policy0-1668773917218][0], node[SKbralgVQAa1DsC6hvAUQQ], [R], recovery_source[peer recovery
], s[INITIALIZING], a[id=3zEcDhuhSyCVrIXRM9qrtQ], unassigned_info[[reason=REPLICA_ADDED], at[2022-11-18T12:18:37.688Z], delayed=false, allocation_status[no_attempt]], failed_attempts[0]
            at __randomizedtesting.SeedInfo.seed([CFA329E7A925FA7F]:0)
            at org.elasticsearch.cluster.routing.allocation.GatewayAllocatorObserver.shardInitialized(GatewayAllocatorObserver.java:28)
            at org.elasticsearch.cluster.routing.RoutingChangesObserver$DelegatingRoutingChangesObserver.shardInitialized(RoutingChangesObserver.java:78)
            at org.elasticsearch.cluster.routing.RoutingNodes.initializeShard(RoutingNodes.java:437)
            at org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceReconciler.allocateUnassigned(DesiredBalanceReconciler.java:226)
            at org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceReconciler.run(DesiredBalanceReconciler.java:80)
            at org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceShardsAllocator.recordTime(DesiredBalanceShardsAllocator.java:304)
            at org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceShardsAllocator.reconcile(DesiredBalanceShardsAllocator.java:213)
            at org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceShardsAllocator$ReconcileDesiredBalanceExecutor.lambda$applyBalance$1(DesiredBalanceShardsAllocator.java:282)
            at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:522)
            at org.elasticsearch.cluster.routing.allocation.AllocationService.executeWithRoutingAllocation(AllocationService.java:444)
            at org.elasticsearch.cluster.ClusterModule.reconcile(ClusterModule.java:149)
            at org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceShardsAllocator$ReconcileDesiredBalanceExecutor.applyBalance(DesiredBalanceShardsAllocator.java:280)
            at org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceShardsAllocator$ReconcileDesiredBalanceExecutor.execute(DesiredBalanceShardsAllocator.java:266)
            at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1052)
            at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1017)
            at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:278)
            at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170)
            at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)
            at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:850)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
            at java.base/java.lang.Thread.run(Thread.java:833)
```
cc @idegtiarenko @DaveCTurner

**Comment by slobodanadamovic** [comment]
This issue occurred again today: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.5+multijob+platform-support-windows/GRADLE_TASK=checkPart2,os=windows-2016/137/consoleFull


```
REPRODUCE WITH: gradlew ':x-pack:plugin:core:internalClusterTest' --tests "org.elasticsearch.xpack.cluster.routing.allocation.DataTierAllocationDeciderIT.testDesiredNodesAreTakenIntoAccountInAutoExpandReplicas" -Dtests.seed=DCEE9C82A2657651 -Dtests.locale=ar-YE -Dtests.timezone=Pacific/Honolulu -Druntime.java=19

org.elasticsearch.xpack.cluster.routing.allocation.DataTierAllocationDeciderIT > testDesiredNodesAreTakenIntoAccountInAutoExpandReplicas FAILED
    java.lang.Exception: Test abandoned because suite timeout was reached.
        at __randomizedtesting.SeedInfo.seed([DCEE9C82A2657651]:0)

REPRODUCE WITH: gradlew ':x-pack:plugin:core:internalClusterTest' --tests "org.elasticsearch.xpack.cluster.routing.allocation.DataTierAllocationDeciderIT.testDesiredNodesAreTakenIntoAccountInAutoExpandReplicas" -Dtests.seed=DCEE9C82A2657651 -Dtests.locale=ar-YE -Dtests.timezone=Pacific/Honolulu -Druntime.java=19

org.elasticsearch.xpack.cluster.routing.allocation.DataTierAllocationDeciderIT > classMethod FAILED
    java.lang.Exception: Suite timeout exceeded (>= 2400000 msec).
        at __randomizedtesting.SeedInfo.seed([DCEE9C82A2657651]:0)
```

**Comment by fcofdez** [comment]
I think this was solved by https://github.com/elastic/elasticsearch/pull/92837. I'm closing it by now and we can reopen it if the failures surface again.
