### ISSUE TITLE
7.17 bwc test with 7.4.2 fails due to min_version field

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#91394]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.17+periodic+bwc/BWC_VERSION=7.4.2,nodes=general-purpose/980/consoleFull

### Repro line

Multiple reproduction lines

### Does it reproduce?

Didn't try

### Applicable branches

7.17

### Failure excerpt

```
06:15:16 REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v7.4.2#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=snapshot.create/10_basic/Create a snapshot for missing index}" -Dtests.seed=534B638032355ED4 -Dtests.bwc=true -Dtests.locale=en-AU -Dtests.timezone=Asia/Ujung_Pandang -Druntime.java=8
06:15:16 
06:15:16 org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search/330_fetch_fields/Test nested fields with ignored subfields} FAILED
06:15:16     org.junit.AssumptionViolatedException: [search/330_fetch_fields] skipped, reason: [the 'fields' parameter was added in 7.10]
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedTest.assumeTrue(RandomizedTest.java:745)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedTest.assumeFalse(RandomizedTest.java:753)
06:15:16         at org.apache.lucene.util.LuceneTestCase.assumeFalse(LuceneTestCase.java:884)
06:15:16         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:399)
06:15:16         at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
06:15:16         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:15:16         at java.lang.reflect.Method.invoke(Method.java:498)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
06:15:16         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
06:15:16         at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
06:15:16         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
06:15:16         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
06:15:16         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
06:15:16         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
06:15:16         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
06:15:16         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
06:15:16         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
06:15:16         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
06:15:16         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
06:15:16         at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
06:15:16         at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
06:15:16         at java.lang.Thread.run(Thread.java:748)
06:15:16 
06:15:16     org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:43773/], URI [/_snapshot/test_repo_create_1/_all?ignore_unavailable=true], status line [HTTP/1.1 400 Bad Request]
06:15:16     {"error":{"root_cause":[{"type":"parse_exception","reason":"unknown field name  [min_version]"}],"type":"parse_exception","reason":"unknown field name  [min_version]"},"status":400}
06:15:16         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
06:15:16         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
06:15:16         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
06:15:16         at org.elasticsearch.test.rest.ESRestTestCase.wipeSnapshots(ESRestTestCase.java:1010)
06:15:16         at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:658)
06:15:16         at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:384)
06:15:16         at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
06:15:16         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:15:16         at java.lang.reflect.Method.invoke(Method.java:498)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
06:15:16         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
06:15:16         at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
06:15:16         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
06:15:16         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
06:15:16         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
06:15:16         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
06:15:16         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
06:15:16         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
06:15:16         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
06:15:16         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
06:15:16         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
06:15:16         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
06:15:16         at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
06:15:16         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
06:15:16         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
06:15:16         at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
06:15:16         at java.lang.Thread.run(Thread.java:748)
06:15:16 REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v7.4.2#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search/330_fetch_fields/Test nested fields with ignored subfields}" -Dtests.seed=534B638032355ED4 -Dtests.bwc=true -Dtests.locale=en-AU -Dtests.timezone=Asia/Ujung_Pandang -Druntime.java=8
06:15:16
```

**Comment by kingherc** [comment]
Also similar failures for 7.1.0 bwc, see details [here](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.17+periodic+bwc/BWC_VERSION=7.1.0,nodes=general-purpose/981/console).

**Comment by kingherc** [comment]
I've been looking at this. I cannot reproduce it, unfortunately the logs are gone, and there has not been a similar failure.

Since there were many failures, I assume something went bad with the repository as a fluke somehow.

Judging from the stacktrace, it seems to fail at this spot of the code:

```
                if (INCOMPATIBLE_SNAPSHOTS.equals(currentFieldName)) {
                    if (parser.nextToken() == XContentParser.Token.START_ARRAY) {
                        while (parser.nextToken() != XContentParser.Token.END_ARRAY) {
                            incompatibleSnapshotIds.add(snapshotIdFromXContent(parser));
                        }
                    } else {
                        throw new ElasticsearchParseException("expected array for [" + currentFieldName + "]");
                    }
                } else {
                    throw new ElasticsearchParseException("unknown field name  [" + currentFieldName + "]"); // this errs
                }
```

during the cleanup of the repository during `org.elasticsearch.test.rest.ESRestTestCase#wipeCluster()`.

This means that the cleanup actually found an `incompatible-snapshots` blob and the first field of that json was `min_version` instead of `incompatible-snapshots`. I cannot understand how this could have happened at all. I am not familiar with the concept of these older incompatible snapshots. But I do not find any code that could write such a blob in 7.17 and I also see that the code that wrote this blob was removed in https://github.com/elastic/elasticsearch/pull/44096 (labelled 7.4.0 and done through [this backport PR](https://github.com/elastic/elasticsearch/pull/44183)), so it should not have existed in 7.4.2 that this tests with. From all of this, I understand that possibly the repository was inconsistent already when the tests started to run. Maybe some other concurrent bwc test with an older version (that actually wrote incompatible snapshots) run before and failed to clean up. Rather than this being an actual bug. I think I will close this and if it re-appears, we can handle this. Please feel free to raise concerns if you think there's something more to investigate here, cc @original-brownbear .

**Comment by kingherc** [comment]
Found new 7.17 instance at https://gradle-enterprise.elastic.co/s/ha4hcjs72lx5i

```
:qa:mixed-cluster:v7.2.0#mixedClusterTest FAILED
Test cluster endpoints are: [::1]:39369,127.0.0.1:37627,[::1]:45137,127.0.0.1:33195,[::1]:41527,127.0.0.1:36597,[::1]:43193,127.0.0.1:37463
Upgrading one node to create a mixed cluster
Upgrade complete, endpoints are: [::1]:41529,127.0.0.1:34211,[::1]:45137,127.0.0.1:33195,[::1]:41527,127.0.0.1:36597,[::1]:43193,127.0.0.1:37463
Upgrading another node to create a mixed cluster
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8


org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=snapshot.create/10_basic/Create a snapshot for missing index} FAILED
    java.lang.AssertionError: Failure at [snapshot.create/10_basic:114]: expected [2xx] status code but api [snapshot.delete] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"parse_exception","reason":"unknown field name  [min_version]","stack_trace":"ElasticsearchParseException[unknown field name  [min_version]]\n\tat org.elasticsearch.repositories.RepositoryData.snapshotsFromXContent(RepositoryData.java:444)\n\tat org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:657)\n\tat org.elasticsearch.snapshots.SnapshotsService.deleteSnapshot(SnapshotsService.java:1098)\n\tat org.elasticsearch.action.admin.cluster.snapshots.delete.TransportDeleteSnapshotAction.masterOperation(TransportDeleteSnapshotAction.java:70)\n\tat org.elasticsearch.action.admin.cluster.snapshots.delete.TransportDeleteSnapshotAction.masterOperation(TransportDeleteSnapshotAction.java:39)\n\tat org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:127)\n\tat org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.doRun(TransportMasterNodeAction.java:200)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.lang.Thread.run(Thread.java:835)\n"}],"type":"parse_exception","reason":"unknown field name  [min_version]","stack_trace":"ElasticsearchParseException[unknown field name  [min_version]]\n\tat org.elasticsearch.repositories.RepositoryData.snapshotsFromXContent(RepositoryData.java:444)\n\tat org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:657)\n\tat org.elasticsearch.snapshots.SnapshotsService.deleteSnapshot(SnapshotsService.java:1098)\n\tat org.elasticsearch.action.admin.cluster.snapshots.delete.TransportDeleteSnapshotAction.masterOperation(TransportDeleteSnapshotAction.java:70)\n\tat org.elasticsearch.action.admin.cluster.snapshots.delete.TransportDeleteSnapshotAction.masterOperation(TransportDeleteSnapshotAction.java:39)\n\tat org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:127)\n\tat org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.doRun(TransportMasterNodeAction.java:200)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.lang.Thread.run(Thread.java:835)\n"},"status":400}]
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:482)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:455)
        at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.AssertionError: expected [2xx] status code but api [snapshot.delete] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"parse_exception","reason":"unknown field name  [min_version]","stack_trace":"ElasticsearchParseException[unknown field name  [min_version]]\n\tat org.elasticsearch.repositories.RepositoryData.snapshotsFromXContent(RepositoryData.java:444)\n\tat org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:657)\n\tat org.elasticsearch.snapshots.SnapshotsService.deleteSnapshot(SnapshotsService.java:1098)\n\tat org.elasticsearch.action.admin.cluster.snapshots.delete.TransportDeleteSnapshotAction.masterOperation(TransportDeleteSnapshotAction.java:70)\n\tat org.elasticsearch.action.admin.cluster.snapshots.delete.TransportDeleteSnapshotAction.masterOperation(TransportDeleteSnapshotAction.java:39)\n\tat org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:127)\n\tat org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.doRun(TransportMasterNodeAction.java:200)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.lang.Thread.run(Thread.java:835)\n"}],"type":"parse_exception","reason":"unknown field name  [min_version]","stack_trace":"ElasticsearchParseException[unknown field name  [min_version]]\n\tat org.elasticsearch.repositories.RepositoryData.snapshotsFromXContent(RepositoryData.java:444)\n\tat org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:657)\n\tat org.elasticsearch.snapshots.SnapshotsService.deleteSnapshot(SnapshotsService.java:1098)\n\tat org.elasticsearch.action.admin.cluster.snapshots.delete.TransportDeleteSnapshotAction.masterOperation(TransportDeleteSnapshotAction.java:70)\n\tat org.elasticsearch.action.admin.cluster.snapshots.delete.TransportDeleteSnapshotAction.masterOperation(TransportDeleteSnapshotAction.java:39)\n\tat org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:127)\n\tat org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.doRun(TransportMasterNodeAction.java:200)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.lang.Thread.run(Thread.java:835)\n"},"status":400}]
            at org.junit.Assert.fail(Assert.java:88)
            at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:375)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:471)
            ... 38 more

    org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:43077], URI [/_snapshot/test_repo_create_1/_all?ignore_unavailable=true], status line [HTTP/1.1 400 Bad Request]
    {"error":{"root_cause":[{"type":"parse_exception","reason":"unknown field name  [min_version]"}],"type":"parse_exception","reason":"unknown field name  [min_version]"},"status":400}
```

Attaching whole log file so it's not lost: 
[ha4hcjs72lx5i-console-log.zip](https://github.com/elastic/elasticsearch/files/10696217/ha4hcjs72lx5i-console-log.zip)

**Comment by fcofdez** [comment]
Another instance of this https://gradle-enterprise.elastic.co/s/4lb6oos4ckqdg

**Comment by slobodanadamovic** [comment]
Another one today: https://gradle-enterprise.elastic.co/s/3wicoilisquf2

**Comment by luigidellaquila** [comment]
Another one today https://gradle-enterprise.elastic.co/s/hd47ryhpg3jtg/tests/:qa:mixed-cluster:v7.3.0%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=snapshot.create%2F10_basic%2FCreate%20a%20snapshot%20for%20missing%20index%7D
