### ISSUE TITLE
Multiple PyTorchModelIT tests failed in 8.5 in single processor mode

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#91422]
### CI Link

https://gradle-enterprise.elastic.co/s/odf7hayhkpbts/console-log?task=:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest

### Repro line

See below

### Does it reproduce?

Didn't try

### Applicable branches

8.5

### Failure excerpt

```
Tests with failures:
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testStoppingDeploymentShouldTriggerRebalance
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testGetDeploymentStats_WithStartedStoppedDeployments
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testDeleteFailureDueToDeployment
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testGetDeploymentStats_WithWildcard
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluateWithResultFieldOverride
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testNotifications
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluate
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testTruncation
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testLiveDeploymentStats
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testFailedDeploymentStats
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testPipelineWithBadProcessor
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testStopUsedDeploymentByIngestProcessor
 - org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testDeploymentStats
 - org.elasticsearch.xpack.ml.integration.TestFeatureResetIT.testMLFeatureResetWithModelDeployment

273 tests completed, 14 failed, 4 skipped
```

e.g.,

```
:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest FAILED
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testStoppingDeploymentShouldTriggerRebalance" -Dtests.seed=C5A28319B7703BDF -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=it-IT -Dtests.timezone=Europe/Oslo -Druntime.java=17

org.elasticsearch.xpack.ml.integration.PyTorchModelIT > testStoppingDeploymentShouldTriggerRebalance FAILED
    java.lang.AssertionError: 
    Expected: <1>
         but: was <0>
        at __randomizedtesting.SeedInfo.seed([C5A28319B7703BDF:95DB58D96EEC0ADE]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.PyTorchModelIT.assertAllocationCount(PyTorchModelIT.java:887)
        at org.elasticsearch.xpack.ml.integration.PyTorchModelIT.lambda$testStoppingDeploymentShouldTriggerRebalance$14(PyTorchModelIT.java:769)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1105)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1078)
        at org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testStoppingDeploymentShouldTriggerRebalance(PyTorchModelIT.java:769)

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testGetDeploymentStats_WithStartedStoppedDeployments" -Dtests.seed=C5A28319B7703BDF -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=it-IT -Dtests.timezone=Europe/Oslo -Druntime.java=17

org.elasticsearch.xpack.ml.integration.PyTorchModelIT > testGetDeploymentStats_WithStartedStoppedDeployments FAILED
    org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:39557], URI [/_ml/trained_models/foo/deployment/_start?timeout=40s&wait_for=fully_allocated&threads_per_allocation=1&number_of_allocations=1], status line [HTTP/1.1 408 Request Timeout]
    {"error":{"root_cause":[{"type":"status_exception","reason":"Starting deployment timed out after [40s]"}],"type":"status_exception","reason":"Starting deployment timed out after [40s]"},"status":408}
        at __randomizedtesting.SeedInfo.seed([C5A28319B7703BDF:D53DE8A4DD8FCE3D]:0)
        at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
        at app//org.elasticsearch.xpack.ml.integration.PyTorchModelIT.startDeployment(PyTorchModelIT.java:960)
        at app//org.elasticsearch.xpack.ml.integration.PyTorchModelIT.startDeployment(PyTorchModelIT.java:944)
        at app//org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testGetDeploymentStats_WithStartedStoppedDeployments(PyTorchModelIT.java:442)
```

**Comment by davidkyle** [comment]
Another failure also 8.5: https://gradle-enterprise.elastic.co/s/wpmlr6uztg5vo

**Comment by ywangd** [comment]
Another on 8.5 https://gradle-enterprise.elastic.co/s/pjmvmwbsjpiay/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.PyTorchModelIT/testNotifications?top-execution=1

**Comment by dimitris-athanasiou** [comment]
This should now be fixed
