### ISSUE TITLE
[CI] ReplicaShardAllocatorSyncIdIT testFullClusterRestartPerformNoopRecovery failing

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#91451]
**Build scan:**
https://gradle-enterprise.elastic.co/s/grzpzxi26hddo/tests/:server:internalClusterTest/org.elasticsearch.gateway.ReplicaShardAllocatorSyncIdIT/testFullClusterRestartPerformNoopRecovery

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.gateway.ReplicaShardAllocatorSyncIdIT.testFullClusterRestartPerformNoopRecovery" -Dtests.seed=E03B2E3EB3A43343 -Dtests.locale=vi -Dtests.timezone=MST -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gateway.ReplicaShardAllocatorSyncIdIT&tests.test=testFullClusterRestartPerformNoopRecovery

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[file (name [_0.cfe], reused [false], length [672], recovered [672], recovered from snapshot [0]) , file (name [_0.si], reused [false], length [346], recovered [346], recovered from snapshot [0]) , file (name [_0.cfs], reused [false], length [10341], recovered [10341], recovered from snapshot [0]) , file (name [segments_5], reused [false], length [355], recovered [355], recovered from snapshot [0]) ]>

  at __randomizedtesting.SeedInfo.seed([E03B2E3EB3A43343:998B3C7B62A07E0]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.gateway.ReplicaShardAllocatorSyncIdIT.assertNoOpRecoveries(ReplicaShardAllocatorSyncIdIT.java:351)
  at org.elasticsearch.gateway.ReplicaShardAllocatorSyncIdIT.testFullClusterRestartPerformNoopRecovery(ReplicaShardAllocatorSyncIdIT.java:279)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by pxsalehi** [comment]
Some more reproduction: https://gradle-enterprise.elastic.co/s/n5sbx7s23mde6

**Comment by joegallo** [comment]
https://gradle-enterprise.elastic.co/s/zkuld54oafdga

**Comment by DaveCTurner** [comment]
Reproduces for me locally within a few hundred iterations.

**Comment by ywangd** [comment]
I just got a intake [CI failure](https://gradle-enterprise.elastic.co/s/mgsrjxjofv4fu/tests/:server:internalClusterTest/org.elasticsearch.gateway.ReplicaShardAllocatorIT/testFullClusterRestartPerformNoopRecovery) for a method with exact same name but in a different test class. It is `ReplicaShardAllocatorIT.testFullClusterRestartPerformNoopRecovery` instead of `ReplicaShardAllocatorSyncIdIT. testFullClusterRestartPerformNoopRecovery`. The error message is also similar enough. So I assume they are caused by the same underlying issue.
