### ISSUE TITLE
[CI] UberModuleClassLoaderTests failing

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#91609]
### CI Link

https://gradle-enterprise.elastic.co/s/jfyygdphnhmu6

### Repro line

./gradlew ':server:test' --tests "org.elasticsearch.plugins.UberModuleClassLoaderTests" -Dtests.seed=A39D03284C84C6A2 -Dtests.locale=en-US -Dtests.timezone=Atlantic/Reykjavik -Druntime.java=19

### Does it reproduce?

No

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.plugins.UberModuleClassLoaderTests&tests.test=classMethod

### Failure excerpt

```
  2> java.io.IOException: Could not remove the following files (in the order of attempts):
       C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001\libs-002: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001\libs-002
       C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001\libs-002\parent.jar: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001\libs-002\parent.jar
       C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001\libs-002\optional.jar: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001\libs-002\optional.jar
       C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001\libs-002\modular.jar: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001\libs-002\modular.jar
       C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001\libs-002\non-modular.jar: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001\libs-002\non-modular.jar
       C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\479\server\build\testrun\test\temp\org.elasticsearch.plugins.UberModuleClassLoaderTests_A39D03284C84C6A2-001
        at __randomizedtesting.SeedInfo.seed([A39D03284C84C6A2]:0)
        at org.apache.lucene.util.IOUtils.rm(IOUtils.java:341)
        at org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:209)
        at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1589)
  2> REPRODUCE WITH: gradlew ':server:test' --tests "org.elasticsearch.plugins.UberModuleClassLoaderTests" -Dtests.seed=A39D03284C84C6A2 -Dtests.locale=en-US -Dtests.timezone=Atlantic/Reykjavik -Druntime.java=19
  2> NOTE: test params are: codec=Lucene94, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=sq-AL, timezone=Asia/Manila
  2> NOTE: Windows Server 2012 R2 6.3 amd64/Oracle Corporation 19.0.1 (64-bit)/cpus=32,threads=1,free=331172344,total=536870912
```

**Comment by luigidellaquila** [comment]
This keeps failing and seems to be Windows-specific

**Comment by thecoop** [comment]
Windows is a lot more picky about deleting files - Linux lets you delete files that have open handles on them, Windows does not.

**Comment by thecoop** [comment]
There's no open handles for those files during cleanup on a linux system, something really odd is going on here.

**Comment by n1v0lg** [comment]
More failures today: https://gradle-enterprise.elastic.co/s/lv6cbblo7magu

**Comment by thecoop** [comment]
I've been unable to reproduce this on a windows VM so far...

**Comment by valeriy42** [comment]
Another failure here https://gradle-enterprise.elastic.co/s/epvcq7zatnlys

**Comment by slobodanadamovic** [comment]
This failed again and it looks like the same issue as in https://github.com/elastic/elasticsearch/issues/88275 - which was solved by disabling the cache for JAR URLConnections (https://github.com/elastic/elasticsearch/pull/88586).

**Comment by williamrandolph** [comment]
Looks like I introduced this in #91217. I don't see an obvious spot to disable the jar cache but I'll take another look tomorrow.

**Comment by craigtaverner** [comment]
This morning this failed several times, and the test history claims it fails 100% of the time over the last seven days (39 failures over 39 runs): https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Stockholm&tests.container=org.elasticsearch.plugins.UberModuleClassLoaderTests&tests.test=classMethod

**Comment by joegallo** [comment]
https://gradle-enterprise.elastic.co/s/iif2bt34tmxgs/tests/:server:test/org.elasticsearch.plugins.UberModuleClassLoaderTests/classMethod?top-execution=1

**Comment by albertzaharovits** [comment]
Two more failures today:
https://gradle-enterprise.elastic.co/s/jqtnpbyymo522
https://gradle-enterprise.elastic.co/s/ch54gifxmy2c4

I'm hesitant to mute because it only fails on Win, whle the whole suite class ought to get muted but there are many tests in the class.

**Comment by williamrandolph** [comment]
I should check whether this fix helped here: https://github.com/elastic/elasticsearch/pull/92096

**Comment by williamrandolph** [comment]
I think I've tracked down where the problem is. For context, these tests were added in https://github.com/elastic/elasticsearch/pull/91217. That PR concerns the case where a jar can have a compile-time dependency on some service provider. When constructing the module graph, the UberModuleClassLoader should only declare that the synthetic module `uses` that service if the service is present at runtime; otherwise there will be an error.

In order to test this, I created a parent module layer that contains a required dependency and an optional dependency, then tested that the synthetic module can use SPI in either case. But it looks like there's a resource leak in the JDK module code for this kind of `ModuleLayer`: the classloader for jar-based modules (`jdk.internal.loader.Loader`) opens a `ModuleReader` in `findResource` and `defineClass` but never closes it, and on Windows this will prevent resource cleanup.

`ModuleLayer` and `Loader` are not closeable, so unless there's a JDK fix coming soon, I'm going to have to find some other way to test this scenario.
