### ISSUE TITLE
[CI] MinimumMasterNodesIT testThreeNodesNoMasterBlock failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#91639]
**Build scan:**
https://gradle-enterprise.elastic.co/s/txfitri4deo3w/tests/:server:internalClusterTest/org.elasticsearch.cluster.MinimumMasterNodesIT/testThreeNodesNoMasterBlock

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.MinimumMasterNodesIT.testThreeNodesNoMasterBlock" -Dtests.seed=BD2F4F716FC43ED -Dtests.locale=et-EE -Dtests.timezone=Asia/Atyrau -Druntime.java=17
```

**Applicable branches:**
8.5

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.cluster.MinimumMasterNodesIT&tests.test=testThreeNodesNoMasterBlock

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=559, name=elasticsearch[node_t0][generic][T#1], state=RUNNABLE, group=TGRP-MinimumMasterNodesIT]

  at __randomizedtesting.SeedInfo.seed([BD2F4F716FC43ED:5F4513F87DCE6BA3]:0)

  Caused by: java.lang.AssertionError: (No message provided)

    at __randomizedtesting.SeedInfo.seed([BD2F4F716FC43ED]:0)
    at org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:50)
    at org.elasticsearch.common.bytes.ReleasableBytesReference.close(ReleasableBytesReference.java:92)
    at org.elasticsearch.action.ActionListener$RunBeforeActionListener.onFailure(ActionListener.java:421)
    at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:92)
    at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:92)
    at org.elasticsearch.action.ActionListener$RunBeforeActionListener.onFailure(ActionListener.java:425)
    at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:92)
    at org.elasticsearch.action.ActionListener$RunBeforeActionListener.onFailure(ActionListener.java:425)
    at org.elasticsearch.action.support.RetryableAction.cancel(RetryableAction.java:88)
    at org.elasticsearch.indices.recovery.RemoteRecoveryTargetHandler.lambda$cancel$16(RemoteRecoveryTargetHandler.java:327)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:825)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by original-brownbear** [comment]
There is a real double free bug here it seems. We appear to be resolving a listener twice during retrying + cancelling a recovery. Hunting it down now.

**Comment by original-brownbear** [comment]
Back I looked into this I made some safety adjustments to how the ref counting is handled in this code, I can't see any more possible failure paths, could never reproduce this and the exact failure seen here only ever happened once.
-> closing this
