### ISSUE TITLE
SetProcessor should prevent user from setting an id longer than 512 bytes

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#91777]
### Description

[IndexRequest](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/index/IndexRequest.java#L226) prevents users from setting a document ID more than 512 bytes long because it is not possible to do a get request with an ID that is longer. However users can bypass this by using the SetProcessor like:
```
PUT _ingest/pipeline/test
{
  "processors": [
    {
      "set": {
        "field": "_id",
        "value": "Some_Server_name.thisisareallylongthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamethisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamethisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeat"
      }
    }
  ]
}
```
The SetProcessor ought to throw an exception in this case.
Relates to #16034

**Comment by HiDAl** [comment]
I've created a PR (#91884) which fix this bug, but, sadly, this is breaking change. Basically, the PR adds a change that during the creation of the `SetProcessor`, in case the set is for the `_id` field, it validates that its value is shorter than 512. The problem with validating this scenario during the creation of the processor is that it makes unable to migrate to a newer version. 

### Example
1. a cluster with the old version has a pipeline with a set processor updating the `_id` to a long string
2. user update to the newer version and starts the cluster
3. the cluster loads and validates the stored pipeline in the cluster metadata
4. Since the processor is invalid, ES is unable of start, failing with the following error:

```bash
[...]
[2022-11-24T11:38:09,127][WARN ][o.e.i.IngestService      ] [Pablos-MBP.home] failed to update ingest pipelinesorg.elasticsearch.ElasticsearchParseException: [value] _id [Some_Server_name.thisisareallylongthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamethisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamethisisareallylongsoftwarenamerepeatedthisisareallylongsoftwarenamerepeat] is too long, must not be longer than 512 bytes but was: 904
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.ingest.ConfigurationUtils.newConfigurationException(ConfigurationUtils.java:449)
	at org.elasticsearch.ingest.common@8.7.0-SNAPSHOT/org.elasticsearch.ingest.common.SetProcessor$Factory.create(SetProcessor.java:125)
	at org.elasticsearch.ingest.common@8.7.0-SNAPSHOT/org.elasticsearch.ingest.common.SetProcessor$Factory.create(SetProcessor.java:99)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:595)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:559)

See logs for more details.
[...]
```

we have to discuss as a team what's the best approach to fix this issue.

**Comment by HiDAl** [comment]
There's another not considered scenario, which derives from this issue:

Right now it's possible to create a pipeline like the following:

```json
{
  "processors": [
    {
      "set": {
        "field": "_id",
        "copy_from": "long-key"
      }
    }
  ]
}

{
  "processors": [
    {
      "set": {
        "field": "_id",
        "value": "{{{long-key}}}"
      }
    }
  ]
}
```

These examples are not possible of capture during the creation of the pipeline, since we don't know before hand what is going to be the length of the field value, so, we have to validate during the execution of the pipeline that this step is generating an invalid (?) value for the `_id` field. 

I've tried these scenarios with the following snippets:

```bash
POST {{ES}}/data-stream/_doc?pipeline=copy_from

{
    "long-key": "COPY_FROM::really-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-id"
}

{
  "_index": "data-stream",
  "_id": "COPY_FROM::really-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-id",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "_seq_no": 0,
  "_primary_term": 1
}

###
POST {{ES}}/data-stream/_doc?pipeline=template-value

{
    "long-key": "really-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-id"
}

{
  "_index": "data-stream",
  "_id": "really-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-id",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "_seq_no": 1,
  "_primary_term": 1
}

###
GET {{ES}}/data-stream/_search

{
  "took": 81,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": 1.0,
    "hits": [
      {
        "_index": "data-stream",
        "_id": "COPY_FROM::really-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-id",
        "_score": 1.0,
        "_ignored": [
          "long-key.keyword"
        ],
        "_source": {
          "long-key": "COPY_FROM::really-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-id"
        }
      },
      {
        "_index": "data-stream",
        "_id": "really-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-id",
        "_score": 1.0,
        "_ignored": [
          "long-key.keyword"
        ],
        "_source": {
          "long-key": "really-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-idreally-really-long-id"
        }
      }
    ]
  }
}
```

Should I create 1 or 2 tickets for these cases? Basically, they are the same case, but with different ways of reach it, so my guess is 1 ticket

**Comment by HiDAl** [comment]
Thinking a bit more about the issue and potential solutions I came up with the following, which I know is not the best one, but at least it would cover the 3 exposed scenarios of this issue:

what about make the pipeline to fail during the execution of this step, instead of during the creation? it has the pitfall that customers will still have the option of create a `set _id to long-string` step, but it'd resolve the issue for all the 3 cases. We might roll this up in steps like:

1. allow the creation of the non-valid step, maybe displaying a warning during the creation (I've no idea whether this is possible or not to show a warning)
2. indicate in the documentation that this warning will become an error in forthcoming versions
3. after a set of releases (release 9? release 8.[>6]?), make impossible the creation of this step

**Comment by dakrone** [comment]
> what about make the pipeline to fail during the execution of this step, instead of during the creation?

Hmm.. we already have validation for extremely long IDs, I take it that validation is running *before* the index pipelines, so it's not catching these issues. I wonder if we should change all of the validation to run on the requests after ingest pipelines, to catch other problems (like setting `_source` to null, or changing op type with invalid versions. However, that might be too much of a breaking change depending on how it affects the response.

I also think we'll have to handle it generically during execution, rather than creation, because there will always be some programmatic way of setting it larger than 512 bytes (a script processor, for example).

**Comment by HiDAl** [comment]
> we already have validation for extremely long IDs, I take it that validation is running before the index pipelines, so it's not catching these issues.

Yes, we do have it. I'm not very familiar with the index pipeline, but does make sense what you say. 

>  I wonder if we should change all of the validation to run on the requests after ingest pipelines
Do you mean "apply the steps to the documents and then validate that the out document is _valid_"?

**Comment by dakrone** [comment]
> Do you mean "apply the steps to the documents and then validate that the out document is valid"?

Yep, that's what I meant. I'm also not sure of the feasibility of it without digging more into the code, so let's see how complex it will be.
