### ISSUE TITLE
Running a pipeline within a pipeline can lead to ConcurrentModificationException

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#91868]
### Elasticsearch Version

8.5.2

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

If a pipeline runs the PipelineProcessor asynchronously while other processors are updating the document, it can result in this exception:
```
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at org.elasticsearch.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1282) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1283) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1283) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1258) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.xcontent.XContentBuilder.map(XContentBuilder.java:1073) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.xcontent.XContentBuilder.map(XContentBuilder.java:1031) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.action.index.IndexRequest.source(IndexRequest.java:395) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService.lambda$innerExecute$10(IngestService.java:929) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestDocument.lambda$executePipeline$2(IngestDocument.java:838) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.Pipeline.lambda$execute$0(Pipeline.java:139) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:158) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$2(CompoundProcessor.java:226) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.PipelineProcessor.execute(PipelineProcessor.java:45) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:214) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$2(CompoundProcessor.java:226) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.ConditionalProcessor.execute(ConditionalProcessor.java:152) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:214) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$2(CompoundProcessor.java:226) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.ConditionalProcessor.execute(ConditionalProcessor.java:152) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:214) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:152) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:129) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestDocument.executePipeline(IngestDocument.java:831) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService.innerExecute(IngestService.java:895) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService.executePipelines(IngestService.java:745) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService$1.doRun(IngestService.java:707) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:892) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.5.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
```
That exception then triggers this exception:
```
[2022-11-23T11:53:36,239][WARN ][o.e.i.CompoundProcessor  ] [xpcs-s1] Preventing postIngest from being called more than once
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at org.elasticsearch.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1282) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1283) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1283) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1258) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.xcontent.XContentBuilder.map(XContentBuilder.java:1073) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.xcontent.XContentBuilder.map(XContentBuilder.java:1031) ~[elasticsearch-x-content-8.5.2.jar:?]
        at org.elasticsearch.action.index.IndexRequest.source(IndexRequest.java:395) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService.lambda$innerExecute$10(IngestService.java:929) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestDocument.lambda$executePipeline$2(IngestDocument.java:838) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.Pipeline.lambda$execute$0(Pipeline.java:139) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:158) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$2(CompoundProcessor.java:226) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.PipelineProcessor.execute(PipelineProcessor.java:45) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:214) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$2(CompoundProcessor.java:226) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.ConditionalProcessor.execute(ConditionalProcessor.java:152) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:214) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$2(CompoundProcessor.java:226) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.ConditionalProcessor.execute(ConditionalProcessor.java:152) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:214) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:152) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:129) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestDocument.executePipeline(IngestDocument.java:831) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService.innerExecute(IngestService.java:895) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService.executePipelines(IngestService.java:745) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService$1.doRun(IngestService.java:707) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:892) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.5.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```
And that results in:
```
[2022-11-23T11:53:36,240][WARN ][o.e.i.Pipeline           ] [xpcs-s1] A listener was unexpectedly called more than once
java.lang.RuntimeException: null
        at org.elasticsearch.ingest.Pipeline.lambda$execute$0(Pipeline.java:131) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.executeOnFailure(CompoundProcessor.java:278) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.executeOnFailure(CompoundProcessor.java:312) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.executeOnFailureOuter(CompoundProcessor.java:261) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:241) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$2(CompoundProcessor.java:226) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.ConditionalProcessor.execute(ConditionalProcessor.java:152) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:214) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$2(CompoundProcessor.java:226) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.ConditionalProcessor.execute(ConditionalProcessor.java:152) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:214) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:152) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:129) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestDocument.executePipeline(IngestDocument.java:831) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService.innerExecute(IngestService.java:895) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService.executePipelines(IngestService.java:745) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.ingest.IngestService$1.doRun(IngestService.java:707) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:892) ~[elasticsearch-8.5.2.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.5.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```
The end result is that the listener is never notified of success or failure for the pipeline, and so the client waits forever for a response (or more realistically, times out).
We need to prevent the ConcurrentModificationException. The easiest way might be to just make a copy of it before we validate. Another option might be to only do the validation after the top-level pipeline has completed rather than after every pipeline.

### Steps to Reproduce

This occurs in a pipeline with a nested pipeline that has dozens of other processors, including a script processor.

**Comment by joegallo** [comment]
Closing this in favor of https://github.com/elastic/elasticsearch/issues/91977.
