### ISSUE TITLE
[CI] DockerTests test600Interrupt failing

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#91874]
This has been failing since last night; the test was introduced here https://github.com/elastic/elasticsearch/pull/91704

@pgomulka could you take a look?

**Build scan:**
https://gradle-enterprise.elastic.co/s/vbiskqwpfrcog/tests/:qa:os:destructiveDistroTest.default-dockerUbi/org.elasticsearch.packaging.test.DockerTests/test600Interrupt

**Reproduction line:**
```
null
```

**Applicable branches:**
main, 8.6, 8.5, 7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DockerTests&tests.test=test600Interrupt

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c docker exec --tty 18025adbdc4e3507cc8aac28e446346d2ff847cf947a139795b2d14541c16fd3 kill -int 297]
   result: exitCode = [126] stdout = [OCI runtime exec failed: exec failed: unable to start container process: exec: "kill": executable file not found in $PATH: unknown] stderr = []

  at __randomizedtesting.SeedInfo.seed([46155085AFD7DEFA:DCFEE387CFC8A38C]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.util.docker.DockerShell.run(DockerShell.java:49)
  at org.elasticsearch.packaging.test.DockerTests.test600Interrupt(DockerTests.java:1234)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by valeriy42** [comment]
@pgomulka  It seems that the PR didn't fix the failure on `8.5`: https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.packaging.test.DockerTests&tests.test=test600Interrupt
