### ISSUE TITLE
[CI] DataStreamIT testWriteLoadAndAvgShardSizeIsStoredInABestEffort failing

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#91967]
Only Windows runs are failing.

**Build scan:**
https://gradle-enterprise.elastic.co/s/zyijl5succa7u/tests/:modules:data-streams:internalClusterTest/org.elasticsearch.datastreams.DataStreamIT/testWriteLoadAndAvgShardSizeIsStoredInABestEffort

**Reproduction line:**
```
gradlew ':modules:data-streams:internalClusterTest' --tests "org.elasticsearch.datastreams.DataStreamIT.testWriteLoadAndAvgShardSizeIsStoredInABestEffort" -Dtests.seed=38CC3C8574AEB1D8 -Dtests.locale=es-PA -Dtests.timezone=Pacific/Tongatapu -Druntime.java=19
```

**Applicable branches:**
8.6, main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.datastreams.DataStreamIT&tests.test=testWriteLoadAndAvgShardSizeIsStoredInABestEffort

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is not null
     but: was null

  at __randomizedtesting.SeedInfo.seed([38CC3C8574AEB1D8:9CF0E198064B4DB3]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.datastreams.DataStreamIT.testWriteLoadAndAvgShardSizeIsStoredInABestEffort(DataStreamIT.java:2113)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by dakrone** [comment]
@fcofdez I believe this is related to your recent data stream load writing work on the distributed side.

**Comment by joegallo** [comment]
https://gradle-enterprise.elastic.co/s/kpjcuctgfqodw/tests/:modules:data-streams:internalClusterTest/org.elasticsearch.datastreams.DataStreamIT/testWriteLoadAndAvgShardSizeIsStoredInABestEffort?top-execution=1

**Comment by craigtaverner** [comment]
Failed again today: https://gradle-enterprise.elastic.co/s/gk524nszmmrss

**Comment by dakrone** [comment]
Another failure today (from Mark): https://gradle-enterprise.elastic.co/s/viq7jx3vzhxuw/tests/:modules:data-streams:internalClusterTest/org.elasticsearch.datastreams.DataStreamIT/testWriteLoadAndAvgShardSizeIsStoredInABestEffort

**Comment by dakrone** [comment]
Muted this in #92601 and #92602

**Comment by fcofdez** [comment]
Looks like this is related to a replica that hasn't started yet when we request the stats during rollover:
```
Node IDs failing to respond to stats requests [96CkSfPSSVqtAeb9IqkJ_w, W5CORryAR0OaVVUL3Xaeaw, OOXZtJFFSpSwaQ848N4cXA], shard 1 replica routing [.ds-logs-es-2023.01.27-000001][1], node[0p9lnf9hT-qGKmck-UQMUQ], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=jh2K7bLtQ--9QsoFMODMrA], unassigned_info[[reason=INDEX_CREATED], at[2023-01-27T08:41:46.664Z], delayed=false, allocation_status[no_attempt]], failed_attempts[0]
```
