### ISSUE TITLE
Elasticsearch 8.5 branch build fails with Exit-code 17 when calling /usr/local/bin/docker-compose

### ISSUE THREAD

**Issue by vaishali-prophecy** [elastic/elasticsearch#92071]
### Elasticsearch Version

8.5.

### Java Version

17.0.5

### OS Version

Darwin MacBook-Pro 19.0.0 Darwin Kernel Version 19.0.0: Wed Oct 23 18:29:05 PDT 2019; root:xnu-6153.41.3~44/RELEASE_X86_64 x86_64

### Problem Description

./gradlew build fails with - 

> > Exit-code 17 when calling /usr/local/bin/docker-compose, stdout:

* Try:
> Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test:fixtures:krb5kdc-fixture:composeUp'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        
        
Also, I was trying to build new docker image for elasticsearch due to some security issues with commons-io-2.5.jar being used. Hence I need to move it to commons-io-2.7.jar or above. If you could tell me how can I build new centos based docker image from  source code, that would be great. The above error is without making any changes to source code. And I am guessing that ./gradlew composeBuild will build docker image but not really sure..

### Steps to Reproduce

Just run ./gradlew build

**Comment by mark-vieira** [comment]
The 8.5 branch is no longer supported. If you have issues building new branches please feel free to open a new issue.
