### ISSUE TITLE
Kubernetes Kibana 8.5.2 [ERROR][plugins.ruleRegistry] Error: Server is stopping; must stop all async operations

### ISSUE THREAD

**Issue by khteh** [elastic/elasticsearch#92223]
### Elasticsearch Version

8.5.2

### Java Version

_bundled_

### OS Version

Ubuntu 22.10

### Problem Description

```
[2022-12-08T07:57:38.408+00:00][ERROR][plugins.ruleRegistry] Error: Server is stopping; must stop all async operations
    at /usr/share/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:66:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-12-08T07:57:38.408+00:00][ERROR][plugins.ruleRegistry] Error: Failure installing common resources shared between all indices. Server is stopping; must stop all async operations
    at ResourceInstaller.installWithTimeout (/usr/share/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:75:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ResourceInstaller.installCommonResources (/usr/share/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:89:5)
[2022-12-08T07:57:38.419+00:00][FATAL][root] Error: 
    at _super (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/createErrorClass.js:7:26)
    at new EmptyErrorImpl (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/EmptyError.js:6:5)
    at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/first.js:13:263
    at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/throwIfEmpty.js:14:86
    at OperatorSubscriber._this._complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:56:21)
    at OperatorSubscriber.Subscriber.complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:69:18)
    at OperatorSubscriber.Subscriber._complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:92:30)
    at OperatorSubscriber.Subscriber.complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:69:18)
    at OperatorSubscriber.Subscriber._complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:92:30)
    at OperatorSubscriber.Subscriber.complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:69:18)
    at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subject.js:104:39
    at Object.errorContext (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at ReplaySubject.Subject.complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subject.js:98:24)
    at Object.complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/share.js:80:30)
    at ConsumerObserver.complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:138:33)
    at SafeSubscriber.Subscriber._complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:92:30)
    at SafeSubscriber.Subscriber.complete (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:69:18)
    at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/takeUntil.js:10:141
    at OperatorSubscriber._this._next (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subject.js:69:34
    at Object.errorContext (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Subject.next (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subject.js:59:24)
    at ElasticsearchService.stop (/usr/share/kibana/node_modules/@kbn/core-elasticsearch-server-internal/target_node/src/elasticsearch_service.js:147:16)
    at Server.stop (/usr/share/kibana/src/core/server/server.js:419:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Root.shutdown (/usr/share/kibana/src/core/server/root/index.js:87:5)
```

### Steps to Reproduce

Run a Kibana `Statefulset` on k8s cluster. `ConfigMap`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: default
data:
  kibana.yml: |+
    csp.strict: true
    server.port: 5601
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["https://elasticsearch-es-default:9200"]
```

**Comment by grcevski** [comment]
Hi @khteh, this looks like a Kibana issue, not elasticsearch? The server that's mentioned is the kibana backend nodejs server.

Can you please open an issue in the correct repository?
