### ISSUE TITLE
UberModuleClassLoader interleaved in java.lang.reflect.Proxy.newProxyInstance

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#92356]
### Elasticsearch Version

8.7

### Java Version

_bundled_

### OS Version

macos

### Problem Description

stable api settings are created with dynamic proxies. this fails security manager permissions when uberclassloader is used
```
(“java.lang.RuntimePermission” “accessClassInPackage.jdk.internal.reflect”)
»       at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
»       at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
»       at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
»       at java.base/java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1332)
»       at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:184)
»       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:574)
»       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
»       at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.plugins.UberModuleClassLoader.loadClass(UberModuleClassLoader.java:267)
»       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
»       at java.base/java.lang.ClassLoader.defineClass1(Native Method)
»       at java.base/java.lang.System$2.defineClass(System.java:2303)
»       at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:66)
»       at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:401)
»       at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:395)
»       at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
»       at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:394)
»       at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:92)
»       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:65)
»       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
»       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
»       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
»       at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1053)
»       at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1039)
»       at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.indices.analysis.wrappers.SettingsInvocationHandler.create(SettingsInvocationHandler.java:41)
»       at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.indices.analysis.wrappers.StableApiWrappers.createSettings(StableApiWrappers.java:247)
»       at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.indices.analysis.wrappers.StableApiWrappers.createInstance(StableApiWrappers.java:223)
»       at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.indices.analysis.wrappers.StableApiWrappers$1.get(StableApiWrappers.java:100)
»       at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:507)
»       at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.index.analysis.AnalysisRegistry.buildCharFilterFactories(AnalysisRegistry.java:320)
»       at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:205)
```

### Steps to Reproduce

git checkout -b pgomulka-example_plugin_settings main
git pull https://github.com/pgomulka/elasticsearch.git example_plugin_settings

remove line 25 in server/src/main/resources/bootstrap/security.policy (this line allows the test to work)
  permission java.lang.RuntimePermission "accessClassInPackage.jdk.internal.reflect";

cd plugins/examples
./gradlew ':stable-analysis:yamlRestTest' --tests "org.elasticsearch.example.stable.client.ExampleStableAnalysisClientYamlTestSuiteIT"  --include-build=../..

**Comment by rjernst** [comment]
This should be ok, we just need server to have this permission. Should be something like this in `security.policy`:

```
diff --git a/server/src/main/resources/org/elasticsearch/bootstrap/security.policy b/server/src/mai>
index 3b21c273d3a..8016ab0dc38 100644
--- a/server/src/main/resources/org/elasticsearch/bootstrap/security.policy
+++ b/server/src/main/resources/org/elasticsearch/bootstrap/security.policy
@@ -28,6 +28,9 @@ grant codeBase "${codebase.elasticsearch}" {
   // for module layer
   permission java.lang.RuntimePermission "createClassLoader";
   permission java.lang.RuntimePermission "getClassLoader";
+
+  // for plugin api dynamic settings instances
+  permission java.lang.RuntimePermission “accessClassInPackage.jdk.internal.reflect”;
 };
```
