### ISSUE TITLE
[CI] SSLReloadIntegTests testThatSSLConfigurationReloadsOnModification failing

### ISSUE THREAD

**Issue by joegallo** [elastic/elasticsearch#92365]
**Build scan:**
https://gradle-enterprise.elastic.co/s/z2pvgeyxxqfoo/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.ssl.SSLReloadIntegTests/testThatSSLConfigurationReloadsOnModification

**Reproduction line:**
```
gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.xpack.ssl.SSLReloadIntegTests.testThatSSLConfigurationReloadsOnModification" -Dtests.seed=2CD592B1AC5189E4 -Dtests.locale=el -Dtests.timezone=America/Denver -Druntime.java=19
```

**Applicable branches:**
8.6

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ssl.SSLReloadIntegTests&tests.test=testThatSSLConfigurationReloadsOnModification

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=3286, name=elasticsearch[node_s0][generic][T#1], state=RUNNABLE, group=TGRP-SSLReloadIntegTests]


  Caused by: java.lang.AssertionError: initial cluster state not set yet

    at __randomizedtesting.SeedInfo.seed([2CD592B1AC5189E4]:0)
    at org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:181)
    at org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:141)
    at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporter.onCleanUpIndices(LocalExporter.java:598)
    at org.elasticsearch.xpack.monitoring.cleaner.CleanerService$IndicesCleaner.doRunInLifecycle(CleanerService.java:164)
    at org.elasticsearch.common.util.concurrent.AbstractLifecycleRunnable.doRun(AbstractLifecycleRunnable.java:56)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1589)

```

**Comment by joegallo** [comment]
Note: It might be important to know that the failure above on Windows.

**Comment by slobodanadamovic** [comment]
Looking at [the test](https://github.com/elastic/elasticsearch/blob/e20979179f2ba887b04850627d6a1f8ece78aeb3/x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/ssl/SSLReloadIntegTests.java#L144), I don't think this is a security issue since test was executed successfully:

```
[2022-12-14T01:00:02,734][INFO ][o.e.x.s.SSLReloadIntegTests] [[HandshakeCompletedNotify-Thread]] ssl handshake completed on port [64842]
```

Seems like there is some race condition when `Node` is stopping  `LifecycleComponent`s, or simply the order in which they are stopped is causing the issue. Since `CleanerService` (in monitoring plugin) depends on `ClusterService`, maybe we should stop the cluster service last? This is just hypothetical. I would appreciate if someone from @elastic/es-distributed could have a look.

**Comment by idegtiarenko** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/100565
