### ISSUE TITLE
[CI] SearchableSnapshotsLicenseIntegTests testShardAllocationOnInvalidLicense failing

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#92393]
This failed on the `8.5` branch but might be something we want to look into in the `main` branch. The root cause seems to be a reflection problem
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private int java.io.FileDescriptor.fd accessible: module java.base does not "opens java.io" to unnamed module @1afd44cb
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/tjwwxsakplazs/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsLicenseIntegTests/testShardAllocationOnInvalidLicense

**Reproduction line:**
```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsLicenseIntegTests.testShardAllocationOnInvalidLicense" -Dtests.seed=6C83B0C8CEA07617 -Dtests.locale=tr-TR -Dtests.timezone=America/Santiago -Druntime.java=17
```

**Applicable branches:**
8.5

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsLicenseIntegTests&tests.test=testShardAllocationOnInvalidLicense

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=319, name=elasticsearch[node_t1][generic][T#1], state=RUNNABLE, group=TGRP-SearchableSnapshotsLicenseIntegTests]

  at __randomizedtesting.SeedInfo.seed([6C83B0C8CEA07617:E0936B507650A207]:0)

  Caused by: java.lang.AssertionError: (No message provided)

    at __randomizedtesting.SeedInfo.seed([6C83B0C8CEA07617]:0)
    at org.elasticsearch.indices.recovery.RecoveryTarget.restoreFileFromSnapshot(RecoveryTarget.java:571)
    at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RestoreFileFromSnapshotTransportRequestHandler.messageReceived(PeerRecoveryTargetService.java:614)
    at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RestoreFileFromSnapshotTransportRequestHandler.messageReceived(PeerRecoveryTargetService.java:599)
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:71)
    at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:291)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:892)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by arteam** [comment]
This doesn't reproduce for me on the main branch nor on 8.5. Same on the CI, no test failures over the month. I'm going to close the issue.
