### ISSUE TITLE
[CI] DatafeedJobsIT testStartDatafeed_GivenTimeout_Returns408 failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#92521]
**Build scan:**
https://gradle-enterprise.elastic.co/s/wyobowf5rwv4c/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.DatafeedJobsIT/testStartDatafeed_GivenTimeout_Returns408

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.testStartDatafeed_GivenTimeout_Returns408" -Dtests.seed=FD095D9802DCA16F -Dtests.locale=fi -Dtests.timezone=America/Monterrey -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.DatafeedJobsIT&tests.test=testStartDatafeed_GivenTimeout_Returns408

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([FD095D9802DCA16F]:0)

```

**Comment by droberts195** [comment]
Seems like the problem is related to what happens if a normalization is in progress when reset mode is enabled:

```
[2022-12-21T00:34:12,858][ERROR][o.e.x.m.j.p.n.ShortCircuitingRenormalizer] [javaRestTest-2] [job-for-start-datafeed-timeout] Error propagated from normalization
java.util.concurrent.ExecutionException: org.elasticsearch.common.util.CancellableThreads$ExecutionCancelledException: Reset mode has been enabled
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.normalizer.ShortCircuitingRenormalizer.waitUntilIdle(ShortCircuitingRenormalizer.java:95) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.normalizer.ShortCircuitingRenormalizer.shutdown(ShortCircuitingRenormalizer.java:114) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.output.AutodetectResultProcessor.setProcessKilled(AutodetectResultProcessor.java:240) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectCommunicator.killProcess(AutodetectCommunicator.java:204) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.ProcessContext$KillBuilder.kill(ProcessContext.java:139) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager.killProcess(AutodetectProcessManager.java:199) ~[?:?]
        at org.elasticsearch.xpack.ml.job.task.JobTask.killJob(JobTask.java:91) ~[?:?]
        at org.elasticsearch.xpack.ml.action.TransportKillProcessAction.taskOperation(TransportKillProcessAction.java:89) ~[?:?]
        at org.elasticsearch.xpack.ml.action.TransportKillProcessAction.taskOperation(TransportKillProcessAction.java:35) ~[?:?]
        at org.elasticsearch.action.support.tasks.TransportTasksAction.nodeOperation(TransportTasksAction.java:138) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:331) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:327) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:316) ~[?:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:378) ~[?:?]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:368) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$6(AuthorizationService.java:439) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:992) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:958) ~[?:?]
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$7(AuthorizationService.java:453) ~[?:?]
        at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:163) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
        at org.elasticsearch.xpack.security.authz.RBACEngine.authorizeClusterAction(RBACEngine.java:182) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(AuthorizationService.java:443) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(AuthorizationService.java:419) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$3(AuthorizationService.java:320) ~[?:?]
        at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:163) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
...
```

**Comment by droberts195** [comment]
The problem is in https://github.com/elastic/elasticsearch/blob/a422d82a073af4239cc1018da475e834b8772e08/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/ShortCircuitingRenormalizer.java#L97-98

The reasoning that it can never happen has not been true since we've had async retries on results persistence.
