### ISSUE TITLE
[CI] :plugins:repository-hdfs:javaRestTestSecure2 failing

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#92752]
### CI Link

https://gradle-enterprise.elastic.co/s/5g2ajm6cie4rm

### Repro line

gradlew :plugins:repository-hdfs:javaRestTestSecure2

### Does it reproduce?

No

### Applicable branches

main, 8.6

### Failure excerpt

```
Caused by: java.io.UncheckedIOException: Could not write config file: /dev/shm/elastic+elasticsearch+8.6+periodic+java-matrix/plugins/repository-hdfs/build/testclusters/javaRestTestSecure2-0/config/elasticsearch.yml
10:40:04 	at org.elasticsearch.gradle.testclusters.ElasticsearchNode.createConfiguration(ElasticsearchNode.java:1452)
10:40:04 	at org.elasticsearch.gradle.testclusters.ElasticsearchNode.start(ElasticsearchNode.java:542)
10:40:04 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
10:40:04 	at org.elasticsearch.gradle.testclusters.ElasticsearchCluster.start(ElasticsearchCluster.java:343)
10:40:04 	at org.elasticsearch.gradle.testclusters.TestClustersRegistry.maybeStartCluster(TestClustersRegistry.java:37)
10:40:04 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
10:40:04 	at org.elasticsearch.gradle.testclusters.TestClustersPlugin$TestClustersHookPlugin$1.beforeActions(TestClustersPlugin.java:205)
10:40:04 	at jdk.internal.reflect.GeneratedMethodAccessor609.invoke(Unknown Source)
10:40:04 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:40:04 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:40:04 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
10:40:04 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
10:40:04 	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:464)
10:40:04 	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:446)
10:40:04 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:61)
10:40:04 	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:434)
10:40:04 	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:221)
10:40:04 	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:192)
10:40:04 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
10:40:04 	at jdk.proxy1/jdk.proxy1.$Proxy84.beforeActions(Unknown Source)
10:40:04 	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:186)
10:40:04 	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:165)
10:40:04 	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
10:40:04 	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
10:40:04 	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
10:40:04 	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
10:40:04 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:50)
10:40:04 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:40)
10:40:04 	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
10:40:04 	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
10:40:04 	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
10:40:04 	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
10:40:04 	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
10:40:04 	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
10:40:04 	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
10:40:04 	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:124)
10:40:04 	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:80)
10:40:04 	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:58)
10:40:04 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
10:40:04 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
10:40:04 	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:181)
10:40:04 	at org.gradle.internal.execution.steps.BuildCacheStep.executeAndStoreInCache(BuildCacheStep.java:154)
10:40:04 	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$executeWithCache$4(BuildCacheStep.java:121)
10:40:04 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
10:40:04 	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$executeWithCache$5(BuildCacheStep.java:121)
10:40:04 	at org.gradle.internal.Try$Success.map(Try.java:164)
10:40:04 	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithCache(BuildCacheStep.java:81)
10:40:04 	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$0(BuildCacheStep.java:70)
10:40:04 	at org.gradle.internal.Either$Left.fold(Either.java:115)
10:40:04 	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
10:40:04 	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:69)
10:40:04 	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:47)
10:40:04 	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
10:40:04 	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
10:40:04 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
10:40:04 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
10:40:04 	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:110)
10:40:04 	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:56)
10:40:04 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
10:40:04 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:56)
10:40:04 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
10:40:04 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:73)
10:40:04 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
10:40:04 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
10:40:04 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
10:40:04 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:89)
10:40:04 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:50)
10:40:04 	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:114)
10:40:04 	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:57)
10:40:04 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:76)
10:40:04 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
10:40:04 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:254)
10:40:04 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:209)
10:40:04 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:88)
10:40:04 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:56)
10:40:04 	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
10:40:04 	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
10:40:04 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
10:40:04 	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
10:40:04 	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
10:40:04 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
10:40:04 	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:281)
10:40:04 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
10:40:04 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
10:40:04 	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
10:40:04 	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
10:40:04 	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
10:40:04 	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
10:40:04 	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
10:40:04 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:139)
10:40:04 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
10:40:04 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
10:40:04 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
10:40:04 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
10:40:04 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
10:40:04 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
10:40:04 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
10:40:04 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
10:40:04 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
10:40:04 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
10:40:04 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
10:40:04 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
10:40:04 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
10:40:04 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:327)
10:40:04 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:314)
10:40:04 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:307)
10:40:04 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:293)
10:40:04 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:420)
10:40:04 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:342)
10:40:04 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
10:40:04 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
10:40:04 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
10:40:04 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
10:40:04 	at java.base/java.lang.Thread.run(Thread.java:833)
10:40:04 Caused by: java.nio.file.NoSuchFileException: /dev/shm/elastic+elasticsearch+8.6+periodic+java-matrix/plugins/repository-hdfs/build/testclusters/javaRestTestSecure2-0/distro/8.6.0-INTEG_TEST/config
10:40:04 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
10:40:04 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
10:40:04 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
10:40:04 	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:440)
10:40:04 	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
10:40:04 	at java.base/java.nio.file.Files.list(Files.java:3792)
10:40:04 	at org.elasticsearch.gradle.testclusters.ElasticsearchNode.createConfiguration(ElasticsearchNode.java:1441)
```

**Comment by masseyke** [comment]
Sending this over to the delivery team because it looks like a problem with org.elasticsearch.gradle.testclusters.ElasticsearchNode rather than with repository-hdfs or its tests. Send it back to us if you think I'm misreading it.

**Comment by mark-vieira** [comment]
This looks to have never happened again so I'm closing this as a transient failure.
