### ISSUE TITLE
[CI] NamedComponentScannerTests testNamedComponentsAreFoundWhenSingleJarProvided failing

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#92782]
see build scan for many more similar tests that fail with the same error:

```
org.elasticsearch.plugin.scanner.NamedComponentScannerTests > testNamedComponentsCanExtednCommonSuperClass FAILED	
    java.lang.IllegalArgumentException: Unsupported class file major version 63	
        at __randomizedtesting.SeedInfo.seed([2F888D6ACFE09C0C:603C93F7C473A506]:0)	
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)	
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)	
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)	
        at org.elasticsearch.plugin.scanner.ClassReaders.lambda$classesInPath$5(ClassReaders.java:99)	
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)	
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)	
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)	
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)	
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)	
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)	
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)	
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)	
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)	
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)	
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)	
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)	
        at org.elasticsearch.plugin.scanner.ClassReaders.classesInPath(ClassReaders.java:104)	
        at org.elasticsearch.plugin.scanner.ClassReaders.classesInJar(ClassReaders.java:84)	
        at org.elasticsearch.plugin.scanner.ClassReaders.lambda$ofPaths$1(ClassReaders.java:74)	
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)	
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)	
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)	
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)	
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)	
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)	
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)	
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)	
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)	
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)	
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)	
        at org.elasticsearch.plugin.scanner.ClassReaders.ofPaths(ClassReaders.java:78)	
        at org.elasticsearch.plugin.scanner.ClassReaders.ofDirWithJars(ClassReaders.java:49)	
        at org.elasticsearch.plugin.scanner.NamedComponentScannerTests.testNamedComponentsCanExtednCommonSuperClass(NamedComponentScannerTests.java:154)
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/3dgcvixgygke6/tests/:libs:elasticsearch-plugin-scanner:test/org.elasticsearch.plugin.scanner.NamedComponentScannerTests/testNamedComponentsAreFoundWhenSingleJarProvided

**Reproduction line:**
```
./gradlew ':libs:elasticsearch-plugin-scanner:test' --tests "org.elasticsearch.plugin.scanner.NamedComponentScannerTests.testNamedComponentsAreFoundWhenSingleJarProvided" -Dtests.seed=96C4AEB6115F6293 -Dtests.locale=es-CO -Dtests.timezone=Africa/Lome -Druntime.java=19
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.plugin.scanner.NamedComponentScannerTests&tests.test=testNamedComponentsAreFoundWhenSingleJarProvided

**Failure excerpt:**
```
java.lang.IllegalArgumentException: Unsupported class file major version 63

  at __randomizedtesting.SeedInfo.seed([96C4AEB6115F6293:AD48B68DDB0BADDF]:0)
  at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
  at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
  at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
  at org.elasticsearch.plugin.scanner.ClassReaders.lambda$classesInPath$5(ClassReaders.java:99)
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  at java.util.Iterator.forEachRemaining(Iterator.java:133)
  at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
  at org.elasticsearch.plugin.scanner.ClassReaders.classesInPath(ClassReaders.java:104)
  at org.elasticsearch.plugin.scanner.ClassReaders.classesInJar(ClassReaders.java:84)
  at org.elasticsearch.plugin.scanner.ClassReaders.lambda$ofPaths$1(ClassReaders.java:74)
  at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
  at java.util.Iterator.forEachRemaining(Iterator.java:133)
  at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
  at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
  at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
  at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
  at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
  at org.elasticsearch.plugin.scanner.ClassReaders.ofPaths(ClassReaders.java:78)
  at org.elasticsearch.plugin.scanner.ClassReaders.ofDirWithJars(ClassReaders.java:49)
  at org.elasticsearch.plugin.scanner.NamedComponentScannerTests.testNamedComponentsAreFoundWhenSingleJarProvided(NamedComponentScannerTests.java:79)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by thecoop** [comment]
We need to update the version of asm to at least 9.3 to support java 19 class files

**Comment by thecoop** [comment]
8.6 backport is https://github.com/elastic/elasticsearch/pull/92942
