### ISSUE TITLE
[CI] ClassReadersTests and NamedComponentScannerTests failing on 8.6

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#92936]
**Build scan:**
https://gradle-enterprise.elastic.co/s/xc6ytu3ghgvtw/tests/:libs:elasticsearch-plugin-scanner:test/org.elasticsearch.plugin.scanner.ClassReadersTests/testMultipleJarsInADir
https://gradle-enterprise.elastic.co/s/xc6ytu3ghgvtw/tests/:libs:elasticsearch-plugin-scanner:test/org.elasticsearch.plugin.scanner.NamedComponentScannerTests/testNamedComponentsAreFoundWhenSingleJarProvided
https://gradle-enterprise.elastic.co/s/xc6ytu3ghgvtw/tests/:libs:elasticsearch-plugin-scanner:test/org.elasticsearch.plugin.scanner.NamedComponentScannerTests/testNamedComponentsCanExtednCommonSuperClass
https://gradle-enterprise.elastic.co/s/xc6ytu3ghgvtw/tests/:libs:elasticsearch-plugin-scanner:test/org.elasticsearch.plugin.scanner.ClassReadersTests/testStreamOfJarsAndIndividualClasses
https://gradle-enterprise.elastic.co/s/xc6ytu3ghgvtw/tests/:libs:elasticsearch-plugin-scanner:test/org.elasticsearch.plugin.scanner.ClassReadersTests/testTwoClassesInAStreamFromJar

**Reproduction line:**
```
./gradlew ':libs:elasticsearch-plugin-scanner:test' --tests "org.elasticsearch.plugin.scanner.ClassReadersTests.testMultipleJarsInADir" -Dtests.seed=27A22EAE711B269E -Dtests.locale=sv-SE -Dtests.timezone=America/Dawson -Druntime.java=19
```

**Applicable branches:**
8.6

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.plugin.scanner.ClassReadersTests&tests.test=testMultipleJarsInADir

**Failure excerpt:**
```
java.lang.IllegalArgumentException: Unsupported class file major version 63

  at __randomizedtesting.SeedInfo.seed([27A22EAE711B269E:F3AD5825DB82D634]:0)
  at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
  at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
  at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
  at org.elasticsearch.plugin.scanner.ClassReaders.lambda$classesInPath$5(ClassReaders.java:98)
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  at java.util.Iterator.forEachRemaining(Iterator.java:133)
  at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
  at org.elasticsearch.plugin.scanner.ClassReaders.classesInPath(ClassReaders.java:103)
  at org.elasticsearch.plugin.scanner.ClassReaders.classesInJar(ClassReaders.java:84)
  at org.elasticsearch.plugin.scanner.ClassReaders.lambda$ofPaths$1(ClassReaders.java:74)
  at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
  at java.util.Iterator.forEachRemaining(Iterator.java:133)
  at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
  at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
  at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
  at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
  at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
  at org.elasticsearch.plugin.scanner.ClassReaders.ofPaths(ClassReaders.java:78)
  at org.elasticsearch.plugin.scanner.ClassReaders.ofDirWithJars(ClassReaders.java:49)
  at org.elasticsearch.plugin.scanner.ClassReadersTests.testMultipleJarsInADir(ClassReadersTests.java:122)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by davidkyle** [comment]
Looks similar to #92866 although the error is different. This failing build contained the backport fix #92897 (92a9cc1ebae8f1379fe3a274af2a11ee78322960)

**Comment by thecoop** [comment]
Backport PR https://github.com/elastic/elasticsearch/pull/92942

**Comment by thecoop** [comment]
#92942 merged
