### ISSUE TITLE
[CI] ClassReadersTests classMethod failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#93005]
Maybe related to: https://github.com/elastic/elasticsearch/issues/92936

**Build scan:**
https://gradle-enterprise.elastic.co/s/xnay2gtnbk67u/tests/:libs:elasticsearch-plugin-scanner:test/org.elasticsearch.plugin.scanner.ClassReadersTests

**Reproduction line:**
```
./gradlew ':libs:elasticsearch-plugin-scanner:test' --tests "org.elasticsearch.plugin.scanner.ClassReadersTests" -Dtests.seed=62A93F3353484C1B -Dtests.locale=en-US -Dtests.timezone=Atlantic/Reykjavik -Druntime.java=19
```

**Applicable branches:**
8.6, main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.plugin.scanner.ClassReadersTests&tests.test=classMethod

**Failure excerpt:**
```
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001\tempDir-003: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001\tempDir-003
   C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001\tempDir-003\jars-dir: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001\tempDir-003\jars-dir
   C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001

  at __randomizedtesting.SeedInfo.seed([62A93F3353484C1B]:0)
  at org.apache.lucene.util.IOUtils.rm(IOUtils.java:341)
  at org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:209)
  at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by benwtrent** [comment]
@thecoop This may be related to your recent change: https://github.com/elastic/elasticsearch/issues/92936

**Comment by rjernst** [comment]
This looks unrelated to https://github.com/elastic/elasticsearch/issues/92936. Instead it looks like https://github.com/elastic/elasticsearch/issues/92866 was never actually fully fixed by https://github.com/elastic/elasticsearch/pull/92890.

I've opened #93019 to try to help further diagnose where the underlying file leak is occurring.
