### ISSUE TITLE
[CI] FeatureUpgradeApiIT testCreatingSystemIndex failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#93007]
This is a weird one. The failures all stem from some slow cluster state behavior on ARM/Aarch64. Didn't see an open issue related to ARM slowness...

Immediately before the reset was called, this is logged:

```
» [2023-01-17T20:38:50,688][WARN ][o.e.g.PersistedClusterStateService] [javaRestTest-0] writing cluster state took [12004ms] which is above the warn threshold of [10s]; [wrote] global metadata, wrote [0] new mappings, removed [0] mappings and skipped [0] unchanged mappings, wrote metadata for [0] new indices and [0] existing indices, removed metadata for [0] indices and skipped [0] unchanged indices	
```

Assigning ML, but may very well be a distributed issue. 
```
» [2023-01-17T20:39:32,804][WARN ][r.suppressed             ] [javaRestTest-0] path: /_features/_reset, params: {} org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (ml-set-reset-mode) within 30s	
```

Is logged, but also suppressed is:
```
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (transform-set-reset-mode) within 30s
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/sthumtsu4ptli/tests/:qa:system-indices:javaRestTest/org.elasticsearch.system.indices.FeatureUpgradeApiIT/testCreatingSystemIndex

**Reproduction line:**
```
./gradlew ':qa:system-indices:javaRestTest' --tests "org.elasticsearch.system.indices.FeatureUpgradeApiIT.testCreatingSystemIndex" -Dtests.seed=445818AF1D9967CE -Dtests.locale=bg -Dtests.timezone=Chile/EasterIsland -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.system.indices.FeatureUpgradeApiIT&tests.test=testCreatingSystemIndex

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:37475], URI [/_features/_reset], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[{"type":"process_cluster_event_timeout_exception","reason":"failed to process cluster event (ml-set-reset-mode) within 30s","suppressed":[{"type":"process_cluster_event_timeout_exception","reason":"failed to process cluster event (transform-set-reset-mode) within 30s"}]}],"type":"process_cluster_event_timeout_exception","reason":"failed to process cluster event (ml-set-reset-mode) within 30s","suppressed":[{"type":"process_cluster_event_timeout_exception","reason":"failed to process cluster event (transform-set-reset-mode) within 30s"}]},"status":503}

  at __randomizedtesting.SeedInfo.seed([445818AF1D9967CE:2D902C53F4AE997B]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:319)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.system.indices.FeatureUpgradeApiIT.resetFeatures(FeatureUpgradeApiIT.java:36)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by henningandersen** [comment]
This looks more infrastructure related than a problem with the code. The persistence of the cluster state taking more than 12s seems like an overload situation, either on CPU or IO.

**Comment by mark-vieira** [comment]
I've started by re-enabling ram-disks on these jobs and spitting them up into smaller pieces to avoid running into memory constraints.

**Comment by mark-vieira** [comment]
The last half dozen jobs on `main` have passed now and complete in about an hour so I'll consider this fixed.
