### ISSUE TITLE
[CI] JsonLogsFormatAndParseIT testElementsPresentOnAllLinesOfLog failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#93070]
**Build scan:**
https://gradle-enterprise.elastic.co/s/lx3zdpgwrk7wi/tests/:qa:unconfigured-node-name:javaRestTest/org.elasticsearch.unconfigured_node_name.JsonLogsFormatAndParseIT/testElementsPresentOnAllLinesOfLog

**Reproduction line:**
```
./gradlew ':qa:unconfigured-node-name:javaRestTest' --tests "org.elasticsearch.unconfigured_node_name.JsonLogsFormatAndParseIT.testElementsPresentOnAllLinesOfLog" -Dtests.seed=6796DC9D72F6FC3A -Dtests.locale=fi -Dtests.timezone=America/St_Johns -Druntime.java=17
```

**Applicable branches:**
8.6

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.unconfigured_node_name.JsonLogsFormatAndParseIT&tests.test=testElementsPresentOnAllLinesOfLog

**Failure excerpt:**
```
java.lang.AssertionError: there are still running tasks:
{time_in_queue=41.3s, time_in_queue_millis=41307, source=put-lifecycle-.monitoring-8-ilm-policy, executing=true, priority=NORMAL, insert_order=31}
{time_in_queue=41.3s, time_in_queue_millis=41306, source=put-lifecycle-ml-size-based-ilm-policy, executing=false, priority=NORMAL, insert_order=33}
{time_in_queue=41.3s, time_in_queue_millis=41300, source=put-lifecycle-.fleet-actions-results-ilm-policy, executing=false, priority=NORMAL, insert_order=44}
{time_in_queue=41.2s, time_in_queue_millis=41297, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=50}
{time_in_queue=41.2s, time_in_queue_millis=41299, source=create persistent task, executing=false, priority=NORMAL, insert_order=47}
{time_in_queue=41.2s, time_in_queue_millis=41287, source=cluster_reroute(state recovered), executing=false, priority=NORMAL, insert_order=51}
{time_in_queue=34.4s, time_in_queue_millis=34428, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=57}
{time_in_queue=31s, time_in_queue_millis=31040, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=61}
{time_in_queue=32.2s, time_in_queue_millis=32269, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=60}
{time_in_queue=41.2s, time_in_queue_millis=41298, source=health-metadata-update-master-election, executing=false, priority=NORMAL, insert_order=49}
{time_in_queue=32.4s, time_in_queue_millis=32453, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=59}
{time_in_queue=29.5s, time_in_queue_millis=29535, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=62}
{time_in_queue=25.8s, time_in_queue_millis=25827, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=65}
{time_in_queue=32.9s, time_in_queue_millis=32949, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=58}
{time_in_queue=23.5s, time_in_queue_millis=23571, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=66}
{time_in_queue=12.4s, time_in_queue_millis=12481, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=68}
{time_in_queue=29.4s, time_in_queue_millis=29421, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=63}
{time_in_queue=20.8s, time_in_queue_millis=20862, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=67}
{time_in_queue=551ms, time_in_queue_millis=551, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=70}
{time_in_queue=28.5s, time_in_queue_millis=28530, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=64}
{time_in_queue=5.5s, time_in_queue_millis=5556, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=69}

  at __randomizedtesting.SeedInfo.seed([6796DC9D72F6FC3A:CA067918F6F08183]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.test.rest.ESRestTestCase.lambda$waitForClusterStateUpdatesToFinish$31(ESRestTestCase.java:1275)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1112)
  at org.elasticsearch.test.rest.ESRestTestCase.waitForClusterStateUpdatesToFinish(ESRestTestCase.java:1266)
  at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:406)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by rjernst** [comment]
While I do not think this is an issue with the particular logs test, we see these types of errors periodically. Instead of just ignoring it, I think we should try to improve the failure logging in the case of pending tasks that do not complete. Right now we only see which tasks are still pending at the end of 30 seconds.

We could add more information about each task, for example how long each has been running. In this particular failure, a put lifecycle action is running when the timeout occurs, but we don't know how long it has been running for.

**Comment by thecoop** [comment]
Created #93222 to improve this, closing this issue

**Comment by cbuescher** [comment]
@thecoop would this recent failure also fall under the category? https://gradle-enterprise.elastic.co/s/rtddkhh7neaeu 
Asking because I'm on test triage and not sure if we want to open new issues for these type of errors until #93222 has been implemented.

**Comment by thecoop** [comment]
Yeah, that looks the same to me. Maybe the distributed team need to have a look, it's the ILM tasks that are in the list...

**Comment by thecoop** [comment]
OK, reopening to see if Distributed have any insights as to why the ILM tasks are blocking

**Comment by thecoop** [comment]
From comments on #93222, sounds like this is just a very slow ES instance
