### ISSUE TITLE
[CI] SmokeTestIngestDisabledClientYamlTestSuiteIT test {yaml=ingest_mustache/10_ingest_disabled/Test bulk api that contains a single index call with pipeline id fails when node.ingest is set to false} failing

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#93139]
**Build scan:**
https://gradle-enterprise.elastic.co/s/dhaykl6xmnv3w/tests/:qa:smoke-test-ingest-disabled:yamlRestTest/org.elasticsearch.smoketest.SmokeTestIngestDisabledClientYamlTestSuiteIT/test%20%7Byaml=ingest_mustache%2F10_ingest_disabled%2FTest%20bulk%20api%20that%20contains%20a%20single%20index%20call%20with%20pipeline%20id%20fails%20when%20node.ingest%20is%20set%20to%20false%7D

**Reproduction line:**
```
./gradlew ':qa:smoke-test-ingest-disabled:yamlRestTest' --tests "org.elasticsearch.smoketest.SmokeTestIngestDisabledClientYamlTestSuiteIT" -Dtests.method="test {yaml=ingest_mustache/10_ingest_disabled/Test bulk api that contains a single index call with pipeline id fails when node.ingest is set to false}" -Dtests.seed=DC137C62ED6BE88D -Dtests.locale=zh-Hans-CN -Dtests.timezone=Atlantic/Madeira -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.smoketest.SmokeTestIngestDisabledClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dingest_mustache/10_ingest_disabled/Test%20bulk%20api%20that%20contains%20a%20single%20index%20call%20with%20pipeline%20id%20fails%20when%20node.ingest%20is%20set%20to%20false%7D

**Failure excerpt:**
```
java.lang.AssertionError: there are still running tasks:
{time_in_queue=36.1s, time_in_queue_millis=36112, source=put-lifecycle-30-days-default, executing=true, priority=NORMAL, insert_order=29}
{time_in_queue=36.1s, time_in_queue_millis=36112, source=put-lifecycle-7-days-default, executing=false, priority=NORMAL, insert_order=30}
{time_in_queue=36.1s, time_in_queue_millis=36112, source=put-lifecycle-.monitoring-8-ilm-policy, executing=false, priority=NORMAL, insert_order=31}
{time_in_queue=36.1s, time_in_queue_millis=36104, source=put-lifecycle-.fleet-file-data-ilm-policy, executing=false, priority=NORMAL, insert_order=49}
{time_in_queue=36.1s, time_in_queue_millis=36111, source=put-lifecycle-ml-size-based-ilm-policy, executing=false, priority=NORMAL, insert_order=34}
{time_in_queue=36.1s, time_in_queue_millis=36104, source=put-lifecycle-.fleet-actions-results-ilm-policy, executing=false, priority=NORMAL, insert_order=50}
{time_in_queue=18.3s, time_in_queue_millis=18372, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=68}
{time_in_queue=36.1s, time_in_queue_millis=36102, source=health-metadata-update-master-election, executing=false, priority=NORMAL, insert_order=53}
{time_in_queue=36.1s, time_in_queue_millis=36104, source=put-lifecycle-.fleet-files-ilm-policy, executing=false, priority=NORMAL, insert_order=51}
{time_in_queue=32.4s, time_in_queue_millis=32432, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=64}
{time_in_queue=36.1s, time_in_queue_millis=36103, source=create persistent task, executing=false, priority=NORMAL, insert_order=52}
{time_in_queue=36s, time_in_queue_millis=36091, source=cluster_reroute(state recovered), executing=false, priority=NORMAL, insert_order=55}
{time_in_queue=762ms, time_in_queue_millis=762, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=72}
{time_in_queue=7.1s, time_in_queue_millis=7164, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=70}
{time_in_queue=3.3s, time_in_queue_millis=3319, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=71}
{time_in_queue=36.1s, time_in_queue_millis=36101, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=54}
{time_in_queue=27.1s, time_in_queue_millis=27197, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=65}
{time_in_queue=32.9s, time_in_queue_millis=32925, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=62}
{time_in_queue=24.4s, time_in_queue_millis=24497, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=66}
{time_in_queue=16.6s, time_in_queue_millis=16648, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=69}
{time_in_queue=33.1s, time_in_queue_millis=33108, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=61}
{time_in_queue=20.7s, time_in_queue_millis=20730, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=67}
{time_in_queue=32.6s, time_in_queue_millis=32693, source=maybe generate license for cluster, executing=false, priority=NORMAL, insert_order=63}

  at __randomizedtesting.SeedInfo.seed([DC137C62ED6BE88D:544743B843978575]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.test.rest.ESRestTestCase.lambda$waitForClusterStateUpdatesToFinish$29(ESRestTestCase.java:1230)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1120)
  at org.elasticsearch.test.rest.ESRestTestCase.waitForClusterStateUpdatesToFinish(ESRestTestCase.java:1221)
  at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:402)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by mark-vieira** [comment]
This sound similar to https://github.com/elastic/elasticsearch/issues/93007 which is just a performance issue on our ARM agents. This should be sorted out by ae073712255f5ea18a3b50b2545d8f96bd89ba21 which re-enabled the use of ramdisks on these tests and splits the job up.
