### ISSUE TITLE
[CI] ComponentTemplatesFileSettingsIT testSettingsApplied failing

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#93202]
**Build scan:**
https://gradle-enterprise.elastic.co/s/fhlif2cbt2zru/tests/:server:internalClusterTest/org.elasticsearch.reservedstate.service.ComponentTemplatesFileSettingsIT/testSettingsApplied

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.reservedstate.service.ComponentTemplatesFileSettingsIT.testSettingsApplied" -Dtests.seed=7E28C6E341B3E40E -Dtests.locale=lv-LV -Dtests.timezone=Atlantic/Canary -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.reservedstate.service.ComponentTemplatesFileSettingsIT&tests.test=testSettingsApplied

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: iterable with items ["template_1", "template_2", "template_other"] in any order
     but: no item matches: "template_1", "template_2", "template_other" in []

  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.reservedstate.service.ComponentTemplatesFileSettingsIT.assertClusterStateSaveOK(ComponentTemplatesFileSettingsIT.java:407)
  at org.elasticsearch.reservedstate.service.ComponentTemplatesFileSettingsIT.testSettingsApplied(ComponentTemplatesFileSettingsIT.java:549)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by tlrx** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/avbvq6wlaxqgs

I'll mute this test in main and 8.6 in #93300

**Comment by grcevski** [comment]
I believe the call I'm making to fetch index templates needs a retry. The state didn't seem to propagate on time. I see in the logs that we save the templates we are looking for:

```


1> [2023-01-27T05:25:15,717][INFO ][o.e.c.m.MetadataIndexTemplateService] [node_t1] adding component template [runtime_component_template] |  
-- | --
  | 1> [2023-01-27T05:25:15,718][INFO ][o.e.c.m.MetadataIndexTemplateService] [node_t1] adding component template [component_template1] |  
  | 1> [2023-01-27T05:25:15,720][INFO ][o.e.c.m.MetadataIndexTemplateService] [node_t1] adding component template [other_component_template] |  
  | 1> [2023-01-27T05:25:15,722][INFO ][o.e.c.m.MetadataIndexTemplateService] [node_t1] adding index template [template_other] for index patterns [foo*, mar*] |  
  | 1> [2023-01-27T05:25:15,725][INFO ][o.e.c.m.MetadataIndexTemplateService] [node_t1] adding index template [template_2] for index patterns [foo*, mar*] |  
  | 1> [2023-01-27T05:25:15,727][INFO ][o.e.c.m.MetadataIndexTemplateService] [node_t1] adding index template [template_1] for index patterns [te*, bar*]
```

I'll make a fix for this theory.
