### ISSUE TITLE
[CI] RegressionIT testAliasFields failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#93228]
**Build scan:**
https://gradle-enterprise.elastic.co/s/rsfjgfma4nzvw/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.RegressionIT/testAliasFields

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testAliasFields" -Dtests.seed=367A2E49A78E5CF0 -Dtests.locale=vi-VN -Dtests.timezone=America/Boa_Vista -Druntime.java=17
```

**Applicable branches:**
8.6

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.RegressionIT&tests.test=testAliasFields

**Failure excerpt:**
```
java.lang.AssertionError: Failure: failed for seed -3649934924374683238 modelId regression_alias_fields-1674608939425 numberTrees 31
6, 91.07589721679688
8, 91.07589721679688
12, 91.07589721679688
18, 91.07589721679688
20, 91.07589721679688
26, 91.07589754778364
32, 91.07589754778364
40, 93.29717254638672
44, 93.29717632426056
52, 103.92047882080078
56, 103.92047882080078
58, 103.92047882080078
68, 113.35578918457031
70, 113.35578918457031
72, 115.57756042480469
82, 125.96941375732422
96, 134.09567260742188
98, 134.09567260742188
108, 148.4807586669922
110, 148.4807586669922
114, 151.96612548828125
116, 154.78773498535156
122, 157.51113891601562
124, 157.51113891601562
128, 163.5010986328125
130, 165.22828294998882
132, 165.22828674316406
134, 165.22828674316406
138, 167.83270263671875
140, 167.83270263671875
142, 172.10374450683594
146, 179.54896545410156
150, 186.57464599609375
172, 198.60635375976562
174, 198.60635375976562
176, 198.60635375976562
184, 198.60635375976562
186, 216.27818298339844
192, 216.27818298339844
194, 217.7173614501953
198, 217.7173614501953
200, 222.1011199951172
202, 222.1011199951172
204, 225.87127685546875
212, 230.9076690673828
214, 230.9076690673828
216, 230.9076690673828
218, 230.9076690673828
220, 236.48526000976562
224, 237.1522216796875
226, 237.1522216796875
228, 237.1522216796875
234, 251.60301208496094
240, 251.60301208496094
248, 258.4667053222656
250, 260.91241455078125
256, 266.8401184082031
258, 266.8401184082031
264, 273.1229248046875
266, 273.1229248046875
270, 274.650390625
278, 284.79925537109375
280, 285.3653259277344
282, 286.52752685546875
284, 288.8528137207031
288, 290.98828125
292, 294.1017761230469
294, 295.4022521972656
304, 305.8304748535156
312, 309.0353088378906
316, 309.7676696777344
320, 319.1098327636719
322, 319.1098327636719
328, 322.1291198730469
330, 325.92657470703125
334, 326.7967834472656
340, 331.5297546386719
342, 336.26165771484375
344, 336.26165771484375
348, 340.44589894525984
350, 340.4458923339844
352, 342.30517578125
358, 342.30517578125
360, 353.0841979980469
364, 357.1208801269531
370, 358.3072814941406
372, 358.3072814941406
374, 360.43084716796875
376, 361.4158020019531
380, 366.3062438964844
384, 366.3062438964844
386, 366.30624280734963
392, 376.7645263671875
394, 376.7645263671875
400, 380.8804626464844
406, 380.8804626464844
410, 385.775634765625
412, 389.1502380371094
418, 398.87331159933615
434, 408.3974914550781
438, 410.7633486607134
442, 412.5696716308594
456, 424.721435546875
458, 424.721435546875
462, 424.721435546875
466, 438.5785217285156
470, 439.7493591308594
472, 439.7493591308594
476, 444.5861511230469
482, 444.5861511230469
484, 444.5861511230469
486, 444.5861511230469
488, 444.5861511230469
492, 444.5861511230469
494, 444.5861511230469
502, 462.90570068359375
508, 467.6964416503906
510, 467.6964285847914
516, 475.8819384975982
518, 477.8193664550781
520, 477.8193664550781
522, 477.8193664550781
528, 485.6568603515625
532, 485.6568603515625
550, 505.09197998046875
552, 505.09197998046875
556, 505.09197998046875
560, 507.28875732421875
566, 507.28875732421875
570, 507.28875732421875
578, 507.28875732421875
580, 507.28875732421875
582, 507.28875732421875
588, 507.28875732421875
596, 507.28875732421875
0, 91.07589721679688
2, 91.07589721679688
4, 91.07589721679688
10, 91.07589754778364
14, 91.07589721679688
16, 91.07589721679688
22, 91.07589721679688
24, 91.07589721679688
28, 91.07589721679688
30, 91.07589721679688
34, 91.07589721679688
36, 93.29717254638672
38, 93.29717254638672
42, 93.29717632426056
46, 93.29717254638672
48, 101.08650970458984
50, 103.92047815378922
54, 103.92047882080078
60, 111.65461730957031
62, 111.65461730957031
64, 113.35578918457031
66, 113.35578918457031
74, 120.39515686035156
76, 120.39515686035156
78, 123.0289306640625
80, 123.0289306640625
84, 131.3300018310547
86, 134.09567260742188
88, 134.09567260742188
90, 134.09567342393456
92, 134.09567342393456
94, 134.09567260742188
100, 143.41278076171875
102, 143.41278076171875
104, 145.3290252685547
106, 145.3290252685547
112, 151.96612548828125
118, 154.78772844207612
120, 154.78773498535156
126, 163.5010986328125
136, 167.83270263671875
144, 172.10374450683594
148, 180.84765625
152, 188.231689453125
154, 188.231689453125
156, 188.23169610756077
158, 190.60157775878906
160, 190.60157775878906
162, 193.2358856201172
164, 193.2358856201172
166, 196.28018188476562
168, 196.28018188476562
170, 198.60634899282414
178, 198.60635375976562
180, 198.60635375976562
182, 198.60635375976562
188, 216.27818298339844
190, 216.27818298339844
196, 217.7173614501953
206, 225.87127685546875
208, 225.87128326158648
210, 225.87127685546875
222, 237.15222574234386
230, 237.15222574234386
232, 237.1522216796875
236, 251.60301208496094
238, 251.60301278551708
242, 255.0328369140625
244, 255.0328369140625
246, 257.4420471191406
252, 260.91241455078125
254, 261.8101501464844
260, 267.8109436035156
262, 268.41552734375
268, 273.1229380017426
272, 274.650390625
274, 280.7827453613281
276, 284.79925537109375
286, 288.8528137207031
290, 290.98828125
296, 297.8836364746094
298, 298.6323547363281
300, 300.996826171875
302, 303.5665283203125
306, 306.6261291503906
308, 306.6261291503906
310, 306.6261291503906
314, 309.0353088378906
318, 314.5467224121094
324, 321.76513671875
326, 321.76513671875
332, 326.7967834472656
336, 331.5297413645342
338, 331.5297546386719
346, 336.26165771484375
354, 342.30517578125
356, 342.30517578125
362, 353.0841979980469
366, 358.3072814941406
368, 358.3072814941406
378, 366.3062438964844
382, 366.3062438964844
388, 369.5065002441406
390, 376.7645263671875
396, 379.1421203613281
398, 380.8804709049498
402, 380.8804626464844
404, 380.8804626464844
408, 385.775634765625
414, 389.1502380371094
416, 392.6734313964844
420, 398.8733215332031
422, 398.8733215332031
424, 398.8733215332031
426, 398.8733215332031
428, 398.8733215332031
430, 398.8733215332031
432, 406.03179931640625
436, 408.3974914550781
440, 410.7633361816406
444, 416.4531555175781
446, 420.0472106933594
448, 420.0472106933594
450, 420.0472106933594
452, 420.0472165799481
454, 423.5265808105469
460, 424.721435546875
464, 435.7550964355469
468, 438.5785217285156
474, 439.7493591308594
478, 444.5861511230469
480, 444.5861511230469
490, 444.5861582837896
496, 460.1521301269531
498, 460.1521301269531
500, 462.90570068359375
504, 462.90568589057955
506, 467.6964416503906
512, 467.6964416503906
514, 475.8819274902344
524, 483.6068115234375
526, 485.6568603515625
530, 485.6568603515625
534, 492.6369323730469
536, 494.2755126953125
538, 494.2755126953125
540, 496.8815002441406
542, 498.8656921386719
544, 498.8656921386719
546, 498.8656852248643
548, 503.2523193359375
554, 505.09197998046875
558, 507.28875732421875
562, 507.28875732421875
564, 507.28875732421875
568, 507.28875732421875
572, 507.28875732421875
574, 507.28875732421875
576, 507.28875732421875
584, 507.28875732421875
586, 507.28875732421875
590, 507.2887607525327
592, 507.28875732421875
594, 507.28875732421875
598, 507.28875732421875
downsample_factor: 0.3329621462120991
alpha: 1.6834204844050102
lambda: 1.418925871636634
gamma: 4.273157877719646
soft_tree_depth_limit: 10.199672344836365
soft_tree_depth_tolerance: 0.15
eta: 0.03901801608335273
eta_growth_rate_per_tree: 1.0195090080416764
max_trees: 30.0
feature_bag_fraction: 0.8

Expected: a value less than or equal to <3.0>
     but: <31.971443924494235> was greater than <3.0>

  at __randomizedtesting.SeedInfo.seed([367A2E49A78E5CF0:4481A27292116]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.xpack.ml.integration.RegressionIT.testAliasFields(RegressionIT.java:652)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by droberts195** [comment]
@valeriy42 I think this is the same as #90599, but on the 8.6 branch. The fix of #92868 was only made in the main branch. Please could you backport that same fix to 8.6 to silence the failures there too.

**Comment by droberts195** [comment]
This failed again on the `main` branch in https://gradle-enterprise.elastic.co/s/sajecywbmv5gc using code that contains the fix of #92868:

>```
> java.lang.AssertionError: Failure: failed for seed 1000 modelId regression_alias_fields-1675025581180 numberTrees 82
>```

@valeriy42 it seems like forcing the seed to 1000 does not make the test deterministic. Is there some portion of the C++ code that's using random sampling but not seeded? Please can you have another look.

**Comment by gmarouli** [comment]
Failed on `7.17` today: https://gradle-enterprise.elastic.co/s/ksulzjkho33po/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.RegressionIT/testAliasFields

**Comment by javanna** [comment]
Saw another failure today on a PR build against main.

**Comment by kingherc** [comment]
Also failed in https://gradle-enterprise.elastic.co/s/r33kmuawebce2 in main and also in 7.17 with https://gradle-enterprise.elastic.co/s/wsoiwwfvfbxjy/ with a different error:

```
java.lang.AssertionError: Accounting breaker not reset to 0 on node: {javaRestTest-1}{ldiR6v0tTvC64cAaxEXQVQ}{39Q8-HctTdid4TfEAvWGdA}{127.0.0.1}{127.0.0.1:44549}{cdfhilmrstw}{testattr=test, ml.machine_memory=101372276736, ml.max_open_jobs=512, xpack.installed=true, ml.max_jvm_size=536870912, transform.node=true} |  
-- | --
  | Expected: <0L> |  
  | but: was <1652L> |  



[2023-05-15T15:56:13,886][INFO ][o.e.x.m.i.RegressionIT   ] [testAliasFields] before test	
[2023-05-15T15:56:13,887][INFO ][o.e.x.m.i.RegressionIT   ] [testAliasFields] [RegressionIT#testAliasFields]: setting up test	
[2023-05-15T15:56:14,183][INFO ][o.e.x.m.i.RegressionIT   ] [testAliasFields] [RegressionIT#testAliasFields]: all set up test	
[2023-05-15T15:56:24,402][INFO ][o.e.x.m.i.RegressionIT   ] [testAliasFields] [RegressionIT#testAliasFields]: cleaning up after test	
[2023-05-15T15:56:24,775][INFO ][o.e.x.m.i.RegressionIT   ] [testAliasFields] after test	
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testAliasFields" -Dtests.seed=E48C1450B4C96CEB -Dtests.locale=he-IL -Dtests.timezone=America/Metlakatla -Druntime.java=20 -Dtests.fips.enabled=true
```

Will mute on main, 7.17.x and 8.8.x.

**Comment by droberts195** [comment]
The most recent failure, which caused the test to be muted, is completely different to the original failure. Marking as `medium-risk` for this second failure. The original failure is `low-risk`.
