### ISSUE TITLE
[CI] IndexFoldersDeletionListenerIT testListenersInvokedWhenIndexIsRelocated failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#93226]
**Build scan:**
https://gradle-enterprise.elastic.co/s/fzbi7zeynkfc4/tests/:server:internalClusterTest/org.elasticsearch.plugins.IndexFoldersDeletionListenerIT/testListenersInvokedWhenIndexIsRelocated

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.plugins.IndexFoldersDeletionListenerIT.testListenersInvokedWhenIndexIsRelocated" -Dtests.seed=BCC2C1704017CB6D -Dtests.locale=ru-RU -Dtests.timezone=America/Montreal -Druntime.java=8
```

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.plugins.IndexFoldersDeletionListenerIT&tests.test=testListenersInvokedWhenIndexIsRelocated

**Failure excerpt:**
```
java.lang.AssertionError: Expecting no shards deleted on node [node_t1] but got: {[feomlbaymz/hEzINmjPQAyAgksKgUOpMQ]=[[feomlbaymz][2]]}

  at __randomizedtesting.SeedInfo.seed([BCC2C1704017CB6D:723426E6EF14FAA7]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.elasticsearch.plugins.IndexFoldersDeletionListenerIT.assertNoDeletions(IndexFoldersDeletionListenerIT.java:430)
  at org.elasticsearch.plugins.IndexFoldersDeletionListenerIT.lambda$testListenersInvokedWhenIndexIsRelocated$1(IndexFoldersDeletionListenerIT.java:205)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1141)
  at org.elasticsearch.plugins.IndexFoldersDeletionListenerIT.testListenersInvokedWhenIndexIsRelocated(IndexFoldersDeletionListenerIT.java:179)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by idegtiarenko** [comment]
This test failed 3 times over the last 90 days:
https://gradle-enterprise.elastic.co/s/fzbi7zeynkfc4/tests/:server:internalClusterTest/org.elasticsearch.plugins.IndexFoldersDeletionListenerIT/testListenersInvokedWhenIndexIsRelocated/?top-execution=1
https://gradle-enterprise.elastic.co/s/zc2v2rribzehc/tests/:server:internalClusterTest/org.elasticsearch.plugins.IndexFoldersDeletionListenerIT/testListenersInvokedWhenIndexIsRelocated/?top-execution=1
https://gradle-enterprise.elastic.co/s/gblob4mxrjdcg/tests/:server:internalClusterTest/org.elasticsearch.plugins.IndexFoldersDeletionListenerIT/testListenersInvokedWhenIndexIsRelocated/?top-execution=1

Each time log contains:
```
[2022-11-03T13:48:02,149][WARN ][o.e.i.c.IndicesClusterStateService] [node_t4] [jxaeipbmqz][0] marking and sending shard failed due to [failed to create shard]
java.io.IOException: failed to obtain in-memory shard lock
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:513) ~[main/:?]
	at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:834) ~[main/:?]
	at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:175) ~[main/:?]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:594) ~[main/:?]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShard(IndicesClusterStateService.java:533) ~[main/:?]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createIndicesAndUpdateShards(IndicesClusterStateService.java:489) ~[main/:?]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:230) ~[main/:?]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:538) ~[main/:?]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:524) ~[main/:?]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:497) ~[main/:?]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428) ~[main/:?]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:710) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223) ~[main/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: org.elasticsearch.env.ShardLockObtainFailedException: [jxaeipbmqz][0]: obtaining shard lock for [starting shard] timed out after [5000ms], lock already held for [closing shard] with age [5000ms]
	at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:985) ~[main/:?]
	at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:885) ~[main/:?]
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:416) ~[main/:?]
```
This only happens on 7.17

**Comment by DaveCTurner** [comment]
I suspect there might be some unwanted rebalancing going on here, and opened https://github.com/elastic/elasticsearch/pull/93465 to add a little more logging to confirm this.

**Comment by idegtiarenko** [comment]
I checked 2 new failures, both time there are:
```
[2023-03-21T08:17:50,565][DEBUG][o.e.i.IndicesService     ] [node_t0] creating Index [[ikpczlqvga/iQEkvBdGSQ-jKt4GNNxRzQ]], shards [4]/[1] - reason [CREATE_INDEX]
[2023-03-21T08:17:50,917][INFO ][o.e.p.IndexFoldersDeletionListenerIT] [testListenersInvokedWhenIndexIsRelocated] --> excluding nodes [node_t3, node_t1]

[2023-03-21T08:17:56,132][WARN ][o.e.i.c.IndicesClusterStateService] [node_t2] [ikpczlqvga][2] marking and sending shard failed due to [failed to create shard]
java.io.IOException: failed to obtain in-memory shard lock
```

**Comment by idegtiarenko** [comment]
Shard is eventually created on the required node. 
I do not think we keep a shard allocation attempts anywhere in 7.17 and there is a way to permit a deletion if that was retried eventually

**Comment by arteam** [comment]
![Image](https://github.com/user-attachments/assets/ddab2977-276b-447e-bc3a-9db1dfbcb9ca)

This test hasn't failed over a month, so I'm going to close the issue and let the bot to re-open it if failures come back.
