### ISSUE TITLE
[CI] AzureSnapshotRepoTestKitIT testRepositoryAnalysis failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#93231]
**Build scan:**
https://gradle-enterprise.elastic.co/s/bilrug4gn63fo/tests/:x-pack:plugin:snapshot-repo-test-kit:qa:azure:javaRestTest/org.elasticsearch.repositories.blobstore.testkit.AzureSnapshotRepoTestKitIT/testRepositoryAnalysis

**Reproduction line:**
```
./gradlew ':x-pack:plugin:snapshot-repo-test-kit:qa:azure:javaRestTest' --tests "org.elasticsearch.repositories.blobstore.testkit.AzureSnapshotRepoTestKitIT.testRepositoryAnalysis" -Dtests.seed=171B654A63D2DDC8 -Dtests.locale=sl -Dtests.timezone=Brazil/DeNoronha -Druntime.java=17
```

**Applicable branches:**
8.6

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.repositories.blobstore.testkit.AzureSnapshotRepoTestKitIT&tests.test=testRepositoryAnalysis

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:46585], URI [_snapshot/repository?verify=true], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[repository] path [8.6_repository_test_kit_tests_171B654A63D2DDC8] is not accessible on master node"}],"type":"repository_verification_exception","reason":"[repository] path [8.6_repository_test_kit_tests_171B654A63D2DDC8] is not accessible on master node","caused_by":{"type":"reactive_exception","reason":"io.netty.channel.ConnectTimeoutException: connection timed out: elasticsearchci.blob.core.windows.net/20.60.221.196:443","caused_by":{"type":"connect_timeout_exception","reason":"connection timed out: elasticsearchci.blob.core.windows.net/20.60.221.196:443"},"suppressed":[{"type":"exception","reason":"#block terminated with an error"}]}},"status":500}

  at __randomizedtesting.SeedInfo.seed([171B654A63D2DDC8:EE26C424BD49EE21]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.test.rest.ESRestTestCase.registerRepository(ESRestTestCase.java:1742)
  at org.elasticsearch.test.rest.ESRestTestCase.registerRepository(ESRestTestCase.java:1733)
  at org.elasticsearch.repositories.blobstore.testkit.AbstractSnapshotRepoTestKitRestTestCase.testRepositoryAnalysis(AbstractSnapshotRepoTestKitRestTestCase.java:27)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by cbuescher** [comment]
This looks like a connection issue ("connection timed out: elasticsearchci.blob.core.windows.net/20.60.221.196:443"), however I'm opening this for inspection since I'm not sure if there is any infra work to be done here as a follow up. Please close if not.

**Comment by fcofdez** [comment]
It looks like a transient network error, only a subset of the Azure tests experimented this connection timeout. I'll keep this open for a couple of days to ensure that it's a transient error.

**Comment by fcofdez** [comment]
It looks like this was related to yesterday's Azure outage:
```
Azure Networking - Multiple regions - Mitigated (Tracking ID VSG1-B90)
Summary of Impact: Between 07:05 UTC and 09:45 UTC on 25 January 2023, customers experienced issues with networking connectivity, manifesting as network latency and/or timeouts when attempting to connect to Azure resources in Public Azure regions, as well as other Microsoft services including Microsoft 365 and PowerBI.
```
I'm closing this for now.
