### ISSUE TITLE
[CI] FullClusterRestartIT classMethod failing (SHA MessageDigest not available)

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#93403]
Many tests are failing repeatedly over the last couple of days. All have the same errors:

```
java.lang.RuntimeException: An error occurred orchestrating test cluster.
java.lang.RuntimeException: Elasticsearch process died while waiting for ports file. See console output for details.
fatal exception while booting Elasticsearch java.lang.InternalError: internal error: SHA-1 not available.
java.security.NoSuchAlgorithmException: SHA MessageDigest not available
```

Other tests classes failing include:

* FullClusterRestartIT
  * https://gradle-enterprise.elastic.co/s/ainmjkymgrwi6/tests/:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.upgrades.FullClusterRestartIT
  * https://gradle-enterprise.elastic.co/s/ainmjkymgrwi6/tests/:x-pack:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.xpack.restart.FullClusterRestartIT
  * https://gradle-enterprise.elastic.co/s/ainmjkymgrwi6/tests/:x-pack:plugin:shutdown:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.xpack.restart.FullClusterRestartIT
* QueryBuilderBWCIT
  * https://gradle-enterprise.elastic.co/s/ainmjkymgrwi6/tests/:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.upgrades.QueryBuilderBWCIT
  * https://gradle-enterprise.elastic.co/s/ainmjkymgrwi6/tests/:x-pack:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.xpack.restart.QueryBuilderBWCIT
* MlHiddenIndicesFullClusterRestartIT
  * https://gradle-enterprise.elastic.co/s/ainmjkymgrwi6/tests/:x-pack:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.xpack.restart.MlHiddenIndicesFullClusterRestartIT
* WatcherMappingUpdateIT
  * https://gradle-enterprise.elastic.co/s/ainmjkymgrwi6/tests/:x-pack:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.xpack.restart.WatcherMappingUpdateIT
* MLModelDeploymentFullClusterRestartIT
  * https://gradle-enterprise.elastic.co/s/ainmjkymgrwi6/tests/:x-pack:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT
* CoreFullClusterRestartIT
  * https://gradle-enterprise.elastic.co/s/ainmjkymgrwi6/tests/:x-pack:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.xpack.restart.CoreFullClusterRestartIT
* MlConfigIndexMappingsFullClusterRestartIT
  * https://gradle-enterprise.elastic.co/s/ainmjkymgrwi6/tests/:x-pack:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT

I note that their was a substantial change to the testing framework for these tests yesterday in https://github.com/elastic/elasticsearch/pull/93062, and so I'm assuming this is likely a `Team:Delivery` task.

**Build scan:**
https://gradle-enterprise.elastic.co/s/e6h3axr2tt2k4/tests/:qa:full-cluster-restart:v7.0.0%23bwcTest/org.elasticsearch.upgrades.FullClusterRestartIT

**Reproduction line:**
```
./gradlew ':x-pack:plugin:shutdown:qa:full-cluster-restart:v8.7.0#bwcTest' -Dtests.class="org.elasticsearch.xpack.restart.FullClusterRestartIT" -Dtests.seed=40081232D96C988C -Dtests.bwc=true -Dtests.locale=en-US -Dtests.timezone=Etc/UTC -Druntime.java=17 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.FullClusterRestartIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.RuntimeException: An error occurred orchestrating test cluster.

  at __randomizedtesting.SeedInfo.seed([EE9F3528C4D4D723]:0)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:225)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.writeUnicastHostsFile(LocalClusterHandle.java:206)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.waitUntilReady(LocalClusterHandle.java:149)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.start(LocalClusterHandle.java:70)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:41)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.RuntimeException: Elasticsearch process died while waiting for ports file. See console output for details.

    at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.lambda$waitUntilReady$0(LocalClusterFactory.java:193)
    at org.elasticsearch.test.cluster.util.Retry.lambda$retryUntilTrue$0(Retry.java:33)
    at org.elasticsearch.test.cluster.util.Retry.lambda$getValueWithTimeout$1(Retry.java:47)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by craigtaverner** [comment]
On the suggestion of @pgomulka , I tried reverting https://github.com/elastic/elasticsearch/pull/93355, but the same failure occurred in my local test.

**Comment by craigtaverner** [comment]
Reverting the PR https://github.com/elastic/elasticsearch/pull/93062 allows the test to pass locally, so this appears to be the culprit for these failures.
