### ISSUE TITLE
Abnormal startup of elastic 7.3

### ISSUE THREAD

**Issue by asdas123123-svg** [elastic/elasticsearch#93487]
Yesterday, a node of elasitcsearch suddenly went down abnormally. The following problems occurred when I tried to restart.
-------------------  The exceptions are as follows -------------------------------------
[2023-02-03T10:18:02,912][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-01] fatal error in thread [main], exiting
java.lang.StackOverflowError: null
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.addName(UTF8StreamJsonParser.java:2314) ~[jackson-core-2.8.11.jar:2.8.11]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseEscapedName(UTF8StreamJsonParser.java:2034) ~[jackson-core-2.8.11.jar:2.8.11]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseName(UTF8StreamJsonParser.java:1925) ~[jackson-core-2.8.11.jar:2.8.11]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1742) ~[jackson-core-2.8.11.jar:2.8.11]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:776) ~[jackson-core-2.8.11.jar:2.8.11]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:52) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readGenericMap(AbstractXContentParser.java:335) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:322) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.lambda$readMap$0(AbstractXContentParser.java:322) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readGenericMap(AbstractXContentParser.java:342) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:322) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.lambda$readMap$0(AbstractXContentParser.java:322) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readGenericMap(AbstractXContentParser.java:342) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:322) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.lambda$readMap$0(AbstractXContentParser.java:322) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readGenericMap(AbstractXContentParser.java:342) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:322) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.lambda$readMap$0(AbstractXContentParser.java:322) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readGenericMap(AbstractXContentParser.java:342) ~[elasticsearch-x-content-7.3.0.jar:7.3.0]

**Comment by asdas123123-svg** [comment]
Check the logs and find the logs before the outage
---------------------------------
[2023-02-02T16:39:42,985][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-01] fatal error in thread [elasticsearch[node-01][masterService#updateTask][T#1]], exiting
java.lang.StackOverflowError: null
	at java.util.Collections$UnmodifiableMap.get(Collections.java:1454) ~[?:1.8.0_144]
	at org.elasticsearch.index.mapper.Mapper$TypeParser$ParserContext.typeParser(Mapper.java:121) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:270) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:196) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parse(ObjectMapper.java:169) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:276) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:196)

**Comment by dnhatn** [comment]
Did you increase the `index.mapping.depth.limit` setting? I think this happened because you have too many level mappings? You might temporarily increase the stack size (by adding `-Xss2m` to the `jvm.options` file in the `config` directory) to bring the cluster back. I would suggest you fix the issue and remove the workaround stack size setting as it's not recommended.  I hope you don't mind that I close this as we use GitHub for verified bug reports, feature requests, and pull requests. You can continue this issue on [forums](https://discuss.elastic.co/) where you should be able to get help.

**Comment by asdas123123-svg** [comment]
Thank you for your answer. I have been able to restore the cluster.
