### ISSUE TITLE
[CI] MlConfigIndexMappingsFullClusterRestartIT classMethod failing

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#93504]
Only `windows compatibility` tests seem to be affected.

**Build scan:**
https://gradle-enterprise.elastic.co/s/cgx2tizw623lo/tests/:x-pack:qa:full-cluster-restart:v7.17.10%23bwcTest/org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT

**Reproduction line:**
```
null
```

**Applicable branches:**
main, 8.6

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.RuntimeException: An error occurred orchestrating test cluster.

  at __randomizedtesting.SeedInfo.seed([361F1CF1ABC770D1]:0)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:225)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.writeUnicastHostsFile(LocalClusterHandle.java:206)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.waitUntilReady(LocalClusterHandle.java:149)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.start(LocalClusterHandle.java:70)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:41)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

  Caused by: java.lang.RuntimeException: Elasticsearch process died while waiting for ports file. See console output for details.

    at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.lambda$waitUntilReady$3(LocalClusterFactory.java:197)
    at org.elasticsearch.test.cluster.util.Retry.lambda$retryUntilTrue$0(Retry.java:33)
    at org.elasticsearch.test.cluster.util.Retry.lambda$getValueWithTimeout$1(Retry.java:47)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at java.lang.Thread.run(Thread.java:1589)

```

**Comment by droberts195** [comment]
There are more interesting errors further down the log:

```
Error: loading: C:\Users\jenkins\workspace\platform-support\650\x-pack\qa\full-cluster-restart\build\testrun\v7.17.10_bwcTest\temp\org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT\test-cluster\test-cluster-0\distro\7.17.10\jdk\bin\server\jvm.dll
Error: loading: C:\Users\jenkins\workspace\platform-support\650\x-pack\qa\full-cluster-restart\build\testrun\v7.17.10_bwcTest\temp\org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT\test-cluster\test-cluster-1\distro\7.17.10\jdk\bin\server\jvm.dll
```

@mark-vieira this started happening the day that https://github.com/elastic/elasticsearch/pull/93477 and https://github.com/elastic/elasticsearch/commit/925a6dcbcc2971a027bc46b057f639acd4ed9cdd were merged.

`C:\Users\jenkins\workspace\platform-support\650\x-pack\qa\full-cluster-restart\build\testrun\v7.17.10_bwcTest\temp\org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT\test-cluster\test-cluster-1\distro\7.17.10\jdk\bin\server\jvm.dll` is 254 characters long. `MAX_PATH` on Windows is 260. So that file should be OK, but I am wondering if the reason that `jvm.dll` doesn't load is that it in turn depends on a DLL in the same directory with a file name that's 7+ characters longer.

If that guess is correct then we could fix this by shortening the name of the test class. But if this is affecting other tests too and there's a more generic solution on the way then we won't do that.

**Comment by mark-vieira** [comment]
Yeah, these Windows issues boil down to the fact that, at lest when using `ProcessBuilder`, it won't work if the path to the target executable is longer than 255 characters. I've tried all sort of workaround like trying to place the directory the executable is in on the path, but no-go. Basically all information on these limitation just say "make the path shorter". It's positively maddening.

I have an open PR to simply make the path lengths shorter and avoid this. https://github.com/elastic/elasticsearch/pull/93570

**Comment by mark-vieira** [comment]
This should be addressed by https://github.com/elastic/elasticsearch/pull/93570

**Comment by kingherc** [comment]
Re-occurred on 8.6 : https://gradle-enterprise.elastic.co/s/yksd3dkzz35os

**Comment by kingherc** [comment]
Not sure if 8.6 CI is still relevant, feel free to close if it is not.

**Comment by kingherc** [comment]
Another one at https://gradle-enterprise.elastic.co/s/ykqouonvqmfng for 8.7

**Comment by kingherc** [comment]
Can we somehow mute this?

**Comment by droberts195** [comment]
It's failing because `assertBusy` only loops on `AssertionError`, not `ElasticsearchStatusException`. We just need to make it catch `ElasticsearchStatusException` and convert to `AssertionError` so it waits for the right situation as expected. Should be a quick fix.

**Comment by droberts195** [comment]
It must be a different reason now as the most recent failure is on Unix, not Windows.

**Comment by kingherc** [comment]
I am on test triaging today, and I'm seeing a bunch of similar failures `java.lang.RuntimeException: Elasticsearch process died while waiting for ports file. See console output for details.` on other non-ML full cluster restart ones. So I'll re-close this and keep https://github.com/elastic/elasticsearch/issues/93630 as the "master ticket" for such errors for now.
