### ISSUE TITLE
[CI] MLModelDeploymentFullClusterRestartIT.testDeploymentSurvivesRestart failing

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#93529]
### CI Link

https://gradle-enterprise.elastic.co/s/kxbmgd2hfgn5c

### Repro line

 ./gradlew ':x-pack:qa:full-cluster-restart:v8.4.0#bwcTest' -Dtests.class="org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT" -Dtests.method="testDeploymentSurvivesRestart {cluster=UPGRADED}" -Dtests.seed=D0279276514CA6ED -Dtests.bwc=true -Dtests.locale=ru -Dtests.timezone=America/Belize -Druntime.java=17

### Does it reproduce?

Didn't try

### Applicable branches

main 8.6

### Failure history

[Gradle Enterprise](https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT&tests.test=testDeploymentSurvivesRestart%20%7Bcluster%3DUPGRADED%7D)
### Failure excerpt

[2023-02-05T15:06:16,211][ERROR][o.e.i.g.GeoIpDownloader  ] [test-cluster-1] error downloading geoip database [GeoLite2-City.mmdb] org.elasticsearch.node.NodeClosedException: node closed {test-cluster-1}{77gZQnAFQiSWY92948d6Ng}{wxxdHNpCT6GWif-Y3FJkgA}{test-cluster-1}{127.0.0.1}{127.0.0.1:36535}{cdfhilmrstw}{ml.machine_memory=101250146304, testattr=test, xpack.installed=true, ml.max_jvm_size=536870912, ml.allocated_processors=32}
	at org.elasticsearch.server@8.4.3/org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onClusterServiceClose(TransportReplicationAction.java:1026)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onClusterServiceClose(ClusterStateObserver.java:338)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onClose(ClusterStateObserver.java:245)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.cluster.service.ClusterApplierService.addTimeoutListener(ClusterApplierService.java:254)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:177)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:118)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:110)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retry(TransportReplicationAction.java:1018)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleException(TransportReplicationAction.java:997)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1390)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.transport.TransportService.doStop(TransportService.java:364)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:63)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.node.Node.stop(Node.java:1383)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.node.Node.close(Node.java:1402)
	at org.elasticsearch.base@8.4.3/org.elasticsearch.core.IOUtils.close(IOUtils.java:71)
	at org.elasticsearch.base@8.4.3/org.elasticsearch.core.IOUtils.close(IOUtils.java:87)
	at org.elasticsearch.base@8.4.3/org.elasticsearch.core.IOUtils.close(IOUtils.java:63)
	at org.elasticsearch.server@8.4.3/org.elasticsearch.bootstrap.Elasticsearch.shutdown(Elasticsearch.java:446)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by joegallo** [comment]
https://gradle-enterprise.elastic.co/s/bxfbvk7qhbqwk/tests/:x-pack:qa:full-cluster-restart:v8.6.2%23bwcTest/org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT/testDeploymentSurvivesRestart%20%7Bcluster=UPGRADED%7D?top-execution=1 seems like another bite from this one today.

**Comment by davidkyle** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/93566
