### ISSUE TITLE
[CI] FullClusterRestartIT classMethod failing

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#93630]
Similar to https://github.com/elastic/elasticsearch/issues/93504 but now not related to ML.

Marking it for Delivery team due to PR https://github.com/elastic/elasticsearch/pull/93477 that may be related

**Build scan:**
https://gradle-enterprise.elastic.co/s/alt6kcpebfsdk/tests/:x-pack:qa:full-cluster-restart:v8.7.0%23bwcTest/org.elasticsearch.xpack.restart.FullClusterRestartIT

**Reproduction line:**
```
null
```

**Applicable branches:**
8.7

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.restart.FullClusterRestartIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.RuntimeException: An error occurred orchestrating test cluster.

  at __randomizedtesting.SeedInfo.seed([CEDA55DA1CD14E93]:0)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:225)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.writeUnicastHostsFile(LocalClusterHandle.java:206)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.waitUntilReady(LocalClusterHandle.java:149)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.start(LocalClusterHandle.java:70)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:38)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.RuntimeException: Elasticsearch process died while waiting for ports file. See console output for details.

    at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.lambda$waitUntilReady$0(LocalClusterFactory.java:201)
    at org.elasticsearch.test.cluster.util.Retry.lambda$retryUntilTrue$0(Retry.java:33)
    at org.elasticsearch.test.cluster.util.Retry.lambda$getValueWithTimeout$1(Retry.java:47)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by kingherc** [comment]
Can we somehow mute this?

**Comment by kingherc** [comment]
Another one at 8.6 : https://gradle-enterprise.elastic.co/s/2qnzoofbrjq4k

**Comment by kingherc** [comment]
I am on test triaging today, and I'm seeing a bunch of similar full cluster restart errors in various ES versions. See e.g.
https://github.com/elastic/elasticsearch/issues/93629 -- CoreFullClusterRestartIT
https://github.com/elastic/elasticsearch/issues/93504 -- MlConfigIndexMappingsFullClusterRestartIT
https://gradle-enterprise.elastic.co/s/zu3mznr7dtp6u -- org.elasticsearch.xpack.restart.QueryBuilderBWCIT > classMethod 
I'm keeping this ticket open as the "master ticket" for now.

@elastic/es-delivery I think this may be related to your team. Is there a way to swiftly resolve or mute these? Thanks

**Comment by kingherc** [comment]
Another 7.17 one at https://gradle-enterprise.elastic.co/s/lksqtjubibgxg and https://gradle-enterprise.elastic.co/s/gz7z54mh23fra for EnableSecurityOnBasicLicenseIT » classMethod

**Comment by kingherc** [comment]
Another 8.7 one at https://gradle-enterprise.elastic.co/s/hnq24pvlasn7s

**Comment by droberts195** [comment]
The most recent ML test failure contains this:

```
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,level,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

So I suspect the problem is that one of those options only works with some of the versions of Java we support, not all of them.

**Comment by mark-vieira** [comment]
I've opened a PR to capture some more diagnostics here to try and sort out why this is only happening occasionally.

https://github.com/elastic/elasticsearch/pull/93661

**Comment by mark-vieira** [comment]
Ok I tracked this down to us mistakenly attempting to write GC log to the same location from multiple running clusters. That would explain the flaky behavior and my suspicion this was a type of race condition was right. I've opened https://github.com/elastic/elasticsearch/pull/93672 to address this.
