### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=tsdb/25_id_generation/delete over _bulk} failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#93852]
**Build scan:**
https://gradle-enterprise.elastic.co/s/zkvkcwngxe5su/tests/:qa:mixed-cluster:v8.3.3%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=tsdb%2F25_id_generation%2Fdelete%20over%20_bulk%7D

**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v8.3.3#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=tsdb/25_id_generation/delete over _bulk}" -Dtests.seed=576481A12D47BB1F -Dtests.bwc=true -Dtests.locale=ar-AE -Dtests.timezone=Europe/Warsaw -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dtsdb/25_id_generation/delete%20over%20_bulk%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [tsdb/25_id_generation:348]: field [items.0.delete.result] is null

  at __randomizedtesting.SeedInfo.seed([576481A12D47BB1F:DF30BE7B83BBD6E7]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:547)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:499)
  at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.AssertionError: field [items.0.delete.result] is null

    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertNotNull(Assert.java:712)
    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:78)
    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:527)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:499)
    at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(null:-1)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by gmarouli** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/3n524ujls6lgy/tests/:qa:mixed-cluster:v8.6.2%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=tsdb%2F25_id_generation%2Fdelete%20over%20_bulk%7D

**Comment by iverase** [comment]
Another: https://gradle-enterprise.elastic.co/s/dmi6rfw7ye55e

**Comment by craigtaverner** [comment]
Another one: https://gradle-enterprise.elastic.co/s/zkvkcwngxe5su/tests/:qa:mixed-cluster:v8.3.3%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=tsdb%2F25_id_generation%2Fdelete%20over%20_bulk%7D?top-execution=1

**Comment by martijnvg** [comment]
Looking at several failures, the returned bulk response is interesting:

```
[2023-02-28T14:10:39,073][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{ |  
-- | --
  | "stash" : { |  
  | "body" : { |  
  | "took" : 22, |  
  | "errors" : true, |  
  | "items" : [ |  
  | { |  
  | "delete" : { |  
  | "_index" : "test", |  
  | "_id" : "cn4exTOUtxytuLkQAAABeRnR_mY", |  
  | "status" : 500, |  
  | "error" : { |  
  | "type" : "null_pointer_exception", |  
  | "reason" : "Cannot invoke \"org.apache.lucene.index.PointValues.getMinPackedValue()\" because \"tsPointValues\" is null" |  
  | } |  
  | } |  
  | }, |  
  | { |  
  | "delete" : { |  
  | "_index" : "test", |  
  | "_id" : "cZZNs4NdV58ePSPIAAABeRnSA5M", |  
  | "status" : 500, |  
  | "error" : { |  
  | "type" : "null_pointer_exception", |  
  | "reason" : "Cannot invoke \"org.apache.lucene.index.PointValues.getMinPackedValue()\" because \"tsPointValues\" is null" |  
  | } |  
  | } |  
  | }, |  
  | { |  
  | "delete" : { |  
  | "_index" : "test", |  
  | "_id" : "not found ++ not found", |  
  | "status" : 404, |  
  | "error" : { |  
  | "type" : "resource_not_found_exception", |  
  | "reason" : "invalid id [not found ++ not found] for index [test] in time series mode" |  
  | } |  
  | } |  
  | } |  
  | ] |  
  | } |  
  | } |  
  | }]
```

The bulk requests should delete 2 documents, but that results into a NPE. This looks like a real bug.

**Comment by martijnvg** [comment]
The NPE occurs in `PerThreadIDVersionAndSeqNoLookup` line 98. The `tsPointValues` variable is null.

This means no documents exist that have a `@timestamp` field. Maybe the one of the shards is empty. Maybe the documents to be deleted never got indexed?  These documents should get indexed via the test setup. 

If the bulk api fails to index one of the documents then we never know, since bulk just returns a 200 response (with failures in response body), but that doesn't make the yaml test fail (there are no assertion is the setup section). I will add additional assertions to check whether the documents we index actually exist.

**Comment by martijnvg** [comment]
Maybe the real fix is do wrap lines 99 and 100 into a not null check. But I like to get prove what exactly caused this NPE. As I'm unable to reproduce locally.

**Comment by pgomulka** [comment]
https://gradle-enterprise.elastic.co/s/n64uqabfpeqze/tests/:qa:mixed-cluster:v8.6.3%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=tsdb%2F25_id_generation%2Fdelete%20over%20_bulk%7D?top-execution=1

https://gradle-enterprise.elastic.co/s/mz43fqo4mkz7y/tests/:qa:mixed-cluster:v8.2.2%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=tsdb%2F25_id_generation%2Fdelete%20over%20_bulk%7D?top-execution=1

https://gradle-enterprise.elastic.co/s/c75j5vzitlcl6/tests/:qa:mixed-cluster:v8.6.2%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=tsdb%2F25_id_generation%2Fdelete%20over%20_bulk%7D?top-execution=1

**Comment by iverase** [comment]
More failures:

https://gradle-enterprise.elastic.co/s/dqi2qc7gmxwqu
https://gradle-enterprise.elastic.co/s/pttp67sxwx656
https://gradle-enterprise.elastic.co/s/pazwjw7osg64m
https://gradle-enterprise.elastic.co/s/x4rnosvgzr3xw

**Comment by valeriy42** [comment]
https://gradle-enterprise.elastic.co/s/jqkytmyz5pga2

**Comment by xyu** [comment]
We have run into this problem on our production TSDS metrics cluster, not sure if it helps but we were able to trigger this error we performed the following actions:

1. Index some metrics for a given `@timestamp` value and set of dimensions via the `_bulk` API
2. Some time later run a `_delete_by_query` for a timestamp range that encompass the `@timestamp` (with a `bool` => `filter` => `range` => `@timestamp` query)
3. Try and reindex docs with the same `@timestamp` value and set of dimensions but updated metrics via the `_bulk` API

**Comment by xyu** [comment]
Some more context, I've recreated the TSDS index and changed the way we index into it by forcing a `_refresh` after both the `_delete_by_query` call as well as Bulk API calls and we have not encountered this issue again. It's still early so not sure if this mitigation strategy is working or we're just lucky. Another note, we could not reproduce this on a 1 node test cluster (replicas:0) so seems like something is wonky with requests hitting different replicas / nodes without refreshes.

**Comment by xyu** [comment]
Another update we encountered this issue again even with forced `_refresh` calls.

**Comment by hendrikmuhs** [comment]
another one: https://gradle-enterprise.elastic.co/s/d34kv7p3vssi4

**Comment by gmarouli** [comment]
another one: https://gradle-enterprise.elastic.co/s/a22s3ufttsrlw/tests/:qa:mixed-cluster:v8.7.1%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=tsdb%2F25_id_generation%2Fdelete%20over%20_bulk%7D?top-execution=1

**Comment by xyu** [comment]
I think this may have been fixed by #96461
