### ISSUE TITLE
[CI] PartiallyCachedShardAllocationIntegTests testPartialSearchableSnapshotNotAllocatedToNodesWithoutCache failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#93868]
**Build scan:**
https://gradle-enterprise.elastic.co/s/j3hbfj6vmofsa/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.cache.shared.PartiallyCachedShardAllocationIntegTests/testPartialSearchableSnapshotNotAllocatedToNodesWithoutCache

**Reproduction line:**
```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.cache.shared.PartiallyCachedShardAllocationIntegTests.testPartialSearchableSnapshotNotAllocatedToNodesWithoutCache" -Dtests.seed=BC14612E85D1CBD8 -Dtests.locale=und -Dtests.timezone=America/Atikokan -Druntime.java=17
```

**Applicable branches:**
8.7

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.searchablesnapshots.cache.shared.PartiallyCachedShardAllocationIntegTests&tests.test=testPartialSearchableSnapshotNotAllocatedToNodesWithoutCache

**Failure excerpt:**
```
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.snapshots.RestoreInfo.successfulShards()" because the return value of "org.elasticsearch.action.admin.cluster.snapshots.restore.RestoreSnapshotResponse.getRestoreInfo()" is null

  at __randomizedtesting.SeedInfo.seed([BC14612E85D1CBD8:2228D7173DF88D09]:0)
  at org.elasticsearch.xpack.searchablesnapshots.cache.shared.PartiallyCachedShardAllocationIntegTests.testPartialSearchableSnapshotNotAllocatedToNodesWithoutCache(PartiallyCachedShardAllocationIntegTests.java:109)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by gmarouli** [comment]
One more: https://gradle-enterprise.elastic.co/s/qwarlzsg5a2ga/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.cache.shared.PartiallyCachedShardAllocationIntegTests/testPartialSearchableSnapshotNotAllocatedToNodesWithoutCache?top-execution=1

**Comment by csoulios** [comment]
Failed again today https://gradle-enterprise.elastic.co/s/hiut7bqdroqmg

Same failing test, different error: 

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.cache.shared.PartiallyCachedShardAllocationIntegTests.testPartialSearchableSnapshotNotAllocatedToNodesWithoutCache" -Dtests.seed=4133B3E6CCD9B61B -Dtests.locale=zh-HK -Dtests.timezone=America/Rankin_Inlet -Druntime.java=17

org.elasticsearch.xpack.searchablesnapshots.cache.shared.PartiallyCachedShardAllocationIntegTests > testPartialSearchableSnapshotNotAllocatedToNodesWithoutCache FAILED
    java.lang.Exception: Test abandoned because suite timeout was reached.
        at __randomizedtesting.SeedInfo.seed([4133B3E6CCD9B61B]:0)

REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.cache.shared.PartiallyCachedShardAllocationIntegTests.testPartialSearchableSnapshotNotAllocatedToNodesWithoutCache" -Dtests.seed=4133B3E6CCD9B61B -Dtests.locale=zh-HK -Dtests.timezone=America/Rankin_Inlet -Druntime.java=17

org.elasticsearch.xpack.searchablesnapshots.cache.shared.PartiallyCachedShardAllocationIntegTests > classMethod FAILED
    java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
        at __randomizedtesting.SeedInfo.seed([4133B3E6CCD9B61B]:0)
```

**Comment by original-brownbear** [comment]
@arteam the timeout version of this failure is rather easily reproducible by putting a breakpoint for the current thread in `org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceShardsAllocator#submitReconcileTask` and waiting a few seconds before allowing it to submit the task. That way we get stuck in the infinite wait every time in my testing.

**Comment by csoulios** [comment]
@arteam let me know if you want me to mute the test https://github.com/elastic/elasticsearch/pull/94073
Added you as reviewer

**Comment by arteam** [comment]
[2023-03-02T11:38:11,069][INFO ][o.e.c.r.a.AllocationService] [node_s1] current.health="RED" message="Cluster health status changed from [YELLOW] to [RED] (reason: [snapshot shard size updated])." previous.health="YELLOW" reason="snapshot shard size updated"

**Comment by craigtaverner** [comment]
Another timed out version of this failure at https://gradle-enterprise.elastic.co/s/zuyhwmsmtmcei/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.cache.shared.PartiallyCachedShardAllocationIntegTests/testPartialSearchableSnapshotNotAllocatedToNodesWithoutCache?top-execution=1

The last message before timeout:

```
  | [2023-04-04T11:59:12,477][INFO ][o.e.c.r.a.AllocationService] [node_s0] current.health="RED" message="Cluster health status changed from [YELLOW] to [RED] (reason: [snapshot shard size updated])." previous.health="YELLOW" reason="snapshot shard size updated"
```

**Comment by idegtiarenko** [comment]
It could be fixed by https://github.com/elastic/elasticsearch/pull/97929.
I will close it if there are no new failures in couple of weeks.

**Comment by idegtiarenko** [comment]
I was able to confirm that above pr fixes this test.
