### ISSUE TITLE
[CI] WatcherMappingUpdateIT classMethod failing

### ISSUE THREAD

**Issue by gmarouli** [elastic/elasticsearch#93994]
Same with the following tests:

- [FullClusterRestartIT » classMethod](https://gradle-enterprise.elastic.co/s/3tsuuk6mskbgg/tests/:x-pack:qa:full-cluster-restart:v6.1.1%23bwcTest/org.elasticsearch.xpack.restart.FullClusterRestartIT)
- [FullClusterRestartSettingsUpgradeIT » classMethod](https://gradle-enterprise.elastic.co/s/dmq7jhbqtfdas/tests/:x-pack:qa:full-cluster-restart:v6.2.3%23bwcTest/org.elasticsearch.xpack.restart.FullClusterRestartSettingsUpgradeIT)

**Build scan:**
https://gradle-enterprise.elastic.co/s/3tsuuk6mskbgg/tests/:x-pack:qa:full-cluster-restart:v6.1.1%23bwcTest/org.elasticsearch.xpack.restart.WatcherMappingUpdateIT

**Reproduction line:**
```
null
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.restart.WatcherMappingUpdateIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.RuntimeException: Execution of elasticsearch-plugin failed with exit code 74

  at __randomizedtesting.SeedInfo.seed([6A12AC0C75EEBD97]:0)
  at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.runToolScript(LocalClusterFactory.java:641)
  at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.lambda$installPlugins$24(LocalClusterFactory.java:490)
  at java.util.ArrayList.forEach(ArrayList.java:1511)
  at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.installPlugins(LocalClusterFactory.java:490)
  at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.start(LocalClusterFactory.java:126)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.start(LocalClusterHandle.java:70)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:38)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by mark-vieira** [comment]
This looks to be an ephermeral error attempting to install xpack in an older cluster.

```
[2023-02-21T06:13:15,149][INFO ][process-output           ] [[elasticsearch-plugin]] ERROR: SHA-512 mismatch, expected 9041f4984b950381c188ffd51769c6dba6abf2d9b160bf428b21939331bac59953e5a0d62fc10b6a82a7f0479b27806c55527127985a455e0a0763c3a97975a8 but got 19f52d7e7571107dfe8082890591a4ea9b2bf735b1cd885388953d28fac8492f9b12f5cddbb6ea9e76ce0bb9273710aef106d04ae33747b41cc350024b779284
```

This test is passing again so I'm calling this good.
