### ISSUE TITLE
Shard failing to load with `Index -65536 out of bounds for length 66192`

### ISSUE THREAD

**Issue by ezorita** [elastic/elasticsearch#94077]
### Elasticsearch Version

8.4

### Installed Plugins

elastiknn 8.4

### Java Version

_bundled_

### OS Version

Amazon Linux 2

### Problem Description

While indexing, one of the shards failed (and now fails to load) with the error below. Any ideas what could cause that? To my understanding this is an overflow somewhere in the Lucene segment, is it possible that an excessive segment size is causing this?

Thanks,

```
failed shard on node [NE6jQiShQHSqYnAjVKS0mw]: shard failure, reason [index id[63669288] origin[LOCAL_TRANSLOG_RECOVERY] seq#[172671]], failure java.lang.ArrayIndexOutOfBoundsException: Index -65536 out of bounds for length 66192
    at org.apache.lucene.index.TermsHashPerField.writeByte(TermsHashPerField.java:219)
    at org.apache.lucene.index.TermsHashPerField.writeVInt(TermsHashPerField.java:264)
    at org.apache.lucene.index.FreqProxTermsWriterPerField.writeProx(FreqProxTermsWriterPerField.java:86)
    at org.apache.lucene.index.FreqProxTermsWriterPerField.addTerm(FreqProxTermsWriterPerField.java:197)
    at org.apache.lucene.index.TermsHashPerField.positionStreamSlice(TermsHashPerField.java:212)
    at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:200)
    at org.apache.lucene.index.IndexingChain$PerField.invert(IndexingChain.java:1224)
    at org.apache.lucene.index.IndexingChain.processField(IndexingChain.java:733)
    at org.apache.lucene.index.IndexingChain.processDocument(IndexingChain.java:620)
    at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:241)
    at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:432)
    at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1532)
    at org.apache.lucene.index.IndexWriter.softUpdateDocuments(IndexWriter.java:1577)
    at org.elasticsearch.index.engine.InternalEngine.updateDocs(InternalEngine.java:1364)
    at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:1177)
    at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:984)
    at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:1041)
    at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:974)
    at org.elasticsearch.index.shard.IndexShard.applyTranslogOperation(IndexShard.java:1792)
    at org.elasticsearch.index.shard.IndexShard.runTranslogRecovery(IndexShard.java:1840)
    at org.elasticsearch.index.shard.IndexShard.lambda$openEngineAndRecoverFromTranslog$13(IndexShard.java:1888)
    at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:493)
    at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:468)
    at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:113)
    at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1897)
    at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:463)
    at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90)
    at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:462)
    at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:88)
    at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:2241)
    at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:769)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

### Steps to Reproduce

I can't reproduce this since this happened after indexing 13TB of data.

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
