### ISSUE TITLE
org.elasticsearch.discovery.MasterDisruptionIT.testMasterNodeGCs fails with JDK 20 EA builds

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#94070]
reproduce with:
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.discovery.MasterDisruptionIT.testMasterNodeGCs"`

Excerpt from the log:
```
  1> java.lang.UnsupportedOperationException: null
  1>    at java.lang.Thread.resume(Thread.java:1882) ~[?:?]
  1>    at org.elasticsearch.test.disruption.LongGCDisruption.resumeThreads(LongGCDisruption.java:346) ~[framework-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
  1>    at org.elasticsearch.test.disruption.IntermittentLongGCDisruption.simulateLongGC(IntermittentLongGCDisruption.java:82) ~[framework-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
  1>    at org.elasticsearch.test.disruption.IntermittentLongGCDisruption$BackgroundWorker.run(IntermittentLongGCDisruption.java:93) ~[framework-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
```

Resulting from a JDK 20 change that degrades `Thread::resume` to unconditionally throw UOE,  see https://bugs.openjdk.org/browse/JDK-8249627

**Comment by DaveCTurner** [comment]
https://github.com/elastic/elasticsearch/issues/93707 is the same thing I think

**Comment by ChrisHegarty** [comment]
Oops, closing this dup!
