### ISSUE TITLE
[CI] TransportClusterStateActionDisruptionIT testNonLocalRequestAlwaysFindsMaster failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#94221]
I have tried in main and 8,7

**Build scan:**
https://gradle-enterprise.elastic.co/s/pakrvbvsl6zhu/tests/:server:internalClusterTest/org.elasticsearch.action.admin.cluster.state.TransportClusterStateActionDisruptionIT/testNonLocalRequestAlwaysFindsMaster

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.cluster.state.TransportClusterStateActionDisruptionIT.testNonLocalRequestAlwaysFindsMaster" -Dtests.seed=63D96EFD66FB3674 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=bg-BG -Dtests.timezone=Brazil/East -Druntime.java=17
```

**Applicable branches:**
8.7

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.admin.cluster.state.TransportClusterStateActionDisruptionIT&tests.test=testNonLocalRequestAlwaysFindsMaster

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=221, name=elasticsearch[node_t0][management][T#1], state=RUNNABLE, group=TGRP-TransportClusterStateActionDisruptionIT]

  at __randomizedtesting.SeedInfo.seed([63D96EFD66FB3674:1D064C94735DE0D9]:0)

  Caused by: java.lang.AssertionError: (No message provided)

    at __randomizedtesting.SeedInfo.seed([63D96EFD66FB3674]:0)
    at org.elasticsearch.action.admin.cluster.state.TransportClusterStateAction.masterOperation(TransportClusterStateAction.java:98)
    at org.elasticsearch.action.admin.cluster.state.TransportClusterStateAction.masterOperation(TransportClusterStateAction.java:41)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction.executeMasterOperation(TransportMasterNodeAction.java:124)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:235)
    at org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:72)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:958)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by albertzaharovits** [comment]
Another one today: https://gradle-enterprise.elastic.co/s/tytmyb5adkqry

**Comment by tlrx** [comment]
Relabeling and removing stale assignment.

**Comment by ywangd** [comment]
I am pretty sure this is already fixed by https://github.com/elastic/elasticsearch/pull/96869. Closing.
