### ISSUE TITLE
[CI] SetSingleNodeAllocateStepTests testPerformActionAttrsAllNodesValid failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#94323]
**Build scan:**
https://gradle-enterprise.elastic.co/s/qktjykqqetinc/tests/:x-pack:plugin:core:test/org.elasticsearch.xpack.core.ilm.SetSingleNodeAllocateStepTests/testPerformActionAttrsAllNodesValid

**Reproduction line:**
```
./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.ilm.SetSingleNodeAllocateStepTests.testPerformActionAttrsAllNodesValid" -Dtests.seed=B4288E6E95515294 -Dtests.locale=en-GB -Dtests.timezone=Australia/South -Druntime.java=19
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.core.ilm.SetSingleNodeAllocateStepTests&tests.test=testPerformActionAttrsAllNodesValid

**Failure excerpt:**
```
org.elasticsearch.client.internal.transport.NoNodeAvailableException: could not find any nodes to allocate index [CmuIqeFXMG] onto prior to shrink

  at __randomizedtesting.SeedInfo.seed([B4288E6E95515294:DC0F9922B5CCBE87]:0)
  at org.elasticsearch.xpack.core.ilm.SetSingleNodeAllocateStep.performAction(SetSingleNodeAllocateStep.java:120)
  at org.elasticsearch.xpack.core.ilm.SetSingleNodeAllocateStepTests.lambda$assertNodeSelected$11(SetSingleNodeAllocateStepTests.java:629)
  at org.elasticsearch.action.support.PlainActionFuture.get(PlainActionFuture.java:396)
  at org.elasticsearch.xpack.core.ilm.SetSingleNodeAllocateStepTests.assertNodeSelected(SetSingleNodeAllocateStepTests.java:629)
  at org.elasticsearch.xpack.core.ilm.SetSingleNodeAllocateStepTests.assertNodeSelected(SetSingleNodeAllocateStepTests.java:595)
  at org.elasticsearch.xpack.core.ilm.SetSingleNodeAllocateStepTests.testPerformActionAttrsAllNodesValid(SetSingleNodeAllocateStepTests.java:143)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by idegtiarenko** [comment]
This is a funny one. This seems to generate a single node and set of attributes with duplicated key `Q` that happens to be used for the only node:
![image](https://user-images.githubusercontent.com/1331856/223112356-5e70ec76-a01f-47f5-a049-c2ed389f98fa.png)

I will update the test to generate unique attribute names shortly.
I suspect testPerformActionAttrsAllNodesValid, testPerformActionAttrsRequestFails, testPerformActionAttrsNoShard are affected.
