### ISSUE TITLE
[CI] PackageUpgradeTests test12SetupBwcVersion failing

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#94370]
**Build scan:**
https://gradle-enterprise.elastic.co/s/2oknszicnrzei/tests/:qa:os:destructiveDistroUpgradeTest.v6.8.0.default-deb/org.elasticsearch.packaging.test.PackageUpgradeTests/test12SetupBwcVersion

**Reproduction line:**
```
null
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.PackageUpgradeTests&tests.test=test12SetupBwcVersion

**Failure excerpt:**
```
java.lang.RuntimeException: Elasticsearch did not start

  at __randomizedtesting.SeedInfo.seed([29E23992C167A4F0:1873DD844E3085E0]:0)
  at org.elasticsearch.packaging.util.ServerUtils.waitForElasticsearch(ServerUtils.java:213)
  at org.elasticsearch.packaging.util.ServerUtils.waitForElasticsearch(ServerUtils.java:85)
  at org.elasticsearch.packaging.util.Packages.assertElasticsearchStarted(Packages.java:273)
  at org.elasticsearch.packaging.test.PackagingTestCase.awaitElasticsearchStartup(PackagingTestCase.java:347)
  at org.elasticsearch.packaging.test.PackagingTestCase.startElasticsearch(PackagingTestCase.java:365)
  at org.elasticsearch.packaging.test.PackageUpgradeTests.test12SetupBwcVersion(PackageUpgradeTests.java:53)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

  Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:9200 [localhost/127.0.0.1] failed: Connection refused

    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
    at org.apache.http.client.fluent.Request.internalExecute(Request.java:173)
    at org.apache.http.client.fluent.Executor.execute(Executor.java:262)
    at org.elasticsearch.packaging.util.ServerUtils.execute(ServerUtils.java:133)
    at org.elasticsearch.packaging.util.ServerUtils.waitForElasticsearch(ServerUtils.java:177)
    at org.elasticsearch.packaging.util.ServerUtils.waitForElasticsearch(ServerUtils.java:85)
    at org.elasticsearch.packaging.util.Packages.assertElasticsearchStarted(Packages.java:273)
    at org.elasticsearch.packaging.test.PackagingTestCase.awaitElasticsearchStartup(PackagingTestCase.java:347)
    at org.elasticsearch.packaging.test.PackagingTestCase.startElasticsearch(PackagingTestCase.java:365)
    at org.elasticsearch.packaging.test.PackageUpgradeTests.test12SetupBwcVersion(PackageUpgradeTests.java:53)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1589)

    Caused by: java.net.ConnectException: Connection refused

      at sun.nio.ch.Net.pollConnect(Net.java:-2)
      at sun.nio.ch.Net.pollConnectNow(Net.java:672)
      at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:535)
      at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585)
      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
      at java.net.Socket.connect(Socket.java:666)
      at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
      at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
      at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
      at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
      at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
      at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
      at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
      at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
      at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
      at org.apache.http.client.fluent.Request.internalExecute(Request.java:173)
      at org.apache.http.client.fluent.Executor.execute(Executor.java:262)
      at org.elasticsearch.packaging.util.ServerUtils.execute(ServerUtils.java:133)
      at org.elasticsearch.packaging.util.ServerUtils.waitForElasticsearch(ServerUtils.java:177)
      at org.elasticsearch.packaging.util.ServerUtils.waitForElasticsearch(ServerUtils.java:85)
      at org.elasticsearch.packaging.util.Packages.assertElasticsearchStarted(Packages.java:273)
      at org.elasticsearch.packaging.test.PackagingTestCase.awaitElasticsearchStartup(PackagingTestCase.java:347)
      at org.elasticsearch.packaging.test.PackagingTestCase.startElasticsearch(PackagingTestCase.java:365)
      at org.elasticsearch.packaging.test.PackageUpgradeTests.test12SetupBwcVersion(PackageUpgradeTests.java:53)
      at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
      at java.lang.reflect.Method.invoke(Method.java:578)
      at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
      at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
      at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
      at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
      at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
      at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
      at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
      at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
      at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
      at java.lang.Thread.run(Thread.java:1589)

```

**Comment by mark-vieira** [comment]
Addressed by 494669196f25738bf2adde684220b904ca59b770
