### ISSUE TITLE
[CI] BulkProcessor2RetryIT testBulkRejectionLoadWithBackoff failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#94452]
**Build scan:**
https://gradle-enterprise.elastic.co/s/ynnt3hzgvl37o/tests/:server:internalClusterTest/org.elasticsearch.action.bulk.BulkProcessor2RetryIT/testBulkRejectionLoadWithBackoff

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.bulk.BulkProcessor2RetryIT.testBulkRejectionLoadWithBackoff" -Dtests.seed=7979906EFF34169B -Dtests.locale=sq -Dtests.timezone=America/Eirunepe -Druntime.java=19
```

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.bulk.BulkProcessor2RetryIT&tests.test=testBulkRejectionLoadWithBackoff

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <650>
     but: was <569>

  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.action.bulk.BulkProcessor2RetryIT.executeBulkRejectionLoad(BulkProcessor2RetryIT.java:97)
  at org.elasticsearch.action.bulk.BulkProcessor2RetryIT.testBulkRejectionLoadWithBackoff(BulkProcessor2RetryIT.java:63)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by cbuescher** [comment]
And another one also on 7.17 https://gradle-enterprise.elastic.co/s/fbkcotkghv7ba

**Comment by masseyke** [comment]
I think that this one is caused by an unrelated assertion error:
```
        Caused by:
        java.lang.AssertionError: Expected current thread [Thread[elasticsearch[node_s2][transport_worker][T#1],5,TGRP-BulkProcessor2RetryIT]] to not be a transport thread. Reason: [Blocking operation]
            at __randomizedtesting.SeedInfo.seed([7979906EFF34169B]:0)
            at org.elasticsearch.transport.Transports.assertNotTransportThread(Transports.java:56)
            at org.elasticsearch.common.util.concurrent.BaseFuture.blockingAllowed(BaseFuture.java:80)
            at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:74)
            at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:45)
            at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:26)
            at org.elasticsearch.action.support.PlainActionFuture.get(PlainActionFuture.java:24)
            at org.elasticsearch.transport.TransportService.openConnection(TransportService.java:483)
            at org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler.doSample(TransportClientNodesService.java:413)
            at org.elasticsearch.client.transport.TransportClientNodesService$NodeSampler.sample(TransportClientNodesService.java:364)
            at org.elasticsearch.client.transport.TransportClientNodesService.addTransportAddresses(TransportClientNodesService.java:200)
            at org.elasticsearch.client.transport.TransportClient.addTransportAddress(TransportClient.java:416)
            at org.elasticsearch.test.InternalTestCluster$TransportClientFactory.client(InternalTestCluster.java:1224)
            at org.elasticsearch.test.InternalTestCluster$NodeAndClient.getOrBuildTransportClient(InternalTestCluster.java:1040)
            at org.elasticsearch.test.InternalTestCluster$NodeAndClient.client(InternalTestCluster.java:994)
            at org.elasticsearch.test.InternalTestCluster.client(InternalTestCluster.java:849)
            at org.elasticsearch.test.ESIntegTestCase.client(ESIntegTestCase.java:677)
            at org.elasticsearch.test.ESIntegTestCase.client(ESIntegTestCase.java:670)
            at org.elasticsearch.action.bulk.BulkProcessor2RetryIT.countAndBulk(BulkProcessor2RetryIT.java:167)
```
When I comment that out locally the test passes fine.
