### ISSUE TITLE
[CI] MultiVersionRepositoryAccessIT testCreateAndRestoreSnapshot failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#94459]
**Build scan:**
https://gradle-enterprise.elastic.co/s/il7hbc4bhjukq/tests/:qa:repository-multi-version:v7.2.0%23Step1OldClusterTest/org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT/testCreateAndRestoreSnapshot

**Reproduction line:**
```
./gradlew ':qa:repository-multi-version:v7.2.0#Step1OldClusterTest' -Dtests.class="org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT" -Dtests.method="testCreateAndRestoreSnapshot" -Dtests.seed=9AC3C89F13A6872E -Dtests.bwc=true -Dtests.locale=es-UY -Dtests.timezone=Etc/UTC -Druntime.java=19
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT&tests.test=testCreateAndRestoreSnapshot

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:44759], URI [/_features/_reset], status line [HTTP/1.1 400 Bad Request]
Warnings: [[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).]
{"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}

  at __randomizedtesting.SeedInfo.seed([9AC3C89F13A6872E:1C7BEAC18EA7E693]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:689)
  at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:401)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by cbuescher** [comment]
All three tests (testUpgradeMovesRepoToNewMetaVersion, testCreateAndRestoreSnapshot, testReadOnlyRepo) are failing for almost all bwc versions before 7.13 (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+periodic+bwc)
This

**Comment by cbuescher** [comment]
Looks like some time on March 7th this job has been failing for a bunch of 7.x bwc cases:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+periodic+bwc/1073/

**Comment by hendrikmuhs** [comment]
tons of failures today. E.g. https://gradle-enterprise.elastic.co/s/3gxfimbnmry4u

**Comment by slobodanadamovic** [comment]
I've raised a [test mute PR](https://github.com/elastic/elasticsearch/pull/94580) since tests are failing quite often.

**Comment by arteam** [comment]
It looks like the API was for resetting feature states was added in 7.13 in https://github.com/elastic/elasticsearch/pull/69469, but the recent change for cleaning up the cluster https://github.com/elastic/elasticsearch/pull/94191 didn't check the version of the node.
```
 if (resetFeatureStates()) {
            final Request postRequest = new Request("POST", "/_features/_reset");
            adminClient().performRequest(postRequest);
        }
```

I believe doing a version check like this should work?

``` 
if (nodeVersions.first().onOrAfter(Version.V_7_13_0)) {
      final Request postRequest = new Request("POST", "/_features/_reset");
      adminClient().performRequest(postRequest);
 }
```

**Comment by ldematte** [comment]
Hi! I have started investigating this and the issue is exactly what @arteam pointed out: there should have been a check that version is onOrAfter 7.13, because 7.12 does not have the `reset` API (https://www.elastic.co/guide/en/elasticsearch/reference/7.12/features-apis.html).

However this problem is no longer observed now since at this time the oldest version on which bwc tests are run is 7.16; after a brief sync we decided to not fix the test case code to include exceptions for versions < 7.13 since these are not tested anymore.

**Comment by ldematte** [comment]
Removing AwaitFix and un-muting the tests exposed a new and different issue.
I have opened a new issue to track this new bug (https://github.com/elastic/elasticsearch/issues/98454) and submitted a PR (https://github.com/elastic/elasticsearch/pull/98440) to update test muting with the new bug URL to help keep tracking the correct issues.

**Comment by DaveCTurner** [comment]
> we decided to not fix the test case code to include exceptions for versions < 7.13 since these are not tested anymore.

I believe we do still test these versions, at least they are covered by the `test-full-bwc` suite. I opened https://github.com/elastic/elasticsearch/pull/100423 to fix this.
