### ISSUE TITLE
[CI Failure] SimpleChildQuerySearchTests.testParentFieldToNonExistingType

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#9461]
Reproduces with:

mvn clean test -Dtests.seed=CAB60064FD12D5A0 -Dtests.class=org.elasticsearch.search.child.SimpleChildQuerySearchTests -Dtests.method="testParentFieldToNonExistingType" -Des.logger.level=DEBUG -Des.node.mode=network -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=635m -Dtests.jvm.argline="-server -XX:+UseG1GC -XX:-UseCompressedOops" -Dtests.locale=de_CH -Dtests.timezone=Pacific/Samoa -Dtests.processors=8

**Comment by cbuescher** [comment]
This looks similar and was reproducible on my machine: 
http://build-us-00.elasticsearch.org/job/es_core_master_debian/3737/
Revision: 86e52c30a1528698d13048d04e8d3623675815c1 

mvn clean test -Dtests.seed=FB8C5EB86F124E9A -Dtests.class=org.elasticsearch.search.child.SimpleChildQuerySearchTests -Dtests.method="testParentFieldToNonExistingType" -Des.logger.level=DEBUG -Des.node.mode=network -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=685m -Dtests.jvm.argline="-server -XX:+UseParallelGC -XX:-UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=et -Dtests.timezone=Atlantic/Reykjavik -Dtests.processors=8

**Comment by cbuescher** [comment]
and this: http://build-us-00.elasticsearch.org/job/es_core_1x_metal/6743/

**Comment by martijnvg** [comment]
This looks like the cause:
```
org.elasticsearch.transport.RemoteTransportException: [node_s0][inet[/192.168.1.33:9400]][indices:data/read/search[phase/query+fetch]]
  1> Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: [test][0]: query[parent_filter[parent](filtered(ConstantScore(*:*))->cache(_type:parent))],from[0],size[10]: Query Failed [Failed to execute main query]
  1> 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:158)
  1> 	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:367)
  1> 	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:812)
  1> 	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:803)
  1> 	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:275)
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  1> 	at java.lang.Thread.run(Thread.java:745)
  1> Caused by: java.lang.RuntimeException: java.lang.NullPointerException
  1> 	at org.elasticsearch.search.internal.ContextIndexSearcher.createNormalizedWeight(ContextIndexSearcher.java:128)
  1> 	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:268)
  1> 	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:256)
  1> 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:152)
  1> 	... 8 more
  1> Caused by: java.lang.NullPointerException
  1> 	at org.elasticsearch.index.fielddata.plain.ParentChildIndexFieldData$GlobalAtomicFieldData.getOrdinalsValues(ParentChildIndexFieldData.java:378)
  1> 	at org.elasticsearch.index.search.child.ParentConstantScoreQuery.createWeight(ParentConstantScoreQuery.java:96)
  1> 	at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:655)
  1> 	at org.apache.lucene.search.AssertingIndexSearcher.createNormalizedWeight(AssertingIndexSearcher.java:59)
  1> 	at org.elasticsearch.search.internal.ContextIndexSearcher.createNormalizedWeight(ContextIndexSearcher.java:125)
  1> 	... 11 more
```
