### ISSUE TITLE
Exception in `_terms_enum` on docvalue-only keywords fields

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#94673]
### Elasticsearch Version

8.6.2

### Java Version

_bundled_

### OS Version

Mac OS X

### Problem Description

Running a "_terms_enum" request on a `keyword` field with `index: false` setting can very likely throws UnsupportedOperationException.

This happens under two conditions. The field queries by the "_terms_enum" has index disabled ("index" : false),
which means its docvalues only. This isn't the default but could happen.
The second condition is that a shard has more than one segment. The code path that is then executed throws the following exception
```
java.lang.UnsupportedOperationException
	at org.elasticsearch.server@8.6.2/org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType$SortedSetDocValuesTerms.hasFreqs(KeywordFieldMapper.java:664)
	at org.apache.lucene.core@9.4.2/org.apache.lucene.index.MultiTerms.<init>(MultiTerms.java:56)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType$SortedSetDocValuesTerms.getTerms(KeywordFieldMapper.java:618)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType.getTerms(KeywordFieldMapper.java:537)
	at org.elasticsearch.xcore@8.6.2/org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.dataNodeOperation(TransportTermsEnumAction.java:355)
	at org.elasticsearch.xcore@8.6.2/org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.lambda$asyncNodeOperation$1(TransportTermsEnumAction.java:733)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:50)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:47)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:72)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Steps to Reproduce

```
DELETE my-index

PUT /my-index
{
  "mappings": {
    "properties": {
      "foo": {
        "type": "keyword",
        "index" : "false"
      }
    }
  }
}


// run the following a couple of times to add a few documents, each with a bit of delay so we likely roll over into a new segment
// when the default refresh interval of 1s is used
POST my-index/_doc
{
  "foo": "hello"
}

POST /my-index/_terms_enum
{
  "field": "foo"
}
```

**Comment by cbuescher** [comment]
The problem is an unimplemented method in [SortedSetDocValuesTerms](https://github.com/elastic/elasticsearch/blob/242f4e3f84e85c436bb9cd19723c71d48c98f4b9/server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java#L664). This code path usually doesn't get triggered for keyword fields which are normally indexed. Even for doc-value only fields, we only hit this line if there is more than one segment, so in tests we don't usually see this. Has probably been like that for a long time already.
