### ISSUE TITLE
[CI] NodeShutdownShardsIT testNodeReplacementOnlyToTarget failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#94728]
Doesn't look related to the specific test so much as something fairly fundamental wrong with JDK stats collection:

```
Caused by: java.lang.InternalError: Memory Pool not found	
at __randomizedtesting.SeedInfo.seed([6ED1C68BAF8AACC1]:0)	
at sun.management.MemoryPoolImpl.getPeakUsage0(Native Method)	
at sun.management.MemoryPoolImpl.getPeakUsage(MemoryPoolImpl.java:98)	
at org.elasticsearch.monitor.jvm.JvmStats.jvmStats(JvmStats.java:63)	
at org.elasticsearch.monitor.jvm.JvmGcMonitorService$JvmMonitor.jvmStats(JvmGcMonitorService.java:522)
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/fimkttzyvl7no/tests/:x-pack:plugin:shutdown:internalClusterTest/org.elasticsearch.xpack.shutdown.NodeShutdownShardsIT/testNodeReplacementOnlyToTarget

**Reproduction line:**
```
./gradlew ':x-pack:plugin:shutdown:internalClusterTest' --tests "org.elasticsearch.xpack.shutdown.NodeShutdownShardsIT.testNodeReplacementOnlyToTarget" -Dtests.seed=6ED1C68BAF8AACC1 -Dtests.locale=sk -Dtests.timezone=Australia/Adelaide -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.shutdown.NodeShutdownShardsIT&tests.test=testNodeReplacementOnlyToTarget

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=409, name=test_TEST-TEST_WORKER_VM=[370]-CLUSTER_SEED=[3842257269405316757]-HASH=[B137CBE5C9]-cluster[T#1], state=RUNNABLE, group=TGRP-NodeShutdownShardsIT]

  at __randomizedtesting.SeedInfo.seed([6ED1C68BAF8AACC1:F3546514071033F8]:0)

  Caused by: java.lang.InternalError: Memory Pool not found

    at __randomizedtesting.SeedInfo.seed([6ED1C68BAF8AACC1]:0)
    at sun.management.MemoryPoolImpl.getPeakUsage0(MemoryPoolImpl.java:-2)
    at sun.management.MemoryPoolImpl.getPeakUsage(MemoryPoolImpl.java:98)
    at org.elasticsearch.monitor.jvm.JvmStats.jvmStats(JvmStats.java:63)
    at org.elasticsearch.monitor.jvm.JvmGcMonitorService$JvmMonitor.jvmStats(JvmGcMonitorService.java:522)
    at org.elasticsearch.monitor.jvm.JvmGcMonitorService$JvmMonitor.<init>(JvmGcMonitorService.java:413)
    at org.elasticsearch.monitor.jvm.JvmGcMonitorService$1.<init>(JvmGcMonitorService.java:212)
    at org.elasticsearch.monitor.jvm.JvmGcMonitorService.doStart(JvmGcMonitorService.java:212)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:43)
    at org.elasticsearch.monitor.MonitorService.doStart(MonitorService.java:57)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:43)
    at org.elasticsearch.node.Node.start(Node.java:1371)
    at org.elasticsearch.test.InternalTestCluster$NodeAndClient.startNode(InternalTestCluster.java:988)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
    at java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:891)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by dakrone** [comment]
This exception comes from the JVM itself, in a native function :(

Let's see if this occurs more times with JDK 20.0.0 (as this failure is), perhaps it's a regression in the JVM.

**Comment by DaveCTurner** [comment]
Same thing on a PR build: https://gradle-enterprise.elastic.co/s/33aqy3hf6ekgg

**Comment by masseyke** [comment]
This failure appears to be incredibly rare. I'm going to close this with the hope that the changes in #95710 have fixed it. If not, we can reopen this, and hopefully #95710 will have given us a little more information.
