### ISSUE TITLE
[CI] SearchableSnapshotActionIT testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped failing

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#94918]
Looks like a fluke on 7.17 but let's use this for tracking.

**Build scan:**
https://gradle-enterprise.elastic.co/s/utaybdheq5ykk/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT/testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped" -Dtests.seed=872DB50157E46291 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=th-TH -Dtests.timezone=Etc/GMT-10 -Druntime.java=20
```

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT&tests.test=testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is "cold"
     but: was "hot"

  at __randomizedtesting.SeedInfo.seed([872DB50157E46291:AE11761CF42910AF]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.lambda$testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped$11(SearchableSnapshotActionIT.java:357)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1141)
  at org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped(SearchableSnapshotActionIT.java:355)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by kingherc** [comment]
Another one at https://gradle-enterprise.elastic.co/s/wfnctmelueblw/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT/testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped?top-execution=1 :

```
org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:54833], URI [_snapshot/yGkdROmLAoKqlEHvcL], status line [HTTP/1.1 409 Conflict] |  
-- | --
  | {"error":{"root_cause":[{"type":"repository_conflict_exception","reason":"[yGkdROmLAoKqlEHvcL] trying to modify or unregister repository that is currently used (snapshot is in progress)"}],"type":"repository_conflict_exception","reason":"[yGkdROmLAoKqlEHvcL] trying to modify or unregister repository that is currently used (snapshot is in progress)"},"status":409} |  

...


REPRODUCE WITH: gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped" -Dtests.seed=EED8B05DE8BCEF7E -Dtests.locale=fi-FI -Dtests.timezone=America/El_Salvador -Druntime.java=20

```

**Comment by gmarouli** [comment]
One more failure like the one @kingherc mentioned on main: https://gradle-enterprise.elastic.co/s/naj2fzc3aermo/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT/testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped?top-execution=1

**Comment by alex-spies** [comment]
Another one just like the one mentioned by @kingherc : https://gradle-enterprise.elastic.co/s/l6aqhk354adco

**Comment by nielsbauman** [comment]
Tried looking into this but the cluster logs were missing in all these builds, unfortunately... Pinged the Delivery team about the missing logs (which seemed to be Windows-related), so hopefully we have some more info to work with next time this comes around.

**Comment by nielsbauman** [comment]
The last three reported failures in the comments here (https://github.com/elastic/elasticsearch/issues/94918#issuecomment-1549306619, https://github.com/elastic/elasticsearch/issues/94918#issuecomment-1574257027, https://github.com/elastic/elasticsearch/issues/94918#issuecomment-2020717428) are different from and unrelated to the original failure in this issue. See https://github.com/elastic/elasticsearch/issues/107818 for the failure that those comments were seeing.
