### ISSUE TITLE
[CI] RemoteClusterSecurityRestIT and RemoteClusterSecuritySpecialUserIT and RemoteClusterSecurityWithSameModelRemotesRestIT classMethods failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#94939]
**Build scan:**
https://gradle-enterprise.elastic.co/s/3wwnehg5i63ow/tests/:x-pack:plugin:security:qa:multi-cluster:javaRestTest/org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityRestIT

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityRestIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.RuntimeException: An error occurred orchestrating test cluster.

  at __randomizedtesting.SeedInfo.seed([8D2E6C76D2C38EC3]:0)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:236)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:241)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.start(LocalClusterHandle.java:68)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:38)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:39)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.util.concurrent.CancellationException: Request execution cancelled

    at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:114)
    at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
    at org.elasticsearch.xpack.remotecluster.AbstractRemoteClusterSecurityTestCase.performRequestAgainstFulfillingCluster(AbstractRemoteClusterSecurityTestCase.java:173)
    at org.elasticsearch.xpack.remotecluster.AbstractRemoteClusterSecurityTestCase.createCrossClusterAccessApiKey(AbstractRemoteClusterSecurityTestCase.java:127)
    at org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityRestIT.lambda$static$0(RemoteClusterSecurityRestIT.java:69)
    at org.elasticsearch.test.cluster.local.AbstractLocalSpecBuilder.lambda$keystore$12(AbstractLocalSpecBuilder.java:165)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.lambda$resolveKeystore$1(LocalClusterSpec.java:244)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.resolveKeystore(LocalClusterSpec.java:244)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.getSetting(LocalClusterSpec.java:208)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.isMasterEligible(LocalClusterSpec.java:194)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
    at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at org.elasticsearch.test.cluster.local.DefaultSettingsProvider.get(DefaultSettingsProvider.java:73)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.lambda$resolveSettings$0(LocalClusterSpec.java:226)
    at java.util.ArrayList.forEach(ArrayList.java:1511)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.resolveSettings(LocalClusterSpec.java:226)
    at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.writeConfiguration(LocalClusterFactory.java:331)
    at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.start(LocalClusterFactory.java:139)
    at org.elasticsearch.test.cluster.local.LocalClusterHandle.lambda$start$0(LocalClusterHandle.java:68)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667)
    at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
    at org.elasticsearch.test.cluster.local.LocalClusterHandle.lambda$start$1(LocalClusterHandle.java:68)
    at org.elasticsearch.test.cluster.local.LocalClusterHandle.lambda$execute$14(LocalClusterHandle.java:242)
    at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1456)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

```

**Comment by ywangd** [comment]
All failures are on Windows. So it is definitely platform specific. It failed during test setup phase, specifically when trying to create an API key against the fulfilling cluster
https://github.com/elastic/elasticsearch/blob/e735455431ebad86221c260fecad2870b919915b/x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecuritySpecialUserIT.java#L65

The [error](https://gradle-enterprise.elastic.co/s/kqri66y4vy5dq/tests/:x-pack:plugin:security:qa:multi-cluster:javaRestTest/org.elasticsearch.xpack.remotecluster.RemoteClusterSecuritySpecialUserIT?top-execution=1) is "Request execution cancelled" which means the client is either closed or never started. But I don't see where this could happen. It is also interesting to see that [some tests in the same test suite do not fail](https://gradle-enterprise.elastic.co/s/c7ca2uydlu4rg/tests/overview?task-path=:x-pack:plugin:security:qa:multi-cluster:javaRestTest) despite using the exact same API key setup. I am really puzzled.

It could take sometime to track it down. Also ping @mark-vieira to see whether there is any tricks involved in performing request against a cluster while bootstrapping the other cluster. The below logs suggest both clusters are terminated most likely due to HTTP request error.
```
[2023-03-29T20:41:07,465][INFO ][o.e.x.s.a.Realms         ] [fulfilling-cluster-0] license mode is [trial], currently licensed security realms are [reserved/reserved,file/default_file,native/default_native]	
[2023-03-30T07:41:07,520][INFO ][o.e.t.c.l.WaitForHttpResource] [suite] Got successful response [200] from URL [http://127.0.0.1:63802/_cluster/health?wait_for_nodes=>=1&wait_for_status=yellow]	
[2023-03-30T07:41:07,521][INFO ][o.e.t.c.l.LocalClusterHandle] [suite] Starting Elasticsearch test cluster 'query-cluster'	
[2023-03-30T07:41:07,521][INFO ][o.e.t.c.l.LocalClusterFactory] [[query-cluster-node-executor-0]] Starting Elasticsearch node 'query-cluster-0'	
[2023-03-30T07:41:07,522][INFO ][o.e.t.c.l.LocalClusterFactory] [[query-cluster-node-executor-0]] Creating installation for node 'query-cluster-0' in C:\Users\jenkins\workspace\platform-support\756\x-pack\plugin\security\qa\multi-cluster\build\testrun\javaRestTest\temp\query-cluster16383417108539276155\query-cluster-0	
[2023-03-30T07:41:07,522][INFO ][o.e.t.c.l.LocalClusterFactory] [[query-cluster-node-executor-0]] Distribution for node 'query-cluster-0': DefaultDistributionDescriptor{version=8.8.0, snapshot=true, distributionDir=C:\Users\jenkins\workspace\platform-support\756\distribution\archives\integ-test-zip\build\install, type=INTEG_TEST}	
[2023-03-30T07:41:07,657][INFO ][o.e.t.c.l.LocalClusterFactory] [[query-cluster-node-executor-0]] Installing modules [analysis-common] into node 'query-cluster-0	
[2023-03-30T07:41:07,680][INFO ][o.e.t.c.l.LocalClusterHandle] [suite] Stopping Elasticsearch test cluster 'query-cluster', forcibly: false	
[2023-03-30T07:41:07,681][INFO ][o.e.t.c.l.LocalClusterHandle] [suite] Stopping Elasticsearch test cluster 'fulfilling-cluster', forcibly: false
```

In the meantime, I raised https://github.com/elastic/elasticsearch/pull/94973 to skip the tests on Windows so that we don't lose coverage entirely.

**Comment by DaveCTurner** [comment]
Some similar non-Windows failures (mutes incoming):

- https://gradle-enterprise.elastic.co/s/ssvyx7xcnoa2k
- https://gradle-enterprise.elastic.co/s/oopv3w6pwdse4

I wonder if perhaps the clusters are just starting up too slowly leading to a timeout? They certainly do not look quick - this last one started the first node at `2023-04-03T00:39:02,531` and looks like it gave up at `2023-04-03T00:40:28,501` without even getting around to starting up the third node.

**Comment by ywangd** [comment]
OK the non-Windows failures are for the two new test classes that both spin up 3 clusters.
* RemoteClusterSecurityWithSameModelRemotesRestIT
* RemoteClusterSecurityWithMixedModelRemotesRestIT

The initially failed test classes only use 2 clusters and they only have ever failed on Windows (that's why I mis-interpreted it to be platform specific):
* RemoteClusterSecurityRestIT
* RemoteClusterSecuritySpecialUserIT

It is interesting that similar test classes such as `RemoteClusterSecurityApiKeyRestIT` have never failed so far. But it may just be luck. 

> I wonder if perhaps the clusters are just starting up too slowly leading to a timeout?

I am not sure but I suspect it is *not* due to timeout. The successful test class also takes about 1 min to complete (each cluster takes about 20-30 seconds to bootstrap). @mark-vieira Do you have suggestions on how we could get more logs around the failure point?

**Comment by n1v0lg** [comment]
This reproduces for me locally (occasionally), when I run the whole (`o.e.x.remotecluster.*`) test suite. I'm wondering if `RemoteClusterSecurityApiKeyRestIT` does not fail because it always runs first.

Still looking into this but a (not-so-well-founded) hypothesis I have is that the client is closed from a previous run and not re-built. Do we need to set `fulfillingClusterClient = null;` after closing maybe?

**Comment by ywangd** [comment]
@n1v0lg 
> Still looking into this but a (not-so-well-founded) hypothesis I have is that the client is closed from a previous run and not re-built. Do we need to set fulfillingClusterClient = null; after closing maybe?

By previous run, do you mean one test class running in parallel could affect another? I think this is a good theory. The test classes do seem to run in parallel. Since the client is in a static variable in the base class, it might be closed earlier by another tests. If so, this also means we cannot use mutate any static variables from the superclass, including `fullfillingCluster` and `queryCluster`. I'll confirm with Mark. Thanks for the tip!

**Comment by n1v0lg** [comment]
> By previous run, do you mean one test class running in parallel could affect another?

Yup, parallel run would explain this esp. since we have:

```java
@BeforeClass
public static void initFulfillingClusterClient() {
    if (fulfillingClusterClient != null) {
        return;
    }
    fulfillingClusterClient = buildRestClient(fulfillingCluster);
}

@AfterClass
public static void closeFulfillingClusterClient() throws IOException, InterruptedException {
    IOUtils.close(fulfillingClusterClient);
}
```

So test 1 could be closing the client, while test 2 sees it's not `null`, and does not re-init it.
