### ISSUE TITLE
[CI] MlMappingsUpgradeIT testMappingsUpgrade failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#95005]
Server-side log shows:

```
[2023-04-02T20:41:20,292][WARN ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [v8.8.0-2] [ml-mappings-upgrade-job] some results not processed due to the termination of autodetect
[2023-04-02T20:41:20,304][ERROR][o.e.x.m.p.l.CppLogMessageHandler] [v8.8.0-2] [controller/8335] [CDetachedProcessSpawner.cc@193] Child process with PID 24509 was terminated by signal 9
```

This suggests the process was killed by the OOM killer, i.e. the CI worker ran out of memory.

**Build scan:**
https://gradle-enterprise.elastic.co/s/tzqdjt6bv3hb6/tests/:x-pack:qa:rolling-upgrade:v8.8.0%23upgradedClusterTest/org.elasticsearch.upgrades.MlMappingsUpgradeIT/testMappingsUpgrade

**Reproduction line:**
```
./gradlew ':x-pack:qa:rolling-upgrade:v8.8.0#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.MlMappingsUpgradeIT" -Dtests.method="testMappingsUpgrade" -Dtests.seed=DEF8F0A60F580BEE -Dtests.bwc=true -Dtests.locale=is -Dtests.timezone=Japan -Druntime.java=19
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.MlMappingsUpgradeIT&tests.test=testMappingsUpgrade

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:38593], URI [_ml/anomaly_detectors/ml-mappings-upgrade-job/_close], status line [HTTP/1.1 409 Conflict]
{"error":{"root_cause":[{"type":"status_exception","reason":"cannot close job [ml-mappings-upgrade-job] because it failed, use force close"}],"type":"status_exception","reason":"cannot close job [ml-mappings-upgrade-job] because it failed, use force close"},"status":409}

  at __randomizedtesting.SeedInfo.seed([DEF8F0A60F580BEE:F38314F186C7708A]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.upgrades.MlMappingsUpgradeIT.closeAndReopenTestJob(MlMappingsUpgradeIT.java:102)
  at org.elasticsearch.upgrades.MlMappingsUpgradeIT.testMappingsUpgrade(MlMappingsUpgradeIT.java:63)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by mark-vieira** [comment]
Sure enough, memory usage is likely a big issue here:

![image](https://user-images.githubusercontent.com/4106672/229911711-44d9c062-4761-4184-bc2b-a318597ffe54.png)

One thing that doesn't help here is the fact that we run in a ramdisk. The issue with these heavy weight tests is that we don't want to be overly aggressive in making parallel execution mutually exclusive across specific tasks because that kills build times and what makes a test suite "heavier" is not easily inferable in an automated way so we risk having to "hand wire" these things together in a way.

I think perhaps we might just need beefier agents or less parallelism in general.

Is there any heuristic we could use here to limit paralleism on these test suite? For test clusters we give each node 512MB of heap by default, which isn't a lot. So even if we have 4, 3-node clusters going that's only 6GB of heap used by ES Java processes. Is there anyway to control the memory usage of the native ML jobs or cap parallelism on jobs within a test suite to keep memory usage more reasonable?

**Comment by droberts195** [comment]
> Is there anyway to control the memory usage of the native ML jobs or cap parallelism on jobs within a test suite

The jobs that are used for the rolling upgrade tests are pretty small. They'd take minutes to run and need substantial test data setup to do anything particularly memory-hungry.

This problem is happening again today. I searched for `agent.hostname` `elasticsearch-ci-immutable-ubuntu-1804-1683613821542693245` in the `metricbeat-*` indices in the CI stats. That's the machine where https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.8+periodic+java-matrix/ES_RUNTIME_JAVA=openjdk18,GRADLE_TASK=bwcTestSnapshots,nodes=general-purpose/25/ ran, which is one of the builds that failed today. (Corresponding build scan for that is https://gradle-enterprise.elastic.co/s/qoilclajycfxy.)

Based on what I can see I think the most likely culprit for using up more memory than expected is the Gradle daemon. I can see two really big Gradle daemons running around the time of the failures, one using around 11GB and the other around 15GB. Search for `system.process.memory.rss.bytes` in [this text file](https://github.com/elastic/elasticsearch/files/11430376/hungry_gradle_daemons.txt) to see those two records. The PIDs are different so it's not the same process being monitored twice. There's also another Gradle daemon with a different PID using 6.4GB.

**Comment by mark-vieira** [comment]
Interesting, these extra daemons should get shut down when there is system memory pressure but clearly that's not happening. @breskeby I'm wondering if we should pass explicit heap arguments to nested builds for BWC distributions. Otherwise by default they'll eat up a ton of heap using the default memory settings.

Alternatively we can also further chop up this job.

**Comment by droberts195** [comment]
This hasn't failed for 5 months. Presumably something was changed that reduces the amount of memory needed by Gradle daemons.
