### ISSUE TITLE
[CI] JdbcFrozenCsvSpecIT 'Unknown time-zone ID' failures

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#95044]
### CI Link

https://gradle-enterprise.elastic.co/s/bd62opsxghfsa/tests/:x-pack:plugin:sql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.sql.qa.single_node.JdbcFrozenCsvSpecIT/test%20%7Bfrozen.testSum%7D?top-execution=1

### Repro line

./gradlew ':x-pack:plugin:sql:qa:server:single-node:javaRestTest' --tests "org.elasticsearch.xpack.sql.qa.single_node.JdbcFrozenCsvSpecIT" -Dtests.method="test {frozen.testSum}" -Dtests.seed=D97DCCA7876C825E -Dtests.locale=fr-FR -Dtests.timezone=Antarctica/Davis -Druntime.java=20	

### Does it reproduce?

No

Looks like time zone issues, so could equally be core/infra

### Applicable branches

7.17, main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/London&tests.container=org.elasticsearch.xpack.sql.qa.single_node.JdbcFrozenCsvSpecIT&tests.test=test%20%7Bfrozen.testShowTables%7D

### Failure excerpt

	java.sql.SQLException: Server sent bad type [x_content_parse_exception]. Original type was [[-1:86] [sql/query] failed to parse field [time_zone]]. [org.elasticsearch.xcontent.XContentParseException: [-1:86] [sql/query] failed to parse field [time_zone]	
		at org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:609)	
		at org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:604)	
		at org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:652)	
		at org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:320)	
		at org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:260)	
		at org.elasticsearch.xcontent.ObjectParser.apply(ObjectParser.java:393)	
		at org.elasticsearch.xpack.sql.action.SqlQueryRequest.fromXContent(SqlQueryRequest.java:335)	
		at org.elasticsearch.xpack.sql.plugin.RestSqlQueryAction.prepareRequest(RestSqlQueryAction.java:51)	
		at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:86)	
		at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:337)	
		at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:403)	
		at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:255)	
		at org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:382)	
		at org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:461)	
		at org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:357)	
		at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:35)	
		at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:19)	
		at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)	
		at org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:48)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)	
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)	
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)	
		at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)	
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)	
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)	
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)	
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)	
		at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)	
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)	
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)	
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)	
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)	
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)	
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620)	
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583)	
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)	
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)	
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)	
		at java.base/java.lang.Thread.run(Thread.java:833)	
	Caused by: java.time.zone.ZoneRulesException: Unknown time-zone ID: America/Ciudad_Juarez	
		at java.base/java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:280)	
		at java.base/java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:235)	
		at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:121)	
		at java.base/java.time.ZoneId.of(ZoneId.java:410)	
		at java.base/java.time.ZoneId.of(ZoneId.java:358)	
		at org.elasticsearch.xpack.sql.action.AbstractSqlQueryRequest.lambda$objectParser$1(AbstractSqlQueryRequest.java:125)	
		at org.elasticsearch.xcontent.ObjectParser.lambda$declareField$8(ObjectParser.java:424)	
		at org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:602)

**Comment by thecoop** [comment]
Also JdbcFetchSizeIT - https://gradle-enterprise.elastic.co/s/qzrtpzpsi6za2/tests/:x-pack:plugin:sql:qa:jdbc:single-node:v7.17.8%23bwcTest/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcFetchSizeIT/testScrollWithDatetimeAndTimezoneParam?top-execution=1

**Comment by davidkyle** [comment]
A bunch more failures today: https://gradle-enterprise.elastic.co/s/4nltfr3bvfdse

Looks like that pesky **America/Ciudad_Juarez** timezone again
```
Caused by: java.time.zone.ZoneRulesException: Unknown time-zone ID: America/Ciudad_Juarez
```

**Comment by davidkyle** [comment]
Several recent failures all with the same `Unknown time-zone ID` message but this time the error is for *Europe/Kyiv*.

https://gradle-enterprise.elastic.co/s/hw44qiq2mlrhq/tests/:x-pack:plugin:sql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.sql.qa.single_node.JdbcFrozenCsvSpecIT/test%20%7Bfrozen.testColumnFromFrozen%7D?top-execution=1
https://gradle-enterprise.elastic.co/s/hw44qiq2mlrhq/tests/:x-pack:plugin:sql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.sql.qa.single_node.JdbcFrozenCsvSpecIT/test%20%7Bfrozen.testPercentileFrozen%7D?top-execution=1

**Comment by thecoop** [comment]
Happened again on 7.17: https://gradle-enterprise.elastic.co/s/nm67xny3jwbd2/tests/:x-pack:plugin:sql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.sql.qa.single_node.JdbcFrozenCsvSpecIT/test%20%7Bfrozen.testSum%7D

**Comment by ldematte** [comment]
And again: 
- https://gradle-enterprise.elastic.co/s/ol5uv5trltksk
- https://gradle-enterprise.elastic.co/s/xw23f2zcvic4k
- https://gradle-enterprise.elastic.co/s/qchfrr4qfn4rs
