### ISSUE TITLE
[CI] MaxDocsLimitIT testMaxDocsLimitConcurrently failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#95217]
**Build scan:**
https://gradle-enterprise.elastic.co/s/ethrw3t2cprhe/tests/:server:internalClusterTest/org.elasticsearch.index.engine.MaxDocsLimitIT/testMaxDocsLimitConcurrently

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.index.engine.MaxDocsLimitIT.testMaxDocsLimitConcurrently" -Dtests.seed=11F223311CC63125 -Dtests.locale=sr-BA -Dtests.timezone=Pacific/Kanton -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.engine.MaxDocsLimitIT&tests.test=testMaxDocsLimitConcurrently

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=2897, name=Thread-12, state=RUNNABLE, group=TGRP-MaxDocsLimitIT]

  at __randomizedtesting.SeedInfo.seed([11F223311CC63125:44EB99060C594388]:0)

  Caused by: java.lang.AssertionError: 
  Expected: a string containing "Number of documents in the index can't exceed [16]"
       but: was "number of documents in the index cannot exceed 16"

    at __randomizedtesting.SeedInfo.seed([11F223311CC63125]:0)
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.junit.Assert.assertThat(Assert.java:923)
    at org.elasticsearch.index.engine.MaxDocsLimitIT.lambda$indexDocs$1(MaxDocsLimitIT.java:189)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by arteam** [comment]
The error doesn't reproduce locally (I've run the test 1000 times) and there have been no test failures on CI over the last month. Please free to reopen the issue if it shows up again.
