### ISSUE TITLE
[CI] TransformDestIndexIT testTransformDestIndexAliases failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#95327]
**Build scan:**
https://gradle-enterprise.elastic.co/s/xpuwud76tjcak/tests/:x-pack:plugin:transform:qa:single-node-tests:javaRestTest/org.elasticsearch.xpack.transform.integration.TransformDestIndexIT/testTransformDestIndexAliases

**Reproduction line:**
```
./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformDestIndexIT.testTransformDestIndexAliases" -Dtests.seed=F43C808C18408700 -Dtests.locale=uk -Dtests.timezone=Asia/Tbilisi -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.transform.integration.TransformDestIndexIT&tests.test=testTransformDestIndexAliases

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [DELETE], host [http://127.0.0.1:37421], URI [/_transform/test_aliases], status line [HTTP/1.1 409 Conflict]
{"error":{"root_cause":[{"type":"status_exception","reason":"Cannot delete transform [test_aliases] as the task is running. Stop the task first"}],"type":"status_exception","reason":"Cannot delete transform [test_aliases] as the task is running. Stop the task first"},"status":409}

  at __randomizedtesting.SeedInfo.seed([F43C808C18408700:2A8275CC14FE5B60]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.xpack.transform.integration.TransformRestTestCase.deleteTransform(TransformRestTestCase.java:616)
  at org.elasticsearch.xpack.transform.integration.TransformRestTestCase.deleteTransform(TransformRestTestCase.java:607)
  at org.elasticsearch.xpack.transform.integration.TransformDestIndexIT.testTransformDestIndexAliases(TransformDestIndexIT.java:96)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by droberts195** [comment]
Same thing in https://gradle-enterprise.elastic.co/s/gqpxejtmbxb24

@przemekwitek please can you investigate.

**Comment by przemekwitek** [comment]
> please can you investigate.

Sure, thanks for heads-up!

**Comment by przemekwitek** [comment]
So it seems that 1. listed above is the issue.

I'm using the following test to debug this:
```
    public void testCreateAndDeleteTransformInALoop() throws Exception {
        String transformId = "test_create_and_delete_in_a_loop";
        String destIndex = transformId + "-dest";
        for (int i = 0; i < 100; ++i) {
            try {
                // Create the batch transform
                createPivotReviewsTransform(transformId, destIndex, null);
                // Wait until the transform finishes
                startAndWaitForTransform(transformId, destIndex);
                // Delete the transform
                deleteTransform(transformId);
            } catch (Exception e) {
                fail("Failure at iteration " + i + ": " + e.getMessage());
            }
        }
    }
```

I already identified and fixed (locally) part of the problem (race condition between persisting "stopped" state and removing the pTask). 
The test above used to fail consistently on iteration no. 0. Now it sometimes passes, sometimes fails at random iteration.
Still digging into other parts that may cause the problem here...
