### ISSUE TITLE
[CI] AggregationsClientYamlTestSuiteIT test {yaml=aggregations/composite/Composite aggregation with lossy format} failing

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#95386]
**Build scan:**
https://gradle-enterprise.elastic.co/s/oiye2nezvkr5i/tests/:modules:aggregations:yamlRestTest/org.elasticsearch.aggregations.AggregationsClientYamlTestSuiteIT/test%20%7Byaml=aggregations%2Fcomposite%2FComposite%20aggregation%20with%20lossy%20format%7D

**Reproduction line:**
```
./gradlew ':modules:aggregations:yamlRestTest' --tests "org.elasticsearch.aggregations.AggregationsClientYamlTestSuiteIT.test {yaml=aggregations/composite/Composite aggregation with lossy format}" -Dtests.seed=5529ADD5DF0835D6 -Dtests.locale=ja-JP -Dtests.timezone=US/Aleutian -Druntime.java=20
```

There's a second, related test failing with this repro line:
```
./gradlew ':modules:aggregations:yamlRestTest' --tests "org.elasticsearch.aggregations.AggregationsClientYamlTestSuiteIT.test {yaml=aggregations/composite/Composite aggregation with invalid format}" -Dtests.seed=5529ADD5DF0835D6 -Dtests.locale=ja-JP -Dtests.timezone=US/Aleutian -Druntime.java=20
```
**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.aggregations.AggregationsClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Daggregations/composite/Composite%20aggregation%20with%20lossy%20format%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [aggregations/composite:498]: expected [4xx|5xx] status code but api [search] returned [200 OK] [{"took":7,"timed_out":false,"_shards":{"total":2,"successful":1,"skipped":0,"failed":1,"failures":[{"shard":0,"index":"test","node":"o9Blnz4aQdSEZes0jJcuOg","reason":{"type":"illegal_argument_exception","reason":"Format [DocValueFormat.DateTime(format[yyyy-MM] locale[], Z, MILLISECONDS)] created output it couldn't parse for value [1508544000000] of type [class java.lang.Long]. parsed value: [1506816000000(class java.lang.Long)]"}}]},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"test","_id":"4","_score":1.0,"_source":{"keyword":"bar","long":[1000,0],"geo_point":"41.12,-71.34"}}]},"aggregations":{"test":{"buckets":[]}}}]

  at __randomizedtesting.SeedInfo.seed([5529ADD5DF0835D6:DD7D920F71F4582E]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:572)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:39)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.lang.AssertionError: expected [4xx|5xx] status code but api [search] returned [200 OK] [{"took":7,"timed_out":false,"_shards":{"total":2,"successful":1,"skipped":0,"failed":1,"failures":[{"shard":0,"index":"test","node":"o9Blnz4aQdSEZes0jJcuOg","reason":{"type":"illegal_argument_exception","reason":"Format [DocValueFormat.DateTime(format[yyyy-MM] locale[], Z, MILLISECONDS)] created output it couldn't parse for value [1508544000000] of type [class java.lang.Long]. parsed value: [1506816000000(class java.lang.Long)]"}}]},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"test","_id":"4","_score":1.0,"_source":{"keyword":"bar","long":[1000,0],"geo_point":"41.12,-71.34"}}]},"aggregations":{"test":{"buckets":[]}}}]

    at org.junit.Assert.fail(Assert.java:88)
    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:360)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:552)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:39)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by not-napoleon** [comment]
@romseygeek I know you touched some stuff around this code recently, but this might also predate your change?  I'll dig into it when I can, but I figured you should also be aware.

**Comment by romseygeek** [comment]
Yes, pretty sure this is due to my changes.  I will try and take a look at it today.

**Comment by romseygeek** [comment]
```
"stash" : {
  1>     "body" : {
  1>       "took" : 86,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 2,
  1>         "successful" : 1,
  1>         "skipped" : 0,
  1>         "failed" : 1,
  1>         "failures" : [
  1>           {
  1>             "shard" : 0,
  1>             "index" : "test",
  1>             "node" : "0zD_8IuQSmm7r9eIYiAgwg",
  1>             "reason" : {
  1>               "type" : "illegal_argument_exception",
  1>               "reason" : "Format [DocValueFormat.DateTime(format[YYYY-MM-dd] locale[], Z, MILLISECONDS)] created output it couldn't parse for value [1508544000000] of type [class java.lang.Long]. parsed value: [1483315200000(class java.lang.Long)]"
  1>             }
  1>           }
  1>         ]
  1>       },
  1>       "hits" : {
  1>         "total" : 1,
  1>         "max_score" : 1.0,
  1>         "hits" : [
  1>           {
  1>             "_index" : "test",
  1>             "_id" : "4",
  1>             "_score" : 1.0,
  1>             "_source" : {
  1>               "keyword" : "bar",
  1>               "long" : [
  1>                 1000,
  1>                 0
  1>               ],
  1>               "geo_point" : "41.12,-71.34"
  1>             }
  1>           }
  1>         ]
  1>       },
  1>       "aggregations" : {
  1>         "test" : {
  1>           "buckets" : [ ]
  1>         }
  1>       }
  1>     }
  1>   }
  1> }]
```

**Comment by romseygeek** [comment]
We only get the failure on one shard, so overall the response is a 200 rather than the expected 400.  I suspect that this doesn't fail all the time because in most cases the test targets a single shard, in which case the whole response is failed.  I'm not sure if this is caused by my changes in #95037 or if there have been other changes that mean we don't fail the whole response though?

**Comment by not-napoleon** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/95460
