### ISSUE TITLE
[CI] TransformSchedulerTests testScheduleNowWithSystemClock failing

### ISSUE THREAD

**Issue by HiDAl** [elastic/elasticsearch#95445]
This test has been failing consistently twice per month almost the same days. Probably something related to the date 
<img width="555" alt="Screenshot 2023-04-21 at 12 22 41" src="https://user-images.githubusercontent.com/284537/233612871-aa59d137-dcd1-4333-adf4-800b049691b8.png">

**Build scan:**
https://gradle-enterprise.elastic.co/s/m44bu6kvdglmg/tests/:x-pack:plugin:transform:test/org.elasticsearch.xpack.transform.transforms.scheduling.TransformSchedulerTests/testScheduleNowWithSystemClock

**Reproduction line:**
```
./gradlew ':x-pack:plugin:transform:test' --tests "org.elasticsearch.xpack.transform.transforms.scheduling.TransformSchedulerTests.testScheduleNowWithSystemClock" -Dtests.seed=51789FCA46998A02 -Dtests.locale=uk-UA -Dtests.timezone=Etc/GMT+6 -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.transform.transforms.scheduling.TransformSchedulerTests&tests.test=testScheduleNowWithSystemClock

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a collection with size <2>
     but: 

  at __randomizedtesting.SeedInfo.seed([51789FCA46998A02:4BE1BDC054FCCE5]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.transform.transforms.scheduling.TransformSchedulerTests.testScheduleNowWithSystemClock(TransformSchedulerTests.java:347)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by przemekwitek** [comment]
I identified this bug as a non-monotonicity in the system clock.
Fix is already in review.

**Comment by danielmitterdorfer** [comment]
@przemekwitek this happened again on a PR of mine (https://github.com/elastic/elasticsearch/pull/96499, which changed something completely unrelated):

```

17:05:28 org.elasticsearch.xpack.transform.transforms.scheduling.TransformSchedulerTests > testScheduleNowWithSystemClock FAILED
17:05:28     java.lang.AssertionError: 
17:05:28     Expected: a collection with size <2>
17:05:28          but: 
17:05:28         at __randomizedtesting.SeedInfo.seed([395D394976AF3495:6C9BBD5F35797272]:0)
17:05:28         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
17:05:28         at org.junit.Assert.assertThat(Assert.java:956)
17:05:28         at org.junit.Assert.assertThat(Assert.java:923)
17:05:28         at org.elasticsearch.xpack.transform.transforms.scheduling.TransformSchedulerTests.testScheduleNowWithSystemClock(TransformSchedulerTests.java:345)
```

Reproduction line:

```
./gradlew ':x-pack:plugin:transform:test' --tests "org.elasticsearch.xpack.transform.transforms.scheduling.TransformSchedulerTests.testScheduleNowWithSystemClock" -Dtests.seed=395D394976AF3495 -Dtests.locale=ar-DZ -Dtests.timezone=GB-Eire -Druntime.java=20
```

Did not reproduce locally (I've tried 100 iterations).

Build scan: https://gradle-enterprise.elastic.co/s/hoyxmrw6dozbc

**Comment by przemekwitek** [comment]
Thanks for reporting.

**Comment by albertzaharovits** [comment]
New failure today on main: https://gradle-enterprise.elastic.co/s/qggytn4zkqykg .

**Comment by albertzaharovits** [comment]
It failed 4 times in the past week: https://gradle-enterprise.elastic.co/scans/tests?search.startTimeMax=1689086022958&search.startTimeMin=1688418000000&search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.xpack.transform.transforms.scheduling.TransformSchedulerTests&tests.test=testScheduleNowWithSystemClock

**Comment by kingherc** [comment]
New failure on main https://gradle-enterprise.elastic.co/s/xdxhgg64vz674

**Comment by kingherc** [comment]
Seems to fail multiple times on 8.8, 8.9, main. Will mute.

**Comment by droberts195** [comment]
Assigning `medium-risk` due to loss of test coverage from muting.
