### ISSUE TITLE
[CI] MachineLearningPackageLoaderTests testValidateModelRepository failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#95487]
Always fails on Windows - presumably a Windows-specific problem.

**Build scan:**
https://gradle-enterprise.elastic.co/s/foreblfh6omxq/tests/:x-pack:plugin:ml-package-loader:test/org.elasticsearch.xpack.ml.packageloader.MachineLearningPackageLoaderTests/testValidateModelRepository

**Reproduction line:**
```
gradlew ':x-pack:plugin:ml-package-loader:test' --tests "org.elasticsearch.xpack.ml.packageloader.MachineLearningPackageLoaderTests.testValidateModelRepository" -Dtests.seed=5E75D196AF6E8B5D -Dtests.locale=zh-Hant-TW -Dtests.timezone=SystemV/AST4 -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.packageloader.MachineLearningPackageLoaderTests&tests.test=testValidateModelRepository

**Failure excerpt:**
```
org.junit.ComparisonFailure: expected:<...figuration: file:///[]home/elk/elasticsear...> but was:<...figuration: file:///[C:/]home/elk/elasticsear...>

  at __randomizedtesting.SeedInfo.seed([5E75D196AF6E8B5D:816ADB1E1ECB96BA]:0)
  at org.junit.Assert.assertEquals(Assert.java:115)
  at org.junit.Assert.assertEquals(Assert.java:144)
  at org.elasticsearch.xpack.ml.packageloader.MachineLearningPackageLoaderTests.testValidateModelRepository(MachineLearningPackageLoaderTests.java:21)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by albertzaharovits** [comment]
https://gradle-enterprise.elastic.co/s/nghz4jbwy4xa2
https://gradle-enterprise.elastic.co/s/vxdo4w3is5ihy
https://gradle-enterprise.elastic.co/s/47kuz5zomjjd6
https://gradle-enterprise.elastic.co/s/bc2abah4jdsie

Couple more today, all on windows.

**Comment by hendrikmuhs** [comment]
I am working on a fix, should be ready EOB.

**Comment by valeriy42** [comment]
There are still failures:
- https://gradle-enterprise.elastic.co/s/gw7ef4txcohwu
- https://gradle-enterprise.elastic.co/s/gcnyjiedl6l2u
- https://gradle-enterprise.elastic.co/s/wyciolkccd5fq
- https://gradle-enterprise.elastic.co/s/ef7irhta3kmjg

Ping @hendrikmuhs

**Comment by droberts195** [comment]
> There are still failures

The Windows builds are running off of old commits from before the fix because all intake builds in elasticsearch-ci have failed since yesterday morning. (This is due to 8.9.0 Beats not existing yet.)
