### ISSUE TITLE
[CI] MultipleDeploymentsIT testGetStats failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#95486]
Failed in single processor tests, so probably means we're doing something that relies on more than 1 thread in a thread pool that only has one thread per processor. This can be a production problem on small Cloud nodes.

**Build scan:**
https://gradle-enterprise.elastic.co/s/rvqlsrhmzobmk/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.MultipleDeploymentsIT/testGetStats

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.MultipleDeploymentsIT.testGetStats" -Dtests.seed=328E0568EB78E7F5 -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=pl-PL -Dtests.timezone=Zulu -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.MultipleDeploymentsIT&tests.test=testGetStats

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:46460], URI [/_ml/trained_models/model-with-1-deployment/deployment/_start?timeout=40s&wait_for=started&threads_per_allocation=1&number_of_allocations=1&priority=normal], status line [HTTP/1.1 429 Too Many Requests]
{"error":{"root_cause":[{"type":"status_exception","reason":"Could not start deployment because no ML nodes with sufficient capacity were found"}],"type":"status_exception","reason":"Could not start deployment because no ML nodes with sufficient capacity were found","caused_by":{"type":"illegal_state_exception","reason":"Could not start deployment because no suitable nodes were found, allocation explanation [Could not assign (more) allocations on node [EhOXHr8uQVGeP5OOv_KZqg]. Reason: This node has insufficient allocated processors. Available processors [1], free processors [0], processors required for each allocation of this model [1]|Could not assign (more) allocations on node [__3j4m0CSGKz-hMvvKghGg]. Reason: This node has insufficient allocated processors. Available processors [1], free processors [0], processors required for each allocation of this model [1]]"}},"status":429}

  at __randomizedtesting.SeedInfo.seed([328E0568EB78E7F5:A5BFDB9EC48C1FA0]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.xpack.ml.integration.PyTorchModelRestTestCase.startDeployment(PyTorchModelRestTestCase.java:250)
  at org.elasticsearch.xpack.ml.integration.PyTorchModelRestTestCase.startDeployment(PyTorchModelRestTestCase.java:223)
  at org.elasticsearch.xpack.ml.integration.PyTorchModelRestTestCase.startDeployment(PyTorchModelRestTestCase.java:215)
  at org.elasticsearch.xpack.ml.integration.MultipleDeploymentsIT.testGetStats(MultipleDeploymentsIT.java:79)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by davidkyle** [comment]
This is the same problem as #95370. I'll open a PR to fix by using low priority deployments
