### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT test {yaml=reference/migration/apis/feature-migration/line_47} failing

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#95556]
**Build scan:**
https://gradle-enterprise.elastic.co/s/u4chus7dwhd2s/tests/:docs:yamlRestTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Fmigration%2Fapis%2Ffeature-migration%2Fline_47%7D

**Reproduction line:**
```
./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/migration/apis/feature-migration/line_47}" -Dtests.seed=D8813DC1CCFCEF26 -Dtests.locale=nn-NO -Dtests.timezone=America/Maceio -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dreference/migration/apis/feature-migration/line_47%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [reference/migration/apis/feature-migration:15]: Expected a map containing
         features: a list containing
                  0: a map containing
              indices: an empty list
         feature_name: "async_search"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                  1: a map containing
              indices: an empty list
         feature_name: "enrich"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                  2: a map containing
              indices: an empty list
         feature_name: "ent_search"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                  3: a map containing
              indices: an empty list
         feature_name: "fleet"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                  4: a map containing
              indices: an empty list
         feature_name: "geoip"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                  5: a map containing
              indices: an empty list
         feature_name: "kibana"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                  6: a map containing
              indices: an empty list
         feature_name: "logstash_management"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                  7: a map containing
              indices: an empty list
         feature_name: "machine_learning"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                  8: a map containing
              indices: an empty list
         feature_name: "searchable_snapshots"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                  9: a map containing
              indices: an empty list
         feature_name: "security"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                 10: a map containing
              indices: an empty list
         feature_name: expected "tasks" but was "synonyms"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                 11: a map containing
              indices: an empty list
         feature_name: expected "transform" but was "tasks"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                 12: a map containing
              indices: an empty list
         feature_name: expected "watcher" but was "transform"
     migration_status: "NO_MIGRATION_NEEDED"
minimum_index_version: "8.8.0"
                 13: <unexpected> but was <{feature_name=watcher, minimum_index_version=8.8.0, migration_status=NO_MIGRATION_NEEDED, indices=[]}>
 migration_status: "NO_MIGRATION_NEEDED"

  at __randomizedtesting.SeedInfo.seed([D8813DC1CCFCEF26:50D5021B620082DE]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:572)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.lang.AssertionError: Expected a map containing
           features: a list containing
                    0: a map containing
                indices: an empty list
           feature_name: "async_search"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                    1: a map containing
                indices: an empty list
           feature_name: "enrich"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                    2: a map containing
                indices: an empty list
           feature_name: "ent_search"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                    3: a map containing
                indices: an empty list
           feature_name: "fleet"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                    4: a map containing
                indices: an empty list
           feature_name: "geoip"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                    5: a map containing
                indices: an empty list
           feature_name: "kibana"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                    6: a map containing
                indices: an empty list
           feature_name: "logstash_management"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                    7: a map containing
                indices: an empty list
           feature_name: "machine_learning"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                    8: a map containing
                indices: an empty list
           feature_name: "searchable_snapshots"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                    9: a map containing
                indices: an empty list
           feature_name: "security"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                   10: a map containing
                indices: an empty list
           feature_name: expected "tasks" but was "synonyms"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                   11: a map containing
                indices: an empty list
           feature_name: expected "transform" but was "tasks"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                   12: a map containing
                indices: an empty list
           feature_name: expected "watcher" but was "transform"
       migration_status: "NO_MIGRATION_NEEDED"
  minimum_index_version: "8.8.0"
                   13: <unexpected> but was <{feature_name=watcher, minimum_index_version=8.8.0, migration_status=NO_MIGRATION_NEEDED, indices=[]}>
   migration_status: "NO_MIGRATION_NEEDED"

    at org.elasticsearch.test.MapMatcher.assertMap(MapMatcher.java:82)
    at org.elasticsearch.test.MapMatcher.assertMap(MapMatcher.java:65)
    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:94)
    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:552)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by mayya-sharipova** [comment]
Opened accidentally through Homer
