### ISSUE TITLE
[CI] CommonAnalysisPluginTests testSystemSynonymsIndexName failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#95840]
**Build scan:**
https://gradle-enterprise.elastic.co/s/m7cvk5icn35dm/tests/:modules:analysis-common:test/org.elasticsearch.analysis.common.CommonAnalysisPluginTests/testSystemSynonymsIndexName

**Reproduction line:**
```
./gradlew ':modules:analysis-common:test' --tests "org.elasticsearch.analysis.common.CommonAnalysisPluginTests.testSystemSynonymsIndexName" -Dtests.seed=2350B1BAFF48BDD6 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=ar-SA -Dtests.timezone=America/Hermosillo -Druntime.java=20
```

**Applicable branches:**
8.8

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.analysis.common.CommonAnalysisPluginTests&tests.test=testSystemSynonymsIndexName

**Failure excerpt:**
```
java.lang.AssertionError: expected:<[.synonyms]> but was:<[]>

  at __randomizedtesting.SeedInfo.seed([2350B1BAFF48BDD6:211D00FAD34788CC]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:118)
  at org.junit.Assert.assertEquals(Assert.java:144)
  at org.elasticsearch.analysis.common.CommonAnalysisPluginTests.testSystemSynonymsIndexName(CommonAnalysisPluginTests.java:228)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by cbuescher** [comment]
Tried reproduction but couldn't get it to fail yet. I'm surprised a bit because I'd think the index is either there or not after start, but maybe there is a race here somewhere.

**Comment by mark-vieira** [comment]
This is failing consistently in release builds. Are you including `-Dbuild.snapshot=false`?

**Comment by cbuescher** [comment]
Yes, sorry for the confusion. This seems to be an issue only when using the release flag. This call succeeds:
```
./gradlew --no-build-cache ':modules:analysis-common:test' --tests "org.elasticsearch.analysis.common.CommonAnalysisPluginTests.testSystemSynonymsIndexName" -Druntime.java=20
```

while adding `-Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false"` seems to reliably fail the test with the above exception. So this needs digging whats different in those two cases since in PR before merging we only checked the former case.

**Comment by kingherc** [comment]
Another one at https://gradle-enterprise.elastic.co/s/3wmn5y6uor6hk/tests/:modules:analysis-common:test/org.elasticsearch.analysis.common.CommonAnalysisPluginTests/testSystemSynonymsIndexName?top-execution=1 .
