### ISSUE TITLE
Failure in backwards.MixedClusterClientYamlTestSuiteIT test {p0=tsdb/30_snapshot/Create a snapshot and then restore it}

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#95889]
### CI Link

https://gradle-enterprise.elastic.co/s/sh335e3ibamyc

### Repro line

`gradlew ':qa:mixed-cluster:v8.7.0#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=tsdb/30_snapshot/Create a snapshot and then restore it}" -Dtests.seed=C454C443A8479A6D -Dtests.bwc=true -Dtests.locale=is -Dtests.timezone=Turkey -Druntime.java=20`

### Does it reproduce?

No

### Applicable branches

8.8

### Failure excerpt

```
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=tsdb/30_snapshot/Create a snapshot and then restore it} FAILED
    java.lang.AssertionError: Failure at [tsdb/30_snapshot:134]: 
    Expected: "SNAPSHOT"
         but: was "PEER"
        at __randomizedtesting.SeedInfo.seed([C454C443A8479A6D:4C00FB9906BBF795]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:572)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1623)

        Caused by:
        java.lang.AssertionError: 
        Expected: "SNAPSHOT"
             but: was "PEER"
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.junit.Assert.assertThat(Assert.java:956)
            at org.junit.Assert.assertThat(Assert.java:923)
            at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:99)
            at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:552)
```

```
1> [2023-05-05T16:24:56,058][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "test_index" : {
  1>         "shards" : [
  1>           {
  1>             "id" : 1,
  1>             "type" : "PEER",
  1>             "stage" : "TRANSLOG",
  1>             "primary" : true,
  1>             "start_time_in_millis" : 1683293096027,
  1>             "total_time_in_millis" : 22,
  1>             "source" : {
  1>               "id" : "4h99jLz3SpKRgmTl-ki-0w",
  1>               "host" : "127.0.0.1",
  1>               "transport_address" : "127.0.0.1:41361",
  1>               "ip" : "127.0.0.1",
  1>               "name" : "v8.7.0-2"
  1>             },
  1>             "target" : {
  1>               "id" : "d7RN2uowR0KDM2ootjpBrw",
  1>               "host" : "127.0.0.1",
  1>               "transport_address" : "127.0.0.1:39139",
  1>               "ip" : "127.0.0.1",
  1>               "name" : "v8.7.0-1"
  1>             },
  1>             "index" : {
  1>               "size" : {
  1>                 "total_in_bytes" : 10275,
  1>                 "reused_in_bytes" : 0,
  1>                 "recovered_in_bytes" : 10275,
  1>                 "recovered_from_snapshot_in_bytes" : 0,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "files" : {
  1>                 "total" : 4,
  1>                 "reused" : 0,
  1>                 "recovered" : 4,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "total_time_in_millis" : 13,
  1>               "source_throttle_time_in_millis" : 0,
  1>               "target_throttle_time_in_millis" : 0
  1>             },
  1>             "translog" : {
  1>               "recovered" : 0,
  1>               "total" : 0,
  1>               "percent" : "100.0%",
  1>               "total_on_start" : 0,
  1>               "total_time_in_millis" : 4
  1>             },
  1>             "verify_index" : {
  1>               "check_index_time_in_millis" : 0,
  1>               "total_time_in_millis" : 0
  1>             }
  1>           },
  1>           {
  1>             "id" : 1,
  1>             "type" : "SNAPSHOT",
  1>             "stage" : "DONE",
  1>             "primary" : true,
  1>             "start_time_in_millis" : 1683293095989,
  1>             "stop_time_in_millis" : 1683293096012,
  1>             "total_time_in_millis" : 23,
  1>             "source" : {
  1>               "repository" : "test_repo",
  1>               "snapshot" : "test_restore_tsdb",
  1>               "version" : "8.8.0",
  1>               "index" : "test_index",
  1>               "restoreUUID" : "LF4zIkCYSwuS9dRxmeov3Q"
  1>             },
  1>             "target" : {
  1>               "id" : "4h99jLz3SpKRgmTl-ki-0w",
  1>               "host" : "127.0.0.1",
  1>               "transport_address" : "127.0.0.1:41361",
  1>               "ip" : "127.0.0.1",
  1>               "name" : "v8.7.0-2"
  1>             },
  1>             "index" : {
  1>               "size" : {
  1>                 "total_in_bytes" : 10275,
  1>                 "reused_in_bytes" : 9945,
  1>                 "recovered_in_bytes" : 330,
  1>                 "recovered_from_snapshot_in_bytes" : 0,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "files" : {
  1>                 "total" : 4,
  1>                 "reused" : 3,
  1>                 "recovered" : 1,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "total_time_in_millis" : 13,
  1>               "source_throttle_time_in_millis" : 0,
  1>               "target_throttle_time_in_millis" : 0
  1>             },
  1>             "translog" : {
  1>               "recovered" : 0,
  1>               "total" : 0,
  1>               "percent" : "100.0%",
  1>               "total_on_start" : 0,
  1>               "total_time_in_millis" : 6
  1>             },
  1>             "verify_index" : {
  1>               "check_index_time_in_millis" : 0,
  1>               "total_time_in_millis" : 0
  1>             }
  1>           },
  1>           {
  1>             "id" : 0,
  1>             "type" : "SNAPSHOT",
  1>             "stage" : "DONE",
  1>             "primary" : true,
  1>             "start_time_in_millis" : 1683293095973,
  1>             "stop_time_in_millis" : 1683293095996,
  1>             "total_time_in_millis" : 22,
  1>             "source" : {
  1>               "repository" : "test_repo",
  1>               "snapshot" : "test_restore_tsdb",
  1>               "version" : "8.8.0",
  1>               "index" : "test_index",
  1>               "restoreUUID" : "LF4zIkCYSwuS9dRxmeov3Q"
  1>             },
  1>             "target" : {
  1>               "id" : "vP_y13UkTpWUXkNlDNFajg",
  1>               "host" : "127.0.0.1",
  1>               "transport_address" : "127.0.0.1:44139",
  1>               "ip" : "127.0.0.1",
  1>               "name" : "v8.7.0-0"
  1>             },
  1>             "index" : {
  1>               "size" : {
  1>                 "total_in_bytes" : 8938,
  1>                 "reused_in_bytes" : 8608,
  1>                 "recovered_in_bytes" : 330,
  1>                 "recovered_from_snapshot_in_bytes" : 0,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "files" : {
  1>                 "total" : 4,
  1>                 "reused" : 3,
  1>                 "recovered" : 1,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "total_time_in_millis" : 12,
  1>               "source_throttle_time_in_millis" : 0,
  1>               "target_throttle_time_in_millis" : 0
  1>             },
  1>             "translog" : {
  1>               "recovered" : 0,
  1>               "total" : 0,
  1>               "percent" : "100.0%",
  1>               "total_on_start" : 0,
  1>               "total_time_in_millis" : 7
  1>             },
  1>             "verify_index" : {
  1>               "check_index_time_in_millis" : 0,
  1>               "total_time_in_millis" : 0
  1>             }
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
```

**Comment by tmgordeeva** [comment]
I haven't been able to repro this, so I think we should close it and see if it comes back. This test or the equivalent in other test for non-tsdb indices does have a history of flaky failures in the past and possibly some of those fixes somehow don't fully apply to tsdb indices, but it wasn't apparent from going through the old failures.
