### ISSUE TITLE
`AtomicRegisterCoordinatorTests.testUnresponsiveFollowerDetectedEventually` fails in `8.8`

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#95915]
### CI Link

https://gradle-enterprise.elastic.co/s/aswq4zbjvfhtw

### Repro line

./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.AtomicRegisterCoordinatorTests.testUnresponsiveFollowerDetectedEventually" -Dtests.seed=4A6CCA4249F2C7FC -Dtests.locale=sr-Latn-ME -Dtests.timezone=America/Indiana/Tell_City -Druntime.java=20

### Does it reproduce?

Yes

### Applicable branches

8.8

### Failure excerpt

```
12:54:56 org.elasticsearch.cluster.coordination.AtomicRegisterCoordinatorTests > testUnresponsiveFollowerDetectedEventually FAILED
12:54:56     java.lang.AssertionError: node1 has no NO_MASTER_BLOCK
12:54:56     Expected: <false>
12:54:56          but: was <true>
12:54:56         at __randomizedtesting.SeedInfo.seed([4A6CCA4249F2C7FC:230317C8D23B5CE2]:0)
12:54:56         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
12:54:56         at org.junit.Assert.assertThat(Assert.java:956)
12:54:56         at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:583)
12:54:56         at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:553)
12:54:56         at org.elasticsearch.cluster.coordination.CoordinatorTests.testUnresponsiveFollowerDetectedEventually(CoordinatorTests.java:471)
12:54:56         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
12:54:56         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
12:54:56         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
12:54:56         at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
12:54:56         at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
12:54:56         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
12:54:56         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
12:54:56         at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
12:54:56         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
12:54:56         at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
12:54:56         at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
12:54:56         at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
12:54:56         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
12:54:56         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
12:54:56         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
12:54:56         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
12:54:56         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
12:54:56         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
12:54:56         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
12:54:56         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
12:54:56         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
12:54:56         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
12:54:56         at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
12:54:56         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
12:54:56         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
12:54:56         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
12:54:56         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
12:54:56         at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
12:54:56         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
12:54:56         at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
12:54:56         at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
12:54:56         at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
12:54:56         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
12:54:56         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
12:54:56         at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
12:54:56         at java.base/java.lang.Thread.run(Thread.java:1623)

```

**Comment by cbuescher** [comment]
This failure today on 8.8 looks similar: https://gradle-enterprise.elastic.co/s/br7emqz65ioku

**Comment by fcofdez** [comment]
This was fixed by https://github.com/elastic/elasticsearch/pull/96490. I could reproduce the issue in 8.8 and after applying the patch it didn't reproduce anymore.
