### ISSUE TITLE
"Too many open files" is not evidence of corruption

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#95930]
A user reported that one of their shards was marked as corrupted after hitting a `Too many open files` exception:

`"details": """failed shard on node [REDACTED]: shard failure, reason [corrupt file (source: [start])], failure java.nio.file.FileSystemException: /data/REDACTED/0/index/_abc.fdx: Too many open files`

While this exception is indeed fatal to the shard, it should be treated as a transient error and should not lead to the shard being marked as corrupt.

**Comment by tlrx** [comment]
I found an interesting stack trace in which a `FileSystemException` thrown because of `too many open files` can lead to a shard being marked as corrupted:

```java
[2023-04-15T00:02:15,587][WARN ][o.e.i.e.Engine           ] [node] [index][0] failed engine [corrupt file (source: [start])]
java.nio.file.FileSystemException: /data/indices/abcdefghijkl/0/index/_3gc.fdx: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:304) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:363) ~[?:?]
	at org.apache.lucene.store.NIOFSDirectory.openInput(NIOFSDirectory.java:78) ~[lucene-core-9.4.2.jar:?]
	at org.elasticsearch.index.store.FsDirectoryFactory$HybridDirectory.openInput(FsDirectoryFactory.java:124) ~[elasticsearch-8.6.1.jar:?]
	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:101) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:101) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.codecs.lucene90.compressing.FieldsIndexReader.<init>(FieldsIndexReader.java:68) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.codecs.lucene90.compressing.Lucene90CompressingStoredFieldsReader.<init>(Lucene90CompressingStoredFieldsReader.java:166) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.codecs.lucene90.compressing.Lucene90CompressingStoredFieldsFormat.fieldsReader(Lucene90CompressingStoredFieldsFormat.java:133) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.codecs.lucene90.Lucene90StoredFieldsFormat.fieldsReader(Lucene90StoredFieldsFormat.java:136) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:138) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:91) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:179) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:221) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.index.IndexWriter.lambda$getReader$0(IndexWriter.java:536) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:138) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:598) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:112) ~[lucene-core-9.4.2.jar:?]
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:91) ~[lucene-core-9.4.2.jar:?]
	at org.elasticsearch.index.engine.InternalEngine.createReaderManager(InternalEngine.java:624) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:249) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:194) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:14) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:1949) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.index.shard.IndexShard.openEngineAndSkipTranslogRecovery(IndexShard.java:1925) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoveryTarget.lambda$prepareForTranslogOperations$1(RecoveryTarget.java:356) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:444) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoveryTarget.prepareForTranslogOperations(RecoveryTarget.java:353) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$PrepareForTranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:377) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$PrepareForTranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:367) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:257) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:319) ~[?:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:309) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeSystemUser(AuthorizationService.java:604) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:259) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(ServerTransportFilter.java:113) ~[?:?]
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:162) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.action.ActionListener$MappedActionListener.onResponse(ActionListener.java:127) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticateAsync(AuthenticatorChain.java:93) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:199) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(ServerTransportFilter.java:104) ~[?:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:330) ~[?:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:71) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:291) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917) ~[elasticsearch-8.6.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.6.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (f4c97aae). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/data/indices/abcdefghijkl/0/index/_3gc.fdm")))
		at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:500) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.codecs.lucene90.compressing.Lucene90CompressingStoredFieldsReader.<init>(Lucene90CompressingStoredFieldsReader.java:208) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.codecs.lucene90.compressing.Lucene90CompressingStoredFieldsFormat.fieldsReader(Lucene90CompressingStoredFieldsFormat.java:133) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.codecs.lucene90.Lucene90StoredFieldsFormat.fieldsReader(Lucene90StoredFieldsFormat.java:136) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:138) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:91) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:179) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:221) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.index.IndexWriter.lambda$getReader$0(IndexWriter.java:536) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:138) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:598) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:112) ~[lucene-core-9.4.2.jar:?]
		at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:91) ~[lucene-core-9.4.2.jar:?]
		at org.elasticsearch.index.engine.InternalEngine.createReaderManager(InternalEngine.java:624) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:249) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:194) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:14) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:1949) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.index.shard.IndexShard.openEngineAndSkipTranslogRecovery(IndexShard.java:1925) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.indices.recovery.RecoveryTarget.lambda$prepareForTranslogOperations$1(RecoveryTarget.java:356) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:444) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.indices.recovery.RecoveryTarget.prepareForTranslogOperations(RecoveryTarget.java:353) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$PrepareForTranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:377) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$PrepareForTranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:367) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:257) ~[?:?]
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:319) ~[?:?]
		at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:309) ~[?:?]
		at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeSystemUser(AuthorizationService.java:604) ~[?:?]
		at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:259) ~[?:?]
		at org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(ServerTransportFilter.java:113) ~[?:?]
		at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:162) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.action.ActionListener$MappedActionListener.onResponse(ActionListener.java:127) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticateAsync(AuthenticatorChain.java:93) ~[?:?]
		at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:199) ~[?:?]
		at org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(ServerTransportFilter.java:104) ~[?:?]
		at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:330) ~[?:?]
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:71) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:291) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917) ~[elasticsearch-8.6.1.jar:?]
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.6.1.jar:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

When opening a Lucene file related to stored fields ([FieldsIndexReader.java:68](https://github.com/apache/lucene/blob/858d9b437047a577fa9457089afff43eefa461db/lucene/core/src/java/org/apache/lucene/codecs/lucene90/compressing/FieldsIndexReader.java#L68)) the too many open files `FileSystemException` is thrown and caught upstream in [Lucene90CompressingStoredFieldsReader.java:208](https://github.com/apache/lucene/blob/858d9b437047a577fa9457089afff43eefa461db/lucene/core/src/java/org/apache/lucene/codecs/lucene90/compressing/Lucene90CompressingStoredFieldsReader.java#L206-L208).

In this catch block Lucene executes a [CodecUtil.checkFooter()](https://github.com/apache/lucene/blob/858d9b437047a577fa9457089afff43eefa461db/lucene/core/src/java/org/apache/lucene/codecs/CodecUtil.java#L498) on the file which adds a new `CorruptIndexException` as a suppressed exception of the prior `FileSystemException`.

In Elasticsearch when failing the engine we unwrap all causes and suppressed exception to look for any instances of `CorruptIndexException`, `IndexFormatTooOldException` or  `IndexFormatTooNewException` and mark the shard as corrupted.

I also think that any IO exception in `IndexShard#checkIndex` can lead to the corruption marker to be written, which is also debatable
