### ISSUE TITLE
[CI] JdbcResultSetIT testGettingTimeWithoutCalendar failing

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#95950]
Seems like https://github.com/elastic/elasticsearch/pull/56493 needs porting to 7.17

**Build scan:**
https://gradle-enterprise.elastic.co/s/746r2w3gsa6fy/tests/:x-pack:plugin:sql:qa:jdbc:single-node:javaRestTest/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT/testGettingTimeWithoutCalendar

**Reproduction line:**
```
./gradlew ':x-pack:plugin:sql:qa:jdbc:single-node:javaRestTest' -Dtests.class="org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT" -Dtests.method="testGettingTimeWithoutCalendar" -Dtests.seed=45289A6DD9A400F8 -Dtests.bwc=true -Dtests.locale=ar-SY -Dtests.timezone=Asia/Manila -Druntime.java=20
```

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT&tests.test=testGettingTimeWithoutCalendar

**Failure excerpt:**
```
java.lang.AssertionError: expected: java.sql.Time<14:09:31> but was: java.sql.Time<14:09:31>

  at __randomizedtesting.SeedInfo.seed([45289A6DD9A400F8:907ABE5F71F8D1D]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:118)
  at org.junit.Assert.assertEquals(Assert.java:144)
  at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingTimeWithoutCalendar$127(ResultSetTestCase.java:1276)
  at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:2025)
  at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:2013)
  at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingTimeWithoutCalendar(ResultSetTestCase.java:1272)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by valeriy42** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/3x4ftumygn76c

It seems to be related to #94461

**Comment by cbuescher** [comment]
Another one today on 7.17: https://gradle-enterprise.elastic.co/s/swuci54i5s6ow

**Comment by arteam** [comment]
https://gradle-enterprise.elastic.co/s/bxdqetxguw77y/tests/task/:x-pack:plugin:sql:qa:jdbc:single-node:v7.11.1%23bwcTest/details/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT/testGettingTimeWithoutCalendar

**Comment by ldematte** [comment]
Another one today on 7.17 https://gradle-enterprise.elastic.co/s/3nnotq3ewgsoo/tests/task/:x-pack:plugin:sql:qa:jdbc:single-node:v7.13.3%23bwcTest/details/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT/testGettingTimeWithoutCalendar?top-execution=1
