### ISSUE TITLE
[CI] JdbcFrozenCsvSpecIT test {frozen.testSum} failing

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#95951]
Caused by unrecognised TZ: `Europe/Kyiv`, which seems to have been updated from `Europe/Kiev`. Testing machines might need updating. (Logging it here for now.)

### CI Link

https://gradle-enterprise.elastic.co/s/6pht7osbgqly2

### Repro line

./gradlew ':x-pack:plugin:sql:qa:server:single-node:javaRestTest' --tests "org.elasticsearch.xpack.sql.qa.single_node.JdbcFrozenCsvSpecIT" -Dtests.method="test {frozen.testSum}" -Dtests.seed=B438E619ED5855DD -Dtests.locale=ar-LY -Dtests.timezone=America/Denver -Druntime.java=20

### Does it reproduce?

No

### Applicable branches

7.17

### Failure excerpt

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:sql:qa:server:single-node:javaRestTest' --tests "org.elasticsearch.xpack.sql.qa.single_node.JdbcFrozenCsvSpecIT" -Dtests.method="test {frozen.testSum}" -Dtests.seed=B438E619ED5855DD -Dtests.locale=ar-LY -Dtests.timezone=America/Denver -Druntime.java=20

org.elasticsearch.xpack.sql.qa.single_node.JdbcFrozenCsvSpecIT > test {frozen.testSum} FAILED
    java.sql.SQLException: Server sent bad type [x_content_parse_exception]. Original type was [[-1:86] [sql/query] failed to parse field [time_zone]]. [org.elasticsearch.xcontent.XContentParseException: [-1:86] [sql/query] failed to parse field [time_zone]
    	at org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:609)
    	at org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:604)
    	at org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:652)
    	at org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:320)
    	at org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:260)
    	at org.elasticsearch.xcontent.ObjectParser.apply(ObjectParser.java:393)
    	at org.elasticsearch.xpack.sql.action.SqlQueryRequest.fromXContent(SqlQueryRequest.java:335)
    	at org.elasticsearch.xpack.sql.plugin.RestSqlQueryAction.prepareRequest(RestSqlQueryAction.java:51)
    	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:86)
    	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:337)
    	at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:403)
    	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:255)
    	at org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:382)
    	at org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:461)
    	at org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:357)
    	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:35)
    	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:19)
    	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    	at org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:48)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
    	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
    	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    	at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: java.time.zone.ZoneRulesException: Unknown time-zone ID: Europe/Kyiv
    	at java.base/java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:280)
    	at java.base/java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:235)
    	at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:121)
    	at java.base/java.time.ZoneId.of(ZoneId.java:410)
    	at java.base/java.time.ZoneId.of(ZoneId.java:358)
    	at org.elasticsearch.xpack.sql.action.AbstractSqlQueryRequest.lambda$objectParser$1(AbstractSqlQueryRequest.java:125)
    	at org.elasticsearch.xcontent.ObjectParser.lambda$declareField$8(ObjectParser.java:424)
    	at org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:602)
    	... 65 more
```

**Comment by valeriy42** [comment]
Another test failure here: https://gradle-enterprise.elastic.co/s/gznqoo5vsp4n6

**Comment by pxsalehi** [comment]
More failure here https://gradle-enterprise.elastic.co/s/x5bx5yh2rlvbs

**Comment by mosche** [comment]
Closing, tracked in #106005
