### ISSUE TITLE
[CI] RestoreSnapshotIT testChangeSettingsOnRestore failing

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#96018]
**Build scan:**
https://gradle-enterprise.elastic.co/s/57brnuf4tdwpq/tests/:server:internalClusterTest/org.elasticsearch.snapshots.RestoreSnapshotIT/testChangeSettingsOnRestore

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.RestoreSnapshotIT.testChangeSettingsOnRestore" -Dtests.seed=E04845BEA9B6442F -Dtests.locale=uk -Dtests.timezone=America/Anguilla -Druntime.java=20
```

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.snapshots.RestoreSnapshotIT&tests.test=testChangeSettingsOnRestore

**Failure excerpt:**
```
java.lang.AssertionError: All incoming requests on node [node_s3] should have finished. Expected 0 but got 171; pending tasks [[]]

  at org.elasticsearch.test.InternalTestCluster.lambda$assertRequestsFinished$43(InternalTestCluster.java:2786)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1141)
  at org.elasticsearch.test.InternalTestCluster.assertRequestsFinished(InternalTestCluster.java:2775)
  at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2749)
  at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:622)
  at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2396)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by kingherc** [comment]
The underlying error seems to be [this one](https://gradle-enterprise.elastic.co/s/57brnuf4tdwpq/tests/:server:internalClusterTest/org.elasticsearch.snapshots.RestoreSnapshotIT/testChangeSettingsOnRestore/1/output):

```
[2023-05-11T04:57:50,228][INFO ][o.e.s.RestoreSnapshotIT  ] [testChangeSettingsOnRestore] --> restore index with correct settings from the snapshot
трав. 11, 2023 4:57:50 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#9334,elasticsearch[node_s3][generic][T#4],5,TGRP-RestoreSnapshotIT]
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([E04845BEA9B6442F]:0)
	at org.elasticsearch.indices.recovery.RecoveryTarget.restoreFileFromSnapshot(RecoveryTarget.java:570)
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RestoreFileFromSnapshotTransportRequestHandler.messageReceived(PeerRecoveryTargetService.java:590)
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RestoreFileFromSnapshotTransportRequestHandler.messageReceived(PeerRecoveryTargetService.java:575)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:67)
	at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:272)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

I have yet to understand why `assert hasPermitToDownloadSnapshotFiles();` fails in this scenario. I've been unable to reproduce it. It feels though like a genuine bug, since it should have the permit when it reaches that part of restoring from the snapshot.

One thing I see in the logs of the failure is that there were probably some relocations of shards that were cancelled because of a `cluster().wipeIndices("test-idx");` command of the test. That does not happen on every run. I would expect that the shards are gone for the command to return/complete. But I do wonder if there were any stale ongoing recoveries. I'll try to take more look into it, and if I cannot come up with something, I may continue with another test failure and hope the next person can delve more.

**Comment by DaveCTurner** [comment]
This seems super-rare but still an issue I think. The only failure in the last year was https://gradle-enterprise.elastic.co/s/ptwzzmbp6ecd4
