### ISSUE TITLE
[CI] CronEvalCliTests test10Install failing

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#96026]
**Build scan:**
https://gradle-enterprise.elastic.co/s/h723ygr4ew7qy/tests/:qa:os:destructiveDistroTest.default-windows-archive-no-jdk/org.elasticsearch.packaging.test.CronEvalCliTests/test10Install

**Reproduction line:**
```
null
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.CronEvalCliTests&tests.test=test10Install

**Failure excerpt:**
```
java.lang.RuntimeException: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch-7.17.11-SNAPSHOT -> C:\tmp\elasticsearch

  at __randomizedtesting.SeedInfo.seed([DC2405E221D1200F:307E091A7D419F55]:0)
  at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:136)
  at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:99)
  at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:62)
  at org.elasticsearch.packaging.test.PackagingTestCase.install(PackagingTestCase.java:218)
  at org.elasticsearch.packaging.test.CronEvalCliTests.test10Install(CronEvalCliTests.java:25)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch-7.17.11-SNAPSHOT -> C:\tmp\elasticsearch

    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:414)
    at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
    at java.nio.file.Files.move(Files.java:1429)
    at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:134)
    at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:99)
    at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:62)
    at org.elasticsearch.packaging.test.PackagingTestCase.install(PackagingTestCase.java:218)
    at org.elasticsearch.packaging.test.CronEvalCliTests.test10Install(CronEvalCliTests.java:25)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by kingherc** [comment]
Also appears in https://gradle-enterprise.elastic.co/s/cjnmrfnsb4org/tests/:qa:os:destructiveDistroTest.default-windows-archive/org.elasticsearch.packaging.test.CertGenCliTests/test10Install?top-execution=1 in 8.7 windows packaging.

**Comment by rjernst** [comment]
I wonder if some antivirus is running on the windows CI image, such that occasionally it happens to open up the distribution after we have extracted it but before we move it to the correct location. I think it would then have a lock on the file, and could result in the confusing "access denied" seen here.

**Comment by stu-elastic** [comment]
@mark-vieira is there something we can do to disable the antivirus in the CI machines?

**Comment by stu-elastic** [comment]
And indeed we do not see the failures recently, closing
![image](https://github.com/elastic/elasticsearch/assets/24232742/10c3a0b6-1195-436c-bc2e-f13b52d92cc7)
