### ISSUE TITLE
[CI] GeoIpUpgradeIT testGeoIpDownloader failing

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#96129]
From Tim Vernum:
It looks like something changes that now causes the GeoIPDownloader to run in the upgrade tests, when it didn't before.
I'm trying to see if I can track it down (else I'll just mute the test)

**Build scan:**
https://gradle-enterprise.elastic.co/s/xvui7goynb3wi/tests/:x-pack:qa:rolling-upgrade:v7.17.11%23upgradedClusterTest/org.elasticsearch.upgrades.GeoIpUpgradeIT/testGeoIpDownloader

**Reproduction line:**
```
./gradlew ':x-pack:qa:rolling-upgrade:v7.17.11#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.GeoIpUpgradeIT" -Dtests.method="testGeoIpDownloader" -Dtests.seed=4474E0B205A9EE78 -Dtests.bwc=true -Dtests.locale=mk -Dtests.timezone=Europe/Lisbon -Druntime.java=20
```

**Applicable branches:**
~~7.17~~ main, but seems to be upgrading from 7.17 in most cases

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.GeoIpUpgradeIT&tests.test=testGeoIpDownloader

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a string containing "failed_downloads\":0"
     but: was "{"stats":{"successful_downloads":0,"failed_downloads":1,"total_download_time":0,"databases_count":0,"skipped_updates":0,"expired_databases":0},"nodes":{}}"

  at __randomizedtesting.SeedInfo.seed([4474E0B205A9EE78:7F87CC10F00B7F80]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.upgrades.GeoIpUpgradeIT.lambda$testGeoIpDownloader$1(GeoIpUpgradeIT.java:33)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1158)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1131)
  at org.elasticsearch.upgrades.GeoIpUpgradeIT.testGeoIpDownloader(GeoIpUpgradeIT.java:29)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by tvernum** [comment]
@joemcelroy @jimczi 
It looks like this could be due to https://github.com/elastic/elasticsearch/pull/96104 (it looks like it might have undone https://github.com/elastic/elasticsearch/pull/95621)

**Comment by joemcelroy** [comment]
Hey @tvernum,

Yes short term we have undone this change but we plan to address it in this issue in the linked issue. Thanks for flagging!

**Comment by joemcelroy** [comment]
We are also going to remove the geoip processor, so that tests can be re-enabled. https://github.com/elastic/elasticsearch/pull/96159/files

**Comment by kingherc** [comment]
@joemcelroy feel free to re-enable tests when appropriate and close the issue.

**Comment by HiDAl** [comment]
Closing the ticket since all the related work is done and the test has not failed in the last weeks
