### ISSUE TITLE
update for query script that worked fine on 7.12.0 failed on 7.17.7

### ISSUE THREAD

**Issue by zhuangmm** [elastic/elasticsearch#96122]
### Elasticsearch Version

7.17.7

### Installed Plugins

analysis-icu 7.17.7, analysis-ik 7.17.7, analysis-pinyin 7.17.7

### Java Version

_bundled_

### OS Version

docker

### Problem Description

The script below works well on 7.12.0, but throws a null pointer exception on 7.17.7, which looks like a problem in the Elasticsearch code.
```
POST index_name/_update_by_query?conflicts=proceed&wait_for_completion=false
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "field1": {
              "value": "value"
            }
          }
        },
        {
          "term": {
            "field2": {
              "value": "old"
            }
          }
        }
      ]
    }
  },
  "script": {
    "source":
    """
        ctx._source['field2'] = 'new';
    """,
    "lang": "painless"
  }
}
```
The ```GET /``` result of 7.17.7 looks like this:
```
{
  "name" : "name",
  "cluster_name" : "cluster_name",
  "cluster_uuid" : "cluster_uuid",
  "version" : {
    "number" : "7.17.7",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "78dcaaa8cee33438b91eca7f5c7f56a70fec9e80",
    "build_date" : "2022-10-17T15:29:54.167373105Z",
    "build_snapshot" : false,
    "lucene_version" : "8.11.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

```
The ```GET /``` result of 7.12.0 looks like this:
```
{
  "name" : "name",
  "cluster_name" : "cluster_name",
  "cluster_uuid" : "cluster_uuid",
  "version" : {
    "number" : "7.12.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "78722783c38caa25a70982b5b042074cde5d3b3a",
    "build_date" : "2021-03-18T06:17:15.410153305Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

The ```GET /_cat/plugins``` result of 7.17.7 looks like this:
```
data-nodes-2   analysis-icu    7.17.7
data-nodes-2   analysis-ik     7.17.7
data-nodes-2   analysis-pinyin 7.17.7
master-nodes-1 analysis-icu    7.17.7
master-nodes-1 analysis-ik     7.17.7
master-nodes-1 analysis-pinyin 7.17.7
data-nodes-0   analysis-icu    7.17.7
data-nodes-0   analysis-ik     7.17.7
data-nodes-0   analysis-pinyin 7.17.7
master-nodes-0 analysis-icu    7.17.7
master-nodes-0 analysis-ik     7.17.7
master-nodes-0 analysis-pinyin 7.17.7
master-nodes-2 analysis-icu    7.17.7
master-nodes-2 analysis-ik     7.17.7
master-nodes-2 analysis-pinyin 7.17.7
data-nodes-1   analysis-icu    7.17.7
data-nodes-1   analysis-ik     7.17.7
data-nodes-1   analysis-pinyin 7.17.7
```
The ```GET /_cat/plugins``` result of 7.12.0 looks like this:
```
data-nodes-2   analysis-icu    7.12.0
data-nodes-2   analysis-ik     7.12.0
data-nodes-2   repository-hdfs 7.12.0
master-nodes-1 analysis-icu    7.12.0
master-nodes-1 analysis-ik     7.12.0
master-nodes-1 repository-hdfs 7.12.0
data-nodes-0   analysis-icu    7.12.0
data-nodes-0   analysis-ik     7.12.0
data-nodes-0   repository-hdfs 7.12.0
master-nodes-0 analysis-icu    7.12.0
master-nodes-0 analysis-ik     7.12.0
master-nodes-0 repository-hdfs 7.12.0
master-nodes-2 analysis-icu    7.12.0
master-nodes-2 analysis-ik     7.12.0
master-nodes-2 repository-hdfs 7.12.0
data-nodes-1   analysis-icu    7.12.0
data-nodes-1   analysis-ik     7.12.0
data-nodes-1   repository-hdfs 7.12.0
```

The error information looks like this:
```
      {
        "index" : "index_name",
        "type" : "_doc",
        "id" : "id",
        "cause" : {
          "type" : "null_pointer_exception",
          "reason" : """Cannot invoke "org.elasticsearch.cluster.metadata.IndexAbstraction.getIndices()" because "ia" is null"""
        },
        "status" : 500
      }
```

### Steps to Reproduce

runing this script on elasticsearch(version 7.17.7)

**Comment by puppylpg** [comment]
I've encountered the same problem:
```
{"type": "server", "timestamp": "2023-09-15T03:32:44,819Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "es-eed15189", "node.name": "es-eed15189-es-default-0", "message": "path: /<my-index>/_update/701966-wOvbq1Yn1b8, params: {routing=70966, index=<my-index>, id=70966-wOvbq1Yn1j8, retry_on_conflict=3, timeout=1m}", "cluster.uuid": "nMG6VGctSdGqO8gRgFpQZg", "node.id": "xJ7iGK_uRdit6Vxxk3wX-w" , 
"stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [es-eed15189-es-default-4][10.104.237.45:9300][indices:data/write/update[s]]",
"Caused by: java.lang.NullPointerException: Cannot invoke \"org.elasticsearch.cluster.metadata.IndexAbstraction.getIndices()\" because \"ia\" is null",
"at org.elasticsearch.xpack.enrich.EnrichCache.getEnrichIndexKey(EnrichCache.java:91) ~[?:?]",
"at org.elasticsearch.xpack.enrich.EnrichCache.get(EnrichCache.java:55) ~[?:?]",
"at org.elasticsearch.xpack.enrich.EnrichProcessorFactory.lambda$createSearchRunner$2(EnrichProcessorFactory.java:134) ~[?:?]",
"at org.elasticsearch.xpack.enrich.AbstractEnrichProcessor.execute(AbstractEnrichProcessor.java:85) ~[?:?]",
"at org.elasticsearch.ingest.ConditionalProcessor.execute(ConditionalProcessor.java:102) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:137) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:122) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:117) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.IngestDocument.executePipeline(IngestDocument.java:823) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.PipelineProcessor.execute(PipelineProcessor.java:34) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:137) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$1(CompoundProcessor.java:145) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.IngestDocument.lambda$executePipeline$1(IngestDocument.java:830) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.Pipeline.lambda$execute$0(Pipeline.java:123) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:127) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$1(CompoundProcessor.java:145) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.ConditionalProcessor.lambda$execute$1(ConditionalProcessor.java:109) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.Processor.execute(Processor.java:46) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.ConditionalProcessor.execute(ConditionalProcessor.java:102) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:137) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:122) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:117) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.IngestDocument.executePipeline(IngestDocument.java:823) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.PipelineProcessor.execute(PipelineProcessor.java:34) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:137) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:122) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:117) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.IngestDocument.executePipeline(IngestDocument.java:823) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.IngestService.innerExecute(IngestService.java:849) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.IngestService.executePipelines(IngestService.java:700) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.IngestService.access$000(IngestService.java:82) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.ingest.IngestService$3.doRun(IngestService.java:662) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.17.6.jar:7.17.6]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]",
"at java.lang.Thread.run(Thread.java:833) [?:?]"] }
```
Finally I found the reason: our generated enrich index(say '.enrich-policy-a') by enrich policy(say 'policy-a') is delete by elasticsearch as [#85221](https://github.com/elastic/elasticsearch/issues/85221) stated. NullPointerException happens when enriching documents in our pipeline because there is no such generated enrich index.

Seems that [upgrading to 7.17.10 will solve the problem](https://github.com/elastic/elasticsearch/pull/94702).

However I also think there should be NullPointerException check and throw index not found exception to the response so the user can understand what happens with the enrich index, rather than just "Caused by: java.lang.NullPointerException: Cannot invoke \"org.elasticsearch.cluster.metadata.IndexAbstraction.getIndices()\" because \"ia\" is null", which is confusing for user.

**Comment by jdconrad** [comment]
Closing this as it is unlikely to be prioritized.
