### ISSUE TITLE
8.8 - unix compatibility rhel-7&&immutable :x-pack:plugin:ccr:qa:multi-cluster:middle-cluster

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#96137]
### CI Link

https://gradle-enterprise.elastic.co/s/z66cr67udhaqw

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

8.8

### Failure excerpt

```
:x-pack:plugin:ccr:qa:multi-cluster:middle-cluster FAILED

=== Log output of node `node{:x-pack:plugin:ccr:qa:multi-cluster:middle-cluster-0}` ===

»    ↓ errors and warnings from /var/lib/jenkins/workspace/elastic+elasticsearch+8.8+multijob+platform-support-unix/x-pack/plugin/ccr/qa/multi-cluster/build/testclusters/middle-cluster-0/logs/es.out ↓
» [2023-05-16T00:59:58,337][WARN ][stderr                   ] [middle-cluster-0] SLF4J: No SLF4J providers were found.
»   ↑ repeated 2 times ↑
» [2023-05-16T00:59:58,338][WARN ][stderr                   ] [middle-cluster-0] SLF4J: Defaulting to no-operation (NOP) logger implementation
»   ↑ repeated 2 times ↑
» [2023-05-16T00:59:58,338][WARN ][stderr                   ] [middle-cluster-0] SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
»   ↑ repeated 2 times ↑
» [2023-05-16T00:59:58,339][WARN ][stderr                   ] [middle-cluster-0] SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
»   ↑ repeated 2 times ↑
» [2023-05-16T00:59:49,382][WARN ][stderr                   ] [middle-cluster-0] SLF4J: Ignoring binding found at [jar:file:///var/lib/jenkins/workspace/elastic+elasticsearch+8.8+multijob+platform-support-unix/distribution/archives/linux-tar/build/install/elasticsearch-8.8.0-SNAPSHOT/modules/repository-azure/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
» [2023-05-16T00:59:58,339][WARN ][stderr                   ] [middle-cluster-0] SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
»   ↑ repeated 2 times ↑
» [2023-05-16T00:59:53,699][WARN ][stderr                   ] [middle-cluster-0] May 16, 2023 12:59:53 AM org.apache.lucene.store.MemorySegmentIndexInputProvider <init>
» [2023-05-16T00:59:58,339][WARN ][stderr                   ] [middle-cluster-0] SLF4J: Ignoring binding found at [jar:file:///var/lib/jenkins/workspace/elastic+elasticsearch+8.8+multijob+platform-support-unix/distribution/archives/linux-tar/build/install/elasticsearch-8.8.0-SNAPSHOT/modules/x-pack-security/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
» [2023-05-16T01:00:00,001][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [middle-cluster-0] fatal error in thread [elasticsearch[middle-cluster-0][generic][T#4]], exiting java.lang.AssertionError: initial cluster state not set yet
»  	at org.elasticsearch.server@8.8.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:181)
»  	at org.elasticsearch.server@8.8.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:141)
»  	at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporter.onCleanUpIndices(LocalExporter.java:598)
»  	at org.elasticsearch.xpack.monitoring.cleaner.CleanerService$IndicesCleaner.doRunInLifecycle(CleanerService.java:164)
»  	at org.elasticsearch.server@8.8.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractLifecycleRunnable.doRun(AbstractLifecycleRunnable.java:56)
»  	at org.elasticsearch.server@8.8.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
»  	at org.elasticsearch.server@8.8.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»  	at java.base/java.lang.Thread.run(Thread.java:1623)
»  
»  
»  ERROR: Elasticsearch exited unexpectedly
»   ↓ last 40 non error or warning messages from /var/lib/jenkins/workspace/elastic+elasticsearch+8.8+multijob+platform-support-unix/x-pack/plugin/ccr/qa/multi-cluster/build/testclusters/middle-cluster-0/logs/es.out ↓
» [2023-05-16T00:59:50,964][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [x-pack-deprecation]
» [2023-05-16T00:59:50,964][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [x-pack-fleet]
» [2023-05-16T00:59:50,965][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [x-pack-profiling]
» [2023-05-16T00:59:50,965][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [ingest-geoip]
» [2023-05-16T00:59:50,965][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [x-pack-write-load-forecaster]
» [2023-05-16T00:59:50,965][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [search-business-rules]
» [2023-05-16T00:59:50,965][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [ingest-attachment]
» [2023-05-16T00:59:50,965][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [wildcard]
» [2023-05-16T00:59:50,966][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [unsigned-long]
» [2023-05-16T00:59:50,966][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [x-pack-sql]
» [2023-05-16T00:59:50,966][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [runtime-fields-common]
» [2023-05-16T00:59:50,966][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [x-pack-async]
» [2023-05-16T00:59:50,966][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [vector-tile]
» [2023-05-16T00:59:50,966][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [lang-expression]
» [2023-05-16T00:59:50,967][INFO ][o.e.p.PluginsService     ] [middle-cluster-0] loaded module [x-pack-eql]
» [2023-05-16T00:59:51,135][INFO ][o.e.c.u.FeatureFlag      ] [middle-cluster-0] The current build is a snapshot, feature flag [dlm] is enabled
» [2023-05-16T00:59:53,709][INFO ][o.e.e.NodeEnvironment    ] [middle-cluster-0] using [1] data paths, mounts [[/ (/dev/sda2)]], net usable_space [242.8gb], net total_space [349.7gb], types [xfs]
» [2023-05-16T00:59:53,709][INFO ][o.e.e.NodeEnvironment    ] [middle-cluster-0] heap size [512mb], compressed ordinary object pointers [true]
» [2023-05-16T00:59:53,720][INFO ][o.e.n.Node               ] [middle-cluster-0] node name [middle-cluster-0], node ID [lTgOniHcRe68G485Ny7qoA], cluster name [middle-cluster], roles [data_warm, data_content, transform, data_hot, ml, data_frozen, ingest, data_cold, data, remote_cluster_client, master]
» [2023-05-16T00:59:56,109][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [middle-cluster-0] [controller/637077] [Main.cc@123] controller (64 bit): Version 8.8.0-SNAPSHOT (Build 0186ebafa53543) Copyright (c) 2023 Elasticsearch BV
» [2023-05-16T00:59:56,308][INFO ][o.e.x.s.Security         ] [middle-cluster-0] Security is enabled
» [2023-05-16T00:59:56,695][INFO ][o.e.x.s.a.s.FileRolesStore] [middle-cluster-0] parsed [1] roles from file [/var/lib/jenkins/workspace/elastic+elasticsearch+8.8+multijob+platform-support-unix/x-pack/plugin/ccr/qa/multi-cluster/build/testclusters/middle-cluster-0/config/roles.yml]
» [2023-05-16T00:59:57,579][INFO ][o.e.x.p.ProfilingPlugin  ] [middle-cluster-0] Profiling is enabled
» [2023-05-16T00:59:58,376][INFO ][o.e.t.n.NettyAllocator   ] [middle-cluster-0] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=1mb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=4mb, heap_size=512mb}]
» [2023-05-16T00:59:58,417][INFO ][o.e.i.r.RecoverySettings ] [middle-cluster-0] using rate limit [40mb] with [default=40mb, read=0b, write=0b, max=0b]
» [2023-05-16T00:59:58,471][INFO ][o.e.d.DiscoveryModule    ] [middle-cluster-0] using discovery type [multi-node] and seed hosts providers [settings, file]
» [2023-05-16T00:59:59,912][INFO ][o.e.n.Node               ] [middle-cluster-0] initialized
» [2023-05-16T00:59:59,914][INFO ][o.e.n.Node               ] [middle-cluster-0] starting ...
» [2023-05-16T00:59:59,970][INFO ][o.e.x.s.c.f.PersistentCache] [middle-cluster-0] persistent cache index loaded
» [2023-05-16T00:59:59,971][INFO ][o.e.x.d.l.DeprecationIndexingComponent] [middle-cluster-0] deprecation component started
» [2023-05-16T01:00:00.408144091Z] [BUILD] Stopping node

=== Log output of node `node{:x-pack:plugin:ccr:qa:multi-cluster:leader-cluster-0}` ===

»    ↓ errors and warnings from /var/lib/jenkins/workspace/elastic+elasticsearch+8.8+multijob+platform-support-unix/x-pack/plugin/ccr/qa/multi-cluster/build/testclusters/leader-cluster-0/logs/es.out ↓
» [2023-05-16T00:07:02,437][WARN ][stderr                   ] [leader-cluster-0] SLF4J: No SLF4J providers were found.
»   ↑ repeated 2 times ↑
» [2023-05-16T00:07:02,437][WARN ][stderr                   ] [leader-cluster-0] SLF4J: Defaulting to no-operation (NOP) logger implementation
»   ↑ repeated 2 times ↑
» [2023-05-16T00:07:02,437][WARN ][stderr                   ] [leader-cluster-0] SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
»   ↑ repeated 2 times ↑
» [2023-05-16T00:07:02,438][WARN ][stderr                   ] [leader-cluster-0] SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
»   ↑ repeated 2 times ↑
» [2023-05-16T00:06:52,735][WARN ][stderr                   ] [leader-cluster-0] SLF4J: Ignoring binding found at [jar:file:///var/lib/jenkins/workspace/elastic+elasticsearch+8.8+multijob+platform-support-unix/distribution/archives/linux-tar/build/install/elasticsearch-8.8.0-SNAPSHOT/modules/repository-azure/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
» [2023-05-16T00:07:02,438][WARN ][stderr                   ] [leader-cluster-0] SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
»   ↑ repeated 2 times ↑
» [2023-05-16T00:06:57,562][WARN ][stderr                   ] [leader-cluster-0] May 16, 2023 12:06:57 AM org.apache.lucene.store.MemorySegmentIndexInputProvider <init>
» [2023-05-16T00:07:02,438][WARN ][stderr                   ] [leader-cluster-0] SLF4J: Ignoring binding found at [jar:file:///var/lib/jenkins/workspace/elastic+elasticsearch+8.8+multijob+platform-support-unix/distribution/archives/linux-tar/build/install/elasticsearch-8.8.0-SNAPSHOT/modules/x-pack-security/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
» [2023-05-16T00:07:04,543][WARN ][o.e.b.BootstrapChecks    ] [leader-cluster-0] Transport SSL must be enabled if security is enabled. Please set [xpack.security.transport.ssl.enabled] to [true] or disable security by setting [xpack.security.enabled] to [false]
» [2023-05-16T00:07:04,552][WARN ][o.e.d.FileBasedSeedHostsProvider] [leader-cluster-0] expected, but did not find, a dynamic hosts list at [/var/lib/jenkins/workspace/elastic+elasticsearch+8.8+multijob+platform-support-unix/x-pack/plugin/ccr/qa/multi-cluster/build/testclusters/leader-cluster-0/config/unicast_hosts.txt]
»   ↓ last 40 non error or warning messages from /var/lib/jenkins/workspace/elastic+elasticsearch+8.8+multijob+platform-support-unix/x-pack/plugin/ccr/qa/multi-cluster/build/testclusters/leader-cluster-0/logs/es.out ↓
» [2023-05-16T00:07:06,123][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [7-days-default]
» [2023-05-16T00:07:06,158][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [180-days-default]
» [2023-05-16T00:07:06,192][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [logs]
» [2023-05-16T00:07:06,224][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [90-days-default]
» [2023-05-16T00:07:06,256][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [synthetics]
» [2023-05-16T00:07:06,285][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [365-days-default]
» [2023-05-16T00:07:06,315][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [watch-history-ilm-policy-16]
» [2023-05-16T00:07:06,347][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [ilm-history-ilm-policy]
» [2023-05-16T00:07:06,377][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [slm-history-ilm-policy]
» [2023-05-16T00:07:06,406][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [.deprecation-indexing-ilm-policy]
» [2023-05-16T00:07:06,435][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [.fleet-file-data-ilm-policy]
» [2023-05-16T00:07:06,464][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [.fleet-files-ilm-policy]
» [2023-05-16T00:07:06,494][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [leader-cluster-0] adding index lifecycle policy [.fleet-actions-results-ilm-policy]
» [2023-05-16T00:07:06,561][INFO ][o.e.h.n.s.HealthNodeTaskExecutor] [leader-cluster-0] Node [{leader-cluster-0}{x9iHjM4ZQiS3rh-EeMsS7w}] is selected as the current health node.
» [2023-05-16T00:07:06,646][INFO ][o.e.l.ClusterStateLicenseService] [leader-cluster-0] license [442508d1-4ecf-4e59-9775-a03ee4f5c90f] mode [trial] - valid
» [2023-05-16T00:07:06,647][INFO ][o.e.x.s.a.Realms         ] [leader-cluster-0] license mode is [trial], currently licensed security realms are [reserved/reserved,file/default_file,native/default_native]
» [2023-05-16T00:07:08,430][INFO ][o.e.c.m.MetadataCreateIndexService] [leader-cluster-0] [leader] creating index, cause [api], templates [], shards [1]/[1]
» [2023-05-16T00:07:08,787][INFO ][o.e.c.m.MetadataMappingService] [leader-cluster-0] [leader/7YKMumJuTqmCoFMTFDgGBg] update_mapping [_doc]
» [2023-05-16T00:07:10,865][INFO ][o.e.c.m.MetadataCreateIndexService] [leader-cluster-0] [override_leader_index] creating index, cause [api], templates [], shards [1]/[1]
» [2023-05-16T00:07:11,014][INFO ][o.e.c.m.MetadataCreateIndexService] [leader-cluster-0] [override_leader_index_non_existent_setting] creating index, cause [api], templates [], shards [1]/[1]
» [2023-05-16T00:07:11,164][INFO ][o.e.c.m.MetadataCreateIndexService] [leader-cluster-0] [test_index1] creating index, cause [api], templates [], shards [1]/[1]
» [2023-05-16T00:07:11,309][INFO ][o.e.c.m.MetadataMappingService] [leader-cluster-0] [test_index1/fcuD-EOSRKanQfSoVW9dbA] update_mapping [_doc]
» [2023-05-16T00:07:12,812][INFO ][o.e.c.m.MetadataCreateIndexService] [leader-cluster-0] [tsdb_leader] creating index, cause [api], templates [], shards [1]/[1]
» [2023-05-16T00:07:14,328][INFO ][o.e.c.m.MetadataCreateIndexService] [leader-cluster-0] [synthetic_leader] creating index, cause [api], templates [], shards [1]/[1]
» [2023-05-16T00:07:14,488][INFO ][o.e.c.m.MetadataMappingService] [leader-cluster-0] [synthetic_leader/bN0ngHO2RHW7tlQxZCxmJw] update_mapping [_doc]
» [2023-05-16T00:07:15,737][INFO ][o.e.r.RepositoriesService] [leader-cluster-0] put repository [repository-testfollowsearchablesnapshotsfails]
» [2023-05-16T00:07:15,797][INFO ][o.e.c.m.MetadataCreateIndexService] [leader-cluster-0] [index-testfollowsearchablesnapshotsfails] creating index, cause [api], templates [], shards [1]/[1]
» [2023-05-16T00:07:15,926][INFO ][o.e.s.SnapshotsService   ] [leader-cluster-0] deleting snapshots [snapshot-testfollowsearchablesnapshotsfails] from repository [repository-testfollowsearchablesnapshotsfails]
» [2023-05-16T00:07:15,964][INFO ][o.e.s.SnapshotsService   ] [leader-cluster-0] snapshot [repository-testfollowsearchablesnapshotsfails:snapshot-testfollowsearchablesnapshotsfails/PuZG-IuzTm6_syqvmYcvBg] started
» [2023-05-16T00:07:16,251][INFO ][o.e.s.SnapshotsService   ] [leader-cluster-0] snapshot [repository-testfollowsearchablesnapshotsfails:snapshot-testfollowsearchablesnapshotsfails/PuZG-IuzTm6_syqvmYcvBg] completed with state [SUCCESS]
» [2023-05-16T00:07:16,257][INFO ][o.e.c.m.MetadataDeleteIndexService] [leader-cluster-0] [index-testfollowsearchablesnapshotsfails/PrccgHzRSxaEz_unVu5CQg] deleting index
» [2023-05-16T01:00:00.411391374Z] [BUILD] Stopping node
» [2023-05-16T01:00:00,434][INFO ][o.e.n.Node               ] [leader-cluster-0] stopping ...
» [2023-05-16T01:00:00,435][INFO ][o.e.c.f.AbstractFileWatchingService] [leader-cluster-0] shutting down watcher thread
» [2023-05-16T01:00:00,436][INFO ][o.e.c.f.AbstractFileWatchingService] [leader-cluster-0] watcher service stopped
» [2023-05-16T01:00:00,439][INFO ][o.e.x.w.WatcherService   ] [leader-cluster-0] stopping watch service, reason [shutdown initiated]
» [2023-05-16T01:00:00,439][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [leader-cluster-0] [controller/535472] [Main.cc@176] ML controller exiting
» [2023-05-16T01:00:00,439][INFO ][o.e.x.m.p.NativeController] [leader-cluster-0] Native controller process has stopped - no new native processes can be started
» [2023-05-16T01:00:00,440][INFO ][o.e.x.w.WatcherLifeCycleService] [leader-cluster-0] watcher has stopped and shutdown
```

**Comment by pxsalehi** [comment]
I've taken a brief look at this. It is kind of difficult to see when else has this failed. At least based on the `#es-test-triage` this seems to have happened only once. The error might indicate that the CCR setup which I think is done via some Gradle task has gone wrong. Frankly, not sure if this worths investing more time in. At least until it happens again.

**Comment by davidkyle** [comment]
>  Frankly, not sure if this worths investing more time in. At least until it happens again.

It happened again https://gradle-enterprise.elastic.co/s/63npk4s2r7d32/console-log?task=:x-pack:qa:rolling-upgrade:v8.0.0%23twoThirdsUpgradedTest

**Comment by idegtiarenko** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/100565
