### ISSUE TITLE
[CI] ListenerActionIT testThreadedListeners failing

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#96142]
Multiple warnings like

```
  1> [2023-05-15T21:48:17,113][WARN ][o.e.t.n.MockNioTransport ] [node_s0] Potentially blocked execution on network thread [elasticsearch[node_s0][transport_worker][T#2]] [RUNNABLE] [1400 milliseconds]: 	
  1> java.base/sun.nio.ch.Net.accept(Native Method)	
  1> java.base/sun.nio.ch.ServerSocketChannelImpl.implAccept(ServerSocketChannelImpl.java:433)	
  1> java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:399)	
  1> java.base/java.security.AccessController.doPrivileged(AccessController.java:571)	
  1> org.elasticsearch.nio.ServerChannelContext.accept(ServerChannelContext.java:107)	
  1> org.elasticsearch.transport.nio.MockNioTransport$MockTcpChannelFactory$1.acceptChannels(MockNioTransport.java:270)	
  1> org.elasticsearch.nio.EventHandler.acceptChannel(EventHandler.java:34)	
  1> org.elasticsearch.transport.nio.TestEventHandler.acceptChannel(TestEventHandler.java:43)	
  1> org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:223)	
  1> org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:168)	
  1> org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:125)	
  1> java.base/java.lang.Thread.run(Thread.java:1623)
```

There seems to be older related issues such as #44610 or #50597.

I note 7.17 branch due to original failure, but it may be on main as well.

**Build scan:**
https://gradle-enterprise.elastic.co/s/fldz4e7xmv45i/tests/:server:internalClusterTest/org.elasticsearch.action.ListenerActionIT/testThreadedListeners

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.ListenerActionIT.testThreadedListeners" -Dtests.seed=D7C87C1038D6542A -Dtests.locale=fr -Dtests.timezone=Pacific/Pago_Pago -Druntime.java=20
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.ListenerActionIT&tests.test=testThreadedListeners

**Failure excerpt:**
```
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{eeYOWC1sSNm8qX8PpbRmhA}{127.0.0.1}{127.0.0.1:17562}]

  at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:250)
  at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:51)
  at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:463)
  at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:407)
  at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:392)
  at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:699)
  at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:34)
  at org.elasticsearch.test.TestCluster.wipeRepositories(TestCluster.java:207)
  at org.elasticsearch.test.TestCluster.wipe(TestCluster.java:71)
  at org.elasticsearch.test.ESIntegTestCase.lambda$beforeInternal$0(ESIntegTestCase.java:378)
  at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
  at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
  at org.elasticsearch.test.ESIntegTestCase.beforeInternal(ESIntegTestCase.java:386)
  at org.elasticsearch.test.ESIntegTestCase.setupTestCluster(ESIntegTestCase.java:2380)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by Tim-Brooks** [comment]
This is the same issue as https://github.com/elastic/elasticsearch/issues/43387#issuecomment-587440563.

The failure is due to non-blocking network calls blocking for some reason on debian9. And then the test failing because the nodes are not blocking.

**Comment by kingherc** [comment]
@Tim-Brooks , I see the issue you mentioned was closed because "There's nothing we can do on the ES side here". And suggests we close it here as well. I'll close it then. Feel free to tell me whether we should re-open it.
