### ISSUE TITLE
uploadElasticsearchSnapshotCsvDependencyReportFiles failed with Invalid JWT Signature

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#96166]
### CI Link

https://gradle-enterprise.elastic.co/s/im5euek2bp6xe

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

7.17

### Failure excerpt

```
Error getting access token for service account: 400 Bad Request
POST https://oauth2.googleapis.com/token
{"error":"invalid_grant","error_description":"Invalid JWT Signature."}, iss: vaultelastic-artifa-1662587459@elastic-release-1e491b93.iam.gserviceaccount.com
> Error getting access token for service account: 400 Bad Request
  POST https://oauth2.googleapis.com/token
  {"error":"invalid_grant","error_description":"Invalid JWT Signature."}, iss: vaultelastic-artifa-1662587459@elastic-release-1e491b93.iam.gserviceaccount.com
  > 400 Bad Request
    POST https://oauth2.googleapis.com/token
    {"error":"invalid_grant","error_description":"Invalid JWT Signature."}
Exception
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':uploadElasticsearchSnapshotCsvDependencyReportFiles'.	
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)	
•••
Caused by: com.google.cloud.storage.StorageException: Error getting access token for service account: 400 Bad Request	
POST https://oauth2.googleapis.com/token	
{"error":"invalid_grant","error_description":"Invalid JWT Signature."}, iss: vaultelastic-artifa-1662587459@elastic-release-1e491b93.iam.gserviceaccount.com	
at com.google.cloud.storage.StorageException.translate(StorageException.java:165)	
•••
at co.elastic.release.manager.storage.gcs.GoogleCloudStorageUpload.uploadFile(GoogleCloudStorageUpload.groovy:73)	
at co.elastic.release.manager.storage.gcs.GoogleCloudStorageUpload.upload(GoogleCloudStorageUpload.groovy:43)	
at co.elastic.release.manager.storage.task.UploadTask.action(UploadTask.groovy:56)	
•••
Caused by: com.google.auth.oauth2.GoogleAuthException: Error getting access token for service account: 400 Bad Request	
POST https://oauth2.googleapis.com/token	
{"error":"invalid_grant","error_description":"Invalid JWT Signature."}, iss: vaultelastic-artifa-1662587459@elastic-release-1e491b93.iam.gserviceaccount.com	
at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:131)	
•••
at co.elastic.release.manager.storage.gcs.GoogleCloudStorageUpload.uploadFile(GoogleCloudStorageUpload.groovy:73)	
at co.elastic.release.manager.storage.gcs.GoogleCloudStorageUpload.upload(GoogleCloudStorageUpload.groovy:43)	
at co.elastic.release.manager.storage.task.UploadTask.action(UploadTask.groovy:56)	
•••
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request	
POST https://oauth2.googleapis.com/token	
{"error":"invalid_grant","error_description":"Invalid JWT Signature."}	
at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)	
•••
at co.elastic.release.manager.storage.gcs.GoogleCloudStorageUpload.uploadFile(GoogleCloudStorageUpload.groovy:73)	
at co.elastic.release.manager.storage.gcs.GoogleCloudStorageUpload.upload(GoogleCloudStorageUpload.groovy:43)	
at co.elastic.release.manager.storage.task.UploadTask.action(UploadTask.groovy:56)
```

**Comment by mark-vieira** [comment]
This is an ephemeral infra issue they are investigating.
