### ISSUE TITLE
[CI] EncryptedAzureBlobStoreRepositoryIntegTests testSnapshotWithLargeSegmentFiles failing

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#96246]
**Build scan:**
https://gradle-enterprise.elastic.co/s/ncfior7imz72k/tests/:x-pack:plugin:repository-encrypted:internalClusterTest/org.elasticsearch.repositories.encrypted.EncryptedAzureBlobStoreRepositoryIntegTests/testSnapshotWithLargeSegmentFiles

**Reproduction line:**
```
gradlew ':x-pack:plugin:repository-encrypted:internalClusterTest' --tests "org.elasticsearch.repositories.encrypted.EncryptedAzureBlobStoreRepositoryIntegTests.testSnapshotWithLargeSegmentFiles" -Dtests.seed=DB522246BD1F365E -Dtests.locale=el-GR -Dtests.timezone=Etc/GMT-2 -Druntime.java=20
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.repositories.encrypted.EncryptedAzureBlobStoreRepositoryIntegTests&tests.test=testSnapshotWithLargeSegmentFiles

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=181, name=[org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase][T#2], state=RUNNABLE, group=TGRP-EncryptedAzureBlobStoreRepositoryIntegTests]

  at __randomizedtesting.SeedInfo.seed([DB522246BD1F365E:CC6828BB23856220]:0)

  Caused by: java.lang.AssertionError: State is not REQUEST (IDLE)

    at __randomizedtesting.SeedInfo.seed([DB522246BD1F365E]:0)
    at sun.net.httpserver.ServerImpl.requestCompleted(ServerImpl.java:984)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:761)
    at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase.lambda$startHttpServer$0(ESMockAPIBasedRepositoryIntegTestCase.java:105)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by pxsalehi** [comment]
I've taken a brief look into this. If I'm not mistaken these encrypted repo implementations are not used and are even removed in newer versions. Plus there are only a few failures and it is some internal assertion error from the JDK. I'm not sure this worths spending time on.
<img width="1153" alt="image" src="https://github.com/elastic/elasticsearch/assets/3340727/0cb654ab-7278-4b29-a197-5dd75971d74a">

**Comment by original-brownbear** [comment]
++ yes this code is unused. I'd suggest we just mute or better yet delete these tests in 7.17 and not worry about this again.
