### ISSUE TITLE
[CI] VariableWidthHistogramAggregatorTests testMultipleSegments failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#96295]
This happened in a PR but I don't think its related to the change there. Also I couldn't reproduce locally with the given seed, but I found a few similar looking errors in recent CI history that I will add here, hoping the build scans of those are still there.

**Build scan:**
https://gradle-enterprise.elastic.co/s/3fehoe67iezom/tests/:server:test/org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests/testMultipleSegments

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests.testMultipleSegments" -Dtests.seed=38D40B77C192C67A -Dtests.locale=ms-MY -Dtests.timezone=Pacific/Bougainville -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests&tests.test=testMultipleSegments

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: (a value equal to or greater than <4L> and a value less than or equal to <7L>)
     but: a value equal to or greater than <4L> <3L> was less than <4L>

  at __randomizedtesting.SeedInfo.seed([38D40B77C192C67A:84A3BE2E06356A3F]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests.lambda$testMultipleSegments$31(VariableWidthHistogramAggregatorTests.java:454)
  at org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests.testSearchCase(VariableWidthHistogramAggregatorTests.java:634)
  at org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests.testMultipleSegments(VariableWidthHistogramAggregatorTests.java:438)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by cbuescher** [comment]
Here is a similar one from last year on 8.0: https://gradle-enterprise.elastic.co/s/e4hwix4wbvoqq/tests/:server:test/org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests/testMultipleSegments?top-execution=1
And one later on 8.2: https://gradle-enterprise.elastic.co/s/rvogt2qautmmk/tests/:server:test/org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests/testMultipleSegments?top-execution=1
