### ISSUE TITLE
[CI] SnapshotBasedIndexRecoveryIT testCancelledRecoveryAbortsDownloadPromptly failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#96618]
**Build scan:**
https://gradle-enterprise.elastic.co/s/53sat6a2fhmxu/tests/:x-pack:plugin:snapshot-based-recoveries:internalClusterTest/org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT/testCancelledRecoveryAbortsDownloadPromptly

**Reproduction line:**
```
./gradlew ':x-pack:plugin:snapshot-based-recoveries:internalClusterTest' --tests "org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT.testCancelledRecoveryAbortsDownloadPromptly" -Dtests.seed=2DC52CF2899BDFFF -Dtests.locale=da -Dtests.timezone=America/Cancun -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT&tests.test=testCancelledRecoveryAbortsDownloadPromptly

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertTrue(Assert.java:52)
  at org.elasticsearch.test.ESTestCase.safeAwait(ESTestCase.java:1990)
  at org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT.testCancelledRecoveryAbortsDownloadPromptly(SnapshotBasedIndexRecoveryIT.java:757)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by dakrone** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/u6hcqknmrkiuq

**Comment by andreidan** [comment]
Another failure https://gradle-enterprise.elastic.co/s/esfo5ohslpwk6

**Comment by DaveCTurner** [comment]
Thanks both, the logs from the latest failure are helpful. I'll mute this while I work on a fix.

**Comment by DaveCTurner** [comment]
The failure mentioned above is now addressed, but I am leaving this issue open (and the more verbose logging in place) for a few days in case there's any other problems. If it's all good in a week then we can close this with a PR to remove that extra logging.

**Comment by kingherc** [comment]
I have a new one on 8.9: https://gradle-enterprise.elastic.co/s/jbutb4r3b4cpq with different message:

```
[2023-07-19T14:03:49,334][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_t0] [lspqltidii/NakJMSp0SUuzuLjKTPu_xg] deleting index	
[2023-07-19T14:03:49,348][TRACE][o.e.i.r.PeerRecoveryTargetService] [node_t1] [lspqltidii][0] canceled recovery from {node_t3}{d0yk0xkhSvqDMVcKYp9pCA}{9NzSwnU4SoKRoI-erJG52A}{node_t3}{127.0.0.1}{127.0.0.1:21764}{cdfhilrstw}{8.9.0}, id [15] (reason [shard closed])	
[2023-07-19T14:03:49,348][DEBUG][o.e.i.r.RecoveryTarget   ] [node_t1] [lspqltidii][0] recovery canceled (reason: [shard closed])	
[2023-07-19T14:03:49,349][WARN ][o.e.i.IndexSettings      ] [node_t2] [lspqltidii] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments	
[2023-07-19T14:03:49,349][WARN ][o.e.i.IndexSettings      ] [node_t2] [lspqltidii] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments	
[2023-07-19T14:03:49,349][DEBUG][o.e.i.r.RecoverySourceHandler] [node_t3] [lspqltidii][0][recover to node_t1] cancelled while recovering file [name [_0.cfe], length [934], checksum [1u4cony], writtenBy [9.7.0]] from snapshot	
org.elasticsearch.common.util.CancellableThreads$ExecutionCancelledException: recovery was cancelled	
	at org.elasticsearch.indices.recovery.RemoteRecoveryTargetHandler.cancel(RemoteRecoveryTargetHandler.java:316) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.cancel(RecoverySourceHandler.java:1319) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService$OngoingRecoveries.cancel(PeerRecoverySourceService.java:259) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService.beforeIndexShardClosed(PeerRecoverySourceService.java:121) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.index.CompositeIndexEventListener.beforeIndexShardClosed(CompositeIndexEventListener.java:89) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.index.IndexService.closeShard(IndexService.java:574) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.index.IndexService.removeShard(IndexService.java:562) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.index.IndexService.close(IndexService.java:358) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:902) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:322) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:245) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:536) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:522) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:495) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:426) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]	
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```
