### ISSUE TITLE
[CI] Failed for task ':x-pack:qa:repository-old-versions:javaRestTestAfterRestart#6_8_20'

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#96639]
### CI Link

https://gradle-enterprise.elastic.co/s/bn2fsotfl46mm

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

8.8

### Failure excerpt

The error on the surface is 
> process was found dead while waiting for ports files

which seems to be transient due to cluster not bootstrapped in time. But there are lots of exceptions like the following in the log file which seems to worth a closer look by relevant experts

```
» [2023-06-07T00:58:21,221][WARN ][r.suppressed             ] [6-8-20-0] path: /mounted_shared_cache_test_index/_doc/testdoc5, params: {index=mounted_shared_cache_test_index, id=testdoc5} org.elasticsearch.transport.RemoteTransportException: [6-8-20-1][127.0.0.1:38717][indices:data/read/get[s]]
»  Caused by: java.lang.IllegalStateException: get operations not allowed on a legacy index
»   at org.elasticsearch.index.shard.IndexShard.get(IndexShard.java:1219)
»   at org.elasticsearch.index.get.ShardGetService.innerGet(ShardGetService.java:204)
»   at org.elasticsearch.index.get.ShardGetService.get(ShardGetService.java:107)
»   at org.elasticsearch.index.get.ShardGetService.get(ShardGetService.java:80)
»   at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:114)
»   at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:34)
»   at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.lambda$asyncShardOperation$0(TransportSingleShardAction.java:103)
»   at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:50)
»   at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:47)
»   at org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:72)
»   at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
»   at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»   at java.lang.Thread.run(Thread.java:1623)
```

**Comment by DaveCTurner** [comment]
`process was found dead while waiting for ports files` is almost always due to a tripping assertion causing the node to crash at startup. In this case it's the same thing as in https://github.com/elastic/elasticsearch/issues/94126:

```
» [2023-06-07T01:00:00,002][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [6-8-20-1] fatal error in thread [elasticsearch[6-8-20-1][generic][T#1]], exiting java.lang.AssertionError: initial cluster state not set yet
»       at org.elasticsearch.server@8.8.1-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:181)
»       at org.elasticsearch.server@8.8.1-SNAPSHOT/org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:141)
»       at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporter.onCleanUpIndices(LocalExporter.java:598)
»       at org.elasticsearch.xpack.monitoring.cleaner.CleanerService$IndicesCleaner.doRunInLifecycle(CleanerService.java:164)
»       at org.elasticsearch.server@8.8.1-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractLifecycleRunnable.doRun(AbstractLifecycleRunnable.java:56)
»       at org.elasticsearch.server@8.8.1-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
»       at org.elasticsearch.server@8.8.1-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»       at java.base/java.lang.Thread.run(Thread.java:1623)
```

Apparently that's now fixed so I'm closing this. The noise about `get operations not allowed on a legacy index` doesn't seem to be relevant, or causing any issues.
