### ISSUE TITLE
the remote cluster connection will time out when the node restarts and the remote cluster seeds is point to itself

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#96650]
### Elasticsearch Version

7.10.2

### Java Version

_bundled_

### OS Version

Debian 4.19.117.bsk.12 Thu Mar 17 16:41:16  x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

We configure many remote clusters pointing to the cluster to satisfy the needs, the seeds are the domain name of the cluster,  in the common case, the domain name will map to the local node.

If the node restart, it will not join the cluster successfully because of block.

### Steps to Reproduce

The cluster: data0: (127.0.0.1:9200), master1 (127.0.0.1:9201), master2 (127.0.0.1:9202)
Step1: the cluster is healthy, contains the three nodes.
Step2: set 10 remote cluster settings, the remote_name={remote1...remote10}, which all point to the data0
```
PUT _cluster/settings
{
 "persistent" : {
    "cluster" : {
      "remote" : {
        "{remote_name}" : {
          "skip_unavailable" : "true",
          "seeds" : [
            "127.0.0.1:9300"
          ]
        }
      }
    }
 }
}
``` 
Step3: kill the data0, then the data will be blocked when joining cluster.

### Logs (if relevant)

The blocked jvm stack is as follows:
```
"elasticsearch[data0][clusterApplierService#updateTask][T#1]" #42 daemon prio=5 os_prio=0 cpu=2872.02ms elapsed=415.73s tid=0x00007fc440e08980 nid=0x130 runnable  [0x00007fc448af4000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@15.0.1/Native Method)
        - parking to wait for  <0x00007fcb8a8527c8> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@15.0.1/LockSupport.java:252)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@15.0.1/AbstractQueuedSynchronizer.java:716)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(java.base@15.0.1/AbstractQueuedSynchronizer.java:1073)
        at java.util.concurrent.CountDownLatch.await(java.base@15.0.1/CountDownLatch.java:278)
        at org.elasticsearch.transport.RemoteClusterService.updateRemoteCluster(RemoteClusterService.java:298)
        at org.elasticsearch.transport.RemoteClusterAware.validateAndUpdateRemoteCluster(RemoteClusterAware.java:111)
        at org.elasticsearch.transport.RemoteClusterAware$$Lambda$2441/0x0000000801519ca8.accept(Unknown Source)
        at org.elasticsearch.common.settings.AbstractScopedSettings$2.apply(AbstractScopedSettings.java:354)
        at org.elasticsearch.common.settings.AbstractScopedSettings$2.apply(AbstractScopedSettings.java:326)
        at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:627)
        at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater$$Lambda$3229/0x0000000801753d60.run(Unknown Source)
        at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:193)
        - locked <0x00007fc58b5c5f30> (a org.elasticsearch.common.settings.ClusterSettings)
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:466)
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418)
        at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:68)
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:162)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:684)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@15.0.1/ThreadPoolExecutor.java:1130)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@15.0.1/ThreadPoolExecutor.java:630)
        at java.lang.Thread.run(java.base@15.0.1/Thread.java:832)
```

the related the log is as follow:
```
[2023-06-06T07:25:21,664][DEBUG][o.e.c.c.PublicationTransportHandler] [data0] received full cluster state version [2643818] with size [2199150]
[2023-06-06T07:25:21,666][DEBUG][o.e.c.c.Coordinator      ] [data0] handlePublishRequest: coordinator becoming FOLLOWER of [{es-master-ith17x5iwky9i9am-0}{eUjPI4KKTGCTAG6QubjM3g}{0V0TUH8NS3eQezmZFKjm5g}{172.24.70.226}{172.24.70.226:9300}{imr}{data_node=master}] in term 118 (was CANDIDATE, lastKnownLeader was [Optional.empty])
[2023-06-06T07:25:21,689][DEBUG][o.e.c.s.ClusterApplierService] [data0] processing [ApplyCommitRequest{term=118, version=2643818, sourceNode={es-master-ith17x5iwky9i9am-0}{eUjPI4KKTGCTAG6QubjM3g}{0V0TUH8NS3eQezmZFKjm5g}{172.24.70.226}{172.24.70.226:9300}{imr}{data_node=master}}]: execute
[2023-06-06T07:25:21,691][DEBUG][o.e.c.s.ClusterApplierService] [data0] cluster state updated, version [2643818], source [ApplyCommitRequest{term=118, version=2643818, sourceNode={es-master-ith17x5iwky9i9am-0}{eUjPI4KKTGCTAG6QubjM3g}{0V0TUH8NS3eQezmZFKjm5g}{172.24.70.226}{172.24.70.226:9300}{imr}{data_node=master}}]
[2023-06-06T07:25:21,693][INFO ][o.e.c.s.ClusterApplierService] [data0] master node changed {previous [], current [{es-master-ith17x5iwky9i9am-0}{eUjPI4KKTGCTAG6QubjM3g}{0V0TUH8NS3eQezmZFKjm5g}{172.24.70.226}{172.24.70.226:9300}{imr}{data_node=master}]}, added {{es-master-ith17x5iwky9i9am-0}{eUjPI4KKTGCTAG6QubjM3g}{0V0TUH8NS3eQezmZFKjm5g}{172.24.70.226}{172.24.70.226:9300}{imr}{data_node=master},{es-master-ith17x5iwky9i9am-2}{TjTqqe5VS9G-D2XXbq4A1w}{hzLZnAaSRQyrd4jWLuw2vg}{172.19.120.103}{172.19.120.103:9300}{imr}{data_node=master},{es-data-ith17x5iwky9i9am-4}{KGr3nbpMTouGRp8UeUFFqQ}{9qUT47sFTEev4uqG47GE7g}{172.19.149.62}{172.19.149.62:9300}{dir}{data_node=hot},{es-master-ith17x5iwky9i9am-1}{QIlaC9VkTeKAr-ezekbCsw}{tTPydcqQToWfZRp7CphMHQ}{172.29.103.63}{172.29.103.63:9300}{imr}{data_node=master},{es-data-ith17x5iwky9i9am-1}{MvUONrMhT0q9mURbJMyyLA}{8TfnB5G1SKu4p87tMaEeRg}{172.29.103.64}{172.29.103.64:9300}{dir}{data_node=hot},{es-data-ith17x5iwky9i9am-3}{MsgCwRoQSLijqhCeouYI9Q}{eWIBx3uBTFiBkD-nfkiZjA}{172.23.119.192}{172.23.119.192:9300}{dir}{data_node=hot},{es-data-ith17x5iwky9i9am-5}{lIlPN12eSNS64CWJPjwVeA}{lnRCt5DWTpKroAcAoKjTyw}{172.26.13.99}{172.26.13.99:9300}{dir}{data_node=hot},{es-data-ith17x5iwky9i9am-6}{keu3oi4cT1WvY4cdI6Vt5Q}{QQA_FeABQpuJOzqdO_xkUQ}{172.19.124.80}{172.19.124.80:9300}{dir}{data_node=hot},{es-data-ith17x5iwky9i9am-2}{8yYzycxUQbmBWiF5pn-zxg}{drmhwzadQ0uU18sOC1Gmdw}{172.19.120.104}{172.19.120.104:9300}{dir}{data_node=hot}}, term: 118, version: 2643818, reason: ApplyCommitRequest{term=118, version=2643818, sourceNode={es-master-ith17x5iwky9i9am-0}{eUjPI4KKTGCTAG6QubjM3g}{0V0TUH8NS3eQezmZFKjm5g}{172.24.70.226}{172.24.70.226:9300}{imr}{data_node=master}}
[2023-06-06T07:25:21,697][DEBUG][o.e.c.NodeConnectionsService] [data0] connecting to {es-master-ith17x5iwky9i9am-2}{TjTqqe5VS9G-D2XXbq4A1w}{hzLZnAaSRQyrd4jWLuw2vg}{172.19.120.103}{172.19.120.103:9300}{imr}{data_node=master}
[2023-06-06T07:25:21,699][DEBUG][c.a.o.s.s.t.OpenDistroSecuritySSLNettyTransport] [data0] Connection to 172.19.120.103 needs to be ssl, adding ssl handler to the client channel
[2023-06-06T07:25:21,699][DEBUG][c.a.o.s.s.t.OpenDistroSecuritySSLNettyTransport] [data0] Connection to 172.19.120.103 needs to be ssl, adding ssl handler to the client channel
[2023-06-06T07:25:21,700][DEBUG][c.a.o.s.s.t.OpenDistroSecuritySSLNettyTransport] [data0] Connection to 172.19.120.103 needs to be ssl, adding ssl handler to the client channel
[2023-06-06T07:25:21,700][DEBUG][c.a.o.s.s.t.OpenDistroSecuritySSLNettyTransport] [data0] Connection to 172.19.120.103 needs to be ssl, adding ssl handler to the client channel
......
[2023-06-06T07:25:48,697][DEBUG][o.e.a.s.m.TransportMasterNodeAction] [data0] no known master node, scheduling a retry
```

Failed to connect remote cluster:
```
[2023-06-06T07:26:35,242][WARN ][o.e.t.RemoteClusterService] [data0] failed to connect to new remote cluster remote1 within 10s
[2023-06-06T07:26:45,242][WARN ][o.e.t.RemoteClusterService] [data0] failed to connect to new remote cluster remote2 within 10s
[2023-06-06T07:26:55,243][WARN ][o.e.t.RemoteClusterService] [data0] failed to connect to new remote cluster remote3 within 10s
```

The reason why data0 fails to join the cluster(`ClusterApplierService.applyChanges`):
1.data0 restarts and receives the new ClusterState.
2.data0 starts to connect the remote cluster, but failed to build remote connection mapped to it self. because it will send request to the master.
https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/transport/SniffConnectionStrategy.java#L330
but the master will be null by local ClusterState, because the new ClusterState is not set(it will be set later), so the request will be blocked.

That means, here is a deadlock, the connecting remote node depends on settings new ClusterState, but settings new ClusterState is blocked by the the connecting remote node.

So every connecting remote cluster(point to the local ip) will timeout 10s)(see above), if we have ten more than the same remote cluster, it will cost 100s, which means it will be removed from the cluster by the master.

There are two problems when applying the new ClusterState:
1.the connection of remote cluster (point to the local ip) will cost 10s(timeout)
2.the process of connection of remote cluster is included in the process of applying the new ClusterState, if there are thousands of  remote cluster, it may costs much time and be removed by the master.

Solution:
If we should handle this remote connection asynchronously？

**Comment by DaveCTurner** [comment]
I think this is still an issue in latest `main`. I've labelled it for the attention of the security team because they have been doing a bunch of work on remote cluster connections recently, but I could believe this lands on the distrib or core teams too.

**Comment by kkewwei** [comment]
If possible, I'm please to be a part of solving the case.

**Comment by ywangd** [comment]
I observed similar behaviour in 7.17 so I don't think it is related to the recent changes to remote cluster connections. The cluster does recover at the end once the node has gone through and timed out on all remote clusters. But it will be a very long process if there are thousands of them.

**Comment by DaveCTurner** [comment]
++ I don't think it's _related_ to those changes, it's been like this for ages.
