### ISSUE TITLE
`fields` API fails to retrieve subfields of objects with `subobjects: false`

### ISSUE THREAD

**Issue by eyalkoren** [elastic/elasticsearch#96700]
### Elasticsearch Version

8.9.0

### Java Version

_bundled_

### OS Version

macOS

### Problem Description

When setting `subobjects: false`, the `fields` API fails to retrieve subfields.
The `_source` contains the correct subfield value, but the retrieved field gets the parent field's value.

### Steps to Reproduce

Run this test through the yaml test framework:
```yml
  - do:
      indices.create:
        index: test_index
        body:
          mappings:
            subobjects: false

  - do:
      index:
        index: test_index
        refresh: true
        body: >
          {
            "root": "parent",
            "root.subfield": "child"
          }
  - match: {result: "created"}

  - do:
      search:
        index: test_index
        body:
          query:
            term:
              root:
                value: 'parent'
          fields:
            - field: 'root'
            - field: 'root.subfield'
  - match: { hits.hits.0.fields.root.0: 'parent' }
  - match: { hits.hits.0.fields.root\.subfield.0: 'child' }
```

See full failure below.

### Logs

```
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 28,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 1,
  1>         "successful" : 1,
  1>         "skipped" : 0,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : {
  1>           "value" : 1,
  1>           "relation" : "eq"
  1>         },
  1>         "max_score" : 0.2876821,
  1>         "hits" : [
  1>           {
  1>             "_index" : "test_index",
  1>             "_id" : "8acBm4gBiDGez0EIgdKq",
  1>             "_score" : 0.2876821,
  1>             "_source" : {
  1>               "root.subfield" : "child",
  1>               "root" : "parent"
  1>             },
  1>             "fields" : {
  1>               "root.subfield" : [
  1>                 "parent"
  1>               ],
  1>               "root" : [
  1>                 "parent"
  1>               ]
  1>             }
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
...
    Expected: "child"
         but: was "parent"
        at __randomizedtesting.SeedInfo.seed([A0FAA2C731FB678B:28AE9D1D9F070A73]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:572)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.elasticsearch.test.cluster.DefaultElasticsearchCluster$1.evaluate(DefaultElasticsearchCluster.java:36)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1623)

        Caused by:
        java.lang.AssertionError:
        Expected: "child"
             but: was "parent"
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.junit.Assert.assertThat(Assert.java:956)
            at org.junit.Assert.assertThat(Assert.java:923)
            at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:99)
            at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:552)
            ... 38 more
```

**Comment by eyalkoren** [comment]
The culprit may be related to a [multi-field handling for source-path resolution during fields values fetch](https://github.com/elastic/elasticsearch/blob/afbf1f5ca182f4fb960efe4826dc633962aaca0b/server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java#L196-L203)- if the algorithm finds a mapping type for both `parent` and `parent.subfield`, it assumes that this is a result of multi-field mapping, so it returns `parent` as the source path for both. However, when setting `subobjects: false`, it is possible to get `parent` and `parent.subfield` are two real distinct fields, non-related to multi-field mapping, in which case the correct source path for `parent.subfield` is actually `parent.subfield`.
