### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=indices.stats/13_fields/Fielddata fields - all metric} failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#96711]
**Build scan:**
https://gradle-enterprise.elastic.co/s/zlgx2yuikqnp6/tests/:qa:mixed-cluster:v8.4.0%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=indices.stats%2F13_fields%2FFielddata%20fields%20-%20all%20metric%7D

**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v8.4.0#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.stats/13_fields/Fielddata fields - all metric}" -Dtests.seed=F8C1BF871B7A72B7 -Dtests.bwc=true -Dtests.locale=tr -Dtests.timezone=Asia/Hong_Kong -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dindices.stats/13_fields/Fielddata%20fields%20-%20all%20metric%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [indices.stats/13_fields:232]: value of [_all.total.fielddata.fields.bar.memory_size_in_bytes] is not comparable (got [null])
Expected: an instance of java.lang.Comparable
     but: null

  at __randomizedtesting.SeedInfo.seed([F8C1BF871B7A72B7:7095805DB5861F4F]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:572)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.lang.AssertionError: value of [_all.total.fielddata.fields.bar.memory_size_in_bytes] is not comparable (got [null])
  Expected: an instance of java.lang.Comparable
       but: null

    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.elasticsearch.test.rest.yaml.section.GreaterThanAssertion.doAssert(GreaterThanAssertion.java:50)
    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:552)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by masseyke** [comment]
The fielddata fields are definitely not in the result. For example we get:
```
            "fielddata" : {
              "memory_size_in_bytes" : 0,
              "evictions" : 0,
              "fields" : { },
              "global_ordinals" : {
                "build_time_in_millis" : 0
              }
            },
```
instead of something more like:
```
          "fielddata" : {
            "memory_size_in_bytes" : 584,
            "evictions" : 0,
            "fields" : {
              "bar" : {
                "memory_size_in_bytes" : 292
              }
            },
            "global_ordinals" : {
              "build_time_in_millis" : 0
            }
          },
```
So far I haven't been able to reproduce it though.

**Comment by masseyke** [comment]
Also, I don't see it in the gradle history from June 1, 2022 through April 2, 2023. But I see it 7 times from April 3 to now.

**Comment by bpintea** [comment]
One more similar failure https://gradle-enterprise.elastic.co/s/y7rbb75mfijvy

**Comment by kingherc** [comment]
Another one at [elasticsearch / periodic / main / openjdk17 / bwcTestSnapshots / java-fips-matrix](https://gradle-enterprise.elastic.co/s/loyijho4swg4w)

**Comment by gmarouli** [comment]
Every test case firsts asserts there are no shards failures, which makes sense, if a shard does not respond then we are probably missing stats. What I find weird in this test response is the following:
```
      "_shards" : {	
        "total" : 4,	
        "successful" : 3,	
        "failed" : 0	
      }
```
So, there 4 total shards but only 3 were successful. I am following up to see when does this happen.

**Comment by gmarouli** [comment]
When running it locally I often get the difference between the successful number of shards and the total, so probably it's not related.

**Comment by gmarouli** [comment]
Another (potentially irrelevant) observation:

These failures happen on bwc tests with versions before `8.5`:

<img width="1649" alt="Screenshot 2024-03-29 at 14 34 55" src="https://github.com/elastic/elasticsearch/assets/4698234/7e9b6ff8-14f2-48ad-92a0-0cca97281183">

So potentially, another idea is to look if something was "fixed" then.

**Comment by gmarouli** [comment]
I have found nothing useful in the logs so far, apart from cluster instability in https://gradle-enterprise.elastic.co/s/loyijho4swg4w/tests/task/:qa:mixed-cluster:v7.17.19%23mixedClusterTest/details/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0%3Dindices.stats%2F13_fields%2FFielddata%20fields%20-%20pattern%7D?top-execution=1.

It appears during this test only the master node was available but this did not change during the test but much earlier. On the other hand, during this test it manages to allocate 3 shards, which is confusing since there is only one node available.

**Comment by davidkyle** [comment]
Another https://gradle-enterprise.elastic.co/s/kff7ghrhytk6y/tests/task/:qa:mixed-cluster:v7.17.23%23mixedClusterTest/details/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=indices.stats%2F13_fields%2FFields%20-%20multi%20metric%7D?top-execution=1

**Comment by nielsbauman** [comment]
I had a look at this test failure and #118217. I think @gmarouli's observation in https://github.com/elastic/elasticsearch/issues/96711#issuecomment-2027161715 is what is causing both of these test failures, as all the test failures (from both issues) I examined showed this mismatch in returning shards. This mismatch in shards might occur more often (as Mary noted in https://github.com/elastic/elasticsearch/issues/96711#issuecomment-2027168835), but my suspicion is that this test only fails when the unavailable shard is the only shard that has the relevant document, and there is no issue if any other shard is unavailable.

Therefore, my conclusion is that we should reduce the number of shards to just 1 shard per index (1 primary, 0 replicas) so that we can wait for the health _and_ `wait_for_no_relocating_shards: true` right before we do the assertion. Technically, that still leaves space/time for the balancer to move shards arround between the health check and the test, but it should be greatly reduced as there is very little/no activity in the cluster.
