### ISSUE TITLE
[Transform] possible NPE in transform preview if data is empty

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#96781]
If data is missing the composite aggregation might be `null` and transform preview fails with an NPE:

```
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": """Cannot invoke "org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregation.getBuckets()" because "agg" is null""",
        "stack_trace": """org.elasticsearch.ElasticsearchException$1: Cannot invoke "org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregation.getBuckets()" because "agg" is null
	at org.elasticsearch.server@8.7.1/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:668)
```

caused by:

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregation.getBuckets()" because "agg" is null
	at org.elasticsearch.xpack.transform.transforms.pivot.AggregationResultUtils.extractCompositeAggregationResults(AggregationResultUtils.java:111)
	at org.elasticsearch.xpack.transform.transforms.pivot.Pivot.extractResults(Pivot.java:142)
	at org.elasticsearch.xpack.transform.transforms.common.AbstractCompositeAggFunction.lambda$preview$0(AbstractCompositeAggFunction.java:94)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:167)
```

## Fix:

Handle `null` at:

https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/common/AbstractCompositeAggFunction.java#L90

**Comment by AjeetNathawat** [comment]
hi @hendrikmuhs I have created a PR for this issue, since this looks like a straightforward null check here is the PR: https://github.com/elastic/elasticsearch/pull/96785
