### ISSUE TITLE
[CI] GeoLineAggregatorTests testGeoLine_TSDB_simplified failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#96909]
**Build scan:**
https://gradle-enterprise.elastic.co/s/rulj5uiotvqrm/tests/:x-pack:plugin:spatial:test/org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests/testGeoLine_TSDB_simplified

**Reproduction line:**
```
./gradlew ':x-pack:plugin:spatial:test' --tests "org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.testGeoLine_TSDB_simplified" -Dtests.seed=D11AF5F8AA7F05DC -Dtests.locale=tr-TR -Dtests.timezone=America/Indiana/Marengo -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests&tests.test=testGeoLine_TSDB_simplified

**Failure excerpt:**
```
java.lang.AssertionError: GeoLine[sort=asc, use-timestamps=false] is complete
Expected: is <false>
     but: was <true>

  at __randomizedtesting.SeedInfo.seed([D11AF5F8AA7F05DC:289440E199ADD4C]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.assertGeoLine(GeoLineAggregatorTests.java:435)
  at org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.lambda$testGeoLine_TSDB_simplified$27(GeoLineAggregatorTests.java:401)
  at org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.lambda$assertGeoLine_TSDB$31(GeoLineAggregatorTests.java:825)
  at org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.testCase(GeoLineAggregatorTests.java:962)
  at org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.assertGeoLine_TSDB(GeoLineAggregatorTests.java:797)
  at org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.testGeoLine_TSDB_simplified(GeoLineAggregatorTests.java:396)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by craigtaverner** [comment]
The error description `GeoLine[sort=asc, use-timestamps=false] is complete: expected false but is true` means this test is checking the old algorithm (time time-series is not used when use-timestamps is false), and passing in more data than the size limit, so should be truncated, but is not. I'll test locally and see what is going on. I know not all documents have data, but the fraction that has data is deterministic, so should not cause this.
