### ISSUE TITLE
[CI] InternalTDigestPercentilesRanksTests testConcurrentEquals failing

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#96973]
**Build scan:**
https://gradle-enterprise.elastic.co/s/rl6qnn6z24wbs/tests/:server:test/org.elasticsearch.search.aggregations.metrics.InternalTDigestPercentilesRanksTests/testConcurrentEquals

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.InternalTDigestPercentilesRanksTests.testConcurrentEquals" -Dtests.seed=736C42A7C5819486 -Dtests.locale=es-NI -Dtests.timezone=America/Dominica -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.metrics.InternalTDigestPercentilesRanksTests&tests.test=testConcurrentEquals

**Failure excerpt:**
```
java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException

  at __randomizedtesting.SeedInfo.seed([736C42A7C5819486:1817296FE9F76CA]:0)
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:191)
  at org.elasticsearch.test.AbstractWireTestCase.concurrentTest(AbstractWireTestCase.java:98)
  at org.elasticsearch.test.AbstractWireTestCase.testConcurrentEquals(AbstractWireTestCase.java:78)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.util.ConcurrentModificationException: (No message provided)

    at java.util.ArrayList.sort(ArrayList.java:1723)
    at java.util.Collections.sort(Collections.java:145)
    at org.elasticsearch.tdigest.SortingDigest.compress(SortingDigest.java:71)
    at org.elasticsearch.tdigest.SortingDigest.centroids(SortingDigest.java:95)
    at org.elasticsearch.tdigest.SortingDigest.centroidCount(SortingDigest.java:136)
    at org.elasticsearch.tdigest.HybridDigest.centroidCount(HybridDigest.java:167)
    at org.elasticsearch.search.aggregations.metrics.TDigestState.centroidCount(TDigestState.java:251)
    at org.elasticsearch.search.aggregations.metrics.TDigestState.equals(TDigestState.java:169)
    at java.util.Objects.equals(Objects.java:64)
    at org.elasticsearch.search.aggregations.metrics.AbstractInternalTDigestPercentiles.equals(AbstractInternalTDigestPercentiles.java:224)
    at org.elasticsearch.search.aggregations.metrics.InternalTDigestPercentileRanks.equals(InternalTDigestPercentileRanks.java:18)
    at org.junit.Assert.isEquals(Assert.java:131)
    at org.junit.Assert.equalsRegardingNull(Assert.java:127)
    at org.junit.Assert.assertEquals(Assert.java:111)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at org.elasticsearch.test.AbstractWireTestCase.lambda$testConcurrentEquals$0(AbstractWireTestCase.java:80)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
    at java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by salvatore-campagna** [comment]
Duplicate of #96961
