### ISSUE TITLE
Index Recovery Failed after upgrade to 1.4.3

### ISSUE THREAD

**Issue by HenrikOssipoff** [elastic/elasticsearch#9704]
Today we attempted to do an upgrade of our Elasticsearch cluster from 1.3.0 to 1.4.3. After having upgraded the first node, it joins the cluster just fine, but we cannot get it to initialize shards. Our logs are spammed with the following error per index:

```bash
org.elasticsearch.indices.recovery.RecoveryFailedException: [pim_v3][0]: Recovery failed from [elasticsearch02][K5GW34H-TMO8_sMIB5P77g][elasticsearch02][inet[/172.31.7.56:9300]] into [elasticsearch01][nSy51hptRKSMMQqhPPvGVg][elasticsearch01][inet[172.31.7.55/172.31.7.55:9300]]
        at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:308)
        at org.elasticsearch.indices.recovery.RecoveryTarget.access$200(RecoveryTarget.java:65)
        at org.elasticsearch.indices.recovery.RecoveryTarget$2.run(RecoveryTarget.java:177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.transport.RemoteTransportException: [elasticsearch02][inet[/172.31.7.56:9300]][index/shard/recovery/startRecovery]
Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.lucene.util.Version.4.9.0
        at java.lang.Enum.valueOf(Enum.java:236)
        at org.apache.lucene.util.Version.valueOf(Version.java:32)
        at org.apache.lucene.util.Version.parseLeniently(Version.java:250)
        at org.elasticsearch.index.store.StoreFileMetaData.readFrom(StoreFileMetaData.java:105)
        at org.elasticsearch.index.store.StoreFileMetaData.readStoreFileMetaData(StoreFileMetaData.java:89)
        at org.elasticsearch.indices.recovery.StartRecoveryRequest.readFrom(StartRecoveryRequest.java:115)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:214)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:111)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[2015-02-15 13:21:10,115][WARN ][cluster.action.shard     ] [elasticsearch01] [pim_v3][0] sending failed shard for [pim_v3][0], node[nSy51hptRKSMMQqhPPvGVg], [R], s[INITIALIZING], indexUUID [67HPMYJ7RmeVQ-_rHyIBTQ], reason [Failed to start shard, message [RecoveryFailedException[[pim_v3][0]: Recovery failed from [elasticsearch02][K5GW34H-TMO8_sMIB5P77g][elasticsearch02][inet[/172.31.7.56:9300]] into [elasticsearch01][nSy51hptRKSMMQqhPPvGVg][elasticsearch01][inet[172.31.7.55/172.31.7.55:9300]]]; nested: RemoteTransportException[[elasticsearch02][inet[/172.31.7.56:9300]][index/shard/recovery/startRecovery]]; nested: IllegalArgumentException[No enum constant org.apache.lucene.util.Version.4.9.0]; ]]
```

The node remains unable to have any shards allocated.

**Comment by bleskes** [comment]
Thx for reporting this. This issue results from a change in the way we serialize and parse lucene versions  ( changed inhttps://github.com/elasticsearch/elasticsearch/pull/7584/files#diff-6debabcebb4a810f1be417d16c41c115R140 ). The change is compatible with ES 1.3.1 since the parsing there was improved due to another issue ( https://github.com/elasticsearch/elasticsearch/pull/7055 ). 

At the moment, I can only think of 2  solutions:

- you can ignore these errors and continue the upgrade. The shards will be allocated as soon as the primary is assigned to a 1.4.2 (once all nodes with current copies have been upgraded). The down side is that your indices will be temporally red (indexing may stall, and searches will return partial data in that time)
- do a rolling upgrade to 1.3.8, where this is not an issue and from there upgrade to 1.4.3 .

**Comment by HenrikOssipoff** [comment]
Thank you for getting back to me on this.

We will attempt to do a rolling upgrade (or rather, downgrade I guess) of 1.3.8 on all nodes, and from there do an upgrade to 1.4.3.

While I know this is very conditional of which version you are running, this should likely be marked as a breaking change in the appropriate version -- in case someone else tries to do an upgrade from 1.3.0 to 1.4.3.

**Comment by bleskes** [comment]
@HenrikOssipoff yeah, I agree it's tricky. This is why I left it open for further thought. 

Note that if you have successfully indexed any document into a shard created on the 1.4.2 node you will not be able to downgrade it. You can close it and reopen once the whole procedure is compleeted. This can only happen an index was created while the 1.4.2 was in the cluster.

**Comment by jpountz** [comment]
Closing as 1.4.0 is getting old now and this issue has not been addressed yet. Note that if you hit this issue, a work-around is to do a rolling upgrade to 1.3.8 first as documented above.
