### ISSUE TITLE
[CI] ml/inference_rescore/Test rescore with stored model and chained rescorers failed

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#97182]
### CI Link

https://gradle-enterprise.elastic.co/s/2s6vsrzztb46s/console-log?task=:x-pack:plugin:yamlRestTest

### Repro line

./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/inference_rescore/Test rescore with stored model and chained rescorers}" -Dtests.seed=390EFD717D965AF4 -Dtests.locale=de -Dtests.timezone=Europe/Andorra -Druntime.java=20

### Does it reproduce?

No

### Applicable branches

main (from a PR)

### Failure history

https://ci-stats.elastic.co/s/jenkins/goto/f75ca960-15ab-11ee-9600-7bc775af4222

### Failure excerpt

```
org.elasticsearch.xpack.test.rest.XPackRestIT > test {p0=ml/inference_rescore/Test rescore with stored model and chained rescorers} FAILED |  
-- | --
  | org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:33691], URI [/_ml/trained_models/_stats?size=10000], status line [HTTP/1.1 500 Internal Server Error] |  
  | {"error":{"root_cause":[],"type":"exception","reason":"Searching for stats for models [lang_ident_model_1,ltr-model] failed","caused_by":{"type":"search_phase_execution_exception","reason":"","phase":"query","grouped":true,"failed_shards":[],"caused_by":{"type":"search_phase_execution_exception","reason":"Search rejected due to missing shards [[.ml-stats-000001][0]]. Consider using `allow_partial_search_results` setting to bypass this error.","phase":"query","grouped":true,"failed_shards":[]}}},"status":500} |  
  | at __randomizedtesting.SeedInfo.seed([390EFD717D965AF4:B15AC2ABD36A370C]:0) |  
  | at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347) |  
  | at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:313) |  
  | at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) |  
  | at app//org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.deleteAllTrainedModelIngestPipelines(MlRestTestStateCleaner.java:42) |  
  | at app//org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.resetFeatures(MlRestTestStateCleaner.java:33) |  
  | at app//org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.clearMlState(AbstractXPackRestTest.java:133) |  
  | at app//org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.cleanup(AbstractXPackRestTest.java:117)

org.elasticsearch.xpack.test.rest.XPackRestIT > test {p0=ml/inference_rescore/Test rescore with stored model and chained rescorers} FAILED	
    org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:33691/], URI [/_ml/trained_models/_stats?size=10000], status line [HTTP/1.1 500 Internal Server Error]	
    {"error":{"root_cause":[],"type":"exception","reason":"Searching for stats for models [lang_ident_model_1,ltr-model] failed","caused_by":{"type":"search_phase_execution_exception","reason":"","phase":"query","grouped":true,"failed_shards":[],"caused_by":{"type":"search_phase_execution_exception","reason":"Search rejected due to missing shards [[.ml-stats-000001][0]]. Consider using `allow_partial_search_results` setting to bypass this error.","phase":"query","grouped":true,"failed_shards":[]}}},"status":500}	
        at __randomizedtesting.SeedInfo.seed([390EFD717D965AF4:B15AC2ABD36A370C]:0)	
        at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)	
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)	
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)	
        at app//org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.deleteAllTrainedModelIngestPipelines(MlRestTestStateCleaner.java:42)	
        at app//org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.resetFeatures(MlRestTestStateCleaner.java:33)	
        at app//org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.clearMlState(AbstractXPackRestTest.java:133)	
        at app//org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.cleanup(AbstractXPackRestTest.java:117)
```

**Comment by maxhniebergall** [comment]
https://github.com/elastic/elasticsearch/pull/108202
