### ISSUE TITLE
[CI] TextExpansionQueryIT testSearchWithMissingModel failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#97245]
Many tests failed with the same error, but the first one was `testSearchWithMissingModel`, so presumably if any single test is responsible for causing these recovery tasks to linger it's that one. That test hasn't been modified since March.

**Build scan:**
https://gradle-enterprise.elastic.co/s/6dhljzr55ppxs/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.TextExpansionQueryIT/testSearchWithMissingModel

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.TextExpansionQueryIT.testSearchWithMissingModel" -Dtests.seed=4C373A6E503FD58D -Dtests.locale=sr-ME -Dtests.timezone=BET -Druntime.java=20
```

**Applicable branches:**
8.9

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.TextExpansionQueryIT&tests.test=testSearchWithMissingModel

**Failure excerpt:**
```
java.lang.AssertionError: 3 active tasks found:
internal:index/shard/recovery/start_recovery At-hs4rwTxeh3N8lcb21Eg:59240  -                            transport  1688005283461 02:21:23 3.8m        127.0.0.1 javaRestTest-0 recovery of [test-model-memory-limit][5] to {javaRestTest-2}{elR80oPZSbiOWi4v0-rtPw}{6k_gGKEVR_mRpXb9xX4bVA}{javaRestTest-2}{127.0.0.1}{127.0.0.1:35557}{dilm}{8.9.0} [recoveryId=624, targetAllocationId=jZ9eregIRN-R3ESrviNgNA, startingSeqNo=-2, primaryRelocation=false, canDownloadSnapshotFiles=true]
internal:index/shard/recovery/start_recovery elR80oPZSbiOWi4v0-rtPw:71769  -                            transport  1688005283462 02:21:23 3.8m        127.0.0.1 javaRestTest-2 recovery of [test-model-memory-limit][3] to {javaRestTest-0}{At-hs4rwTxeh3N8lcb21Eg}{eNMb9dmhQfiuj_p4EDdq2w}{javaRestTest-0}{127.0.0.1}{127.0.0.1:32915}{dim}{8.9.0} [recoveryId=558, targetAllocationId=F0NBThr9TDO9iAT1IHU-5g, startingSeqNo=-2, primaryRelocation=false, canDownloadSnapshotFiles=true]
internal:index/shard/recovery/start_recovery elR80oPZSbiOWi4v0-rtPw:71775  -                            transport  1688005283470 02:21:23 3.8m        127.0.0.1 javaRestTest-2 recovery of [test-model-memory-limit][6] to {javaRestTest-1}{oaS5tiGqQaCBdx_sthr1_w}{zKm-bS5cSH2e_MYG_KRuSQ}{javaRestTest-1}{127.0.0.1}{127.0.0.1:33105}{dilm}{8.9.0} [recoveryId=540, targetAllocationId=87IdPEZjT32RbRZTY3Hmgw, startingSeqNo=-2, primaryRelocation=false, canDownloadSnapshotFiles=true]
 expected:<0> but was:<3>

  at __randomizedtesting.SeedInfo.seed([4C373A6E503FD58D:424290DD7772D0DE]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:645)
  at org.elasticsearch.test.rest.ESRestTestCase.lambda$waitForPendingTasks$2(ESRestTestCase.java:490)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1172)
  at org.elasticsearch.test.rest.ESRestTestCase.waitForPendingTasks(ESRestTestCase.java:461)
  at org.elasticsearch.test.rest.ESRestTestCase.waitForPendingTasks(ESRestTestCase.java:447)
  at org.elasticsearch.xpack.ml.integration.PyTorchModelRestTestCase.cleanup(PyTorchModelRestTestCase.java:86)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by droberts195** [comment]
Same failure in a different test in https://gradle-enterprise.elastic.co/s/zxoaf76pfmsr6:

```
java.lang.AssertionError: 1 active tasks found:	
internal:index/shard/recovery/start_recovery Pwe7mpjBTWWbPJf_8GVRqQ:66203  -                            transport  1689120405007 00:06:45 6.8m        127.0.0.1 javaRestTest-0 recovery of [test-stop-outlier-detection-with-enough-docs-to-scroll][0] to {javaRestTest-1}{SbZHeWm_RqCJwifklQ_EAg}{cVRw1GtuTsuh7H1t_Xb-SQ}{javaRestTest-1}{127.0.0.1}{127.0.0.1:33595}{dilm}{8.10.0}{7000099-8100099} [recoveryId=627, targetAllocationId=8-FOv-zxSkO-xlhwCz5UzQ, startingSeqNo=-2, primaryRelocation=false, canDownloadSnapshotFiles=true]	
 expected:<0> but was:<1>
```

**Comment by luigidellaquila** [comment]
More failures on this class. Not sure it's the same thing, but they seem very similar

https://gradle-enterprise.elastic.co/s/bbyncd6wtbqie/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.DatafeedJobsRestIT/testLookbackWithoutPermissions?top-execution=1

**Comment by droberts195** [comment]
Long-running `start_recovery` tasks were seen again today in https://gradle-enterprise.elastic.co/s/e3zjigozbae3y/tests/task/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/details/org.elasticsearch.xpack.ml.integration.PyTorchModelIT/testStartMultipleLowPriorityDeployments?top-execution=1

These `start_recovery` tasks are not part of ML.

This has been superseded by #100589.
