### ISSUE TITLE
[CI] WindowsServiceTests test10InstallArchive failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#97264]
It's on Windows. The underlying error is 

```
[2023-06-30T04:38:49,190][INFO ][o.e.p.u.Shell            ] [TEST-WindowsServiceTests.test10InstallArchive-seed#[A3B96D2CF27A68C3]-workerest_thread_info] Ran: [powershell.exe, -Command, null remove] exitCode = [1] stdout = [] stderr = [null : The term 'null' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ null remove
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (null:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException]
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/r2d35fmdqbepg/tests/:qa:os:destructiveDistroTest.default-windows-archive/org.elasticsearch.packaging.test.WindowsServiceTests/test10InstallArchive

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.WindowsServiceTests&tests.test=test10InstallArchive

**Failure excerpt:**
```
java.lang.RuntimeException: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch-8.10.0-SNAPSHOT -> C:\tmp\elasticsearch

  at __randomizedtesting.SeedInfo.seed([A3B96D2CF27A68C3:4191219B21A3E630]:0)
  at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:136)
  at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:100)
  at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:55)
  at org.elasticsearch.packaging.test.WindowsServiceTests.test10InstallArchive(WindowsServiceTests.java:101)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch-8.10.0-SNAPSHOT -> C:\tmp\elasticsearch

    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:414)
    at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
    at java.nio.file.Files.move(Files.java:1429)
    at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:134)
    at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:100)
    at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:55)
    at org.elasticsearch.packaging.test.WindowsServiceTests.test10InstallArchive(WindowsServiceTests.java:101)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by rjernst** [comment]
This looks like a dup of https://github.com/elastic/elasticsearch/issues/96343. We occasionally have failures while trying to rename the installation we just unzipped. We've tried disabling windows Defender, under the theory it was reading the directory while the test was running, but that doesn't seem to have helped. I'm going to close this in favor of #96343.
