### ISSUE TITLE
[CI] RejectionActionIT testSimulatedSearchRejectionLoad failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#97291]
Also seen more recently in an unrelated PR branch: https://gradle-enterprise.elastic.co/s/wyty535kiytps

Unclear why this apparently-idle threadpool should be rejecting things.

**Build scan:**
https://gradle-enterprise.elastic.co/s/mkdoarby2pepg/tests/:server:internalClusterTest/org.elasticsearch.action.RejectionActionIT/testSimulatedSearchRejectionLoad

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.RejectionActionIT.testSimulatedSearchRejectionLoad" -Dtests.seed=736E2230D0CFC275 -Dtests.locale=es-CU -Dtests.timezone=Europe/Belfast -Druntime.java=18
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.RejectionActionIT&tests.test=testSimulatedSearchRejectionLoad

**Failure excerpt:**
```
org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of org.elasticsearch.action.bulk.TransportBulkAction$1/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener/org.elasticsearch.tasks.TaskManager$1{SafelyWrappedActionListener[listener=org.elasticsearch.action.support.PlainActionFuture@259a34e6]}{Task{id=129, type='transport', action='indices:data/write/index', description='index {[test][6], source[{"field":"1"}]}', parentTask=unset, startTime=1686472827280, startTimeNanos=770550969431}}/org.elasticsearch.action.bulk.TransportBulkAction$$Lambda$3396/0x00000008014f1228@2a531174/org.elasticsearch.action.bulk.TransportBulkAction$$Lambda$3401/0x00000008014f1f60@e0ebc2 on EsThreadPoolExecutor[name = node_s1/write, queue capacity = 2, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@540a1227[Running, pool size = 1, active threads = 1, queued tasks = 2, completed tasks = 13]]

  at __randomizedtesting.SeedInfo.seed([736E2230D0CFC275:E95E7532E82FBC45]:0)
  at org.elasticsearch.common.util.concurrent.EsRejectedExecutionHandler.newRejectedException(EsRejectedExecutionHandler.java:40)
  at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:34)
  at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
  at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
  at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:72)
  at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:214)
  at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:91)
  at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:86)
  at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:61)
  at org.elasticsearch.action.bulk.TransportSingleItemBulkWriteAction.doExecute(TransportSingleItemBulkWriteAction.java:47)
  at org.elasticsearch.action.bulk.TransportSingleItemBulkWriteAction.doExecute(TransportSingleItemBulkWriteAction.java:27)
  at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:86)
  at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:61)
  at org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:199)
  at org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:112)
  at org.elasticsearch.client.internal.node.NodeClient.doExecute(NodeClient.java:90)
  at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:379)
  at org.elasticsearch.client.internal.FilterClient.doExecute(FilterClient.java:57)
  at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:379)
  at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:365)
  at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:34)
  at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:41)
  at org.elasticsearch.action.RejectionActionIT.testSimulatedSearchRejectionLoad(RejectionActionIT.java:49)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by DaveCTurner** [comment]
Perhaps this relates to #96364, we only have 1 write thread and a queue length of 2, but I think it's possible we don't quite release the executor in time to keep the queue below 2 always. Do we really need the write pool to have such a short queue? It doesn't seem to relate to the point of this test. /cc @Tim-Brooks
