### ISSUE TITLE
[CI] BulkProcessorFactoryTests testFlushDelay failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#97360]
**Build scan:**
https://gradle-enterprise.elastic.co/s/mclzwalttwijo/tests/:x-pack:plugin:ent-search:test/org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests/testFlushDelay

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ent-search:test' --tests "org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests.testFlushDelay" -Dtests.seed=BAF47521A90D626F -Dtests.locale=mk -Dtests.timezone=Europe/Kyiv -Druntime.java=20
```

**Applicable branches:**
main, 8.9

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests&tests.test=testFlushDelay

**Failure excerpt:**
```
org.mockito.exceptions.verification.WantedButNotInvoked: 
Wanted but not invoked:
client.execute(
    <any org.elasticsearch.action.bulk.BulkAction>,
    <custom argument matcher>,
    <any>
);
-> at org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests.lambda$testFlushDelay$1(BulkProcessorFactoryTests.java:65)

However, there were exactly 2 interactions with this mock:
client.settings();
-> at org.elasticsearch.client.internal.FilterClient.<init>(FilterClient.java:34)

client.threadPool();
-> at org.elasticsearch.client.internal.FilterClient.<init>(FilterClient.java:34)


  at __randomizedtesting.SeedInfo.seed([BAF47521A90D626F:CC935BD102AE17C]:0)
  at org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests.lambda$testFlushDelay$1(BulkProcessorFactoryTests.java:65)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1172)
  at org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests.testFlushDelay(BulkProcessorFactoryTests.java:65)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by davidkyle** [comment]
Another failure 

https://gradle-enterprise.elastic.co/s/hqvs5bc4r2ryw/tests/task/:x-pack:plugin:ent-search:test/details/org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests/testFlushDelay?top-execution=1

**Comment by afoucret** [comment]
In some rare case, a race condition occurs and the bulk is not added fast enough which is causing flakiness for this test.
The new version of the tests https://github.com/elastic/elasticsearch/pull/101164 fix it.
