### ISSUE TITLE
[CI] EnableSecurityOnBasicLicenseIT failures

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#97487]
**Build scan:**
https://gradle-enterprise.elastic.co/s/zfzootmw3ogj6/tests/:x-pack:plugin:security:qa:basic-enable-security:javaRestTest/org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT/testSecurityEnabledSetup

**Reproduction line:**
```
./gradlew ':x-pack:plugin:security:qa:basic-enable-security:javaRestTest' --tests "org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT.testSecurityEnabledSetup" -Dtests.seed=A2B325A5BAB8A5D7 -Dtests.locale=es-CO -Dtests.timezone=NZ -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT&tests.test=testSecurityEnabledSetup

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <2>
     but: was <1>

  at __randomizedtesting.SeedInfo.seed([A2B325A5BAB8A5D7:54BA5EE42C41ECE1]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT.checkIndexCount(EnableSecurityOnBasicLicenseIT.java:224)
  at org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT.checkSecuritySetup(EnableSecurityOnBasicLicenseIT.java:133)
  at org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT.testSecurityEnabledSetup(EnableSecurityOnBasicLicenseIT.java:116)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.DefaultElasticsearchCluster$1.evaluate(DefaultElasticsearchCluster.java:36)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by pxsalehi** [comment]
This was failing on my PR, but I checked it and it also fails on main with a slightly different assertion failure. See https://gradle-enterprise.elastic.co/s/rdyaiuf3nodfi/tests/:x-pack:plugin:security:qa:basic-enable-security:javaRestTest/org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT/testSecurityEnabledSetup?top-execution=1 which failed locally for me using `main`(402d8a77f9c).

**Comment by ywangd** [comment]
> This was failing on my PR, but I checked it and it also fails on main on a different assertion.

This test class has "ordered" test methods. Therefore running a single test method is expected to fail because it assumes certain configuration, e.g. "enabling security", from prior methods. That is the reason why running the reproduction line locally fails with a different assertion.

Running the entire test class locally with 
```
./gradlew ':x-pack:plugin:security:qa:basic-enable-security:javaRestTest' --tests "org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT" -Dtests.seed=A2B325A5BAB8A5D7 -Dtests.locale=es-CO -Dtests.timezone=NZ -Druntime.java=20
```

does not fail. I will take another look later to see why it failed with the original error.

**Comment by DaveCTurner** [comment]
Saw another one of these in https://gradle-enterprise.elastic.co/s/gq4ng3e7npkaq/tests/:x-pack:plugin:security:qa:basic-enable-security:javaRestTest/org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT/testSecurityEnabledSetup (see #100762). This looks suspicious?

```
java.lang.AssertionError: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:40271], URI [/_license], status line [HTTP/1.1 404 Not Found]
```

**Comment by DaveCTurner** [comment]
Anyway muted in 684bfa9e31c18811c54437628d7965910076a322 (see also a6b6a9434f3b5a8e28954ef307d5ea1a45861de4).

**Comment by tvernum** [comment]
The most recent failure looks like a "test cluster is slow" problem (which we've seen a few of lately).
We have
```
[2023-10-12T16:16:19,669][INFO ][o.e.g.GatewayService     ] [test-cluster-1] recovered [0] indices into cluster_state	
[2023-10-12T16:16:19,739][INFO ][o.e.t.c.l.WaitForHttpResource] [suite] Got successful response [200] from URL [http://[::1]:43015/_cluster/health?wait_for_nodes=>=2&wait_for_status=yellow]	
```

But we're still adding templates and lifecycle policies 16 seconds later
```
[2023-10-12T16:16:35,791][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [test-cluster-1] adding index lifecycle policy [.fleet-file-fromhost-meta-ilm-policy]
```

Once the test starts we wait 10s for the license to become available, but it wasn't long enough.
I can increase the timeout, but we really need to work out why it take so longer to go from "green" to actually ready.

**Comment by tvernum** [comment]
The standout log message is this:
>   1> [2023-10-12T16:16:30,845][WARN ][o.e.c.s.MasterService    ] [test-cluster-1] took [11.1s/11171ms] to compute cluster state update for [create-component-template [synthetics-mappings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@a74cba3], create-index-template [.monitoring-alerts-7], cause [api][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$7@169c3ac7], create-index-template-v2 [.monitoring-kibana-mb], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@58ff3d09], create-index-template-v2 [.monitoring-logstash-mb], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@35e170dc], create-index-template [.monitoring-logstash], cause [api][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$7@19e48c10], create-index-template [.monitoring-es], cause [api][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$7@6ed9c7e9], create-index-template-v2 [ilm-history], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@4fefa84e], create-component-template [elastic-connectors-sync-jobs-settings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@71b656ff], create-index-template [.monitoring-beats], cause [api][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$7@4c0fd0d5], create-component-template [data-streams-mappings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@6c49b032], create-index-template-v2 [.kibana-reporting], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@5ed6d82d], create-component-template [.deprecation-indexing-mappings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@1d146ca6], create-component-template [metrics-tsdb-settings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@2faf9ea9], create-component-template [elastic-connectors-settings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@ec6734e], create-index-template-v2 [.fleet-fileds-fromhost-meta], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@66b9c50b], create-component-template [elastic-connectors-sync-jobs-mappings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@5876f426], create-index-template-v2 [.watch-history-16], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@b7f7357], create-index-template-v2 [.monitoring-es-mb], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@369e2d75], create-component-template [synthetics-settings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@1e273730], create-component-template [logs-mappings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@711f3716], create-index-template-v2 [.fleet-fileds-tohost-data], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@10a17a9], create-component-template [.deprecation-indexing-settings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@46b87778], create-index-template-v2 [.slm-history], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@61814628], create-index-template-v2 [.monitoring-ent-search-mb], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@69ae6a89], create-index-template-v2 [.monitoring-beats-mb], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@38c89f4a], create-component-template [metrics-settings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@3dce2c9c], create-index-template-v2 [.fleet-fileds-tohost-meta], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@56159d0b], create-component-template [metrics-mappings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@4c754f62], create-index-template-v2 [search-acl-filter], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@303bab69], create-index-template [.monitoring-kibana], cause [api][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$7@7cdddb3e], create-index-template-v2 [.fleet-fileds-fromhost-data], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5@6dafc6b], create-component-template [ecs@dynamic_templates], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@60b2ad8d], create-component-template [behavioral_analytics-events-mappings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@dbf2211], create-component-template [elastic-connectors-mappings], cause [null][org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$3@1fa90cb3]], which exceeds the warn threshold of [5s]	

If we're losing 11 seconds of startup time pushing 1 cluster state update for the templates, then it's no wonder we can't get a license generated within 10 seconds.

**Comment by tvernum** [comment]
On my laptop, we get from cluster state recovery to license generation in < 2s
```
[2023-10-13T17:03:58,862][INFO ][o.e.g.GatewayService     ] [test-cluster-1] recovered [0] indices into cluster_state
```
```
[2023-10-13T17:04:00,502][INFO ][o.e.l.ClusterStateLicenseService] [test-cluster-1] license [09c5834b-3c58-4edb-83dd-820e5a411179] mode [basic] - valid
```

Why was the CI worked so slow?

**Comment by tvernum** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/100796 to increase the timeout for the `awaitBusy` on the basis that the slowness is unrelated to the test itself.
I don't know whether that will fix the original issue though - I'm not convinced that had the same cause.

I'll drop this from `blocker` to `low-risk` once the PR is merged and test is running again.
If we don't get any more failures over the next month or 2 we can probably close this issue.

**Comment by tvernum** [comment]
It looks like this is still failing occasionally (about 8 failures in December) but only on PR builds.
I'll leave the issue open for now, and check in again if someone posts a new failure.

**Comment by tvernum** [comment]
I'm going to close this. I spot checked a failure recent failures and in all case it was because everything was broken rather than a single failing test.
