### ISSUE TITLE
[CI]  org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT testFullClusterRestart

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#97574]
### CI Link

https://gradle-enterprise.elastic.co/s/dwx3kc4kw6eus/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testFullClusterRestart?top-execution=1

### Repro line

./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testFullClusterRestart" -Dtests.seed=DD1E8F814527A5D7 -Dtests.locale=ca -Dtests.timezone=Etc/GMT-14 -Druntime.java=20

### Does it reproduce?

Yes

### Applicable branches

8.9

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT&tests.test=testFullClusterRestart

### Failure excerpt

```
[2023-07-12T01:15:13,029][ERROR][o.e.x.c.t.IndexTemplateRegistry] [node_t1] error adding index template [.monitoring-es-mb] for [monitoring]
java.lang.IllegalArgumentException: composable template [.monitoring-es-mb] template after composition is invalid
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateIndexTemplateV2(MetadataIndexTemplateService.java:729) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.addIndexTemplateV2(MetadataIndexTemplateService.java:619) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.addIndexTemplateV2(MetadataIndexTemplateService.java:556) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5.execute(MetadataIndexTemplateService.java:501) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$1.executeTask(MetadataIndexTemplateService.java:136) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$1.executeTask(MetadataIndexTemplateService.java:133) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.SimpleBatchedExecutor.execute(SimpleBatchedExecutor.java:70) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1622) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:382) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1619) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1237) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:382) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1216) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.IllegalArgumentException: invalid composite mappings for [.monitoring-es-mb]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.lambda$validateCompositeTemplate$28(MetadataIndexTemplateService.java:1600) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:697) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateCompositeTemplate(MetadataIndexTemplateService.java:1570) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateIndexTemplateV2(MetadataIndexTemplateService.java:723) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	... 20 more
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: No handler for type [wildcard] declared on field [name]
	at org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:385) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:361) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.lambda$validateCompositeTemplate$28(MetadataIndexTemplateService.java:1593) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:697) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateCompositeTemplate(MetadataIndexTemplateService.java:1570) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateIndexTemplateV2(MetadataIndexTemplateService.java:723) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	... 20 more
Caused by: org.elasticsearch.index.mapper.MapperParsingException: No handler for type [wildcard] declared on field [name]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:313) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:235) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parse(ObjectMapper.java:200) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:325) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:235) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parse(ObjectMapper.java:200) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:325) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:235) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.RootObjectMapper.parse(RootObjectMapper.java:411) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:103) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:97) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:383) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:361) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.lambda$validateCompositeTemplate$28(MetadataIndexTemplateService.java:1593) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:697) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateCompositeTemplate(MetadataIndexTemplateService.java:1570) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateIndexTemplateV2(MetadataIndexTemplateService.java:723) ~[elasticsearch-8.9.0-SNAPSHOT.jar:8.9.0-SNAPSHOT]
```

**Comment by albertzaharovits** [comment]
Same test as https://github.com/elastic/elasticsearch/issues/87593 and https://github.com/elastic/elasticsearch/issues/95947 but with a different error.

**Comment by droberts195** [comment]
This may well have been fixed by #97302. If not then it suggests that a fix very similar to #97302 is required in one more place.

**Comment by craigtaverner** [comment]
Failed again today at https://gradle-enterprise.elastic.co/s/m4iosvxwao7wq/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testFullClusterRestart?top-execution=1

**Comment by craigtaverner** [comment]
I noticed that the above mentioned fixes were merged into `main`, but this CI failure is only occuring on 8.9, so perhaps a back-port would do the trick?

**Comment by droberts195** [comment]
> Failed again today at https://gradle-enterprise.elastic.co/s/m4iosvxwao7wq/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testFullClusterRestart?top-execution=1

That particular failure is the problem of #95947. There are multiple reasons for the same test failing at the moment.

**Comment by droberts195** [comment]
Assigning `medium-risk` due to loss of test coverage from muting.

**Comment by iverase** [comment]
https://gradle-enterprise.elastic.co/s/mpoaovveneqwi

**Comment by kingherc** [comment]
Another one at [elasticsearch / periodic / platform-support / main / rocky-9 / platform-support-unix](https://gradle-enterprise.elastic.co/s/oikitaz3tncra)

**Comment by mosche** [comment]
another one on 8.13
[elasticsearch / periodic / platform-support / 8.13 / almalinux-8-aarch64 / checkPart4 / platform-support-arm](https://gradle-enterprise.elastic.co/s/uppcikn2v566k)
Test failures:
[MlDistributedFailureIT » testFullClusterRestart](https://gradle-enterprise.elastic.co/s/uppcikn2v566k/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testFullClusterRestart)
