### ISSUE TITLE
[CI] SharedBytesTests testReleasesFileCorrectly failing

### ISSUE THREAD

**Issue by quux00** [elastic/elasticsearch#97626]
https://gradle-enterprise.elastic.co/s/dzmuhdmaew3t4/tests/:x-pack:plugin:blob-cache:test/org.elasticsearch.blobcache.shared.SharedBytesTests/testReleasesFileCorrectly?top-execution=1

Does not reproduce on MacOS, but this is a Windows test, so that is not surprising.

**Build scan:**
https://gradle-enterprise.elastic.co/s/dzmuhdmaew3t4/tests/:x-pack:plugin:blob-cache:test/org.elasticsearch.blobcache.shared.SharedBytesTests/testReleasesFileCorrectly

**Reproduction line:**
```
gradlew ':x-pack:plugin:blob-cache:test' --tests "org.elasticsearch.blobcache.shared.SharedBytesTests.testReleasesFileCorrectly" -Dtests.seed=4304E94D00142100 -Dtests.locale=ar-OM -Dtests.timezone=Cuba -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.blobcache.shared.SharedBytesTests&tests.test=testReleasesFileCorrectly

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([4304E94D00142100:A8E3F1E55E401319]:0)
  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertFalse(Assert.java:64)
  at org.junit.Assert.assertFalse(Assert.java:74)
  at org.elasticsearch.blobcache.shared.SharedBytesTests.testReleasesFileCorrectly(SharedBytesTests.java:50)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by craigtaverner** [comment]
Seems to have failed on windows only, multiple times since the merger of https://github.com/elastic/elasticsearch/pull/97581

**Comment by craigtaverner** [comment]
The description above does not give an error message, but I see this:

```


[2566-07-13T13:20:34,722][WARN ][o.e.b.s.SharedBytes      ] [testReleasesFileCorrectly] Failed to clean up shared bytes file |  
-- | --
  | java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\967\x-pack\plugin\blob-cache\build\testrun\test\temp\org.elasticsearch.blobcache.shared.SharedBytesTests_2B029CD690CC652E-001\tempDir-003\shared_snapshot_cache
```

At https://gradle-enterprise.elastic.co/s/vjnkv6wac3htc/tests/:x-pack:plugin:blob-cache:test/org.elasticsearch.blobcache.shared.SharedBytesTests/testReleasesFileCorrectly?top-execution=1

**Comment by davidkyle** [comment]
Reopening with the same failure in SharedBytesTest. The linked PR which is described as fixing this issue (https://github.com/elastic/elasticsearch/pull/97639) does not modify SharedBytesTest or its super class, was this closed accidentally?

https://gradle-enterprise.elastic.co/s/duoagjzyv2l2k/tests/:x-pack:plugin:blob-cache:test/org.elasticsearch.blobcache.shared.SharedBytesTests/testReleasesFileCorrectly?top-execution=1

**Comment by original-brownbear** [comment]
No it wasn't this only needs a test change but turns out I missed a spot ... let me fix this :)
