### ISSUE TITLE
EQL: async search with missing events fails with NPE

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#97644]
### Elasticsearch Version

8.10.0-SNAPSHOT

### Java Version

_bundled_

### OS Version

Windows

### Problem Description

When using async search with missing events, there is a failure to add the saved search to the async-search index, due to a serialization issue.

### Steps to Reproduce

```
PUT /test
{
  "mappings": {
    "dynamic": false,
    "properties": {
      "@timestamp": {
        "type": "date"
      },
      "event.category": {
        "type": "keyword"
      }
    }
  }
}


POST /test/_doc
{
   "@timestamp": "2023-07-11T11:09:05.529Z",
   "event.category": "process"
}

POST /test/_doc
{
   "@timestamp": "2023-07-11T11:09:05.529Z",
   "event.category": "process"
}

POST /test/_eql/search
{
 "wait_for_completion_timeout": "0ms",
  "keep_alive": "60s",
  "query": "sequence with maxspan=24h  [ process where true ]  ![ process where true ]  "
}
```

### Logs (if relevant)

```
failed to store eql search results for [FlAyZWItOTRBVFBLckJrSWNyZFBaamcdWGdhTmV6UV9RNDJYZVFqeFRWSEpQZzoxNDY5MDY=] java.lang.NullPointerException: Cannot invoke "org.elasticsearch.common.io.stream.Writeable.writeTo(org.elasticsearch.common.io.stream.StreamOutput)" because "v" is null
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.lambda$writeCollection$35(StreamOutput.java:1041)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1060)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1041)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeList(StreamOutput.java:1048)
at org.elasticsearch.xpack.eql.action.EqlSearchResponse$Sequence.writeTo(EqlSearchResponse.java:408)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.lambda$writeCollection$35(StreamOutput.java:1041)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1060)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1041)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeList(StreamOutput.java:1048)
at org.elasticsearch.xpack.eql.action.EqlSearchResponse$Hits.writeTo(EqlSearchResponse.java:505)
at org.elasticsearch.xpack.eql.action.EqlSearchResponse.writeTo(EqlSearchResponse.java:125)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeOptionalWriteable(StreamOutput.java:968)
at org.elasticsearch.xcore@8.10.0-SNAPSHOT/org.elasticsearch.xpack.core.async.StoredAsyncResponse.writeTo(StoredAsyncResponse.java:64)
at org.elasticsearch.xcore@8.10.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.writeResponse(AsyncTaskIndexService.java:575)
at org.elasticsearch.xcore@8.10.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.lambda$createResponseForEQL$1(AsyncTaskIndexService.java:222)
at org.elasticsearch.xcontent@8.10.0-SNAPSHOT/org.elasticsearch.xcontent.XContentBuilder.lambda$directFieldAsBase64$24(XContentBuilder.java:1229)
at org.elasticsearch.xcontent.impl@8.10.0-SNAPSHOT/org.elasticsearch.xcontent.provider.json.JsonXContentGenerator.writeDirectField(JsonXContentGenerator.java:543)
at org.elasticsearch.xcontent@8.10.0-SNAPSHOT/org.elasticsearch.xcontent.XContentBuilder.directFieldAsBase64(XContentBuilder.java:1223)
at org.elasticsearch.xcore@8.10.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.createResponseForEQL(AsyncTaskIndexService.java:222)
at org.elasticsearch.xpack.ql.async.AsyncTaskManagementService.storeResults(AsyncTaskManagementService.java:268)
at org.elasticsearch.xpack.ql.async.AsyncTaskManagementService.storeResults(AsyncTaskManagementService.java:263)
at org.elasticsearch.xpack.ql.async.AsyncTaskManagementService.lambda$wrapStoringListener$3(AsyncTaskManagementService.java:237)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.xpack.eql.plugin.TransportEqlSearchAction.lambda$operation$2(TransportEqlSearchAction.java:245)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:260)
at org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.xpack.eql.execution.search.BasicQueryClient.lambda$fetchHits$3(BasicQueryClient.java:179)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.xpack.eql.execution.search.PITAwareQueryClient.lambda$pitListener$3(PITAwareQueryClient.java:118)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.xpack.eql.execution.search.RuntimeUtils.lambda$multiSearchLogListener$1(RuntimeUtils.java:92)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.client.internal.node.NodeClient$SafelyWrappedActionListener.onResponse(NodeClient.java:160)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:205)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:199)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.TransportMultiSearchAction$1.finish(TransportMultiSearchAction.java:180)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.TransportMultiSearchAction$1.handleResponse(TransportMultiSearchAction.java:166)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:154)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:151)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.client.internal.node.NodeClient$SafelyWrappedActionListener.onResponse(NodeClient.java:160)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:205)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:199)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:260)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:723)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.FetchLookupFieldsPhase.run(FetchLookupFieldsPhase.java:75)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:470)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:464)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.ExpandSearchPhase.onPhaseDone(ExpandSearchPhase.java:151)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:105)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:470)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:464)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:273)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:110)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:119)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:90)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by karanbirsingh-qasource** [comment]
Hi @astefan 

we have validated this issue on 8.9.1 following the steps in the issue and found the issue to be fixed now ✔️ .

**Build Details:**
```
Version: 8.9.1 BC1
Commit: 6c664aeb22673e6eb42348ea50b5a098509f7deb
Build: 64802
```

**Screen-Shot:**

- Dev Hits has no error

![image](https://github.com/elastic/elasticsearch/assets/59917825/ee24e7df-6310-4c8a-8784-4191789b30a2)

- Sequence EQL query has no error on rule creation and alert generated from it

![Untitled](https://github.com/elastic/elasticsearch/assets/59917825/4dbd2210-2fa4-4645-9335-74a685804414)


c.c @MadameSheema
