### ISSUE TITLE
Can't retrieve stored fields as part of inner hits

### ISSUE THREAD

**Issue by tstibbs** [elastic/elasticsearch#9766]
I've been trying out the new 'inner_hits' stuff (see #8153, I built a 1.5 snapshot from commit 23ef4e8 on the 1.x branch).

However, I don't seem to be able to request stored fields from my nested documents. It would be great to be able to specify a 'fields' element as part of the nested hit.

Note that Martijn's comment in https://github.com/elasticsearch/elasticsearch/pull/8153#issuecomment-61798326 suggested it is possible, but I couldn't work out how... 

As a side note, that comment was suggested in relation to disabling the source. In my case I was trying to disable the source for just the nested children, by adding the following to my mapping:
````json
"_source" : {
    "excludes" : ["nested_field", "nested_field.*"]
}
````
which resulted in a null pointer exception...
````
java.lang.NullPointerException
	at org.elasticsearch.search.fetch.FetchPhase.createNestedSearchHit(FetchPhase.java:295)
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:178)
	at org.elasticsearch.search.fetch.innerhits.InnerHitsFetchSubPhase.hitExecute(InnerHitsFetchSubPhase.java:96)
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:190)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:501)
	at org.elasticsearch.search.action.SearchServiceTransportAction$17.call(SearchServiceTransportAction.java:452)
	at org.elasticsearch.search.action.SearchServiceTransportAction$17.call(SearchServiceTransportAction.java:449)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
````

**Comment by clintongormley** [comment]
The NPE sounds like a bug, because inner hits is expecting the source to be there.  You should be able to use the `fields` parameter to retrieve stored fields though (at least according to the docs: http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.x/search-request-inner-hits.html#nested-inner-hits )

**Comment by tstibbs** [comment]
@clintongormley yeah, I noticed the docs say you can use fields, but it doesn't tell you where to put the `fields` element within the `inner_hits` element - I've tried a whole bunch of different places but can't make any of them do anything other than give me a parse error. Looking at `InnerHitsParseElement` and `InnerHitsQueryParserHelper` etc I can't see it looking for fields so I think probably the docs are wrong in this case.

**Comment by martijnvg** [comment]
@tstibbs I referred to disabling the entire source and I think in your case you only leave out the nested part of your source. I see how this can result into the NPE you're describing.

**Comment by tstibbs** [comment]
@martijnvg yep, I noticed that, just thought I'd report the NPE as it's presumably a bug (though a pretty minor one).

My original point about not being able to retrieve stored fields (e.g. if you disable the entire source) is still valid though I think.

**Comment by martijnvg** [comment]
@tstibbs I opened #10235 in order to fix the stored field support in inner hits (it was supported, but forgot to add the parsing support for stored fields) and address the NPE you have found.
