### ISSUE TITLE
Elasticsearch in docker container crashes after restart when elasticsearch-plugins.yml is used

### ISSUE THREAD

**Issue by jawmn** [elastic/elasticsearch#97702]
### Elasticsearch Version

7.17.11

### Installed Plugins

repository-s3, analysis-icu

### Java Version

_bundled_

### OS Version

Linux 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

When desired plugins listed in file elasticsearch-plugins.yml, elasticsearch at start creates file plugins/.elasticsearch-plugins.yml.cache. Once container restarts, this file prevents elasticsearch from starting.

### Steps to Reproduce

Define plugins in config/elasticsearch-plugins.yml, for example:
```
plugins:
  - id: analysis-icu
  - id: repository-s3
```
Start docker container, then restart it.

### Logs (if relevant)

```
Exception in thread "main" java.nio.file.NotDirectoryException: /usr/share/elasticsearch/plugins/.elasticsearch-plugins.yml.cache
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:476)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:481)
	at java.base/java.nio.file.Files.list(Files.java:3767)
	at org.elasticsearch.tools.launchers.BootstrapJvmOptions.getPluginInfo(BootstrapJvmOptions.java:49)
	at org.elasticsearch.tools.launchers.BootstrapJvmOptions.bootstrapJvmOptions(BootstrapJvmOptions.java:34)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
```

**Comment by soulCooker** [comment]
try mount /usr/share/elasticsearch/plugins to a docker volumes
for example:
   volumes:
      - es7plugin2:/usr/share/elasticsearch/plugins
volumes:
  es7plugin2:
    driver: local

**Comment by rjernst** [comment]
BootstrapJvmOptions only existed in 7.x, so the scope of this issue is limited. I opened https://github.com/elastic/elasticsearch/pull/109116 to fix.

**Comment by mosche** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/109116
