### ISSUE TITLE
query against node that is not master get remotetransportexception exception

### ISSUE THREAD

**Issue by omerh** [elastic/elasticsearch#9776]
I have a cluster setup
elasticsearch 1.4.3
Java version 1.7.0_75

when I query the master i get the result fast, but when quering a node on the cluster I get the following exception:

```
"error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[Lo1poYQOQSyEGHmAx9bt5w][agg_usages][0]: SearchParseException[[agg_usages][0]: from[-1],size[-1]:
```

Exception in log is:
```
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:687)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:543)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:515)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:277)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchParseException: Expected START_OBJECT but got START_ARRAY null
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:661)
```

**Comment by kimchy** [comment]
can you show the request you are sending? seems like the JSON you are building is starting with `[ ... `, and we only support `{ ... ` .

**Comment by clintongormley** [comment]
No feedback. Closing
