### ISSUE TITLE
Marvel nullpointer with 1.4.3

### ISSUE THREAD

**Issue by analytically** [elastic/elasticsearch#9778]
```
java.lang.NullPointerException
        at org.elasticsearch.marvel.agent.Utils.extractHostsFromHttpServer(Utils.java:90)
        at org.elasticsearch.marvel.agent.exporter.ESExporter.openAndValidateConnection(ESExporter.java:344)
        at org.elasticsearch.marvel.agent.exporter.ESExporter.openExportingConnection(ESExporter.java:212)
        at org.elasticsearch.marvel.agent.exporter.ESExporter.exportXContent(ESExporter.java:275)
        at org.elasticsearch.marvel.agent.exporter.ESExporter.exportNodeStats(ESExporter.java:173)
        at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.exportNodeStats(AgentService.java:305)
        at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.run(AgentService.java:225)
```

**Comment by bleskes** [comment]
@analytically thx for reporting. Does this happen all the time for you? does it help if you increase the agent's data sampling interval? (marvel.agent.interval )

I had similar issue fixed in the yet-to-be released code and I want to make sure it's the same.

**Comment by analytically** [comment]
It does happen all the time. I'm seeing the same with 1.4.4.

**Comment by bleskes** [comment]
@analytically thx. This is a Marvel issue not ES. Can you try increasing the marvel.agent.interval and see it helps?

**Comment by mausch** [comment]
I'm seeing this in 1.4.2 too.

**Comment by clintongormley** [comment]
Marvel 2 has been completely rewritten. Closing
