### ISSUE TITLE
[CI] AzureBlobStoreRepositoryTests testReadNonExistingPath failing

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#97799]
**Build scan:**
https://gradle-enterprise.elastic.co/s/clwdebv6laqfw/tests/:modules:repository-azure:internalClusterTest/org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests/testReadNonExistingPath

**Reproduction line:**
```
./gradlew ':modules:repository-azure:internalClusterTest' --tests "org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests.testReadNonExistingPath" -Dtests.seed=64E8B0A2A854CC1C -Dtests.locale=da -Dtests.timezone=Asia/Amman -Druntime.java=20
```

**Applicable branches:**
8.9

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests&tests.test=testReadNonExistingPath

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=137, name=[org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase][T#2], state=RUNNABLE, group=TGRP-AzureBlobStoreRepositoryTests]

  at __randomizedtesting.SeedInfo.seed([64E8B0A2A854CC1C:59D72DF4D5155188]:0)

  Caused by: java.lang.AssertionError: State is not REQUEST (IDLE)

    at __randomizedtesting.SeedInfo.seed([64E8B0A2A854CC1C]:0)
    at sun.net.httpserver.ServerImpl.requestCompleted(ServerImpl.java:984)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:761)
    at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase.lambda$startHttpServer$0(ESMockAPIBasedRepositoryIntegTestCase.java:104)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by williamrandolph** [comment]
I had the same failure on main today with another test in the suite: https://gradle-enterprise.elastic.co/s/litjnrpyarrra

```


:modules:repository-azure:internalClusterTest FAILED |  
:modules:repository-azure:internalClusterTest FAILED
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8
Oct 18, 2023 4:08:19 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>
WARNING: COMPAT locale provider will be removed in a future release

REPRODUCE WITH: ./gradlew ':modules:repository-azure:internalClusterTest' --tests "org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests.testRequestStats" -Dtests.seed=C7A02B86B5D3A61 -Dtests.locale=bg-BG -Dtests.timezone=Asia/Dili -Druntime.java=21

org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests > testRequestStats FAILED
    java.lang.AssertionError: State is not REQUEST (IDLE)
        at __randomizedtesting.SeedInfo.seed([C7A02B86B5D3A61]:0)
        at jdk.httpserver/sun.net.httpserver.ServerImpl.requestCompleted(ServerImpl.java:1001)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:773)
        at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase.lambda$startHttpServer$0(ESMockAPIBasedRepositoryIntegTestCase.java:104)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

Tests with failures:
 - org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests.testRequestStats

15 tests completed, 1 failed
```

**Comment by ywangd** [comment]
Same error but on a different test method `testSnapshotWithLargeSegmentFiles`

https://gradle-enterprise.elastic.co/s/uipe6ktvqco4q/tests/task/:modules:repository-azure:internalClusterTest/details/org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests/testSnapshotWithLargeSegmentFiles?expanded-stacktrace=WyIwIl0&top-execution=1

**Comment by DaveCTurner** [comment]
This was a JDK bug https://bugs.openjdk.org/browse/JDK-8299058, should be ok now.
