### ISSUE TITLE
Windows packaging tests - runbld failing to parse git commit messages

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#97998]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.8+multijob+packaging-tests-windows/os=windows-2012-r2/412/console

### Repro line

n/a

### Does it reproduce?

Didn't try

### Applicable branches

8.8

### Failure history

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.8+multijob+packaging-tests-windows/os=windows-2012-r2/

### Failure excerpt

```
runbld>>> Platform: windows
09:03:38 commit 85b40b7eb5b9f9905a70610545660d062daedf6f
09:03:38 tree 7a2dfc44bea3fd862535c6e4a15239f6eb9f0cda
09:03:38 parent 6186b18c2f4583c01f9d0d9aea607592131195ca
09:03:38 author Ryan Ernst <ryan@iernst.net> 1690308912 -0700
09:03:38 committer Ryan Ernst <ryan@iernst.net> 1690309455 -0700
09:03:38 gpgsig -----BEGIN SSH SIGNATURE-----
09:03:38  U1NIU0lHAAAAAQAAADMAAAALc3NoLWVkMjU1MTkAAAAgp/BfveRrtVUWiRB5wn8/tegbGr
09:03:38  DscD3xPgUWJBV1oV8AAAADZ2l0AAAAAAAAAAZzaGE1MTIAAABTAAAAC3NzaC1lZDI1NTE5
09:03:38  AAAAQACS4OfJMk2Wu4fmPBm6EOJuaB/xkHwyjaQyWgIs3BOiCWT94R+YPPSrjFvVqRFIW7
09:03:38  kOQh+BHdIofsjRl1WU/AA=
09:03:38  -----END SSH SIGNATURE-----
09:03:38 
09:03:38     Bump versions after 7.17.12 release
09:03:38 
09:03:38 runbld>>> Sending debug log to infra-root+runbld-debug@e***.co
09:03:38 Exception in thread "main" clojure.lang.ExceptionInfo: throw+: {:res Parse error at line 6, column 8:
09:03:38 gpgsig -----BEGIN SSH SIGNATURE-----
09:03:38        ^
09:03:38 Expected:
09:03:38 "-----BEGIN PGP SIGNATURE-----"
09:03:38 , :commit "commit 85b40b7eb5b9f9905a70610545660d062daedf6f\ntree 7a2dfc44bea3fd862535c6e4a15239f6eb9f0cda\nparent 6186b18c2f4583c01f9d0d9aea607592131195ca\nauthor Ryan Ernst <ryan@iernst.net> 1690308912 -0700\ncommitter Ryan Ernst <ryan@iernst.net> 1690309455 -0700\ngpgsig -----BEGIN SSH SIGNATURE-----\n U1NIU0lHAAAAAQAAADMAAAALc3NoLWVkMjU1MTkAAAAgp/BfveRrtVUWiRB5wn8/tegbGr\n DscD3xPgUWJBV1oV8AAAADZ2l0AAAAAAAAAAZzaGE1MTIAAABTAAAAC3NzaC1lZDI1NTE5\n AAAAQACS4OfJMk2Wu4fmPBm6EOJuaB/xkHwyjaQyWgIs3BOiCWT94R+YPPSrjFvVqRFIW7\n kOQh+BHdIofsjRl1WU/AA=\n -----END SSH SIGNATURE-----\n\n    Bump versions after 7.17.12 release\n"} {:res Parse error at line 6, column 8:
09:03:38 gpgsig -----BEGIN SSH SIGNATURE-----
09:03:38        ^
09:03:38 Expected:
09:03:38 "-----BEGIN PGP SIGNATURE-----"
09:03:38 , :commit "commit 85b40b7eb5b9f9905a70610545660d062daedf6f\ntree 7a2dfc44bea3fd862535c6e4a15239f6eb9f0cda\nparent 6186b18c2f4583c01f9d0d9aea607592131195ca\nauthor Ryan Ernst <ryan@iernst.net> 1690308912 -0700\ncommitter Ryan Ernst <ryan@iernst.net> 1690309455 -0700\ngpgsig -----BEGIN SSH SIGNATURE-----\n U1NIU0lHAAAAAQAAADMAAAALc3NoLWVkMjU1MTkAAAAgp/BfveRrtVUWiRB5wn8/tegbGr\n DscD3xPgUWJBV1oV8AAAADZ2l0AAAAAAAAAAZzaGE1MTIAAABTAAAAC3NzaC1lZDI1NTE5\n AAAAQACS4OfJMk2Wu4fmPBm6EOJuaB/xkHwyjaQyWgIs3BOiCWT94R+YPPSrjFvVqRFIW7\n kOQh+BHdIofsjRl1WU/AA=\n -----END SSH SIGNATURE-----\n\n    Bump versions after 7.17.12 release\n"}
09:03:38 	at slingshot.support$stack_trace.invoke(support.clj:201)
09:03:38 	at runbld.util.debug$with_debug_logging.invokeStatic(debug.clj:93)
09:03:38 	at runbld.util.debug$with_debug_logging.invoke(debug.clj:77)
09:03:38 	at runbld.main$fn__13281$fn__13282.invoke(main.clj:73)
09:03:38 	at runbld.main$fn__13274$fn__13275.invoke(main.clj:72)
09:03:38 	at runbld.main$_main.invokeStatic(main.clj:106)
09:03:38 	at runbld.main$_main.doInvoke(main.clj:95)
09:03:38 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
09:03:38 	at runbld.main.main(Unknown Source)
09:03:38 Caused by: clojure.lang.ExceptionInfo: parse failure {:res Parse error at line 6, column 8:
09:03:38 gpgsig -----BEGIN SSH SIGNATURE-----
09:03:38        ^
09:03:38 Expected:
09:03:38 "-----BEGIN PGP SIGNATURE-----"
09:03:38 , :commit "commit 85b40b7eb5b9f9905a70610545660d062daedf6f\ntree 7a2dfc44bea3fd862535c6e4a15239f6eb9f0cda\nparent 6186b18c2f4583c01f9d0d9aea607592131195ca\nauthor Ryan Ernst <ryan@iernst.net> 1690308912 -0700\ncommitter Ryan Ernst <ryan@iernst.net> 1690309455 -0700\ngpgsig -----BEGIN SSH SIGNATURE-----\n U1NIU0lHAAAAAQAAADMAAAALc3NoLWVkMjU1MTkAAAAgp/BfveRrtVUWiRB5wn8/tegbGr\n DscD3xPgUWJBV1oV8AAAADZ2l0AAAAAAAAAAZzaGE1MTIAAABTAAAAC3NzaC1lZDI1NTE5\n AAAAQACS4OfJMk2Wu4fmPBm6EOJuaB/xkHwyjaQyWgIs3BOiCWT94R+YPPSrjFvVqRFIW7\n kOQh+BHdIofsjRl1WU/AA=\n -----END SSH SIGNATURE-----\n\n    Bump versions after 7.17.12 release\n"}
09:03:38 	at clj_git.core$parse_raw_commit.invokeStatic(core.clj:180)
09:03:38 	at clj_git.core$parse_raw_commit.invoke(core.clj:175)
09:03:38 	at clj_git.core$git_log_commit.invokeStatic(core.clj:189)
09:03:38 	at clj_git.core$git_log_commit.invoke(core.clj:184)
09:03:38 	at runbld.vcs.git$head_commit.invokeStatic(git.clj:90)
09:03:38 	at runbld.vcs.git$head_commit.invoke(git.clj:87)
09:03:38 	at runbld.vcs.git$fn__7783$log_latest__7788$fn__7789.invoke(git.clj:135)
09:03:38 	at runbld.vcs.git$fn__7783$log_latest__7788.invoke(git.clj:133)
09:03:38 	at runbld.vcs$fn__6872$G__6859__6877.invoke(vcs.clj:3)
09:03:38 	at runbld.vcs.middleware$fn__7937$add_vcs_info__7942$fn__7943.invoke(middleware.clj:48)
09:03:38 	at runbld.vcs.middleware$fn__7937$add_vcs_info__7942.invoke(middleware.clj:41)
09:03:38 	at runbld.main$fn__13343$fn__13344.invoke(main.clj:82)
09:03:38 	at runbld.main$fn__13336$fn__13337.invoke(main.clj:81)
09:03:38 	at runbld.main$fn__13329$fn__13330.invoke(main.clj:80)
09:03:38 	at runbld.main$fn__13322$fn__13323.invoke(main.clj:79)
09:03:38 	at runbld.main$fn__13315$fn__13316.invoke(main.clj:78)
09:03:38 	at runbld.main$fn__13308$fn__13309.invoke(main.clj:77)
09:03:38 	at runbld.main$fn__13301$fn__13302.invoke(main.clj:76)
09:03:38 	at runbld.main$fn__13294$fn__13295.invoke(main.clj:75)
09:03:38 	at runbld.main$fn__13287$fn__13288.invoke(main.clj:74)
09:03:38 	at runbld.util.debug$with_debug_logging.invokeStatic(debug.clj:82)
09:03:38 	... 7 more
09:04:38 
```

Has been failing for a couple of days now.

**Comment by edsavage** [comment]
And another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.8+multijob+packaging-tests-windows/os=windows-2012-r2/467/console

**Comment by mark-vieira** [comment]
Looks like this is due to an old version of `runbld` on these old Windows agents. @brianseeders is investigating.
