### ISSUE TITLE
[CI] QueryFeatureExtractorTests testQueryExtractor failing

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#98127]
**Build scan:**
https://gradle-enterprise.elastic.co/s/t6hdkuadj5qem/tests/:x-pack:plugin:ml:test/org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests/testQueryExtractor

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests.testQueryExtractor" -Dtests.seed=C4A0A3DDA3C8FD63 -Dtests.locale=ar-QA -Dtests.timezone=Antarctica/Vostok -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests&tests.test=testQueryExtractor

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: map containing ["number_score"-><1.0F>]
     but: map was []

  at __randomizedtesting.SeedInfo.seed([C4A0A3DDA3C8FD63:C39EDBEDE28E481C]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests.testQueryExtractor(QueryFeatureExtractorTests.java:119)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by pgomulka** [comment]
another one on main https://gradle-enterprise.elastic.co/s/xkgjimpjkagl6/tests/:x-pack:plugin:ml:test/org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests/testQueryExtractor?top-execution=1

**Comment by astefan** [comment]
[Another one](https://gradle-enterprise.elastic.co/s/76cqsik25tvco) today: `gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests.testQueryExtractor" -Dtests.seed=8E60D992F5931488 -Dtests.locale=sr-Latn-RS -Dtests.timezone=US/Central -Druntime.java=20`

It does reproduce (tested in `main`). The output is slightly different though:

```
org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests > testQueryExtractor FAILED
    java.lang.AssertionError: target must be > docID(), got 3 <= 3
        at __randomizedtesting.SeedInfo.seed([8E60D992F5931488:895EA1A2B4D5A1F7]:0)
        at org.apache.lucene.tests.search.AssertingScorer$1.advance(AssertingScorer.java:173)
        at org.apache.lucene.search.DisjunctionDISIApproximation.advance(DisjunctionDISIApproximation.java:67)
        at org.apache.lucene.search.DisjunctionDISIApproximation.advance(DisjunctionDISIApproximation.java:67)
        at org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractor.addFeatures(QueryFeatureExtractor.java:63)
        at org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests.testQueryExtractor(QueryFeatureExtractorTests.java:103)


Suite: Test class org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests
  1> [2023-08-17T05:48:00,538][INFO ][o.e.x.m.i.r.QueryFeatureExtractorTests] [testQueryExtractor] before test
  1> [2023-08-17T05:48:01,833][INFO ][o.e.x.m.i.r.QueryFeatureExtractorTests] [testQueryExtractor] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests.testQueryExtractor" -Dtests.seed=8E60D992F5931488 -Dtests.locale=sr-Latn-RS -Dtests.timezone=US/Central -Druntime.java=20
  2> java.lang.AssertionError: target must be > docID(), got 3 <= 3
        at __randomizedtesting.SeedInfo.seed([8E60D992F5931488:895EA1A2B4D5A1F7]:0)
        at org.apache.lucene.tests.search.AssertingScorer$1.advance(AssertingScorer.java:173)
        at org.apache.lucene.search.DisjunctionDISIApproximation.advance(DisjunctionDISIApproximation.java:67)
        at org.apache.lucene.search.DisjunctionDISIApproximation.advance(DisjunctionDISIApproximation.java:67)
        at org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractor.addFeatures(QueryFeatureExtractor.java:63)
        at org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests.testQueryExtractor(QueryFeatureExtractorTests.java:103)
```

**Comment by thecoop** [comment]
And again: https://gradle-enterprise.elastic.co/s/gljbbiyzd4cse/tests/task/:x-pack:plugin:ml:test/details/org.elasticsearch.xpack.ml.inference.rescorer.QueryFeatureExtractorTests/testQueryExtractor?top-execution=1
