### ISSUE TITLE
[CI] FleetRestIT test {p0=fleet/30_secrets_post/Create Fleet Secret} failing

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#98179]
**Build scan:**
https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F30_secrets_post%2FCreate%20Fleet%20Secret%7D

**Reproduction line:**
```
./gradlew ':x-pack:plugin:fleet:qa:rest:yamlRestTest' --tests "org.elasticsearch.xpack.fleet.FleetRestIT.test {p0=fleet/30_secrets_post/Create Fleet Secret}" -Dtests.seed=9CB985A118760D1F -Dtests.locale=hi -Dtests.timezone=America/Caracas -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.fleet.FleetRestIT&tests.test=test%20%7Bp0%3Dfleet/30_secrets_post/Create%20Fleet%20Secret%7D

**Failure excerpt:**
```
java.lang.RuntimeException: Failure at [fleet/30_secrets_post:2]: Connection reset

  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:573)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:523)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.io.IOException: Connection reset

    at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:935)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:303)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
    at org.elasticsearch.test.rest.yaml.ClientYamlTestClient.callApi(ClientYamlTestClient.java:204)
    at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApiInternal(ClientYamlTestExecutionContext.java:186)
    at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApi(ClientYamlTestExecutionContext.java:106)
    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:343)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:551)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:523)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1623)

    Caused by: java.net.SocketException: Connection reset

      at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
      at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
      at org.apache.http.impl.nio.reactor.SessionInputBufferImpl.fill(SessionInputBufferImpl.java:231)
      at org.apache.http.impl.nio.codecs.AbstractMessageParser.fillBuffer(AbstractMessageParser.java:136)
      at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:241)
      at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)
      at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)
      at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
      at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
      at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
      at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
      at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
      at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
      at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
      at java.lang.Thread.run(Thread.java:1623)

```

**Comment by mayya-sharipova** [comment]
It seems that all test in `FleetRestIT` fail:

[FleetRestIT » test {p0=fleet/30_secrets_post/Create Fleet Secret}](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F30_secrets_post%2FCreate%20Fleet%20Secret%7D)
[FleetRestIT » test {p0=fleet/50_secrets_delete/Delete non existent Fleet Se...](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F50_secrets_delete%2FDelete%20non%20existent%20Fleet%20Secret%7D)
[FleetRestIT » test {p0=fleet/20_wait_for_checkpoints/Wait for unprocessed c...](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F20_wait_for_checkpoints%2FWait%20for%20unprocessed%20checkpoint%20fails%7D)
[FleetRestIT » test {p0=fleet/50_secrets_delete/Delete Fleet Secret}](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F50_secrets_delete%2FDelete%20Fleet%20Secret%7D)
[FleetRestIT » test {p0=fleet/10_global_checkpoints/Get Global Checkpoints a...](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F10_global_checkpoints%2FGet%20Global%20Checkpoints%20after%20advance%7D)
[FleetRestIT » test {p0=fleet/20_wait_for_checkpoints/Cannot wait_for_checkp...](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F20_wait_for_checkpoints%2FCannot%20wait_for_checkpoints%20with%20refresh%20disabled%7D)
[FleetRestIT » test {p0=fleet/20_wait_for_checkpoints/Execute successful sea...](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F20_wait_for_checkpoints%2FExecute%20successful%20search%20with%20wait_for_checkpoints%20default%7D)
[FleetRestIT » test {p0=fleet/20_wait_for_checkpoints/Test msearch wait_for_...](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F20_wait_for_checkpoints%2FTest%20msearch%20wait_for_checkpoints%20default%7D)
[FleetRestIT » test {p0=fleet/10_global_checkpoints/Wait for index timeout}](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F10_global_checkpoints%2FWait%20for%20index%20timeout%7D)
[FleetRestIT » test {p0=fleet/40_secrets_get/Get Fleet Secret}](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F40_secrets_get%2FGet%20Fleet%20Secret%7D)
[FleetRestIT » test {p0=fleet/20_wait_for_checkpoints/Can use alias}](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F20_wait_for_checkpoints%2FCan%20use%20alias%7D)
[FleetRestIT » test {p0=fleet/20_wait_for_checkpoints/Execute successful aft...](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F20_wait_for_checkpoints%2FExecute%20successful%20after%20refresh%20search%7D)
[FleetRestIT » test {p0=fleet/10_global_checkpoints/Advance no timeout}](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F10_global_checkpoints%2FAdvance%20no%20timeout%7D)
[FleetRestIT » test {p0=fleet/40_secrets_get/Get non existent Fleet Secret}](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F40_secrets_get%2FGet%20non%20existent%20Fleet%20Secret%7D)
[FleetRestIT » test {p0=fleet/20_wait_for_checkpoints/Must provide correct n...](https://gradle-enterprise.elastic.co/s/dxn5rl6n5hxju/tests/:x-pack:plugin:fleet:qa:rest:yamlRestTest/org.elasticsearch.xpack.fleet.FleetRestIT/test%20%7Bp0=fleet%2F20_wait_for_checkpoints%2FMust%20provide%20correct%20number%20of%20checkpoints%7D)

**Comment by jbaiera** [comment]
I'm muting these since they have been failing somewhat consistently https://github.com/elastic/elasticsearch/pull/98181

**Comment by jbaiera** [comment]
cc/ @elastic/fleet

**Comment by juliaElastic** [comment]
@jbaiera Could you advise what could cause the `Connection reset` errors? Are we doing something wrong in the tests?

**Comment by tvernum** [comment]
Discussed internally - the issue is that the Rest Action assumes the HTTP Body is a UTF8 string, which may not be the case (e.g. if the test uses SMILE as the content-type)
