### ISSUE TITLE
NoSuchFileException _1gl.si in OldIndexBackwardsCompatibilityTests

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#9822]
OldIndexBackCompatTests fails (rarely, won't repro for me after beasting) sometimes (http://build-us-00.elasticsearch.org/job/es_core_1x_centos/3304/console) with this nasty exception:

```
java.nio.file.NoSuchFileException: _1gl.si in dir=least_used[rate_limited(default(mmapfs(/mnt/jenkins/workspace/es_core_1x_centos/target/J0/data/TEST-ip-10-255-15-175-CHILD_VM=[0]-CLUSTER_SEED=[3276434121362593305]-HASH=[87FD12A7499C81]/nodes/1/indices/test/0/index),niofs(/mnt/jenkins/workspace/es_core_1x_centos/target/J0/data/TEST-ip-10-255-15-175-CHILD_VM=[0]-CLUSTER_SEED=[3276434121362593305]-HASH=[87FD12A7499C81]/nodes/1/indices/test/0/index)), type=MERGE, rate=20.0)]
	at org.apache.lucene.store.MockDirectoryWrapper.openInput(MockDirectoryWrapper.java:603)
	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:80)
	at org.elasticsearch.index.store.Store$StoreDirectory.openInput(Store.java:688)
	at org.apache.lucene.codecs.lucene3x.Lucene3xSegmentInfoReader.read(Lucene3xSegmentInfoReader.java:106)
	at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:358)
	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:454)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:906)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:752)
	at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:450)
	at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:92)
	at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:158)
	at org.elasticsearch.index.store.Store.readLastCommittedSegmentsInfo(Store.java:148)
	at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:648)
	at org.elasticsearch.index.engine.InternalEngine.snapshotIndex(InternalEngine.java:774)
	at org.elasticsearch.test.store.MockFSDirectoryService$1.beforeIndexShardClosed(MockFSDirectoryService.java:93)
	at org.elasticsearch.indices.InternalIndicesLifecycle.beforeIndexShardClosed(InternalIndicesLifecycle.java:193)
	at org.elasticsearch.index.IndexService.closeShardInjector(IndexService.java:391)
	at org.elasticsearch.index.IndexService.removeShard(IndexService.java:382)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyDeletedShards(IndicesClusterStateService.java:294)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:187)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:466)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:182)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

It's always with the 0.20.6 index (= Lucene 3.6.2).  The exc is bad: it means Lucene corrupted the 3.x index on first commit with Lucene 4.x, because it failed to write an upgraded .si file yet did reference it.

Digging with @s1monw we uncovered one abuse case where Lucene could do this https://issues.apache.org/jira/browse/LUCENE-6279 (which is a "won't fix") where if a directory is "dirty" (has unrelated index files from a previous index), Lucene will fail to upgrade the .si files and the index will be corrupt.

So ... is ES re-using directories here?  The test make new nodes, sharing the local data dir, to replicate to, and then later closes them before testing the next index.  Each node that starts up will try to find a free (not locked) sub-dir of the data dir, and then that may have leftover files from the last time that index was replicated to that node?

If this is happening ... I think we need to somehow fix ES to never share dirty index directories?

**Comment by mikemccand** [comment]
One thing that freaks me out a bit about the 0.20.6.zip back compat test index is it has big segment names e.g. _1gz, _1gm, whereas the other indices all have tiny (brand new index) segments like _0, _1, ... not sure it's related but it's sort of weird :)  @rjernst any ideas?

**Comment by mikemccand** [comment]
I turned on logging for all file deletions: https://github.com/elasticsearch/elasticsearch/commit/50875f13a78e03886b27dd84c2e98713a5afbcfd

Maybe it sheds light on the next failure ...

**Comment by rmuir** [comment]
I think i added this one. I altered ryan's code locally to ensure this segment had non-cfs segments. means i told it to make a lot more docs. You can see with ls -l that its 10x bigger than the other test indexes.

Particularly, most test indexes are trivially small and only contain cfs segments from flush. I needed this one to have non-cfs segments so that we could test some of the corner cases present there (like old adler32 checksums for term dictionaries that seek'ed on write)

**Comment by mikemccand** [comment]
@rmuir ahh good, thanks for the explanation.  It's good that it's non-trivial ... maybe that's related here (this test only seems to fail with 0.20.6 index even though there are other 3.x indices).

**Comment by rmuir** [comment]
I looked and none of the 0.20.6 indexes have any CFS. Yet all of the later ones do (and no non-CFS). None of the indexes have any deletes, or documents in translogs.

So I don't remember what my issue was and why i needed to hack the script to produce more documents, but I am sure its because my expected test would not fail without me doing it... I generally hide from python.

related: #9143

**Comment by mikemccand** [comment]
The "log all file deletions" (test.engine.lucene.iw.ifd logger) we turned on for this test was very helpful!  It revealed a different Lucene bug  that looks to be the cause here: https://issues.apache.org/jira/browse/LUCENE-6287

I suspect because this particular index (0.20.6) had many more segments and therefore needed merging, it tickled this Lucene bug.

**Comment by clintongormley** [comment]
Old issue, closing
