### ISSUE TITLE
[CI] InferenceRescorerIT testInferenceRescore failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#98372]
This test along with `testInferenceRescoreSmallWindow` and `testInferenceRescorerWithChainedRescorers` fail in release tests because they need `inference_rescorer` feature flag to be enabled.

**Build scan:**
https://gradle-enterprise.elastic.co/s/cndzfyrgsbdji/tests/:x-pack:plugin:ml:qa:single-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.InferenceRescorerIT/testInferenceRescore

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.InferenceRescorerIT.testInferenceRescore" -Dtests.seed=D4F21BB6A9D4C7A4 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=zh-Hant-TW -Dtests.timezone=Asia/Vientiane -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.InferenceRescorerIT&tests.test=testInferenceRescore

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:44031], URI [_ml/trained_models/ltr-model], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"named_object_not_found_exception","reason":"[5:6] unknown field [learn_to_rank]"}],"type":"x_content_parse_exception","reason":"[5:6] [trained_model_config] failed to parse field [inference_config]","caused_by":{"type":"x_content_parse_exception","reason":"[5:6] [inference_config] failed to parse field [learn_to_rank]","caused_by":{"type":"named_object_not_found_exception","reason":"[5:6] unknown field [learn_to_rank]"}}},"status":400}

  at __randomizedtesting.SeedInfo.seed([D4F21BB6A9D4C7A4:512C14F654D3A535]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.xpack.ml.integration.InferenceTestCase.putRegressionModel(InferenceTestCase.java:106)
  at org.elasticsearch.xpack.ml.integration.InferenceRescorerIT.setupModelAndData(InferenceRescorerIT.java:28)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by ywangd** [comment]
These tests failed on my PR (#98307) that needs to run release test. I muted them in e2aa4f9a21b269cdd323ee50e51b75976067b033

**Comment by maxhniebergall** [comment]
The file was renamed to `LearnToRankRescorerIT`

https://github.com/elastic/elasticsearch/commit/4faa02f68cd48223cbd17761425558512566eb50#diff-6db7a2e1f51f93db9fb6c77da55e48e77d4a93f6c051b378406d2d6280429bf4

**Comment by maxhniebergall** [comment]
I was able to reproduce two of the test failures:
`./gradlew ':x-pack:plugin:ml:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT.testLearningToRankRescorerWithChainedRescorers {seed=[4532878D3975E25:BF0819146D1CF712]}" -Dtests.seed=4532878D3975E25 -Dtests.locale=bg -Dtests.timezone=Etc/GMT+10 -Druntime.java=21`

`./gradlew ':x-pack:plugin:ml:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT.testLearningToRankRescoreSmallWindow {seed=[4532878D3975E25:5DD60B2C26E14FEE]}" -Dtests.seed=4532878D3975E25 -Dtests.locale=bg -Dtests.timezone=Etc/GMT+10 -Druntime.java=21`

`testLearningToRankRescore` didn't fail in my hundreds of iterations
