### ISSUE TITLE
ESQL: allow minus in eval expressions

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#98388]
### Description

This should a valid `eval` command, but it's not supported atm: `from employees | eval minus_salary = -salary | keep minus_salary, salary`

Error message received:

```
[2023-08-11T13:29:51,339][WARN ][r.suppressed             ] [runTask-0] path: /_query, params: {format=txt} org.elasticsearch.xpack.ql.QlIllegalArgumentException: Unsupported expression [-salary]
        at org.elasticsearch.xpack.esql.planner.EvalMapper.toEvaluator(EvalMapper.java:83)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planEval(LocalExecutionPlanner.java:367)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:165)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planProject(LocalExecutionPlanner.java:500)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:171)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planOutput(LocalExecutionPlanner.java:260)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:197)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:146)
```

**Comment by alex-spies** [comment]
I'm on it already, draft PR is here: https://github.com/elastic/elasticsearch/pull/98352

**Comment by alex-spies** [comment]
This works now that https://github.com/elastic/elasticsearch/pull/98352 is merged.
