### ISSUE TITLE
[CI] DownsampleClusterDisruptionIT failures

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#98485]
**Build scan:**
https://gradle-enterprise.elastic.co/s/sckamdegc5wei/tests/:x-pack:plugin:downsample:internalClusterTest/org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT/testDownsampleIndexWithRollingRestart

**Reproduction line:**
```
./gradlew ':x-pack:plugin:downsample:internalClusterTest' --tests "org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT.testDownsampleIndexWithRollingRestart" -Dtests.seed=BEED2AC8F65AB92C -Dtests.locale=ar-LB -Dtests.timezone=Asia/Ust-Nera -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT&tests.test=testDownsampleIndexWithRollingRestart

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=429, name=elasticsearch[node_t2][write][T#1], state=RUNNABLE, group=TGRP-DownsampleClusterDisruptionIT]


  Caused by: java.lang.AssertionError: primary indexing unexpected in state [CLOSED]

    at __randomizedtesting.SeedInfo.seed([BEED2AC8F65AB92C]:0)
    at org.elasticsearch.index.shard.IndexShard.assertStartedForPrimaryIndexing(IndexShard.java:2204)
    at org.elasticsearch.index.shard.IndexShard.ensureWriteAllowed(IndexShard.java:2184)
    at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:955)
    at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:902)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:355)
    at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:219)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:286)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:137)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:74)
    at org.elasticsearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:215)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by DaveCTurner** [comment]
>  Caused by: java.lang.AssertionError: primary indexing unexpected in state [CLOSED]

This is fixed by #98519
