### ISSUE TITLE
[CI] TransformPersistentTasksExecutorTests testNodeVersionAssignment failing

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#98564]
Seems related to https://github.com/elastic/elasticsearch/issues/98552

**Build scan:**
https://gradle-enterprise.elastic.co/s/jlwmbb5bzxpo2/tests/:x-pack:plugin:transform:test/org.elasticsearch.xpack.transform.transforms.TransformPersistentTasksExecutorTests/testNodeVersionAssignment

**Reproduction line:**
```
./gradlew ':x-pack:plugin:transform:test' --tests "org.elasticsearch.xpack.transform.transforms.TransformPersistentTasksExecutorTests.testNodeVersionAssignment" -Dtests.seed=E767AF7B95825F28 -Dtests.locale=sq -Dtests.timezone=Egypt -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.transform.transforms.TransformPersistentTasksExecutorTests&tests.test=testNodeVersionAssignment

**Failure excerpt:**
```
java.lang.IllegalArgumentException: Cannot convert 8.11.0. Incompatible version

  at __randomizedtesting.SeedInfo.seed([E767AF7B95825F28:B3343E93BE548785]:0)
  at org.elasticsearch.xpack.core.transform.TransformConfigVersion.fromVersion(TransformConfigVersion.java:310)
  at org.elasticsearch.xpack.core.transform.TransformConfigVersion.getTransformConfigVersionForNode(TransformConfigVersion.java:352)
  at org.elasticsearch.xpack.core.transform.TransformConfigVersion.fromNode(TransformConfigVersion.java:281)
  at org.elasticsearch.xpack.transform.transforms.TransformNodes.nodeCanRunThisTransform(TransformNodes.java:220)
  at org.elasticsearch.xpack.transform.transforms.TransformPersistentTasksExecutor.lambda$getAssignment$0(TransformPersistentTasksExecutor.java:134)
  at org.elasticsearch.persistent.PersistentTasksExecutor.selectLeastLoadedNode(PersistentTasksExecutor.java:69)
  at org.elasticsearch.xpack.transform.transforms.TransformPersistentTasksExecutor.getAssignment(TransformPersistentTasksExecutor.java:131)
  at org.elasticsearch.xpack.transform.transforms.TransformPersistentTasksExecutorTests.testNodeVersionAssignment(TransformPersistentTasksExecutorTests.java:67)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by droberts195** [comment]
Fixed by #98575.
