### ISSUE TITLE
JobUpdateTests.testMergeWithJob 

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#98626]
### CI Link

https://gradle-enterprise.elastic.co/s/o5szwywjimd6o/

### Repro line

./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.ml.job.config.JobUpdateTests.testMergeWithJob" -Dtests.seed=574F3B6BEFEFE6BA -Dtests.locale=ar-DZ -Dtests.timezone=Universal -Druntime.java=20

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
org.elasticsearch.xpack.core.ml.job.config.JobUpdateTests > testMergeWithJob FAILED
    java.lang.IllegalArgumentException: Cannot convert 8.11.0. Incompatible version
        at __randomizedtesting.SeedInfo.seed([574F3B6BEFEFE6BA:691D63E8F460F0FE]:0)
        at org.elasticsearch.xpack.core.ml.MlConfigVersion.fromVersion(MlConfigVersion.java:274)
        at org.elasticsearch.xpack.core.ml.job.config.JobUpdateTests.testMergeWithJob(JobUpdateTests.java:296)
```

With all these "versions" that we have now decoupled from transport version or node version, we need to ensure that all get bumped when a version bump occurs. There are too many of these things to not catch them in CI in a version bump for a cut release.

**Comment by droberts195** [comment]
@edsavage I suspect this failure was from the time when a "random ML config version" could include `Version.CURRENT`. If so that's fixed now, but the test is still muted. Please can you unmute it and close this issue.
