### ISSUE TITLE
Node is unable to join the cluster due to negative `version` in composable index template

### ISSUE THREAD

**Issue by romain-chanu** [elastic/elasticsearch#98652]
### Elasticsearch Version

8.9.1 

Note: problem was observed also in version 8.7.0. It is likely that older versions are affected by this problem.

### Java Version

_bundled_

### OS Version

N.A

### Problem Description

Users may report that a node is unable to join the cluster. The below warning message can be observed in the Elasticsearch logs:

```
[2023-08-21T04:24:51,202][WARN ][org.elasticsearch.cluster.coordination.Coordinator] [instance-0000000000] failed to validate incoming join request from node [{instance-0000000001}{63-KclayQUaMIz-leXvoAg}{lPanlM_3QcOBP8aw4jgDaA}{instance-0000000001}{XXX.XXX.XXX.XXX}{XXX.XXX.XXX.XXX:19837}{himrst}{8.9.1}{logical_availability_zone=zone-1, availability_zone=ap-southeast-1b, region=ap-southeast-1, instance_configuration=aws.es.datahot.i3.1.1, server_name=instance-0000000001.b3b02013757e4721ac9119e99d90cda1, data=hot, xpack.installed=true}]
java.lang.IllegalStateException: Negative longs unsupported, use writeLong or writeZLong for negative numbers [-3]
	at org.elasticsearch.common.io.stream.StreamOutput.writeVLong(StreamOutput.java:250) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalVLong(StreamOutput.java:260) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.metadata.ComposableIndexTemplate.writeTo(ComposableIndexTemplate.java:266) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.metadata.ComposableIndexTemplateMetadata.lambda$writeTo$2(ComposableIndexTemplateMetadata.java:100) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.io.stream.StreamOutput.writeMap(StreamOutput.java:625) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.metadata.ComposableIndexTemplateMetadata.writeTo(ComposableIndexTemplateMetadata.java:100) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:991) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.io.stream.VersionedNamedWriteable.writeVersionedWritables(VersionedNamedWriteable.java:63) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.metadata.Metadata.writeTo(Metadata.java:1687) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.ClusterState.writeTo(ClusterState.java:952) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.coordination.JoinValidationService.serializeClusterState(JoinValidationService.java:363) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.coordination.JoinValidationService$JoinValidation.lambda$doRun$0(JoinValidationService.java:316) ~[elasticsearch-8.9.1.jar:?]
	at java.util.Objects.requireNonNullElseGet(Objects.java:334) ~[?:?]
	at org.elasticsearch.cluster.coordination.JoinValidationService$JoinValidation.doRun(JoinValidationService.java:316) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.coordination.JoinValidationService.processNextItem(JoinValidationService.java:233) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.coordination.JoinValidationService$1.doRun(JoinValidationService.java:203) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.9.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

The above exception indicates an issue serialising composable index template information. Reviewing the composable index templates, we would find negative `version` in one or more templates.

Workaround would be to update the `version` to a positive value for all affected composable index templates.

### Steps to Reproduce

1) Create a cluster version 8.9.1 in Elasticsearch Service (ESS): single node, 1 availability zone (AZ)

2) Add a composable index template with a negative `version`:

```
PUT /_index_template/template_1
{
  "index_patterns" : ["te*"],
  "priority" : 1,
  "template": {
    "settings" : {
      "number_of_shards" : 2
    }
  },
  "version": -3
}
```

Notice that the API is successfully acknowledged.

3) Scale-up the cluster from 1 AZ to 2 AZ

4) Observe that the second node is unable to join the cluster. Checking the Elasticsearch logs, the below warning message can be observed:

```
[2023-08-21T04:24:51,202][WARN ][org.elasticsearch.cluster.coordination.Coordinator] [instance-0000000000] failed to validate incoming join request from node [{instance-0000000001}{63-KclayQUaMIz-leXvoAg}{lPanlM_3QcOBP8aw4jgDaA}{instance-0000000001}{XXX.XXX.XXX.XXX}{XXX.XXX.XXX.XXX:19837}{himrst}{8.9.1}{logical_availability_zone=zone-1, availability_zone=ap-southeast-1b, region=ap-southeast-1, instance_configuration=aws.es.datahot.i3.1.1, server_name=instance-0000000001.b3b02013757e4721ac9119e99d90cda1, data=hot, xpack.installed=true}]
java.lang.IllegalStateException: Negative longs unsupported, use writeLong or writeZLong for negative numbers [-3]
	at org.elasticsearch.common.io.stream.StreamOutput.writeVLong(StreamOutput.java:250) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalVLong(StreamOutput.java:260) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.metadata.ComposableIndexTemplate.writeTo(ComposableIndexTemplate.java:266) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.metadata.ComposableIndexTemplateMetadata.lambda$writeTo$2(ComposableIndexTemplateMetadata.java:100) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.io.stream.StreamOutput.writeMap(StreamOutput.java:625) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.metadata.ComposableIndexTemplateMetadata.writeTo(ComposableIndexTemplateMetadata.java:100) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:991) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.io.stream.VersionedNamedWriteable.writeVersionedWritables(VersionedNamedWriteable.java:63) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.metadata.Metadata.writeTo(Metadata.java:1687) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.ClusterState.writeTo(ClusterState.java:952) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.coordination.JoinValidationService.serializeClusterState(JoinValidationService.java:363) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.coordination.JoinValidationService$JoinValidation.lambda$doRun$0(JoinValidationService.java:316) ~[elasticsearch-8.9.1.jar:?]
	at java.util.Objects.requireNonNullElseGet(Objects.java:334) ~[?:?]
	at org.elasticsearch.cluster.coordination.JoinValidationService$JoinValidation.doRun(JoinValidationService.java:316) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.coordination.JoinValidationService.processNextItem(JoinValidationService.java:233) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.cluster.coordination.JoinValidationService$1.doRun(JoinValidationService.java:203) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.9.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.9.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

### Logs (if relevant)

c.f above

**Comment by dakrone** [comment]
I'm able to do this also, we should enforce that `version` cannot be negative in the API.

**Comment by predogma** [comment]
https://github.com/elastic/elasticsearch/pull/90319
