### ISSUE TITLE
tribe in es v.1.4.4 crashes when downstream cluster have problems

### ISSUE THREAD

**Issue by TinLe** [elastic/elasticsearch#9865]
This bug shows up in ES v1.4.4.   I reverted to running 1.4.3 and did not see this.   One of my downstream cluster suffered problems and the tribe node started hanging also, to where Kibana connecting to it timed out.

The logs were flooded with lines like these and the tribe node pretty much stopped responding.  If I shutdown it down and replaced with 1.4.3.   Then eventhough errors show in log, it still respond ok.

    [2015-02-24 22:46:17,814][DEBUG][action.admin.cluster.node.stats] [ela4-app11185.prod] failed to execute on node [qZDMHmpgR4qDW8SX7M3ppg]
    org.elasticsearch.transport.RemoteTransportException: [ltx1-app13285.prod][inet[/10.149.106.54:9300]][clu
    ster:monitor/nodes/stats[n]]
    Caused by: org.elasticsearch.ElasticsearchException: io exception while building 'store stats'
            at org.elasticsearch.index.shard.service.InternalIndexShard.storeStats(InternalIndexShard.java:542)
            at org.elasticsearch.action.admin.indices.stats.CommonStats.<init>(CommonStats.java:134)
            at org.elasticsearch.action.admin.indices.stats.ShardStats.<init>(ShardStats.java:49)

etc...

    [2015-02-24 22:46:17,953][DEBUG][action.admin.cluster.node.stats] [ela4-app11185.prod] failed to execute on node [zMwqY3NnR82BgSmdfeGEbQ]
    org.elasticsearch.transport.RemoteTransportException: [ltx1-app13578.prod][inet[/10.149.108.37:9300]][cluster:monitor/nodes/stats[n]]
    Caused by: org.elasticsearch.ElasticsearchException: io exception while building 'store stats'
            at org.elasticsearch.index.shard.service.InternalIndexShard.storeStats(InternalIndexShard.java:542)
            at org.elasticsearch.action.admin.indices.stats.CommonStats.<init>(CommonStats.java:134)
            at org.elasticsearch.action.admin.indices.stats.ShardStats.<init>(ShardStats.java:49)
            at org.elasticsearch.indices.InternalIndicesService.stats(InternalIndicesService.java:212)
            at org.elasticsearch.node.service.NodeService.stats(NodeService.java:156)
            at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:96)
            at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:44)
            at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$NodeTransportHandler.messageReceived(TransportNodesOperationAction.java:278)
            at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$NodeTransportHandler.messageReceived(TransportNodesOperationAction.java:269)
            at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.run(MessageChannelHandler.java:275)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:744)
    Caused by: java.io.IOException: directory '/export/content/data/data-elasticsearch/nodes/0/indices/abc-log_event-ltx1-2015.02.22/1/index' exists and is a directory, but cannot be listed: list() returned null
            at org.apache.lucene.store.FSDirectory.listAll(FSDirectory.java:231)
            at org.apache.lucene.store.FSDirectory.listAll(FSDirectory.java:242)
            at org.apache.lucene.store.FileSwitchDirectory.listAll(FileSwitchDirectory.java:87)
            at org.apache.lucene.store.FilterDirectory.listAll(FilterDirectory.java:48)
            at org.elasticsearch.index.store.DistributorDirectory.listAll(DistributorDirectory.java:88)
            at org.apache.lucene.store.FilterDirectory.listAll(FilterDirectory.java:48)
            at org.elasticsearch.common.lucene.Directories.estimateSize(Directories.java:40)
            at org.elasticsearch.index.store.Store.stats(Store.java:216)
            at org.elasticsearch.index.shard.service.InternalIndexShard.storeStats(InternalIndexShard.java:540)
            ... 12 more

etc.

I have the logs, it's fairly large and contain some internal data.  Let me know how you want me to get them to you.

**Comment by pickypg** [comment]
Hi @TinLe, can you clarify what you mean when you say that the tribe node is stopped responding?

> The logs were flooded with lines like these and the tribe node pretty much stopped responding.

- Were requests made against the tribe node not returning?
- Were they returning with an exception?
- Specific API calls (e.g., stats as shown above) were failing?
- All API calls were failing?
- Were all failures related to a specific cluster?

Thanks, let us know.

**Comment by TinLe** [comment]
The tribe does exactly as described :-).

. It stop responding to Kibana.  When I tried curl localhost:9200/_nodes/_local on node, it just hangs.   Eventually (30+ minutes, I went to get coffee, do something else), I control-c it :-}.

I posted part of the logs above (those are the common errors I was seeing).  I'd have to scrub it before putting entire log in public.

All API calls were failing, e.g. they all timed out or hang....   I ended up having to bounce tribe node each time, and it would be (maybe) useable for a bit before getting into a bad state again due to downstream cluster mis-behaving/sad.

These problems are due to one or more clusters.   No specific ones, although some clusters tend to "experience" more issues than others.   Due to internal policy, I do not have administrative control over all clusters.   But I do own the tribe nodes and am responsible for aggregating data from all clusters.

So I am caught between a rock and a very hard place.   I need tribe nodes to be highly resistant to misbehaving downstream clusters/nodes.   If a downstream clusters/nodes have issues, tribe should be able to skip/drop from list and check back later to see if that particular cluster or node has recovered.

**Comment by pickypg** [comment]
Well, in that case, let's figure out how to get us those logs. Can you DM me your email address on Twitter ([@pickypg](https://twitter.com/pickypg)) to avoid giving away either of emails to the lovely bots of the world.

We certainly also want to ensure that we are not creating problems for our Tribe clients out there.

**Comment by TinLe** [comment]
I have not had chance to get the logs together.   I'll do so soon.

I wonder if this is related to https://github.com/elastic/elasticsearch/issues/8677

**Comment by pickypg** [comment]
@TinLe Any luck on scrounging those logs together?

**Comment by TinLe** [comment]
Unfortunately I've gotten all my downstream to fix (and add monitoring to) their clusters, so have not seen this lately.

I do have one log from end of Feb that seem to show this problem.   Tried dm @pickypg on twitter, but since you're not following me, I am not allowed to dm you :-)

I'll send the log to you via another route.

**Comment by pickypg** [comment]
@TinLe I sent a follow request to you, assuming the same name. You can probably also guess my email address using my first.last name. :)

**Comment by TinLe** [comment]
@pickypg  I've submitted log file via your support site.  It's issue 10900.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/pull/13948 and https://github.com/elastic/elasticsearch/pull/14993
