### ISSUE TITLE
[CI] AsyncStatusResponseTests testGetStatusFromStoredSearchWithNonEmptyClustersStillRunning failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#98706]
**Build scan:**
https://gradle-enterprise.elastic.co/s/pylhm6bwnaqho/tests/:x-pack:plugin:async-search:test/org.elasticsearch.xpack.search.AsyncStatusResponseTests/testGetStatusFromStoredSearchWithNonEmptyClustersStillRunning

**Reproduction line:**
```
./gradlew ':x-pack:plugin:async-search:test' --tests "org.elasticsearch.xpack.search.AsyncStatusResponseTests.testGetStatusFromStoredSearchWithNonEmptyClustersStillRunning" -Dtests.seed=2E88581A39F42A0B -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=lt -Dtests.timezone=Asia/Qostanay -Druntime.java=20
```

**Applicable branches:**
8.10, main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.search.AsyncStatusResponseTests&tests.test=testGetStatusFromStoredSearchWithNonEmptyClustersStillRunning

**Failure excerpt:**
```
java.lang.AssertionError: successful + skipped + partial must be > 0

  at __randomizedtesting.SeedInfo.seed([2E88581A39F42A0B:8AE0F1A46BA14E5E]:0)
  at org.elasticsearch.xpack.search.AsyncSearchResponseTests.createCCSClusterObjects(AsyncSearchResponseTests.java:781)
  at org.elasticsearch.xpack.search.AsyncStatusResponseTests.testGetStatusFromStoredSearchWithNonEmptyClustersStillRunning(AsyncStatusResponseTests.java:414)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by thecoop** [comment]
Also fails on main ^^

**Comment by pmpailis** [comment]
In the specific test (`AsyncStatusResponseTests#testGetStatusFromStoredSearchWithNonEmptyClustersStillRunning`) we make use of 3 random integer generators with an upper bound of 10 (i.e. `randomInt(10)`), and subsequently there is an assertion that the sum of them must be > 0. 
So, it could happen, albeit not that often, that we might end up with 0 values for all. The assertion happens within a test class, when trying to create a `SearchResponse.Clusters` object through the `AsyncSearchResponseTests#createCCSClusterObjects`. 

This seems something specific to how the test is structured (and a recent refactor which introduced randomness), so I was thinking of adding some additional "noise" to one of the generators, in case they all end up being zero to avoid this edge case. (cc'ing @javanna  @quux00 )
