### ISSUE TITLE
[CI] InternalEngineTests testGetWithSearcherWrapper failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#98716]
**Build scan:**
https://gradle-enterprise.elastic.co/s/wyzblc2izfy4a/tests/:server:test/org.elasticsearch.index.engine.InternalEngineTests/testGetWithSearcherWrapper

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.index.engine.InternalEngineTests.testGetWithSearcherWrapper" -Dtests.seed=A7D30B8605DA9104 -Dtests.locale=sl -Dtests.timezone=Asia/Tehran -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.engine.InternalEngineTests&tests.test=testGetWithSearcherWrapper

**Failure excerpt:**
```
java.lang.AssertionError: The top-reader used to create Weight is not the same as the current reader's top-reader (LeafReaderContext(FieldUsageTrackingLeafReader(reader=FilterLeafReader(org.elasticsearch.index.engine.TranslogDirectoryReader$TranslogLeafReader@25ea4d4c)) docBase=0 ord=0)

  at __randomizedtesting.SeedInfo.seed([A7D30B8605DA9104:B93F2EC6EDE1FAC2]:0)
  at org.apache.lucene.search.TermQuery$TermWeight.scorer(TermQuery.java:105)
  at org.apache.lucene.search.Weight.scorerSupplier(Weight.java:136)
  at org.apache.lucene.tests.search.AssertingWeight.scorerSupplier(AssertingWeight.java:80)
  at org.apache.lucene.tests.search.AssertingWeight.scorer(AssertingWeight.java:66)
  at org.elasticsearch.index.engine.EngineTestCase$MatchingDirectoryReader$1.wrap(EngineTestCase.java:1519)
  at org.apache.lucene.index.FilterDirectoryReader$SubReaderWrapper.wrap(FilterDirectoryReader.java:61)
  at org.apache.lucene.index.FilterDirectoryReader.<init>(FilterDirectoryReader.java:91)
  at org.elasticsearch.index.engine.EngineTestCase$MatchingDirectoryReader.<init>(EngineTestCase.java:1512)
  at org.elasticsearch.index.engine.InternalEngineTests.lambda$testGetWithSearcherWrapper$9(InternalEngineTests.java:1105)
  at org.elasticsearch.index.shard.IndexShard.wrapSearcher(IndexShard.java:1590)
  at org.elasticsearch.index.shard.SearcherHelper.wrapSearcher(SearcherHelper.java:28)
  at org.elasticsearch.index.engine.InternalEngineTests.lambda$testGetWithSearcherWrapper$10(InternalEngineTests.java:1105)
  at org.elasticsearch.index.engine.InternalEngine.getFromTranslog(InternalEngine.java:784)
  at org.elasticsearch.index.engine.InternalEngine.realtimeGetUnderLock(InternalEngine.java:869)
  at org.elasticsearch.index.engine.InternalEngine.get(InternalEngine.java:799)
  at org.elasticsearch.index.engine.InternalEngineTests.testGetWithSearcherWrapper(InternalEngineTests.java:1101)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by kingherc** [comment]
Hi @idegtiarenko , after some tinkering, I realized that the old line of [this recent PR](https://github.com/elastic/elasticsearch/pull/98110/files#diff-27b094e6439598930f32fb39df2872b0b9fe4b7b2058ca019834ddaf6c5b0f8bL1516) makes the test work. That PR is from the Search team, and seeing that the error is search related, maybe the Search team would indeed be better to do (at least a first) investigation of this test failure.
