### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=tsdb/30_snapshot/Create a snapshot and then restore it} failing

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#98746]
**Build scan:**
https://gradle-enterprise.elastic.co/s/agzzu2tce5pl6/tests/:qa:mixed-cluster:v8.10.0%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=tsdb%2F30_snapshot%2FCreate%20a%20snapshot%20and%20then%20restore%20it%7D

**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v8.10.0#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=tsdb/30_snapshot/Create a snapshot and then restore it}" -Dtests.seed=265A30F7DFB9C9D0 -Dtests.bwc=true -Dtests.locale=pt-PT -Dtests.timezone=Asia/Karachi -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dtsdb/30_snapshot/Create%20a%20snapshot%20and%20then%20restore%20it%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [tsdb/30_snapshot:134]: 
Expected: "SNAPSHOT"
     but: was "PEER"

  at __randomizedtesting.SeedInfo.seed([265A30F7DFB9C9D0:AE0E0F2D7145A428]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:582)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:534)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.lang.AssertionError: 
  Expected: "SNAPSHOT"
       but: was "PEER"

    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.junit.Assert.assertThat(Assert.java:923)
    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:99)
    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:562)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:534)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by dakrone** [comment]
Not sure if this one is for TSDB specifically, or for snapshot and restore. Please redirect if so.

**Comment by kkrik-es** [comment]
I see the following error in the log:

```
» [2023-08-22T16:03:25,289][WARN ][o.e.c.s.IndexScopedSettings] [v8.10.0-0] [test_index] failed to apply settings java.lang.IllegalArgumentException: index.time_series.end_time must be larger than current value [1632625793000] but was [2021-09-26T03:09:52Z]
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.TimestampBounds.updateEndTime(TimestampBounds.java:23)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.IndexSettings.lambda$new$4(IndexSettings.java:844)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.settings.Setting$Updater.apply(Setting.java:1284)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:653)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:173)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.IndexSettings.updateIndexMetadata(IndexSettings.java:1134)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.IndexService.updateMetadata(IndexService.java:861)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.indices.IndicesService.verifyIndexMetadata(IndicesService.java:874)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataUpdateSettingsService$UpdateSettingsTask.execute(MetadataUpdateSettingsService.java:288)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataUpdateSettingsService.lambda$new$0(MetadataUpdateSettingsService.java:80)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1626)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:368)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1623)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1237)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:368)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1216)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
»  	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»  	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by kkrik-es** [comment]
Recovery stats report 2 entries for shard `ID: 1`, with type `PEER` and `SNAPSHOT`

```
1> [2023-08-22T21:00:44,694][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "test_index" : {
  1>         "shards" : [
  1>           {
  1>             "id" : 1,
  1>             "type" : "PEER",
  1>             "stage" : "INDEX",
  1>             "primary" : true,
  1>             "start_time_in_millis" : 1692720044674,
  1>             "total_time_in_millis" : 11,
  1>             "source" : {
  1>               "id" : "jrSoJ3x1Rae7TdRnJXmK0Q",
  1>               "host" : "127.0.0.1",
  1>               "transport_address" : "127.0.0.1:45019",
  1>               "ip" : "127.0.0.1",
  1>               "name" : "v8.10.0-3"
  1>             },
  1>             "target" : {
  1>               "id" : "8jFk5xSqQpevrUNIO53GAw",
  1>               "host" : "127.0.0.1",
  1>               "transport_address" : "127.0.0.1:46877",
  1>               "ip" : "127.0.0.1",
  1>               "name" : "v8.10.0-1"
  1>             },
  1>             "index" : {
  1>               "size" : {
  1>                 "total_in_bytes" : 10012,
  1>                 "reused_in_bytes" : 0,
  1>                 "recovered_in_bytes" : 10012,
  1>                 "recovered_from_snapshot_in_bytes" : 0,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "files" : {
  1>                 "total" : 4,
  1>                 "reused" : 0,
  1>                 "recovered" : 4,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "total_time_in_millis" : 7,
  1>               "source_throttle_time_in_millis" : 0,
  1>               "target_throttle_time_in_millis" : 0
  1>             },
  1>             "translog" : {
  1>               "recovered" : 0,
  1>               "total" : 0,
  1>               "percent" : "100.0%",
  1>               "total_on_start" : 0,
  1>               "total_time_in_millis" : 0
  1>             },
  1>             "verify_index" : {
  1>               "check_index_time_in_millis" : 0,
  1>               "total_time_in_millis" : 0
  1>             }
  1>           },
  1>           {
  1>             "id" : 0,
  1>             "type" : "SNAPSHOT",
  1>             "stage" : "DONE",
  1>             "primary" : true,
  1>             "start_time_in_millis" : 1692720044632,
  1>             "stop_time_in_millis" : 1692720044647,
  1>             "total_time_in_millis" : 14,
  1>             "source" : {
  1>               "repository" : "test_repo",
  1>               "snapshot" : "test_restore_tsdb",
  1>               "version" : "8110099",
  1>               "index" : "test_index",
  1>               "restoreUUID" : "4zEeqd1QQP2zOUPpWw8zzw"
  1>             },
  1>             "target" : {
  1>               "id" : "dU1nTC8WS-WGBY6UoOATiA",
  1>               "host" : "127.0.0.1",
  1>               "transport_address" : "127.0.0.1:46847",
  1>               "ip" : "127.0.0.1",
  1>               "name" : "v8.10.0-0"
  1>             },
  1>             "index" : {
  1>               "size" : {
  1>                 "total_in_bytes" : 8932,
  1>                 "reused_in_bytes" : 8601,
  1>                 "recovered_in_bytes" : 331,
  1>                 "recovered_from_snapshot_in_bytes" : 0,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "files" : {
  1>                 "total" : 4,
  1>                 "reused" : 3,
  1>                 "recovered" : 1,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "total_time_in_millis" : 7,
  1>               "source_throttle_time_in_millis" : 0,
  1>               "target_throttle_time_in_millis" : 0
  1>             },
  1>             "translog" : {
  1>               "recovered" : 0,
  1>               "total" : 0,
  1>               "percent" : "100.0%",
  1>               "total_on_start" : 0,
  1>               "total_time_in_millis" : 5
  1>             },
  1>             "verify_index" : {
  1>               "check_index_time_in_millis" : 0,
  1>               "total_time_in_millis" : 0
  1>             }
  1>           },
  1>           {
  1>             "id" : 1,
  1>             "type" : "SNAPSHOT",
  1>             "stage" : "DONE",
  1>             "primary" : true,
  1>             "start_time_in_millis" : 1692720044643,
  1>             "stop_time_in_millis" : 1692720044663,
  1>             "total_time_in_millis" : 20,
  1>             "source" : {
  1>               "repository" : "test_repo",
  1>               "snapshot" : "test_restore_tsdb",
  1>               "version" : "8110099",
  1>               "index" : "test_index",
  1>               "restoreUUID" : "4zEeqd1QQP2zOUPpWw8zzw"
  1>             },
  1>             "target" : {
  1>               "id" : "jrSoJ3x1Rae7TdRnJXmK0Q",
  1>               "host" : "127.0.0.1",
  1>               "transport_address" : "127.0.0.1:45019",
  1>               "ip" : "127.0.0.1",
  1>               "name" : "v8.10.0-3"
  1>             },
  1>             "index" : {
  1>               "size" : {
  1>                 "total_in_bytes" : 10012,
  1>                 "reused_in_bytes" : 9681,
  1>                 "recovered_in_bytes" : 331,
  1>                 "recovered_from_snapshot_in_bytes" : 0,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "files" : {
  1>                 "total" : 4,
  1>                 "reused" : 3,
  1>                 "recovered" : 1,
  1>                 "percent" : "100.0%"
  1>               },
  1>               "total_time_in_millis" : 11,
  1>               "source_throttle_time_in_millis" : 0,
  1>               "target_throttle_time_in_millis" : 0
  1>             },
  1>             "translog" : {
  1>               "recovered" : 0,
  1>               "total" : 0,
  1>               "percent" : "100.0%",
  1>               "total_on_start" : 0,
  1>               "total_time_in_millis" : 5
  1>             },
  1>             "verify_index" : {
  1>               "check_index_time_in_millis" : 0,
  1>               "total_time_in_millis" : 0
  1>             }
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
```

**Comment by kkrik-es** [comment]
Since there's no tsdb-specific logic for snapshot handling, assigning to Distributed team to check this case and advise.

**Comment by kkrik-es** [comment]
Synced offline with @DaveCTurner, he suggested replacing the existing matches on recovery stats output with a simple search, to avoid flakiness. Another option is to use `cluster.routing.rebalance.enable: none` to avoid shard relocation.
