### ISSUE TITLE
[CI] ILMDownsampleDisruptionIT testILMDownsampleRollingRestart failing

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#98764]
**Build scan:**
https://gradle-enterprise.elastic.co/s/lxzpondgso46i/tests/:x-pack:plugin:downsample:internalClusterTest/org.elasticsearch.xpack.downsample.ILMDownsampleDisruptionIT/testILMDownsampleRollingRestart

**Reproduction line:**
```
./gradlew ':x-pack:plugin:downsample:internalClusterTest' --tests "org.elasticsearch.xpack.downsample.ILMDownsampleDisruptionIT.testILMDownsampleRollingRestart" -Dtests.seed=9A70BD78ACFA595F -Dtests.locale=et -Dtests.timezone=America/Monterrey -Druntime.java=20
```

**Applicable branches:**
main, 8.10

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.downsample.ILMDownsampleDisruptionIT&tests.test=testILMDownsampleRollingRestart

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertTrue(Assert.java:52)
  at org.elasticsearch.xpack.downsample.ILMDownsampleDisruptionIT.assertTargetIndex(ILMDownsampleDisruptionIT.java:240)
  at org.elasticsearch.xpack.downsample.ILMDownsampleDisruptionIT.testILMDownsampleRollingRestart(ILMDownsampleDisruptionIT.java:198)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by martijnvg** [comment]
Looking at this instance of this test failure:

The downsample operation did complete successfully: https://gradle-enterprise.elastic.co/s/3lzoqq2wpuzui

```
[2023-08-25T03:12:12,960][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t2] Downsampling task [downsample-downsample-1h-vlmuwkgdam-0-1h on shard [vlmuwkgdam][0] completed
[2023-08-25T03:12:13,018][INFO ][o.e.x.d.TransportDownsampleAction] [node_t0] Downsampling task [downsample-downsample-1h-vlmuwkgdam-0-1h completed for shard [vlmuwkgdam][0]
```

However trying apply the ilm policy to index failed. First it timed out by timeout set in the test and then it failed a number times setting ilm policy on the source index: 

```
java.lang.AssertionError: [vlmuwkgdam] org.elasticsearch.index.IndexNotFoundException: no such index [vlmuwkgdam]	
at __randomizedtesting.SeedInfo.seed([998130E8FEE9BB3:BFF7A4A7A1F485A6]:0)	
at org.elasticsearch.xpack.downsample.ILMDownsampleDisruptionIT.lambda$startDownsampleTaskViaIlm$4(ILMDownsampleDisruptionIT.java:218)	
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1172)	
at org.elasticsearch.xpack.downsample.ILMDownsampleDisruptionIT.startDownsampleTaskViaIlm(ILMDownsampleDisruptionIT.java:213)	
at org.elasticsearch.xpack.downsample.ILMDownsampleDisruptionIT.testILMDownsampleRollingRestart(ILMDownsampleDisruptionIT.java:196)	
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)	
at java.lang.reflect.Method.invoke(Method.java:577)
```

This is a test issue. The index was downsampled and no longer exists. We need to check the existence of the source index and if not longer exists, assume that ilm has cleaned it up.

**Comment by martijnvg** [comment]
Looking at the failure history this test didn't fail anymore after the test fixes were merged.
