### ISSUE TITLE
[CI] ClusterSettingsUpdateWithFaultyMasterIT testClusterSettingsUpdateNotAcknowledged failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#98918]
**Build scan:**
https://gradle-enterprise.elastic.co/s/63ypxmt53q6gc/tests/:server:internalClusterTest/org.elasticsearch.cluster.settings.ClusterSettingsUpdateWithFaultyMasterIT/testClusterSettingsUpdateNotAcknowledged

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.settings.ClusterSettingsUpdateWithFaultyMasterIT.testClusterSettingsUpdateNotAcknowledged" -Dtests.seed=20EF8EE69CC7EA19 -Dtests.locale=sv-SE -Dtests.timezone=Etc/GMT+10 -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.cluster.settings.ClusterSettingsUpdateWithFaultyMasterIT&tests.test=testClusterSettingsUpdateNotAcknowledged

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([20EF8EE69CC7EA19]:0)

```

**Comment by rjernst** [comment]
Another instance today:
https://gradle-enterprise.elastic.co/s/kh5d7qbojosoo

The test has a latch which it waits for. The latch is counted down when setting validators are run. It appears that some scenario can cause validators not not run, causing the latch to never count down, and the test to timeout.

**Comment by stu-elastic** [comment]
Another instance today: https://gradle-enterprise.elastic.co/s/7uw56jf5h3nfq

**Comment by idegtiarenko** [comment]
There was a new failure they logged:
```
[2023-10-19T21:02:00,687][DEBUG][o.e.a.a.c.s.TransportClusterUpdateSettingsAction] [node_t0] failed to perform [cluster_update_settings] org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (cluster_update_settings) within 10ms 
at org.elasticsearch.cluster.service.MasterService$TaskTimeoutHandler.doRun(MasterService.java:1460) ~[main/:?] 
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[main/:?] 
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[main/:?] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] 
at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
