### ISSUE TITLE
[CI] DataStreamLifecycleServiceIT testDataLifecycleServiceConfiguresTheMergePolicy failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#99017]
**Build scan:**
https://gradle-enterprise.elastic.co/s/m6vwwbilobl42/tests/:modules:data-streams:internalClusterTest/org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT/testDataLifecycleServiceConfiguresTheMergePolicy

**Reproduction line:**
```
gradlew ':modules:data-streams:internalClusterTest' --tests "org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT.testDataLifecycleServiceConfiguresTheMergePolicy" -Dtests.seed=BD586B218C23751B -Dtests.locale=be-BY -Dtests.timezone=America/Sitka -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT&tests.test=testDataLifecycleServiceConfiguresTheMergePolicy

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is "5"
     but: was "16"

  at __randomizedtesting.SeedInfo.seed([BD586B218C23751B:26A50C09B2AACE67]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT.lambda$testDataLifecycleServiceConfiguresTheMergePolicy$17(DataStreamLifecycleServiceIT.java:653)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1172)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1145)
  at org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT.testDataLifecycleServiceConfiguresTheMergePolicy(DataStreamLifecycleServiceIT.java:650)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by masseyke** [comment]
I think I see a couple of problems here:

- It's making this assertion on the second generation index, but it appears to be getting the first-gen index: `String secondGenerationIndex = DataStream.getDefaultBackingIndexName(dataStreamName, 1L);`
- Even if it was getting the right generation, we can't get index names like that because it fails if the test runs over midnight.

I wondered why the assertion made on the first generation index succeeds most of the time, but fails every onece in a while. It looks like it would only fail if the first generation index had been force merged before the `data_streams.lifecycle.target.merge.policy.merge_factor` was set to 5. And it looks like that happened in this case. I _think_ we'll be OK if this assertion is made on the intended index (the 2nd one) because it will not have had an opportunity to be force merged. All of the failures in the failure history are on windows (excluding the ones that I just caused locally). I don't know why force merge would be more likely to complete quickly on windows (or maybe settings updates take longer on windows?).

**Comment by cbuescher** [comment]
I've got a failure just like this on the 8.10 branch today. Was the fix backported? 
https://gradle-enterprise.elastic.co/s/bnzlrhkehewni
