### ISSUE TITLE
Scanning and scrolling exceptions

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#9906]
For certain scenarios, scanning/scrolling queries can trigger low-level exceptions probably in cases the scrolling id expired.

```
org.elasticsearch.ElasticsearchParseException: failed to parse / load source
	at org.elasticsearch.search.lookup.SourceLookup.loadSourceIfNeeded(SourceLookup.java:81)
	at org.elasticsearch.search.lookup.SourceLookup.filter(SourceLookup.java:145)
	at org.elasticsearch.search.fetch.source.FetchSourceSubPhase.hitExecute(FetchSourceSubPhase.java:77)
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:211)
	at org.elasticsearch.search.SearchService.executeScan(SearchService.java:247)
	at org.elasticsearch.search.action.SearchServiceTransportAction$21.call(SearchServiceTransportAction.java:520)
	at org.elasticsearch.search.action.SearchServiceTransportAction$21.call(SearchServiceTransportAction.java:517)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: docID must be >= 0 and < maxDoc=15095 (got docID=-1)
	at org.apache.lucene.index.SegmentReader.checkBounds(SegmentReader.java:376)
	at org.apache.lucene.index.SegmentReader.document(SegmentReader.java:334)
	at org.elasticsearch.search.lookup.SourceLookup.loadSourceIfNeeded(SourceLookup.java:70)
	... 10 more
```

Another one:

```
org.elasticsearch.transport.RemoteTransportException: [test][inet[/10.10.10.10:9300]][indices:data/read/search[phase/scan/scroll]]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.search.fetch.source.FetchSourceSubPhase.hitExecute(FetchSourceSubPhase.java:79)
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:211)
	at org.elasticsearch.search.SearchService.executeScan(SearchService.java:247)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchScanScrollTransportHandler.messageReceived(SearchServiceTransportAction.java:939)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchScanScrollTransportHandler.messageReceived(SearchServiceTransportAction.java:930)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.run(MessageChannelHandler.java:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Another one:

```
[2015-02-24 17:27:18,213][DEBUG][action.search.type ] [Search 12] [959835] Failed to execute query phase 
org.elasticsearch.transport.RemoteTransportException: [Search 03][inet[/10.10.10.10:9300]][indices:data/read/search[phase/scan/scroll]] 
Caused by: java.lang.NullPointerException 
at org.elasticsearch.search.internal.InternalSearchHits.writeTo(InternalSearchHits.java:259) 
at org.elasticsearch.search.fetch.FetchSearchResult.writeTo(FetchSearchResult.java:104) 
at org.elasticsearch.search.fetch.QueryFetchSearchResult.writeTo(QueryFetchSearchResult.java:95) 
at org.elasticsearch.search.fetch.ScrollQueryFetchSearchResult.writeTo(ScrollQueryFetchSearchResult.java:68) 
at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:91) 
at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:68) 
at org.elasticsearch.search.action.SearchServiceTransportAction$SearchScanScrollTransportHandler.messageReceived(SearchServiceTransportAction.java:940) 
at org.elasticsearch.search.action.SearchServiceTransportAction$SearchScanScrollTransportHandler.messageReceived(SearchServiceTransportAction.java:930) 
at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.run(MessageChannelHandler.java:275) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at java.lang.Thread.run(Thread.java:745)
```

**Comment by martijnvg** [comment]
An expired scroll id should trigger a different error. Is this issue easily reproducible? and on what version did you encounter these errors?

**Comment by astefan** [comment]
Not easily reproduceable, heavy searching with scrolling scenario is needed for this. ES 1.4.1.

**Comment by clintongormley** [comment]
@astefan Can you show us the actual code that you're using here?  If you're able to provide a working recreation, even better.

**Comment by clintongormley** [comment]
Hi @astefan 

What version of Elasticsearch are you using? Are you using any parent/child or nested queries?  How about a stack trace from the logs where you get the NPE?

We don't have enough information to investigate any further at the moment.

**Comment by ishare** [comment]
got the same err in 1.5.1, is there any idea?

java.lang.IndexOutOfBoundsException: docID must be >= 0 and < maxDoc=1 (got docID=2147483647)
	at org.apache.lucene.index.SegmentReader.checkBounds(SegmentReader.java:376)
	at org.apache.lucene.index.SegmentReader.document(SegmentReader.java:334)
	at org.elasticsearch.search.fetch.FetchPhase.loadStoredFields(FetchPhase.java:407)
	at org.elasticsearch.search.fetch.FetchPhase.createSearchHit(FetchPhase.java:217)
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:182)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:501)
	at org.elasticsearch.search.action.SearchServiceTransportAction$17.call(SearchServiceTransportAction.java:452)
	at org.elasticsearch.search.action.SearchServiceTransportAction$17.call(SearchServiceTransportAction.java:449)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by nik9000** [comment]
Without at least the query you are scrolling this is going to be hard to
debug. The mapping and some example documents would help too.

**Comment by ishare** [comment]
Solved, I found there is exception in native script which cause this problem.

**Comment by q11112345** [comment]
@ishare  ive got the same problem, can you show the details in your script? maybe i can solve mine.

**Comment by haochun** [comment]
@ishare what exception did you found?i occurred the same exception.but,i am use function_score query,not scan.my query dsl is:

`{
  "size": 10,
  "query": {
    "function_score": {
      "functions": [
        {
          "script_score": {
            "lang": "groovy",
            "script": "_score * log(doc['cited'].value)"
          }
        }
      ],
      "query": {
        "filtered": {
          "query": {
            "query_string": {
              "analyzer": "query_ansj",
              "query": "曾彪",
              "fields": [
                "title^10.0",
                "keywords^6.0",
                "summary^1.0",
                "authors^2.0"
              ]
            }
          }
        }
      }
    }
  },
  "from": 90,
  "sort": []
}`

**Comment by haochun** [comment]
the response
`
{
"took": 8,
"timed_out": false,
"_shards": {
"total": 12,
"successful": 11,
"failed": 1,
"failures": [
{
"index": "meta",
"shard": 2,
"status": 500,
"reason": "IndexOutOfBoundsException[docID must be >= 0 and < maxDoc=25371497 (got docID=2147483647)]"
}
]
},
"hits": {
"total": 208,
"max_score": 8.523983,
"hits": [ ]
}
}
`

**Comment by haochun** [comment]
sorry,i found the cause.it it my fault.the doc['cited'] maybe zero.

**Comment by ishare** [comment]
@haochun this error always due to an exception, and the error msg is not quite obviously.
