### ISSUE TITLE
The primary elasticsearch fragment falls out of the cluster

### ISSUE THREAD

**Issue by liyale123** [elastic/elasticsearch#99075]
### Elasticsearch Version

8.8.0

### Java Version

_bundled_

### OS Version

centos7

### Problem Description

elasticsearch集群突然变为red状态，没有任何节点离开集群，但是有两个主分片无法分配。

### Steps to Reproduce

1. 用GET _cluster/allocation/explain?pretty查看原因，报一下错误：
  "unassigned_info": {
    "reason": "MANUAL_ALLOCATION",
    "at": "2023-08-31T02:36:31.950Z",
    "details": """failed shard on node [DzO7X99_TRaiKhp2-goxGQ]: shard failure, reason [refresh failed source[schedule]], failure org.apache.lucene.index.CorruptIndexException: Problem reading index from store(ByteSizeCachingDirectory(HybridDirectory@/data6/es_data/node-224160-19206/indices/fd2A-Ih2Tk29px_cc3KKFA/0/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@1ce02c39)) (resource=store(ByteSizeCachingDirectory(HybridDirectory@/data6/es_data/node-224160-19206/indices/fd2A-Ih2Tk29px_cc3KKFA/0/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@1ce02c39)))
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:164)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:92)
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:180)
	at org.apache.lucene.index.ReadersAndUpdates.getLatestReader(ReadersAndUpdates.java:245)
	at org.apache.lucene.index.SoftDeletesRetentionMergePolicy.keepFullyDeletedSegment(SoftDeletesRetentionMergePolicy.java:81)
	at org.apache.lucene.index.FilterMergePolicy.keepFullyDeletedSegment(FilterMergePolicy.java:118)
	at org.apache.lucene.index.FilterMergePolicy.keepFullyDeletedSegment(FilterMergePolicy.java:118)
	at org.apache.lucene.index.ReadersAndUpdates.keepFullyDeletedSegment(ReadersAndUpdates.java:827)
	at org.apache.lucene.index.IndexWriter.isFullyDeleted(IndexWriter.java:5976)
	at org.apache.lucene.index.IndexWriter.publishFlushedSegment(IndexWriter.java:2867)
	at org.apache.lucene.index.IndexWriter.lambda$publishFlushedSegments$24(IndexWriter.java:5817)
	at org.apache.lucene.index.DocumentsWriterFlushQueue.innerPurge(DocumentsWriterFlushQueue.java:119)
	at org.apache.lucene.index.DocumentsWriterFlushQueue.tryPurge(DocumentsWriterFlushQueue.java:150)
	at org.apache.lucene.index.DocumentsWriter.purgeFlushTickets(DocumentsWriter.java:189)
	at org.apache.lucene.index.IndexWriter.publishFlushedSegments(IndexWriter.java:5793)
	at org.apache.lucene.index.IndexWriter$1.afterSegmentsFlushed(IndexWriter.java:431)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:538)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:671)
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:570)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:381)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:355)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:345)
	at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:112)
	at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:170)
	at org.elasticsearch.index.engine.ElasticsearchReaderManager.refreshIfNeeded(ElasticsearchReaderManager.java:48)
	at org.elasticsearch.index.engine.ElasticsearchReaderManager.refreshIfNeeded(ElasticsearchReaderManager.java:27)
	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:167)
	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:240)
	at org.elasticsearch.index.engine.InternalEngine$ExternalReaderManager.refreshIfNeeded(InternalEngine.java:404)
	at org.elasticsearch.index.engine.InternalEngine$ExternalReaderManager.refreshIfNeeded(InternalEngine.java:384)
	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:167)
	at org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:213)
	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1901)
	at org.elasticsearch.index.engine.InternalEngine.maybeRefresh(InternalEngine.java:1878)
	at org.elasticsearch.index.shard.IndexShard.scheduledRefresh(IndexShard.java:3767)
	at org.elasticsearch.index.IndexService.maybeRefreshEngine(IndexService.java:936)
	at org.elasticsearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:1062)
	at org.elasticsearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:134)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1623)
Caused by: java.io.FileNotFoundException: No sub-file with id .kdi found in compound file "_7e.cfs" (fileName=_7e.kdi files: [_Lucene90_0.dvm, .fnm, .fdm, .fdx, _Lucene90_0.dvd, .fdt])
	at org.apache.lucene.codecs.lucene90.Lucene90CompoundReader.openInput(Lucene90CompoundReader.java:170)
	at org.apache.lucene.codecs.lucene90.Lucene90PointsReader.<init>(Lucene90PointsReader.java:63)
	at org.apache.lucene.codecs.lucene90.Lucene90PointsFormat.fieldsReader(Lucene90PointsFormat.java:74)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:151)
	... 41 more
""",
    "last_allocation_status": "no_valid_shard_copy"
  },
  "can_allocate": "no_valid_shard_copy",
  "allocate_explanation": "Elasticsearch can't allocate this shard because all the copies of its data in the cluster are stale or corrupt. Elasticsearch will allocate this shard when a node containing a good copy of its data joins the cluster. If no such node is available, restore this index from a recent snapshot.",

2. 用POST /_cluster/reroute?retry_failed=true  和  POST _cluster/reroute?retry_failed&metric=none还是解决不了该问题。这是bug吗？

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Please also see the [section of the manual on troubleshooting corruptions](https://www.elastic.co/guide/en/elasticsearch/reference/current/corruption-troubleshooting.html).

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by DaveCTurner** [comment]
> `Caused by: java.io.FileNotFoundException: No sub-file with id .kdi found in compound file "_7e.cfs" (fileName=_7e.kdi files: [_Lucene90_0.dvm, .fnm, .fdm, .fdx, _Lucene90_0.dvd, .fdt])`

Hmm sorry I take it back, this seems unlikely to be a hardware-related corruption. Reopening this.

**Comment by liyale123** [comment]
> Thanks very much for your interest in Elasticsearch.
> 
> This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
> 
> Please also see the [section of the manual on troubleshooting corruptions](https://www.elastic.co/guide/en/elasticsearch/reference/current/corruption-troubleshooting.html).
> 
> There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you very much for your response, I intend to delete this index first and restore from the snapshot to this cluster

**Comment by benwtrent** [comment]
🤔 

The only change recently to the compound file reader/writer: https://github.com/apache/lucene/commit/f45e0963040f8a7d23be3751b07b490d480782e9

@liyale123 was this a freshly installed 8.8.0 cluster or upgraded from a previous version?

**Comment by liyale123** [comment]
@benwtrent    It was upgraded from another version, but there was no problem after the upgrade, this happened in the last day or two.

**Comment by caolix** [comment]
问题最终解决了吗，是通过升级版本解决的吗？

**Comment by caolix** [comment]
@liyale123 看到麻烦回复一下，谢谢
