### ISSUE TITLE
Failed Serialization of Scripted Geo fields 

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#99089]
### Elasticsearch Version

8.7

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

In a multi-node cluster with multiple shards it is not possible to use scripted geo fields.
It fails with:
```
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "can not write type [class org.elasticsearch.common.geo.GeoBoundingBox]"
        }
```

### Steps to Reproduce

In a multi node cluster, create an index with more than 1 shard:
```
PUT /test-geo/
{
  "settings": { "number_of_shards": 2},
  "mappings": { "properties": { "geo_shape" : { "type": "geo_shape" }}}
}
```
Index a few shapes to it so that both shards are populated:
```
POST /test-geo/_doc/
{
  "geo_shape": "POLYGON((24.04725 59.942,24.04825 59.94125,24.04875 59.94125,24.04875 59.94175,24.048 59.9425,24.0475 59.94275,24.0465 59.94225,24.046 59.94225,24.04575 59.9425,24.04525 59.94225,24.04725 59.942))"
}
```

Then search with:
```
GET /test-geo/_search
{
  "script_fields": {
    "bbox": {
      "script": { "source": "doc['geo_shape'].getBoundingBox()" }
    }
  }
}
```

The non-local shard will fail.

**Comment by craigtaverner** [comment]
I've manually reproduced this by running a local 2-node cluster using `gradle run` with a custom config. The server console conveniently dumps a stack trace, which I'll investigate:

```
java.lang.IllegalArgumentException: can not write type [class org.elasticsearch.common.geo.GeoBoundingBox]
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:837)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1053)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.document.DocumentField.writeTo(DocumentField.java:116)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.search.SearchHit.lambda$writeTo$1(SearchHit.java:267)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeMap(StreamOutput.java:625)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.search.SearchHit.writeTo(SearchHit.java:267)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.lambda$writeArray$33(StreamOutput.java:954)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeArray(StreamOutput.java:931)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeArray(StreamOutput.java:954)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.search.SearchHits.writeTo(SearchHits.java:101)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.search.fetch.FetchSearchResult.writeTo(FetchSearchResult.java:52)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.OutboundMessage.serialize(OutboundMessage.java:70)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:185)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.OutboundHandler.sendResponse(OutboundHandler.java:139)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:61)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:42)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.lambda$onResponse$0(ChannelActionListener.java:31)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:368)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:31)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:19)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:1212)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:51)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:48)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:73)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by craigtaverner** [comment]
The core problem is that the painless scripting was provided the function `getBoundingBox()` in https://github.com/elastic/elasticsearch/pull/72886 which provided support for rendering the BoundingBox as a map of maps, but this only works for the final result in JSON. The inter-node communication appears to use a different serialization, and `GeoBoundingBox` is not supported. There appear to be several ways to support this, so I'll investigate the best option.
