### ISSUE TITLE
how to access data using kibana from elastic search cluster with 3 nodes

### ISSUE THREAD

**Issue by jilson-johnson** [elastic/elasticsearch#99118]
When i tried to install kibana getting a warning.

elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.server@8.9.1/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:729)
        at org.elasticsearch.server@8.9.1/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:419)
        at org.elasticsearch.server@8.9.1/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:761)
        at org.elasticsearch.server@8.9.1/org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:513)
        at org.elasticsearch.server@8.9.1/org.elasticsearch.action.search.AbstractSearchAsyncAction.performPhaseOnShard(AbstractSearchAsyncAction.java:327)

**Comment by original-brownbear** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
