### ISSUE TITLE
[CI] MoreExpressionIT testSpecialValueVariable failing

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#99156]
**Build scan:**
https://gradle-enterprise.elastic.co/s/tvr734jx3dias/tests/:modules:lang-expression:internalClusterTest/org.elasticsearch.script.expression.MoreExpressionIT/testSpecialValueVariable

**Reproduction line:**
```
./gradlew ':modules:lang-expression:internalClusterTest' --tests "org.elasticsearch.script.expression.MoreExpressionIT.testSpecialValueVariable" -Dtests.seed=C179C96877ADAAFF -Dtests.locale=nb -Dtests.timezone=Europe/Saratov -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.script.expression.MoreExpressionIT&tests.test=testSpecialValueVariable

**Failure excerpt:**
```
java.lang.AssertionError: expected:<0.7> but was:<0.299999976158142>

  at __randomizedtesting.SeedInfo.seed([C179C96877ADAAFF:893068755394F34B]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:553)
  at org.junit.Assert.assertEquals(Assert.java:683)
  at org.elasticsearch.script.expression.MoreExpressionIT.testSpecialValueVariable(MoreExpressionIT.java:496)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by thecoop** [comment]
This does fail reliably with test seed `C179C96877ADAAFF`

**Comment by thecoop** [comment]
So, this is an odd one...

Looks like the test only works coincidentally. What is happening is that the source values are getting mixed up, leading to either the smallest or the largest values getting dropped.

In [ExpressionAggregationScript](https://github.com/thecoop/elasticsearch/blob/12ad399c488f0cc60e19b5e1b29c6d569cb4351a/modules/lang-expression/src/main/java/org/elasticsearch/script/expression/ExpressionAggregationScript.java#L86) each script value is set from each doc, but it's being set _on the same instance_. This value is then re-used when running the script. The exact order each doc is executed affects the outcome.

Execution that succeeds:

	Set 10.0 on ReplaceableConstDoubleValueSource2096606171
	Set 13.0 on ReplaceableConstDoubleValueSource2096606171
	Read 39.0
	Read 39.0
	Set 5.0 on ReplaceableConstDoubleValueSource2096606171
	Read 15.0

Execution that fails:

	Set 13.0 on ReplaceableConstDoubleValueSource984741442
	Set 10.0 on ReplaceableConstDoubleValueSource984741442
	Read 30.0
	Read 30.0
	Set 5.0 on ReplaceableConstDoubleValueSource984741442
	Read 15.0

@stu-elastic Is it meant to be re-using instances like this? Or is there something about the async execution that is incorrect?

**Comment by thecoop** [comment]
Looks like the threading has changed - it passes reliably on 8.10, with the following traces:

	Set 5.0 on ReplaceableConstDoubleValueSource2005362459
	Read 15.0
	Set 10.0 on ReplaceableConstDoubleValueSource2005362459
	Read 30.0
	Set 13.0 on ReplaceableConstDoubleValueSource2005362459
	Read 39.0

**Comment by thecoop** [comment]
A bisect points towards #98567 causing this behaviour change - the concurrency has changed

**Comment by thecoop** [comment]
@javanna @JVerwolf Is this just another test that needs marking as non-concurrent? Does this point to a deeper problem somewhere?

**Comment by JVerwolf** [comment]
I created https://github.com/elastic/elasticsearch/pull/99203 to disable concurrency for this test so that we don't have flakey test runs.

We may want to keep this issue open for fixing the underlying cause, however.

**Comment by davidkyle** [comment]
Another failure https://gradle-enterprise.elastic.co/s/hzzgrag4rxslk/tests/task/:modules:lang-expression:internalClusterTest/details/org.elasticsearch.script.expression.MoreExpressionIT/testSpecialValueVariable?top-execution=1

**Comment by luigidellaquila** [comment]
One more failure today. 
I was about to mute this test, but I see there is https://github.com/elastic/elasticsearch/pull/99203 in progress. 
cc. @JVerwolf
