### ISSUE TITLE
[CI] PackageUpgradeTests test20InstallUpgradedVersion failing

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#99179]
**Build scan:**
https://gradle-enterprise.elastic.co/s/mfalpmksfx4kq/tests/:qa:os:destructiveDistroUpgradeTest.v8.10.0.default-deb/org.elasticsearch.packaging.test.PackageUpgradeTests/test20InstallUpgradedVersion

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.PackageUpgradeTests&tests.test=test20InstallUpgradedVersion

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: "file/directory: "<File> with owner "root" with group "root" with posix permissions [<OWNER_READ>,<OWNER_WRITE>,<GROUP_READ>,<OTHERS_READ>]
     but: path </usr/share/elasticsearch/NOTICE.txt>Has permissions [GROUP_READ, GROUP_WRITE, OTHERS_READ, OWNER_READ, OWNER_WRITE]

  at __randomizedtesting.SeedInfo.seed([66E7CE269B388551:3A784239A7AC3AAA]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  at org.elasticsearch.packaging.util.Packages.lambda$verifyOssInstallation$12(Packages.java:214)
  at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
  at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
  at org.elasticsearch.packaging.util.Packages.verifyOssInstallation(Packages.java:214)
  at org.elasticsearch.packaging.util.Packages.verifyPackageInstallation(Packages.java:176)
  at org.elasticsearch.packaging.test.PackageUpgradeTests.test20InstallUpgradedVersion(PackageUpgradeTests.java:102)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by mark-vieira** [comment]
This was resolved by https://github.com/elastic/elasticsearch/pull/99206
