### ISSUE TITLE
Percentile Null values leading to Null Pointer Exception

### ISSUE THREAD

**Issue by rhaegar151** [elastic/elasticsearch#99186]
### Elasticsearch Version

8.9.0

### Java Version

8

### OS Version

linux 15

### Problem Description

I'm working on migrating High Level Rest Client to the new Java Api Client. I'm trying to run percentile aggregations over some data, it works fine if the data is present but when no data is present, it is supposed to return null values in the response, but it breaks when being processed by the Jackson Mapper class. keyed parameter can be set to false to get default value as 0 for the null cases but the response generated is very different and we want to stick to the response generated when keyed parameter is set to true. 

Stack Trace:

java.lang.NullPointerException: null
	at org.eclipse.parsson.JsonGeneratorImpl.writeEscapedString(JsonGeneratorImpl.java:539) ~[parsson-1.0.0.jar:na]
	at org.eclipse.parsson.JsonGeneratorImpl.write(JsonGeneratorImpl.java:359) ~[parsson-1.0.0.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.Percentiles.serialize(Percentiles.java:145) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.PercentilesAggregateBase.serializeInternal(PercentilesAggregateBase.java:71) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.AggregateBase.serialize(AggregateBase.java:75) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.json.JsonpMapperBase$JsonpSerializableSerializer.serialize(JsonpMapperBase.java:122) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.json.JsonpMapperBase$JsonpSerializableSerializer.serialize(JsonpMapperBase.java:119) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.json.SimpleJsonpMapper.serialize(SimpleJsonpMapper.java:111) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.Aggregate.serialize(Aggregate.java:1486) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.json.ExternallyTaggedUnion.serializeTypedKeysInner(ExternallyTaggedUnion.java:243) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.json.ExternallyTaggedUnion.serializeTypedKeys(ExternallyTaggedUnion.java:187) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.elasticsearch.core.search.ResponseBody.serializeInternal(ResponseBody.java:252) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.elasticsearch.core.search.ResponseBody.serialize(ResponseBody.java:232) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:408) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:345) ~[elasticsearch-java-8.9.0.jar:na]
	at co.elastic.clients.elasticsearch.core.search.ResponseBody.toString(ResponseBody.java:311) ~[elasticsearch-java-8.9.0.jar:na]
	at com.estrial.queries.CustomController.getQueryResponse(CustomController.java:18) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) ~[tomcat-embed-core-9.0.79.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.29.jar:5.3.29]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[tomcat-embed-core-9.0.79.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-9.0.79.jar:9.0.79]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar:5.3.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar:5.3.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.29.jar:5.3.29]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar:5.3.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.79.jar:9.0.79]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
	Suppressed: jakarta.json.stream.JsonGenerationException: Generating incomplete JSON
		at org.eclipse.parsson.JsonGeneratorImpl.close(JsonGeneratorImpl.java:519) ~[parsson-1.0.0.jar:na]
		at co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:407) ~[elasticsearch-java-8.9.0.jar:na]
		... 53 common frames omitted

### Steps to Reproduce

I have developed a small spring boot project to reproduce the issue. Attached here is the google drive link. 
Some useful curls:

1) For adding the data:

curl --location 'http://localhost:8080/indexValue' \
--header 'Content-Type: application/json' \
--data '{

    "sku":"bk-2",
    "name":"bikes",
    "price":45.2
}'

2) For running the aggregation query:

curl --location --request POST 'http://localhost:8080/getQueryResponse'

Google drive link for the project:

https://drive.google.com/file/d/1PtnRUCkaU709wH6WHEMJphJrYo8TwDYh/view?usp=drive_link

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
