### ISSUE TITLE
ESQL: Error when loading `text` fields from indexes with synthetic source

### ISSUE THREAD

**Issue by csoulios** [elastic/elasticsearch#99183]
ESQL loads `text` fields that are either stored in the index (having `"store": true` in the mapping) or by parsing the `_source` and extracting the text value.  Text fields support [synthetic _source](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html#synthetic-source) if one of the two requirements are met:

1. the text field sets  `"store": true`  in the mapping
1. they have a [keyword](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#keyword-synthetic-source) sub-field that supports synthetic _source 

In the latter case (when `text` field is not stored, but contains a `keyword` sub-field) querying for the `text` field returns an `IllegalArgumentException` with the following error message: `Cannot access source from scripts in synthetic mode`

### Steps to Reproduce

Run the following yaml test:

```yaml
---
"text with synthetic source":
  - do:
      indices.create:
        index: test2
        body:
          mappings:
            _source:
              mode: synthetic
            properties:
              "emp_no":
                type: long
              name:
                type: keyword
              job:
                type: text
                fields:
                  raw:
                    type: keyword

  - do:
      bulk:
        index: test2
        refresh: true
        body:
          - { "index": { } }
          - { "emp_no": 10, "name": "Jenny", "job": "IT Director" }
          - { "index": { } }
          - { "emp_no": 20, "name": "John", "job": "Payroll Specialist" }

  - do:
      esql.query:
        body:
          query: 'from test2 | sort emp_no | keep job'

  - match: { columns.0.name: "job" }
  - match: { columns.0.type: "text" }

  - length: { values: 2 }
  - match: { values.0.0: "IT Director" }
  - match: { values.1.0: "Payroll Specialist" }
```

Returns the following error: 

```
java.lang.IllegalArgumentException: Cannot access source from scripts in synthetic mode
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.query.SearchExecutionContext.lambda$lookup$2(SearchExecutionContext.java:400)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.search.lookup.SearchLookup.getSource(SearchLookup.java:144)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.fielddata.SourceValueFetcherSortedBinaryIndexFieldData$SourceValueFetcherSortedBinaryDocValues.advanceExact(SourceValueFetcherSortedBinaryIndexFieldData.java:113)
    at org.elasticsearch.compute.lucene.BlockDocValuesReader$BytesValuesReader.read(BlockDocValuesReader.java:525)
    at org.elasticsearch.compute.lucene.BlockDocValuesReader$BytesValuesReader.readValuesFromSingleDoc(BlockDocValuesReader.java:520)
    at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.loadFromManyLeaves(ValuesSourceReaderOperator.java:105)
    at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.process(ValuesSourceReaderOperator.java:89)
    at org.elasticsearch.compute.operator.AbstractPageMappingOperator.getOutput(AbstractPageMappingOperator.java:67)
    at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:163)
    at org.elasticsearch.compute.operator.Driver.run(Driver.java:115)
    at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:259)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by csoulios** [comment]
We have discussed at our team meeting that if a `text` field contains a `keyword` sub-field, we should load the sub-field as a performance optimization for faster loading. This bug makes it apparent that `keyword` sub-fields must be loaded, when available.

Loading the `keyword` sub-field can be implemented either at the planner level or at a lower level, where text fields are loaded. We have agreed that it is best to implement this functionality at the planner.

cc @costin, @nik9000

**Comment by astefan** [comment]
There are situations where the sub-field loading is not desired imo.
For example

```
{
  "job": {
    "type": "text",
    "fields": {
      "raw": {
        "type": "keyword",
        "ignore_above": 5
      }
  }
}
```

In this case the `keyword` subfield simply has no value in it, while the `text` field does.

**Comment by csoulios** [comment]
> In this case the `keyword` subfield simply has no value in it, while the `text` field does.

@astefan I agree with you, there are many cases where the keyword field will not exactly match the `text` field. Like you mention, a heavily truncated `keyword` field is useless. 

In this case, we should consider if the `keyword` field can return the payload of the `text` field. 

However, it should be noted that this convention is already used by [synthetic source feature for text fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html#text-synthetic-source):

>text fields support [synthetic _source](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html#synthetic-source) if they have a [keyword](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#keyword-synthetic-source) sub-field that supports synthetic _source ...

**Comment by costin** [comment]
>  We have agreed that it is best to implement this functionality at the planner.

After exploring this venue in #99390, it turns out to be not as straight forward. The main issue is that at extraction and translation time, the field name is used verbatim on the assumption that a FieldAttribute is mapped directly to its peer EsField.
However the same name is used when returning the response - essentially `job` and `job.raw` mean both there's an underlying field in ES with that name AND that's the name of the attribute inside QL.

We likely need to separate them so `job` QL attribute can point to `job.raw` ES field.
#99390 keeps the SQL approach of doing the replacement at query translation time. We would have to do something similar with field extraction.
