### ISSUE TITLE
[CI] org.elasticsearch.xpack.esql.CsvTests > test {string.In3VLWithNull} FAILED

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#99347]
### CI Link

https://gradle-enterprise.elastic.co/s/ulahz7lg2xmtq/console-log?task=:x-pack:plugin:esql:test

### Repro line

./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.CsvTests" -Dtests.method="test {string.In3VLWithNull}" -Dtests.seed=5B78DAC3CF0ABB27 -Dtests.locale=sr-BA -Dtests.timezone=Asia/Bangkok -Druntime.java=20	

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure history

N/A

### Failure excerpt

Sorry for the bare-hands failure report, HOMER isn't working for me right now.

```
org.elasticsearch.xpack.esql.CsvTests > classMethod FAILED	
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=428, name=elasticsearch[CsvTests][esql][T#2], state=RUNNABLE, group=TGRP-CsvTests]	
        Caused by:	
        java.lang.AssertionError	
            at __randomizedtesting.SeedInfo.seed([5B78DAC3CF0ABB27]:0)	
            at org.elasticsearch.compute.data.AbstractBlock.<init>(AbstractBlock.java:42)	
            at org.elasticsearch.compute.data.AbstractArrayBlock.<init>(AbstractArrayBlock.java:30)	
            at org.elasticsearch.compute.data.BooleanArrayBlock.<init>(BooleanArrayBlock.java:23)	
            at org.elasticsearch.xpack.esql.evaluator.predicate.operator.comparison.InMapper$InExpressionEvaluator.evalWithNulls(InMapper.java:109)	
            at org.elasticsearch.xpack.esql.evaluator.predicate.operator.comparison.InMapper$InExpressionEvaluator.eval(InMapper.java:71)	
            at org.elasticsearch.compute.operator.EvalOperator.process(EvalOperator.java:42)	
            at org.elasticsearch.compute.operator.AbstractPageMappingOperator.getOutput(AbstractPageMappingOperator.java:67)	
            at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:163)	
            at org.elasticsearch.compute.operator.Driver.run(Driver.java:115)	
            at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:259)	
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)	
            at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)	
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)	
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)	
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)	
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)	
            at java.base/java.lang.Thread.run(Thread.java:1623)	
```

**Comment by astefan** [comment]
Opened a bug fix. I mentioned ["partially fixes" in the PR](https://github.com/elastic/elasticsearch/pull/99382) because there is still the issue of the test suite timing out instead of finishing with an error.

**Comment by DaveCTurner** [comment]
I think the simplest way to fix the timeout issue is to move `org.elasticsearch.compute.operator.DriverRunner#runToCompletion(org.elasticsearch.threadpool.ThreadPool, int, java.util.List<org.elasticsearch.compute.operator.Driver>)` into the test suite (it's not called by any production code) and then add a timeout to the `.actionGet()`.

**Comment by dnhatn** [comment]
The timeout occurs because we don't catch Throwables but only Exceptions in AbstractRunnable, and the Driver threw a Throwable, leading to the listener in Driver#schedule never being notified. 

However, I don't think we should catch and rethrow Throwable in Driver. Let's add the timeout to DriverRunner#runToCompletion, as David suggested. I will raise a PR for this.

**Comment by dnhatn** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/99386 to remove `DriverRunner#runToCompletion`.
