### ISSUE TITLE
[CI] More multi_node.EsqlSpecIT failures

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#99466]
### CI Link

https://gradle-enterprise.elastic.co/s/kzhx4kcc6e3pw

### Repro line

`./gradlew ':x-pack:plugin:esql:qa:server:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" \   -Dtests.method="test {stats.ByStringAndLongWithAlias}" \   -Dtests.seed=9EEC253CF1741A06 \   -Dtests.locale=sv \   -Dtests.timezone=Africa/Bamako \   -Druntime.java=21`

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

```
12:02:38 REPRODUCE WITH: ./gradlew ':x-pack:plugin:esql:qa:server:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {stats.ByStringAndLong}" -Dtests.seed=9EEC253CF1741A06 -Dtests.locale=sv -Dtests.timezone=Africa/Bamako -Druntime.java=21
12:02:38 
12:02:38 org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT > test {stats.ByStringAndLong} FAILED
12:02:38     org.junit.ComparisonFailure: expected:<[2]00000000> but was:<[3]00000000>
12:02:38         at __randomizedtesting.SeedInfo.seed([9EEC253CF1741A06:16B81AE65F8877FE]:0)
12:02:38         at org.junit.Assert.assertEquals(Assert.java:115)
12:02:38         at org.junit.Assert.assertEquals(Assert.java:144)
12:02:38         at org.elasticsearch.xpack.esql.CsvAssert.assertData(CsvAssert.java:208)
12:02:38         at org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase.doTest(EsqlSpecTestCase.java:103)
12:02:38         at org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase.test(EsqlSpecTestCase.java:84)
12:02:38         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

**Comment by cbuescher** [comment]
Another one earlier today that failed in "stats.ByUnmentionedLongAndLong": https://gradle-enterprise.elastic.co/s/7rs2joz4kcweg
