### ISSUE TITLE
ESQL: assertion error when using to_version of a text field and sorting on any field

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#99475]
### Description

Test data:

```
{
  "mappings": {
    "properties": {
      "emp_no": {
        "type": "long"
      },
      "name": {
        "type": "keyword"
      },
      "job": {
        "type": "text",
        "fields": {
          "raw1": {
            "type": "keyword"
          },
          "raw2": {
            "type": "keyword",
            "ignore_above": 11
          }
        }
      },
      "tag": {
        "type": "text"
      }
    }
  }
}
```

```
{ "index": { } }
{ "emp_no": 10, "name": "Jenny", "job": "IT Director", "ip1": "127.0", "ip2": ".0.1" }
{ "index": { } }
{ "emp_no": 20, "name": "John", "job": "Payroll Specialist", "ip1": "127.0", "ip2": "0.1" }
{ "index": { } }
{ "emp_no": 30, "name": "John", "job": "Payroll Specialist" }
```

Query `FROM test | EVAL o = to_version(ip1) | sort name` fails with

```
[2023-09-12T14:58:41,622][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][esql_worker][T#22]], exiting java.lang.AssertionError
┬╗      at org.apache.lucene.core@9.7.0/org.apache.lucene.util.UnicodeUtil.UTF8toUTF16(UnicodeUtil.java:644)
┬╗      at org.apache.lucene.core@9.7.0/org.apache.lucene.util.BytesRef.utf8ToString(BytesRef.java:136)
┬╗      at org.elasticsearch.xpack.esql.action.EsqlQueryResponse.valueAt(EsqlQueryResponse.java:228)
┬╗      at org.elasticsearch.xpack.esql.action.EsqlQueryResponse.lambda$pagesToValues$13(EsqlQueryResponse.java:210)
┬╗      at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.collect.Iterators$IntRangeIterator.next(Iterators.java:152)
┬╗      at org.elasticsearch.xpack.esql.formatter.TextFormatter.<init>(TextFormatter.java:54)
┬╗      at org.elasticsearch.xpack.esql.formatter.TextFormat$1.format(TextFormat.java:42)
┬╗      at org.elasticsearch.xpack.esql.action.EsqlResponseListener.buildResponse(EsqlResponseListener.java:125)
┬╗      at org.elasticsearch.xpack.esql.action.EsqlResponseListener.buildResponse(EsqlResponseListener.java:33)
┬╗      at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:26)
┬╗      at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:38)
```

Could be related to TopN operator. Haven't dug into it.

**Comment by bpintea** [comment]
Seems it fails when generating the response (`EsqlQueryResponse.valueAt`).
Also seeing a `TextFormatter.java` in the stack, is this a `format=txt`?

**Comment by astefan** [comment]
> Seems it fails when generating the response (`EsqlQueryResponse.valueAt`). Also seeing a `TextFormatter.java` in the stack, is this a `format=txt`?

Yes

**Comment by nik9000** [comment]
Interesting! `Version` fields don't encode to valid utf-8. It's sort of janky and needs to be manually dereferenced and rendered.

**Comment by astefan** [comment]
Actually that bug doesn't reproduce anymore. Without the fix in https://github.com/elastic/elasticsearch/pull/99726 and, also, without https://github.com/elastic/elasticsearch/pull/99685.
