### ISSUE TITLE
ESQL: NPE when aggregating on literals

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#99751]
### Elasticsearch Version

main@b6747b48ba0901a530ba51375e3576fdb8df8527

### Java Version

openjdk version "17.0.8" 2023-07-18

### OS Version

Ubuntu 23.04

### Problem Description

`row a = 1 | stats max(1) by a` (or some other agg) results in:
```
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:556)
	at java.base/java.util.List.of(List.java:812)
	at org.elasticsearch.xpack.esql.planner.AbstractPhysicalOperationProviders.aggregatesToFactory(AbstractPhysicalOperationProviders.java:185)
	at org.elasticsearch.xpack.esql.planner.AbstractPhysicalOperationProviders.groupingPhysicalOperation(AbstractPhysicalOperationProviders.java:133)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planAggregation(LocalExecutionPlanner.java:207)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:158)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planAggregation(LocalExecutionPlanner.java:207)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:158)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planLimit(LocalExecutionPlanner.java:520)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:176)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planOutput(LocalExecutionPlanner.java:259)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:198)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:147)
	at org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:204)
	... 147 more
```

@nik9000 's thoughts on this: `I think this is just a kind of special case of "I can't EVAL in STATS". But it's a case the parser accepts.`

### Steps to Reproduce

Run the ESQL query from above.

**Comment by alex-spies** [comment]
I have a fix ready for the NPE itself. The verification of aggs was a bit off and allowed literals.

However, as for actually supporting expressions like `avg(1)` - this will require some work, so I'm going to open a separate issue for this.

**Comment by alex-spies** [comment]
Follow-up issue for the enhanced functionality created here: https://github.com/elastic/elasticsearch/issues/99828

**Comment by costin** [comment]
Superseded by https://github.com/elastic/elasticsearch/pull/99602

**Comment by alex-spies** [comment]
Looking at #99602 , it does not seem to make changes to the verifier in its current state, which is (ultimately) the culprit for this bug.

@costin , if that's fine with you, we can leave #99827 open for now and merge #99602 first; I can then re-check and make sure the updated verifier in #99827 still makes sense with the new support for `count(*)`; at least, we should merge the tests that #99827 adds to make sure we do not regress in the future.

**Comment by bpintea** [comment]
#99602 fixes this issue, but doesn't solve the problem of aggregating on literals (entirely, i.e. except count). 

@alex-spies I think we can close this one, but open a new one about [optimising the aggs away](https://github.com/elastic/elasticsearch/blob/c24cc0f54c216a5bff8e6b0e3ad2d09f7a3eb956/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/AbstractPhysicalOperationProviders.java#L242). Wdyt?

**Comment by alex-spies** [comment]
@bpintea I agree that we should open an issue on optimizing the aggs away.

However, this is still relevant, even though #99602 improved the current situation by giving a `EsqlIllegalArgumentException` instead of NPE (but still status 500 which is not so nice).

The verifier is still incorrect because it treats aggregation field + parameters the same; for instance, it forbids
```
from employees | stats p50 = percentile(salary_change, 25*2);
```
because `25*2` is not a literal.

**Comment by alex-spies** [comment]
Since #99602 fixes the NPE itself and it makes no fiddle with it in #99827, I'm closing this after all.
