### ISSUE TITLE
ESQL: KEEP after STATS trips assertion error

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#99782]
### Elasticsearch Version

main

### Java Version

_bundled_

### OS Version

all

### Problem Description

Do this

### Steps to Reproduce

```
rm /tmp/evil
for a in {0..9}; do
   for b in {0..9}; do
      echo '{"index": {}}' >> /tmp/evil
      echo '{"a": '$a', "b": '$b'}' >> /tmp/evil
   done
done
echo >> /tmp/evil

curl -uelastic:password -XDELETE localhost:9200/test
curl -HContent-Type:application/json -uelastic:password -XPUT localhost:9200/test
curl -HContent-Type:application/json -uelastic:password -XPOST localhost:9200/test/_bulk --data-binary @/tmp/evil
curl -HContent-Type:application/json -uelastic:password -XPOST localhost:9200/test/_forcemerge?max_num_segments=1
curl -HContent-Type:application/json -uelastic:password -XPOST localhost:9200/test/_refresh

curl -HContent-Type:application/json -uelastic:password -XPOST localhost:9200/_esql?pretty -d'{
   "query": "FROM test | STATS MAX(a) BY a, b | KEEP a"
}'
```

**Comment by astefan** [comment]
```
[2023-09-22T09:44:38,833][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][esql_worker][T#19]], exiting java.lang.AssertionError
┬╗      at org.elasticsearch.xpack.esql.formatter.TextFormatter.<init>(TextFormatter.java:56)
┬╗      at org.elasticsearch.xpack.esql.formatter.TextFormat$1.format(TextFormat.java:42)
┬╗      at org.elasticsearch.xpack.esql.action.EsqlResponseListener.buildResponse(EsqlResponseListener.java:125)
┬╗      at org.elasticsearch.xpack.esql.action.EsqlResponseListener.buildResponse(EsqlResponseListener.java:33)
```

**Comment by costin** [comment]
The issue is caused because the underlying aggregation does not perform any project and instead passes the page as is.
`STATS MAX(a) BY a, b | KEEP a` are combined to `AggregateExec[[a,b], [a])` meaning group by a, b and aggregate on a - that is return only a.
However the aggregation only takes care of the grouping and returns the underlying page as is without dropping the b block (like the `ProjectOperator`).
This causes issue at the response assembly which assumes the datatypes and the page have the same size (they don't) so it blows up when the datatype (which only exists for a) is looked for block b which exists in the page.
