### ISSUE TITLE
[CI] DebMetadataTests test05CheckLintian failing

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#99972]
**Build scan:**
https://gradle-enterprise.elastic.co/s/4d35xg7hj7i7m/tests/:qa:os:destructiveDistroTest.default-deb/org.elasticsearch.packaging.test.DebMetadataTests/test05CheckLintian

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DebMetadataTests&tests.test=test05CheckLintian

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c lintian --fail-on warning --suppress-tags malformed-override,mismatched-override /var/lib/jenkins/workspace/elastic+elasticsearch+main+multijob+packaging-tests-unix/os/ubuntu-22.04-packaging/distribution/packages/deb/build/distributions/elasticsearch-8.11.0-SNAPSHOT-amd64.deb]
   result: exitCode = [2] stdout = [W: elasticsearch: non-standard-dir-perm usr/share/elasticsearch/plugins/ 2755 != 0755
N: 419 hints overridden (209 errors, 158 warnings, 52 info); 5 unused overrides] stderr = [running with root privileges is not recommended!]

  at __randomizedtesting.SeedInfo.seed([A8EC813B7D4DB7A4:68121DD7C739D21F]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.test.DebMetadataTests.test05CheckLintian(DebMetadataTests.java:45)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by breskeby** [comment]
seems related to the gradle update https://github.com/elastic/elasticsearch/pull/97838 
I look into this. wondering why that hasn't been patched by our packaging tests we run for PRs
