### ISSUE TITLE
ProjectTests fails on some seed

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#99982]
### CI Link

local

### Repro line

./gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.operator.ProjectOperatorTests.testProjection" -Dtests.seed=91943554DA6E3559 -Dtests.locale=ar-SA -Dtests.timezone=Indian/Comoro -Druntime.java=21

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
  2> java.lang.AssertionError: java.lang.IllegalStateException: can't release already released block [IntVectorBlock[vector=ConstantIntVector[positions=3, value=0]]]
        at __randomizedtesting.SeedInfo.seed([91943554DA6E3559:69BE85F199AA9B5]:0)
        at org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:49)
        at org.elasticsearch.compute.data.Page.releaseBlocks(Page.java:224)
        at org.elasticsearch.compute.operator.ProjectOperatorTests.testProjection(ProjectOperatorTests.java:79)

        Caused by:
        java.lang.IllegalStateException: can't release already released block [IntVectorBlock[vector=ConstantIntVector[positions=3, value=0]]]
            at org.elasticsearch.compute.data.IntVectorBlock.close(IntVectorBlock.java:76)
            at org.elasticsearch.core.IOUtils.close(IOUtils.java:71)
            at org.elasticsearch.core.IOUtils.close(IOUtils.java:87)
            at org.elasticsearch.core.IOUtils.close(IOUtils.java:63)
            at org.elasticsearch.core.Releasables.close(Releasables.java:73)
            at org.elasticsearch.core.Releasables.close(Releasables.java:41)
            at org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:47)
            ... 2 more
```

I'm unsure if the test is generating sensible projection configurations. This may be an invalid thing.

**Comment by jakelandis** [comment]
Also failed in a PR build : https://gradle-enterprise.elastic.co/s/eylbtwkdrctq6/tests/task/:x-pack:plugin:esql:compute:test/details/org.elasticsearch.compute.operator.ProjectOperatorTests/testProjection?top-execution=1
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.operator.ProjectOperatorTests.testProjection" -Dtests.seed=D4C73589E0FAB04A -Dtests.locale=nb-NO -Dtests.timezone=America/Montevideo -Druntime.java=21 |  
```

**Comment by costin** [comment]
Should be fixed by https://github.com/elastic/elasticsearch/pull/100370
